### ISSUE TITLE
1028x720 image don't work but 512x512 crop works

### ISSUE THREAD

**Issue by harrywang** [Mikubill/sd-webui-controlnet#100]
my image is 1028x720. if I use 512x512 default, the result is good:

<img width="2553" alt="Screenshot 2023-02-16 at 9 25 12 AM" src="https://user-images.githubusercontent.com/595772/219395254-9bc12c42-1186-4b42-b850-06eb99820c7a.png">

however, when I changed to 1028x720 in both webui and controlnet menu, all other settings are the same, the result is not good:
<img width="2559" alt="Screenshot 2023-02-16 at 9 24 21 AM" src="https://user-images.githubusercontent.com/595772/219395505-15685ed2-0b43-401d-84f0-f435b5b4effa.png">

any suggestions?

Thanks!

**Comment by Mikubill** [comment]
Hmm, how about using higher resolution of canny preproc

**Comment by harrywang** [comment]
thanks for your reply but I don't know what you meant. This is my setting:

<img width="1267" alt="Screenshot 2023-02-16 at 10 16 46 AM" src="https://user-images.githubusercontent.com/595772/219407803-fff1d694-4844-4bb6-9c2a-2a95b0555145.png">

**Comment by Mikubill** [comment]
Update the plugin and you will find some new options. fyi: added in https://github.com/Mikubill/sd-webui-controlnet/commit/d09c520d40b68c3b980864ad96fc1455343f4a43

**Comment by harrywang** [comment]
Thanks, will do and report back.

**Comment by harrywang** [comment]
I just noticed that the slider bar is limited to 1024 (https://github.com/Mikubill/sd-webui-controlnet/issues/48), so I resized my image to 1024x567 and tried again before update the plugin - same result. Will update the plugin and try again.

**Comment by harrywang** [comment]
updated the plugin and max the resolution, the result is not good as well:
<img width="2523" alt="Screenshot 2023-02-16 at 10 41 27 AM" src="https://user-images.githubusercontent.co
<img width="1263" alt="Screenshot 2023-02-16 at 10 41 33 AM" src="https://user-images.githubusercontent.com/595772/219415315-ff978b1b-11bb-4e90-bddd-6ad31471fa44.png">
m/595772/219415300-934811c8-b31a-447e-a4c3-1541553ab324.png">

512x512 as a comparison after the updating:
<img width="2556" alt="Screenshot 2023-02-16 at 10 38 16 AM" src="https://user-images.githubusercontent.com/595772/219415427-6a91b1f9-a880-41a0-b693-a8cad81a5770.png">

**Comment by Mikubill** [comment]
you may need to alter some params such as prompts/negative prompts or denoiser/sampling method

**Comment by harrywang** [comment]
Thanks for the suggestion - what confused me is why 512x512 is much better with all other settings being the same - any pointers?

**Comment by harrywang** [comment]
manually cropped the image to 512x512 - out of box - the result is much better:
<img width="2543" alt="Screenshot 2023-02-16 at 11 08 21 AM" src="https://user-images.githubusercontent.com/595772/219422685-5d25ef49-7c9a-4519-b4e4-ea0162534644.png">

**Comment by Nazzaroth2** [comment]
you are using stock sd1.5 right? that model is trained only on 512px res images compared to any other merged model/trained model with aspect ratio bucketing. Maybe try another model from civit ai and see if other aspects work better?

**Comment by harrywang** [comment]
> you are using stock sd1.5 right? that model is trained only on 512px res images compared to any other merged model/trained model with aspect ratio bucketing. Maybe try another model from civit ai and see if other aspects work better?

Thanks a lot for pointing this out. Any suggested models that I should try?
