### ISSUE TITLE
[Bug]: Image loading error when i try to use ControlNet through API

### ISSUE THREAD

**Issue by alitan** [Mikubill/sd-webui-controlnet#1001]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Utilizing the webui through API. My code was working prior updating to >> 84d43539 (Sun Apr 23 22:14:23 2023)
Now i am getting an error when i use img2img and ControlNet.
I tried all the possible options with no luck.

### Steps to reproduce the problem

Here is my payload

payload_img2img = 
{
 "init_images": ""
 "prompt": "style of hans bellmer",
 "negative_prompt": "poorly drawn, childish",
 "steps": 20,
 "denoising_strength": 0.65,
 "seed": -1,
 "sampler_name": "DPM++ 2M Karras",
 "cfg_scale": 7.0,
 "width": 768,
 "height": 512,
 "restore_faces": true,
 "tiling": false,
 "alwayson_scripts": {
  "controlnet": {
   "args": [
    {
     "mask": "",
     "module": "depth_zoe",
     "model": "control_v11f1p_sd15_depth [cfd03158]",
     "weight": 1.0,
     "resize_mode": 1,
     "lowvram": false,
     "processor_res": 64,
     "threshold_a": 64,
     "threshold_b": 64,
     "guidance_start": 0.01,
     "guidance_end": 1.0,
     "guessmode": false,
     "input_image": ""
    }
   ]
  }
 }

### What should have happened?

It should work like the previous version. I am not sure if anything changed with the API.

### Commit where the problem happens

controlnet: API call

### Command Line Arguments

```Shell
No Browser, using it through API
```

### Console logs

```Shell
Error running process: F:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\modules\api\api.py", line 62, in decode_base64_to_image
    image = Image.open(BytesIO(base64.b64decode(encoding)))
  File "F:\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 3283, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x0000015A067BBE20>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "F:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 937, in process
    image = image_dict_from_any(unit.image)
  File "F:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 138, in image_dict_from_any
    image['image'] = external_code.to_base64_nparray(image['image'])
  File "F:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\external_code.py", line 96, in to_base64_nparray
    return np.array(api.decode_base64_to_image(encoding)).astype('uint8')
  File "F:\stable-diffusion-webui\modules\api\api.py", line 65, in decode_base64_to_image
    raise HTTPException(status_code=500, detail="Invalid encoded image")
fastapi.exceptions.HTTPException
```

**Comment by ljleb** [comment]
#995 fixes this.

**Comment by LLLYF** [comment]
Sry to bother there! When I try to use controlnet API the terminal shown that:
[ControlNet] warning: using deprecated '/controlnet/img2img' route
[ControlNet] warning: consider using the '/sdapi/v1/img2img' route with the 'alwayson_scripts' json property instead
Error running process: D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 661, in process
    unit = self.parse_remote_call(p, unit, idx)
  File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 573, in parse_remote_call
    unit.enabled = selector(p, "control_net_enabled", unit.enabled, idx, strict=True)
AttributeError: 'str' object has no attribute 'enabled'
I'm confuse about this problem, beacuse I was successful when I used img2img API .

**Comment by ljleb** [comment]
Please update and open a new issue if the problem persists.

**Comment by LLLYF** [comment]
> Please update and open a new issue if the problem persists. Most likely your webui version is also not up to date.

I got it
