### ISSUE TITLE
Preprocessor API parameters

### ISSUE THREAD

**Issue by alitan** [Mikubill/sd-webui-controlnet#1007]
Threshold A and B is not working for me for all the preprocessor options.
I know the API is really falling behind. What is the roadmap for exposing all the Preprocessor parameters for the API calls?

Thanks.

**Comment by ljleb** [comment]
Please the json request body you are using, it may help fix the issue.

**Comment by alitan** [comment]
Here it is.

payload_img2img =
{
"init_images": ""
"prompt": "style of hans bellmer",
"negative_prompt": "poorly drawn, childish",
"steps": 20,
"denoising_strength": 0.65,
"seed": -1,
"sampler_name": "DPM++ 2M Karras",
"cfg_scale": 7.0,
"width": 768,
"height": 512,
"restore_faces": true,
"tiling": false,
"alwayson_scripts": {
"controlnet": {
"args": [
{
"mask": "",
"module": "canny",
"model": "control_v11p_sd15_canny [d14c016b]",
"weight": 1.0,
"resize_mode": 1,
"lowvram": false,
"processor_res": 64,
"threshold_a":10,
"threshold_b": 20,
"guidance_start": 0.01,
"guidance_end": 1.0,
"guessmode": false,
"input_image": ""
}
]
}
}



I am getting no difference if i change threshold_a and threshold_b..
Are they working?

**Comment by ljleb** [comment]
If `preprocessor_res` is <= 64, it seems that we ignore thresholds. Is there a reason for this @lllyasviel ?

**Comment by ljleb** [comment]
If you raise the value of `preprocessor_res` above 64, you should see changes with respect to your thresholds. Can you confirm this @alitan ?

**Comment by lllyasviel** [comment]
i do not know, it is @Mikubill code

**Comment by alitan** [comment]
Yes, if i change the resolution (which i did 255) i can see the changes now.
Do you mind letting me know where this code is so that i can figure out what is actually going on here?
I guess @Mikubill did come up with a way to map the values based on the preprocessor value low and high limit.
Thank you!
