### ISSUE TITLE
[New Feature] Control Mode

### ISSUE THREAD

**Issue by lllyasviel** [Mikubill/sd-webui-controlnet#1011]
The Guess Mode will be revised into Control Mode since 1.1.09.

**Control Mode (previously called Guess Mode)**

We have fixed many bugs in previous 1.0’s Guess Mode and now it is called Control Mode

![image](https://user-images.githubusercontent.com/19834515/233897484-e84232f5-be3f-418b-bdaa-d9d7393f3988.png)

Now you can control which aspect is more important (your prompt or your ControlNet)

| Input (depth+canny+hed) | Control Mode: "Balanced" | Control Mode: "My prompt is more important" | Control Mode: "ControlNet is more important"
| --- | --- | --- | --- |
| ![image](https://user-images.githubusercontent.com/19834515/233898012-3b7f970e-a599-42b2-a56a-65899b816085.png) | ![image](https://user-images.githubusercontent.com/19834515/233897765-8ecf4ee7-a605-46fc-b124-57474c3d7575.png) | ![image](https://user-images.githubusercontent.com/19834515/233897802-6bf46513-9203-482b-8997-e889d578a381.png) | ![image](https://user-images.githubusercontent.com/19834515/233897826-54033ff3-3251-4a6a-bf4a-62f877cb6434.png) |

Now you can use the guess mode in a better and easier way (easier to understand what happened).

If you want to reproduce your previous results in "Guess Mode", you can always try "ControlNet is more important" and you should be able to get same results. If not, then try "My prompt is more important".

Note that you can 100% reproduce all previous results and nothing is removed.

**Comment by lllyasviel** [comment]
Balanced = turn off guess mode in previous 1.0

**Comment by aartikov** [comment]
@lllyasviel, is it different from "weight" option? 
I mean, it is looks like weight plays same role. High weight - "ControlNet is more important", low weight - "prompt is more important".

**Comment by Mikubill** [comment]
Great change! As a small addition, I think we can use more professional descriptions for the UI text (such as cfg_injection and soft_injection), and also add a "manual layer weight" option for professional users in future.

**Comment by lllyasviel** [comment]
Side note:

Because of a bug of @Mikubill 's previous 1.0 codes, if you were a user of previous ControlNet 1.0 and you use Guess Mode, then you have 50% chances that you are actually using "ControlNet is more important" and 50% chances that you are actually using "My prompt is more important".

In cn 1.1, since we must fix this bug, and we have to produce both of these two options so that all old users can reproduce previous results. 

If you previously use Guess Mode and you cannot find your previous "feeling" using "ControlNet is more important", then you can find your previous "feeling" using "My prompt is more important", and vice versa.

**Comment by topdeckg** [comment]
It now feels completely broken. It is impossible to get a result which matches the input. There is way too much variation. You've broken the animation possibilities.

**Comment by lllyasviel** [comment]
Some doc from readme:

"Balanced" = put ControlNet on both sides of cfg scale, same as turn off "Guess Mode" in ControlNet 1.0

"My prompt is more important" = put ControlNet on both sides of cfg scale and use progressively reduced SD U-Net injections (layer_weight*=0.825**I, where 0<=I <13, and the 13 means ControlNet injected SD 13 times). In this way, you can make sure that your prompts are perfectly displayed in your generated images.

"ControlNet is more important" = put ControlNet only on the Conditional Side (the cond in A1111's batch-cond-uncond). This means the ControlNet will be X times stronger if your cfg-scale is X. For example, if your cfg-scale is 7, then ControlNet is 7 times stronger. Note that here the X times stronger is different from "Control Weights" since your weights are not modified. This "stronger" effect usually has less artifacts and give ControlNet more space to guess what is missing from your prompts (and in 1.0, it is called "Guess Mode").

**Comment by Daxiongmao87** [comment]
Is this not supported in the API yet?
