### ISSUE TITLE
[Bug]: The check box does not work.

### ISSUE THREAD

**Issue by wkdtjs** [Mikubill/sd-webui-controlnet#1016]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

The slide and selection window work fine, but the check box options do not work.

### Steps to reproduce the problem

1. Click the check box.
2. After pressing the Apply button, do restart.
3. It doesn't apply.

### What should have happened?

It should work properly when the check box is pressed.

### Commit where the problem happens

vladmandic/automatic: 98adfb3151575f1020ecda509956ed9bef30ea86
controlnet:  cb288a27cb1385b79a9fce98853aa8c9e2db13d1

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
The log does not exist.
```

### Additional information

It worked normally about 12 hours ago.

**Comment by ghpkishore** [comment]
Can you give more information. I didnt understand what you mean by this? What checkbox are you talking about?

**Comment by wkdtjs** [comment]
The controlnet setting is not working.

**Comment by ghpkishore** [comment]
Do you mean these?

<img width="1321" alt="Screenshot 2023-04-24 at 11 28 28 AM" src="https://user-images.githubusercontent.com/26677859/233911491-5e5c2b86-7efc-4a98-961d-b884e8d64ca2.png">

**Comment by wkdtjs** [comment]
Yes, that's it

**Comment by ghpkishore** [comment]
It is working for me. Ensure that you update the controlnet webui and restart the terminal. Close the terminal and restart it. In the  controlnet UI you should see **ControlNet v1.1.101**
<img width="734" alt="Screenshot 2023-04-24 at 11 30 31 AM" src="https://user-images.githubusercontent.com/26677859/233911767-10c5ac6a-d10a-4532-8192-d78d8c52d5af.png">

**Comment by wkdtjs** [comment]
![화면 캡처 2023-04-24 150358](https://user-images.githubusercontent.com/65364921/233912400-c17b1874-9320-4070-99fd-c563e41a2648.png)
And I'm using a version modified by a person named vladmandic.

**Comment by ghpkishore** [comment]
Oh I wouldnt be able to help then. Maybe raise a issue in that. Because it seems to be working here. Might be an integration error over there. I dont think the issue is here. Would suggest closing it here and asking there.

**Comment by wkdtjs** [comment]
All right.
