### ISSUE TITLE
[Bug]: "Do not append detectmap to output" no longer respected

### ISSUE THREAD

**Issue by LonicaMewinsky** [Mikubill/sd-webui-controlnet#1019]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

After recent significant (awesome!) updates, not sure which, ControlNet no longer respects the "Do not append detectmap to output" option:
![image](https://user-images.githubusercontent.com/93007558/234009451-f657a086-a9c5-4b27-b9b8-c979ee7b28f9.png)
![image](https://user-images.githubusercontent.com/93007558/234010348-e013a9f8-9cea-4b3c-becc-f807bf6c1988.png)

I imagine this is just a nuisance for most use cases, but for other extensions, it creates a scenario where processing returns more images than the desired batch count.

### Steps to reproduce the problem

1. Toggle on "Do not append detectmap to output"
2. Save settings
3. Perform generation with ControlNet enabled
4. Observe appended detectmap despite toggle

### What should have happened?

Detectmap should not have been appended to output.

### Commit where the problem happens

webui: [22bcc7b](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/22bcc7be428c94e9408f589966c2040187245d81)
controlnet: [c598467](https://github.com/Mikubill/sd-webui-controlnet/commit/c5984671ccd7da7d554f239143648b8157ae1c39)

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
--opt-sdp-no-mem-attention
```

### Console logs

```Shell
> Loading model: control_openpose-fp16 [9ca67cc5]
Loaded state_dict from [myrootpath\stable-diffusion-webui\extensions\sd-webui-controlnet\models\control_openpose-fp16.safetensors]
Loading config: myrootpath\stable-diffusion-webui\extensions\sd-webui-controlnet\models\cldm_v15.yaml
ControlNet model control_openpose-fp16 [9ca67cc5] loaded.
Loading preprocessor: openpose
preprocessor resolution = 512
ControlNet preprocessor location: myrootpath\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:01<00:00,  8.37it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 16/16 [00:01<00:00,  8.40it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 16/16 [00:01<00:00, 11.57it/s]
```

**Comment by ljleb** [comment]
#683 is responsible. Working on it.
