### ISSUE TITLE
deforum controlnet doesnt work for me :(

### ISSUE THREAD

**Issue by PurpleVibe** [Mikubill/sd-webui-controlnet#1022]
first i had an error caused by two shot and additional networks extension  making control net not working at all.
i deleted those soo the error wont pop out.
now it suppose to work, i the control net folder with the input inside the deforum video folder. 
but the control net doesnt change anything (txt2img does work).
important to add im using an colab notebook : https://colab.research.google.com/github/camenduru/stable-diffusion-webui-colab/blob/main/stable/dreamshaper_webui_colab.ipynb
thats the first input frame:
![image](https://user-images.githubusercontent.com/92512783/234073185-29a27d06-8bf5-4ca4-8352-cd6717ff6270.png)
first output frame:
![image](https://user-images.githubusercontent.com/92512783/234073271-68526352-02ec-4fc7-ac5f-e0a5439309d2.png)
soo youll see what i mean, idk where the bug from

**Comment by PurpleVibe** [comment]
![image](https://user-images.githubusercontent.com/92512783/234073475-2a7409c2-4657-44d7-91d7-b7f37c765538.png)
the settings used

**Comment by lllyasviel** [comment]
https://github.com/Mikubill/sd-webui-controlnet/issues/1027

**Comment by hithereai** [comment]
That user used an unknown colab webui repository with unknown versions for the protocol. 

Deforum only supports the last Ben webui colab, latest version of it.
