### ISSUE TITLE
[Vlad/Deforum] If you have problems with Vlad/Deforum

### ISSUE THREAD

**Issue by lllyasviel** [Mikubill/sd-webui-controlnet#1027]
Multiple users reported issues about Deforum and here is the guidelines:

1. After updating ControlNets, have you restarted your terminal (not only A1111)? Can you see "ControlNet v1.1.106"?
If no, then it is your problem. Please restart completely and problems will be fixed. Please do not open issue in ControlNet.
If yes, see 2.

2. Is ControlNet working in txt2img or img2img?
If no, then it is ControlNet's problem, you may open an issue in ControlNet and let us know.
If yes, then ControlNet has no problem,  go to 3

3. Can you use Deform?
If yes, everything ok.
If no, based on your previous anwser in (2), you have already know that ControlNet has no problem. Also, according to Deforum's comment below, it seems that Deforum also has no problem. So it seems that if you still have problems, it may be related to Vlad (check if you are using Vlad). If this is Vlad’s problem, then you should open issue in Vlad (or not, because there is one already: https://github.com/vladmandic/automatic/issues/326). Edit: it seems that Vlad posted the fix below.

Update:

Please do not use previous version of ControlNets because Deforum has used updated supports.

**Comment by hithereai** [comment]
Deforum supports the latest cn extension 1000%. I test and update whatever needed daily.

It just won't work on vlad webui, it's in vlad side to fix.

Other than that I don't know of any cn deforum related issues honestly.

**Comment by hithereai** [comment]
Also @lllyasviel please remove the last part - as deforum won't work with earlier versions of CN. We have to be aligned with your latest version as we do our own custom UI inside Deforum - we do not use your UI like all the other extens.

**Comment by vladmandic** [comment]
FYI, I'm not experienced with ControlNet+Deforum workflows, but I've just posted a fix for my repo. Let me know if there are remaining problems.

**Comment by hithereai** [comment]
While it stopped yielding CLI errors, it doesn't work. ControlNet doesn't really do anything, and I get no preproc auto-saves as proof. 

It works perfectly on webui, so I wonder what's the issue, as I see no errors or anything in the CLI. Will have to dig deeper, but not sure I can figure it out alone.

**Comment by lllyasviel** [comment]
ControlNet 1.1 begin to use batch counter to decide whether each instance is cond or uncond. Perhaps related to --always-cond-uncond

**Comment by hithereai** [comment]
Running the exact same setting file in Webui and your fork:

Webui result (look like my canny input):
![image](https://user-images.githubusercontent.com/121192995/234451769-1150e3b4-817f-44d2-8ad1-db242447b3a1.png)

Your fork result:
![image](https://user-images.githubusercontent.com/121192995/234451726-0b1bf0c8-1984-4004-83af-a0faa3d5ac40.png)

**Comment by vladmandic** [comment]
OK, it's a priority for tomorrow...

**Comment by lllyasviel** [comment]
i give a fresh install of vlad and it seems work. not sure what is wrong
![image](https://user-images.githubusercontent.com/19834515/234459150-7464de21-6419-4add-b59c-612b972eab38.png)
![image](https://user-images.githubusercontent.com/19834515/234459203-5469c347-78c1-441c-a3f5-9c7c492f49b0.png)

by the way the UI is quite different and some samplers can not be found

**Comment by ljleb** [comment]
You have to enable the samplers in the settings, by default most samplers are disabled in vlad's fork.

**Comment by lllyasviel** [comment]
Why some people consider UniPC better. In acdemic usually consider Eluer A as SOTA.

**Comment by vladmandic** [comment]
> Why some people consider UniPC better. In acdemic usually consider Eluer A as SOTA.

@lllyasviel faster and requires 1/2 steps to get to decent results, not necessarily better. I wouldn't consider Euler A is as SOTA, but its by far better than original DDIM/PLMS which were the only ones available in original SD implementation. Its just that Euler ancestral came shortly after and silently became a standard as it "just works".

**Comment by hithereai** [comment]
For some reason when I run deforum with CN, CN just doesn't get enabled at all. Not sure why.

**Comment by hithereai** [comment]
Yeah I see it's only the combo. What differences do you have compared to auto1111 in regards to always on scripts then? What should I look for? I always worked on a1111, never had any related issue, so not sure where to look.

**Comment by vladmandic** [comment]
you can see in `modules/scripts.py:process()` `p.script_args` is not valid args.
i'm trying to trace it back where it was set.
what's different? to start with, extension/script loader is totally different, for example `list_scripts()`

**Comment by hithereai** [comment]
@vladmandic when I commented `p.scripts = scripts.scripts_img2img if is_img2img else scripts.scripts_txt2img`, CN isn't working on a1111. Let me test it on your repo now.

**Comment by vladmandic** [comment]
@hithereai not surprised. the line is needed, but you need to append to list to add controlnet instead of overwritting entire list.

**Comment by hithereai** [comment]
@vladmandic I see. Yeah it doesn't work without that line on your either. I'm not sure how to actually do what you ask, but will try.

**Comment by vladmandic** [comment]
i'll update here, give me an hour.

**Comment by vladmandic** [comment]
i'm having exactly the same issue with original A1111 as soon as i install additional extensions that register as always-on scripts.
it works on vanilla a1111 because there are none and in my repo there are some extensions pre-installed.
logic how deforum triggers controlnet is by going back to main and let it trigger script.process(). why not trigger controlnet directly?
anyhow, i'm not giving up just yet.

**Comment by vladmandic** [comment]
> wdym trigger cn directly? we have our custom UI and use the external api of CN

if you were calling CN directly from Deforum, you wouldn't need this:

```python
p.script_args = {"enabled": True} 
```

and that line overwrites script_args for **ALL** always-on scripts indiscriminately
but like you said, if that is NOT set, then CN does not get triggered - which means, its not Deforum that is triggering it at all, its core repo and you just asked it to be enabled (but in a bad way).

**Comment by lllyasviel** [comment]
i am not familiar with api but do cn need to do anything? or will other extensions fail cn if they have some script_args ?

**Comment by hithereai** [comment]
> > wdym trigger cn directly? we have our custom UI and use the external api of CN
> 
> if you were calling CN directly from Deforum, you wouldn't need this:
> 
> ```python
> p.script_args = {"enabled": True} 
> ```
> 
> and that line overwrites script_args for **ALL** always-on scripts indiscriminately but like you said, if that is NOT set, then CN does not get triggered - which means, its not Deforum that is triggering it at all, its core repo and you just asked it to be enabled (but in a bad way).

Honestly I'm not sure how I'm supposed to call CN "directly". I just followed their API, maybe not 1:1 so it's on me.

I'd like to make it work, but at this stage I simply do not understand what I need to do to make that happen.

**Comment by ljleb** [comment]
Why do you need this line in https://github.com/deforum-art/deforum-for-automatic1111-webui/blob/b55b95008e4f8531f094f84a772d6c3ed27d38cb/scripts/deforum_helpers/deforum_controlnet.py#L191 ?

```
p.script_args = {"enabled": True} 
```

Except fort this line, you are calling the API properly. Maybe should consider removing the last 2 kwargs but otherwise it looks okay.

Does it stop working if you remove the scripts args assignment? IIUC the scripts args list should really not be replaced with an almost empty dict.

**Comment by vladmandic** [comment]
if that line is removed, deforum+cn doesn't do anything anymore, error is `Error: 'NoneType' object is not subscriptable.`, but its caught&ignored somewhere, trying to find out where exactly does that even triggered from.

**Comment by kabachuha** [comment]
@vladmandic set p.script_args = {} 

Or else it appends args to None dictionary

**Comment by vladmandic** [comment]
@kabachuha yeah, but p.script_args = None is a valid value and extension should not break because some other extension has empty script_args.

**Comment by ljleb** [comment]
Found the offending line. If script_args is `None` then it will crash here:

https://github.com/Mikubill/sd-webui-controlnet/blob/93b0f9e1b7cc246165666b7b307bc8243db2c3f4/scripts/external_code.py#L238

the external code api expects a list, not none.

**Comment by ljleb** [comment]
should we change the code to ignore script args when they are none? or fill them on our side instead mabye. I'd think the list should not really be `None` in `process` callbacks for any extension. Deforum should create the list before passing it to controlnet to ensure all alwayson scripts present in the script runner will work properly.

**Comment by kabachuha** [comment]
Why do we need an own script runner if img2img is used almost everywhere in Deforum?

And then, people will ask why Deforum doesn't support those 'extra' scripts

I think something is wrong with the initialization, since they *must* chain well

After all, the only thing Deforum's using in Auto directly is the img2img pipeline

**Comment by vladmandic** [comment]
the existing txt2img and img2img script runner pipelines will still trigger as-is.
the point is that you're trying to manually modify existing pipeline and that causes problems. so instead of that, have a separate pipeline for deforum->controlnet.

**Comment by ljleb** [comment]
> if thats the case, you can create your own script runner and trigger it manually instead on relying on

I think this is a good point. Maybe we could do something similar to what the web API does, i.e. add all alwayson scripts that do not have any parameters? I think users could want (or expect in some cases?) some of the alwayson scripts to be active. For example, a script that reformats prompts from `process` could (should?) be active even when generation is initiated from the deforum extension.

**Comment by vladmandic** [comment]
anything thats already registered in txt2txt or img2img script runners will "just work", you don't need to search for them or trigger them. whole point is to add controlnet to separate script runner inside deforum and trigger it when you want.

**Comment by ljleb** [comment]
Yes sorry if I wasn't clear. I meant to only add these scripts to a separate script runner, and initialize this script runner's alwayson args to `[]`.

**Comment by ljleb** [comment]
And then IIUC it should work with the controlnet external code api.

**Comment by ljleb** [comment]
Although, even with alwayson scripts that do not take any argument, to add a controlnet script to the script runner, deforum might have to manually set `cn_script.args_from` and `args_to`. Maybe it just needs a call to `ScriptRunner.setup_ui`?

In any case, it definitely needs a separate instance of a controlnet script, so that the args position for the existing txt2img and img2img are not updated by mistake, and so that the state of any controlnet script stays valid.

I'm not saying this is a bad idea, just that it seems tedious to ask for every extension maintainer to do this. At least, the way to set up a custom generation tab in an extension should be documented somewhere if it isn't trivial.

**Comment by vladmandic** [comment]
actually, i think most of that stuff can be bypassed - you don't even need a full runner like txt2img or img2img, registering a script should be suffficient:

something like
```python
script = scripts.ScriptClassData(script_class=constructor, path=path, basedir=basedir, module=module)
```
and the trigger it when you want using
```python
script.process(script_args)
```

**Comment by ljleb** [comment]
One problem with this approach is that it is somewhat tedious. Extensions will need to also call postprocess, process_batch and postprocess_batch, which take additional parameters in some cases, i.e. the processed images for postprocess_batch as you can see here:

https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/22bcc7be428c94e9408f589966c2040187245d81/modules/processing.py#L670

So it is even more error prone to do it this way. Additionally, if deforum only calls the script members that are used by controlnet right now, it may prevent controlnet from using other members without breaking the interaction between the two extensions. It does not scale as well as using a custom script runner IIUC. Unless there is something in the webui that would allow to avoid these potential issues?

**Comment by vladmandic** [comment]
those are all valid points. and i'd love to redesign script loading/initialization and in general behavior of script runners, but that would only lead to bigger incompatibilities between my repo and a1111, so i'm trying to come up with a solution that works right now for deforum+controlnet. yes, it doesn't scale, its just what i think is cleanest to enable deforum+controlnet as it is today. but if you have other approach in mind - i'm totally for it, whatever it takes.

**Comment by ljleb** [comment]
Tbh it's good that we are considering multiple options. IIUC there is not really a perfect solution in this case, because the main repo all of these extensions rely on is relatively stale at the moment.

I think the solution that is the easiest to write and maintain on the extensions side may be the best, as there are n extensions VS 2 webui hosts. This plus the fact that as long as a1111 webui is stale we can't update the scripts API in place, makes me think we should go with using a script runner in this case, whether txt2img, img2img or custom.

Here's another approach, in case it wasn't considered. We could extend the scripts module with optional features on your fork. Then we can expose which features are available and which aren't. If some features are not available, extensions can fallback to hacky solutions.

In the case of deforum, this would mean looking for a feature (i.e. a function) that creates a script runner, or something else that requires a similar amount of effort. (i.e. ideally a one liner or close to one line, allowlisting which alwayson scripts we want if we dont want them all) Then, if this function is not available, deforum can fallback to the hack of reusing the txt2img or img2img script runners.

This solution has a number of drawbacks IIUC: it could lead to extensions being even more complex in the end, as they would have to maintain 2 versions of the same API. Also, it wouldn't really provide a good solution for a1111 users. It seems to me that the previous suggestions scale better anyway, but I wanted to leave this here in case it could be food for thought.

**Comment by hithereai** [comment]
@ljleb where can we talk about masks in the external API? I don't really understand if/ how they work, as pre-processor never loads when I pass 'mask' in addition to 'image'. This is *not* related to Vlad's webui.

**Comment by ljleb** [comment]
I have not tested them personally, but I know we are mostly just forwarding the api masks to the corresponding key in the gradio image dict... so I would expect them to have the same behavior as in the gradio interface if both an image and a mask is passed to the api:

https://github.com/Mikubill/sd-webui-controlnet/blob/2bc4400011b38ab7f1d3f27a95897a6cb0c28c2a/scripts/external_code.py#L205-L210

**Comment by hithereai** [comment]
(From an issue I was about to open, feel free to delete and move to a discussion or whatever):

When I pass both 'image' and 'mask', even when `Allow detectmap auto saving` is enabled, I get no output detected maps at all. --->>

Actually - I see this in the CLI when I use masks (note the None preproc):
![image](https://user-images.githubusercontent.com/121192995/234946346-68b889a7-4c77-41d2-8f8c-1d6c57ebaedc.png)

And this is how it looks when I don't a mask:
![image](https://user-images.githubusercontent.com/121192995/234946627-0039f87e-66b5-442d-9331-69d96b0d611c.png)

My main input frame:
![000000001](https://user-images.githubusercontent.com/121192995/234947323-bba48fb4-375f-4af6-8a40-bfa36acea9dc.jpg)

My mask frame:
![000000001](https://user-images.githubusercontent.com/121192995/234947392-d5dbb566-5f42-4745-8d46-980d51c2ab7f.jpg)

Result without mask (it's good):
![20230427204023_000000000](https://user-images.githubusercontent.com/121192995/234947140-8d77075f-e2d8-462c-acb2-680b9113cd4b.png)

Result with mask:
![20230427204035_000000000](https://user-images.githubusercontent.com/121192995/234947716-4623d694-9c41-4755-951b-a5b67e179b60.png)

**Comment by ljleb** [comment]
I can take a look later this week if you want... I'm not really available at the moment. If you could open an issue with this, I'll take a look in about a week if no one else looks into it.

**Comment by hithereai** [comment]
@vladmandic so what have we decided on here?

**Comment by vladmandic** [comment]
i've implemented additional per-script arguments (`p.per_script_args` object) in my repo and i've left existing behavior as fallback for backward-compatibiliy (no matter how broken it is).
so for all script callbacks, my code now checks:
```
args = p.per_script_args.get(script.title(), p.script_args[script.args_from:script.args_to])
```

which means you don't need to set `p.script_args = {"enabled": True}` as you do (or you can, for backward compatibility), you can set your private args without worrying about order of params or overwritting some other params.

btw, i've switched script handling when using `/sdapi` api to this and it fixed tons of problems when using scripts that way.
