### ISSUE TITLE
generate black pic

### ISSUE THREAD

**Issue by Timlou36** [Mikubill/sd-webui-controlnet#1045]
![image](https://user-images.githubusercontent.com/75685088/234474852-43723b06-7da4-4a6e-a7fe-d47d45db86a9.png)
hi, I'm fresh. i don't know why my generate pic is black by using controlnet

**Comment by lllyasviel** [comment]
log please

**Comment by Timlou36** [comment]
> log please
Thank u!
[AddNet] Updating model hashes...

ControlNet v1.1.107
ControlNet v1.1.107
Loading weights [9aba26abdf] from D:\sd-webui-aki-v4\models\Stable-diffusion\Deliberate_V2.safetensors
Creating model from config: D:\sd-webui-aki-v4\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(1): EasyNegative
Model loaded in 1.9s (load weights from disk: 0.2s, create model: 0.4s, apply weights to model: 0.5s, apply half(): 0.7s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 10.4s (import torch: 1.8s, import gradio: 1.2s, import ldm: 0.5s, other imports: 1.1s, load scripts: 1.8s, load SD checkpoint: 2.1s, create ui: 1.5s, gradio launch: 0.3s).

Loading model: control_v11p_sd15s2_lineart_anime [3825e83e]
Loaded state_dict from [D:\sd-webui-aki-v4\extensions\sd-webui-controlnet\models\control_v11p_sd15s2_lineart_anime.pth]
Loading config: D:\sd-webui-aki-v4\extensions\sd-webui-controlnet\models\control_v11p_sd15s2_lineart_anime.yaml
ControlNet model control_v11p_sd15s2_lineart_anime [3825e83e] loaded.
Loading preprocessor: invert
preprocessor resolution = 512

**Comment by lllyasviel** [comment]
try use edge or chrome
