### ISSUE TITLE
[Feature request] MangaLineExtraction

### ISSUE THREAD

**Issue by bropines** [Mikubill/sd-webui-controlnet#1046]
Control net has a great dislike for screentone. This is especially evident in this example of mine.
https://github.com/Mikubill/sd-webui-controlnet/issues/736#issuecomment-1519456863
Can you or someone adapt [MangaLineExtraction_PyTorch](https://github.com/ljsabc/MangaLineExtraction_PyTorch) as an anotator, and add it to the list of available anotators?

**Comment by bropines** [comment]
Here is a comparison:

### Without MangaLines:
| Original | Preprocessor | Final |
|----------|--------------|-------|
|  ![08](https://user-images.githubusercontent.com/57861007/233916645-8d3e60c0-b6dc-49cf-8868-5159eef6a47d.png)  |   ![image](https://user-images.githubusercontent.com/57861007/233915531-71459bfa-956c-450a-ba32-8e83687b5ef1.png)           |   ![image](https://user-images.githubusercontent.com/57861007/233915537-56d4114a-c8a0-4589-a3e0-234f842f64eb.png)   |





### MangaLines:

| **Original**                                                                                                  | **Extract manga lines**                                                                                         | **Preprocessor**                                                                                                | **Final**                                                                                                       |
|---------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------|
| ![08](https://user-images.githubusercontent.com/57861007/233916645-8d3e60c0-b6dc-49cf-8868-5159eef6a47d.png)  | ![image](https://user-images.githubusercontent.com/57861007/234507978-3ef97f26-18f3-49f6-a244-f0b8a75b6d1d.png) | ![image](https://user-images.githubusercontent.com/57861007/234507848-0c38328b-2683-43c6-acbf-276b550e66db.png) | ![image](https://user-images.githubusercontent.com/57861007/234507637-86b405be-cecf-4559-b4b4-beca4dd579be.png) |

**Comment by Arron17** [comment]
@bropines I've just put through a Pull Request to get this added, it likely needs a bit of a code tidy up, but it seems to work if you want to try it out.

**Comment by bropines** [comment]
> @bropines I've just put through a Pull Request to get this added, it likely needs a bit of a code tidy up, but it seems to work if you want to try it out.

I'll give it a try, thank you.
