### ISSUE TITLE
[Feature Request]: Generate and save all preprocessor preview

### ISSUE THREAD

**Issue by mykeehu** [Mikubill/sd-webui-controlnet#1048]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I would like to have a way to create all preprocessor preview images based on an image with a specific name, location and the name of the preprocessor as suffix. For example: image_name-preprocessor_name.png 

That would be good, because openpose is not the best for everything, and if I have a set, I don't need the image later. Now I have to create all preprocessor preview images as single images and save them. This could either be done in a separate tab (like batch) or just a button to "Save all preprocessor preview" and the folder location.

### Steps to reproduce the problem

Now:
1. Open an image
2. Turn on Allow Preview
3. Select Preprocessor
4. Click Run preprocessor button
5. Right click preview and Save as...

After:
1. Open an image
2. Select a folder for save
3. Click on "Save all preprocessor preview"

### What should have happened?

Inconvenient to save preprocessor images one by one

### Commit where the problem happens

webui: [22bcc7be](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/22bcc7be428c94e9408f589966c2040187245d81)
controlnet: 1.1.112

### Command Line Arguments

```Shell
--xformers --autolaunch --skip-version-check
```

### Console logs

```Shell
nothing
```

**Comment by ljleb** [comment]
Should be relatively straightforward to do with a script for now.

In the long run, we could allow to select multiple preprocessors by adding a postprocess script for preprocessors. This would make it possible to run preprocessors in extras.

**Comment by h0kay** [comment]
Landed on here from a google search but.. after updating controlnet to 1.1, where did the button go to generate the preview for the preprocessor? The only way I've been able to see it is by actually generating an image first.

**Comment by Pickles726** [comment]
> > Landed on here from a google search but.. after updating controlnet to 1.1, where did the button go to generate the preview for the preprocessor? The only way I've been able to see it is by actually generating an image first.
> 
> Same question here.

You should be able to generate a preview by checking "Allow Preview" and then clicking on the tiny explosion icon inbetween the preprocessor and the model.
![image](https://user-images.githubusercontent.com/30604149/235501533-2f0da3c3-d181-4569-86f4-41581d28fa33.png)

**Comment by mykeehu** [comment]
Is it already done? Where and how to use the generation of ALL preprocessors to a picture?

**Comment by igorleo10** [comment]
did you find an answer? i have the same problem

**Comment by mykeehu** [comment]
No, unfortunately @lllyasviel has closed the topic, but it would have been nice to have a feature like this to generate a preview image of the selected or all models.
