### ISSUE TITLE
ModuleNotFoundError: No module named 'modules.ui_components'

### ISSUE THREAD

**Issue by chasebethay** [Mikubill/sd-webui-controlnet#105]
Hi kind strangers of the internet, I get the following error but applying and refreshing the extension, as well as on startup:

Error loading script: controlnet.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui-master\modules\scripts.py", line 170, in load_scripts
    exec(compiled, module.__dict__)
  File "C:\stable-diffusion-webui-master\extensions\sd-webui-controlnet\scripts\controlnet.py", line 17, in <module>
    from modules.ui_components import ToolButton
ModuleNotFoundError: No module named 'modules.ui_components'

I read online [here](https://www.reddit.com/r/StableDiffusion/comments/111dk11/controlnet_for_automatic1111_is_here/) that a potential fix in the meantime is to use an older model. Does anyone know of a fix for this?

Thanks,

**Comment by Mikubill** [comment]
You might need to update your webui. fyi: ToolButton introduced in https://github.com/Mikubill/sd-webui-controlnet/pull/83

**Comment by chasebethay** [comment]
Thank you for your extremely quick reply, and for all the hard work you've put into ControlNet webui.

> You might need to update your webui. fyi: ToolButton introduced in https://github.com/Mikubill/sd-webui-controlnet/pull/83

here you are referencing AUTO1111 webui or your sd-webui-controlnet? thank u for helping the technologically illiterate <3
