### ISSUE TITLE
[Bug]: the /controlnet/txt2img api

### ISSUE THREAD

**Issue by yuan199696** [Mikubill/sd-webui-controlnet#1053]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

webui提供的 /controlnet/txt2img 接口参数 与webui界面的controlnet扩展参数不同：
1. 接口参数"guidance_start"  与 "Starting Control Step"是同一个参数吗？
2. 接口参数"guidance_end" 与 "Ending Control Step"是同一个参数吗？
3. 接口参数"guessmode" 是boolean类型，但是在contrlnet界面中是 "Control Mode (Guess Mode)" ，并且带着三个选项，这个参数如何在/controlnet/txt2img接口中兼容？

### Steps to reproduce the problem

请问作者是否会考虑更新/controlnet/txt2img接口，以此来适配新版的controlnet？

### What should have happened?

/controlnet/txt2img接口参数应该和controlnet界面参数对应

### Commit where the problem happens

webui: /controlnet/txt2img
controlnet: 界面参数

### Command Line Arguments

```Shell
--api
```

### Console logs

```Shell
No
```

**Comment by rockhward** [comment]
> * guidance_start"  与 "Starting Control Step"是同一个参数吗？
> * 接口参数"guidance_end" 与 "Ending Control Step"

After my own testing,
guidance_start and Starting Control Step
guidance_end and Ending Control Step
This is corresponding, but the effect is different. It should be a bug.
For example, I set Starting Control Step 0.5 Ending Control Step 1 in webui, and set guidance_end and Ending Control Step with the same values. When the seed is locked, the image that comes out is completely different.
