### ISSUE TITLE
[Bug]: ControlNet settings are being ignored by txt2img API

### ISSUE THREAD

**Issue by marcos-acosta** [Mikubill/sd-webui-controlnet#1062]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I would like to run `txt2img` with ControlNet settings to use canny edge detection as guidance. This works fine on the UI, but when I try to achieve the same thing via the API, the ControlNet input image seems to be ignored.

I am running the UI using (sd-webui-controlnet)[https://github.com/Mikubill/sd-webui-controlnet], cloned today
I am sending the request in Python via the `requests` module.

Code:
```
STABLE_DIFFUSION_URL = "https://a3f8774e-24c8-468c.gradio.live/"
TEXT2IMG_ENDPOINT = f"{STABLE_DIFFUSION_URL}sdapi/v1/txt2img"
IMAGE_PATH = Path('image.png')

PROMPT = "The interior of a miniature building made of legos"
SEED = -1
N_STEPS = 20
DEPTH_PREPROCESSOR_NAME = "depth_leres"
CANNY_PREPROCESSOR_NAME = "canny"
DEPTH_MODEL_NAME = "control_depth-fp16 [400750f6]"
SAMPLER_NAME = "Euler a"
BATCH_SIZE = 1

with open(IMAGE_PATH, "rb") as f:
    image_string = base64.b64encode(f.read()).decode('ascii')

controlnet_params = {
    "input_image": image_string,
    "module": DEPTH_PREPROCESSOR_NAME,
    "model": DEPTH_MODEL_NAME,
    "enabled": True,
    "weight": 2.0,
}

params = {
    "prompt": PROMPT,
    "seed": SEED,
    "steps": N_STEPS,
    "sampler_name": SAMPLER_NAME,
    "batch_size": BATCH_SIZE,
    "alwayson_scripts": {
        "controlnet": {
            "args": [controlnet_params]
        }
    }
}

response = requests.post(
    url=TEXT2IMG_ENDPOINT,
    json=params
).json()
```

ControlNet input image:
![image](https://user-images.githubusercontent.com/44717709/234729534-23898a59-ac5d-40d1-866f-fc813f853248.png)

Generated image (from UI):
![00003-2538451843](https://user-images.githubusercontent.com/44717709/234729562-c945ad48-925d-4d6d-ae4e-ac0d2fa4d0d7.png)

Generated image (from API):
![output](https://user-images.githubusercontent.com/44717709/234729620-0ed0c6ab-47b8-4f6c-96a1-a58274149ad0.png)

### Steps to reproduce the problem

Code provided above ^

### What should have happened?

The resulting image should look more like the image generated via the UI.

### Commit where the problem happens

webui: 3715ece0
controlnet: Where can I find this?

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
!COMMANDLINE_ARGS="--api --share --disable-safe-unpickle --no-half-vae --xformers --reinstall-xformers --enable-insecure-extension-access" REQS_FILE="requirements.txt" python launch.py
```
```


### Console logs

```Shell
Python 3.9.16 (main, Dec  7 2022, 01:11:51) 
[GCC 9.4.0]
Commit hash: 3715ece0adce7bf7c5e9c5ab3710b2fdc3848f39
Installing xformers
Installing requirements for Web UI

Launching Web UI with arguments: --api --share --disable-safe-unpickle --no-half-vae --xformers --enable-insecure-extension-access
2023-04-27 00:34:15.404429: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-27 00:34:17.742455: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
ControlNet v1.1.112
ControlNet v1.1.112
Loading weights [ac32a2b5d7] from /content/stable-diffusion-webui/models/Stable-diffusion/realisticvisionv1.3.ckpt
Creating model from config: /content/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(15): bad-hands-5, charturnerv2, easynegative, bad-artist-anime, bad-artist, bad-picture-chill-75v, badhandv4, ulzzang-6500, bad_prompt_version2, ulzzang-6500-v1.1, HyperStylizeV6, bad_prompt, bad-image-v2-39000, ng_deepnegative_v1_75t, pureerosface_v1
Textual inversion embeddings skipped(4): nrealfixer, 21charturnerv2, nartfixer, nfixer
Model loaded in 27.3s (load weights from disk: 14.3s, create model: 0.9s, apply weights to model: 2.2s, apply half(): 1.4s, load VAE: 7.4s, move model to device: 0.9s).
Running on local URL:  http://127.0.0.1:7860
Running on public URL: https://5b66b897-ff08-4080.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
  0% 0/20 [00:00<?, ?it/s]
  5% 1/20 [00:06<02:01,  6.40s/it]
 15% 3/20 [00:06<00:26,  1.56s/it]
 20% 4/20 [00:06<00:16,  1.01s/it]
 25% 5/20 [00:07<00:10,  1.41it/s]
 30% 6/20 [00:07<00:07,  1.90it/s]
 35% 7/20 [00:07<00:05,  2.43it/s]
 40% 8/20 [00:07<00:04,  2.98it/s]
 45% 9/20 [00:07<00:03,  3.53it/s]
 50% 10/20 [00:07<00:02,  4.01it/s]
 55% 11/20 [00:08<00:02,  4.43it/s]
 60% 12/20 [00:08<00:01,  4.77it/s]
 65% 13/20 [00:08<00:01,  5.05it/s]
 70% 14/20 [00:08<00:01,  5.25it/s]
 75% 15/20 [00:08<00:00,  5.41it/s]
 80% 16/20 [00:08<00:00,  5.57it/s]
 85% 17/20 [00:09<00:00,  5.62it/s]
 90% 18/20 [00:09<00:00,  5.64it/s]
 95% 19/20 [00:09<00:00,  5.68it/s]
100% 20/20 [00:09<00:00,  2.07it/s]
```

**Comment by marcos-acosta** [comment]
Discovered that the code I was using checked out an older commit, probably because something was broken at the time. However, I still had to use [WALL-E's patch in this GitHub issue](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9046#issuecomment-1493205365) in order to avoid an asyncio bug.

**Comment by marcos-acosta** [comment]
Hi @Ahtiz! I'm not sure right away what the issue might be, but I can point you to the code I'm using.

Google Colab Notebook for running stable diffusion UI: [link](https://colab.research.google.com/drive/1hCPPVcduv3lR2zP2fNUuf-9XcVZe6nBj?usp=sharing)
- Note the command `!mv api.py /content/stable-diffusion-webui/modules/api/api.py`; `api.py` is the same as the one in the source code except with the [addition suggested by MeeMeeLab](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9046)

Personal code to call API: [link](https://github.com/marcos-acosta/stable-diffusion-tours/blob/main/diffusionify.py)

The URL I've been using is the public one, e.g. `https://0b97684e59fe1ed9eb.gradio.live/sdapi/v1/txt2img/`

Hope this helps!

**Comment by LLLYF** [comment]
> 

Sry to bother you! May I ask if your code is applicable to the latest versions of webui and controllnet?

**Comment by LLLYF** [comment]
> 嗨！我不确定问题可能是什么，但我可以指出我正在使用的代码。
> 
> 谷歌Colab笔记本，用于运行稳定的扩散UI：[链接](https://colab.research.google.com/drive/1hCPPVcduv3lR2zP2fNUuf-9XcVZe6nBj?usp=sharing)
> 
> * 请注意命令 ; 与源代码中的相同，除了[MeeMeeLab建议的添加](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9046)`!mv api.py /content/stable-diffusion-webui/modules/api/api.py``api.py`
> 
> 调用 API 的个人代码：[链接](https://github.com/marcos-acosta/stable-diffusion-tours/blob/main/diffusionify.py)
> 
> 我一直使用的URL是公共的，例如`https://0b97684e59fe1ed9eb.gradio.live/sdapi/v1/txt2img/`
> 
> 希望这有帮助！

Sry to bother you! May I ask if your code is applicable to the latest versions of webui and controllnet?

**Comment by LLLYF** [comment]
> Hi @LLLYF, actually, with the latest versions of webui and controlnet, I didn't need any kind of patches, it just worked as intended.

That's awesome, but when I run my code, the terminal showed AttributeError: 'str' object has no attribute 'enabled'.
I don't know how to solve this error. Maybe the problem about enabled the Controlnet...If you willing to check my code, I will reply, Thanks for your help!

**Comment by bugsebe** [comment]
same fucking shit prompt ignored. doyou even code?
