### ISSUE TITLE
[Bug]: Preprocessor openpose_full produces detected_map with large dots and thick edges

### ISSUE THREAD

**Issue by jordenyt** [Mikubill/sd-webui-controlnet#1066]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

preprocessor openpose_full produces detected_map with large dots and edges.  Last know good commit: a07f6e8a

### Steps to reproduce the problem

- Use img2img API call in automatic1111 with controlnet in alwayson_scripts, use preprocessor openpose_full and model control_v11p_sd15_openpose [cab727d4]
- Produce unexpected result.
- Checking detected_map in webui/extensions folder found the preprocessor output has large dots and thick edge

### What should have happened?

small and precise dots and edges

### Commit where the problem happens

webui: 769def1e
controlnet: 93b0f9e1

### What browsers do you use to access the UI ?

Mozilla Firefox, Google Chrome

### Command Line Arguments

```Shell
--xformers --api --listen
```

### Console logs

```Shell
Loading model from cache: control_v11p_sd15_openpose [cab727d4]
Loading preprocessor: openpose_full
100%|██████████████████████████████████████████████████████████████████████████████████| 40/40 [00:23<00:00,  1.71it/s]
```

**Comment by lllyasviel** [comment]
now need to change 64 to real resolution like 512
