### ISSUE TITLE
[Bug]: Exception when calling controlnet api

### ISSUE THREAD

**Issue by wangdong-ivymobile** [Mikubill/sd-webui-controlnet#1070]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When calling controlnet api, either through the swagger UI or use `webuiapi` client, through me this error `Object of type ControlMode is not JSON serializable`.

the controlnet version we use is 1.1.114

### Steps to reproduce the problem

1. We use `https://github.com/mix1009/sdwebuiapi`
2. our code is almost identical to the provided exmaple
```
control_image = Image.open('base-image.png')
control_net_unit = webuiapi.ControlNetUnit(
    input_image=control_image,
    module='lineart',
    model='control_v11p_sd15_lineart [43d4be0d]'
)

r = api.txt2img(prompt="photo of a beautiful girl", controlnet_units=[control_net_unit])
r.image
```

### What should have happened?

we got image and no exception

### Commit where the problem happens

python: 3.10.10 
torch: 1.13.1+cu117 
xformers: 0.0.16rc425  
webui commit: [22bcc7be](https://github.com/AUTOMATIC1111/stable-diffusion- 
                            webui/commit/22bcc7be428c94e9408f589966c2040187245d81)
controlnet: 1.1.114

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--api
```

### Console logs

```Shell
"errors":"Object of type ControlMode is not JSON serializable"
```

**Comment by viperyl** [comment]
same here

**Comment by ljleb** [comment]
> `"enabeld": True`

The key name is not correct. it should be `"enabled"`

**Comment by ljleb** [comment]
We should print a warning if we are not crashing when receiving unrecognized keys.

**Comment by wangdong-ivymobile** [comment]
thanks, that's fast
