### ISSUE TITLE
docs: for GUI options

### ISSUE THREAD

**Issue by ttorpp** [Mikubill/sd-webui-controlnet#1074]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Hi!

Thank you very much for this great practical project.

I found that there're no official docs for GUI options (e.g. Preprocessor Resolution). 

Though you may think their meanings are obvious, others, especially newbies, may not.

I also found confusion to get what it means, as I am new to this field.

Would you please add the official documentation explaining the meaning of all the options?

Thanks.

### Steps to reproduce the problem

-

### What should have happened?

-

### Commit where the problem happens

-

### Command Line Arguments

```Shell
-
```

### Console logs

```Shell
-
```

**Comment by ghpkishore** [comment]
@ttorpp you use pixel perfect for preprocessor resolution. That will take care of everything which is required for your controlnet.

**Comment by ttorpp** [comment]
@ghpkishore Thank you very much for the exploration.

Do you mean "pixel perfect" option from the screenshot below?

<img width="472" alt="스크린샷 2023-04-30 오후 7 24 41" src="https://user-images.githubusercontent.com/73050977/235348087-61226516-bc81-46d8-be4a-c95ff82ea242.png">

I still do not know what that option mean, unfortunately.

Can I ask that?

**Comment by ghpkishore** [comment]
Read  the issue labelled enhancement. It has a lot of information. Pixel perfect was added as a way to abstract away the processors resolution variable.
