### ISSUE TITLE
[Bug]: AttributeError: module 'modules.script_callbacks' has no attribute 'on_script_unloaded'

### ISSUE THREAD

**Issue by NeilStewart19** [Mikubill/sd-webui-controlnet#1076]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Installation of controlnet through webui extension page triggers an error on controlnet.py. 
AttributeError: module 'modules.script_callbacks' has no attribute 'on_script_unloaded'

### Steps to reproduce the problem

Follow the installation instructions on the readme.

### What should have happened?

No error - Controlnet dialog should appear in UI.

### Commit where the problem happens

python: 3.10.10  •  torch: 1.12.1+cu113  •  xformers: N/A  •  gradio: 3.15.0  •  commit: [cca6e521](https://gitgud.io/AUTOMATIC1111/stable-diffusion-webui/-/commit/cca6e5212ddd77be7efdce2c27e475d3af436d85)
controlnet: v1.1.116

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No.
```

### Console logs

```Shell
Already up to date.
venv "C:\Users\XXX\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
Commit hash: cca6e5212ddd77be7efdce2c27e475d3af436d85
Installing requirements for Web UI

Launching Web UI with arguments:
No module 'xformers'. Proceeding without it.
ControlNet v1.1.116
Error loading script: controlnet.py
Traceback (most recent call last):
  File "C:\Users\XXX\stable-diffusion-webui\modules\scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\Users\XXX\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\Users\XXX\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1335, in <module>
    batch_hijack.instance.do_hijack()
  File "C:\Users\XXX\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 100, in do_hijack
    script_callbacks.on_script_unloaded(self.undo_hijack)
AttributeError: module 'modules.script_callbacks' has no attribute 'on_script_unloaded'

ControlNet v1.1.116
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights [7460a6fa] from C:\Users\XXX\stable-diffusion-webui\models\Stable-diffusion\sd-v1-4.ckpt
Applying cross attention optimization (Doggettx).
Textual inversion embeddings loaded(0):
Model loaded.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
```

### Additional information

Windows 10

**Comment by bropines** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues and checked the recent builds/commits of both this extension and the webui
> 
> ### What happened?
> Installation of controlnet through webui extension page triggers an error on controlnet.py. AttributeError: module 'modules.script_callbacks' has no attribute 'on_script_unloaded'
> 
> ### Steps to reproduce the problem
> Follow the installation instructions on the readme.
> 
> ### What should have happened?
> No error - Controlnet dialog should appear in UI.
> 
> ### Commit where the problem happens
> python: 3.10.10  •  torch: 1.12.1+cu113  •  xformers: N/A  •  gradio: 3.15.0  •  commit: [cca6e521](https://gitgud.io/AUTOMATIC1111/stable-diffusion-webui/-/commit/cca6e5212ddd77be7efdce2c27e475d3af436d85) controlnet: v1.1.116
> 
> ### What browsers do you use to access the UI ?
> Google Chrome
> 
> ### Command Line Arguments
> ```shell
> No.
> ```
> 
> ### Console logs
> ```shell
> Already up to date.
> venv "C:\Users\XXX\stable-diffusion-webui\venv\Scripts\Python.exe"
> Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
> Commit hash: cca6e5212ddd77be7efdce2c27e475d3af436d85
> Installing requirements for Web UI
> 
> Launching Web UI with arguments:
> No module 'xformers'. Proceeding without it.
> ControlNet v1.1.116
> Error loading script: controlnet.py
> Traceback (most recent call last):
>   File "C:\Users\XXX\stable-diffusion-webui\modules\scripts.py", line 205, in load_scripts
>     module = script_loading.load_module(scriptfile.path)
>   File "C:\Users\XXX\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
>     exec(compiled, module.__dict__)
>   File "C:\Users\XXX\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1335, in <module>
>     batch_hijack.instance.do_hijack()
>   File "C:\Users\XXX\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 100, in do_hijack
>     script_callbacks.on_script_unloaded(self.undo_hijack)
> AttributeError: module 'modules.script_callbacks' has no attribute 'on_script_unloaded'
> 
> ControlNet v1.1.116
> LatentDiffusion: Running in eps-prediction mode
> DiffusionWrapper has 859.52 M params.
> Loading weights [7460a6fa] from C:\Users\XXX\stable-diffusion-webui\models\Stable-diffusion\sd-v1-4.ckpt
> Applying cross attention optimization (Doggettx).
> Textual inversion embeddings loaded(0):
> Model loaded.
> Running on local URL:  http://127.0.0.1:7860
> 
> To create a public link, set `share=True` in `launch()`.
> ```
> 
> ### Additional information
> Windows 10

Did you full restart or just reloadUI?

**Comment by NeilStewart19** [comment]
full restart.

**Comment by bropines** [comment]
> full restart.

Can I see a list of all extensions?

**Comment by NeilStewart19** [comment]
<html>
<body>


Extension | URL | Update
-- | -- | --
sd-webui-controlnet | https://github.com/Mikubill/sd-webui-controlnet | latest
LDSR | built-in |  
ScuNET | built-in |  
SwinIR | built-in |  
prompt-bracket-checker | built-in |  
roll-artist | built-in |  


</body>
</html>

**Comment by bropines** [comment]
> Extension	URL	Update
> sd-webui-controlnet	https://github.com/Mikubill/sd-webui-controlnet	latest
> LDSR	built-in	 
> ScuNET	built-in	 
> SwinIR	built-in	 
> prompt-bracket-checker	built-in	 
> roll-artist	built-in

Try deleting the extension folder and reinstalling it. it is desirable to backup the models and anotators folder

**Comment by NeilStewart19** [comment]
deleting the extensions folder and reinstalling still gives the error.
Did a fresh install of SD, rolled back python to 3.10.6 and controlnet installed fine.
python: 3.10.6  •  torch: 1.13.1+cu117  •  xformers: N/A  •  gradio: 3.23.0  •  commit: [22bcc7be]
