### ISSUE TITLE
Depth control seems less precise compared with older version of controlnet

### ISSUE THREAD

**Issue by houseofsecrets** [Mikubill/sd-webui-controlnet#1080]
I have the automatic1111 webui installed with controlnet version (2f7d73a2 - Sun Apr 16 11:39:06 2023)
And the vlad version with the new version of control (2bc44000 - Thu Apr 27 05:43:12 2023)
In text2img when using the 1.1 depth model the generated seems to follow the depth less precise.
Does this has to do with the guess mode settings?
Is setting the guess mode to "controlnet is more important" the same as switching off guess mode completely?

**Comment by lllyasviel** [comment]
" balanced" is the same as switching off guess mode completely?
