### ISSUE TITLE
Tutorial on new models usage

### ISSUE THREAD

**Issue by alitan** [Mikubill/sd-webui-controlnet#1087]
Hi,

Is there any tutorial on how to use ip2p and temporalnet model?
How do we input the prompt for ip2p model and how do we use Loopback for temporalnet.
Also, i will really appreciate if anyone can update the API documentation with the new changes that are introduced with 1.1 guessmode update, pixelperfect, Loopback, etc.

**Comment by 2blackbar** [comment]
I totally agree a doc file is needed for each, even vague but at least something, especialy after update and naming changes
