### ISSUE TITLE
After using canny to preprocess the image, the lines generated are too thick, which makes it impossible to color the line draft later.

### ISSUE THREAD

**Issue by Lucysck** [Mikubill/sd-webui-controlnet#109]
Here are the parameters I used![image](https://user-images.githubusercontent.com/125596007/219450209-8c178478-0e9d-4f8a-9ca8-0f8dae1c6a4f.png)
Here is the line art I generated
![image](https://user-images.githubusercontent.com/125596007/219450433-6c76bf32-b0a2-4b9f-8435-8c8369edbcc5.png)
Testing with the rest of the pictures doesn't work well either。
But the coloring is fine. When I turned off pre-processing, the model colored my line art correctly.

**Comment by Mikubill** [comment]
Update the extension or WebUI, and retry

**Comment by MalOMaw** [comment]
> Update the extension or WebUI, and retry

The errors is that it generates annotator at 64x64 and this option is locked. After pulling in the extension folder, the issue is resolved for me and I can choose annotator's resolution freely.

**Comment by Lucysck** [comment]
> > 更新扩展或 WebUI，然后重试
> 
> 错误是它在 64 位生成注释器并且此选项被锁定。拉入扩展文件夹后，问题就解决了，我可以自由选择注释器的分辨率。默认情况下不再是 64

what should i do to get this far.

**Comment by Lucysck** [comment]
> Update the extension or WebUI, and retry

I tried to do this but it didn't work.

**Comment by Mikubill** [comment]
try update gradio: pip install gradio>=3.16.2
