### ISSUE TITLE
Trigger Button missing

### ISSUE THREAD

**Issue by IronWolve** [Mikubill/sd-webui-controlnet#1097]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Trigger button is missing

![image](https://user-images.githubusercontent.com/3938589/235390771-76c56898-aa29-44a1-a103-ed30cb75536a.png)

### Steps to reproduce the problem

Enable controlnet

### What should have happened?

Should have a red trigger button 

### Commit where the problem happens

webui:  latest
controlnet:  1.1.120

### Command Line Arguments

```Shell
set COMMANDLINE_ARGS=--xformers --port 9999
```

### Console logs

```Shell
(sd) G:\stable-diffusion-webui>webui-user.bat
venv "G:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 | packaged by conda-forge | (main, Oct 24 2022, 16:02:16) [MSC v.1916 64 bit (AMD64)]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Installing requirements for Web UI

Launching Web UI with arguments: --disable-nan-check --opt-sdp-attention --xformers --disable-safe-unpickle --port 9999 --api --api-log --enable-console-prompts
G:\stable-diffusion-webui\venv\lib\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
ControlNet v1.1.120
ControlNet v1.1.120

<snip>
```

**Comment by lllyasviel** [comment]
![image](https://user-images.githubusercontent.com/19834515/235392342-c4c05ace-4a27-4c98-91d8-dd5dfcc4375f.png)
