### ISSUE TITLE
Openpose failed

### ISSUE THREAD

**Issue by lllyasviel** [Mikubill/sd-webui-controlnet#1098]
![image](https://user-images.githubusercontent.com/19834515/235392275-127fb142-8eb0-4368-ab01-16ad32205d9f.png)
Error running process: D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1189, in process
    detected_map, is_image = preprocessor(input_image, res=preprocessor_resolution, thr_a=unit.threshold_a, thr_b=unit.threshold_b)
TypeError: OpenposeModel.run_model() missing 1 required positional argument: 'json_pose_callback'

**Comment by huchenlei** [comment]
Sorry for the failure. I am going to add tests invoking each preprocessor on diffusion task to ensure this never happen again. The fix LGTM.
