### ISSUE TITLE
[Improved UI] The UI for Preview is improved

### ISSUE THREAD

**Issue by lllyasviel** [Mikubill/sd-webui-controlnet#1106]
![image](https://user-images.githubusercontent.com/19834515/235441131-cca10d80-639e-48f9-b77f-dbcd40472cce.png)

Now it looks like this.

You may notice that the preview now have "Close" button, and if you use Openpose, you can download pose meta with "Json" button.

Also, since many users say that they cannot find "trigger"💥 icon, now the trigger icon is always visible. Also since we have "Close" button, users may less likely to get trouble if they just want to close it (even if they do not know to uncheck "allow preview")

Much more user-friendly.

Note that such complicated javascript to hack gradio is super difficult, and I do not know how to implement such complicated js hack.

The hacking code is written by CHATGPT

but I have stolen some basics from [huchenlei](https://github.com/Mikubill/sd-webui-controlnet/issues?q=is%3Apr+is%3Aopen+author%3Ahuchenlei)

**Comment by stevelacy** [comment]
The "trigger" icon was very unintuitive to figure out and use. Since it's between two select dropdowns it does not indicated "Preview" or "Run".
I'd request a "Run" or "Preview" button instead.

**Comment by stevelacy** [comment]
Not looking for hints -- UI should be intuitive not a search for missing buttons

**Comment by lllyasviel** [comment]
![image](https://user-images.githubusercontent.com/19834515/236288503-808b28bc-72a0-4f3e-95fa-fee979f57c59.png)

**Comment by stevelacy** [comment]
Yes
