### ISSUE TITLE
new a1111 break github tests

### ISSUE THREAD

**Issue by lllyasviel** [Mikubill/sd-webui-controlnet#1114]
it seems that github test does not allow torch 2.0. we gonna to find a fix. but it seems not related to actual use.

**Comment by lllyasviel** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9987

**Comment by lllyasviel** [comment]
seems that a1111 has abandoned github ci for a period of time. should we also temporarily abandon github ci?

**Comment by huchenlei** [comment]
Should we do a git on-commit/on-push hook to run tests?

**Comment by lllyasviel** [comment]
fixed by using old a1111
