### ISSUE TITLE
Not working on fresh install

### ISSUE THREAD

**Issue by ksorah1** [Mikubill/sd-webui-controlnet#113]
Hello,

First when I select a model, I get errors : 
![2023-02-16_200006](https://user-images.githubusercontent.com/112913359/219461852-f11b918a-4f93-44b3-9b00-90b314119c7b.jpg)

Then, when I generate the picture, I get something like this :
![2023-02-16_200050](https://user-images.githubusercontent.com/112913359/219461988-81342b09-5731-462a-a084-b152872d96cd.jpg)

And my CMD is :
![2023-02-16_200129](https://user-images.githubusercontent.com/112913359/219462155-2fbc8e02-b4b0-46c7-b7ea-a43a3e954d78.jpg)

I tried to do again the steps, but I can't get it to work.

My computer is good enough. 3070ti 8gb VRAM 32gb RAM, it's ok for generating 1000*px pictures 20 steps in 3 seconds. W10.

Thanks for the help.

**Comment by ksorah1** [comment]
updated all and it works better.

**Comment by Mikubill** [comment]
Try update webui and/or extension
