### ISSUE TITLE
[Feature Request] Automatically set default width + height to the input image resolution

### ISSUE THREAD

**Issue by hassan-sd** [Mikubill/sd-webui-controlnet#114]
It would be nice to have a default width and height that matches the image you upload into the Controlnet media box. 

ie
 - I copy an image from discord, I don't know the resolution or I manually drag and drop or select an image to upload
 - I paste the image into the controlnet media upload box
 - Controlnet height and width parameters default to match the input image dimensions

**Comment by Dweebking** [comment]
I just came here to ask that lol. In the edge cases where you might want to adjust the aspect ratio you could just edit the input image itself.

**Comment by Mikubill** [comment]
You can safely ignore canvas h/w when uploading image since it will not be used.

**Comment by missionfloyd** [comment]
Is the canvas resolution supposed to be multiple of 64? The output resolution is a multiple of 8.

**Comment by GeorgLegato** [comment]
> You can safely ignore canvas h/w when uploading image since it will not be used.

Actually yes, but the user should see which resolution his input images are, so they can setup the output w/h corresponding.
In my current PR I use the Canvas-Sliders Height/Width to show the size of input images.
#336
