### ISSUE TITLE
[Feature Request]: Add pixel_perfect to /controlnet/detect

### ISSUE THREAD

**Issue by Hetaneko** [Mikubill/sd-webui-controlnet#1144]
I'm using ControlNet v1.1.133.
The current payload is this:
![image](https://user-images.githubusercontent.com/54069666/235956611-ae7117fc-1015-49cb-90b6-9e2707a58349.png)

Since we already have pixel perfect mode on /controlnet/*2img. Can we have it as well as on the /controlnet/detect

**Comment by kft334** [comment]
I did this or something similar in my fork using a new endpoint and also added transparency support but I didn't make a PR for it. The fork isn't up-to-date but feel free to rip the added endpoint.
 
https://github.com/kft334/sd-webui-controlnet/commit/cab797404a003002e638da1a9a8d26701dac021b

**Comment by lllyasviel** [comment]
in api, we do not have access to the width/height of gradio slider of you need to set resolution with script on your own. it is just the short side of your image
