### ISSUE TITLE
deforum

### ISSUE THREAD

**Issue by LexVolkov** [Mikubill/sd-webui-controlnet#115]
I don’t know if this is a bug or a feature, but if you generate an image txt2img using the controlnet, and then go to the deforum, then the deforum will use the sketch generated by the controlnet for output images.

**Comment by Mikubill** [comment]
No idea about deforum. Maybe `Do not append detectmap to output` option in settings will help

**Comment by LexVolkov** [comment]
> No idea about deforum. Maybe `Do not append detectmap to output` option in settings will help

It's not a problem, you can always restart. but funny. This can be used.

**Comment by MaximusGroves** [comment]
In settings you can uncheck "append sketch to output" or check "do not append sketch to output" or however they phrase it, that might fix it
