### ISSUE TITLE
[Bug]: "Allow Preview" issue in ui-config.json

### ISSUE THREAD

**Issue by altoiddealer** [Mikubill/sd-webui-controlnet#1150]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

ui-config.json comes with a default setting which I am reporting cannot be changed from "false" to "true" without bugs.

"txt2img/Allow Preview/value": false,

By default ("false") In Automatic1111, user will check the "Allow Preview" box and it will then add a preview box in the UI.

However, if the default value is changed to "true" in ui-config.json, **the preview box will not appear.**
Clicking the starburst icon (Generate Preview) doesn't have any effect.

From this point, the only way to get the box/functionality to work is to toggle the checkbox off and on again.

![Screenshot 2023-05-04 103525](https://user-images.githubusercontent.com/1613484/236240477-ea4ee628-0411-40bf-991a-ab6f0620a90f.jpg)

### Steps to reproduce the problem

1. Edit ui-config.json in text editor
2. Change value of **"txt2img/Allow Preview/value":** from false to true
3. Open Automatic1111

### What should have happened?

**if "txt2img/Allow Preview/value": true,**

-The preview boxes should be present by default (in each ControlNet window)
-Generate Preview should be immediately functional without having to toggle "Allow Preview" off and on.

### Commit where the problem happens

webui: 5ab7f213
controlnet: 5d387abf

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
(NOTE THAT NO PREVIEW IS VISIBLE IN THE UI)

Unpacking objects: 100% (5/5), 572 bytes | 95.00 KiB/s, done.
From https://github.com/AUTOMATIC1111/stable-diffusion-webui
 * [new branch]        LoraFix    -> origin/LoraFix
Already up to date.
venv "C:\0_SD\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 5ab7f213bec2f816f9c5644becb32eb72c8ffb89
Installing requirements


Installing requirements 1 for Infinite-Zoom

Installing sd-dynamic-prompts requirements.txt




Launching Web UI with arguments: --xformers --api --disable-safe-unpickle
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
ControlNet v1.1.134
ControlNet v1.1.134
Loading weights [e6415c4892] from C:\0_SD\stable-diffusion-webui\models\Stable-diffusion\v15\Realistic_Vision_V2.0.safetensors
Creating model from config: C:\0_SD\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: C:\0_SD\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(7): bad-artist, bad-artist-anime, bad-hands-5, bad_prompt_version2, charturnerv2, easynegative, negative_hand-neg
Textual inversion embeddings skipped(4): 21charturnerv2, nartfixer, nfixer, nrealfixer
Model loaded in 2.5s (load weights from disk: 0.3s, create model: 0.2s, apply weights to model: 0.5s, apply half(): 0.5s, move model to device: 0.3s, load textual inversion embeddings: 0.6s).
load Sadtalker Checkpoints from C:\0_SD\stable-diffusion-webui\extensions\SadTalker\checkpoints
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 9.6s (import torch: 2.0s, import gradio: 0.5s, import ldm: 0.3s, other imports: 0.5s, list SD models: 0.1s, load scripts: 1.3s, load SD checkpoint: 2.7s, create ui: 2.0s, gradio launch: 0.2s).
Pixel Perfect Mode Enabled In Preview.
resize_mode = Just Resize
raw_H = 512
raw_W = 512
target_H = 512
target_W = 512
estimation = 512.0
Preview Resolution = 512
```

**Comment by lllyasviel** [comment]
since 1.1.134 the button is always visible so we do not need to change it

**Comment by altoiddealer** [comment]
OK - It's just a shame that it can't be enabled by default.
