### ISSUE TITLE
[Bug]: Not working 

### ISSUE THREAD

**Issue by alexbespik** [Mikubill/sd-webui-controlnet#1152]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I installed  control net with models but it not working 

### Steps to reproduce the problem

![image](https://user-images.githubusercontent.com/122635924/236447194-97b65768-8dee-4636-9a42-31338e293a25.png)

### What should have happened?

I shoul recive picture with schme but not black picture 

### Commit where the problem happens

webui: [22bcc7be](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/22bcc7be428c94e9408f589966c2040187245d81)
controlnet: v1.1.134
Linux manjaro  last version 
nvidia 1650 4gb 
32gb ram 

### Command Line Arguments

```Shell
--medvram --xformers
```

### Console logs

```Shell
Loading model from cache: control_canny-fp16 [e3fe7712]
using mask as input
Loading preprocessor: none
preprocessor resolution = 512
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [01:44<00:00,  5.20s/it]
Total progress: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [01:28<00:00,  4.42s/it]
{"prompt": "", "all_prompts": [""], "negative_prompt": "", "all_negative_prompts": [""], "seed": 619730843, "all_seeds": [619730843], "subseed": 3047939413, "all_subseeds": [3047939413], "subseed_strength": 0, "width": 512, "height": 512, "sampler_name": "Euler a", "cfg_scale": 7, "steps": 20, "batch_size": 1, "restore_faces": false, "face_restoration_model": null, "sd_model_hash": "9aba26abdf", "seed_resize_from_w": 0, "seed_resize_from_h": 0, "denoising_strength": null, "extra_generation_params": {"ControlNet Enabled": true, "ControlNet Preprocessor": "canny", "ControlNet Model": "control_canny-fp16 [e3fe7712]", "ControlNet Weight": 1, "ControlNet Starting Step": 0, "ControlNet Ending Step": 1, "ControlNet Resize Mode": "Crop and Resize", "ControlNet Pixel Perfect": "False", "ControlNet Control Mode": "Balanced", "ControlNet Preprocessor Parameters": "(512, 100, 200)"}, "index_of_first_image": 0, "infotexts": ["Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 619730843, Size: 512x512, Model hash: 9aba26abdf, Model: deliberate_v2, ENSD: 4, ControlNet Enabled: True, ControlNet Preprocessor: canny, ControlNet Model: control_canny-fp16 [e3fe7712], ControlNet Weight: 1, ControlNet Starting Step: 0, ControlNet Ending Step: 1, ControlNet Resize Mode: Crop and Resize, ControlNet Pixel Perfect: False, ControlNet Control Mode: Balanced, ControlNet Preprocessor Parameters: \"(512, 100, 200)\""], "styles": [], "job_timestamp": "20230505142936", "clip_skip": 1, "is_using_inpainting_conditioning": false}
```

### Additional information

I am swich on preprocessor but in console i see none 
![image](https://user-images.githubusercontent.com/122635924/236447981-ab5612de-6d11-4b0f-91ec-95cd5b2220a8.png)

**Comment by lllyasviel** [comment]
clear the mask you draw

**Comment by Enferlain** [comment]
Same issue atm. 0 drawings, random images. Some output proper detectmaps, some don't.

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/15861396/da4db817-bbf0-40be-8933-8f601510e934)

Loading model from cache: control_v11p_sd15_openpose_fp16 [73c2b67d]
Loading preprocessor: openpose_full
Pixel Perfect Mode Enabled.
resize_mode = ResizeMode.RESIZE
raw_H = 989
raw_W = 1280
target_H = 768
target_W = 1024
estimation = 791.2
preprocessor resolution = 791
