### ISSUE TITLE
ControlNet problem on colab

### ISSUE THREAD

**Issue by Maxxxwell62** [Mikubill/sd-webui-controlnet#116]
ControlNet always keeps crash no matter which model I use on colab.

Loading preprocessor: canny, model: control_sd15_canny [fef5e48e]
^C

**Comment by Mikubill** [comment]
It's colab oom issue and you need to try something like change the mapping location to cuda

**Comment by Maxxxwell62** [comment]
> It's colab oom issue and you need to try something like change the mapping location to cuda

I added this cell to work:

!wget http://launchpadlibrarian.net/367274644/libgoogle-perftools-dev_2.5-2.2ubuntu3_amd64.deb
!wget https://launchpad.net/ubuntu/+source/google-perftools/2.5-2.2ubuntu3/+build/14795286/+files/google-perftools_2.5-2.2ubuntu3_all.deb
!wget https://launchpad.net/ubuntu/+source/google-perftools/2.5-2.2ubuntu3/+build/14795286/+files/libtcmalloc-minimal4_2.5-2.2ubuntu3_amd64.deb
!wget https://launchpad.net/ubuntu/+source/google-perftools/2.5-2.2ubuntu3/+build/14795286/+files/libgoogle-perftools4_2.5-2.2ubuntu3_amd64.deb
!apt install -qq libunwind8-dev
!dpkg -i *.deb
%env LD_PRELOAD=libtcmalloc.so
!rm *.deb
