### ISSUE TITLE
none of the models actually detect anything

### ISSUE THREAD

**Issue by alectprasad** [Mikubill/sd-webui-controlnet#117]
https://imgur.com/a/ntEaC97

tried every model in here https://huggingface.co/webui/ControlNet-modules-safetensors/tree/main

**Comment by ClashSAN** [comment]
what happens when you use a different image? (checker pattern might be ruining map generations)

**Comment by alectprasad** [comment]
same thing https://imgur.com/a/OlNYH1E

**Comment by dreamingtulpa** [comment]
I'm experiencing the same issue. ControlNet canvas is not detecting uploaded images during generation. If I draw into the canvas, the drawing is recognized, but not the image itself:

<img width="711" alt="image" src="https://user-images.githubusercontent.com/507849/219500516-ebe7d383-fa7f-4638-ba2d-087dc9220c85.png">

![image](https://user-images.githubusercontent.com/507849/219500741-7156d869-3226-4e83-8d80-10570b89ac6b.png)

**Comment by TomClive** [comment]
Yes - it's not working for me anymore either. It was working previously but I updated the extension and now nothing is happening.

**Comment by ClashSAN** [comment]
If the output is blank, try a different browser.
I couldn't replicate this problem with d81bee5191966477a8113db5ac4fd2a279b5850b, could you test with --xformers and (lowvram checkbox)?

**Comment by Mikubill** [comment]
Couldn't reproduce, works fine on my end:
![rp](https://user-images.githubusercontent.com/31246794/219518533-469af18d-f286-4673-b92b-c3b17b9a94ce.png)

**Comment by yunuskoc005** [comment]
Yeah same problem I think for me. I was using brave also

**Comment by alectprasad** [comment]
why was this closed its still not fixed

**Comment by Mikubill** [comment]
Feel free to reopen it. So changing browser not works for you?
