### ISSUE TITLE
[Bug]: Error running process: E:\GitHub\WEBUI\extensions\sd-webui-controlnet\scripts\controlnet.py

### ISSUE THREAD

**Issue by Joedog6503** [Mikubill/sd-webui-controlnet#1171]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Attempted to run canny on SD, and it fails to run process

### Steps to reproduce the problem

1. Go to the ControlNet v1.1.139
2. Press the canny preprocessor and model sd 15 canny
3. enable Control net
4. use image
5. genertate image

### What should have happened?

for the program to not fail...

### Commit where the problem happens

webui: latest
controlnet: ControlNet v1.1.139

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--API
```

### Console logs

venv "E:\GitHub\WEBUI\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8
Installing requirements for Web UI
Installing Deforum requirement: py3d

Launching Web UI with arguments: --api
E:\GitHub\WEBUI\venv\lib\site-packages\pkg_resources\__init__.py:123: PkgResourcesDeprecationWarning: ansformers is an invalid version and will not be supported in a future release
  warnings.warn(
No module 'xformers'. Proceeding without it.
==============================================================================
You are running torch 1.12.1+cu113.
The program is tested to work with torch 1.13.1.
To reinstall the desired version, run with commandline flag --reinstall-torch.
Beware that this will cause a lot of large files to be downloaded, as well as
there are reports of issues with training tab on the latest version.

Use --skip-version-check commandline argument to disable this check.
==============================================================================
Additional Network extension not installed, Only hijack built-in lora
LoCon Extension hijack built-in lora successfully
[AddNet] Updating model hashes...
100%|█████████████████████████████████████████████████████████████████████████████| 110/110 [00:00<00:00, 18329.56it/s]
[AddNet] Updating model hashes...
100%|█████████████████████████████████████████████████████████████████████████████| 110/110 [00:00<00:00, 16921.20it/s]
ControlNet v1.1.139
ControlNet v1.1.139
Loading weights [6e430eb514] from E:\GitHub\WEBUI\models\Stable-diffusion\anything-v4.5-pruned.safetensors
Creating model from config: E:\GitHub\WEBUI\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying cross attention optimization (Doggettx).
Textual inversion embeddings loaded(27): Arthur, Aya11k, bad-artist-anime, bad-artist, bad-hands-5, bad-image-9600, bad-image-v2-11000, bad-image-v2-27000, bad-image-v2-39000, bad_prompt_version2, Citliu, easynegative, HyperReal, Jasmine11k, Jishuka11k, Knowname, ng_deepnegative_v1_75t, RaidenPT, Realism, Sunburn, Sunburn2, Tessia11k, Tessia4k, Varay11k, Virion, Yamato, YuraOOG
Model loaded in 3.8s (create model: 0.4s, apply weights to model: 0.9s, apply half(): 0.5s, move model to device: 0.9s, load textual inversion embeddings: 1.1s).
*Deforum ControlNet support: enabled*
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  6.60it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 11.01it/s]
Loading model: control_sd15_canny [fef5e48e]
Loaded state_dict from [E:\GitHub\WEBUI\models\ControlNet\control_sd15_canny.pth]
Loading config: E:\GitHub\WEBUI\extensions\sd-webui-controlnet\models\control_sd15_canny.yaml
ControlNet model control_sd15_canny [fef5e48e] loaded.
Error running process: E:\GitHub\WEBUI\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "E:\GitHub\WEBUI\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "E:\GitHub\WEBUI\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1188, in process
    tmp_seed = int(p.all_seeds[0] if p.seed == -1 else max(int(p.seed),0))
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

                                                                                                                       LoRA weight_unet: 0.6, weight_tenc: 0.6, model: TessXArt3(d6dc9d23862c)                          | 0/20 [00:00<?, ?it/s]
dimension: {172}, alpha: {172.0}, multiplier_unet: 0.6, multiplier_tenc: 0.6
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
original forward/weights is backed up.
enable LoRA for text encoder
enable LoRA for U-Net
shapes for 0 weights are converted.
LoRA model TessXArt3(d6dc9d23862c) loaded: <All keys matched successfully>
setting (or sd model) changed. new networks created.
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.83it/s]
 80%|█████████████████████████████████████████████████████████████████▌                | 16/20 [00:32<00:14,  3.72s/it]100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:36<00:00,  1.83s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 40/40 [00:42<00:00,  1.07s/it]
restoring last networks
original forward/weights is restored.
  0%|                                                                                         | 0/20 [00:00<?, ?it/s]
Loading weights [61f21f5915] from E:\GitHub\WEBUI\models\Stable-diffusion\abyssorangemix2NSFW_abyssorangemix2Nsfw.safetensors
Applying cross attention optimization (Doggettx).
Weights loaded in 1.3s (apply weights to model: 0.5s, move model to device: 0.7s).
Loading model: control_sd15_canny [fef5e48e]
Loaded state_dict from [E:\GitHub\WEBUI\models\ControlNet\control_sd15_canny.pth]
Loading config: E:\GitHub\WEBUI\extensions\sd-webui-controlnet\models\control_sd15_canny.yaml
ControlNet model control_sd15_canny [fef5e48e] loaded.
Loading preprocessor: canny
preprocessor resolution = 64
                                                                                                                     LoRA weight_unet: 0.6, weight_tenc: 0.6, model: TessXArt3(d6dc9d23862c)                         | 0/20 [00:00<?, ?it/s]
dimension: {172}, alpha: {172.0}, multiplier_unet: 0.6, multiplier_tenc: 0.6
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
original forward/weights is backed up.
enable LoRA for text encoder
enable LoRA for U-Net
shapes for 0 weights are converted.
LoRA model TessXArt3(d6dc9d23862c) loaded: <All keys matched successfully>
setting (or sd model) changed. new networks created.
100%|████████████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.54it/s]
 60%|████████████████████████████████████████████████                                | 12/20 [00:21<00:14,  1.80s/it]
Loading weights [6e430eb514] from E:\GitHub\WEBUI\models\Stable-diffusion\anything-v4.5-pruned.safetensors  1.81s/it]
Applying cross attention optimization (Doggettx).
Weights loaded in 1.1s (apply weights to model: 0.7s, move model to device: 0.4s).
Total progress:  80%|███████████████████████████████████████████████████▏            | 32/40 [00:31<00:07,  1.02it/s]
Loading model: control_sd15_canny [fef5e48e]
Loaded state_dict from [E:\GitHub\WEBUI\models\ControlNet\control_sd15_canny.pth]
Loading config: E:\GitHub\WEBUI\extensions\sd-webui-controlnet\models\control_sd15_canny.yaml
ControlNet model control_sd15_canny [fef5e48e] loaded.
Error running process: E:\GitHub\WEBUI\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "E:\GitHub\WEBUI\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "E:\GitHub\WEBUI\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1188, in process
    tmp_seed = int(p.all_seeds[0] if p.seed == -1 else max(int(p.seed),0))
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

                                                                                                                     restoring last networks                                                                         | 0/20 [00:00<?, ?it/s]
original forward/weights is restored.
LoRA weight_unet: 0.6, weight_tenc: 0.6, model: TessXArt3(d6dc9d23862c)
dimension: {172}, alpha: {172.0}, multiplier_unet: 0.6, multiplier_tenc: 0.6
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
original forward/weights is backed up.
enable LoRA for text encoder
enable LoRA for U-Net
shapes for 0 weights are converted.
LoRA model TessXArt3(d6dc9d23862c) loaded: <All keys matched successfully>
setting (or sd model) changed. new networks created.
100%|████████████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.55it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 20/20 [00:25<00:00,  1.26s/it]
Total progress: 100%|████████████████████████████████████████████████████████████████| 40/40 [00:31<00:00,  1.26it/s]
Loading model from cache: control_sd15_canny [fef5e48e]
Error running process: E:\GitHub\WEBUI\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "E:\GitHub\WEBUI\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "E:\GitHub\WEBUI\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1188, in process
    tmp_seed = int(p.all_seeds[0] if p.seed == -1 else max(int(p.seed),0))
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

100%|████████████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.78it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 20/20 [00:25<00:00,  1.27s/it]
Total progress: 100%|████████████████████████████████████████████████████████████████| 40/40 [00:30<00:00,  1.31it/s]

### Additional information

I deleted deform from my files, it then worked, but began to fail again

**Comment by Joedog6503** [comment]
venv "E:\GitHub\WEBUI\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8
Installing requirements for Web UI
Installing Deforum requirement: py3d


Launching Web UI with arguments: --api
E:\GitHub\WEBUI\venv\lib\site-packages\pkg_resources\__init__.py:123: PkgResourcesDeprecationWarning: ansformers is an invalid version and will not be supported in a future release
  warnings.warn(
No module 'xformers'. Proceeding without it.
==============================================================================
You are running torch 1.12.1+cu113.
The program is tested to work with torch 1.13.1.
To reinstall the desired version, run with commandline flag --reinstall-torch.
Beware that this will cause a lot of large files to be downloaded, as well as
there are reports of issues with training tab on the latest version.

Use --skip-version-check commandline argument to disable this check.
==============================================================================
Additional Network extension not installed, Only hijack built-in lora
LoCon Extension hijack built-in lora successfully
[AddNet] Updating model hashes...
100%|█████████████████████████████████████████████████████████████████████████████| 110/110 [00:00<00:00, 18329.56it/s]
[AddNet] Updating model hashes...
100%|█████████████████████████████████████████████████████████████████████████████| 110/110 [00:00<00:00, 16921.20it/s]
ControlNet v1.1.139
ControlNet v1.1.139
Loading weights [6e430eb514] from E:\GitHub\WEBUI\models\Stable-diffusion\anything-v4.5-pruned.safetensors
Creating model from config: E:\GitHub\WEBUI\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying cross attention optimization (Doggettx).
Textual inversion embeddings loaded(27): Arthur, Aya11k, bad-artist-anime, bad-artist, bad-hands-5, bad-image-9600, bad-image-v2-11000, bad-image-v2-27000, bad-image-v2-39000, bad_prompt_version2, Citliu, easynegative, HyperReal, Jasmine11k, Jishuka11k, Knowname, ng_deepnegative_v1_75t, RaidenPT, Realism, Sunburn, Sunburn2, Tessia11k, Tessia4k, Varay11k, Virion, Yamato, YuraOOG
Model loaded in 3.8s (create model: 0.4s, apply weights to model: 0.9s, apply half(): 0.5s, move model to device: 0.9s, load textual inversion embeddings: 1.1s).
*Deforum ControlNet support: enabled*
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  6.60it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 11.01it/s]
Loading model: control_sd15_canny [fef5e48e]
Loaded state_dict from [E:\GitHub\WEBUI\models\ControlNet\control_sd15_canny.pth]
Loading config: E:\GitHub\WEBUI\extensions\sd-webui-controlnet\models\control_sd15_canny.yaml
ControlNet model control_sd15_canny [fef5e48e] loaded.
Error running process: E:\GitHub\WEBUI\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "E:\GitHub\WEBUI\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "E:\GitHub\WEBUI\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1188, in process
    tmp_seed = int(p.all_seeds[0] if p.seed == -1 else max(int(p.seed),0))
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

                                                                                                                       LoRA weight_unet: 0.6, weight_tenc: 0.6, model: TessXArt3(d6dc9d23862c)                          | 0/20 [00:00<?, ?it/s]
dimension: {172}, alpha: {172.0}, multiplier_unet: 0.6, multiplier_tenc: 0.6
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
original forward/weights is backed up.
enable LoRA for text encoder
enable LoRA for U-Net
shapes for 0 weights are converted.
LoRA model TessXArt3(d6dc9d23862c) loaded: <All keys matched successfully>
setting (or sd model) changed. new networks created.
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.83it/s]
 80%|█████████████████████████████████████████████████████████████████▌                | 16/20 [00:32<00:14,  3.72s/it]100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:36<00:00,  1.83s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 40/40 [00:42<00:00,  1.07s/it]
restoring last networks
original forward/weights is restored.
  0%|                                                                                         | 0/20 [00:00<?, ?it/s]
Loading weights [61f21f5915] from E:\GitHub\WEBUI\models\Stable-diffusion\abyssorangemix2NSFW_abyssorangemix2Nsfw.safetensors
Applying cross attention optimization (Doggettx).
Weights loaded in 1.3s (apply weights to model: 0.5s, move model to device: 0.7s).
Loading model: control_sd15_canny [fef5e48e]
Loaded state_dict from [E:\GitHub\WEBUI\models\ControlNet\control_sd15_canny.pth]
Loading config: E:\GitHub\WEBUI\extensions\sd-webui-controlnet\models\control_sd15_canny.yaml
ControlNet model control_sd15_canny [fef5e48e] loaded.
Loading preprocessor: canny
preprocessor resolution = 64
                                                                                                                     LoRA weight_unet: 0.6, weight_tenc: 0.6, model: TessXArt3(d6dc9d23862c)                         | 0/20 [00:00<?, ?it/s]
dimension: {172}, alpha: {172.0}, multiplier_unet: 0.6, multiplier_tenc: 0.6
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
original forward/weights is backed up.
enable LoRA for text encoder
enable LoRA for U-Net
shapes for 0 weights are converted.
LoRA model TessXArt3(d6dc9d23862c) loaded: <All keys matched successfully>
setting (or sd model) changed. new networks created.
100%|████████████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.54it/s]
 60%|████████████████████████████████████████████████                                | 12/20 [00:21<00:14,  1.80s/it]
Loading weights [6e430eb514] from E:\GitHub\WEBUI\models\Stable-diffusion\anything-v4.5-pruned.safetensors  1.81s/it]
Applying cross attention optimization (Doggettx).
Weights loaded in 1.1s (apply weights to model: 0.7s, move model to device: 0.4s).
Total progress:  80%|███████████████████████████████████████████████████▏            | 32/40 [00:31<00:07,  1.02it/s]
Loading model: control_sd15_canny [fef5e48e]
Loaded state_dict from [E:\GitHub\WEBUI\models\ControlNet\control_sd15_canny.pth]
Loading config: E:\GitHub\WEBUI\extensions\sd-webui-controlnet\models\control_sd15_canny.yaml
ControlNet model control_sd15_canny [fef5e48e] loaded.
Error running process: E:\GitHub\WEBUI\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "E:\GitHub\WEBUI\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "E:\GitHub\WEBUI\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1188, in process
    tmp_seed = int(p.all_seeds[0] if p.seed == -1 else max(int(p.seed),0))
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

                                                                                                                     restoring last networks                                                                         | 0/20 [00:00<?, ?it/s]
original forward/weights is restored.
LoRA weight_unet: 0.6, weight_tenc: 0.6, model: TessXArt3(d6dc9d23862c)
dimension: {172}, alpha: {172.0}, multiplier_unet: 0.6, multiplier_tenc: 0.6
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
original forward/weights is backed up.
enable LoRA for text encoder
enable LoRA for U-Net
shapes for 0 weights are converted.
LoRA model TessXArt3(d6dc9d23862c) loaded: <All keys matched successfully>
setting (or sd model) changed. new networks created.
100%|████████████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.55it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 20/20 [00:25<00:00,  1.26s/it]
Total progress: 100%|████████████████████████████████████████████████████████████████| 40/40 [00:31<00:00,  1.26it/s]
Loading model from cache: control_sd15_canny [fef5e48e]
Error running process: E:\GitHub\WEBUI\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "E:\GitHub\WEBUI\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "E:\GitHub\WEBUI\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1188, in process
    tmp_seed = int(p.all_seeds[0] if p.seed == -1 else max(int(p.seed),0))
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

100%|████████████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.78it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 20/20 [00:25<00:00,  1.27s/it]
Total progress: 100%|████████████████████████████████████████████████████████████████| 40/40 [00:30<00:00,  1.31it/s]

after removing Deform from my files it worked ONCE, but went back to failing

**Comment by lllyasviel** [comment]
fixed in v1.1.140
