### ISSUE TITLE
[Bug]: The ISSUE About Controlnet API

### ISSUE THREAD

**Issue by LLLYF** [Mikubill/sd-webui-controlnet#1173]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When I used Controlnet API in my own python file, something went error that Controlnet dosen't work.
But there is nothing problem when Img2Img API was used.

### Steps to reproduce the problem

1. Start webui
2. post API

### What should have happened?

No idea...

### Commit where the problem happens

webui: /sdapi/v1/img2img
controlnet: 

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
webui-user.bat
```

### Console logs

```Shell
[ControlNet] warning: using deprecated '/controlnet/img2img' route
[ControlNet] warning: consider using the '/sdapi/v1/img2img' route with the 'alwayson_scripts' json property instead
Error running process: D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 661, in process
    unit = self.parse_remote_call(p, unit, idx)
  File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 573, in parse_remote_call
    unit.enabled = selector(p, "control_net_enabled", unit.enabled, idx, strict=True)
AttributeError: 'str' object has no attribute 'enabled'
```

### Additional information

Just do not know how the problem come out.

**Comment by lllyasviel** [comment]
please see also wiki and consider using the '/sdapi/v1/img2img' route with the 'alwayson_scripts' json property instead

**Comment by ljleb** [comment]
The route was removed in a more recent controlnet release. Please update both the webui and controlnet to fix the problem.

**Comment by LLLYF** [comment]
> please see also wiki and consider using the '/sdapi/v1/img2img' route with the 'alwayson_scripts' json property instead

Thanks for your answer!!! Where I can see wiki?

**Comment by LLLYF** [comment]
> The route was removed in a more recent controlnet release. Please update both the webui and controlnet to fix the problem.

Is that mean my controlnet version for webui is not the newest?

**Comment by ljleb** [comment]
Yes, but also this error occured in earlier versions of the webui, when your number of arguments to controlnet is less than the max number of units. if you really do not want to update for some reason, pass the right amount of cn units to the api, filling {"enabled": false} for disabled units.

**Comment by LLLYF** [comment]
> 

Thanks a lot ! But due to some reasons, I must use v1.5 .I will update the controlnet and try again!

**Comment by ljleb** [comment]
1.5 is the stable diffusion model version. updating the webui will still work with these models, it is unrelated to the webui version.

**Comment by LLLYF** [comment]
> 1.5 is the stable diffusion model version. updating the webui will still work with these models, it is unrelated to the webui version.

I think I finish them, but when I try again, It seems even can not generate any img(It use img2img API when the Controlnet API went error).And terminal shown :KeyError: 'images' (no output image could found)

**Comment by ljleb** [comment]
1) if you have not yet updated your webui, please update using git or by reinstalling a new webui. in later releases, the webui auto-updates to latest
2) see lllysaviel's comment above for new api usage. as the console warning said, these routes were deprecated and have been removed in later releases

**Comment by LLLYF** [comment]
> 1. if you have not yet updated your webui, please update using git or by reinstalling a new webui
> 2. see lllysaviel's comment above for new api usage. as the console warning said, these routes were deprecated and have been removed in later releases

Thanks for your patient reply! That's proves that my version is new and how can I add controlnet in my code?

**Comment by ljleb** [comment]
You can find how to interract with controlnet programmatically by clicking on "wiki" above, then "API".

**Comment by LLLYF** [comment]
> You can find how to interract with controlnet programmatically by clicking on "wiki" above, then "API".

Where is "wiki" ...

**Comment by ljleb** [comment]
https://github.com/Mikubill/sd-webui-controlnet/wiki/API

**Comment by LLLYF** [comment]
> 

I got it ! THANKS !!! I will try.

**Comment by LLLYF** [comment]
> https://github.com/Mikubill/sd-webui-controlnet/wiki/API

I got it ! THANKS !!! I will try.

**Comment by LLLYF** [comment]
> https://github.com/Mikubill/sd-webui-controlnet/wiki/API

sadly I tried some ways about how to add the controlnet in new API but dosen't work.Also remind AttributeError: 'str' object has no attribute 'enabled'...

**Comment by LLLYF** [comment]
> https://github.com/Mikubill/sd-webui-controlnet/wiki/API

I added git pull in webui-user.bat before start webui, then I CLICK API an the website shown {"detail":"Not Found"}... What's wrong with that...

**Comment by LLLYF** [comment]
> > https://github.com/Mikubill/sd-webui-controlnet/wiki/API
> 
> sadly I tried some ways about how to add the controlnet in new API but dosen't work.Also remind AttributeError: 'str' object has no attribute 'enabled'...

I solved all the error about that, Sincerely thanks a lot for your help!
