### ISSUE TITLE
name 'x_samples' is not defined

### ISSUE THREAD

**Issue by wen313** [Mikubill/sd-webui-controlnet#1176]
https://github.com/Mikubill/sd-webui-controlnet/blob/6b2028b187983489f5eba7d2a99d4bdbd7840079/example/chatgpt.py#L391
report error ："sd-webui-controlnet/example/chatgpt.py", line 405, in inference
    real_image = Image.fromarray(x_samples[0])  # default the index0 image
NameError: name 'x_samples' is not defined

**Comment by ljleb** [comment]
hmm /examples looks like a neglected part of the repo. It hasn't been updated for months and still uses the first controlnet web api.

**Comment by wen313** [comment]
Yes, there are some similar errors in it, such as：name 'image' is not defined at "sd-webui-controlnet/example/chatgpt.py", line 265

**Comment by lllyasviel** [comment]
do we really want to maintain chatgpt? or just summon @Mikubill ?
