### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by kgonia** [Mikubill/sd-webui-controlnet#1177]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

extension pick wrong preprocessor for openpose - it's always just face

in logs there is right name

Loading preprocessor: openpose_full
Loading preprocessor: openpose

but generated mask it's always just face

![tmpkuieuocr](https://user-images.githubusercontent.com/4281421/236621891-2721e342-58ab-4519-82ed-a1d263b4df2f.png)

### Steps to reproduce the problem

1. Go to txt2img tab 
2. load image in control net
3. enable controlnet
4. pick openpose preprocessor
5. generate & watch result

### What should have happened?

use right preprocessor

### Commit where the problem happens

webui: [22bcc7be](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/22bcc7be428c94e9408f589966c2040187245d81)
controlnet: af472078 

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
Loading model from cache: control_openpose-fp16 [9ca67cc5]█████████████████████████████| 20/20 [00:04<00:00,  5.17it/s]
Loading preprocessor: openpose
preprocessor resolution = 512
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  5.13it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.87it/s]
Loading model from cache: control_openpose-fp16 [9ca67cc5]█████████████████████████████| 20/20 [00:04<00:00,  5.16it/s]
Loading preprocessor: openpose_full
preprocessor resolution = 512
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  5.12it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.87it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  5.14it/s]
```

**Comment by lllyasviel** [comment]
caused by inaccuracy of openpose - try different images
