### ISSUE TITLE
output is bad

### ISSUE THREAD

**Issue by Linus3524** [Mikubill/sd-webui-controlnet#118]
![S__159539214](https://user-images.githubusercontent.com/120999981/219470923-30ecef7e-97f1-464a-8b79-6770e484408b.jpg)
The resulting picture has a super-thick skeleton. It is not like the pictures in other examples. The super-thick skeleton makes the calculations messy. What is the problem?
![S__159539217](https://user-images.githubusercontent.com/120999981/219471341-d361490f-0ff2-4d98-a3c2-7ab3f6bf3767.jpg)
and other problem like pic, 3 Erorr

**Comment by Mikubill** [comment]
try update extension and/or webui

**Comment by Mikubill** [comment]
btw, simple test with your image:

![ajkd](https://user-images.githubusercontent.com/31246794/219520135-069520cb-2318-494e-ac36-93447b5547a5.png)
