### ISSUE TITLE
[New Feature] png meta is improved

### ISSUE THREAD

**Issue by lllyasviel** [Mikubill/sd-webui-controlnet#1180]
**Below is the old terrible png meta for multi-controlnets:**

house, best quality
Negative prompt: lowres, bad anatomy, bad hands, cropped, worst quality
Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 3253294192, Size: 512x512, Model hash: cc6cb27103, Model: v1-5-pruned-emaonly, Clip skip: 2, ControlNet 0 Enabled: True, ControlNet 0 Preprocessor: mlsd, ControlNet 0 Model: control_v11p_sd15_mlsd [aca30ff0], ControlNet 0 Weight: 1, ControlNet 0 Starting Step: 0, ControlNet 0 Ending Step: 1, ControlNet 0 Resize Mode: Crop and Resize, ControlNet 0 Pixel Perfect: True, ControlNet 0 Control Mode: Balanced, ControlNet 0 Preprocessor Parameters: "(512, 0.1, 0.1)", ControlNet 1 Enabled: True, ControlNet 1 Preprocessor: openpose_full, ControlNet 1 Model: control_v11p_sd15_openpose [cab727d4], ControlNet 1 Weight: 1, ControlNet 1 Starting Step: 0, ControlNet 1 Ending Step: 1, ControlNet 1 Resize Mode: Crop and Resize, ControlNet 1 Pixel Perfect: True, ControlNet 1 Control Mode: Balanced, ControlNet 1 Preprocessor Parameters: "(512, 64, 64)", ControlNet 2 Enabled: True, ControlNet 2 Preprocessor: scribble_hed, ControlNet 2 Model: control_v11p_sd15_scribble [d4ba51ff], ControlNet 2 Weight: 1, ControlNet 2 Starting Step: 0, ControlNet 2 Ending Step: 1, ControlNet 2 Resize Mode: Crop and Resize, ControlNet 2 Pixel Perfect: True, ControlNet 2 Control Mode: Balanced, ControlNet 2 Preprocessor Parameters: "(512, 127, 64)"

**Since 1.1.142, the png meta will look like this:**

house, best quality
Negative prompt: lowres, bad anatomy, bad hands, cropped, worst quality
Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 3457493619, Size: 512x512, Model hash: cc6cb27103, Model: v1-5-pruned-emaonly, Clip skip: 2,
ControlNet 0: "preprocessor: mlsd, model: control_v11p_sd15_mlsd [aca30ff0], weight: 1, starting/ending: (0, 1), resize mode: Crop and Resize, pixel perfect: True, control mode: Balanced, preprocessor params: (512, 0.1, 0.1)",
ControlNet 1: "preprocessor: openpose_full, model: control_v11p_sd15_openpose [cab727d4], weight: 1, starting/ending: (0, 1), resize mode: Crop and Resize, pixel perfect: True, control mode: Balanced, preprocessor params: (512, 64, 64)",
ControlNet 2: "preprocessor: scribble_hed, model: control_v11p_sd15_scribble [d4ba51ff], weight: 1, starting/ending: (0, 1), resize mode: Crop and Resize, pixel perfect: True, control mode: Balanced, preprocessor params: (512, 127, 64)"

![image](https://user-images.githubusercontent.com/19834515/236624878-a0924b30-87e1-4af5-a07e-78ff039c4fc7.png)

Now controlnet will not mess your png meta anymore. it is now organized in a better way

**Comment by marcsyp** [comment]
Love this! Thank you. Question: is the metadata now applied properly when pasting into the prompt text box? I have never seen that work and don't know if it was a feature intended to. Thanks!
