### ISSUE TITLE
"Send to txt2img" works well but another extension "PNG info" broken

### ISSUE THREAD

**Issue by millionart** [Mikubill/sd-webui-controlnet#1203]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

This commint https://github.com/Mikubill/sd-webui-controlnet/commit/a84b6c620d6f1c8228aa46b377020894f93db92f will change the PNG metadata, causing the PNG info's "Send to txt2img" function to break down and fail to properly transmit the control information and more in the metadata.

### Steps to reproduce the problem

The following two figures are before and after comparison. Place them in png info and click Send to txt2img. You can see the difference in the Negative prompt. 

![00007-587900125](https://user-images.githubusercontent.com/7535532/236691119-c7c494fe-6d43-42b2-bca3-b478b926b938.png)
![00005-587900125](https://user-images.githubusercontent.com/7535532/236691125-4d8c2c89-ae4d-45f5-841c-3a3b35d7195c.png)

### What should have happened?

-

### Commit where the problem happens

webui: 1.1.1
controlnet: v1.1.142

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
-
```

### Console logs

```Shell
-
```

**Comment by lllyasviel** [comment]
fixed in 1.1.150 https://github.com/Mikubill/sd-webui-controlnet/pull/1204

feel fre to reopen if not solved
