### ISSUE TITLE
Feature Request - Image cropping in controlnet 1.1

### ISSUE THREAD

**Issue by jonwong666** [Mikubill/sd-webui-controlnet#1205]
This was addressed in controlnet 1.0 , however with the new 1.1 release the cropping feature is gone.

https://github.com/Mikubill/sd-webui-controlnet/pull/483

Is it possible to reimplement cropping to 1.1 please?

Thank you

**Comment by lllyasviel** [comment]
this can be really complicated considering we have inpaint mask now.
but note that if you do not give img to cn, cn can use img in i2i tab, and the img in i2i tab has a crop button

**Comment by jonwong666** [comment]
> this can be really complicated considering we have inpaint mask now. but note that if you do not give img to cn, cn can use img in i2i tab, and the img in i2i tab has a crop button

thank you for the reply, I understand. However I use the old crop feature a lot in txt 2 img during my art making, to experiment with different sources /  references that may not be in the correct ratio or framing. This was a useful because I didn't have to preprocess the input and could drag and drop directly from browser which allowed for a more creative experience.

the solution implemented in the previous version by  @missionfloyd  used a separate tab for cropped images, which sent the result back to the main image window, this shouldn't mess with the inpaint?

I would really appreciate someone helping with this request. 

thank you

**Comment by jonwong666** [comment]
anyone care to give it a shot?

**Comment by jonwong666** [comment]
bump ( please )
