### ISSUE TITLE
How do you control "Inpaint not masked" area?

### ISSUE THREAD

**Issue by Yaoxingtian** [Mikubill/sd-webui-controlnet#1217]
Hi,
 "Inpaint not masked" area is easily changed while paint area change,
so ,how do you control "Inpaint not masked" area not to be changed ?

**Comment by lllyasviel** [comment]
see also https://github.com/Mikubill/sd-webui-controlnet/discussions/1143

**Comment by Yaoxingtian** [comment]
> see also #1143

thank you for you answer!
but i mean ,can you show me the code, where is the implementation ? 
i want to know that.

**Comment by lllyasviel** [comment]
https://github.com/lllyasviel/ControlNet-v1-1-nightly/issues/53#issuecomment-1537445844
