### ISSUE TITLE
[Bug]: Pickled yaml file??

### ISSUE THREAD

**Issue by GeneralAwareness** [Mikubill/sd-webui-controlnet#1218]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

 WARNING:fvcore.common.config:Loading config D:\stable-diffusion-webui-ux\extensions\sd-webui-controlnet\annotator\oneformer\configs/ade20k/oneformer_swin_large_IN21k_384_bs16_160k.yaml with yaml.unsafe_load. Your machine may be at risk if the file contains malicious content.

### Steps to reproduce the problem

Just use it.  I was instructed to come here because that is your file not the model dev for 2.1.  He didn't makes this one and had me come to report this suspicious activity.

### What should have happened?

No warning, no pickle,

### Commit where the problem happens

webui: Commit hash: 23d460d6cae4637add3676264d49b74a45422da7
controlnet: 1.1.150

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--theme dark --medvram --xformers --disable-safe-unpickle --port 9000 --api --opt-channelslast --always-batch-cond-uncond
```

### Console logs

```Shell
I no longer have this and what I typed above should suffice.
```

### Additional information

I never even knew a .yaml could be pickled but was just informed it can be just no real reason to do it.

**Comment by lllyasviel** [comment]
hello please move this to https://github.com/SHI-Labs/OneFormer/blob/4faa05f09cc9e1279aec164e5edc39336365552d/demo/README.md?plain=1#L5 if necessary
