### ISSUE TITLE
[Bug]: preprocess is too slow and always cause sd_webui error

### ISSUE THREAD

**Issue by LianShuaiLong** [Mikubill/sd-webui-controlnet#1229]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

preprocess is too slow and always cause sd_webui error

### Steps to reproduce the problem

1. click ControlNet v1.1.150
2. upload image
3. select Enable,Allow preview
4. select preprocessor: Canny and model:control_v11p_sd15_canny 
5.click "bloom"

### What should have happened?

process quickly

### Commit where the problem happens

webui: 
controlnet: 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
NONE
```

### Console logs

```Shell
NONE
```

### Additional information

NONE

**Comment by lllyasviel** [comment]
from the log it seems a network problem
