### ISSUE TITLE
Error with using Batch of img2img

### ISSUE THREAD

**Issue by EkaLinjas** [Mikubill/sd-webui-controlnet#123]
![image](https://user-images.githubusercontent.com/125619279/219521316-426bb422-f31f-4db2-8e70-2b04b18ce164.png)
After finishing the first image of batch, an error occured and stop the process in here.
Is the extension hasn't support the Batch function in img2img?

in case of bad demonstrate here is the part of UI i use during this issue
![image](https://user-images.githubusercontent.com/125619279/219522186-25ae289f-53fc-4569-9b36-c76e66177a72.png)

**Comment by Mikubill** [comment]
In settings tab, tick the "Do not append map to output" checkbox.
