### ISSUE TITLE
[Feat]: cache from previous preprocessing

### ISSUE THREAD

**Issue by jjangga0214** [Mikubill/sd-webui-controlnet#1238]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Hi.
This is actually a feature request. I'm sorry if there's another proper place to suggest. I'll make sure to forward this there then.

The extension analyses a given image every time. 
It may be great if it caches the result by hash. 
So it can pass duplicate calculations when the same image is given again with the same setting.

How do you think? 

Thanks.

### Steps to reproduce the problem

.

### What should have happened?

.

### Commit where the problem happens

.

### Command Line Arguments

```Shell
.
```

### Console logs

```Shell
.
```

**Comment by huchenlei** [comment]
#807 is intended to add caching for preprocessor results, but it did not made to merge, because of image hash issue.

If many people request this feature, I can try to submit a PR to implement it.

**Comment by jjangga0214** [comment]
@huchenlei Thanks for the reply.
This is a definitely helpful feature, especially for cases where the same base image is used and used again hundreds of times.
I sincerely request this feature.
Thank you so much.

**Comment by huchenlei** [comment]
Cache feature implemented in #1371.
