### ISSUE TITLE
[Bug]: Radio buttons on img2img tab behave weird

### ISSUE THREAD

**Issue by alexopus** [Mikubill/sd-webui-controlnet#1239]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

After updating ControlNet from v1.1.150 to v1.1.153 and also at the same time updating stable-diffusion-webui from 1.1.0 to 1.2.0, I see the following issue on the img2img tab:

https://github.com/Mikubill/sd-webui-controlnet/assets/25933468/e3871678-1ded-4717-9270-54d81acf7834

Clicking on the radio buttons for "Control Mode" and "Resize Mode" sometimes does not select them after the first click, but only after the second click. Instead, first click adds an "outline" that you can see in the video.

Also, selecting an item from Resize Mode sometimes deselects an item from Control Mode and vice versa.

**Everything works fine on the txt2img tab**, only img2img does this.
All other elements on the img2img page behave also normally.

Restarting everything did not help.

### Steps to reproduce the problem

1. Go to img2img controlnet window
2. Press on the radio buttons for "Control Mode" and/or "Resize Mode"
3. They will only be selected after second click. First click only gives them an outline.

### What should have happened?

Should be selected right away, as it correctly does in txt2img tab.

### Commit where the problem happens

webui: 1.2.0 b08500cec8a791ef20082628b49b17df833f5dda
controlnet: 1.1.53 b2f9c7353242162ae66a3453b0c7105aa95d6adc 

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
--enable-insecure-extension-access --medvram --no-half-vae --no-half --xformers --listen
```

### Console logs

```Shell
venv "D:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.2.0
Commit hash: b08500cec8a791ef20082628b49b17df833f5dda
Installing requirements
Installing requirements 1 for Infinite-Zoom

Installing SD-CN-Animation requirement: scikit-image==0.19.2



Installing requirements for TemporalKit extension

Launching Web UI with arguments: --enable-insecure-extension-access --medvram --no-half-vae --no-half --xformers --listen
ControlNet v1.1.153
ControlNet v1.1.153
Loading weights [f8bb2922e1] from D:\stable-diffusion-webui\models\Stable-diffusion\revAnimated_v122.safetensors
Creating model from config: D:\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: D:\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt
Applying xformers cross attention optimization.
No Image data blocks found.
No Image data blocks found.
No Image data blocks found.
No Image data blocks found.
No Image data blocks found.
No Image data blocks found.
No Image data blocks found.
No Image data blocks found.
No Image data blocks found.
Textual inversion embeddings loaded(16): aurate, bad-artist, bad-artist-anime, bad-hands-5, bad-image-v2-39000, bad-picture-chill-75v, bad_prompt, bad_prompt_version2, bad_quality, easynegative, mirko, mrmd, ng_deepnegative_v1_75t, prt, pureerosface_v1, vile_prompt3
Model loaded in 4.9s (load weights from disk: 0.6s, create model: 0.3s, apply weights to model: 0.6s, load VAE: 0.1s, load textual inversion embeddings: 3.3s).
Loading weights [f8bb2922e1] from D:\stable-diffusion-webui\models\Stable-diffusion\revAnimated_v122.safetensors
Creating model from config: D:\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: D:\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt
Applying xformers cross attention optimization.
No Image data blocks found.
No Image data blocks found.
No Image data blocks found.
No Image data blocks found.
No Image data blocks found.
No Image data blocks found.
No Image data blocks found.
No Image data blocks found.
No Image data blocks found.
Model loaded in 4.6s (load weights from disk: 0.1s, create model: 0.3s, apply weights to model: 0.7s, load VAE: 0.2s, load textual inversion embeddings: 3.3s).
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 20.1s (import torch: 1.2s, import gradio: 0.8s, import ldm: 0.4s, other imports: 0.7s, load scripts: 1.5s, create ui: 11.0s, gradio launch: 4.3s).
```

**Comment by lllyasviel** [comment]
cannot reproduce but may be related to a recent pull request about elem_id

**Comment by Trimad** [comment]
I am having the same issue.

**Comment by AugmentedRealityCat** [comment]
Same problem over here as well.

**Comment by imbrium201** [comment]
I found that this is resolved if I disable all non-builtin plugins (I had to specifically remove multidifusion-upscaler). This was working fine for me yesterday morning on a former 1.1.X version but after updating sd-webui-controlnet to 1.1.166 it has failed (gut feeling is its related to fix #1263 ). The extension removal is a workaround for now from this behavior on my 2 machines.

**Comment by AugmentedRealityCat** [comment]
> (I had to specifically remove multidifusion-upscaler)

I will try that, thanks ! 

Hopefully this will be resolved soon, I use multidiffusion for high resolution upscaling, which used to work very very well with ControlNet Tile and Tiled VAE.

**Comment by imbrium201** [comment]
> I have the multidiffusion-upscaler extension installed and enabled and cannot reproduce this. Running latest commit on webui dev branch and latest controlnet version (1.1.171 at this time).

I think youre correct. After re-evaluating my extension list one at a time (sigh) IT seems reproducible with SD-CN-Animation installed only. Running version 1.1.173 of control net and 8d63dd54 for CN-Animation.

**Comment by AugmentedRealityCat** [comment]
I confirm that the bug is related to the use of the SD-CN-Animation extension. I just tested with the latest version of both extensions. As soon as I uncheck that extension, the buttons work and display properly.

**Comment by alexopus** [comment]
Can confirm that disabling SD-CN-Animation resolves this issue. I opened one in their issue tracker: https://github.com/volotat/SD-CN-Animation/issues/109
