### ISSUE TITLE
Slider.update() error when selecting a preprocessor

### ISSUE THREAD

**Issue by dieki-n** [Mikubill/sd-webui-controlnet#125]
Everything works great as long as I don't select a preprocessor. As soon as I select one in the dropdown, I get  the following error:

  File "stablediffusionpath/venv/lib/python3.10/site-packages/gradio/routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "stablediffusionpath/venv/lib/python3.10/site-packages/gradio/blocks.py", line 983, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "stablediffusionpath/venv/lib/python3.10/site-packages/gradio/blocks.py", line 924, in postprocess_data
    prediction_value = postprocess_update_dict(
  File "stablediffusionpath/venv/lib/python3.10/site-packages/gradio/blocks.py", line 424, in postprocess_update_dict
    prediction_value = block.get_specific_update(update_dict)
  File "stablediffusionpath/venv/lib/python3.10/site-packages/gradio/blocks.py", line 265, in get_specific_update
    generic_update = cls.update(**generic_update)
TypeError: Slider.update() got an unexpected keyword argument 'mode'

The sliders also show an error in the UI:

![image](https://user-images.githubusercontent.com/8876807/219527456-18f677c3-461d-47bd-9805-77b7bdc1162b.png)
[controlnet error.webm](https://user-images.githubusercontent.com/8876807/219528130-26dec0d6-ddf2-421f-9e9b-87fce0c77db7.webm)

It will still generate images after the error, but the preprocessor doesn't run.

**Comment by Mikubill** [comment]
Update WebUI and gradio will fix this. Anyway I will add some workaround later.

**Comment by dieki-n** [comment]
I updated automatic1111 and gradio with the following, but I am still getting the error.

```
source ./venv/bin/activate
git pull
pip install -r requirements.txt --upgrade
pip install gradio --upgrade

```

**Comment by Mikubill** [comment]
Could you share some env details? Like `pip list`

**Comment by dieki-n** [comment]
Sure! See attached.

[piplist.txt](https://github.com/Mikubill/sd-webui-controlnet/files/10762927/piplist.txt)

**Comment by Mikubill** [comment]
Seems like the version of gradio locked at 3.9. Added some fix in https://github.com/Mikubill/sd-webui-controlnet/commit/623c5a44d64cd9d208e360a0a2f7382441c7aa4a and now it should work

**Comment by dieki-n** [comment]
Hm, that fix didn't work. But I force-upgraded gradio with

```pip install gradio==3.18.0```

And now it does work. Thank you!
