### ISSUE TITLE
[WinError 5] Access is denied

### ISSUE THREAD

**Issue by UnstableJail** [Mikubill/sd-webui-controlnet#1258]
Hello everyone,

I have a small question:
I downloaded the model from the Extension tab in A1111 and got this "access denied" error in cmd.
Is that a problem and if so how could I fix it ?

Error:
Installing collected packages: flatbuffers, pycparser, opencv-contrib-python, CFFI, sounddevice, mediapipe

stderr: ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\paulv\\stable-diffusion-webui\\venv\\Lib\\site-packages\\cv2\\cv2.pyd'
Check the permissions.

[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: C:\Users\paulv\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip

Warning: Failed to install mediapipe, some preprocessors may not work.
Installing sd-webui-controlnet requirement: svglib
Installing sd-webui-controlnet requirement: fvcore

**Comment by javi22020** [comment]
Same error here

**Comment by jorvilla84** [comment]
same here, no idea how to fix it.

**Comment by vanhapara** [comment]
The same
Installing collected packages: flatbuffers, pycparser, opencv-contrib-python, CFFI, sounddevice, mediapipe

stderr: ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied

**Comment by huchenlei** [comment]
I believe this is a duplicated issue of #1024. Running the commandline as Admin is likely to solve all access denied issue. If issue persists, you can always re-open this issue. Closing the issue for now.

**Comment by aearone** [comment]
> I believe this is a duplicated issue of #1024. Running the commandline as Admin is likely to solve all access denied issue. If issue persists, you can always re-open this issue. Closing the issue for now.

How do I run webui-user.bat as an administrator? When I try to run as administrator, the bat file opens and immediately closes.

**Comment by aearone** [comment]
> Run command line as admin first then navigate to sd folder and run user batVon meinem iPhone gesendetAm 23.05.2023 um 17:34 schrieb Nikolay L. ***@***.***>:﻿ I believe this is a duplicated issue of #1024. Running the commandline as Admin is likely to solve all access denied issue. If issue persists, you can always re-open this issue. Closing the issue for now. How do I run webui-user.bat as an administrator? When I try to run as administrator, the bat file opens and immediately closes. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

Thank you so much!

**Comment by aearone** [comment]
> > How do I run webui-user.bat as an administrator? When I try to run as administrator, the bat file opens and immediately closes.
> 
> `the bat file opens and immediately closes` occurs because at default, the cmd going to cd system32 then running the command from there.
> 
> try adding `cd /d %~dp0` at the first line of `webui-user.bat`,
> 
> and if you want to automate the right click create `webui-user.bat` shortcut, open shortcut properties > advanced > check `Run as administrator`
Hi! Thanks for the reply! I almost immediately figured out how to run webui as administrator. I just opened webui through the command line as administrator, manually specifying the path to the file. As I wrote earlier, running webui as administrator and reinstalling controlnet still gave me an error, so I just manually installed mediapipe the same way and the error disappeared, everything works.

**Comment by ELN23** [comment]
I always start automatic11111  via the launcher shortcut. If I doubleclick webui-user.bat or run it as admin cmd opens and starts the process but when it is finished automatic1111 doesnt open in my browser... How can I fix it? If that doesn't work I just can not start automatic1111 as an adim. And I need to do that, because I get the same "access denied" error.

**Comment by huchenlei** [comment]
When it finishes it will show an url that you can paste to your browser. The default url is http://localhost:7860

**Comment by EnergyMax1** [comment]
I solved this problem without running as admin. I just changed permissions of the problematic folder from READ to FULL CONTROL. It is in the folder's proprties, SECURITY tab.
