### ISSUE TITLE
controlnet without web-ui 

### ISSUE THREAD

**Issue by loboere** [Mikubill/sd-webui-controlnet#1262]
can you please make controlnet work without web-ui , since colab forbids using gradio and UIs it is not possible to use it with automatic1111, it would be better to use it from colab command line maybe with diffusers.
https://github.com/TheLastBen/fast-stable-diffusion/issues/2103
https://twitter.com/thechrisperry/status/1649428447138021376

**Comment by huchenlei** [comment]
You can already use ControlNet in other stable diffusion UIs, such as [ComfyUI](https://github.com/comfyanonymous/ComfyUI). 

This is the ControlNet WebUI extension repo, so probably request the feature on the UI repo you are using.

**Comment by awais-nayyar** [comment]
I am working on my MS research thesis, I want to implement controlnet in Stable Diffusion model, when i did R&D I found that we can implement controlnet with a web-ui of stable diffusion model like AUTOMATIC1111 or ComfyUI etc,
so my question is, Is there anyway to implement controlnet without web-ui, means with pytorch code?
if yes then where can i find the code of controlnet?
your help would be appreciated.
Thanks

**Comment by Ang-Wei-Liang** [comment]
https://github.com/lllyasviel/ControlNet

And

https://github.com/huggingface/diffusers
