### ISSUE TITLE
[Feature Request] Standalone ControlNet Batch Accordion

### ISSUE THREAD

**Issue by lllyasviel** [Mikubill/sd-webui-controlnet#1264]
Since we have succeeded in hacking the attention layers in SD, a mature and technically correct pipeline for handling multiple images is possible. ControlNet’s Batch should be improved a lot and then it can be applied to consistency between batch instances, like video frames and Multiview consistency.

We should move the current Batch out, and then let us have a standalone Accordion with title like “ControlNet Batch v1.1.1XX”. 

This Accordion should be turned off by default and users can turn it on – just like they enable multi-control.

Right now we should only have a batch path input in that Accordion, and a ``send loopback to i-th controlnet’’ Radio (or multi selection). This should be simple but will be good start.

But I am not very familiar with that part, @ljleb are you willing to make some codes to separate that Batch to an Accordion so we will begin to work on that?

**Comment by ljleb** [comment]
Will take a look shortly. I don't know how long this may take.

**Comment by FugueSegue** [comment]
This seems like a good idea. Although I can't help with writing code, I want to contribute the suggestion I made [here](https://github.com/Mikubill/sd-webui-controlnet/discussions/1314#discussion-5209731).
