### ISSUE TITLE
[Bug]: Incorrect color tones in images sometimes when doing "controlnet is more important" using reference pre-processor

### ISSUE THREAD

**Issue by Thawneflash** [Mikubill/sd-webui-controlnet#1279]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Controlnet 1.1.170v. Using "Controlnet is more important" still generates images perfect to the reference image styles compared to balanced mode so I think many would still prefer it for now

But sometimes it also gives images that are a lot darker in tone compared to the reference image. And sometimes there will be ones with the correct colors too. Its dependent on reference image used and prompts too I think. But usually darker ones will be there among a few color correct images. Also depends on the image reference used too. Some image references will produce lots of color correct images while others will produce fewer color correct images

![2](https://github.com/Mikubill/sd-webui-controlnet/assets/132301431/5f8cf42e-79b0-4d5b-86a9-b576bc0dd97d)
![1](https://github.com/Mikubill/sd-webui-controlnet/assets/132301431/e459a737-c202-47a1-bb9a-257f7967b55d)

Here is a comparison between two. You can notice the style looks super similar except for the color tones and maybe a little bit in degradation of image quality. This is not seen in color correct images.

### Steps to reproduce the problem

1. Select Controlnet is more important (Style slider does not matter I think, I kept it at 1)
2. Select pre-processor reference only, and tick pixel perfect. Select several reference images and generate a batch. The images will come broken but high-res fix will fix this issue. Among them u will notice some images have darker and dull tones compared to the reference image. But the ones with the color correct ones are nearly perfect.

### What should have happened?

Should have always produced color correct images and maintains image quality.

### Commit where the problem happens

webui: 
controlnet: 1.1.170v

### What browsers do you use to access the UI ?

Chrome

### Command Line Arguments

```Shell
--xformers
```

### Console logs

```Shell
Loading preprocessor: reference_only██████████████████████████████                     | 41/60 [00:55<00:29,  1.57s/it]
Pixel Perfect Mode Enabled.
resize_mode = ResizeMode.INNER_FIT
raw_H = 1600
raw_W = 1280
target_H = 704
target_W = 512
estimation = 563.2
preprocessor resolution = 563
  0%|                                                                                           | 0/20 [00:00<?, ?it/s]ControlNet used torch.float16 VAE to encode torch.Size([2, 4, 88, 64]).
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:26<00:00,  1.33s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:26<00:00,  1.32s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:26<00:00,  1.31s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 60/60 [01:20<00:00,  1.34s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 60/60 [01:20<00:00,  1.29s/it]
```

**Comment by lllyasviel** [comment]
see if https://github.com/Mikubill/sd-webui-controlnet/discussions/1280 fix this

**Comment by Thawneflash** [comment]
Using the new pre-processors do have correct colors but still not close to the reference image style in anime art atleast. Using "Controlnet is more important" yields the same color tone problem tho. Sometimes incorrect colors and sometimes correct colors. Let me show u a comparison to see it clearly

All of these used reference_adain+attn

**_Reference image:_**
![original](https://github.com/Mikubill/sd-webui-controlnet/assets/132301431/6b41915c-7242-49a4-90a0-be3c7c6c2932)

**_Controlnet is more important:_**
![working one](https://github.com/Mikubill/sd-webui-controlnet/assets/132301431/3d9c433d-c27a-4462-a276-5b14206a6ba3)

**_Balanced:_**
![balanced](https://github.com/Mikubill/sd-webui-controlnet/assets/132301431/2d0a45ec-2b4f-49ad-860b-ac9449aa58b3)

If you can notice, "Controlnet is more important" is more **loyal to the art style** of the reference image while balanced makes it more **detailed but less loyal.**


Using "Controlnet is more important" still gives incorrect tone images. Here is an example shown below. In this example you can see the 1st one has darker tones again. But the 2nd one has color correct tones. The 2nd image is the one I used above with high res fix to fix the destroyed image. 
![ve](https://github.com/Mikubill/sd-webui-controlnet/assets/132301431/4288d897-af4c-4d20-bd3d-77ad60b616c4)

**Comment by lllyasviel** [comment]
marked as wontfix with tech limitation

**Comment by Thawneflash** [comment]
Ah well that is okay. I think maybe the difference is too negligible to notice. It might get randomly fixed sometime in the future so I do look forward to updates.
