### ISSUE TITLE
[Documentation] Multi controlnet inpainting API Reference

### ISSUE THREAD

**Issue by ghpkishore** [Mikubill/sd-webui-controlnet#1290]
I have tried a lot to figure out how to get multi controlnet inpainting to work with A1111 API, and since I couldn't find out the exact code anywhere, I thought I will give what works for me. I check this but getting the same image from the web UI.

To get the understanding of what the variables in the payload are with respect to the webui, refer the ui.py file inside the modules folder (modules/ui.py).  

For example  in the img2img webui we have Mask Mode, which when searched in the ui.py will give you "inpainting_mask_invert" as the variable name. There is no need to pass mask in the controlnet argument   (Note: I haven't checked it yet for inpainting global harmonious, this holds true only for other modules). Also, I haven't necessarily given all inputs in the controlnet in the below example, but you can. 

```
import io
import cv2
import base64
import requests
import re
from PIL import Image


# A1111 URL
url = "http://127.0.0.1:7860"

def image_to_base64(image_path):
    with open(image_path, "rb") as image_file:
        encoded_image = base64.b64encode(image_file.read()).decode("utf-8")
        return encoded_image

# Example usage
input_path="Input.png"
mask_path = "Mask.png"
ref_path = "Ref.png" // This is the input to the controlnet

input_image=image_to_base64(image_path)
mask_image = image_to_base64(mask_path)
ref_image = image_to_base64(ref_path)

payload={
        "init_images" : [input_image],
        "prompt":"photo,Red white and Green colour scheme, christmas theme",
        "resize_mode": 0,
        "width": 512,
        "height": 512,
        "seed":1234,
        "steps": 20,
        "sampler_index": "Euler a",
        "denoising_strength": 1,
        "mask" : mask_image,
        "mask_blur" : 0,
        "inpainting_fill" : 0,
        "inpaint_full_res" : 0,
        "inpaint_full_res_padding" : 0,
        "inpainting_mask_invert" : 1,
        "alwayson_scripts": {
                "controlnet": {
                    "args": [
                        {
                            "input_image": [ref_image],
                            "module": "depth_zoe",
                            "model": "control_v11f1p_sd15_depth [cfd03158]",
                            "resize_mode": 0,
                            "processor_res": 512,
                        },
                        {
                            "input_image": [ref_image],
                            "module": "softedge_hedsafe",
                            "model": "control_v11p_sd15_softedge [a8575a2a]",
                            "resize_mode": 0,
                            "processor_res": 512,
                        }

                    ]
                }
            }

}

# Trigger Generation
response = requests.post(url=f'{url}/sdapi/v1/img2img', json=payload)

# Read results
r = response.json()
result = r['images'][0]
image = Image.open(io.BytesIO(base64.b64decode(result.split(",", 1)[0])))
image.save('output.png')
```

Hope this helps!

**Comment by tristanwqy** [comment]
you should add "enabled": true in each arg

**Comment by ghpkishore** [comment]
@tristanwqy are you sure? I got the above thing working without adding it. It is also not present in the API wiki.

**Comment by richadlee** [comment]
Today I tried using the controlnet net API, but it seems to have no effect. The generated image is the same as when controlnet is not used. I used the example code from the wiki.
import io
import cv2
import base64
import requests


from PIL import Image


# A1111 URL
url = "http://127.0.0.1:7860"

# Read Image in RGB order
img = cv2.imread(r'D:\controlnet\api\1.jpg')[:, :, ::-1]

# Encode into PNG and send to ControlNet
retval, bytes = cv2.imencode('.png', img)
encoded_image = base64.b64encode(bytes).decode('utf-8')

# A1111 payload
payload = {
    "prompt": 'a beautiful girl',
    "negative_prompt": "",
    "batch_size": 1,
    "steps": 25,
    "cfg_scale": 7,
    "alwayson_scripts": {
        "controlnet": {
            "args": [
                {
                    "enabled": True,
                    "input_image": encoded_image,
                    "module": "canny",
                    "model": "control_v11p_sd15_canny [d14c016b]",
                }
            ]
        }
    }
}


# Trigger Generation
response = requests.post(url=f'{url}/sdapi/v1/txt2img', json=payload)

# Read results
r = response.json()
result = r['images'][0]
image = Image.open(io.BytesIO(base64.b64decode(result.split(",", 1)[0])))
image.save('output.png')

**Comment by blacklig** [comment]
How many images are you getting as output from SD server? If CN is working you can easily tell that you will get like 2 outputs at least where one will be that masking map. Also if you turn on debug on SD, I am using vladmatic, you will see something like this:

09:24:09-433123 DEBUG    Script process: ['Steps animation', 'ControlNet']
Loading model from cache: control_v11f1p_sd15_depth [cfd03158]
Loading preprocessor: depth_leres
preprocessor resolution = 512
09:24:09-809244 DEBUG    Script before-process-batch: ['Steps animation', 'ControlNet']

that way you will see API is interacting with control net.

Anyways, I can confirm control net is working here, using whatever samples you are giving here as they are generally correct.
enabled: true is not necessary but doesnt harm :) you have to enable it in UI so it kinda "makes sense" to use it here as well but not needed actually.

**Comment by amanjain1397appy** [comment]
@blacklig @ghpkishore is it necessary to enable it in the UI first? I want to use 2 control net units in the img2img api, however by default only one unit is enabled, unless I manually change it in the UI and restart the service. Were you able to figure out a way to skip the UI changes altogether and do it via the api itself?

**Comment by ghpkishore** [comment]
The settings changes are necessary. They aren’t UI only  but are also needed for api. The key part to note is that even if you change once the setting are stored for when you restart henceforth. So this is a one time process

**Comment by BEpresent** [comment]
> @amanjain1397appy The settings changes are necessary. They aren’t UI only but are also needed for api. The key part to note is that even if you change once the setting are stored for when you restart henceforth. So this is a one time process

How can the settings be changed when I don't use the webui but start it with `--api --nowebui` ? It seems it uses one  controlnet model by default and I don't know how to change this.

**Comment by ghpkishore** [comment]
@BEpresent please refer to this:

> They aren’t UI only but are also needed for api. The key part to note is that even if you change once the setting are stored for when you restart henceforth. So this is a one time process.

This means first use the webui, go to settings, change the number of control models to whatever you want. Then restart the webui. Check whether all the necessary controlnet models are working. Once it is, then restart the entire process with the flag of --api --listen (listen is required if you want to use it with a specific url). Then multi controlnet starts working. For inpainting. Use the img2img api. Check the docs if in doubt. You can basically set all the UI parameters through the api: example, batchsize, maskblur etc. Again, check the docs, which will give you the exact key to use in your JSON object. 

> How can the settings be changed when I don't use the webui but start it with --api --nowebui ? It seems it uses one controlnet model by default and I don't know how to change this.

I do not think this is possible. The settings change is required. Else check what happens when you change the setting in the webui. I think the config should be stored somewhere. Go to the file where the config is stored and update the params there. I haven't done this and dont know if it is possible, but it seems to be the logical method. 

Hope this helps.

**Comment by BEpresent** [comment]
> @BEpresent please refer to this:
> 
> > They aren’t UI only but are also needed for api. The key part to note is that even if you change once the setting are stored for when you restart henceforth. So this is a one time process.
> 
> This means first use the webui, go to settings, change the number of control models to whatever you want. Then restart the webui. Check whether all the necessary controlnet models are working. Once it is, then restart the entire process with the flag of --api --listen (listen is required if you want to use it with a specific url). Then multi controlnet starts working. For inpainting. Use the img2img api. Check the docs if in doubt. You can basically set all the UI parameters through the api: example, batchsize, maskblur etc. Again, check the docs, which will give you the exact key to use in your JSON object.


Thanks! So it seems it is not possible to create via API right ? If I remember I created some hacky workaround, copying the settings file from another webui session that had the desired settings.
