### ISSUE TITLE
Diffusers support for Reference Only

### ISSUE THREAD

**Issue by koshian2** [Mikubill/sd-webui-controlnet#1291]
Reference Only is very interesting.
ControlNet 1.1 is supported by Diffusers, but is there any way to use Reference Only with Diffusers?
Is there any good code?

**Comment by NormXU** [comment]
I try to reimplement the ``reference only`` mode with Diffusers [here](https://github.com/NormXU/reference-only-mode)

Unfortunately, the pipeline is currently not working, and I have doubts about whether I correctly understand the idea behind ``reference_only``. 

I would greatly appreciate any suggestions or corrections regarding my re-implementation.

**Comment by NormXU** [comment]
Here is an [issue](https://github.com/huggingface/diffusers/pull/3435) working on the implementation

**Comment by iszotic** [comment]
Hi I trained a model with diffusers examples but it doesn't work with webui, https://github.com/huggingface/diffusers/tree/main/examples/controlnet

is related to this issue or do I have to open a new one?

**Comment by sudip550** [comment]
> Reference Only is very interesting. ControlNet 1.1 is supported by Diffusers, but is there any way to use Reference Only with Diffusers? Is there any good code?

Did you got answer to how to use reference only function with diffusers?

**Comment by djj0s3** [comment]
@sudip550  There's a few community pipelines here: https://github.com/huggingface/diffusers/blob/main/examples/community/README.md
for 1.5 and SDXL. 

> > Reference Only is very interesting. ControlNet 1.1 is supported by Diffusers, but is there any way to use Reference Only with Diffusers? Is there any good code?
> 
> Did you got answer to how to use reference only function with diffusers?
