### ISSUE TITLE
[Question]: How do I specify Style Fidelity for reference mode in the API?

### ISSUE THREAD

**Issue by entmike** [Mikubill/sd-webui-controlnet#1295]
How do I specify Style Fidelity for reference mode in the API?

I checked the examples, but given the recent addition of the `reference` processor, I suspect it's not been documented yet.  Any hint?

**Comment by kft334** [comment]
It uses threshold_a supposedly. I'm using that in my app and it does appear to work somewhat when using 'Balanced' mode but I can't say for sure since I've only tested it on one image.

**Comment by entmike** [comment]
> It uses threshold_a supposedly. I'm using that in my app and it does appear to work somewhat when using 'Balanced' mode but I can't say for sure since I've only tested it on one image.
> 
> ![Screenshot 2023-05-15 125821](https://user-images.githubusercontent.com/93904307/238418770-a391f826-663b-4444-b065-2cdc6a8a9b7c.png)
> 
> Top left is the reference image, the two below it are using threshold_a = 0.01 and the two on the right are using threshold_a = 1.0

Thanks for the tip!  And neat looking app!

**Comment by Haozhe-Xing** [comment]
Could someone tell what is the meaning of ‘threshold_a'?  I didn't find the same name ckpt such as canny

**Comment by PMykhailo** [comment]
> Could someone tell what is the meaning of ‘threshold_a'? I didn't find the same name ckpt such as canny

this is one of the parameters for any controlnet in the api. But for me it does not work like it should for some reasone. When I make threshold_a = 0,5 I don't get the same result as for style fidelity = 0.5
