### ISSUE TITLE
[Bug]: Error running the process

### ISSUE THREAD

**Issue by 4lt3r3go** [Mikubill/sd-webui-controlnet#1296]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/44883288/aff144a3-2b00-4667-a672-b32d9f01e5d8)

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

Error running process: F:\SD\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "F:\SD\modules\scripts.py", line 418, in process
    script.process(p, *script_args)
  File "F:\SD\extensions\sd-webui-controlnet\scripts\controlnet.py", line 984, in process
    self.enabled_units = self.get_enabled_units(p)
  File "F:\SD\extensions\sd-webui-controlnet\scripts\controlnet.py", line 943, in get_enabled_units
    unit = self.parse_remote_call(p, unit, idx)
  File "F:\SD\extensions\sd-webui-controlnet\scripts\controlnet.py", line 795, in parse_remote_call
    unit.enabled = selector(p, "control_net_enabled", unit.enabled, idx, strict=True)
AttributeError: 'list' object has no attribute 'enabled'

### Commit where the problem happens

webui: 
controlnet: 

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
no
```

**Comment by 4lt3r3go** [comment]
i've been using controlNET daily
after last Auto1111 pull i'm having this problem
i tryed reinstall everything, is still there

**Comment by Jetbleu** [comment]
I'm having the same issue, same error message, control net is not working anymore

**Comment by 519571754** [comment]
> i've been using controlNET daily after last Auto1111 pull i'm having this problem i tryed reinstall everything, is still there

Did you fix the problem, now my controlnet is not working

**Comment by vianseto** [comment]
Yeah, I also experienced this when using ControlNet version 1.1.170 and trying to use it via API. Here's an example of the payload:

`payload = {
  "sampler_name": "DPM++ 2M Karras",
  "prompt": _prompt,
  "negative_prompt": _negatice,
  "enable_hr": True,
  "denoising_strength": 0.7,
  "hr_scale": 1,
  "hr_upscaler": "4x-UltraSharp",
  "restore_faces": True,
  "seed": -1,
  "batch_size": 1,
  "n_iter": 1,
  "steps": 20,
  "cfg_scale": 8,
  "width": 512,
  "height": 768,
  "alwayson_scripts": {
    "controlnet": {
      "args": [
        { 
          "input_image": base64_string,
          "module": "openpose_full",
          "model": "control_v11p_sd15_openpose [cab727d4]"
        }
      ]
    }
  }
}`

**Comment by ApathyJones** [comment]
the [SD-CN-Animation] extension is causing this error. Remove it until it is updated.

**Comment by 4lt3r3go** [comment]
i remvoed sd-webui-segment-anything, as i read somewere else.. it works

**Comment by Jetbleu** [comment]
> the [SD-CN-Animation] extension is causing this error. Remove it until it is updated.

Thanks, disabling SD-CN-Animation did work for me

**Comment by vianseto** [comment]
I don't have SD-CN-Animation extension, but I still encounter the error.

**Comment by Jetbleu** [comment]
> I don't have SD-CN-Animation extension, but I still encounter the error.

My bad, I had to disable sd-webui-segment-anything too, 

Disabling SD-CN-Animation seems to fix the error for txt2img without controlnet 

Disabling sd-webui-segment-anything seems to fix the error when using controlnet

**Comment by sfkeeper** [comment]
I had same problem today, ControlNet 1.1.174
removing [sd-webui-segment-anything], solved!
