### ISSUE TITLE
[Major Update] Reference-only Control

### ISSUE THREAD

**Issue by seawater668** [Mikubill/sd-webui-controlnet#1299]
### Discussed in https://github.com/Mikubill/sd-webui-controlnet/discussions/1236

<div type='discussions-op-text'>

<sup>Originally posted by **lllyasviel** May 13, 2023</sup>
### Reference-Only Control

Now we have a `reference-only` preprocessor that does not require any control models. It can guide the diffusion directly using images as references.

(Prompt "a dog running on grassland, best quality, ...")
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/19834515/2d6441a4-aed5-402c-96b5-a7ccf55405e0)

This method is similar to inpaint-based reference but it does not make your image disordered. 

Many professional A1111 users know a trick to diffuse image with references by inpaint. For example, if you have a 512x512 image of a dog, and want to generate another 512x512 image with the same dog, some users will connect the 512x512 dog image and a 512x512 blank image into a 1024x512 image, send to inpaint, and mask out the blank 512x512 part to diffuse a dog with similar appearance. However, that method is usually not very satisfying since images are connected and many distortions will appear.

This `reference-only` ControlNet can directly link the attention layers of your SD to any independent images, so that your SD will read arbitary images for reference. You need at least ControlNet 1.1.153 to use it.

To use, just select `reference-only` as preprocessor and put an image. Your SD will just use the image as reference.

*Note that this method is as "non-opinioned" as possible. It only contains very basic connection codes, without any personal preferences, to connect the attention layers with your reference images. However, even if we tried best to not include any opinioned codes, we still need to write some subjective implementations to deal with weighting, cfg-scale, etc - tech report is on the way.*</div>

![2023-05-16 10-06-01 的屏幕截图](https://github.com/Mikubill/sd-webui-controlnet/assets/29244715/ca86b2c2-aa35-4163-a414-205b4d961db1)
![2023-05-16 10-02-30 的屏幕截图](https://github.com/Mikubill/sd-webui-controlnet/assets/29244715/cff808e5-7b5a-493e-be11-670b1b953cd0)
Follow the original picture in the discussion, the result is not the same as the author, what am I doing wrong？

**Comment by seawater668** [comment]
![2023-05-16 10-29-25 的屏幕截图](https://github.com/Mikubill/sd-webui-controlnet/assets/29244715/f1943294-7e48-4c06-b456-70fd183fda80)
Follow the original picture in the discussion, the result is not the same as the author, what am I doing wrong？

**Comment by seawater668** [comment]
@catboxanon 
Thank you for your hint, I performed the same operation as you said, but the result is still not the same as the author, for example, the color of the anime is not bright enough,
![2023-05-17 10-11-05 的屏幕截图](https://github.com/Mikubill/sd-webui-controlnet/assets/29244715/94012f90-a33a-4cf6-bbb8-eec7ddb698c2)
![2023-05-17 10-00-03 的屏幕截图](https://github.com/Mikubill/sd-webui-controlnet/assets/29244715/e13a50a2-6295-451b-bba9-6d5e162f5068)

**Comment by lllyasviel** [comment]
typical results of not loading correct vae
