### ISSUE TITLE
Clip skip = 2 & 3 x longer token ?

### ISSUE THREAD

**Issue by toyxyz** [Mikubill/sd-webui-controlnet#13]
According to lllyasviel's comment, models like Anyhing V3 require clip skip = 2, 3xlonger token. I wonder if this extension requires such extra work.
https://github.com/lllyasviel/ControlNet/discussions/12
![image](https://user-images.githubusercontent.com/8006000/218603679-b7f654cd-b87d-47c9-9e28-8465c6f4a23c.png)

**Comment by Mikubill** [comment]
Clip skip and longer token handling have already been taken care of by the WebUI and will be automatically applied when the features are enabled. (checkout the output log)

**Comment by toyxyz** [comment]
> Clip skip and longer token handling have already been taken care of by the WebUI and will be automatically applied when the features are enabled. (checkout the output log)

Oh I got it! Thank you.
