### ISSUE TITLE
Extension breaks img2img aspect ratio preview

### ISSUE THREAD

**Issue by slashedstar** [Mikubill/sd-webui-controlnet#130]

**Comment by Mikubill** [comment]
Hmm, any screenshots?

**Comment by neojam** [comment]
He probably meant the red rectangle that appears over images when you change width or height on img2img tab after importing an image. 
I've noticed that as well yesterday, but the problem seems fixed after I updated to the new version of your extention today.

Thanks btw for the great extension  :)

**Comment by slashedstar** [comment]
Oh wow, neither my description nor my comment were published, either way, its what neojam said, the rectangle still shows in inpainting but it isn't there in img2img
