### ISSUE TITLE
API use of reference_only causes crash

### ISSUE THREAD

**Issue by thot-experiment** [Mikubill/sd-webui-controlnet#1300]
When using controlnet via the API as [described here](https://github.com/Mikubill/sd-webui-controlnet/wiki/API#integrating-sdapiv12img) with the new `reference_only` controlnet 
```js
{
   "input_image": ref ,
   "guidance_end": 0.8,
   "module": "reference_only",
   "model": "none",
 } 
```

i get an `"UnetHook" has no property "control_params"` (this may not be the exact error, i'm writing it from memory) 

I have patched it by commenting out the following lines at the end of [hook.py](https://github.com/Mikubill/sd-webui-controlnet/blob/d831043cb81e97724ccf9f071da391d479440a77/scripts/hook.py#L528) which seems to have solved it

```python
        if hasattr(self, "control_params"):
            del self.control_params
```

I have no idea how any of this stuff works, so I'm sure by commenting these out I've broken something else. Hopefully someone with more insight into the arch here can help me come to a real fix.

**Comment by huaizong** [comment]
we have same sense, when webui raise exception, controlnet extendsion restore failure
