### ISSUE TITLE
text2img does not recognize reference only

### ISSUE THREAD

**Issue by Jpbonino** [Mikubill/sd-webui-controlnet#1303]
<img width="1060" alt="Captura de pantalla 2023-05-16 075017" src="https://github.com/Mikubill/sd-webui-controlnet/assets/81916559/511e3fb4-cd03-4c52-9126-a7afa2d45285">
hello friends ! Does anyone know why using all the default values when I put in controlnet reference only generates me an image as if it were only text to image ? thanks!

im using ControlNet v1.1.173 version
![Uploading Captura de pantalla 2023-05-16 075017.png…]()

**Comment by AvaCadava** [comment]
I can't get it to work, too.

**Comment by tavenhall1** [comment]
Same here. I've tried multiple computers and multiple installs of A1111 and CN. The generated image looks nothing like the CN image.

**Comment by Jpbonino** [comment]
> Same here. I've tried multiple computers and multiple installs of A1111 and CN. The generated image looks nothing like the CN image.

any news ?

**Comment by Jpbonino** [comment]
> I can't get it to work, too.

any news ?

**Comment by Arron17** [comment]
I would suggest re-submitting this as a bug report with the template and filling out all the details.

Without that information it's very hard for anyone to help you.

**Comment by M30W-git** [comment]
Same problem here today after updating everything !
Idk if it was working before because first time i'm trying this ! Other pre-processor works tho, i've managed to work with Canny for exemple, but "ref only" give me nothing similar to my image.

**Comment by rayofshadow23** [comment]
@Jpbonino which kind of GPU are you using? Also me i have the same issue and i have a AMD Radeon GPU

**Comment by tavenhall1** [comment]
It's finally working for me today after updating to the newest release (1.1.179)

**Comment by M30W-git** [comment]
> Same problem here today after updating everything ! Idk if it was working before because first time i'm trying this ! Other pre-processor works tho, i've managed to work with Canny for exemple, but "ref only" give me nothing similar to my image.
> 
> _P.S.: NVidia GeForce RTX 3070Ti - 8G_

Amazing ! It look like it's working for me as well now !! Thank you for your hard work ! <3
