### ISSUE TITLE
MacOS M1 Max - Using DeForum + ControlNet Preprocessors generates RuntimeError: Placeholder storage has not been allocated on MPS device!

### ISSUE THREAD

**Issue by Fedevoxlive** [Mikubill/sd-webui-controlnet#1304]
### **Is there an existing issue for this?**
- [x] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui
#1226 
#1128 

### **Premise**
As a MacOS M1 Max user, Implementing the suggested changes inside webui-user.sh in the line _export COMMANDLINE_ARGS="--skip-torch-cuda-test --no-half --use-cpu all"_ , allowed me to get back **full functionality** on SD overall, including DeForum. 

### **What happened?**
I tend to use Init elements, and everything works fine even when I enable the _Use Init_ command inside DeForum's Init tab with ControlNet enabled but with no Preprocessor loaded.
**The remaining issue is if I load any Preprocessor in ControlNet**. 
The moment I try to do so and click generate, DeForum crashes with RuntimeError: Placeholder storage has not been allocated on MPS device! As in the Screenshot below:
<img width="1837" alt="Screenshot 2023-05-16 at 11 27 17" src="https://github.com/Mikubill/sd-webui-controlnet/assets/19222477/25270f7e-e81a-41c1-8423-dba4a8de294f">

### **Steps to reproduce the problem**
- Launch SD webui
- Go to DeForum tab
- Enable _Use Init_ command and specify a valid path to your content
- Enable _ControlNet_ and paste the same valid path of your Init content inside _ControlNet Input Video/ Image Path_
- Load any Preprocessor inside ControlNet
- Click Generate

### **What should have happened?**
It should generate an animation using ControlNet models.

### **Commit where the problem happens**
webui: [v1.2.1] (https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/89f9faa63388756314e8a1d96cf86bf5e0663045)
deforum: [c96d4377](https://github.com/deforum-art/sd-webui-deforum/commit/c96d437708adc759a775ac086f0906724f2a1a00)
controlnet: [d831043c] 

### **What browsers do you use to access the UI ?**
Brave (Chromium based)

**Comment by littleyeson** [comment]
try edit COMMANDLINE_ARGS="--skip-torch-cuda-test --no-half --use-cpu all" to COMMANDLINE_ARGS="--skip-torch-cuda-test --no-half"

**Comment by DavidEscalante** [comment]
> try edit COMMANDLINE_ARGS="--skip-torch-cuda-test --no-half --use-cpu all" to COMMANDLINE_ARGS="--skip-torch-cuda-test --no-half"

but using "--skip-torch-cuda-test --no-half" re-enables the GPU, isnt the point of "--use-cpu all" to use only the CPU?

**Comment by istraw** [comment]
> 尝试将 COMMANDLINE_ARGS="--skip-torch-cuda-test --no-half --use-cpu all" 编辑为 COMMANDLINE_ARGS="--skip-torch-cuda-test --no-half"
修改后
TypeError: Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead.
