### ISSUE TITLE
REMOVED setting - Skip img2img processing when using img2img initial image - why?

### ISSUE THREAD

**Issue by Michaelvirga** [Mikubill/sd-webui-controlnet#1307]
Hello,

As the title states - I noticed that this setting was removed from ControlNET settings in A1111 - can anyone provide some insight into why, and if it is accessible somewhere else, where to access it? I do not see it anywhere.

If the feature was removed entirely, i am requesting that it be reinstated, as this is very much necessary for many workflows that do not want to do img2img processing before sending to ControlNET processing.

**Comment by lllyasviel** [comment]
hi you can set denoising strength to 1.0 and leave controlnet image as blank to achieve the previous effect.

**Comment by Michaelvirga** [comment]
Will this work with batch though?

**Comment by ljleb** [comment]
Controlnet batch replaces this feature and allows to control the images fed into individual models. This will soon be moved to its own accordion.
