### ISSUE TITLE
OpenPose replaces skeleton image with blank

### ISSUE THREAD

**Issue by Meta12314** [Mikubill/sd-webui-controlnet#131]
I've installed the extension with default path "sd-webui-controlnet" and decided to try out OpenPose preprocessor. The extension downloaded the OpenPose body and hand model pth files. When using the skeleton image for ControlNet and processing it, at the output it becomes black, and the final image is not affected by it at all.

More info:
- For testing were used pre-extracted [control_openpose-fp16.safetensors] and [diff_control_sd15_openpose_fp16.safetensors]
- Other preprocessors seem to be working, tried out Scribble and Canny and they are using the input image at least
- Using the current latest commit of webui
- Happens both on "txt2img" and "img2img".
- Tested on both Chrome and Firefox, with and without browser extensions
- With enabled and disabled command line args, including xformers
- Tested on several checkpoints, including base Stable Diffisuon 1.5, NAE and Any3
- Used my own skeleton image and skeleton image from this extension's repo page
- Tried out different resolutions, including base 512x512
- Reset canvas several times, tried out all available options, no avail.

The only thing I didn't try is reinstalling webui. Unless I am doing something horribly wrong, I can try that out tomorrow.

![OpenPose problem](https://user-images.githubusercontent.com/48676875/219540277-450b3220-2159-4271-8ca8-64410610d1d5.png)

**Comment by Mikubill** [comment]
Use `none` preprocessor/annotator

**Comment by Meta12314** [comment]
Is it described on main page or I am dumb?

**Comment by Mikubill** [comment]
Hmm currently no, docs is poor and PRs welcome.

**Comment by Meta12314** [comment]
Thank you for your swift response!
