### ISSUE TITLE
Where we can find more about API for different preprocessors?

### ISSUE THREAD

**Issue by blacklig** [Mikubill/sd-webui-controlnet#1313]
Hi, first of all thanks for hilarious models from control net! I am playing around with API which for most of the time I have no trouble with, but for example I want to control more of "depth_leres" preprocessor which in web UI has settings like this

<img width="511" alt="image" src="https://github.com/Mikubill/sd-webui-controlnet/assets/32385597/f482134b-d837-45c7-94f6-f7393466e85d">

and I totally dont know how to control them via API, because docs dont say much about using those "preprocessor specific" payloads...

<img width="956" alt="image" src="https://github.com/Mikubill/sd-webui-controlnet/assets/32385597/90625385-1a33-48af-b929-85843a15c684">

And what is worse, seems to me, at least this depth_leres is using different defaults via API than via Web UI.. because on web UI default is like 0% on both of those values, but from API call I am getting results simillar to if I set 50% and 50% to both of those values and I really dont know how to change those :) 

Does anyone know? Better yet, how to generally know what are variable names in json payload for all those preprocessors specific values that we see in Web UI? Any tips here?

Thanks

**Comment by lictex** [comment]
should be `threshold_a` & `threshold_b` for the two params
<details>
<summary>ranges and defaults can be found in <code>/controlnet/module_list</code></summary>

```
// ...
"depth_leres": {
  "sliders": [
    {
      "name": "Preprocessor Resolution",
      "min": 64,
      "max": 2048,
      "value": 512
    },
    {
      "name": "Remove Near %",
      "min": 0,
      "max": 100,
      "value": 0,
      "step": 0.1
    },
    {
      "name": "Remove Background %",
      "min": 0,
      "max": 100,
      "value": 0,
      "step": 0.1
    }
  ]
},
// ...
```
</details>

**Comment by blacklig** [comment]
Oh wow! You are my hero.

I actually knew about those parameters but I thought those are not them as I thought each model can have more than 2 so I thought there must be even something else.. also their defaults are 64 which perfectly matches why my depth map was giving me basically only black and white useless mask..

With proper usage of treshold_a and treshold_b everything works as expected.

Thanks again

**Comment by blacklig** [comment]
Anyways, do you know about how to turn "pixel perfect" option on for control net? That is also visible on UI and dont know what actually accepts it via JSON payload.

Something like processor_res maybe? set to 0 maybe? But dont know it.. just guessing

**Comment by lictex** [comment]
just `"pixel_perfect": true`
actually i remember this is documented somewhere but... cannot find it anymore
think maybe it was in the old removed `/controlnet/txt2img` api docs

**Comment by blacklig** [comment]
thanks :)

**Comment by ljleb** [comment]
`"pixel_perfect"` now documented. Note that it is not an option for the /controlnet/detect route because it requires 2 input images to work.
