### ISSUE TITLE
ControlNet inpaing with image pattern

### ISSUE THREAD

**Issue by segalinc** [Mikubill/sd-webui-controlnet#1318]
Hello everyone,
I am trying to find a way that starting from img2img inpaint, I select a mask on the image and somehow using controlNet I can inpaint that region with an image  containing a pattern to replicate the pattern in it

any idea?

thanks in advance for all the help and hints

**Comment by lllyasviel** [comment]
reference preprocessor should work in inpaint just like all other CNs

**Comment by lllyasviel** [comment]
"inpaint whole image" should just work for ref preprocessor
"inpaint only mask" would need user to align the ref to the mask position using other tools like Photoshop before put it in SD

**Comment by segalinc** [comment]
ok I can try that thanks
another thing, is it possible also to sue controlnet to just change pose of a person in a image ?
thanks again

**Comment by lllyasviel** [comment]
you can use multi-controlnet in the setting

**Comment by lllyasviel** [comment]
update - it is now supported officially in 1.1.178
https://github.com/Mikubill/sd-webui-controlnet/discussions/1280#discussioncomment-5944492

**Comment by segalinc** [comment]
oh awesome I'll try it now!
