### ISSUE TITLE
[Bug]: Generate API Silent fail

### ISSUE THREAD

**Issue by spacewalkingninja** [Mikubill/sd-webui-controlnet#1322]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

```

This program is tested with 3.10.6 Python, but you have 3.8.7.
If you encounter an error with "RuntimeError: Couldn't install torch." message,
or any other error regarding unsuccessful package (library) installation,
please downgrade (or upgrade) to the latest version of 3.10 Python
and delete current Python and "venv" folder in WebUI's directory.

You can download 3.10 Python from here: https://www.python.org/downloads/release/python-3109/

Alternatively, use a binary release of WebUI: https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases

Use --skip-python-version-check to suppress this warning.
==============================================================================================================
Python 3.8.7rc1 (tags/v3.8.7rc1:e320109, Dec  7 2020, 16:42:32) [MSC v.1927 64 bit (AMD64)]
Commit hash: <none>
Installing requirements for Web UI

Launching Web UI with arguments: --api
No module 'xformers'. Proceeding without it.
ControlNet v1.1.173
ControlNet v1.1.173
Loading weights [6ce0161689] from C:\Users\Admin\Desktop\stable-diffusion-webui-master\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Creating model from config: C:\Users\Admin\Desktop\stable-diffusion-webui-master\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying cross attention optimization (Doggettx).
Textual inversion embeddings loaded(0):
Model loaded in 5.5s (create model: 0.6s, apply weights to model: 1.3s, apply half(): 1.3s, move model to device: 1.0s, load textual inversion embeddings: 1.2s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Total progress: 100%|███████████████████████| 20/20 20/20 [00:13<00:00,  1.48it/s]
Total progress: 100%|███████████████████████| 20/20 [00:12<00:00,  1.57it/s]
```

When running test api code 
```

# A1111 payload
payload = {
    "prompt": 'a handsome man',
    "negative_prompt": "",
    "batch_size": 1,
    "steps": 20,
    "cfg_scale": 7,
    "alwayson_scripts": {
        "controlnet": {
            "args": [
                {
                    "input_image": encoded_image,
                    "module": "canny",
                    "model": "control_v11p_sd15_canny [d14c016b]",
                }
            ]
        }
    }
}

```

### Steps to reproduce the problem

Run test python api code on stable diffusion checkpoint: [6ce0161689]

### What should have happened?

Shouldda create canny image, load controlnet modules, models, etc,
INSTEAD
it creates random image, noticeably NOT canny image

### Commit where the problem happens

webui: d831043c  and 8d84f1f7 
controlnet: 1.1

### Command Line Arguments

```Shell
api enabled
```

### List of enabled extensions

Sadtalker, latest,
sd-webui-controlnet, latest

LDSR built-in
Lora built-in
ScuNET built-in
SwinIR built-in
prompt-bracket-checker built-in

### Console logs

```Shell
I tried to revert to old api format as well and i got pydantic class errors
```

![output_canny-control](https://github.com/Mikubill/sd-webui-controlnet/assets/27017759/2cc409af-7ff4-45b3-9210-8c0c92052497)
![output](https://github.com/Mikubill/sd-webui-controlnet/assets/27017759/34ffc972-62d6-4ed3-af01-53605f342ef7)

**Comment by spacewalkingninja** [comment]
Everything is working fin on webui tho, been working fine all along. What fails is really when I try to call controlnet from the api.
First I tried the new format which is described in the api, and it failed always, never even calls the controlnet models. 
THEN
I tried to edit my api.py file and restore the old format, but something pydantic related made the extension crash, so I decided to ask here as you know the code better.

**Comment by ljleb** [comment]
Which version of the webui are you using? The webui prints "Commit hash: <none>" and you shared 2 times the same commit for the controlnet repo. If you are not up to date, please update the webui and try again.

**Comment by spacewalkingninja** [comment]
Mikubill/sd-webui-controlnet:

webui: https://github.com/Mikubill/sd-webui-controlnet/commit/d831043cb81e97724ccf9f071da391d479440a77 and https://github.com/Mikubill/sd-webui-controlnet/commit/8d84f1f74f89ff29f3ef0af833d7b354b9b21da8

automat111c / SD : 6ce0161689b3853acaa03779ec93eafe75a02f4ced659bee03f50797806fa2fa (This the full hash of what appears in the footer)

you want **ME** to update automat111c sd?

**Comment by ljleb** [comment]
Each of these commits give me:

- `fatal: ambiguous argument '6ce01616': unknown revision or path not in the working tree.`
- `fatal: ambiguous argument 'd831043': unknown revision or path not in the working tree.`

In any case, please update your webui if it is not on this commit: https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/89f9faa63388756314e8a1d96cf86bf5e0663045

**Comment by BrofessorNFT** [comment]
Mine does not fail, but also does not recognize control net during the API call. I think it may be something related to the version of AUTO 1111 that you are using

**Comment by 2424004764** [comment]
Has the problem been resolved? I also encountered this problem

**Comment by mengcius** [comment]
same problem

**Comment by garment-chan** [comment]
Same problem.
I try both ways
1、/controlnet/txt2img
2、/sdapi/v1/txt2img
api doesn't work

**Comment by luicenh** [comment]
maybe you should set "weight" :1 in "args"

**Comment by huchenlei** [comment]
Setting enabled: true in control net args should solve the problem.
