### ISSUE TITLE
Understanding sd-webui models

### ISSUE THREAD

**Issue by timegate** [Mikubill/sd-webui-controlnet#1326]
In my view, there are two typical pipelines as follows.

1. Setting stable diffusion checkpoint and do img2img, txt2img, etc..
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/16134605/fbcdaa1d-d427-4e0c-ad98-08efa57afc37)

2. Setting controlnet model and do controlnet-seg, controlnet-dpeth, etc..
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/16134605/387197fa-5190-4c27-a3bd-acd17d611bff)

As far as I know, controlnet models (ex. cotrolnet-seg) are already trained (fine-tuned) from base stable diffusion. Then does it mean that a trained controlnet checkpoint already have the all parts that the stable diffusion checkpoint has?

And when we use controlnet units, "the stable diffusion checkpoint (v1-5-pruned-emaonly.safetensors)" is ignored? or, the checkpoint is used for locked part?
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/16134605/7dd2f85e-2efa-4829-8881-af16bdf8aac4)

Lastly, is it ok to put a trained custom model (from https://github.com/lllyasviel/ControlNet/blob/main/docs/train.md) to controlnet unit?

**Comment by lllyasviel** [comment]
1.sd base models in controlnet ckpt will be ignored 2.yes

**Comment by timegate** [comment]
@lllyasviel Thanks so much!
