### ISSUE TITLE
[Bug]: Quality degradation when using modified separate hires fix prompts

### ISSUE THREAD

**Issue by catboxanon** [Mikubill/sd-webui-controlnet#1340]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

**Preface**: this is an upcoming change for the webui that's only part of the dev branch currently. I'm opening this issue now in preparation of this being merged into master. https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/ff0e17174f8d93a71fdd5a4a80a4629bbf97f822

---

When inputting a separate **different** prompt into the hires fix prompt, ControlNet's quality is severely degraded. This only occurrs when ControlNet is used, and only ever when the hires fix prompt(s) differ from the main prompt(s).

### Steps to reproduce the problem

Generated images below have their metadata retained so they can be replicated. SD model hash is of course irrelevant as the same issue can be seen on all models.

<details>
<summary>ControlNet input image</summary>

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/122327233/730aa17e-2c6f-4758-84f9-b8679c727b48)
</details>

<details>
<summary>No separate hires fix prompt (good result)</summary>

![ef1ff5531c5153ee9bf5e9290abe46d0d8e2b769f30b5bbe5b8d646017d28020](https://github.com/Mikubill/sd-webui-controlnet/assets/122327233/ac399cc3-3bb5-4c12-a265-eb10b002da3c)
</details>

<details>
<summary>Separate hires fix prompt (bad result)</summary>

![cf3cb918e72d0419223272f3e5f2047547780b639e6e0026992eb41ff3f46cbb](https://github.com/Mikubill/sd-webui-controlnet/assets/122327233/f2b5281f-989d-4950-849e-f47e85affabd)
</details>

### What should have happened?

ControlNet quality should not be hampered by this change.

### Commit where the problem happens

webui: https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/39ec4f06ffb2c26e1298b2c5d80874dc3fd693ac
controlnet: https://github.com/Mikubill/sd-webui-controlnet/commit/ce2278d5bcf1801c6a2e6c3cb7bcb345c05275fe

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
No
```

### List of enabled extensions

ControlNet (https://github.com/Mikubill/sd-webui-controlnet/commit/ce2278d5bcf1801c6a2e6c3cb7bcb345c05275fe)

### Console logs

```Shell
n/a
```

**Comment by lllyasviel** [comment]
Fixed in https://github.com/Mikubill/sd-webui-controlnet/pull/1351
Please test 1.1.184 and see if fixed - I am not familiar with the new logic
