### ISSUE TITLE
[Announcement] Issue is under attack

### ISSUE THREAD

**Issue by lllyasviel** [Mikubill/sd-webui-controlnet#1359]
Beginning from yesterday, the GitHub issue of ControlNet Webui Extension is under attack and many unrelated issues/advertisements are in the “closed” issues.

Please help us by report these to GitHub. You can check the posts in recently closed issues, find those attacks, and report a GitHub abuse.

Thank you for your continued support - we'll do our best to avoid being disrupted by attacks.

**Comment by ljleb** [comment]
Does anyone know why these malicious issues are opened? Is sd-webui-controlnet the only target?
