### ISSUE TITLE
Can we control control net more?

### ISSUE THREAD

**Issue by blacklig** [Mikubill/sd-webui-controlnet#1372]
Hi, hope I am not spamming here - maybe I should post it elsewhere? If so, please instruct me, kinda new here.

Anyways - my question is - can we somehow control what for example canny map will give us?

I mean sure, it makes kinda lines from image, I cont control tresholds etc, but that is all and sometimes results arent what I would expect.

Like for example - I create canny map of kinda empty room, so it basically draws just edges, windows etc, but then it generates like mostly around those edges. Like it is extremely difficult to tell it "now generate into that empty space something new yet hold the main lines".. because it thinks, aa, this is empty space, so he wants this empty space to remain empty.. and he wants me to draw something about those lines.. that is how I feel canny map model (or actually all of control net models) work. Which is cool and has it use cases for sure, I love control net, dont get me wrong, but is there way to extend its capabilities? Some another extension that generates new canny maps based on input canny map for example? Or somehow tell model to be more creative on canny map creation etc?

What I think would work best would be even generating canny map further. Something like impainting where I would provide that canny map and told it "add table" or something like that.. and that "extended" canny map I would then provide to model and generate complex image based on this extended canny map. 

I hope it makes sense :). Actually img2img where canny map is provided doesnt work like it would extend that provided canny map. It just generates some quite useless outputs.

Like this is my normal canny map:

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/32385597/6eb8c7e7-4766-4cf4-b75f-7d435ed7e56b)

and now I would love to know some approach how to instruct models like "add table" to give me something like this for example:

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/32385597/97374f63-a4cc-4d8a-a24c-b489530eeb09)

**Comment by lllyasviel** [comment]
it seems that your example is a typical use case for multi controlnet. see also the setting to use multi controlnet at the same time. you probably need to use a canny controlnet and a scribble controlnet at the same time

**Comment by kft334** [comment]
Have a look at my program. You have to do a bit of work but it does exactly what you're asking for and keeps all your 'scene objects' organized. https://kfs334.itch.io/prompt-crafter-organizer

**Comment by blacklig** [comment]
> it seems that your example is a typical use case for multi controlnet. see also the setting to use multi controlnet at the same time. you probably need to use a canny controlnet and a scribble controlnet at the same time

Ok, that is interesting idea, might be right direction, like use canny map as input into scribble model, but I dont think as multi control net but as one inputs another, which isnt multi control, is it?

But anyways, this is still missing one step I need to solve - how to generate that modified canny map, or scribble input or how do we call it.. Like in my example I drew that table by hand just to ilustrate what I want to achieve from original canny map. But I want this to be generated somehow. Like to input that canny map into some model and tell him "add table there", or maybe somehow detect "empty" area and do some form of inpainting or whatereve.. I really am out of ideas what could be used here to achieve that.

Any ideas? :)

**Comment by kft334** [comment]
If by hand you mean drawing the objects yourself then no, it doesn't have to be by hand. Objects can be created with transparency from existing images.

**Comment by blacklig** [comment]
I mean like that somehow I need to interfere with that workflow. My ideal would be script that would just run itself from A to Z.. like extend canny map or scribble map according to prompt or something like that.

**Comment by lllyasviel** [comment]
canny model aleady does that. if in some areas there is no edges, the model will assume the area is a smooth surface OR let other controlnet to control that area if you enable another CN

**Comment by lllyasviel** [comment]
that is why many people use multi-controlnet, you can just leave blank in control maps

**Comment by blacklig** [comment]
> OR let other controlnet to control that area if you enable another CN

That is very interesting.. I had experience that, yes, it takes area as smooth and doenst do much with that, but if another control net then filll up that empty space, that is very interesting info for me.

But anyway, in your example with dogs, how did you achieve that background behind them? 

Anyways, even though your info is worth the consideration, I still think it wont do what I want from it - like to generate something new into that canny map. Even though I could use like new canny map as input, how would I get that "second" canny map in first place? Placing something manually and manually deciding where is that empty space is not option for me.

For my usecase, I am trying go generate interiors, where if it takes canny map edges of an empty room, how do I tell to model to fill that empty space with for example furniture? That is what I struggle with. I can for sure create by hand mask area and then do impainting and that works really well, but that is all too much of manual process. I would love to have this automatic and somehow tell model - look, there is canny map, now generate into empty space furniture for example. It can take multiple steps if necessary, but I still dont know how to do it.

So like that second dog in your example would be furniture - but were you able to generate that second dog without YOU manually placing it not overlying the first dog for example etc? Or knowing that first dog isnt already 90%of image etc.. hope you get where I am pointing :)

And thanks for your valuable advices, really appreciate you are taking time for helping me and hopefuly even others to understand your awesome models better.

**Comment by lllyasviel** [comment]
hello if your prompt is strong enough, the effect will be similar to a second CN and black regions will be filled with prompt contents
