### ISSUE TITLE
webui controlnet run well, bug img2img/txt2img api is not found

### ISSUE THREAD

**Issue by oHuflying** [Mikubill/sd-webui-controlnet#1376]
I install sd 1.2.1 and controlnet, terminal with `--api `and enable `Allow other script to control this extension`，but FastAPI not found `http://127.0.0.1:7860/controlnet/img2img`, use python to request will return `{'detail': 'Not Found'}`，when i use webui, controlnet run no problem.

**Comment by Hetaneko** [comment]
_`API Update: The /controlnet/txt2img and /controlnet/img2img routes have been removed. Please use the /sdapi/v1/txt2img and /sdapi/v1/img2img routes instead.`_

[Wiki](https://github.com/Mikubill/sd-webui-controlnet/wiki/API)
