### ISSUE TITLE
FileNotFoundError: no such file: /path/to/t2iadapter_sketch_sd14v1.yaml

### ISSUE THREAD

**Issue by gymdreams** [Mikubill/sd-webui-controlnet#1390]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

What is the correct way to install the T2I preprocessors? I have downloaded and installed the models.

I can’t find the `clip_vision` preprocessor but I have found `t2ia_style_clipvision` in the dropdown, so I assume that’s the same thing.

Here are the complete error log:

```
Loading preprocessor: canny
preprocessor resolution = 512
Loading model: t2iadapter_style_sd14v1 [202e85cc]
Loaded state_dict from [/path/to/stable-diffusion-webui/extensions/sd-webui-controlnet/models/t2iadapter_models/t2iadapter_style_sd14v1.pth]
ERROR: ControlNet cannot find model config [/path/to/stable-diffusion-webui/extensions/sd-webui-controlnet/models/t2iadapter_models/t2iadapter_style_sd14v1.yaml]
ERROR: ControlNet will use a WRONG config [/path/to/stable-diffusion-webui/extensions/sd-webui-controlnet/models/t2iadapter_sketch_sd14v1.yaml] to load your model.
ERROR: The WRONG config may not match your model. The generated results can be bad.
ERROR: You are using a ControlNet model [t2iadapter_style_sd14v1] without correct YAML config file.
ERROR: The performance of this model may be worse than your expectation.
ERROR: If this model cannot get good results, the reason is that you do not have a YAML file for the model.
Solution: Please download YAML file, or ask your model provider to provide [/path/to/stable-diffusion-webui/extensions/sd-webui-controlnet/models/t2iadapter_models/t2iadapter_style_sd14v1.yaml] for you to download.
Hint: You can take a look at [/path/to/stable-diffusion-webui/extensions/sd-webui-controlnet/models] to find many existing YAML files.

Loading config: /path/to/stable-diffusion-webui/extensions/sd-webui-controlnet/models/t2iadapter_sketch_sd14v1.yaml
Error running process: /path/to/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
Traceback (most recent call last):


Loading config: /path/to/stable-diffusion-webui/extensions/sd-webui-controlnet/models/t2iadapter_sketch_sd14v1.yaml
Error running process: /path/to/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
Traceback (most recent call last):
  File "/path/to/stable-diffusion-webui/modules/scripts.py", line 417, in process
    script.process(p, *script_args)
  File "/path/to/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 1024, in process
    model_net = self.load_control_model(p, unet, unit.model, unit.low_vram)
  File "/path/to/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 687, in load_control_model
    model_net = self.build_control_model(p, unet, model, lowvram)
  File "/path/to/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 767, in build_control_model
    network = network_module(
  File "/path/to/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/adapter.py", line 73, in __init__
    self.config = OmegaConf.load(config_path)
  File "/path/to/stable-diffusion-webui/venv/lib/python3.10/site-packages/omegaconf/omegaconf.py", line 187, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/stable-diffusion-webui/extensions/sd-webui-controlnet/models/t2iadapter_sketch_sd14v1.yaml'
```

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

Things to work out of box

### Commit where the problem happens

webui: https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/1e30ae895e487b1b4b81033db14863c702d26268
controlnet: https://github.com/Mikubill/sd-webui-controlnet/commit/bccb1a1d067ca21301e473171de72bc48e194417

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
COMMANDLINE_ARGS="--skip-torch-cuda-test --upcast-sampling --opt-sub-quad-attention --use-cpu interrogate --api --no-half --no-half-vae"
```

### List of enabled extensions

<img width="1094" alt="Screenshot 2023-05-22 at 12 08 39 PM" src="https://github.com/Mikubill/sd-webui-controlnet/assets/133461943/53fca36c-bb0d-4d40-b93f-dd7dcfaacb81">

multidiffusion-upscaler-for-automatic1111 | https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111 | dc3f5031 (Sat May 20 13:42:27 2023) | unknown
-- | -- | -- | --
openpose-editor | https://github.com/fkunn1326/openpose-editor | d74fdd72 (Tue May 2 09:49:03 2023) | unknown
sd-webui-controlnet | https://github.com/Mikubill/sd-webui-controlnet | bccb1a1d (Sun May 21 13:31:33 2023) | unknown
sd-webui-regional-prompter | https://github.com/hako-mikan/sd-webui-regional-prompter.git | ef9d50a6 (Sat May 20 23:20:29 2023) | unknown
stable-diffusion-webui-promptgen | https://github.com/AUTOMATIC1111/stable-diffusion-webui-promptgen | 84e58b5d (Fri Jan 20 11:15:12 2023) | unknown
ultimate-upscale-for-automatic1111 | https://github.com/Coyote-A/ultimate-upscale-for-automatic1111 | 756bb505 (Fri May 5 00:22:21 2023) | unknown
LDSR | built-in |   |  
Lora | built-in |   |  
ScuNET | built-in |   |  
SwinIR | built-in |   |  
prompt-bracket-checker

### Console logs

```Shell
Loading preprocessor: canny
preprocessor resolution = 512
Loading model: t2iadapter_style_sd14v1 [202e85cc]
Loaded state_dict from [/path/to/stable-diffusion-webui/extensions/sd-webui-controlnet/models/t2iadapter_models/t2iadapter_style_sd14v1.pth]
ERROR: ControlNet cannot find model config [/path/to/stable-diffusion-webui/extensions/sd-webui-controlnet/models/t2iadapter_models/t2iadapter_style_sd14v1.yaml]
ERROR: ControlNet will use a WRONG config [/path/to/stable-diffusion-webui/extensions/sd-webui-controlnet/models/t2iadapter_sketch_sd14v1.yaml] to load your model.
ERROR: The WRONG config may not match your model. The generated results can be bad.
ERROR: You are using a ControlNet model [t2iadapter_style_sd14v1] without correct YAML config file.
ERROR: The performance of this model may be worse than your expectation.
ERROR: If this model cannot get good results, the reason is that you do not have a YAML file for the model.
Solution: Please download YAML file, or ask your model provider to provide [/path/to/stable-diffusion-webui/extensions/sd-webui-controlnet/models/t2iadapter_models/t2iadapter_style_sd14v1.yaml] for you to download.
Hint: You can take a look at [/path/to/stable-diffusion-webui/extensions/sd-webui-controlnet/models] to find many existing YAML files.

Loading config: /path/to/stable-diffusion-webui/extensions/sd-webui-controlnet/models/t2iadapter_sketch_sd14v1.yaml
Error running process: /path/to/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
Traceback (most recent call last):


Loading config: /path/to/stable-diffusion-webui/extensions/sd-webui-controlnet/models/t2iadapter_sketch_sd14v1.yaml
Error running process: /path/to/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
Traceback (most recent call last):
  File "/path/to/stable-diffusion-webui/modules/scripts.py", line 417, in process
    script.process(p, *script_args)
  File "/path/to/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 1024, in process
    model_net = self.load_control_model(p, unet, unit.model, unit.low_vram)
  File "/path/to/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 687, in load_control_model
    model_net = self.build_control_model(p, unet, model, lowvram)
  File "/path/to/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 767, in build_control_model
    network = network_module(
  File "/path/to/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/adapter.py", line 73, in __init__
    self.config = OmegaConf.load(config_path)
  File "/path/to/stable-diffusion-webui/venv/lib/python3.10/site-packages/omegaconf/omegaconf.py", line 187, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/stable-diffusion-webui/extensions/sd-webui-controlnet/models/t2iadapter_sketch_sd14v1.yaml'
```
```


### Additional information

Mainly trying to use style transfer. Thanks!

**Comment by lllyasviel** [comment]
you deleted yaml files?

**Comment by lllyasviel** [comment]
Do not use folder t2iadapter_models. Please follow official installation instructions. See also the readme for how to install t2i adapter models.

**Comment by gymdreams** [comment]
> you deleted yaml files?

I didn’t delete yaml files. Should I reinstall?


> Do not use folder t2iadapter_models. Please follow official installation instructions. See also the readme for how to install t2i adapter models.

I have since moved the models out of the folder into the /models folder but have the same issue

**Comment by lllyasviel** [comment]
The support for T2I adapter style and clipvision is tested everyday.
If you encounter problems with missing files, consider reinstall and only follow official instructions of using T2I adapters in the readme.

**Comment by gymdreams** [comment]
> The support for T2I adapter style and clipvision is tested everyday. If you encounter problems with missing files, consider reinstall and only follow official instructions of using T2I adapters in the readme.

Ok. I did follow the instructions. My guess is that you are referring to this:

> Download files from https://huggingface.co/TencentARC/T2I-Adapter/tree/main/models
> Put them in "stable-diffusion-webui\extensions\sd-webui-controlnet\models".
> Make sure that the file names of pth files and yaml files are consistent.

I am specifically wondering about `Make sure that the file names of pth files and yaml files are consistent.` - how would I know what yaml files to point to the models? Do I rename the yaml files or rename the models? Assuming that I’m using the Tencent models.

**Comment by lllyasviel** [comment]
can you share a screenshot about the files that confuse you?

**Comment by gymdreams** [comment]
Update, I just performed a completely new install of the extension, then added all the models (and t2i), and it’s now working. 

Regarding `clip_vision`, I should be using `t2ia_style_clipvision`, yes? I see that there are 10+ pth models but only 3 preprocessors. Do I need to rename anything?

I see now in my fresh install that these files are consistent. It wasn’t before. 😅

But still the dropdown only shows 3 t2ia preprocessors so I think that’s why there are some confusion on my part. For example, if i want to use t2iadapter_canny, do i just use the regular canny?

```
t2iadapter_canny_sd14v1.pth
t2iadapter_canny_sd14v1.yaml
t2iadapter_canny_sd15v2.pth
t2iadapter_canny_sd15v2.yaml
t2iadapter_color_sd14v1.pth
t2iadapter_color_sd14v1.yaml
t2iadapter_depth_sd14v1.pth
t2iadapter_depth_sd14v1.yaml
t2iadapter_depth_sd15v2.pth
t2iadapter_depth_sd15v2.yaml
t2iadapter_keypose_sd14v1.pth
t2iadapter_keypose_sd14v1.yaml
t2iadapter_openpose_sd14v1.pth
t2iadapter_openpose_sd14v1.yaml
t2iadapter_seg_sd14v1.pth
t2iadapter_seg_sd14v1.yaml
t2iadapter_sketch_sd14v1.pth
t2iadapter_sketch_sd14v1.yaml
t2iadapter_sketch_sd15v2.pth
t2iadapter_sketch_sd15v2.yaml
t2iadapter_style_sd14v1.pth
t2iadapter_style_sd14v1.yaml
t2iadapter_zoedepth_sd15v1.pth
t2iadapter_zoedepth_sd15v1.yaml
```

<img width="254" alt="Screenshot 2023-05-22 at 1 01 38 PM" src="https://github.com/Mikubill/sd-webui-controlnet/assets/133461943/a3bc1a4f-7a01-49bd-85e2-000608b4db50">

**Comment by lllyasviel** [comment]
yes canny and others are same.

**Comment by gymdreams** [comment]
Are these the correct settings? As a test, I put in an image with a predominant single color palette but the results look nothing like it. Or rather, it’s as if nothing has been applied. I toggle enable and disable and nothing seems to change for the output. If I use the t2ia_color_grid, I can see that the colors are applied. Just that for style, nothing appears to do anything. 

The CN preview also looks different to other CN models, which usually have recognizable previews (e.g. open pose, softhed, etc). Is the style preview supposed to look like this, or is there something wrong?

<img width="552" alt="Screenshot 2023-05-22 at 1 20 15 PM" src="https://github.com/Mikubill/sd-webui-controlnet/assets/133461943/c9bdac5b-f71a-4005-9881-0eca2d162f31">

There are no errors in console.

**Comment by lllyasviel** [comment]
you can test if it works by fixing a random seed and compare the result with or without it enabled.
the preview image is designed by Tencent in that look.

**Comment by gymdreams** [comment]
> you can test if it works by fixing a random seed and compare the result with or without it enabled. the preview image is designed by Tencent in that look.

I did what you asked and the results are indeed different, that’s a really good tip! Btw, please let me know where I can send you some tips for coffee. I know how tough it is to maintain an open source project and I’d like to show some appreciation.

Thanks for your help!
