### ISSUE TITLE
[Bug]: Warning: Failed to install svglib, some preprocessors may not work

### ISSUE THREAD

**Issue by kiskasiska** [Mikubill/sd-webui-controlnet#1399]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I have installed ControlNet v1.1.189 and saw this in terminal: Warning: Failed to install svglib, some preprocessors may not work.

I did something wrong? when I was installing control net and pushed "Apply and restart" my SD tab was reloading too long time and I did just closed it and then restart terminal...

how can I fix it?

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

if there are no warnings in terminal it would be great

### Commit where the problem happens

webui: 
controlnet: 

version: [v1.2.1](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/89f9faa63388756314e8a1d96cf86bf5e0663045)  •  python: 3.10.11  •  torch: 2.0.1  •  xformers: N/A  •  gradio: 3.29.0  •  checkpoint: [e1441589a6](https://google.com/search?q=e1441589a6f3c5a53f5f54d0975a18a7feb7cdf0b0dee276dfc3331ae376a053)

### What browsers do you use to access the UI ?

Apple Safari

### Command Line Arguments

```Shell
Launching Web UI with arguments: --skip-torch-cuda-test --upcast-sampling --no-half-vae --use-cpu interrogate
No module 'xformers'. Proceeding without it.
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
ControlNet v1.1.189
ControlNet v1.1.189
```

### List of enabled extensions

![IMG_9692](https://github.com/Mikubill/sd-webui-controlnet/assets/134323958/ac77fbed-8bb2-4413-98ac-649803cf3927)

### Console logs

```Shell
Installing sd-webui-controlnet requirement: svglib
Couldn't install sd-webui-controlnet requirement: svglib.
Command: "/Users/+++++++++/Documents/stable-diffusion/stable-diffusion-webui/venv/bin/python3.10" -m pip install svglib --prefer-binary
Error code: 1
stdout: Collecting svglib
  Using cached svglib-1.5.1-py3-none-any.whl
Collecting lxml
  Using cached lxml-4.9.2-cp310-cp310-macosx_13_0_arm64.whl
Collecting cssselect2>=0.2.0
  Using cached cssselect2-0.7.0-py3-none-any.whl (15 kB)
Collecting tinycss2>=0.6.0
  Using cached tinycss2-1.2.1-py3-none-any.whl (21 kB)
Collecting reportlab
  Using cached reportlab-4.0.0-py3-none-any.whl (1.9 MB)
Collecting webencodings
  Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Collecting rlPyCairo<1,>=0.2.0
  Using cached rlPyCairo-0.2.0-py3-none-any.whl (10 kB)
Requirement already satisfied: pillow>=9.0.0 in ./venv/lib/python3.10/site-packages (from reportlab->svglib) (9.4.0)
Collecting freetype-py<2.4,>=2.3.0
  Using cached freetype_py-2.3.0-py3-none-macosx_10_9_universal2.whl (1.7 MB)
Collecting pycairo>=1.20.0
  Using cached pycairo-1.23.0.tar.gz (344 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: pycairo
  Building wheel for pycairo (pyproject.toml): started
  Building wheel for pycairo (pyproject.toml): finished with status 'error'
Failed to build pycairo

stderr:   error: subprocess-exited-with-error

  × Building wheel for pycairo (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-13-arm64-cpython-310
      creating build/lib.macosx-13-arm64-cpython-310/cairo
      copying cairo/__init__.py -> build/lib.macosx-13-arm64-cpython-310/cairo
      copying cairo/__init__.pyi -> build/lib.macosx-13-arm64-cpython-310/cairo
      copying cairo/py.typed -> build/lib.macosx-13-arm64-cpython-310/cairo
      running build_ext
      Package cairo was not found in the pkg-config search path.
      Perhaps you should add the directory containing `cairo.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'cairo' found
      Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.15.10']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycairo
ERROR: Could not build wheels for pycairo, which is required to install pyproject.toml-based projects

[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: pip install --upgrade pip


Warning: Failed to install svglib, some preprocessors may not work.
```

### Additional information

please tell me how to fix the problem...

**Comment by kiskasiska** [comment]
> (EDIT: On Linux) Manual installation of svglib:
> 
> Once you are in terminal, you can install svglib `sudo pip install svglib`
> 
> That is, if "pip" is available, which can be achieved by installing `sudo apt install python3-pip`
> 
> Then try to restart webui.
> 
> Background on PIP and how to install and use it on all platforms: [https://pip.pypa.io/en/stable/user_guide/](url)

thanks for the help, I tried to follow the instructions, but this is what appeared in the terminal:

sudo pip install svglib
Password: I entered
sudo: pip: command not found

sudo apt install python3-pip
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.

do I need to instal Java now?

**Comment by lindsayfowler** [comment]
@kiskasiska if you're on a Mac M1, you probably need to install it with:
`sudo pip3 install svglib`

**Comment by lindsayfowler** [comment]
I installed svglib successfully using the above line, but Stable Diffusion still complains that it is not installed and some things will not work. I figure SD is running in its own environment. How do I find the environment and enter it to install svglib manually in the SD environment?

**Comment by lindsayfowler** [comment]
@kiskasiska I got it working:

**install pip**
Open the Mac Terminal app via the Launchpad. In the Terminal, type `python -m ensurepip` or `python3 -m ensurepip` and press Enter. If PIP is missing, ensurepip will install PIP. Follow any additional on-screen instructions to complete this process.

**Install home-brew** 
If you don't have home-brew installed, you'll need it to install Cairo, which is needed for svglib.
[https://docs.brew.sh/Installation](https://docs.brew.sh/Installation) gives some info, but you may need to follow a video if unsure, because it's not so straightforward. You need to read the terminal output carefully.

**Install Cairo**
`brew install cairo`

**install svglib**
`pip install svglib`

**Comment by kiskasiska** [comment]
> 



> @kiskasiska I got it working:
> 
> **install pip** Open the Mac Terminal app via the Launchpad. In the Terminal, type `python -m ensurepip` or `python3 -m ensurepip` and press Enter. If PIP is missing, ensurepip will install PIP. Follow any additional on-screen instructions to complete this process.
> 
> **Install home-brew** If you don't have home-brew installed, you'll need it to install Cairo, which is needed for svglib. https://docs.brew.sh/Installation gives some info, but you may need to follow a video if unsure, because it's not so straightforward. You need to read the terminal output carefully and follow the instructions it gives to "add brew to path".
> 
> **Install Cairo** `brew install cairo`
> 
> **install svglib** `pip install svglib`

wow that works! thank you! SD started with ControlNet extension without any warnings of errors in my warp terminal

**Comment by simwiki** [comment]
I fixed itby this way:

1. run command below on linux
sudo apt install libcairo2-dev

2. install svglib package manually or relaunch webui
pip install svglib

**Comment by recoilme** [comment]
Is it possible run from sudo (sudo apt install libcairo2-dev) on runpod?
i try:
!apt install libcairo2-dev
!pip install svglib
!apt install -y python3-cairo && \
apt install -y python3-dev && \
apt install -y python3-cairo-dev
and so on, same error for controlnet
```
      cairo/bufferproxy.c:32:10: fatal error: Python.h: No such file or directory
         32 | #include <Python.h>
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycairo
Failed to build pycairo
ERROR: Could not build wheels for pycairo, which is required to install pyproject.toml-based projects
```

**Comment by cindy9923** [comment]
我也遇到了同样的问题，我通过找到anaconda的 include文件夹中的 Python.h文件解决了这个问题
