### ISSUE TITLE
I'm not able to get walk cycle pose correct probably due to open pose not saving info on joint depth

### ISSUE THREAD

**Issue by PudyJapan** [Mikubill/sd-webui-controlnet#1400]
Hi,

So I have a walk cycle that I want to replicate while generating. I have two problems, one of them is the shoulder pose.

The shoulders are mostly on the same level especially on the third frame, but the model creates it so that the right shoulder is nearer to the camera than the left soldier.

I tried several models and I mostly get this problem.

The other dominant problem is the knee and feet positioning.

As for feet positioning I understand because the model doesn't include that, however the right knee is not bent at all like it should be.

I thought of using the depth map and it solved the 2 problems, but the character itself took the shape of the original source material, and I don't want that, I only want the pose.

I think this is solvable if open pose somewhat encodes the depth of the joints or if we have a new model that just extracts the depth of the joints (neck, shoulders, elbows, hands, knees, etc..) and try to enforce the depth relativity of the joints to the generated image. And with multi-control net, the 2d open pose can be a 3d pose with this new suggested model.

Those are just thoughts of course and I might be doing things the wrong way and my interpretation might be completely off.

If anyone has some thoughts on this it would be much appreciated.

Thanks for advance.

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/13039210/8f102abf-e39e-4c67-9867-84f803b25631)
original

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/13039210/ed786e8d-4d37-417f-82a9-c1694560305c)
generated poses

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/13039210/18a0fa5f-bfba-4c90-9861-799d70270e7d)
generated image using openpose control net model

**Comment by khill25** [comment]
I'm struggling with exactly this problem and still unsure how to fix it. I've had limited success horizontally flipping the skeleton image. Is there a setting I'm missing to get depth information for the joints/bones?
