### ISSUE TITLE
the color of the input image affects the output of txt2img if it is not deleted.

### ISSUE THREAD

**Issue by loboere** [Mikubill/sd-webui-controlnet#141]
using the canny model you load an image X then press generate, it will generate the canny image and the final image will have some color of the input image X.
if you then use only the generated canny image as input and activate Scribble Mode (Invert colors) the color will be random.
that can give a headache to someone who wants different colors than the original input image.

**Comment by Mikubill** [comment]
Enable scribble mode is required for correct result with canny mode and white background
related: https://github.com/Mikubill/sd-webui-controlnet/issues/84
