### ISSUE TITLE
Missing ControlNet Unit 0 and ControlNet Unit 1 tabs

### ISSUE THREAD

**Issue by zuckingit** [Mikubill/sd-webui-controlnet#1412]
**Description:**
我正在遇到一个问题，我无法在我的项目中找到"ControlNet Unit 0"和"ControlNet Unit 1"选项卡。目前，我只能看到"单图像"和"批处理"两个选项，上面没有其他选项卡。我已经验证了所有的软件组件都是最新的。

I am experiencing an issue where I am unable to find the ControlNet Unit 0 and ControlNet Unit 1 tabs in my project. Currently, the only options available to me are "single image" and "batch," with no additional tabs above them. I have verified that all my software components are up to date.

**Steps to Reproduce:**
1. Open the project/application.
2. Navigate to the relevant section where ControlNet Unit tabs should be present.
3. Observe that only "single image" and "batch" options are available.

**Expected Behavior:**
I should see the ControlNet Unit 0 and ControlNet Unit 1 tabs alongside the "single image" and "batch" options.

**Actual Behavior:**
The ControlNet Unit 0 and ControlNet Unit 1 tabs are missing, and only "single image" and "batch" options are visible.

**Additional Information:**
- I have double-checked that all my software components, including dependencies, are up to date.
- I have not made any recent changes to the project that could have caused this issue.
- I have tried restarting the application, but the issue persists.

**Environment:**
- Operating System: Windows 10
- Software Version: [sd-webui-controlnet](https://github.com/Mikubill/sd-webui-controlnet) v1.1.190

**Screenshots
![Screenshot_35](https://github.com/Mikubill/sd-webui-controlnet/assets/134475964/f688b805-cddf-4c4e-8ab8-73ed252be364)
:**

**Comment by ljleb** [comment]
multi controlnet units is a slider in the options. just raise the value, reatart the ui and enjoy.

**Comment by winstonma** [comment]
@ljleb I faced this issue when I came to this place.

Then I find video showing how to set [multiple controlnet](https://youtu.be/WZg3e6B2yPQ?t=199). Just watch that 50 second and it should do it.
