### ISSUE TITLE
[Bug]: Reference_only not work

### ISSUE THREAD

**Issue by jackylive** [Mikubill/sd-webui-controlnet#1414]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

The Reference_only Preprocessor of CN 1.1.89 fails to present the results correctly.

### Steps to reproduce the problem

I followed the instructions in the manual precisely

### What should have happened?

The results are not displayed as shown in the manual.

### Commit where the problem happens

webui: 1.2.1
controlnet: 1.1.189

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--lowvram --xformers --opt-sub-quad-attention --theme dark
```

### List of enabled extensions

multidiffusion-upscaler-for-automatic1111
sd-webui-3d-open-pose-editor
sd-webui-aspect-ratio-helper
sd-webui-controlnet
sd-webui-llul
sd-webui-lora-block-weight
stable-diffusion-webui-images-browser
ultimate-upscale-for-automatic1111

### Console logs

```Shell
Launching Web UI with arguments: --lowvram --xformers --opt-sub-quad-attention --theme dark
ControlNet v1.1.189
ControlNet v1.1.189
Image Browser: ImageReward is not installed, cannot be used.
Loading weights [9c03252bea] from E:\stable-diffusion-webui\models\Stable-diffusion\braBeautifulRealistic_v40.safetensors
Create LRU cache (max_size=16) for preprocessor results.
Create LRU cache (max_size=16) for preprocessor results.
Creating model from config: E:\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying sub-quadratic cross attention optimization.
Textual inversion embeddings loaded(2): easynegative, pureerosface_v1
Model loaded in 4.2s (load weights from disk: 0.8s, create model: 1.1s, apply weights to model: 1.4s, apply half(): 0.9s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Create LRU cache (max_size=16) for preprocessor results.
Startup time: 15.5s (import torch: 3.0s, import gradio: 1.8s, import ldm: 0.9s, other imports: 1.6s, setup codeformer: 0.2s, load scripts: 2.5s, create ui: 5.1s, gradio launch: 0.3s).
```

### Additional information

![2023-05-24 145841](https://github.com/Mikubill/sd-webui-controlnet/assets/4900424/4d40bd8b-0417-4a67-8b97-5f96a69e036f)

![2023-05-24 145923](https://github.com/Mikubill/sd-webui-controlnet/assets/4900424/21de7188-847b-4712-a5f3-3650a8a7f197)

**Comment by AmitShashi** [comment]
true its not working for all

**Comment by Joeyd348039** [comment]
Any luck with this? I have the same problem.

**Comment by cvar66** [comment]
Same problem, anyone find out how to fix this? looks like this was posted weeks ago and still not fixed an no response from devs... great.

**Comment by cvar66** [comment]
I even tried uninstalling, deleting the folder and reinstalling. Same problem using latest most up to date version.  : (

**Comment by Joeyd348039** [comment]
> I even tried uninstalling, deleting the folder and reinstalling. Same problem using latest most up to date version. : (

Same here. Rolled back my Nvidia driver too and no luck. The PreProcessor Preview works fine when I check it. I think on the older version that part didn't work but the images came out great. I tried it in Automatic1111, DirectML, and Vlads fork. No luck.
Sometimes it seems to pick up a part of the image but it's small like 5% of the structure that's in the image rather than the style that's in it. 

Wish I had everything saved properly so I could try rolling back to the original Controlnet and give it a try to see what happens.

I miss it.. was my favorite thing in Stable Diffusion.
