### ISSUE TITLE
[Bug]: batch_hijack error when set batch > 1 , use batch = 1 runs ok

### ISSUE THREAD

**Issue by xxaier** [Mikubill/sd-webui-controlnet#1417]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

error

### Steps to reproduce the problem

I use mac m2
batch_hijack error when set batch > 1 , use batch = 1 runs ok

### What should have happened?

runs ok

### Commit where the problem happens

controlnet: 54f7c64b4dc4a4206e76a152651d5f0b0fac248f
webui: 

version: [v1.2.1-9-g0c9f8a6](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/0c9f8a6c02c2507b11403ddf50f7a845598d66a1)  • 

 python: 3.10.11  •  torch: 2.0.1  •  xformers: N/A  •  
gradio: 3.29.0  •  

checkpoint: [d819c8be6b](https://google.com/search?q=d819c8be6bc2a15307640a7eb069fa92e4c69c84289d8309273760ee7394e5f0)

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
Launching Web UI with arguments: --disable-safe-unpickle --lyco-dir=/Users/z/git/stable-diffusion-webui/models/LyCORIS --skip-torch-cuda-test --upcast-sampling --no-half-
vae --use-cpu interrogate
```

### List of enabled extensions

a1111-sd-webui-lycoris | ssh://git@github.com/KohakuBlueleaf/a1111-sd-webui-lycoris | b0d24ca6 (Wed May 17 00:19:32 2023) | 未知
adetailer | ssh://git@github.com/Bing-su/adetailer.git | b63205b4 (Mon May 22 03:57:26 2023) | 未知
openpose-editor | ssh://git@github.com/fkunn1326/openpose-editor | d74fdd72 (Tue May 2 09:49:03 2023) | 未知
sd-dynamic-prompts | ssh://git@github.com/adieyal/sd-dynamic-prompts | b88e1159 (Wed May 24 08:05:38 2023) | 未知
sd-webui-controlnet | ssh://git@github.com/Mikubill/sd-webui-controlnet.git | 54f7c64b (Wed May 24 03:07:30 2023) | 未知
stable-diffusion-webui-chinese | ssh://git@github.com/VinsonLaro/stable-diffusion-webui-chinese | 0af4e05b (Sun May 14 09:03:21 2023) | 未知
stable-diffusion-webui-wd14-tagger | ssh://git@github.com/toriato/stable-diffusion-webui-wd14-tagger.git | a9eacb1e (Wed Jan 25 14:47:36 2023) | 未知
LDSR | built-in |   |  
低秩微调模型(LoRA) | built-in |   |  
ScuNET | built-in |   |  
SwinIR | built-in |   |  
prompt-bracket-checker | built-in |  

<br class="Apple-interchange-newline">扩展插件	网址	版本	更新
a1111-sd-webui-lycoris	ssh://git@github.com/KohakuBlueleaf/a1111-sd-webui-lycoris	b0d24ca6 (Wed May 17 00:19:32 2023)	未知
adetailer	ssh://git@github.com/Bing-su/adetailer.git	b63205b4 (Mon May 22 03:57:26 2023)	未知
openpose-editor	ssh://git@github.com/fkunn1326/openpose-editor	d74fdd72 (Tue May 2 09:49:03 2023)	未知
sd-dynamic-prompts	ssh://git@github.com/adieyal/sd-dynamic-prompts	b88e1159 (Wed May 24 08:05:38 2023)	未知
sd-webui-controlnet	ssh://git@github.com/Mikubill/sd-webui-controlnet.git	54f7c64b (Wed May 24 03:07:30 2023)	未知
stable-diffusion-webui-chinese	ssh://git@github.com/VinsonLaro/stable-diffusion-webui-chinese	0af4e05b (Sun May 14 09:03:21 2023)	未知
stable-diffusion-webui-wd14-tagger	ssh://git@github.com/toriato/stable-diffusion-webui-wd14-tagger.git	a9eacb1e (Wed Jan 25 14:47:36 2023)	未知
LDSR	[built-in](http://127.0.0.1:7860/)		
低秩微调模型(LoRA)	[built-in](http://127.0.0.1:7860/)		
ScuNET	[built-in](http://127.0.0.1:7860/)		
SwinIR	[built-in](http://127.0.0.1:7860/)		
prompt-bracket-checker	[built-in](http://127.0.0.1:7860/)

### Console logs

```Shell
Traceback (most recent call last):
  File "/Users/z/git/stable-diffusion-webui/modules/call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "/Users/z/git/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/Users/z/git/stable-diffusion-webui/modules/txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "/Users/z/git/stable-diffusion-webui/modules/processing.py", line 526, in process_images
    res = process_images_inner(p)
  File "/Users/z/git/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "/Users/z/git/stable-diffusion-webui/modules/processing.py", line 680, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "/Users/z/git/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 252, in process_sample
    return process.sample_before_CN_hack(*args, **kwargs)
  File "/Users/z/git/stable-diffusion-webui/modules/processing.py", line 907, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "/Users/z/git/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 377, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "/Users/z/git/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 251, in launch_sampling
    return func()
  File "/Users/z/git/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 377, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "/Users/z/git/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/z/git/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/sampling.py", line 594, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/Users/z/git/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/z/git/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 167, in forward
    devices.test_for_nans(x_out, "unet")
  File "/Users/z/git/stable-diffusion-webui/modules/devices.py", line 156, in test_for_nans
    raise NansException(message)
modules.devices.NansException: A tensor with all NaNs was produced in Unet. This could be either because there's not enough precision to represent the picture, or because
 your video card does not support half type. Try setting the "Upcast cross attention layer to float32" option in Settings > Stable Diffusion or using the --no-half comman
dline argument to fix this. Use --disable-nan-check commandline argument to disable this check.
```

**Comment by xxaier** [comment]
I found because this plugin https://github.com/Bing-su/adetailer/issues/78 + sd-webui-controlnet will cause this my error

**Comment by Mistborn-First-Era** [comment]
@xxaier 
Yes, I never had this problem then I installed adetailer and started getting this issue.

**Comment by dalmackay** [comment]
> @xxaier Yes, I never had this problem then I installed adetailer and started getting this issue.
> 
> Edit: it has been fixed

I just started getting this error when I got adetailer. Everything up to date
