### ISSUE TITLE
[Bug]: change() and other events can only be called within a blocks context

### ISSUE THREAD

**Issue by RunXiaoLi** [Mikubill/sd-webui-controlnet#1420]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

This problem occurs when text2img is called through the api

### Steps to reproduce the problem

text2img error

### What should have happened?

text2img error

### Commit where the problem happens

webui: 
controlnet: 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
text2img error
```

### List of enabled extensions

text2img error

### Console logs

```Shell
text2img error
```

**Comment by huchenlei** [comment]
Closing as no sufficient context is given.

**Comment by RunXiaoLi** [comment]
How do I fix this error, which is the same as any other normal request, some requests have this error
