### ISSUE TITLE
[Feature]: Do not return ControlNet images via API

### ISSUE THREAD

**Issue by andypotato** [Mikubill/sd-webui-controlnet#1432]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When creating images via the API using ControlNet, the control images will be sent back as part of the result images array. While this may be useful in some cases, most of the time it is just unnecessary data traffic.

Therefore I suggest to have an option to remove the control images from the resulting images array, similar to how the A1111 API already has a "send_images" parameter.

### Steps to reproduce the problem

Create any txt2img or img2img API request with a ControlNet module enabled.

### What should have happened?

See feature request description - returning the original control images via the API should be optional.

### Commit where the problem happens

Feature request

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--api
```

### List of enabled extensions

ControlNet

### Console logs

```Shell
No logs necessary
```

**Comment by MagicReader** [comment]
I want it too

**Comment by Dadacticiel** [comment]
Hello ! As a workaround, i added those lines in stable diffusion webui code to remove controlnet images in api response.
File **stable-diffusion-webui\modules\api\api.py**, around line 448, add the try/except segment :
```     
        if not img2imgreq.include_init_images:
            img2imgreq.init_images = None
            img2imgreq.mask = None
            try:
                for index, controlnet_arg in enumerate(img2imgreq.alwayson_scripts["ControlNet"]["args"]):
                    if "image" in controlnet_arg and controlnet_arg["image"] is not None and "image" in controlnet_arg["image"]:
                        img2imgreq.alwayson_scripts["ControlNet"]["args"][index]["image"]["image"] = None
            except AttributeError:
               pass

**Comment by wasa4587** [comment]
here's an example
```
{
...,
       "alwayson_scripts": {
         "controlnet": {
           "args": [
             {
               "input_image": openposeBase64,
               "model": "control_v11p_sd15_openpose [cab727d4]",
               save_detected_map: true,
               "pixel_perfect": false
             },
             {
                "input_image": depthBase64,
                "model": "control_v11f1p_sd15_depth [cfd03158]",
                save_detected_map: true,
                "pixel_perfect": false
            } 
           ]
         }
       }
}
```
