### ISSUE TITLE
[Bug]: Loopback checkbox does not work

### ISSUE THREAD

**Issue by neuralweights** [Mikubill/sd-webui-controlnet#1433]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I tried looping through generated images in ControlNet with no success. Tried txt2img, img2img with denoise 1 and img2img loopback script. The runs with fixed seed are the same, with ticked checkbox or not. Should be different if controlnet takes the generated picture.

### Steps to reproduce the problem

Run batch size 1 batch count 4 with fixed seed and txt2img or img2img controlnet checkbox "Loopback" activated or off

### What should have happened?

Different images for the runs

### Commit where the problem happens

webui: newest vlad1111
controlnet: newest

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
none (SDP enabled, no ToMe)
```

### List of enabled extensions

openOutpaint + vlad standard extensions

### Console logs

```Shell
No errors produced
```

**Comment by ljleb** [comment]
batch count and img2img batch tab each have their own batch loop. Controlnet relies on the loop of the latter, not the former, to select the first image. Please use controlnet batch or the img2img batch tab for this checkbox to take effect.

**Comment by ljleb** [comment]
We need to refactor the ui to make the usage easier. I intend to look into this but haven't found as much time as I would have liked this last week.

**Comment by Rokonuxa** [comment]
I may need help understanding this, is there or is there not a way to have whatever image was generated last selected as the new input image for controlnet? Because that is what I am right now doing manually and I would LOVE a way to do this automatically.

**Comment by ljleb** [comment]
the loopback checkbox is intended to be used in batch mode, when you want to process a video and have the last processed frame as input to control the next.

**Comment by Rokonuxa** [comment]
so, the unchanged current frame as the img2img input, the changed previous frame as the controlnet input?

**Comment by ljleb** [comment]
I am not sure if this feature still works as well as it used to, it's been a while I contributed here. The intention was to be able to give a specific batch directory to each control unit in batch mode, and then let each control unit decide whether to use the last generated image back as its control map for the next iteration. The preprocessor should automatically pass on the generated image to get a proper control map for that unit.

**Comment by ljleb** [comment]
see #1264 for where lllysaviel wanted to take this. I think this is still a good idea, but I haven't been able to spend time working on this as I would have liked to.

**Comment by Rokonuxa** [comment]
damn, I was hoping it was more like SD loopback, except without the limit. That, with it also being, well, controlnet, that would have been awesome.
