### ISSUE TITLE
Prompt-Free Diffusion

### ISSUE THREAD

**Issue by loboere** [Mikubill/sd-webui-controlnet#1438]
I would like to know if you plan to implement Prompt-Free Diffusion, it seems like a significant improvement and better than reference_only
https://github.com/SHI-Labs/Prompt-Free-Diffusion

**Comment by ljleb** [comment]
IIUC, PFD does not necessarily rely on controlnet. It can be its own extension, as it merely replaces the prompt encoder with a transformer architecture.
