### ISSUE TITLE
[Bug]: Failed to install mediapipe, some preprocessors may not work

### ISSUE THREAD

**Issue by aearone** [Mikubill/sd-webui-controlnet#1439]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When I try to install Controlnet, I get a mediapipe installation error in the command terminal. On the advice from this case, I opened webui through the command line as administrator and tried to install controlnet. Unfortunately, I got an error in this case as well. 

### Steps to reproduce the problem

1. Run webui (as well through the administrator rights)
2. Installing the sd-webui-controlnet extension using the URL
3. Gets an error in the terminal

### What should have happened?

I don't know what the reason is, but none of the advice helped me. Is there any other way to install mediapipe? 

### Commit where the problem happens

webui: version: python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: N/A  •  gradio: 3.29.0  •
controlnet: v1.1.191

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--opt-sdp-attention
```

### List of enabled extensions

sd-webui-controlnet extension

### Console logs

```Shell
Installing sd-webui-controlnet requirement: mediapipe
Couldn't install sd-webui-controlnet requirement: mediapipe.
Command: "E:\Downloader\stable_diffusion\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install mediapipe --prefer-binary
Error code: 1
stdout: Collecting mediapipe
  Using cached mediapipe-0.10.0-cp310-cp310-win_amd64.whl (50.2 MB)
Requirement already satisfied: numpy in e:\downloader\stable_diffusion\stable-diffusion-webui\venv\lib\site-packages (from mediapipe) (1.23.5)
Requirement already satisfied: flatbuffers>=2.0 in e:\downloader\stable_diffusion\stable-diffusion-webui\venv\lib\site-packages (from mediapipe) (23.5.26)
Requirement already satisfied: matplotlib in e:\downloader\stable_diffusion\stable-diffusion-webui\venv\lib\site-packages (from mediapipe) (3.7.1)
Requirement already satisfied: attrs>=19.1.0 in e:\downloader\stable_diffusion\stable-diffusion-webui\venv\lib\site-packages (from mediapipe) (23.1.0)
Requirement already satisfied: protobuf<4,>=3.11 in e:\downloader\stable_diffusion\stable-diffusion-webui\venv\lib\site-packages (from mediapipe) (3.20.0)
Collecting opencv-contrib-python
  Using cached opencv_contrib_python-4.7.0.72-cp37-abi3-win_amd64.whl (44.9 MB)
Requirement already satisfied: absl-py in e:\downloader\stable_diffusion\stable-diffusion-webui\venv\lib\site-packages (from mediapipe) (1.4.0)
Collecting sounddevice>=0.4.4
  Using cached sounddevice-0.4.6-py3-none-win_amd64.whl (199 kB)
Collecting CFFI>=1.0
  Using cached cffi-1.15.1-cp310-cp310-win_amd64.whl (179 kB)
Requirement already satisfied: contourpy>=1.0.1 in e:\downloader\stable_diffusion\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mediapipe) (1.0.7)
Requirement already satisfied: fonttools>=4.22.0 in e:\downloader\stable_diffusion\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mediapipe) (4.39.4)
Requirement already satisfied: packaging>=20.0 in e:\downloader\stable_diffusion\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mediapipe) (23.1)
Requirement already satisfied: pillow>=6.2.0 in e:\downloader\stable_diffusion\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mediapipe) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in e:\downloader\stable_diffusion\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mediapipe) (3.0.9)
Requirement already satisfied: cycler>=0.10 in e:\downloader\stable_diffusion\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mediapipe) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in e:\downloader\stable_diffusion\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mediapipe) (1.4.4)
Requirement already satisfied: python-dateutil>=2.7 in e:\downloader\stable_diffusion\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mediapipe) (2.8.2)
Requirement already satisfied: pycparser in e:\downloader\stable_diffusion\stable-diffusion-webui\venv\lib\site-packages (from CFFI>=1.0->sounddevice>=0.4.4->mediapipe) (2.21)
Requirement already satisfied: six>=1.5 in e:\downloader\stable_diffusion\stable-diffusion-webui\venv\lib\site-packages (from python-dateutil>=2.7->matplotlib->mediapipe) (1.16.0)
Installing collected packages: opencv-contrib-python, CFFI, sounddevice, mediapipe

stderr: ERROR: Could not install packages due to an OSError: [WinError 5]   : 'E:\\Downloader\\stable_diffusion\\stable-diffusion-webui\\venv\\Lib\\site-packages\\cv2\\cv2.pyd'
Check the permissions.


[notice] A new release of pip available: 22.2.1 -> 23.1.2
[notice] To update, run: E:\Downloader\stable_diffusion\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip


Warning: Failed to install mediapipe, some preprocessors may not work.
```

### Additional information

![Screenshot_15](https://github.com/Mikubill/sd-webui-controlnet/assets/93353660/983d74fc-e497-4a83-bb64-6e218f83e1bb)

**Comment by aearone** [comment]
I was able to install mediapipe manually by following these steps:

>Open a command prompt as administrator

Insert this command from your error log: 

`**your disk**:\**your stable diffusion folder**\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install mediapipe --prefer-binary`

Press the Enter key. This will install the mediapipe library successfully and you will no longer get an error when installing controlnet.

**Comment by ryo0ka** [comment]
for other sd-related tools i had the same issue (mediapipe failing to install etc) and the issue was something to do with permission. 

solution was `pip install -r requirements.txt --user`; note `--user`, which bypasses the permission issue.

**Comment by lllyasviel** [comment]
This is a warning so you can ignore it. It do not influence most functionalities

**Comment by Charlie-Steer** [comment]
Same issue, and on a fresh install of WebUI.

**Comment by mellow-tnk** [comment]
> This is a warning so you can ignore it. It does not influence most functionalities

do you know if this affects ControlNet's Reference ability? Everything else from controlnet works, but trying to generate an image from Reference gives a "ControlNet failed to use VAE. Please try to add `--no-half-vae`, `--no-half` and remove `--precision full` in launch cmd." But I already have those commands for launch.

**Comment by visualhippocracy** [comment]
> I was able to install mediapipe manually by following these steps:
> 
> **Open a command prompt as administrator:**
> 
> **Insert this command from your error log:**
> 
> `*your disk*:\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install mediapipe --prefer-binary`
> 
> Press the Enter key.
> 
> Q: Is it correct to install mediapipe this way?

ok never mind my earlier issue was fixed by doing this, to get around the permission issue i did this in an administrator level command prompt

**Comment by ZUIcat** [comment]
I have the same problem today.

**Comment by Ketorami** [comment]
![Screenshot 2023-07-25 044348](https://github.com/Mikubill/sd-webui-controlnet/assets/101268214/1a04b5dc-5d86-435f-8218-d921175d58e8)
![Screenshot 2023-07-25 044418](https://github.com/Mikubill/sd-webui-controlnet/assets/101268214/440c51e4-7fb6-4aeb-b444-24aa12592f0a)

**Comment by wertstahl** [comment]
i had this error too, and the problem was, i had the AUTOMATIC1111 cmd window still open. after closing it, @visualhippocracy 's solution worked fine.

**Comment by paradox8008** [comment]
> venv\scripts\activate.bat

had same issue today... windows 11. Dropped the -m off of the cmd and ran:   pip install mediapipe --prefer-binary     everything seemed to install and is running seemingly OK right now. Hope this helps anyone with same issue.
