### ISSUE TITLE
Error using Controlnet

### ISSUE THREAD

**Issue by alexclerick** [Mikubill/sd-webui-controlnet#144]
RuntimeError: Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 9, 64, 64] to have 4 channels, but got 9 channels instead
Appears only using CN with all models

**Comment by ljleb** [comment]
related: #112

**Comment by putaozhang** [comment]
Controlnet is enabled but no input image is given

**Comment by putaozhang** [comment]
RuntimeError: Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 9, 64, 64] to have 4 channels, but got 9 channels instead
