### ISSUE TITLE
[Bug]:  "Model" drop-down list is always empty

### ISSUE THREAD

**Issue by manzhizhen** [Mikubill/sd-webui-controlnet#1452]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When using controlnet, regardless of any "Preprocessor" I select, my "Model" drop-down list is always empty, as shown in the screenshot below:

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/6687462/5565f568-f4fe-44a1-9298-796db9890cb4)

Launching Web UI with arguments:
No module 'xformers'. Proceeding without it.
ControlNet v1.1.200
ControlNet v1.1.200
sd-webui-prompt-all-in-one background API service started successfully.

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

Theoretically, the "Model" drop-down list should interwork with the "Preprocessor" drop-down list on the left

### Commit where the problem happens

webui: 
controlnet: 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/6687462/00d6c685-b593-4bbd-a1b2-b3a1fc61de50)

### Console logs

```Shell
Launching Web UI with arguments:
No module 'xformers'. Proceeding without it.
ControlNet v1.1.200
ControlNet v1.1.200
sd-webui-prompt-all-in-one background API service started successfully.
Loading weights [fba9027fa4] from F:\stable-diffusion-webui\models\Stable-diffusion\realisian_v40.safetensors
Creating model from config: F:\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying cross attention optimization (Doggettx).
Textual inversion embeddings loaded(0):
Model loaded in 3.6s (load weights from disk: 0.2s, create model: 0.4s, apply weights to model: 0.7s, apply half(): 0.8s, move model to device: 0.6s, load textual inversion embeddings: 0.9s).
Create LRU cache (max_size=16) for preprocessor results.
Create LRU cache (max_size=16) for preprocessor results.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Create LRU cache (max_size=16) for preprocessor results.
Startup time: 14.3s (import torch: 2.1s, import gradio: 1.3s, import ldm: 0.6s, other imports: 0.9s, load scripts: 1.9s, load SD checkpoint: 3.7s, create ui: 1.2s, gradio launch: 2.4s).
```

**Comment by huchenlei** [comment]
Is this your first time using ControlNet. Does the feature work before (A certain controlnet version)?

Very likely you did not follow download models step in README:
https://github.com/Mikubill/sd-webui-controlnet#download-models

**Comment by manzhizhen** [comment]
My fault，thanks
