### ISSUE TITLE
[Bug]: multi controlnet does not work in 1.1.201

### ISSUE THREAD

**Issue by Naylenv** [Mikubill/sd-webui-controlnet#1459]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

In the previous version, it was possible to use the webui api to call multiple controlnets without any special settings.
In the current version, first go to the setting to adjust the size of the multi controlnet, in order to use the api to call multiple controlnet

This is not a convenient way to deploy webui, is there a way to solve this problem, as if you do not need to set in the setting can call multiple controlnet. 

### Steps to reproduce the problem

None

### What should have happened?

None

### Commit where the problem happens

webui: 1.3.0
controlnet: 1.1.201

### Command Line Arguments

```Shell
None
```

### List of enabled extensions

None

### Console logs

```Shell
None
```

### Additional information

None

**Comment by subinznz** [comment]
do you have an example of a working payload after you changed the setting ?

**Comment by Nomination-NRB** [comment]
> do you have an example of a working payload after you changed the setting ?

Hello,
when I use multi controlnet, it will return 3 images, the same in the webui, but it seems that the softedge doesn't work.

using api:
![W2 E3ZTD7MT06KSPUD_UCF](https://github.com/Mikubill/sd-webui-controlnet/assets/83486284/ab0f2027-89a2-40e3-baee-5a2dab4c2119)
![XI(}K~TM7B)W7BPS}OWSJA9](https://github.com/Mikubill/sd-webui-controlnet/assets/83486284/09cfaf3e-3df9-466e-a912-11f63a101237)

using webui:
![{KFY6N5LO08E3ZKRHG}97_P](https://github.com/Mikubill/sd-webui-controlnet/assets/83486284/d72986fa-0e75-4b0f-abbb-ef2298a7a576)
![D9H%5FB1DC2VY%M2IMI)NHY](https://github.com/Mikubill/sd-webui-controlnet/assets/83486284/5cafeacd-16f3-4cdc-8c26-ff5846bc7487)

If I use only one controlnet, either openpose or softedge will work, but not both together
