### ISSUE TITLE
[Bug]: Different results API vs UI when using reference_* controlnet

### ISSUE THREAD

**Issue by reimager** [Mikubill/sd-webui-controlnet#1467]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

API vs UI Different results with reference

I get different results from the API vs the UI. This is with fixed seeds, and there is no randomness.
They are consistently the same image, but always different on the UI vs the API. I thought it was an A1111 issue, but I finally tracked it down to controlnet.
Its not all the control methods, depth and softedge (or both) produce the same results on the API vs the UI, but if you do reference_only its always different on the API vs the UI.

I'm using the same settings and comparing the infotexts

These produce the same result:
```
a cat
Steps: 20, Sampler: Euler a, CFG scale: 7.0, Seed: 0, Size: 512x512, Model hash: c0d1994c73, Model: Realistic_Vision_V2.0-fp16-no-ema, Version: v1.3.0

a cat
Steps: 20, Sampler: Euler a, CFG scale: 7.0, Seed: 0, Size: 512x512, Model hash: c0d1994c73, Model: Realistic_Vision_V2.0-fp16-no-ema, Version: v1.3.0
```

These do not produce the same results:
```
a cat
Steps: 20, Sampler: Euler a, CFG scale: 7.0, Seed: 0, Size: 512x512, Model hash: c0d1994c73, Model: Realistic_Vision_V2.0-fp16-no-ema, ControlNet 0: "preprocessor: reference_only, model: None, weight: 1, starting/ending: (0, 1), resize mode: Crop and Resize, pixel perfect: False, control mode: ControlNet is more important, preprocessor params: (512, 0.5, 64)", Version: v1.3.0

a cat
Steps: 20, Sampler: Euler a, CFG scale: 7.0, Seed: 0, Size: 512x512, Model hash: c0d1994c73, Model: Realistic_Vision_V2.0-fp16-no-ema, ControlNet 0: "preprocessor: reference_only, model: None, weight: 1, starting/ending: (0, 1), resize mode: Crop and Resize, pixel perfect: False, control mode: ControlNet is more important, preprocessor params: (512, 0.5, 64)", Version: v1.3.0
```

I have not been able to figure out where the two diverge.

FWIW, the coloring is always distinctly different through the API than the UI. The UI produces better results imo.  Maybe this has to do with how the image is encoded?

### Steps to reproduce the problem

```
    url = "http://127.0.0.1:7860"
    _, bytelist = cv2.imencode('.png', cv2.imread('cat-striped-768x768.jpg')[:, :, ::-1])
    reference_image = base64.b64encode(bytelist).decode('utf-8')

    seed = 0
    payload = {
        "prompt": "a cat",
        "seed": seed,
        "subseed": seed,
        "cfg_scale": 7.0,
        "steps": 20,
        "sampler_index": "Euler a",
        "cfg_scale": 7.0,

        'seed': 0.0,
        'subseed': 0.0,
        'subseed_strength': 0,
        'seed_resize_from_h': 0,
        'seed_resize_from_w': 0, 

        "alwayson_scripts": {
            "controlnet": {
                "args": [
                    {
                        "input_image": reference_image,
                        "module": "reference_only",
                        "weight": 1,
                        "guidance_start": 0,
                        "guidance_end": 1,
                        "resize_mode": "Crop and Resize",
                        "control_mode": "ControlNet is more important",
                        "threshold_a": 0.5,
                    },
                ]
            }
        }
    }

    response = requests.post(url=f'{url}/sdapi/v1/txt2img', json=payload)

    r = response.json()
    info = json.loads(r['info'])
    infotexts = info['infotexts'][0]
    print(infotexts)

    image = Image.open(io.BytesIO(base64.b64decode(r['images'][0].split(",", 1)[0])))
    image.save(f"output-{seed}.png")
```

use the same settings in the UI (mostly defaults) 
but add the controlnet ref image to reference_only and "ControlNet is more important" (for this example)

### What should have happened?

I would expect the same results API vs UI

### Commit where the problem happens

webui: c0d1994c73
controlnet: 2e0dc37d

### Command Line Arguments

```Shell
webui.sh --xformers --api
```

### List of enabled extensions

 sd-webui-controlnet	https://github.com/Mikubill/sd-webui-controlnet/	main	2e0dc37d	Sun May 28 11:53:51 2023	unknown
￼LDSR	built-in	None		Tue May 30 04:13:39 2023	
￼Lora	built-in	None		Tue May 30 04:13:39 2023	
￼ScuNET	built-in	None		Tue May 30 04:13:39 2023	
￼SwinIR	built-in	None		Tue May 30 04:13:39 2023	
￼prompt-bracket-checker	built-in	None		Tue May 30 04:13:39 2023

**Comment by reimager** [comment]
![output-0](https://github.com/Mikubill/sd-webui-controlnet/assets/20918094/38f72926-0276-4ea5-a484-5012c912a918)
![output-1](https://github.com/Mikubill/sd-webui-controlnet/assets/20918094/a34ee138-34cf-4167-82ed-28855b2fb8fb)

**Comment by reimager** [comment]
After a good amount of testing, I believe this is almost entirely related to the base64 encoding.
If you use the base64 encoding that the backend uses it produces almost identical results. So I'm guessing that it was just more noticeable with reference than other controlnets.

So this is either invalid or just a doc issue. Closing

**Comment by reimager** [comment]
For others having similar issues: 

The doc shows
```
# Read Image in RGB order
img = cv2.imread('your_image.jpg')[:, :, ::-1]

# Encode into PNG and send to ControlNet
retval, bytes = cv2.imencode('.png', img)
encoded_image = base64.b64encode(bytes).decode('utf-8')
```

I would suggest:
```
with io.BytesIO() as output_bytes:
    Image.open('your_image.jpg').convert('RGB').save(output_bytes, format="PNG")
    encoded_image = base64.b64encode(output_bytes.getvalue()).decode('utf-8')
```

**Comment by Joeyd348039** [comment]
> Image.open('your_image.jpg')

Where is this located? I can't seem to find it in any files.

**Comment by reimager** [comment]
> > Image.open('your_image.jpg')
> 
> Where is this located? I can't seem to find it in any files.
That the pillow image library

from PIL import Image
