### ISSUE TITLE
[Bug]:  Error when calling Controlnet Inpaint with API: could not broadcast input array from shape (1024,768,4) into shape (1024,768,3).

### ISSUE THREAD

**Issue by ExplodedJelly** [Mikubill/sd-webui-controlnet#1468]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

After updating to Controlnet v1.1.202, I'm encountering an error when using the API to call Controlnet inpaint, an issue I did not experience with version v1.1.187. I'm inputting the mask through ControlnetUnit to Controlnet inpaint, could this be related to the format of the mask image (whether it's RGBA or not)?

### Steps to reproduce the problem

Here is the method I use with Controlnet inpaint:
self.inpaint_controlnet_unit = webuiapi.ControlNetUnit(input_image=self.image,
                                           mask=self.mask,
                                           guidance=2,
                                           module='inpaint',
                                           model='control_v11p_sd15_inpaint',
                                           pixel_perfect=False)
controlnet_unit_list = [self.inpaint_controlnet_unit]
result = api.img2img(images=image_list,
                                 width=self.target_resolution[0],
                                 height=self.target_resolution[1],
                                 prompt=self._get_image_prompt(),
                                 inpainting_fill=0,
                                 inpaint_full_res=False,
                                 inpaint_full_res_padding=32,
                                 denoising_strength=0.9,
                                 steps=25,
                                 sampler_name='Euler a',
                                 restore_faces=False,
                                 negative_prompt=self.config.get("BasicPrompt").get("negative_prompt"),
                                 controlnet_units=controlnet_unit_list,
                                 alwayson_scripts={
                                     "ADetailer": {
                                         "args": [
                                             True,
                                             {
                                                 "ad_model": "face_yolov8n.pt",
                                                 "ad_prompt": "",
                                                 "ad_negative_prompt": "",
                                                 "ad_confidence": 0.3,
                                                 "ad_mask_min_ratio": 0.0,
                                                 "ad_mask_max_ratio": 1.0,
                                                 "ad_dilate_erode": 32,
                                                 "ad_x_offset": 0,
                                                 "ad_y_offset": 0,
                                                 "ad_mask_merge_invert": "None",
                                                 "ad_mask_blur": 4,
                                                 "ad_denoising_strength": 0.4,
                                                 "ad_inpaint_only_masked": True,
                                                 "ad_inpaint_only_masked_padding": 0,
                                                 "ad_use_inpaint_width_height": False,
                                                 "ad_inpaint_width": 512,
                                                 "ad_inpaint_height": 512,
                                                 "ad_use_steps": True,
                                                 "ad_steps": 28,
                                                 "ad_use_cfg_scale": False,
                                                 "ad_cfg_scale": 7.0,
                                                 "ad_restore_face": False,
                                                 "ad_controlnet_model": "control_v11p_sd15_inpaint",
                                                 "ad_controlnet_weight": 1.0
                                             }
                                         ]
                                     }
                                 }
                                 )

### What should have happened?

I expect Controlnet inpaint to run correctly.

### Commit where the problem happens

webui: [5ab7f213]
controlnet:  v1.1.202

### Command Line Arguments

```Shell
No
```

### List of enabled extensions

Stable-Diffusion-Webui-Civitai-Helper
a1111-sd-webui-locon
a1111-sd-webui-lycoris
a1111-sd-webui-tagcomplete
adetailer
Deforum
multidiffusion-upscaler-for-automatic1111
sd-webui-3d-open-pose-editor
sd-webui-additional-networks
sd-webui-controlnet
sd-webui-lora-block-weight
sd-webui-model-converter
sd-webui-prompt-all-in-one
sd-webui-segment-anything
stable-diffusion-webui-Layer-Divider
stable-diffusion-webui-images-browser
简体中文语言包
stable-diffusion-webui-localization-zh_Hans
stable-diffusion-webui-wd14-tagger
ultimate-upscale-for-automatic1111
LDSR
Lora
ScuNET
SwinIR
prompt-bracket-checker

### Console logs

```Shell
Error running process: E:\sd-webui-aki-v4\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "E:\sd-webui-aki-v4\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "E:\sd-webui-aki-v4\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1258, in process
    control, detected_map = self.detectmap_proc(detected_map, unit.module, resize_mode, h, w)
  File "E:\sd-webui-aki-v4\extensions\sd-webui-controlnet\scripts\controlnet.py", line 967, in detectmap_proc
    high_quality_background[pad_h:pad_h + new_h, pad_w:pad_w + new_w] = detected_map
ValueError: could not broadcast input array from shape (1024,768,4) into shape (1024,768,3)
```

**Comment by lllyasviel** [comment]
have you restarted terminal after update?

**Comment by ExplodedJelly** [comment]
> 

yes, I have restarted

**Comment by lllyasviel** [comment]
can you share more details about input_image=self.image, mask=self.mask?
