### ISSUE TITLE
[Bug]: Getting this Error from a week or so:  unit.enabled = selector(p, "control_net_enabled", unit.enabled, idx, strict=True) AttributeError: 'int' object has no attribute 'enabled'

### ISSUE THREAD

**Issue by Pavankunchala** [Mikubill/sd-webui-controlnet#1478]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I have updated the Controlnet model recently and even reinstalled it but I am getting the same error time and again, let me know what should I do to get rid of this error

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...
Install  the latest version of WebUI and Controlnet and launch it with python launch.py --xformers 

### What should have happened?

I am initializing the Canny and Depth model but it doesn't seem to be working 

### Commit where the problem happens

webui:  20ae71faa8ef035c31aa3a410b707d792c8203a3
controlnet: 7b707dc1f03c3070f8a506ff70a2b68173d57bb5

### What browsers do you use to access the UI ?

Brave

### Command Line Arguments

```Shell
Python launch.py --xformers
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/39479635/bca1f518-efc4-498a-933c-257736a0a9ce)

### Console logs

```Shell
Error running process: C:\Users\pavan\Desktop\Projects\Deep-Learning\webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "C:\Users\pavan\Desktop\Projects\Deep-Learning\webui\modules\scripts.py", line 451, in process
    if (inputs):
  File "C:\Users\pavan\Desktop\Projects\Deep-Learning\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1036, in process
    self.enabled_units = self.get_enabled_units(p)
  File "C:\Users\pavan\Desktop\Projects\Deep-Learning\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 995, in get_enabled_units
    unit = self.parse_remote_call(p, unit, idx)
  File "C:\Users\pavan\Desktop\Projects\Deep-Learning\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 845, in parse_remote_call
    unit.enabled = selector(p, "control_net_enabled", unit.enabled, idx, strict=True)
AttributeError: 'int' object has no attribute 'enabled
```

**Comment by cheezecrisp** [comment]
same issue occurrs after updateing all extension. issue solved by disabling segment anything extension.
but there are still something wrong. the `Control Mode` and `Resize Mode` were unchecked by default, I
 have to check them manually. After generating pictures they become unchecked again.
