### ISSUE TITLE
[Bug]: Controlnet 2.1 models calling for Yaml files which are there.

### ISSUE THREAD

**Issue by Piscabo** [Mikubill/sd-webui-controlnet#1483]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Fail to implement SD21 canvas drawing or any other canny, depth, or any other SD21 way of controlling image. The result is not controlled.

### Steps to reproduce the problem

1. Go to Controlnet, Choose Lineart or any other SD21 models
2. Press generate an image with an SD21 checkpoint  file
3. Log console error, but it generated an incorrect image

### What should have happened?

The image must represent canvas, which it does not.
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/123719842/96c56e19-5b6c-4052-ba0c-de0999650e5c)
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/123719842/85584c51-b138-4413-8ac4-272cda842e10)

### Commit where the problem happens

webui: v1.3.0
controlnet: v1.1.204
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/123719842/baa05d3e-c590-4735-9c6c-0f7b6e83f61b)

### What browsers do you use to access the UI ?

Google Chrome, Microsoft Edge

### Command Line Arguments

```Shell
COMMANDLINE_ARGS=--theme=dark --allow-code --skip-torch-cuda-test --skip-version-check --api --xformers --opt-split-attention --upcast-sampling
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/123719842/c1222f55-d3ce-43c9-8970-cf2bdb03e5d9)

### Console logs

```Shell
Error running process: A:\AI_Files\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "A:\AI_Files\stable-diffusion-webui\modules\scripts.py", line 451, in process
    script.process(p, *script_args)
  File "A:\AI_Files\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1075, in process
    model_net = self.load_control_model(p, unet, unit.model, unit.low_vram)
  File "A:\AI_Files\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 735, in load_control_model
    model_net = self.build_control_model(p, unet, model, lowvram)
  File "A:\AI_Files\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 800, in build_control_model
    assert os.path.exists(override_config), f'Error: The model config {override_config} is missing. ControlNet 1.1 must have configs.'
AssertionError: Error: The model config A:\AI_Files\stable-diffusion-webui\extensions\sd-webui-controlnet\models\control_v11p_sd21_lineart.yaml is missing. ControlNet 1.1 must have configs.
```

### Additional information

Correct settings :
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/123719842/a16d19b1-a8ae-4b84-9299-242b69583bc5)

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/123719842/9ad22a70-a778-4ff2-b06b-81dde368321d)

**Comment by huchenlei** [comment]
There might be some issue with the `control_v11p_sd21_lineart.safetensors` file as it is only 3 kB. You can see all other models are 700MB+.

**Comment by lllyasviel** [comment]
From your screenshot, it seems that "control_v11p_sd21_lineart.yaml" is not there

**Comment by Piscabo** [comment]
Replaced models and Lora, NO luck still?
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/123719842/94d002be-934a-489a-9405-5e36b51c0a1e)
Loaded state_dict from [A:\AI_Files\stable-diffusion-webui\extensions\sd-webui-controlnet\models\control_v11p_sd21_lineart.safetensors]
Loading config: A:\AI_Files\stable-diffusion-webui\extensions\sd-webui-controlnet\models\control_v11p_sd21_lineart.yaml
Error running process: A:\AI_Files\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "A:\AI_Files\stable-diffusion-webui\modules\scripts.py", line 451, in process
    script.process(p, *script_args)
  File "A:\AI_Files\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 560, in process
    model_net = self.load_control_model(p, unet, unit.model, unit.low_vram)
  File "A:\AI_Files\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 220, in load_control_model
    model_net = self.build_control_model(p, unet, model, lowvram)
  File "A:\AI_Files\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 300, in build_control_model
    network = network_module(
  File "A:\AI_Files\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\cldm.py", line 91, in __init__
    self.control_model.load_state_dict(state_dict)
  File "A:\AI_Files\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ControlNet:

**Comment by mcdorians** [comment]
Try to use absolute paths in the Control Net settings section.
