### ISSUE TITLE
[Bug]: OpenPose Model is really slow in the lastest update!

### ISSUE THREAD

**Issue by fadedninna** [Mikubill/sd-webui-controlnet#1487]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I updated the extension and the openpose model now takes around 2-3 minutes, it was taking around 30-50 seconds before the update.

### Steps to reproduce the problem

1. Go to ...
2. Press ....
3. ...

### What should have happened?

It should be faster

### Commit where the problem happens

webui: v1.3.0
controlnet: v1.1.205

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--medvram --theme=dark --precision full --opt-sdp-attention --no-half --no-half-vae
```

### List of enabled extensions

I only use ControlNet extension.

### Console logs

```Shell
Loading model: control_sd15_openpose [fef5e48e]
Loaded state_dict from [C:\Users\fadedninna\Desktop\Stable-Diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\models\control_sd15_openpose.pth]
Loading config: C:\Users\fadedninna\Desktop\Stable-Diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\models\control_sd15_openpose.yaml
ControlNet model control_sd15_openpose [fef5e48e] loaded.
Loading preprocessor: none
Pixel Perfect Mode Enabled.
resize_mode = ResizeMode.RESIZE
raw_H = 767
raw_W = 512
target_H = 512
target_W = 512
estimation = 512.0
preprocessor resolution = 512
 55%|███████████████████████████████████████████▍                                   | 11/20 [01:25<01:09,  7.73s/it]
Total progress:  55%|██████████████████████████████████▋                            | 11/20 [01:20<01:05,  7.30s/it]
Total progress:  55%|██████████████████████████████████▋                            | 11/20 [01:20<01:06,  7.36s/it]
```

### Additional information

I'm using 1660TI Mobile and this is my normal speed
Total progress: 100%██████████████████████████████████████████████████████████████████| 20/20 [01:00<00:00,  1.67it/s]

**Comment by fadedninna** [comment]
Update! 
Almost all models are too slow for me!

**Comment by ljleb** [comment]
For me, the generation seems to pause every ~3 frames when using 3+ controlnet units on a 3080. Is this the same for you @fadedninna? I will try to bisect the commit down.

**Comment by fadedninna** [comment]
@ljleb I had no problems before the update. Generating 512x512 and 512x768 images with controlnet was taking around 30 seconds to 1 min. After the update, If i use controlnet even a simple 512x512 image takes around 5 minutes and turning controlnet off does not change the generation speed, it still takes around 5 minutes to generate!

**Comment by fadedninna** [comment]
PLEASE FIX MEDVRAM AGAIN!!!

**Comment by lllyasviel** [comment]
Hi please follow the following steps:

1. Provide detail of your OS and GPU.
2. Nvidia released new 531.XXX driver at 2023 May 30, which is repoted to consume more memory than old drivers. Windows 10 may has automatically updated it without let you know.
3. A1111 changed the setting from xformers to sdp, which may have different computation with old versions. This is also an automatic update without let users know.
4. If you still cannot find the cause, you can try to use `git checkout` to see which commit still works. If that is the case, we can make sure it is CN problem and solve it once you inform us.

**Comment by lllyasviel** [comment]
wait. It seems that medvram is broken. I can reproduce the problem. perhaps a CN problem

**Comment by fadedninna** [comment]
1.Windows 10 version 22H2 (19045.2846), 
2.Nvidia 1660 TI 6GB Mobile, Driver Version 535.98 (05/30/2023)
3. I was already using spd (--opt-sdp-attention)

I will upload a Video to show what is wrong with my ControlNet.

**Comment by fadedninna** [comment]
@lllyasviel https://www.youtube.com/watch?v=uiUgMmkXdEE

**Comment by lllyasviel** [comment]
I fixed a bug in 1.1.210 related to medvram but this does not seems to relate to openpose. You can try it but I think the chance of driver breaking it is larger

**Comment by lllyasviel** [comment]
Update: I tried openpose medvram on two devices without problems. Consider more about my points 2 and 3

**Comment by fadedninna** [comment]
@lllyasviel I do not know which one fixed but I updated ControlNet and rollback to the 528.24 (Nvidia Driver) now it is working perfectly!

**Comment by yi** [comment]
> https://www.youtube.com/watch?v=uiUgMmkXdEE
@fadedninna sorry for off-topic. Could you please kindly tell me what the prompt hint plugin is. It looks really useful. thank you!

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/9838/39c3cbd4-7b10-459f-8b98-96f12abd4d70)

**Comment by fadedninna** [comment]
@yi https://github.com/DominikDoom/a1111-sd-webui-tagcomplete

**Comment by ktee95** [comment]
> @lllyasviel I do not know which one fixed but I updated ControlNet and rollback to the 528.24 (Nvidia Driver) now it is working perfectly!



did you switch from Studio Driver to Game-Ready driver?  528.24 released on Jan, do you think it's a bit old?

**Comment by fadedninna** [comment]
> > @lllyasviel I do not know which one fixed but I updated ControlNet and rollback to the 528.24 (Nvidia Driver) now it is working perfectly!
> 
> did you switch from Studio Driver to Game-Ready driver? 528.24 released on Jan, do you think it's a bit old?

I was using an older driver before i updated it to the latest driver, i usually dont do updates because they broke thing so often
