### ISSUE TITLE
[Bug]: Control mode is set to nothing by default, resets back to nothing after every generation

### ISSUE THREAD

**Issue by crazygonuts** [Mikubill/sd-webui-controlnet#1499]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

None of the three radial selections for "control mode" are set by default, and after selecting one and hitting "generate" on the txt2img tab, it will unset whichever radial was selected.

theres also no selection for "resize mode"

### Steps to reproduce the problem

1. Go to controlnet
2. observe that there is no selection for controlmode
<img width="903" alt="Capture" src="https://github.com/Mikubill/sd-webui-controlnet/assets/131223696/c52c7df0-e0c7-4a3c-bc68-344cf017be75">

3. select an option
4. hit generate
5. observe that the selection has become unset

### What should have happened?

there should be a default and it should remember my selections

### Commit where the problem happens

webui: vladmandic and automatic1111
controlnet: all

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
n/a
```

### List of enabled extensions

vladmandic - default set

### Console logs

```Shell
there wasn't anything about controlnet in the logs
```

**Comment by huchenlei** [comment]
Please specify controlnet version you are using. Does the feature stop working after a certain version? I cannot reproduce the problem following the steps provided.

**Comment by crazygonuts** [comment]
controlnet v1.1.208

**Comment by crazygonuts** [comment]
as far as I can tell the buttons are working and it is remember the setting - I can see that the generation is doing the right thing - but the radial buttons just aren't set.

**Comment by crazygonuts** [comment]
OK I double checked my extensions and I think this is caused by https://github.com/volotat/SD-CN-Animation

**Comment by aaronkingdom** [comment]
same error,   ControlNet v1.1.219

**Comment by aaronkingdom** [comment]
> OK I double checked my extensions and I think this is caused by https://github.com/volotat/SD-CN-Animation

same
