### ISSUE TITLE
[Bug]: contronlnet API fails to call MLSD

### ISSUE THREAD

**Issue by utenkkekou** [Mikubill/sd-webui-controlnet#1501]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I am using the latest stable diffusion and controlnet, and I also refer to the minimal working example on the API wiki, but only a few models can be called normally, and now only canny and normalbae can be used normally through the api.

（I have used the latest three versions in both win1O and win11, all of which are in similar situations, canny can be used normally, but mlsd and most of the others cannot, other models may be named problems, but mlsd is not）

### Steps to reproduce the problem

1. Go to  Start sd via webui-user.bat
2. Press Check the model with a minimal working example
3. canny and normalba can pass the test, mlsd can't

### What should have happened?

The normal situation should be to produce the correct picture like canny,but not

### Commit where the problem happens

webui:
version: [v1.3.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/20ae71faa8ef035c31aa3a410b707d792c8203a3)  •  python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: N/A  •  gradio: 3.31.0  •  checkpoint: [2bd89c4fad](https://google.com/search?q=2bd89c4fad32b590f03bb6d39ecd9b354232c12e82ac2ca6bb130f868fb61ef3)
controlnet:
v1.1.202 (main)

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
webui-user .bat
--listen --api
```

### List of enabled extensions

Only sd-webui-controlnet

### Console logs

```Shell
Loading model: control_v11p_sd15_mlsd [aca30ff0]
Loaded state_dict from [D:\stable-diffusion-webui\models\ControlNet\control_v11p_sd15_mlsd.pth]
Loading config: D:\stable-diffusion-webui\extensions\sd-webui-controlnet\models\control_v11p_sd15_mlsd.yaml
ControlNet model control_v11p_sd15_mlsd [aca30ff0] loaded.
Loading preprocessor: mlsd
preprocessor resolution = 512
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:01<00:00, 23.46it/s]
```

**Comment by dragoncdj** [comment]
I encountered the same problem as you, please solve it, mlsd does not work, even preprocessing is not good

**Comment by ljleb** [comment]
The default value for thresholds is 64, must likely you need to pass threshold a and b to the api.

**Comment by ljleb** [comment]
We need to change these default values.

**Comment by lllyasviel** [comment]
added smart default value in 1.1.218 https://github.com/Mikubill/sd-webui-controlnet/pull/1565
