### ISSUE TITLE
[Bug]: ControlNet Canvas Too Small To Be Useful in Inpaint Mode

### ISSUE THREAD

**Issue by dmx974** [Mikubill/sd-webui-controlnet#1504]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

ControlNet Canvas Too Small To Be Useful in Inpaint Mode. 

### Steps to reproduce the problem

If you have a large image, the preview of the image you dragged prevent you to inpaint in detail. What would be awesome is that we could zoom the canva.

### What should have happened?

What should be done is:
1) make the canvas bigger when you are in inpaint mode (like the canva in img2img tab)
2) allow users to be able to zoom in / out part of the image, so they can perfectly see how to draw the mask

### Commit where the problem happens

webui: 
controlnet: 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
n/a
```

### List of enabled extensions

n/a

### Console logs

```Shell
n/a
```

**Comment by huchenlei** [comment]
Ref
#1488 discussed similar issue.

**Comment by altoiddealer** [comment]
You can use the canvas-zoom extension for this, actually.

When you have that installed, go to img2img tab > Inpaint.  In the image window, right click and youll see a menu.... top of the menu is "Enable canvas zoom in controlnet windows".  Once you enable that and refresh the page, you can use the canvas-zoom functionality in all the controlnet windows.

**Comment by huchenlei** [comment]
> You can use the canvas-zoom extension for this, actually.
> 
> When you have that installed, go to img2img tab > Inpaint. In the image window, right click and youll see a menu.... top of the menu is "Enable canvas zoom in controlnet windows". Once you enable that and refresh the page, you can use the canvas-zoom functionality in all the controlnet windows.
> 
> More info on this here: [richrobber2/canvas-zoom#42](https://github.com/richrobber2/canvas-zoom/discussions/42)

Just tried. Thanks for sharing that awesome extension!

One issue with it seems to be if you do not select `enable preview` in controlnet, the image element will be a long flat stripe, which after the zoom still very small. You will have to check `enable preview` to make zoom to fit screen work properly.

**Comment by lllyasviel** [comment]
You can use A1111 inpaint at the same time with CN inpaint. You can just leave CN input blank. But that method does not have high-res fix. However, high res fix is not really necessary for detailed inpaint since detailed inpaint is ususally "Inpaint area only masked"

**Comment by huchenlei** [comment]
Guess we can close this issue because the zoom feature is merged into A1111.

**Comment by daswer123** [comment]
Hi all, I made a PR with which you can add a zoom feature to any canvas
https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/11005

**Comment by w-e-w** [comment]
it's going to at least take 3~4 weeks until 1.4.0

**Comment by a3nima** [comment]
what means "neds the function call" ?
