### ISSUE TITLE
List ALL required files that are not included somewhere obvious, like the "install" section of the readme.

### ISSUE THREAD

**Issue by AmusedDiffuser** [Mikubill/sd-webui-controlnet#152]
This is a serious issue for anyone with slow or intermittent internet access. Very frustrating to get everything else working and then have to wait an hour for a 50mb download (network-bsds500.pth) that could have been had in seconds when faster internet was available. Not to mention Midas and OpenPose...

The "Install" section of the readme that mentions the cv2 library and gradio versions seems like an appropriate place to append mentions of:

--"https://huggingface.co/lllyasviel/ControlNet/resolve/main/annotator/ckpts/network-bsds500.pth" to D:\zzSD2\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\hed\network-bsds500.pth

--"https://huggingface.co/lllyasviel/ControlNet/resolve/main/annotator/ckpts/body_pose_model.pth" to D:\zzSD2\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\openpose\body_pose_model.pth

--Midas (didn't have the opportunity to copy/paste

...and any other critical files that will slow or stop people from using this incredible tool. 

A million times thank you for bringing this into our ecosystem!.. Total paradigm shift!

**Comment by Mikubill** [comment]
Just search `load_file_from_url` and you will get all of them. Note that path may change in the future

**Comment by joemamafue** [comment]
> load_file_from_url

I appreciate the quick response but have no idea what you mean. Search google? Search the issues here on GitHub? Either way, thanks again, but this hardly solves the problem for others nor prevents them from running into it, and as some here have pointed out, MANY others are coming... One gram of prevention outweighs five tons of intervention.

**Comment by Mikubill** [comment]
https://github.com/search?q=repo%3AMikubill%2Fsd-webui-controlnet%20load_file_from_url&type=code

**Comment by zhmou** [comment]
Yes, as I commented here(https://github.com/Mikubill/sd-webui-controlnet/issues/110#issuecomment-1434496365), it took me a whole afternoon to figure out that it was my network that was causing that problem (at least for me).

You can find the download addresses of those models [here](https://huggingface.co/lllyasviel/ControlNet/tree/main/annotator/ckpts) and put them under the corresponding folders (X:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\[preprocessor])

Hope this will solve your problem.

**Comment by ZeroCool22** [comment]
Where is the MIDAS one?

![Screenshot_5](https://user-images.githubusercontent.com/13344308/219843009-32cb7e09-a138-4312-be11-d73393ab6c30.png)

I already downloaded everything but i don't see the MIDAS one.

**Comment by QinCaii** [comment]
I'm completely confused now

**Comment by Mikubill** [comment]
"depth" is "midas". All preprocessors/annotators are using same name as the corresponding model.
