### ISSUE TITLE
[Bug]: ControlNet remembering last inpaint operation under certain circumstances

### ISSUE THREAD

**Issue by catboxanon** [Mikubill/sd-webui-controlnet#1531]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

ControlNet seems to remember the last txt2img inpaint after it's been disabled under certain circumstances. Below is the quickest reproducible example I came up with.

### Steps to reproduce the problem

1. Generate an image with ControlNet inpaint in txt2img tab (mask the image as well)
2. Generate an image in the img2img tab (no ControlNet)
3. Generate an image in txt2img (no ControlNet)

This seems to only occur if the resolution in txt2img is left unchanged. What occurrs in step 3 is something like this below. The tori gate image is what I used in step 1, which I masked out the bottom half of, and when prompting an image in step 3, it only appears in that previously masked area.

<details>
<summary>Image</summary>

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/122327233/5ce3b9d3-1ae4-46c8-8e87-915c91c9b608)
</details>

I did have a case where this same issue occurred, but only when enabling hires fix in the txt2img tab (also no ControlNet), but that was the first time I ran into this and I'm not sure how to reproduce that scenario, but I would guess it's caused by the same thing.

### What should have happened?

ControlNet should not be remembering the previous inpaint.

### Commit where the problem happens

webui: https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/3e995778fc525ff15d56c1472c1a1bc701019ec5
controlnet: https://github.com/Mikubill/sd-webui-controlnet/commit/591b3de809a9f46c1409adcae31345c887aa7f0f

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
n/a
```

### List of enabled extensions

(only ControlNet)

### Console logs

```Shell
n/a
```

**Comment by MrGingerSir222** [comment]
I have also had this exact issue.

**Comment by huchenlei** [comment]
Confirmed reproduceable.

**Comment by huchenlei** [comment]
Version v1.1.202 does not have the bug.

Doing a bisect now to find culprit.

**Comment by lllyasviel** [comment]
fixed in 1.1.214.
Feel free to test and close. or report if not fixed
