### ISSUE TITLE
[Bug]: Using ControlNet tile upscale method changes the face of my subject.

### ISSUE THREAD

**Issue by faultline047** [Mikubill/sd-webui-controlnet#1533]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When using ControlNet tile feature, along with Ultimate SD Upscaler to upscale an image with a person, it changes the face drastically that it becomes another person, or worse, a deformed one on higher denoising strength.

### Steps to reproduce the problem

1. Put image into img2img tab, setup the settings _(I leave pretty much everything on default and just play with denoising strength)_
2. Put the same image into ControlNet
3. Enable ControlNet, Low VRAM
   - Set Preprocessor: tile_resample
   - Set Model: control_v11f1e_sd15_tile[a371b31b]
   - Set, "ControlNet is more important" _(although I tried all three, doesn't make a difference)_

4. Set up the script, Ultimate SD Upscale with these settings:
   - Target Size(Custom): 540x960
   - Upscaler: 4x-UltraSharp, I also tried with R-ESRGAN, still changes the face drastically
   - Type: Linear
   - Tile Size: 384x384

6. Generate

### What should have happened?

It should add details and noise without changing the image entirely, specially the face, even with a high denoising strength.

### Commit where the problem happens

webui: 5e48f300
controlnet: 591b3de

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
--opt-sub-quad-attention --lowvram --precision full --disable-nan-check --no-half --no-half-vae --opt-split-attention-v1 --autolaunch
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/134237564/afbeecb8-2017-4660-8919-455f46413456)

### Console logs

```Shell
venv "E:\AI\Stable Diffusion\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: <none>
Commit hash: 5e48f300c1b74f0312f692dc8d0485b5120fc497
Installing requirements


Launching Web UI with arguments: --opt-sub-quad-attention --lowvram --precision full --disable-nan-check --no-half --no-half-vae --opt-split-attention-v1 --autolaunch
No module 'xformers'. Proceeding without it.
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
ControlNet v1.1.213
ControlNet v1.1.213
Loading weights [fc2511737a] from E:\AI\Stable Diffusion\stable-diffusion-webui-directml\models\Stable-diffusion\chilloutmix_NiPrunedFp32Fix.safetensors
Create LRU cache (max_size=16) for preprocessor results.
Create LRU cache (max_size=16) for preprocessor results.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Creating model from config: E:\AI\Stable Diffusion\stable-diffusion-webui-directml\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
Create LRU cache (max_size=16) for preprocessor results.
Startup time: 20.4s (import torch: 5.2s, import gradio: 1.5s, import ldm: 1.8s, other imports: 4.3s, setup codeformer: 0.2s, load scripts: 3.6s, create ui: 0.8s, gradio launch: 2.9s).
DiffusionWrapper has 859.52 M params.
Applying optimization: sub-quadratic... done.
Textual inversion embeddings loaded(9): bad-picture-chill-75v, bad_prompt_version2-neg, badhandv4, BadNegAnatomyV1-neg, By bad artist -neg, corneo_cowgirl, easynegative, negative_hand-neg, ng_deepnegative_v1_75t
Model loaded in 91.5s (load weights from disk: 3.7s, create model: 0.8s, apply weights to model: 86.5s, load VAE: 0.2s, load textual inversion embeddings: 0.2s).
Canva size: 540x960
Image size: 360x640
Scale factor: 2
Upscaling iteration 1 with scale factor 2
Tile size: 384x384
Tiles amount: 6
Grid: 3x2
Redraw enabled: True
Seams fix mode: NONE
Loading model: control_v11f1e_sd15_tile [a371b31b]
Loaded state_dict from [E:\AI\Stable Diffusion\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\models\control_v11f1e_sd15_tile.pth]
Loading config: E:\AI\Stable Diffusion\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\models\control_v11f1e_sd15_tile.yaml
ControlNet model control_v11f1e_sd15_tile [a371b31b] loaded.
Loading preprocessor: tile_resample
preprocessor resolution = 512
Calling preprocessor tile_resample outside of cache.
100%|██████████████████████████████████████████████████████████████████████████████████| 13/13 [01:33<00:00,  7.20s/it]
Loading model from cache: control_v11f1e_sd15_tile [a371b31b]                          | 13/78 [01:20<06:54,  6.37s/it]
Loading preprocessor: tile_resample
preprocessor resolution = 512
Calling preprocessor tile_resample outside of cache.
100%|██████████████████████████████████████████████████████████████████████████████████| 13/13 [01:25<00:00,  6.59s/it]
Loading model from cache: control_v11f1e_sd15_tile [a371b31b]                          | 26/78 [02:49<05:35,  6.45s/it]
Loading preprocessor: tile_resample
preprocessor resolution = 512
Calling preprocessor tile_resample outside of cache.
100%|██████████████████████████████████████████████████████████████████████████████████| 13/13 [01:26<00:00,  6.63s/it]
Loading model from cache: control_v11f1e_sd15_tile [a371b31b]                          | 39/78 [04:17<04:14,  6.53s/it]
Loading preprocessor: tile_resample
preprocessor resolution = 512
Calling preprocessor tile_resample outside of cache.
100%|██████████████████████████████████████████████████████████████████████████████████| 13/13 [01:23<00:00,  6.44s/it]
Loading model from cache: control_v11f1e_sd15_tile [a371b31b]████                      | 52/78 [05:43<02:46,  6.39s/it]
Loading preprocessor: tile_resample
preprocessor resolution = 512
Calling preprocessor tile_resample outside of cache.
100%|██████████████████████████████████████████████████████████████████████████████████| 13/13 [01:24<00:00,  6.49s/it]
Loading model from cache: control_v11f1e_sd15_tile [a371b31b]███████████████           | 65/78 [07:09<01:28,  6.80s/it]
Loading preprocessor: tile_resample
preprocessor resolution = 512
Calling preprocessor tile_resample outside of cache.
100%|██████████████████████████████████████████████████████████████████████████████████| 13/13 [01:26<00:00,  6.62s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 78/78 [08:39<00:00,  6.66s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 78/78 [08:39<00:00,  6.46s/it]
```

### Additional information

I just updated the ControlNet extension as I'm writing this, however, it still didn't solve my problem. 
Here are some additional info that I have also posted in Reddit r/StableDiffusion which, at the time of writing this, still haven't received any solution _(that works)._

[Reddit post](https://www.reddit.com/r/StableDiffusion/comments/13ywbse/need_help_with_controlnets_tile_upscale_method/):
When I use ControlNet for upscaling, using the Tile Resample and then the script Ultimate SD Upscale, I do get an upscaled image, however, the face of my subject changes drastically, regardless of how low my denoising strength is. I even set it to 0.01 and it still changes it to a point that it's a completely different person.

I tried tweaking some of the things around, like doing with or without the positive and/or negative prompts. Setting the ControlNet into "Balanced", "My Prompt is more important" and "ControlNet is more important."

With Ultimate SD Upscale, I've tried it with different upscaler as well, I'm originally using 4x-UltraSharp and I've also tested it with R-ESRGAN 4x+ and nothing solved my issue. Meanwhile, I see some YouTuber doing the exact same thing and the face of their subject doesn't change.

### **Here are my settings:**
**Resize Mode:** Just Resize
**Sampler:** Euler a _(Also tried with DPM++ SDE karras)_
**Size:** 360x640
**CFG:** 7 _(Also tried 15, due to some recommendation on GitHub)_
**Denoise:** I usually tried to stick with 0.2, but I tried various settings as well, high and low

### **ControlNet:**
Tested with and without an image in the ControlNet box. Same result.
**Low VRAM enabled** (Also tested with the Pixel Perfect box, did nothing either)
**Preprocessor:** tile_resample
**Model:** control_v11f1e_sd15_tile[a371b31b]
**Control Mode:** I tried all three, doesn't make a difference.

### **Ultimate SD Upscale:**
**Target Size(Custom):** 540x960
**Upscaler:** 4x-UltraSharp, I also tried with R-ESRGAN, still changes the face drastically
**Type:** Linear
**Tile Size:** 384x384 (I have shitty GPU and can't run Ultimate SD Upscale any higher than that)

### **Hardware:**
**GPU:** AMD RX570 4gb

**Comment by lllyasviel** [comment]
AMD cards reports unexpected results from time to time and rightnow we still have 20% preprocesssors that do not support AMD.
AMD RX570 4gb is an even more special card and we do not really have good chance to test it. 
However I will add help wanted flag if other cards can reproduce problems

**Comment by faultline047** [comment]
@lllyasviel I first started testing ControlNet a week ago _(well, I'm new to image generation in general)_, and if I remember correctly, it worked properly, upscaling with tiles using ControlNet and the scripts. So maybe going back to previous commits would solve my problem, as a temporary solution? But which one though?

Anyway, thanks for a fast response. I should've chosen an Nvidia card lol

**Comment by faultline047** [comment]
I have done some test yesterday on a 512x512 image, upscaling it to 1080x1080 and it worked normally. I don't exactly know what's happening, but my suspicion is because of the size of the image I was trying to upscale, from 360x640 and only upscaling it to 540x960, which is a portrait of a woman, from head to thighs, and there's still quite a space above her head, making her face a bit small for the entire image. Which causes the face to be inside one tile and maybe that's why there's a lot of changes made in the whole face, unlike test that I did with a 512x512 image, zoomed in to her face. 

But for good measure, I'll do another test using the 360p image upscaling into 540p and see if my problem is still there. Then I would try and upscale it to 1080x1920 to see if my theory is correct. 

Anyway, you can find the test [here](https://imgur.com/a/EqeJdmi), and [this](https://imgur.com/a/tt8Lrs3) is the screenshot of my settings after the test is done.

**Comment by Woisek** [comment]
>2. Put the same image into ControlNet

Is not needed and maybe a problem ... ?

**Comment by mandal-rahul** [comment]
Did you figure out why it’s changing the face?
I’m trying to upscale a 1024x1024 image into x2 and even with a small denoising strength of 0.08 it’s changing the face. Previously it used to work fine.
