### ISSUE TITLE
[Bug/Suggestion]: name collisions from scripts.ui

### ISSUE THREAD

**Issue by ArrowM** [Mikubill/sd-webui-controlnet#1534]
### What happened?
This isn't technically a bug with the extension, but a conflict with other extensions (and the fix takes like 10 seconds). I've seen other extensions using the package `scripts.ui` which causes problems with the way A1111 handles extensions. For example, at the time of writing, having this extension and dataset-tag-editor installed together breaks dataset-tag-editor. 

### Suggestion
Move `controlnet_ui_group.py` to the `scripts` directory and avoid using subdirectories in `scripts`.

### Commit where the problem happens
webui: n/a
controlnet: 7b2bf668ee4e0ce63dd67c828ea20c064e719796

**Comment by huchenlei** [comment]
Already fixed. Please update to most recent version.

**Comment by ArrowM** [comment]
thx <3
