### ISSUE TITLE
can someone please help me to fix this-now there isnt control net anymore in my UI after new update/restarting

### ISSUE THREAD

**Issue by demirklvc** [Mikubill/sd-webui-controlnet#154]
<img width="1440" alt="Bildschirmfoto 2023-02-17 um 16 09 17" src="https://user-images.githubusercontent.com/78754525/219692604-237c9532-ea32-40fd-90b5-dc71034c5ac0.png">

**Comment by Mikubill** [comment]
will fix later

**Comment by demirklvc** [comment]
thanks. im waiting for you. was in a generating session :D appreciate your work <3

**Comment by Mikubill** [comment]
Should work now.

**Comment by demirklvc** [comment]
it works thanks! what is the name of it in the X Y Z script? because i think it isnt there still. ive updated, restarted two times.

**Comment by ljleb** [comment]
seems it should be `[ControlNet] Weight` from [this line](https://github.com/Mikubill/sd-webui-controlnet/pull/145/files#diff-e80a5271c782cd8241a860851ea82f6430055edeb26996b3fe2014fc6c452bfcR22)

**Comment by demirklvc** [comment]
thanks. ive clsoed and reopened stable several times-still it doesnt appear it the list.
