### ISSUE TITLE
log duplicated

### ISSUE THREAD

**Issue by lllyasviel** [Mikubill/sd-webui-controlnet#1551]
The log is always duplicated and use red color
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/19834515/51cc3bef-f54a-4dbe-b287-0bbe0b43068e)

and ideally it should be of some other color like Deform 
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/19834515/a7362698-8ed4-4644-9e34-8105cddbed18)

**Comment by huchenlei** [comment]
I don't think it is duplicated as the timestamps are different.

**Comment by huchenlei** [comment]
It might be caused by root logger also printing out the logs.

**Comment by huchenlei** [comment]
#1555 fixes the duplicated log.

**Comment by huchenlei** [comment]
#1556 fixes the red color issue (PyCharm shows all stderr messages as red)
