### ISSUE TITLE
error

### ISSUE THREAD

**Issue by demirklvc** [Mikubill/sd-webui-controlnet#156]
<img width="1440" alt="Bildschirmfoto 2023-02-17 um 16 42 59" src="https://user-images.githubusercontent.com/78754525/219699516-b0e73597-e876-469a-af89-d8782d9b0079.png">

after updating

**Comment by Mikubill** [comment]
mps issue. fixed

**Comment by demirklvc** [comment]
<img width="1440" alt="Bildschirmfoto 2023-02-17 um 16 53 25" src="https://user-images.githubusercontent.com/78754525/219701934-a1367305-2e3b-48cd-8c9c-22bc3046daf1.png">
<img width="1440" alt="Bildschirmfoto 2023-02-17 um 16 53 41" src="https://user-images.githubusercontent.com/78754525/219701958-46feb82f-2f88-430b-8ccd-b151c43fc23f.png">
