### ISSUE TITLE
[Bug]: The controlNet is not working anymore.

### ISSUE THREAD

**Issue by sololll** [Mikubill/sd-webui-controlnet#1569]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Everything was normal a few days ago.
Now, no matter which Control Type of ControlNet, none of them work.
After pressing the generate button, there is no response. The progress bar shows "waiting...", the console does not have any movement, neither started nor reported any errors, nor generated anything.
About 20 seconds later the generate button restores color, but also does not respond after pressing it. 
The console is still silent.
Sometimes  there was a piece of information in the console:WARNING: Invalid HTTP request received.

### Steps to reproduce the problem

1. Go to t2i ControlNet,upload a picture.
2. Press Generate.
3. The progress bar shows "waiting...", then everything stopped responding.
4. About 20 seconds later the generate button restores color, but also does not respond after pressing it.
5. No images were generated and displayed.
6. The console is still silent.
7. Sometimes console got this:WARNING: Invalid HTTP request received.

### What should have happened?

generates images and displays them.

### Commit where the problem happens

webui: 1.3.2
controlnet: 1.1.218

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--port 6520 --gradio-auth xxx:xxx --opt-sdp-attention --opt-sdp-no-mem-attention --opt-split-attention --xformers --disable-safe-unpickle --enable-insecure-extension-access
```

### List of enabled extensions

ControlNet 1.1.218

### Console logs

```Shell
Launching Web UI with arguments: --port 6520 --gradio-auth xxx:xxx --opt-sdp-attention --opt-sdp-no-mem-attention --opt-split-attention --xformers --disable-safe-unpickle --enable-insecure-extension-access
2023-06-05 15:29:29,505 - ControlNet - INFO - ControlNet v1.1.217
ControlNet preprocessor location: /root/aaa/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
2023-06-05 15:29:29,660 - ControlNet - INFO - ControlNet v1.1.217
Loading weights [ce4d987a0e] from /root/aaa/stable-diffusion-webui/models/Stable-diffusion/duchaitenaiart_V453.safetensors
Running on local URL:  http://127.0.0.1:6520

To create a public link, set `share=True` in `launch()`.
Startup time: 7.9s (import torch: 1.3s, import gradio: 1.0s, import ldm: 1.0s, other imports: 2.4s, load scripts: 1.4s, create ui: 0.4s, gradio launch: 0.2s).
Creating model from config: /root/aaa/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying optimization: xformers... done.
Textual inversion embeddings loaded(18): 4nn4k3ndrick, art by mc-mimana25-500, bad-picture-chill-75v, caraVoxelSd15, coloring-book-style, easynegative, erinOobleksd15-Final, gmazzeo, jenn1f1850, jg_ashleyresch, n1n4d0brev, ng_deepnegative_v1_75t, PoqssiV2, pureerosface_v1, Style-BladeRunner2049-8v, ulzzang-6500-v1.1, Unspeakable-Horrors-Composition-4v, youwillgotothemoon3
Model loaded in 2.5s (load weights from disk: 0.8s, create model: 0.5s, apply weights to model: 0.4s, apply half(): 0.2s, move model to device: 0.6s).
2023-06-05 15:30:39,128 - ControlNet - INFO - Preview Resolution = 512
```

### Additional information

I used A1111 on the remote server through an SSH tunnel, which seems to be the cause of the problem. However, a few days ago, before upgrading A1111 and ControlNet to the latest version, everything was normal and there was no such problem.

Now, as long as any picture is uploaded in the ControlNet interface, no matter whether any other options are selected or not, or which one is selected, even "Enable" is not checked, the above problem will occur. 

So, apart from my network environment as a background factor, there must be something inside ControlNet that triggers such a problem.

**Comment by sololll** [comment]
I found some clues.
As long as no picture is uploaded, even if "Enable" is checked and any Control Type is selected, it can work normally without any problem.
So I think the problem may occur in the path processing part related to picture uploading.

**Comment by rohitsainier** [comment]
any solutions??

**Comment by lllyasviel** [comment]
try change browser?

**Comment by solomonlaneia** [comment]
> 
nothing, I tried it and it does not work.

**Comment by sololll** [comment]
I tried Firefox but still got the same issue. 
Error says:
WARNING:  Invalid HTTP request received.

**Comment by sololll** [comment]
It was the first time I found that error messages could also appear here: 
[https://imgse.com/i/pCF4Urn](url)

**Comment by darcula1993** [comment]
I found this problem like 1 months ago. It came with gradio version upgrade I guess. This bug only occur when I use remote server to run "generate" with controlnet.

**Comment by sololll** [comment]
> I found this problem like 1 months ago. It came with gradio version upgrade I guess. This bug only occur when I use remote server to run "generate" with controlnet.

I think so too. It should be related to the new version of gradio and the path handling of ControlNet. 
I found that this problem only occurs when using a remote server through SSH Tunnel. 
If opened directly through the IP address or URL, there is no problem.

**Comment by sololll** [comment]
> > > I found this problem like 1 months ago. It came with gradio version upgrade I guess. This bug only occur when I use remote server to run "generate" with controlnet.
> > 
> > 
> > I think so too. It should be related to the new version of gradio and the path handling of ControlNet. I found that this problem only occurs when using a remote server through SSH Tunnel. If opened directly through the IP address or URL, there is no problem.
> 
> Exactly! But how to open directly through the IP address? I use --listen but seems doesn't work.

Oh, this depends on your specific network environment, whether it's an internal network or external network. If it's an external network, whether there is a public IP address, as well as routers, firewalls, etc. There are many factors.
--listen is necessary, but may not be enough.

**Comment by darcula1993** [comment]
> > > > I found this problem like 1 months ago. It came with gradio version upgrade I guess. This bug only occur when I use remote server to run "generate" with controlnet.
> > > 
> > > 
> > > I think so too. It should be related to the new version of gradio and the path handling of ControlNet. I found that this problem only occurs when using a remote server through SSH Tunnel. If opened directly through the IP address or URL, there is no problem.
> > 
> > 
> > Exactly! But how to open directly through the IP address? I use --listen but seems doesn't work.
> 
> Oh, this depends on your specific network environment, whether it's an internal network or external network. If it's an external network, whether there is a public IP address, as well as routers, firewalls, etc. There are many factors. --listen is necessary, but may not be enough.

try --no-gradio-queue,it works for me!

**Comment by sololll** [comment]
> > > > > I found this problem like 1 months ago. It came with gradio version upgrade I guess. This bug only occur when I use remote server to run "generate" with controlnet.
> > > > 
> > > > 
> > > > I think so too. It should be related to the new version of gradio and the path handling of ControlNet. I found that this problem only occurs when using a remote server through SSH Tunnel. If opened directly through the IP address or URL, there is no problem.
> > > 
> > > 
> > > Exactly! But how to open directly through the IP address? I use --listen but seems doesn't work.
> > 
> > 
> > Oh, this depends on your specific network environment, whether it's an internal network or external network. If it's an external network, whether there is a public IP address, as well as routers, firewalls, etc. There are many factors. --listen is necessary, but may not be enough.
> 
> try --no-gradio-queue,it works for me!

Great !
It works for me too.

**Comment by ameets21** [comment]
in My ControlNet, I get bloody random faces but don't get Output which I add as a reference.
I tried with Img2Img but same issue.
and This not only with ControlNet but with Roop too.
please help me to solve this issue
![Screenshot 2023-07-09 at 22-59-13 Stable Diffusion](https://github.com/Mikubill/sd-webui-controlnet/assets/7465991/19d36d00-57e6-4142-8734-f255284a820a)
