### ISSUE TITLE
[Feature] Files To Metadata

### ISSUE THREAD

**Issue by CVL1971** [Mikubill/sd-webui-controlnet#1570]
Would it be possible to add the option to include in the image metadata the name of the file(s) used by control.net, if any, which conditioned the diffusion of the image? It happens to me that I can't recreate/correct certain images because I don't know exactly what pose was used, out of the hundreds I have stored.

**Comment by huchenlei** [comment]
> Related to #305. I don't think there's a way to do this until Gradio supports it. [gradio-app/gradio#3158 (comment)](https://github.com/gradio-app/gradio/issues/3158#issuecomment-1460766959)

Agreed. As long as we are still using gradio image component, it is impossible to get uploaded image's original file name.

**Comment by Chubbly** [comment]
Is this still true if you use the batch functionality in ControlNet? The filename is stored is stored in a list somewhere, right?

I'm trying to understand this limitation in this discussion: https://github.com/Mikubill/sd-webui-controlnet/discussions/1809
