### ISSUE TITLE
[Bug]: Tutorial uses wrong parameters

### ISSUE THREAD

**Issue by Meerkov** [Mikubill/sd-webui-controlnet#1584]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

https://github.com/Mikubill/sd-webui-controlnet/wiki/API#integrating-sdapiv12img

It says to use "input_images" but the correct parameter name is "init_images".

It's not very clear how to get img2img working from the tutorial and requires tinkering, please double check it.

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

Tutorial would have correct arguments for img2img.

### Commit where the problem happens

webui: 
controlnet: 

### Command Line Arguments

```Shell
.
```

### List of enabled extensions

 .

### Console logs

```Shell
Two errors appear when following the tutorial as written

> {'error': 'HTTPException', 'detail': 'Init image not found', 'body': '', 'errors': ''}

> stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 286, in build_control_model
    raise RuntimeError(f"model not found: {model}")
RuntimeError: model not found: None
```

**Comment by huchenlei** [comment]
- `init_images` is the input image in A1111 img2img setting.
- `input_images` is the input image to controlnet. When you don't specify `input_images`, ControlNet will use `init_images` as fallback when it is available. 

Both are valid parameters.

**Comment by huchenlei** [comment]
It is very likely you used the txt2img payload in the tutorial and sent it to img2img endpoint. Closing for now.

**Comment by Meerkov** [comment]
You can't use the img2img payload as written, because it is missing the init_images parameter. The model is also not found. Please double check by using the exact payload in the tutorial on a fresh install.
