### ISSUE TITLE
No Control Net option in  X Y Script

### ISSUE THREAD

**Issue by demirklvc** [Mikubill/sd-webui-controlnet#159]
No Control Net option in  X Y Script

Im on the latest Update, several times restarted/reopened Stable. Please help me :)

**Comment by shinoratsutomu** [comment]
I think that I have same issue.
I can't find ControlNet in txt2img and img2img tabs.

Installed and updated sd-webui-controlnet on local WebUI.
The extensions and WebUI are latest version. 
Python 3.10.6

**Comment by Mikubill** [comment]
Try restart WebUI instead of reload/<Apply and restartUI>

**Comment by monmonchan** [comment]
おそらく同じ状況です。
restartUIしましたがありません。
Error loading script: controlnet.py
と出ています。

**Comment by monmonchan** [comment]
Probably the same situation.
I tried restartUI but there is none.
Error loading script: controlnet.py
I am getting the following error message.

**Comment by Mikubill** [comment]
Hmm.. can you share full log, or at least include some traceback?

**Comment by demirklvc** [comment]
> Try restart WebUI instead of reload/Apply and restartUI

didnt work for me

**Comment by demirklvc** [comment]
im getting no errors, just it appears nowhere

> I think that I have same issue. I can't find ControlNet in txt2img and img2img tabs.
> 
> Installed and updated sd-webui-controlnet on local WebUI. The extensions and WebUI are latest version and click "Apply and restart UI". Python 3.10.6

uhm this is my issue with no control net in X Y script. why would you write your comment here?

**Comment by monmonchan** [comment]
Already up to date.
error: patch failed: modules/script_callbacks.py:68
error: modules/script_callbacks.py: patch does not apply
error: patch failed: modules/sd_samplers_kdiffusion.py:8
error: modules/sd_samplers_kdiffusion.py: patch does not apply
venv "C:\Users\〇〇〇〇\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Commit hash: 3715ece0adce7bf7c5e9c5ab3710b2fdc3848f39
Installing requirements for Web UI
Installing None

Installing requirements for kohya sd-scripts

Installing requirement for sd-webui-controlnet

Launching Web UI with arguments: --no-half-vae
C:\Users\〇〇〇〇\stable-diffusion-webui\venv\lib\site-packages\pkg_resources\__init__.py:123: PkgResourcesDeprecationWarning: llow is an invalid version and will not be supported in a future release
  warnings.warn(
C:\Users\〇〇〇〇\stable-diffusion-webui\venv\lib\site-packages\pkg_resources\__init__.py:123: PkgResourcesDeprecationWarning: ansformers is an invalid version and will not be supported in a future release
  warnings.warn(
No module 'xformers'. Proceeding without it.
C:\Users\〇〇〇〇\stable-diffusion-webui\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
C:\Users\〇〇〇〇\stable-diffusion-webui\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
[AddNet] Updating model hashes...
100%|████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<?, ?it/s]
[AddNet] Updating model hashes...
100%|████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<?, ?it/s]
Error loading script: controlnet.py
Traceback (most recent call last):
  File "C:\Users\〇〇〇〇\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\〇〇〇〇\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\〇〇〇〇\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 18, in <module>
    from scripts.utils import load_state_dict
ImportError: cannot import name 'load_state_dict' from 'scripts.utils' (C:\Users\〇〇〇〇\stable-diffusion-webui\extensions\kohya-sd-scripts-webui\scripts\utils.py)

Loading weights [866946217b] from C:\Users\〇〇〇〇\stable-diffusion-webui\models\Stable-diffusion\ACertainThing.ckpt
Creating model from config: C:\Users\〇〇〇〇\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying cross attention optimization (Doggettx).
Textual inversion embeddings loaded(12): corneo_anal, corneo_ball_gag, corneo_bound_missionary, corneo_cowgirl, corneo_pov_anal, corneo_pov_oral, corneo_side_deepthroat, corneo_side_doggy, corneo_spitroast, corneo_tentacle_sex, CUserspinnkDesktop112asotaihi, NG_DeepNegative_V1_75T
Model loaded in 3.4s (load weights from disk: 0.8s, create model: 0.3s, apply weights to model: 0.4s, apply half(): 0.5s, move model to device: 0.6s, load textual inversion embeddings: 0.7s).
add tab
C:\Users\〇〇〇〇\stable-diffusion-webui\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

It's like this.

**Comment by Mikubill** [comment]
Seems like the sd-webui-controlnet extension in your webui is outdated. Try manuall update (such as git clone/remove extension and reinstall etc.)

**Comment by demirklvc** [comment]
what about me?

**Comment by Mikubill** [comment]
Hmm..no idea. cc @aiton-sd

**Comment by monmonchan** [comment]
Deleting the folder stable-diffusion-webui\extensions, installing the extensions again and starting webui again did not solve the problem.

**Comment by Mikubill** [comment]
Seems like #165 added some fix about it. Feel free to try and feedback

**Comment by siraxe** [comment]
having trouble as well , models don't appear in top left corner
or is it supposed be used from XYZ script ?
![image](https://user-images.githubusercontent.com/27487254/219766581-52fba3fa-e675-457f-b175-f4518ec0b442.png)
![image](https://user-images.githubusercontent.com/27487254/219766704-ce328102-1552-42f5-9abd-db14689f3b3f.png)
![image](https://user-images.githubusercontent.com/27487254/219766925-5b8a6b98-6e7a-471c-adbf-3cd418d75a0a.png)

**Comment by demirklvc** [comment]
fixed. thanks alot!

**Comment by siraxe** [comment]
> 

im an idiot it should appear on top of xyz scripts
![image](https://user-images.githubusercontent.com/27487254/219768784-62aecc02-473f-447c-9483-b04254195f99.png)

**Comment by monmonchan** [comment]
I was told it was fixed, so I deleted the folder under extensions just to be sure, reinstalled, restarted ui, but the problem was not fixed.
There is no indication of the controlnet tab itself…
