### ISSUE TITLE
Where should I access the technical report of Reference Only Control？

### ISSUE THREAD

**Issue by pixeli99** [Mikubill/sd-webui-controlnet#1590]
I would like to know the technical details of reference only, but it may be difficult for me to understand through reading the PR, so I am wondering if there are any technical reports that I can read?

**Comment by ifsheldon** [comment]
+1, I am trying to porting reference_only to ComfyUI but I find it hard to pick up a starting point.

**Comment by Vinicius-ufsc** [comment]
+1

**Comment by malteprinzler** [comment]
is there any news on this?

**Comment by syguan96** [comment]
any news?
