### ISSUE TITLE
[Bug]: txt2img outpainting using low-resolution image in hires. fix pass

### ISSUE THREAD

**Issue by catboxanon** [Mikubill/sd-webui-controlnet#1609]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When outpainting, it seems like hires. fix is not using the full resolution of the input image when applying the hires. fix pass. This basically nullifies the point of https://github.com/Mikubill/sd-webui-controlnet/discussions/1464.

### Steps to reproduce the problem

1. Input a high quality image into ControlNet

<details>
<summary>Image</summary>

https://unsplash.com/photos/fxszcH00OF4
![valentin-petkov-fxszcH00OF4-unsplash](https://github.com/Mikubill/sd-webui-controlnet/assets/122327233/63d2eb79-f930-472e-9f89-243473aa9aa7)
</details>

---

2. Outpaint _without_ hires fix. Notice the results here are fine.
<details>
<summary>Image</summary>

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/122327233/6dd9189f-3f2c-4585-8b64-350c1c0d2ada)
</details>

3. Outpaint _with_ hires fix. (see result below, which includes PNG metadata for reproduction)
<details>
<summary>Image</summary>

![56e4e11b8ab423407926449f2dc5b3b4bde6b06e3d76fcbbda2ba6df967fb7be](https://github.com/Mikubill/sd-webui-controlnet/assets/122327233/bb4b66e7-1d70-4a08-bb30-f2a1e4f211d2)
</details>

4. Notice the original image is noticeably blurrier/more pixelated, even from the rest of the outpaint, almost as if it simply took the intermediary output before hires fix, instead of using the original image (see result in section for what it should look more like).

### What should have happened?

Hires. fix should not use the low-resolution (I assume pre-hires fix?) pass.

The final output should look something more like this. For this I took the original image and downscaled it manually on top of the webui's hires fix output (disregard the seams).

<details>
<summary>Image</summary>

![fix](https://github.com/Mikubill/sd-webui-controlnet/assets/122327233/a0566219-2b00-48d1-9f0e-f83519dc9a4c)
</details>

### Commit where the problem happens

webui: https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/59419bd64a1581caccaac04dceb66c1c069a2db1 (1.4.0-RC)
controlnet: https://github.com/Mikubill/sd-webui-controlnet/commit/4f884009efddf72c33493e3a7927f04817a719d7 (1.1.223)

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
n/a
```

### List of enabled extensions

(only ControlNet)

### Console logs

```Shell
n/a
```

### Additional information

This does **not** seem to occur for inpainting, only for outpainting.

**Comment by lllyasviel** [comment]
fixed in 1.1.224 - this only happens to lama. inpaint_only 223 does not have problem,
see if fixed and close

**Comment by lllyasviel** [comment]
also it seems that a1111's high res fix for inpaint pariation model in t2i is broken
