### ISSUE TITLE
how to use controlnet by webapi

### ISSUE THREAD

**Issue by J-Wu97** [Mikubill/sd-webui-controlnet#1620]
It doesn't work by run the code tests/web_api/img2img_test.py
how to generate pics with controlnet by using the webapi?

**Comment by huchenlei** [comment]
See discussion here:
https://github.com/Mikubill/sd-webui-controlnet/discussions/1614

Will you find it helpful if there is a button to show you the corresponding API payload based on current ControlNetUnit's UI state?

**Comment by huchenlei** [comment]
`tests/web_api/img2img_test.py` is a test file, and is not intended to be run by users. You can follow the API wiki here:
https://github.com/Mikubill/sd-webui-controlnet/wiki/API#web-api

**Comment by J-Wu97** [comment]
> 

Your example does not work too. The controlnet is not loaded in the webui and the corresponding scripts returns None.

**Comment by J-Wu97** [comment]
I have checked all the discussion about the webapi.
This one is similar to mine. https://github.com/Mikubill/sd-webui-controlnet/issues/1213. But i don't figure out how to solve this problem.
