### ISSUE TITLE
[Bug]: When using both tile-color fix and "AND" command, Mismatch of tensor at non-singleton dimension 0

### ISSUE THREAD

**Issue by jimlin1668478052** [Mikubill/sd-webui-controlnet#1622]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When I tried to use both the tile-color fix (including tile-color fix+sharp),  and "AND" command (as required for use of latent couple), the error as below appears:

Traceback (most recent call last):
  File "/workspace/sd/stable-diffusion-webui/modules/call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "/workspace/sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/workspace/sd/stable-diffusion-webui/modules/img2img.py", line 178, in img2img
    processed = process_images(p)
  File "/workspace/sd/stable-diffusion-webui/modules/processing.py", line 610, in process_images
    res = process_images_inner(p)
  File "/workspace/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "/workspace/sd/stable-diffusion-webui/modules/processing.py", line 728, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "/workspace/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 350, in process_sample
    return process.sample_before_CN_hack(*args, **kwargs)
  File "/workspace/sd/stable-diffusion-webui/modules/processing.py", line 1261, in sample
    samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
  File "/workspace/sd/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 356, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "/workspace/sd/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 257, in launch_sampling
    return func()
  File "/workspace/sd/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 356, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/sd/stablediffusion/src/k-diffusion/k_diffusion/sampling.py", line 594, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/sd/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 156, in forward
    x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond=make_condition_dict(c_crossattn, image_cond_in[a:b]))
RuntimeError: The expanded size of the tensor (1) must match the existing size (2) at non-singleton dimension 0.  Target sizes: [1, 4, 192, 128].  Tensor sizes: [2, 4, 192, 128]

This error does not happen when using tile_resample (while, there is a well-known issue of color shift) nor when I removed the "AND" command

<img width="539" alt="Screenshot 2023-06-11 111721" src="https://github.com/Mikubill/sd-webui-controlnet/assets/42947184/eb94c983-7c20-4931-959d-75c468b925aa">

### Steps to reproduce the problem

1. write a prompt with "AND" used
2. Use Control net tile-color fix

### What should have happened?

The error should not appear and images can be generated normally

### Commit where the problem happens

webui: [API](https://3hodsge55h9pyh-3000.proxy.runpod.net/docs)  •  [Github](https://github.com/AUTOMATIC1111/stable-diffusion-webui)  •  [Gradio](https://gradio.app/)  •  [Reload UI](https://3hodsge55h9pyh-3000.proxy.runpod.net/)
version: [v1.3.2](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/baf6946e06249c5af9851c60171692c44ef633e0)  •  python: 3.10.10  •  torch: 2.0.0+cu117  •  xformers: N/A  •  gradio: 3.29.0  •  checkpoint: [5493a0ec49](https://google.com/search?q=5493a0ec491f5961dbdc1c861404088a6ae9bd4007f6a3a7c5dee8789cdc1361)
controlnet: v1.1.224

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### List of enabled extensions

<html>
<body>

Stable-Diffusion-Webui-Civitai-Helper | https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper.git | main | 920ca326 | Tue May 23 11:53:22 2023 | unknown
-- | -- | -- | -- | -- | --
a1111-sd-webui-lycoris | https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris | main | e4754888 | Tue Jun 6 02:12:14 2023 | unknown
deforum-for-automatic1111-webui | https://github.com/deforum-art/deforum-for-automatic1111-webui.git | automatic1111-webui | b58056f9 | Tue Jun 6 21:47:35 2023 | unknown
multidiffusion-upscaler-for-automatic1111 | https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111 | main | 70b3c5ea | Sun May 28 09:11:28 2023 | unknown
openOutpaint-webUI-extension | https://github.com/zero01101/openOutpaint-webUI-extension.git | main | 5e84d6d5 | Mon Apr 10 23:01:41 2023 | unknown
openpose-editor | https://github.com/fkunn1326/openpose-editor.git | master | 722bca6f | Sat Jun 3 04:54:52 2023 | unknown
posex | https://github.com/hnmr293/posex.git | master | 292f92d5 | Wed May 3 08:59:57 2023 | unknown
sd-dynamic-thresholding | https://github.com/mcmonkeyprojects/sd-dynamic-thresholding.git | master | f02cacfc | Mon May 22 14:20:30 2023 | unknown
sd-webui-3d-open-pose-editor | https://github.com/nonnonstop/sd-webui-3d-open-pose-editor.git | main | f2d5aac5 | Sat Apr 15 13:21:06 2023 | unknown
sd-webui-additional-networks | https://github.com/kohya-ss/sd-webui-additional-networks.git | main | e9f3d622 | Tue May 23 12:31:15 2023 | unknown
sd-webui-controlnet | https://github.com/Mikubill/sd-webui-controlnet.git | main | 133f20ac | Sun Jun 11 15:20:00 2023 | unknown
sd-webui-cutoff | https://github.com/hnmr293/sd-webui-cutoff | main | 3a073e9c | Wed May 3 07:14:40 2023 | unknown
sd-webui-neutral-prompt | https://github.com/ljleb/sd-webui-neutral-prompt.git | main | 6e3df35a | Wed May 31 05:29:17 2023 | unknown
sd-webui-regional-prompter | https://github.com/hako-mikan/sd-webui-regional-prompter.git | main | f71aa479 | Wed May 31 11:11:41 2023 | unknown
stable-diffusion-webui-composable-lora | https://github.com/a2569875/stable-diffusion-webui-composable-lora | main | 90de77aa | Tue May 30 05:13:39 2023 | unknown
stable-diffusion-webui-two-shot | https://github.com/ashen-sensored/stable-diffusion-webui-two-shot | main | 6b55dd52 | Sun Apr 2 11:24:25 2023 | unknown
LDSR | built-in | None |   | Sun Jun 11 17:50:39 2023 |  
Lora | built-in | None |   | Sun Jun 11 17:50:39 2023 |  
ScuNET | built-in | None |   | Sun Jun 11 17:50:39 2023 |  
SwinIR | built-in | None |   | Sun Jun 11 17:50:39 2023 |  
prompt-bracket-checker | built-in | None |   | Sun Jun 11 17:50:39 2023

</body>
</html>Stable-Diffusion-Webui-Civitai-Helper	https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper.git	main	[920ca326](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/commit/920ca3267f789a72e3225c99f069bf0be0db795d)	Tue May 23 11:53:22 2023	unknown
a1111-sd-webui-lycoris	https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris	main	[e4754888](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/commit/e47548884864da9cfe30f6f33fbaa8e731d3dd85)	Tue Jun 6 02:12:14 2023	unknown
deforum-for-automatic1111-webui	https://github.com/deforum-art/deforum-for-automatic1111-webui.git	automatic1111-webui	[b58056f9](https://github.com/deforum-art/deforum-for-automatic1111-webui/commit/b58056f9113b0c6d305642dad6d3bd238b2b9132)	Tue Jun 6 21:47:35 2023	unknown
multidiffusion-upscaler-for-automatic1111	https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111	main	[70b3c5ea](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/commit/70b3c5ea3c9f684d04e7ff59167565974415735c)	Sun May 28 09:11:28 2023	unknown
openOutpaint-webUI-extension	https://github.com/zero01101/openOutpaint-webUI-extension.git	main	[5e84d6d5](https://github.com/zero01101/openOutpaint-webUI-extension/commit/5e84d6d5b1057f837eeecaa49a92a235dd589bc5)	Mon Apr 10 23:01:41 2023	unknown
openpose-editor	https://github.com/fkunn1326/openpose-editor.git	master	[722bca6f](https://github.com/fkunn1326/openpose-editor/commit/722bca6fb9b062815d13b950e7040589abaec797)	Sat Jun 3 04:54:52 2023	unknown
posex	https://github.com/hnmr293/posex.git	master	[292f92d5](https://github.com/hnmr293/posex/commit/292f92d5068046f988fe002eb0a43b8841ad449e)	Wed May 3 08:59:57 2023	unknown
sd-dynamic-thresholding	https://github.com/mcmonkeyprojects/sd-dynamic-thresholding.git	master	[f02cacfc](https://github.com/mcmonkeyprojects/sd-dynamic-thresholding/commit/f02cacfc923e8bbf73f25327d722d50c458d66bb)	Mon May 22 14:20:30 2023	unknown
sd-webui-3d-open-pose-editor	https://github.com/nonnonstop/sd-webui-3d-open-pose-editor.git	main	[f2d5aac5](https://github.com/nonnonstop/sd-webui-3d-open-pose-editor/commit/f2d5aac51d891bc5f266b1549f3cf4495fc52160)	Sat Apr 15 13:21:06 2023	unknown
sd-webui-additional-networks	https://github.com/kohya-ss/sd-webui-additional-networks.git	main	[e9f3d622](https://github.com/kohya-ss/sd-webui-additional-networks/commit/e9f3d622b5a98650008a685ea23b27eb810da35a)	Tue May 23 12:31:15 2023	unknown
sd-webui-controlnet	https://github.com/Mikubill/sd-webui-controlnet.git	main	[133f20ac](https://github.com/Mikubill/sd-webui-controlnet/commit/133f20ac9eebd33abecfd043fc1e3913267a0f76)	Sun Jun 11 15:20:00 2023	unknown
sd-webui-cutoff	https://github.com/hnmr293/sd-webui-cutoff	main	[3a073e9c](https://github.com/hnmr293/sd-webui-cutoff/commit/3a073e9c4525c21b72ae4645125768457c9c98e1)	Wed May 3 07:14:40 2023	unknown
sd-webui-neutral-prompt	https://github.com/ljleb/sd-webui-neutral-prompt.git	main	[6e3df35a](https://github.com/ljleb/sd-webui-neutral-prompt/commit/6e3df35afe9ea1c8bb121086d15156feca4d3d85)	Wed May 31 05:29:17 2023	unknown
sd-webui-regional-prompter	https://github.com/hako-mikan/sd-webui-regional-prompter.git	main	[f71aa479](https://github.com/hako-mikan/sd-webui-regional-prompter/commit/f71aa479e00736e2c9e19d986f977bdb4bf4f9c7)	Wed May 31 11:11:41 2023	unknown
stable-diffusion-webui-composable-lora	https://github.com/a2569875/stable-diffusion-webui-composable-lora	main	[90de77aa](https://github.com/a2569875/stable-diffusion-webui-composable-lora/commit/90de77aaf071225416d6a6818214c536e0c4c0c0)	Tue May 30 05:13:39 2023	unknown
stable-diffusion-webui-two-shot	https://github.com/ashen-sensored/stable-diffusion-webui-two-shot	main	[6b55dd52](https://github.com/ashen-sensored/stable-diffusion-webui-two-shot/commit/6b55dd5248fd07f55ffefbf9be369b439b239502)	Sun Apr 2 11:24:25 2023	unknown
LDSR	[built-in](https://3hodsge55h9pyh-3000.proxy.runpod.net/)	None		Sun Jun 11 17:50:39 2023	
Lora	[built-in](https://3hodsge55h9pyh-3000.proxy.runpod.net/)	None		Sun Jun 11 17:50:39 2023	
ScuNET	[built-in](https://3hodsge55h9pyh-3000.proxy.runpod.net/)	None		Sun Jun 11 17:50:39 2023	
SwinIR	[built-in](https://3hodsge55h9pyh-3000.proxy.runpod.net/)	None		Sun Jun 11 17:50:39 2023	
prompt-bracket-checker	[built-in](https://3hodsge55h9pyh-3000.proxy.runpod.net/)	None		Sun Jun 11 17:50:39 2023

### Console logs

```Shell
2023-06-11 18:10:40,962 - ControlNet - INFO - Loading model: control_v11f1e_sd15_tile [a371b31b]
2023-06-11 18:10:41,475 - ControlNet - INFO - Loaded state_dict from [/workspace/sd/stable-diffusion-webui/models/ControlNet/control_v11f1e_sd15_tile.pth]
2023-06-11 18:10:41,475 - ControlNet - INFO - Loading config: /workspace/sd/stable-diffusion-webui/models/ControlNet/control_v11f1e_sd15_tile.yaml
2023-06-11 18:10:43,999 - ControlNet - INFO - ControlNet model control_v11f1e_sd15_tile [a371b31b] loaded.
2023-06-11 18:10:44,023 - ControlNet - INFO - API used default config: unit.threshold_b = 1.0
2023-06-11 18:10:44,023 - ControlNet - INFO - Loading preprocessor: tile_colorfix+sharp
2023-06-11 18:10:44,023 - ControlNet - INFO - preprocessor resolution = 512
Found LyCORIS models, Using Composable LyCORIS.
Composable LoRA load successful.
  0%|                                                    | 0/45 [00:00<?, ?it/s]2023-06-11 18:10:49,584 - ControlNet - INFO - ControlNet used torch.float32 VAE to encode torch.Size([1, 4, 192, 128]).
  0%|                                                    | 0/45 [00:07<?, ?it/s]
Error completing request
Arguments: ('task(fb3x0gvm9fqqbl6)', 0, 'masterpiece, best quality, high resolution 8K wallpaper, front view, original, dynamic composition, dynamic angle, splendid, 6girls\nAND masterpiece, best quality, high resolution 8K wallpaper, side view, looking right, original, dynamic composition, dynamic angle, splendid, 6girls, meisho doto \\(umamusume\\), white shirt, collared shirt, white gloves, shoulder bag, strap between breasts, blue skirt, long sleeves, white thighhighs, handbag, center frills, sleeves past wrists, <lora:meisho_doto_lora:0.8>\nAND masterpiece, best quality, high resolution 8K wallpaper, front view, original, dynamic composition, dynamic angle, splendid, 6girls,  <lyco:jungle_pocket_loha:0.7>, jungle pocket \\(umamusume\\), ear ornament, hairclip, yellow jacket, crop top, cropped jacket, open clothes, open jacket, strapless, tube top, bandeau, long sleeves, midriff, navel, suspenders, animal print, belt, suspender skirt, black skirt, pleated skirt, green socks, black footwear, boots\nAND masterpiece, best quality, high resolution 8K wallpaper, front view, original, dynamic composition, dynamic angle, splendid, 6girls, <lora:manhattan_cafe_lora:0.7>, manhattan cafe \\(umamusume\\), black choker, black gloves, long sleeves, collared shirt, yellow necktie, black vest, black coat, belt, black skirt, pleated skirt, black pantyhose, shoes, white footwear\nAND masterpiece, best quality, high resolution 8K wallpaper, front view, original, dynamic composition, dynamic angle, splendid, 6girls, <lora:agnes_digital_r4_lora:0.8>, agnes digital \\(umamusume\\), single thighhighs, sleeveless, single glove, garter straps, white gloves, crop top, frills, sailor collar, multicolored skirt, multicolored clothes, layered skirt, red belt, white shirt\nAND masterpiece, best quality, high resolution 8K wallpaper, from_behind, back view, side view, original, dynamic composition, dynamic angle, splendid, 6girls, t.m. opera o \\(umamusume\\), mini crown, ear piercing, white shirt, shoulder armor, pink cape, white skirt, pink skirt, two-tone skirt, pleated skirt, white thighhighs, zettai ryouiki, open mouth, smile  <lyco:tMOperaOUmamusume_loha:0.8>\nAND masterpiece, best quality, high resolution 8K wallpaper, front view, original, dynamic composition, dynamic angle, splendid, 6girls,   <lyco:naritaTopRoad_loha:0.8>, narita top road \\(umamusume\\), ear cover, star hair ornament, brooch, sleeveless dress, purple dress, white bow, mismatched gloves, white gloves, black gloves, shoulder cutout, puffy long sleeves, detached sleeves, see-through sleeves, frills, shorts under dress, short shorts, purple shorts, thigh strap', '(negative_hand-neg:0.8)', [], <PIL.Image.Image image mode=RGBA size=1024x1536 at 0x7F363C72F100>, None, None, None, None, None, None, 45, 15, 4, 0, 1, False, False, 1, 1, 7, 1.5, 0.55, -1.0, -1.0, 0, 0, 0, False, 1, 512, 512, 1, 0, 0, 32, 0, '', '', '', [], 0, False, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 4, 'None', 2, False, 10, 1, 1, 64, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 3072, 192, True, True, True, False, False, '', 0, False, 7, 100, 'Constant', 0, 'Constant', 0, 4, False, False, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, None, 'Refresh models', <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x7f3664c31840>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x7f363cc105b0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x7f3664c31f60>, False, '', 0.5, True, False, '', 'Lerp', False, 0, False, False, 'Matrix', 'Horizontal', 'Mask', 'Prompt', '1,1', '0.2', False, False, False, 'Attention', False, '0', '0', '0.4', None, True, False, False, False, False, False, True, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 150, 0.2, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 1, 1, 1, 1, 1, 1, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, None, None, False, None, None, False, None, None, False, 50) {}
Traceback (most recent call last):
  File "/workspace/sd/stable-diffusion-webui/modules/call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "/workspace/sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/workspace/sd/stable-diffusion-webui/modules/img2img.py", line 178, in img2img
    processed = process_images(p)
  File "/workspace/sd/stable-diffusion-webui/modules/processing.py", line 610, in process_images
    res = process_images_inner(p)
  File "/workspace/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "/workspace/sd/stable-diffusion-webui/modules/processing.py", line 728, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "/workspace/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 350, in process_sample
    return process.sample_before_CN_hack(*args, **kwargs)
  File "/workspace/sd/stable-diffusion-webui/modules/processing.py", line 1261, in sample
    samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
  File "/workspace/sd/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 356, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "/workspace/sd/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 257, in launch_sampling
    return func()
  File "/workspace/sd/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 356, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/sd/stablediffusion/src/k-diffusion/k_diffusion/sampling.py", line 594, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/sd/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 156, in forward
    x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond=make_condition_dict(c_crossattn, image_cond_in[a:b]))
RuntimeError: The expanded size of the tensor (1) must match the existing size (2) at non-singleton dimension 0.  Target sizes: [1, 4, 192, 128].  Tensor sizes: [2, 4, 192, 128]
```

**Comment by ljleb** [comment]
Does the error still occur if you disable the neutral-prompt extension?

**Comment by jimlin1668478052** [comment]
Nope. The same issue.

**Comment by ljleb** [comment]
This is unrelated to controlnet then. Please reopen this issue in the appropriate repository.
