### ISSUE TITLE
[Bug] UnboundLocalError: local variable 'cond_cast_unet' referenced before assignment

### ISSUE THREAD

**Issue by liberate-your-heart** [Mikubill/sd-webui-controlnet#163]
Thank you for your great work! But when I enable ControlNet, the console always reports this error. 
The error message is very long, and the general content is as follows:

Error completing request
Arguments: ......
{'image': array([[[ ...... ]]], dtype=uint8)}, False, 'Scale to Fit (Inner Fit)', False, False, 512, 100, 200, 1, 0.9, 5, '0.0001', False, 'None', '', 0.1, False, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0) {}

Traceback (most recent call last):
......(very long). The last sentence is:
  File "D:\WebUI\extensions\sd-webui-controlnet\scripts\cldm.py", line 425, in forward
    def forward(self, x, hint, timesteps, context, **kwargs):
UnboundLocalError: local variable 'cond_ cast_ unet' referenced before assignment

How can I solve it?

**Comment by Mikubill** [comment]
update and restart webui will fix it

**Comment by liberate-your-heart** [comment]
It works, thanks!
