### ISSUE TITLE
[Bug]: error on install on mac

### ISSUE THREAD

**Issue by ecreatures** [Mikubill/sd-webui-controlnet#1637]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I GitCommandError: Cmd('git') failed due to: exit code(129) cmdline: git clone -v --filter=blob:none -- https://github.com/Mikubill/sd-webui-controlnet.git /Users/mic/stable-diffusion-webui/tmp/sd-webui-controlnet stderr: 'error: unknown option `filter=blob:none' u
when I click on install

### Steps to reproduce the problem

1. Go to stable diffusion web UI
2. paste https://github.com/Mikubill/sd-webui-controlnet.git
3. click on install

### What should have happened?

Successfull instalation of the extension

### Commit where the problem happens

webui: version: [v1.3.2](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/baf6946e06249c5af9851c60171692c44ef633e0)
controlnet: 

### What browsers do you use to access the UI ?

Apple Safari

### Command Line Arguments

```Shell
NO
```

### List of enabled extensions

LDSR		
Lora		
ScuNET		
SwinIR		
prompt-bracket-checke

### Console logs

```Shell
none
```

**Comment by LinkTree3** [comment]
I'm having the same issue right now. Can't install ControlNet :(
