### ISSUE TITLE
[REQUEST]: New method segcanny

### ISSUE THREAD

**Issue by pakresi** [Mikubill/sd-webui-controlnet#1656]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Hello, when mixing seg and canny its more useful for inpainting
Maybe there can be a canny option like this.

![SEGCANNY](https://github.com/Mikubill/sd-webui-controlnet/assets/133514291/22c00b2c-3fda-4744-ad32-ce13d823e439)

You can try yourself

**Comment by pakresi** [comment]
because of lines creating similar limit dresses or disfigured objects in front of picture

its just an idea now works better in my demos. (generation seg 0.3 sec with api)

Seg and canny together **just creating limits of outlines of object**, 2nd controlnet with depth you not need openpose. Creating same shape object not thing or thick

**Comment by huchenlei** [comment]
Can you give an example of the usage/workflow?
