### ISSUE TITLE
Feauture Request: Ability to Point to a Folder when using Control Net in the Text2IMG Tab

### ISSUE THREAD

**Issue by demirklvc** [Mikubill/sd-webui-controlnet#166]
Feauture Request: Ability to Point to a Folder when using Control Net in the Text2IMG Tab

So one can test many Images at once in that Area too. i know this is already possible in IMG2IMG tab but:
Input Image changes the results, even at 1 Denoising.

Please :)

**Comment by FizzleDorf** [comment]
isn't this the same request as #74?
