### ISSUE TITLE
[Feature] Loopback X step

### ISSUE THREAD

**Issue by olamedia** [Mikubill/sd-webui-controlnet#1670]
Use X step (including txt2img) (custom number) as input for controlnet tab and then trigger preprocessing it, clear input image at the start of new generation if number is set.

This will alllow to use X step for input of openpose, for example. Then it will be useful to have ability to select some custom script to post-process that generated openpose to remove extra bodies and to fix broken anatomy by adjusting angles in openpose json.

**Comment by olamedia** [comment]
It may be also useful to restart generation after X step reached in first tab (then after Y step reached in second tab, etc), to end up generating image with all maps ready from the first step.

**Comment by huchenlei** [comment]
Please describe in detail:
- What problem the feature is trying to solve.
- How the user is expected to use this feature. What is the workflow, e.g. 1. check a newly added checkbox, 2. click...

**Comment by olamedia** [comment]
What problem the feature is trying to solve:
Allow user to intervene into generation process in the middle. For example, to apply fixes (to the pose etc) in the middle of the generation instead of postprocessing bad generations like adetailer.

Expected workflow:
1. set the desired step at textbox, optionally check a checkbox "[V] Loopback at step [___5___]"
2. at the selected step the input will be filled with the image being generated therefore controlnet tab starts to work
3. optionally, restart generation after each input image was set, can be a checkbox "[V] Restart generation after input was set"
4. after image was generated with all input images set, clear input images for such tabs (for batch mode)

**Comment by olamedia** [comment]
Depends on https://github.com/Mikubill/sd-webui-controlnet/issues/1674 to actually modify processing

**Comment by olamedia** [comment]
Since there's already a slider to define the starting step, the checkbox is only needed may be.
But small textboxes near the sliders would be easier to control precisely down to the concrete step.
