### ISSUE TITLE
[Bug]: detected_maps force-created in app root

### ISSUE THREAD

**Issue by vladmandic** [Mikubill/sd-webui-controlnet#1672]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

`detected_maps` folder is force-created in main app's root folder regardless of user option `control_net_detectedmap_dir`

```python
cn_detectedmap_dir = os.path.join("detected_maps")
default_detectedmap_dir = cn_detectedmap_dir
...
os.makedirs(cn_detectedmap_dir, exist_ok=True)
```

### Steps to reproduce the problem

N/A

### What should have happened?

N/A

### Commit where the problem happens

controlnet 1.1.224 (41011be)

### Command Line Arguments

```Shell
N/A
```

### List of enabled extensions

N/A

### Console logs

```Shell
N/A
```

**Comment by huchenlei** [comment]
Fixed in https://github.com/Mikubill/sd-webui-controlnet/pull/1677.
