### ISSUE TITLE
controlNet Installed and updated but not showing in Vlad

### ISSUE THREAD

**Issue by Koguist4** [Mikubill/sd-webui-controlnet#1676]
I copied the URL for the manual install and nothing appened, Somehow the extention is installed at \automatic\extensions as sd-webui-controlnet. Im doing something wrong. Cant see it under FromText or FromImage tabs in VLAD.

Thanks

**Comment by huchenlei** [comment]
You probably want to ask in v1111 repo instead of here. 
https://github.com/vladmandic/automatic/issues
