### ISSUE TITLE
Runtime Error when using text2img sizes other than 512

### ISSUE THREAD

**Issue by Neverdusk** [Mikubill/sd-webui-controlnet#168]
This is a problem that was solved previous, but seems to have come back up after I updated the extension to its latest version.

Whenever I use parameters other than 512 in the text2img tab, I get the following error: 
> RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 14 but got size 13 for tensor number 1 in the list.

The actual "expected size" and "size" values seem to depend on the length / width I set. If I do 640x320, I get the above values (14/13). But doing 640x640 gives me different values (26/25). 

This happens regardless of the size of the input ControlNet images, so it seems to be entirely dependent on text2img settings. It also doesn't seem to be affected by the selected preprocessor or ControlNet model. I've attached a full log in case it helps.
[Log.txt](https://github.com/Mikubill/sd-webui-controlnet/files/10772394/Log.txt)

As a result, doing any aspect ratio or render size other than 512x512 seems impossible at the moment.

**Comment by Mikubill** [comment]
Hmm.. does the latest commit works?

**Comment by Neverdusk** [comment]
I updated again, and I think it does. I'm now able to create both 640x640 and 320x640 images without any errors.
