### ISSUE TITLE
[Bug]: All models but Canny throw UnpicklingError: pickle data was truncated

### ISSUE THREAD

**Issue by roseyyy2022ai** [Mikubill/sd-webui-controlnet#1681]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

All models except Canny seem to not be working.
At first it was saying that there's an "extension conflict" so I tried clean installing SD with no extensions but controlnet.
It worked, but only "unblocked" the canny model. Trying to use anything else throws this error.

### Steps to reproduce the problem

1. Install SD with Controlnet
2. input the prompt and select any model other than Canny in CN
3. Press "generate"
4. Observe error in the console

### What should have happened?

The other models should be loading as normal.

### Commit where the problem happens

webui: [59ffe2243a](https://google.com/search?q=59ffe2243a25c9fe137d590eb3c5c3d3273f1b4c86252da11bbdc9568773da0c)
controlnet: v1.1.224 [784eadbb](https://github.com/Mikubill/sd-webui-controlnet/commit/784eadbba6600b3ecc2e3b07363895e42d6b3e8f)

### What browsers do you use to access the UI ?

Google Chrome, Microsoft Edge

### Command Line Arguments

```Shell
--share --disable-safe-unpickle --no-half-vae --xformers --enable-insecure-extension-access --gradio-queue --api --remotemoe
```

### List of enabled extensions

Controlnet, sd-webui-tunnels (temporarily disabled)

### Console logs

```Shell
Trying to load the depth model:


2023-06-23 08:51:51,625 - ControlNet - INFO - Loading model: control_v11f1p_sd15_depth [e3b0c442]
Error running process: /content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 451, in process
    script.process(p, *script_args)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 708, in process
    model_net = Script.load_control_model(p, unet, unit.model, unit.low_vram)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 265, in load_control_model
    model_net = Script.build_control_model(p, unet, model, lowvram)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 293, in build_control_model
    state_dict = load_state_dict(model_path)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 20, in load_state_dict
    torch.load(ckpt_path, map_location=torch.device(location))
  File "/content/stable-diffusion-webui/modules/safe.py", line 107, in load
    return load_with_extra(filename, *args, extra_handler=global_extra_handler, **kwargs)
  File "/content/stable-diffusion-webui/modules/safe.py", line 152, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: pickle data was truncated

  0% 0/13 [00:00<?, ?it/s]
  8% 1/13 [00:00<00:10,  1.19it/s]
 15% 2/13 [00:01<00:05,  1.89it/s]
 23% 3/13 [00:01<00:04,  2.33it/s]
 31% 4/13 [00:01<00:03,  2.59it/s]
 38% 5/13 [00:02<00:02,  2.79it/s]
 46% 6/13 [00:02<00:02,  2.90it/s]
 54% 7/13 [00:02<00:02,  3.00it/s]
 62% 8/13 [00:03<00:01,  3.06it/s]
 69% 9/13 [00:03<00:01,  3.11it/s]
 77% 10/13 [00:03<00:00,  3.14it/s]
 85% 11/13 [00:03<00:00,  3.17it/s]
 92% 12/13 [00:04<00:00,  3.15it/s]
100% 13/13 [00:04<00:00,  2.82it/s]

Total progress: 100% 13/13 [00:04<00:00,  2.69it/s]
```

**Comment by huchenlei** [comment]
Can you explain why you have `--disable-safe-unpickle` flag in commandline arguments?

**Comment by roseyyy2022ai** [comment]
> Can you explain why you have `--disable-safe-unpickle` flag in commandline arguments?

Because in the previous versions this bug occasionally popped up until I added the argument 🤷‍♀️

**Comment by lllyasviel** [comment]
https://github.com/Mikubill/sd-webui-controlnet/blob/8e143d3545140b8f0398dfbe1d95a0a766019283/README.md?plain=1#L38
