### ISSUE TITLE
New iimg2img  masking npaint mode  function that ignores colours of the source  image  

### ISSUE THREAD

**Issue by 2blackbar** [Mikubill/sd-webui-controlnet#169]
Hey , as of now we have masked  img2img but even with denoise slider to the max it still picksup the colours from the source image so... would it be possible to create additional option to ignore those ? 
So it would work like in txt2img mode where colors are totally ignored and just  controlnet guides are used , but this time with mask to replace only area that we want or for example hheres hard case scenario ...    image with guy wearing black shirt , if you want to turn him into astronaut in white spacesuit its almost impossible with img2img cause it still picksup his black shirt, but its very easy with txt2img controlnet because it  ignores source colours,  but we cant mask the face so it would stay unchanged  and only area around it gets replaced.

Can something like this be done ? maybe in inpaint mode for img2img , additional tickbox to totally ignore colours from source image ?

Also i think it would need to transfer the skin colour of the face  still so it would erge seamlessly, but info about colour  outside of the mask should be ignored , should work in theory, but could also be a fail.

**Comment by AbyszOne** [comment]
That effect is very useful. Its ok if we can choice to avoid it, but we absolutely shouldn't remove it.
