### ISSUE TITLE
errors in controlnet - not fixed

### ISSUE THREAD

**Issue by shihanqu** [Mikubill/sd-webui-controlnet#1693]
### Discussed in https://github.com/Mikubill/sd-webui-controlnet/discussions/1682

<div type='discussions-op-text'>

<sup>Originally posted by **Rejimon-12** June 23, 2023</sup>
WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args passed to ControlNet: (<scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x290d69e40>,).</div>

Still getting an error with deforum:
" WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args passed to ControlNet: [<extensions.sd-webui-controlnet.scripts.external_code.ControlNetUnit object at 0x000001D9C2F45930>, <extensions.sd-webui-controlnet.scripts.external_code.ControlNetUnit object at 0x000001D9C2F45360>, <extensions.sd-webui-controlnet.scripts.external_code.ControlNetUnit object at 0x000001D9C2F44E50>, <extensions.sd-webui-controlnet.scripts.external_code.ControlNetUnit object at 0x000001D9C2F47010>, <extensions.sd-webui-controlnet.scripts.external_code.ControlNetUnit object at 0x000001D9C2F441F0>]."

I've made a fresh install of A1111, ControlNet and Deforum. Currently running ControlNet v1.1.226. Been trying to get controlnet to work with deforum for a long time, though I'm glad at least it's showing errors instead of being silent. I suspect controlnet hasn't worked with deforum for a bit, and most just haven't noticed because errors weren't reported until recently.

**Comment by huchenlei** [comment]
I would suspect that the `ControlNetUnit` is created and passed to `ControlNet` after an extension reload. Do you still get the error  after completely restart WebUI? (i.e. close terminal and relaunch through .bat file)

**Comment by huchenlei** [comment]
I think the extension loading mechanism A1111 has is the worst part of A1111.
The reload extension button does very little job, which made a large distinction between reload/restart. 

The ControlNet extension tries to make the reload behaves the same way as restart through dynamic module reloading, but different versions of class/function implementations floating around actually introduce more subtle bugs.

**Comment by shingj** [comment]
I am having this issue as well, restarted with and without flags. Error shows on latest commit (c36b5a0d)

**Comment by cool-bigdogs-tshirt** [comment]
i think `isinstance` is too fragile for the amount of monkeypatching that goes on in the main codebase. `type(script_arg).__name__ == 'ControlNetUnit'` might be better?

**Comment by huchenlei** [comment]
> i think `isinstance` is too fragile for the amount of monkeypatching that goes on in the main codebase. `type(script_arg).__name__ == 'ControlNetUnit'` might be better?

#1695 tries to resolve this.
Check name is not a good idea as other code might extends the class and give totally irrelevant name. 

I check whether the instance has all fields defined in the up-to-date `ControlNetUnit` in the PR as a compromise.

**Comment by huchenlei** [comment]
Fixed in v1.1.227.

**Comment by roseyyy2022ai** [comment]
guys it gives UnpicklingError: pickle data was truncated for me

My logs:
2023-06-23 08:51:51,625 - ControlNet - INFO - Loading model: control_v11f1p_sd15_depth [e3b0c442]
Error running process: /content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 451, in process
    script.process(p, *script_args)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 708, in process
    model_net = Script.load_control_model(p, unet, unit.model, unit.low_vram)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 265, in load_control_model
    model_net = Script.build_control_model(p, unet, model, lowvram)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 293, in build_control_model
    state_dict = load_state_dict(model_path)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 20, in load_state_dict
    torch.load(ckpt_path, map_location=torch.device(location))
  File "/content/stable-diffusion-webui/modules/safe.py", line 107, in load
    return load_with_extra(filename, *args, extra_handler=global_extra_handler, **kwargs)
  File "/content/stable-diffusion-webui/modules/safe.py", line 152, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: pickle data was truncated

  0% 0/13 [00:00<?, ?it/s]
  8% 1/13 [00:00<00:10,  1.19it/s]
 15% 2/13 [00:01<00:05,  1.89it/s]
 23% 3/13 [00:01<00:04,  2.33it/s]
 31% 4/13 [00:01<00:03,  2.59it/s]
 38% 5/13 [00:02<00:02,  2.79it/s]
 46% 6/13 [00:02<00:02,  2.90it/s]
 54% 7/13 [00:02<00:02,  3.00it/s]
 62% 8/13 [00:03<00:01,  3.06it/s]
 69% 9/13 [00:03<00:01,  3.11it/s]
 77% 10/13 [00:03<00:00,  3.14it/s]
 85% 11/13 [00:03<00:00,  3.17it/s]
 92% 12/13 [00:04<00:00,  3.15it/s]
100% 13/13 [00:04<00:00,  2.82it/s]

Total progress: 100% 13/13 [00:04<00:00,  2.69it/s]

**Comment by ayatake-art** [comment]
I am also getting the same error when using Deforum. The ControlNet version I'm using is v1.1.227. what should i do?

Reading ControlNet 1 base frame #0 at P:\data1\software\Stable Diffusion Web UI\stable-diffusion-webui\outputs/img2img-images\Deforum_20230625102250\controlnet_1_inputframes\000000000.jpg
2023-06-25 10:22:52,244 - ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: [].
Error running process: P:\data1\software\Stable Diffusion Web UI\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py
Traceback (most recent call last):
  File "P:\data1\software\Stable Diffusion Web UI\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
TypeError: Script.process() missing 21 required positional arguments: 'enabled', 'method', 'overwrite_size', 'keep_input_size', 'image_width', 'image_height', 'tile_width', 'tile_height', 'overlap', 'tile_batch_size', 'upscaler_name', 'scale_factor', 'noise_inverse', 'noise_inverse_steps', 'noise_inverse_retouch', 'noise_inverse_renoise_strength', 'noise_inverse_renoise_kernel', 'control_tensor_cpu', 'enable_bbox_control', 'draw_background', and 'causal_layers'

Error running process: P:\data1\software\Stable Diffusion Web UI\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\vae_optimize.py
Traceback (most recent call last):
  File "P:\data1\software\Stable Diffusion Web UI\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
TypeError: Script.process() missing 7 required positional arguments: 'enabled', 'encoder_tile_size', 'decoder_tile_size', 'vae_to_gpu', 'fast_decoder', 'fast_encoder', and 'color_fix'

Error running process: P:\data1\software\Stable Diffusion Web UI\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
Traceback (most recent call last):
  File "P:\data1\software\Stable Diffusion Web UI\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
TypeError: Script.process() missing 18 required positional arguments: 'is_enabled', 'is_combinatorial', 'combinatorial_batches', 'is_magic_prompt', 'is_feeling_lucky', 'is_attention_grabber', 'min_attention', 'max_attention', 'magic_prompt_length', 'magic_temp_value', 'use_fixed_seed', 'unlink_seed_from_prompt', 'disable_negative_prompt', 'enable_jinja_templates', 'no_image_generation', 'max_generations', 'magic_model', and 'magic_blocklist_regex'

2023-06-25 10:22:52,246 - ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: [].
100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [00:18<00:00,  1.36it/s]
Error running postprocess_batch: P:\data1\software\Stable Diffusion Web UI\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py
Traceback (most recent call last):
  File "P:\data1\software\Stable Diffusion Web UI\stable-diffusion-webui\modules\scripts.py", line 453, in postprocess_batch
    script.postprocess_batch(p, *script_args, images=images, **kwargs)
TypeError: Script.postprocess_batch() missing 1 required positional argument: 'enabled'

Error running postprocess: P:\data1\software\Stable Diffusion Web UI\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py
Traceback (most recent call last):
  File "P:\data1\software\Stable Diffusion Web UI\stable-diffusion-webui\modules\scripts.py", line 444, in postprocess
    script.postprocess(p, processed, *script_args)
TypeError: Script.postprocess() missing 1 required positional argument: 'enabled'

Error running postprocess: P:\data1\software\Stable Diffusion Web UI\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\vae_optimize.py
Traceback (most recent call last):
  File "P:\data1\software\Stable Diffusion Web UI\stable-diffusion-webui\modules\scripts.py", line 444, in postprocess
    script.postprocess(p, processed, *script_args)
TypeError: Script.postprocess() missing 1 required positional argument: 'enabled'

**Comment by huchenlei** [comment]
This is not the same error. ControlNet is not getting any input parameters at all.

 You can see all other scripts/extensions are complaining about not getting correct params. There is nothing we can do here to fix your problem. Try disable all extensions but ControlNet to see if the problem persists.

**Comment by ayatake-art** [comment]
thank you. I'll try it.

**Comment by roseyyy2022ai** [comment]
> Fixed in v1.1.227.

Nope. not fixed.....

I resolved the Unpickling error and started getting the warning again.

**Comment by syousip** [comment]
I am getting this error in deforum
![error](https://github.com/Mikubill/sd-webui-controlnet/assets/121361502/7e028af1-6c91-4131-8a91-9a27e5e23439)

I tried disabling all Int/Ext Extensions, restart UI with same error

**Comment by huchenlei** [comment]
@syousip Please submit a new issue as this issue is tracking the problem where there is ControlNetUnit passed to ControlNet but not recognized. 

From your logs, there is nothing passed to ControlNet.

**Comment by huchenlei** [comment]
If you see the warning after v1.4.0 A1111 update, please go to this thread:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/11448
