### ISSUE TITLE
What's the prompt of canny example?

### ISSUE THREAD

**Issue by marsplant** [Mikubill/sd-webui-controlnet#17]
Can you provide the prompts examples?

**Comment by marsplant** [comment]
I used the same canny model and prompts as yours, but failed to reproduce your anime-styled results.

![00001-4153881177](https://user-images.githubusercontent.com/78839542/218664770-ff5392fe-15d3-4aac-befa-d9be1963ee6f.png)

**Comment by marsplant** [comment]
I used the same canny model and prompts as yours, but failed to reproduce your anime-styled results.

![00002-1947041791](https://user-images.githubusercontent.com/78839542/218665069-a8acc22f-e0f8-44e9-b8bc-9a7480a4c405.png)

**Comment by Mikubill** [comment]
![Screenshot](https://user-images.githubusercontent.com/31246794/218666524-203d2e5e-11fd-4e0f-a018-e5d0d2e21591.png)
Works fine, note that different GPU or fp32/fp16 mode also influence the result

**Comment by marsplant** [comment]
thx! Did you use pastel-mix model here?
