### ISSUE TITLE
can someone help me with controlnet inpainting not outpainting?

### ISSUE THREAD

**Issue by keats9** [Mikubill/sd-webui-controlnet#1701]
I'm trying to extend an image. I turned on controlnet and inpainting, changed the width, clicked resize and fill and controlnet is more important, but the generated image is not related to my original image at all. I can't find the denoise section; seems to have disappeared on my UI. Help! Or is there another way to do outpainting?

Thanks!

**Comment by huchenlei** [comment]
Closing for insufficient context. Please feel free to file another issue with detailed reproduction steps.
