### ISSUE TITLE
[Bug]: 在deforum中使用controlNet时报错

### ISSUE THREAD

**Issue by goodboylll** [Mikubill/sd-webui-controlnet#1713]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Error running postprocess: F:\webUI\sd-webui-aki-v4\extensions\multidiffusion-upscaler-for-automatic1111\scripts\vae_optimize.py
Traceback (most recent call last):
  File "F:\webUI\sd-webui-aki-v4\modules\scripts.py", line 478, in postprocess
    script.postprocess(p, processed, *script_args)
TypeError: Script.postprocess() missing 1 required positional argument: 'enabled'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...
-

### What should have happened?

-

### Commit where the problem happens

webui: 
controlnet: 

### Command Line Arguments

```Shell
-
```

### List of enabled extensions

-

### Console logs

```Shell
-
```

**Comment by huchenlei** [comment]
Please fill all fields in the bug report template and attach the full stacktrace. Closing this issue for now. Feel free to open a new one with all necessary information attached. Also follow steps in #1153 first.
