### ISSUE TITLE
[Bug]: Run Preprocessor button doesn't work and Breaks WebUI

### ISSUE THREAD

**Issue by Vendaciousness** [Mikubill/sd-webui-controlnet#1715]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I tried to preview the pose of an image. The preview never loads and now my Automatic1111 WebUI is frozen and unable to process any other requests.

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/127359965/25b2eaf2-26bb-420e-84e6-71d7de135842)

### Steps to reproduce the problem

1. Go to Img2Img Tab
2. Enable ControlNet v1.1.227
3. Upload image
4. Select OpenPose model, openpose_faceonly preprocessor.
5. Enable MultiDiffusion Tiled VAE/Regional Prompt
6. Click on Run Preprocessor

Sorry I don't have time to enter all my setting again just to lose them. I've lost half the day as it is. Here are all my settings from the job, so maybe that'll help.
Prompt: trending on artstation, devientart, highly detailed by greg rutkowski
Steps: 45 | Sampler: DPM++ 2M Karras | CFG scale: 6.5 | Seed: 433283022 | Size: 2560x1440 | Model hash: c8094fea44 | Model: aZovyaRPGArtistTools_v3VAE | VAE: vae-ft-mse-840000-ema-pruned | Denoising strength: 0.94 | Clip skip: 1 | Version: b80fcca | Token merging ratio: 0.5 | Parser: Full parser | Tiled Diffusion upscaler: 4x_Nickelback_70000G | Tiled Diffusion scale factor: 2 | Tiled Diffusion: {"Method": "MultiDiffusion" | "Tile tile width": 96 | "Tile tile height": 96 | "Tile Overlap": 48 | "Tile batch size": 4 | "Upscaler": "4x_Nickelback_70000G" | "Upscale factor": 2 | "Keep input size": true | "Region control": {"Region 1": {"enable": true | "x": 0 | "y": 0.0609 | "w": 0.3825 | "h": 0.9756 | "prompt": "1 girl | lila | gorgeous female brunette hair about to kiss a man | sultry big lips | pouting | bright lighting | volumetric lighting | maximalist photo-illustration | 8k resolution concept art | intricately detailed | complex | elegant | expansive | fantastical | gloomy | misty | foggy | detailed hands | 8K UHD | ultra detailed | in the style of <lora:Lila_v1:0.6>\n" | "neg_prompt": "text | logo | watermark | ugly | duplicate | morbid | mutilated | out of frame | extra fingers | mutated hands | poorly drawn hands | poorly drawn face | mutation | deformed | blurry | bad anatomy | bad proportions | extra limbs | cloned face | extra limbs | gross proportions | malformed limbs | missing arms | missing legs | extra arms | extra legs | mutated hands | fused fingers | too many fingers | long neck | watermark | weird hand | weird finger | weird arm | mutation | blurry | bad anatomy | bad proportions | monochrome | signature | disfigured | jpeg artifacts | 3d max | grotesque | desaturated" | "blend_mode": "Foreground" | "feather_ratio": 0.4 | "seed": 1223586564} | "Region 2": {"enable": true | "x": 0.341 | "y": 0.0122 | "w": 0.2688 | "h": 1 | "prompt": "attractive male smiling | long dark hair green eyes | a-line haircut | shaved sides | style of by Jordan Grimmer and greg rutkowski | crisp lines and color <lora:M0le_v1:0.6> masterpiece | highest quality | (solo focus) | (perfect face:1. 1) | (high detail:1. 1) | (hyper detailed eyes) | dramatic | 1guy | (tan skin)\n" | "neg_prompt": "lowres | ((bad anatomy)) | ((bad hands)) | text | missing finger | extra digits | fewer digits | blurry | ((mutated hands and fingers)) | (poorly drawn face) | ((mutation)) | ((deformed face)) | (ugly) | ((bad proportions)) | ((extra limbs)) | extra face | (double head) | (extra head) | ((extra feet)) | monster | logo | cropped | (worst quality | low quality) | normal quality | jpeg | humpbacked | long body | long neck | ((jpeg artifacts)) | EasyNegative | multiple people | group of people | cartoon | 3d render" | "blend_mode": "Foreground" | "feather_ratio": 0.4 | "seed": 2703570049} | "Region 3": {"enable": true | "x": 0.6062 | "y": 0.0753 | "w": 0.6387 | "h": 1 | "prompt": "gorgeous female platinum blonde hair about to kiss a man | sultry big lips | pouting | bright lighting | volumetric lighting | maximalist photo-illustration | 8k resolution concept art | intricately detailed | complex | elegant | expansive | fantastical | gloomy | misty | foggy | detailed hands | 8K UHD | ultra detailed | in the style of marton bobzert <lora:Momo:0.3> <lora:Momo_v2:0.3>\n" | "neg_prompt": "text | logo | watermark | ugly | duplicate | morbid | mutilated | out of frame | extra fingers | mutated hands | poorly drawn hands | poorly drawn face | mutation | deformed | blurry | bad anatomy | bad proportions | extra limbs | cloned face | extra limbs | gross proportions | malformed limbs | missing arms | missing legs | extra arms | extra legs | mutated hands | fused fingers | too many fingers | long neck | watermark | weird hand | weird finger | weird arm | mutation | blurry | bad anatomy | bad proportions | monochrome | signature | disfigured | jpeg artifacts | 3d max | grotesque | desaturated" | "blend_mode": "Foreground" | "feather_ratio": 0.45 | "seed": 81477322} | "Region 4": {"enable": true | "x": 0 | "y": 0 | "w": 1 | "h": 1 | "prompt": "night sky | stars | nebulae | sacred geometry | trending on artstation | devientart | highly detailed by greg rutkowski" | "neg_prompt": "text | logo | watermark | ugly | duplicate" | "blend_mode": "Background" | "feather_ratio": 0.2 | "seed": 2988842845}}} | ControlNet 0: "preprocessor: openpose_hand | model: control_v11p_sd15_openpose [cab727d4] | weight: 1.1 | starting/ending: (0 | 1) | resize mode: Resize and Fill | pixel perfect: True | control mode: ControlNet is more important | preprocessor params: (512 | 100 | 200)" | ControlNet 1: "preprocessor: openpose_faceonly | model: control_v11p_sd15_openpose [cab727d4] | weight: 1.3 | starting/ending: (0 | 1) | resize mode: Resize and Fill | pixel perfect: True | control mode: ControlNet is more important | preprocessor params: (512 | 64 | 64)" | ControlNet 2: "preprocessor: canny | model: control_v11p_sd15_canny [d14c016b] | weight: 0.9 | starting/ending: (0 | 1) | resize mode: Resize and Fill | pixel perfect: True | control mode: Balanced | preprocessor params: (512 | 60 | 200)" | Lora hashes: "Momo: af83af87cc1b | Momo_v2: 53a3741e841c"

### What should have happened?

Worked

### Commit where the problem happens

webui: 
controlnet: 

### Command Line Arguments

```Shell
none
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/127359965/807d34ac-3183-4a2e-a3e5-c3c0b969b346)
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/127359965/f5b0faa0-98bd-48c0-b0b0-c327bd6f0a76)

### Console logs

```Shell
It's a full buffer, so I'll spare you the 50 pages of unrelated logs...

Here's where it went wrong.

10:21:57-859005 INFO     Preview Resolution = 720
10:29:18-840257 INFO     Preview Resolution = 720

That's me clicking Run on both ControlNet OpenPose modules.
```

**Comment by huchenlei** [comment]
Did you try press "Enter" in the command line window? Sometimes it can get stuck for unknown reasons (Probably caused by WebUI).

**Comment by Vendaciousness** [comment]
I'm sorry, I didn't. I'm not sure if it's any additional information, but the cursor was the square-shaped block and it was blinking.  Now I'm wondering if there were jobs I could've saved by hitting enter in the console window... lol
