### ISSUE TITLE
[Bug]: NaN Tensors when disabling ControlNet after use

### ISSUE THREAD

**Issue by Nyksia** [Mikubill/sd-webui-controlnet#1719]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

To start it off with, it is worth noting I'm using [anapnoe's](https://github.com/anapnoe/stable-diffusion-webui-ux) fork of WebUI.
Pretty consistently I've began having issues with ControlNet, where after using it and disabling it afterwards, my generations result in NaN tensors 100% of the time. If I enable ControlNet again, it doesn't result in NaN tensors.
The weirdest thing is that it is fixable with just swapping between models.

### Steps to reproduce the problem

1. Go to ControlNet
2. Generate anything using it
3. Disable it and try generating

### What should have happened?

It shouldn't result in consistent NaN tensors without it enabled.

### Commit where the problem happens

webui: [## 1.4.0](https://github.com/anapnoe/stable-diffusion-webui-ux/commit/3843d60ae7a692932db9be5ca33625382be32ee9)
controlnet: [8e143d35](https://github.com/Mikubill/sd-webui-controlnet/commit/8e143d3545140b8f0398dfbe1d95a0a766019283)

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
--upcast-sampling --xformers
```

### List of enabled extensions

<html>
<body>

Extension | URL | Branch | Version | Date | Update
-- | -- | -- | -- | -- | --
a1111-sd-webui-lycoris | https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris.git | main | 025dea96 | Wed Jun 14 13:56:41 2023 | unknown
a1111-sd-webui-tagcomplete | https://github.com/DominikDoom/a1111-sd-webui-tagcomplete.git | main | 7f188563 | Sun Jun 25 10:34:57 2023 | unknown
adetailer | https://github.com/Bing-su/adetailer.git | main | a1032d89 | Tue Jun 20 14:38:19 2023 | unknown
clip-interrogator-ext | https://github.com/pharmapsychotic/clip-interrogator-ext.git | main | 4d865c54 | Sun Jun 11 16:26:21 2023 | unknown
multidiffusion-upscaler-for-automatic1111 | https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111.git | main | de488810 | Sun Jun 18 21:39:44 2023 | unknown
sd-webui-ar | https://github.com/alemelis/sd-webui-ar.git | main | 9df49dc2 | Wed Apr 12 09:23:17 2023 | unknown
sd-webui-aspect-ratio-helper | https://github.com/thomasasfk/sd-webui-aspect-ratio-helper.git | main | 99fcf9b0 | Sun Jun 4 15:39:07 2023 | unknown
sd-webui-controlnet | https://github.com/Mikubill/sd-webui-controlnet.git | main | 8e143d35 | Sun Jun 25 04:45:53 2023 | unknown
sd-webui-infinite-image-browsing | https://github.com/zanllp/sd-webui-infinite-image-browsing.git | main | d560741f | Mon Jun 26 02:51:56 2023 | unknown
sd-webui-llul | https://github.com/hnmr293/sd-webui-llul.git | master | aa47b3ee | Thu May 4 16:14:34 2023 | unknown
sd-webui-model-converter | https://github.com/Akegarasu/sd-webui-model-converter.git | main | f6e0fa53 | Tue May 23 13:04:48 2023 | unknown
sd-webui-openpose-editor | https://github.com/huchenlei/sd-webui-openpose-editor.git | main | 0a87f8d0 | Wed Jun 21 03:21:17 2023 | unknown
sd-webui-regional-prompter | https://github.com/hako-mikan/sd-webui-regional-prompter.git | main | 5f0681ea | Sun Jun 25 16:08:26 2023 | unknown
sd-webui-supermerger | https://github.com/hako-mikan/sd-webui-supermerger.git | main | fc313940 | Sun Jun 25 05:14:28 2023 | unknown
stable-diffusion-webui-rembg | https://github.com/AUTOMATIC1111/stable-diffusion-webui-rembg.git | master | 3d9eedbb | Sun Jun 4 13:35:24 2023 | unknown
stable-diffusion-webui-state | https://github.com/ilian6806/stable-diffusion-webui-state.git | main | 85d8ef19 | Sat Jun 10 12:39:50 2023 | unknown
ultimate-upscale-for-automatic1111 | https://github.com/Coyote-A/ultimate-upscale-for-automatic1111.git | master | c99f382b | Tue Jun 13 04:29:35 2023 | unknown
LDSR | built-in | None |   | Tue Jun 27 18:19:20 2023 |  
Lora | built-in | None |   | Tue Jun 27 18:19:20 2023 |  
ScuNET | built-in | None |   | Tue Jun 27 18:19:20 2023 |  
SwinIR | built-in | None |   | Tue Jun 27 18:19:20 2023 |  
canvas-zoom-and-pan | built-in | None |   | Tue Jun 27 18:19:20 2023 |  
prompt-bracket-checker | built-in | None |   | Tue Jun 27 18:19:20 2023 |  
sd_theme_editor | built-in | None |   | Tue Jun 27 18:19:20 2023 |  

</body>
</html>

### Console logs

```Shell
venv "C:\Stable Diffusion\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: ## 1.4.0
Commit hash: 3843d60ae7a692932db9be5ca33625382be32ee9
Installing requirements






Launching Web UI with arguments: --upcast-sampling --xformers
[-] ADetailer initialized. version: 23.6.3, num models: 8
2023-06-27 21:33:36,931 - ControlNet - INFO - ControlNet v1.1.227
ControlNet preprocessor location: C:\Stable Diffusion\extensions\sd-webui-controlnet\annotator\downloads
2023-06-27 21:33:37,091 - ControlNet - INFO - ControlNet v1.1.227
Loading weights [6a7951c22d] from C:\Stable Diffusion\models\Stable-diffusion\Volatile Breaking Point v2.1.safetensors
Creating model from config: C:\Stable Diffusion\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: C:\Stable Diffusion\models\VAE\kl-f8-anime2.ckpt
Applying attention optimization: xformers... done.
Textual inversion embeddings loaded(15): aid28, aid291, bad-artist, bad-artist-anime, bad-hands-5, bad_prompt_version2, badv3, badv5, boring_e621, charturnerv2, deepnegative, deformityv6, easynegative, negative-hand, neutral_shylily
Model loaded in 6.5s (load weights from disk: 0.5s, create model: 1.1s, apply weights to model: 0.9s, apply half(): 0.8s, load VAE: 1.0s, move model to device: 1.8s, calculate empty prompt: 0.3s).

Thanks for being a Gradio user! If you have questions or feedback, please join our Discord server and chat with us: https://discord.gg/feTf9x3ZSB
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 21.1s (import torch: 4.0s, import gradio: 1.2s, import ldm: 0.5s, other imports: 1.4s, setup codeformer: 0.1s, load scripts: 5.9s, scripts before_ui_callback: 0.1s, create ui: 7.2s, gradio launch: 0.2s, app_started_callback: 0.4s).
preload_extensions_git_metadata for 24 extensions took 2.06s
2023-06-27 21:35:05,099 - ControlNet - INFO - Preview Resolution = 512
2023-06-27 21:35:13,115 - ControlNet - INFO - Preview Resolution = 512
2023-06-27 21:35:19,973 - ControlNet - INFO - Loading model: control_v11p_sd15_canny [d14c016b]
2023-06-27 21:35:23,054 - ControlNet - INFO - Loaded state_dict from [C:\Stable Diffusion\models\ControlNet\control_v11p_sd15_canny.pth]
2023-06-27 21:35:23,054 - ControlNet - INFO - Loading config: C:\Stable Diffusion\models\ControlNet\control_v11p_sd15_canny.yaml
2023-06-27 21:35:26,053 - ControlNet - INFO - ControlNet model control_v11p_sd15_canny [d14c016b] loaded.
2023-06-27 21:35:26,152 - ControlNet - INFO - Loading preprocessor: canny
2023-06-27 21:35:26,152 - ControlNet - INFO - preprocessor resolution = 512
100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:12<00:00,  3.90it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:20<00:00,  1.01s/it]
  0%|                                                                                           | 0/50 [00:00<?, ?it/s]
*** Error completing request
*** Arguments: ('task(9a2iu4cl4owcz2t)', '1girl', 'worst quality, bad quality, watermark, signature, text,', [], 50, 18, False, False, 1, 1, 11, -1.0, -1.0, 0, 0, 0, False, 512, 512, True, 0.6, 2, 'Latent (nearest)', 20, 0, 0, 0, '', '', [], 0, 0, 4, 512, 512, True, 'None', 'None', 0, 'None', False, False, 240, 10, 10, False, {'ad_model': 'face_yolov8n.pt', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'inpaint_global_harmonious', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1}, {'ad_model': 'None', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'inpaint_global_harmonious', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1}, False, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 4, 'None', 2, False, 10, 1, 1, 64, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 2048, 128, True, True, True, False, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001A635AEE620>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001A5062C2470>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001A61CA0FA60>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001A61CA0FC70>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001A61CB6F970>, False, 1, 0.15, False, 'OUT', ['OUT'], 5, 0, 'Bilinear', False, 'Bilinear', False, 'Lerp', '', '', False, False, None, True, False, False, 'Matrix', 'Horizontal', 'Mask', 'Prompt', '1,1', '0.2', False, False, False, 'Attention', False, '0', '0', '0.4', None, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, None, None, False, None, None, False, None, None, False, None, None, False, None, None, False, 50) {}
    Traceback (most recent call last):
      File "C:\Stable Diffusion\modules\call_queue.py", line 55, in f
        res = list(func(*args, **kwargs))
      File "C:\Stable Diffusion\modules\call_queue.py", line 35, in f
        res = func(*args, **kwargs)
      File "C:\Stable Diffusion\modules\txt2img.py", line 57, in txt2img
        processed = processing.process_images(p)
      File "C:\Stable Diffusion\modules\processing.py", line 620, in process_images
        res = process_images_inner(p)
      File "C:\Stable Diffusion\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "C:\Stable Diffusion\modules\processing.py", line 739, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "C:\Stable Diffusion\modules\processing.py", line 992, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "C:\Stable Diffusion\modules\sd_samplers_kdiffusion.py", line 433, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
      File "C:\Stable Diffusion\modules\sd_samplers_kdiffusion.py", line 275, in launch_sampling
        return func()
      File "C:\Stable Diffusion\modules\sd_samplers_kdiffusion.py", line 433, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
      File "C:\Stable Diffusion\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "C:\Stable Diffusion\repositories\k-diffusion\k_diffusion\sampling.py", line 626, in sample_dpmpp_2m_sde
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "C:\Stable Diffusion\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Stable Diffusion\modules\sd_samplers_kdiffusion.py", line 187, in forward
        devices.test_for_nans(x_out, "unet")
      File "C:\Stable Diffusion\modules\devices.py", line 158, in test_for_nans
        raise NansException(message)
    modules.devices.NansException: A tensor with all NaNs was produced in Unet. This could be either because there's not enough precision to represent the picture, or because your video card does not support half type. Try setting the "Upcast cross attention layer to float32" option in Settings > Stable Diffusion or using the --no-half commandline argument to fix this. Use --disable-nan-check commandline argument to disable this check.

---
```

**Comment by ramyma** [comment]
I'm facing a similar issue but with my custom interface that works over the API.
Interestingly if I generated an image in the A1111 webui and tried again in mine it works just fine.
I suppose it could be related to some missing cleanup in the API code?

**Comment by Nyksia** [comment]
I've actually toyed with it since more and tracked it down to happening specifically once I enable and then disable a ControlNet model. Sometimes it can be fixed by swapping to a different model and generating, then swapping back. If you don't generate, it'll still generate NaN tensors when switching back to the original model.
Still don't know if it is an extension conflict or an issue with that fork of WebUI though.

**Comment by clockworkwhale** [comment]
> Still don't know if it is an extension conflict or an issue with that fork of WebUI though.

This appears _not_ to be a fork problem. I'm using regular auto1111 and getting the same issue as you, where using and then disabling a ControlNet model causes the webui to continuously fail with NaN errors on generation until it's restarted.

**Comment by Nyksia** [comment]
Thank God I'm not the only one with the issue, others I've spoken to about on a Discord server didn't have the issue, so either it is an issue with the most recent version, or an extension conflict.

**Comment by ramyma** [comment]
I suspect it might be happening starting A1111 1.4 or with the newer torch version.
It started happening after updating both in my case.

**Comment by Nyksia** [comment]
> I suspect it might be happening starting A1111 1.4 or with the newer torch version. It started happening after updating both in my case. I also tried using an older commit of CN extension, but the issue was still happening, which I know it shouldn't be from before.

Definitely not a torch issue, since I haven't updated torch both when I didn't have and did start having the issue. So I'm betting on either a latest ControlNet update having some issues, or one of the extensions being used causing a conflict after it got updated.
Or it can even be that the updated ControlNet started conflicting with some extension. It'd be easier to tell if there were other people to compare extensions against.

**Comment by Nyksia** [comment]
**Tracked down the issue**, for me at least, down to cond cache under optimizations.
Having it enabled causes ControlNet to throw out NaN tensors when disabled.

**Comment by ramyma** [comment]
Well, I have `persistent cond cache` turned off already.

**Comment by Nyksia** [comment]
> Well, I have `persistent cond cache` turned off already.

There is a chance that your requirements are messed up, depending on how old your instance is. Could try wiping venv folder and letting it rebuild. I've had issues of that kind before.

**Comment by zero01101** [comment]
confirming NaN after disabling a previously-used controlnet using API in a clean webUI 1.4.0 install with controlnet 1.1.227 and just-picked-farm-fresh venv

- go to http://127.0.0.1:7860/docs#/default/text2imgapi_sdapi_v1_txt2img_post
- POST
``` 
{
	"batch_size": 1,
	"cfg_scale": 7,
	"enable_hr": false,
	"height": 512,
	"n_iter": 1,
	"negative_prompt": "test",
	"prompt": "test",
	"restore_faces": false,
	"sampler_index": "DDIM",
	"seed": "1",
	"steps": 25,
	"width": 512,
  "alwayson_scripts": {
    "controlnet": {
      "args": [
        {
          "input_image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABLSURBVDhPzcsxEoAgDEXB3P/SWmR1GDERO7Yj/xHHT5G8Fuz7Ibm1pMmtJU1uLenNuaYbWQqikaUgejC+UczsE3NDeHH9JF//QMQJZXnqJOtlq1sAAAAASUVORK5CYII=",
          "model": "control_v11f1p_sd15_depth [cfd03158]",
          "module": "depth_midas"
        }
      ]
    }
  }
}
```
- receive expected base64 image output
- remove `alwayson_scripts` element (and children of course) from POST body
- POST updated body again and receive 
```
*** API error: POST: http://127.0.0.1:7860/sdapi/v1/txt2img {'error': 'NansException', 'detail': '', 'body': '', 'errors': "A tensor with all NaNs was produced in VAE. This could be because there's not enough precision to represent the picture. Try adding --no-half-vae commandline argument to fix this. Use --disable-nan-check commandline argument to disable this check."}
    Traceback (most recent call last):
      File "E:\storage\webui-clean-2\venv\lib\site-packages\anyio\streams\memory.py", line 94, in receive
        return self.receive_nowait()
      File "E:\storage\webui-clean-2\venv\lib\site-packages\anyio\streams\memory.py", line 89, in receive_nowait
        raise WouldBlock
    anyio.WouldBlock

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "E:\storage\webui-clean-2\venv\lib\site-packages\starlette\middleware\base.py", line 78, in call_next
        message = await recv_stream.receive()
      File "E:\storage\webui-clean-2\venv\lib\site-packages\anyio\streams\memory.py", line 114, in receive
        raise EndOfStream
    anyio.EndOfStream

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "E:\storage\webui-clean-2\modules\api\api.py", line 153, in exception_handling
        return await call_next(request)
      File "E:\storage\webui-clean-2\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
        raise app_exc
      File "E:\storage\webui-clean-2\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "E:\storage\webui-clean-2\venv\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
        response = await self.dispatch_func(request, call_next)
      File "E:\storage\webui-clean-2\modules\api\api.py", line 117, in log_and_time
        res: Response = await call_next(req)
      File "E:\storage\webui-clean-2\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
        raise app_exc
      File "E:\storage\webui-clean-2\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "E:\storage\webui-clean-2\venv\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
        await self.simple_response(scope, receive, send, request_headers=headers)
      File "E:\storage\webui-clean-2\venv\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
        await self.app(scope, receive, send)
      File "E:\storage\webui-clean-2\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
        await responder(scope, receive, send)
      File "E:\storage\webui-clean-2\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
        await self.app(scope, receive, self.send_with_gzip)
      File "E:\storage\webui-clean-2\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
        raise exc
      File "E:\storage\webui-clean-2\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
        await self.app(scope, receive, sender)
      File "E:\storage\webui-clean-2\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
        raise e
      File "E:\storage\webui-clean-2\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
        await self.app(scope, receive, send)
      File "E:\storage\webui-clean-2\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
        await route.handle(scope, receive, send)
      File "E:\storage\webui-clean-2\venv\lib\site-packages\starlette\routing.py", line 276, in handle
        await self.app(scope, receive, send)
      File "E:\storage\webui-clean-2\venv\lib\site-packages\starlette\routing.py", line 66, in app
        response = await func(request)
      File "E:\storage\webui-clean-2\venv\lib\site-packages\fastapi\routing.py", line 237, in app
        raw_response = await run_endpoint_function(
      File "E:\storage\webui-clean-2\venv\lib\site-packages\fastapi\routing.py", line 165, in run_endpoint_function
        return await run_in_threadpool(dependant.call, **values)
      File "E:\storage\webui-clean-2\venv\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
        return await anyio.to_thread.run_sync(func, *args)
      File "E:\storage\webui-clean-2\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
        return await get_asynclib().run_sync_in_worker_thread(
      File "E:\storage\webui-clean-2\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
        return await future
      File "E:\storage\webui-clean-2\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
        result = context.run(func, *args)
      File "E:\storage\webui-clean-2\modules\api\api.py", line 338, in text2imgapi
        processed = process_images(p)
      File "E:\storage\webui-clean-2\modules\processing.py", line 620, in process_images
        res = process_images_inner(p)
      File "E:\storage\webui-clean-2\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "E:\storage\webui-clean-2\modules\processing.py", line 743, in process_images_inner
        devices.test_for_nans(x, "vae")
      File "E:\storage\webui-clean-2\modules\devices.py", line 158, in test_for_nans
        raise NansException(message)
    modules.devices.NansException: A tensor with all NaNs was produced in VAE. This could be because there's not enough precision to represent the picture. Try adding --no-half-vae commandline argument to fix this. Use --disable-nan-check commandline argument to disable this check.
```

mighty comical of the universe to hit me with that the one day i come back to try and do something useful lmao

**Comment by Nyksia** [comment]
@zero01101 Would you say the issue persists if you swap to a different SD model and generate with it? Because if not, maybe it has similar root issue as what I had because of cond cache, which is as name suggests a caching issue, probably not getting cleaned out properly if I were to guess without knowing the inner workings of it?

**Comment by ramyma** [comment]
In my case changing the SD model clears the issue. But I can confirm that enabling CN and generating via API stops subsequent generations with CN disabled without changing the model, even on A1111 main webui itself.

**Comment by ramyma** [comment]
Found the culprit:
https://github.com/Mikubill/sd-webui-controlnet/commit/fe803c70663b019d11943a9f664e194c5412c7ae#diff-86d1966226c5d294b3ed140211dcc872a2e27312f5f9b88c454e4717ef96f596R898
When I reverted this line the issue disappeared.

**Comment by zero01101** [comment]
> Would you say the issue persists if you swap to a different SD model and generate with it?

in fact i cannot; switching to a different checkpoint does seem to alleviate the issue, until controlnet is invoked and then disabled (via removing `alwayson_scripts` body element) again.  

> But I can confirm that enabling CN and generating via API stops subsequent generations with CN disabled without changing the model, even on A1111 main webui itself.

ironically, it works perfectly fine in webUI; i can enable/disable/re-enable controlnet all day without issue... i can even leave controlnet enabled in webUI after having generated an image, then request txt2img over API _without_ the `alwayson_scripts`  key, and it'll generate no problem. 

so far, i can only reliably reproduce this over solely API means, even after trying specifically to enable CN over API and then generate without CN in webUI with the same model like @ramyma

**Comment by Nyksia** [comment]
>yknow what's interesting though, is i just tried switching to a different checkpoint, did not generate anything, then switched back to the one i was using when i raised the NaN error, and the error occurred....
@zero01101 That's the behavior I've had when I had persistent cond cache enabled. So honestly it looks like both issues, API included, suffers from cache not being cleared properly? At least considering that's what the issue with cond cache was, and this issue seems similar in nature, it looks very likely that API is missing the crucial clean-up.
Reason why changing a model _and_ generating with it alleviates the issue, in my guess, is because the cache gets populated by the model, replacing the broken cache from ControlNet. So that's why swapping a model and not generating doesn't fix it.

**Comment by ramyma** [comment]
I went through the commits on A1111 since v1.4 and I found that the issue started happening starting from this commit:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/7f2214aa2b9a88bc1631f3f1d164a75a3583c851

**Comment by ramyma** [comment]
I created a PR for A1111 to fix the issue.
@zero01101 would you verify that it fixes the issue on your end as well?

**Comment by zero01101** [comment]
> I created a PR for A1111 to fix the issue. @zero01101 would you verify that it fixes the issue on your end as well?

limited testing so far, but it sure appears to do so! :D
