### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Heyzzenberg** [Mikubill/sd-webui-controlnet#1720]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When working with the controlnet, this error appears
<img width="938" alt="Снимок экрана 2023-06-27 230002" src="https://github.com/Mikubill/sd-webui-controlnet/assets/137943890/d9fc1df1-6f75-48aa-a2d6-b0072ae32f95">
<img width="845" alt="Снимок экрана 2023-06-27 230111" src="https://github.com/Mikubill/sd-webui-controlnet/assets/137943890/ba72ceda-d4e8-43f5-9fb8-f23ca84eceba">

### Steps to reproduce the problem

1. Go to .... promt generation
2. Press ....controlnet
3. ...

### What should have happened?

the controlnet should work

### Commit where the problem happens

controlnet: 

### Command Line Arguments

```Shell
yandex
```

### List of enabled extensions

no

### Console logs

```Shell
-
```

**Comment by huchenlei** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/11448

**Comment by Heyzzenberg** [comment]
This solution does not help. Explain exactly what to do

**Comment by Heyzzenberg** [comment]
What you wrote has nothing to do with controlnet. I updated the version to 1.1227 and now controlnet is not working for me

**Comment by huchenlei** [comment]
I cannot help as you did not provide the full context. In the stack trace another extension's script is throwing error but you said no other extension is installed. You also did not specify a1111 version you are using so I assume you just updated to 1.4.0.
