### ISSUE TITLE
[Bug]: HELP !!! Controlnet stopped working

### ISSUE THREAD

**Issue by DavidSchobl** [Mikubill/sd-webui-controlnet#1721]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

After latest update of webui and xformers, controlnet has stopped working - it is in webui, everything can be set, but while I start generating image - controlnet is not loading anything and image is being rendered only from prompt. there are no errors in console. It just does nothing.

### Steps to reproduce the problem

Update webui and xformers to 0.20

### What should have happened?

It should work

### Commit where the problem happens

webui: version: [v1.4.0]
•  python: 3.10.6 
•  torch: 2.0.1+cu118 
•  xformers: 0.0.20 
•  gradio: 3.32.0  
controlnet: v1.1.224

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--api --theme=dark --listen --xformers --enable-insecure-extension-access --medvram --no-half-vae
```

### List of enabled extensions

ImageReward	
SD-CN-Animation	
auto-sd-paint-ext	
infinite-zoom-automatic1111-webui	
openOutpaint-webUI-extension	
openpose-editor	
sd-webui-3d-open-pose-editor	
sd-webui-controlnet	
sd-webui-infinite-image-browsing	
sdweb-merge-board	
stable-diffusion-webui-images-browser	
LDSR	
Lora	
ScuNET
SwinIR	
canvas-zoom-and-pan	
extra-options-section	
prompt-bracket-checker

### Console logs

```Shell
Already up to date.
venv "H:\AI\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.4.0
Commit hash: 394ffa7b0a7fff3ec484bcd084e673a8b301ccc8
Installing requirements
Installing requirements 1 for Infinite-Zoom


Installing SD-CN-Animation requirement: scikit-image





Launching Web UI with arguments: --api --theme=dark --listen --xformers --enable-insecure-extension-access --medvram --no-half-vae
2023-06-27 22:41:09,705 - ControlNet - INFO - ControlNet v1.1.224
ControlNet preprocessor location: H:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-06-27 22:41:09,965 - ControlNet - INFO - ControlNet v1.1.224
Loading weights [fd28fd1df4] from H:\AI\stable-diffusion-webui\models\Stable-diffusion\Artisanica_V1.safetensors
Creating model from config: H:\AI\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
preload_extensions_git_metadata for 18 extensions took 3.78s
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 23.4s (import torch: 2.7s, import gradio: 2.1s, import ldm: 1.1s, other imports: 2.0s, opts onchange: 0.9s, setup codeformer: 0.2s, list SD models: 0.3s, load scripts: 3.7s, create ui: 4.9s, gradio launch: 5.4s, add APIs: 0.2s).
Loading VAE weights specified in settings: H:\AI\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt
Applying attention optimization: xformers... done.
Textual inversion embeddings loaded(0):
Model loaded in 23.7s (load weights from disk: 2.4s, create model: 0.8s, apply weights to model: 17.8s, apply half(): 1.1s, load VAE: 1.1s, calculate empty prompt: 0.4s).
100%|███████████████████████████████████████████████████████████████████████████████| 20/20 [00:42<00:00,  2.15s/it]
Total progress: 100%|███████████████████████████████████████████████████████████████| 20/20 [00:46<00:00,  2.31s/it]
Total progress: 100%|███████████████████████████████████████████████████████████████| 20/20 [00:46<00:00,  2.03s/it]
```

**Comment by DavidSchobl** [comment]
> update to the latest commit [8e143d3](https://github.com/Mikubill/sd-webui-controlnet/commit/8e143d3545140b8f0398dfbe1d95a0a766019283)

Thank you for the answer! Webui says my CN is up to date - but the commit you showed is definitely newer. how to manually update? Sorry for noob question.

**Comment by calufa** [comment]
@DavidSchobl did it work for you? I tried updating to the latest commit, but no luck, the web UI keeps ignoring the controlnet settings.

**Comment by DavidSchobl** [comment]
> @DavidSchobl did it work for you? I tried updating to the latest commit, but no luck, the web UI keeps ignoring the controlnet settings.

Nope, update did not work. I had to update it manualy by git pull, because webui did not recognize newest update. **BUT I FOUND SOLUTION!!!** The reason why this extensiom did not work was because of conflict with another extension - SD-CN-Animation most probably. I have disabled all other extensions and it started to work. So my advice is, disable all but CN, test if it works and start to activate another extensions one by one. Another extension that seems to be corrupted by SDCNA is roop as it is in the same part of webui, I suspect that SDCNA is probably corrupting webui somehow.

**Comment by DanielSHKao** [comment]
Same issue here. The CN is still ignored even if I disabled all other extensions.

**Comment by DavidSchobl** [comment]
> Same issue here. The CN is still ignored even if I disabled all other extensions.

Try going into the extensions/controlnet folder, then open cmd and use: git pull.

Disable all other extensions (especially sd-cn-animation).

Do the same in the main directory of webui, run "git pull".

Disable controlnet in the webui. Restart webui, Enable CN, restart. This helped me, since then this issue dissapeared and I am not running sd-cn-animation.

**Comment by cycleogist** [comment]
any solution yet guy, in my case Controlnet is rendering well but its not reflecting on the image generated
