### ISSUE TITLE
[Feature] Mask influence per tab

### ISSUE THREAD

**Issue by aarongerber** [Mikubill/sd-webui-controlnet#1732]
I know this can be done in inpaint, but it’s hacky. Ideally you could open a section on a controlnet tab and it would show you the currently generated image, and you could inpaint where the effects of the controlnet would show up. Basically reproduce all inpain behavior on each Controlnet tab so that you could for instance only apply the canny to the face and hands, etc.

**Comment by huchenlei** [comment]
See discussion here:
https://github.com/Mikubill/sd-webui-controlnet/issues/1638

**Comment by aarongerber** [comment]
Sorry I didn’t initially think that ticket  was related, after rereading it I finally see how it relates.
