### ISSUE TITLE
[Bug]: Multi ControlNet tabs do not appear (solved)

### ISSUE THREAD

**Issue by epictetito** [Mikubill/sd-webui-controlnet#1734]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

In settings, "Multi ControlNet: Max models amount (requires restart)" I have the slider 
![cap](https://github.com/Mikubill/sd-webui-controlnet/assets/82149386/bc58853b-5ef8-48a4-8031-c77a9aa4d4cc)
3 by default, but no unit tab appears. I have tried with 2 or 4, restarted UI but still no units tab and the slider is back to 3.

Debian 12. 
ControlNet v1.1.227

### Steps to reproduce the problem

1. Go to .... Settings, Multi ControlNet: Max models amount (requires restart)
2. Press .... Slider to 2,3,4 ....  anyone
3. Reload UI
4. tabs do not appear
![cap](https://github.com/Mikubill/sd-webui-controlnet/assets/82149386/6f117813-efa9-4a7c-ac74-759890152560)
![cap2](https://github.com/Mikubill/sd-webui-controlnet/assets/82149386/de0c06e3-a6fb-43ec-a3d7-f21feb187941)

### What should have happened?

when you select several tabs in settings and start UI, the number of selected tabs should be displayed on the control panel

### Commit where the problem happens

webui: version: v1.4.0
controlnet: v1.1.227

### What browsers do you use to access the UI ?

Brave

### Command Line Arguments

```Shell
no
```

### List of enabled extensions

adetailer 
canvas-zoom 
sd-webui-ar 
sd-webui-controlnet
sd-webui-regional-prompter11
sd-webui-roop 
stable-diffusion-webui-two-shot 
LDSR 
Lora
ScuNET 
SwinIR
canvas-zoom-and-pan
extra-options-section | built-in | None |   | Thu Jun 29 20:38:55 2023 |  
prompt-bracket-checker

### Console logs

```Shell
Restarting UI...
Closing server running on port: 7860
[-] ADetailer initialized. version: 23.6.4, num models: 8
2023-06-29 22:38:52,370 - ControlNet - INFO - ControlNet v1.1.227
2023-06-29 22:38:52,385 - roop - INFO - roop v0.0.2

Thanks for being a Gradio user! If you have questions or feedback, please join our Discord server and chat with us: https://discord.gg/feTf9x3ZSB
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 1.7s (load scripts: 1.4s, create ui: 0.2s).
preload_extensions_git_metadata for 14 extensions took 0.16s
Restarting UI...
Closing server running on port: 7860
[-] ADetailer initialized. version: 23.6.4, num models: 8
2023-06-29 22:48:08,663 - ControlNet - INFO - ControlNet v1.1.227
2023-06-29 22:48:08,678 - roop - INFO - roop v0.0.2
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 1.8s (load scripts: 1.5s, create ui: 0.2s).
preload_extensions_git_metadata for 14 extensions took 0.16s
```

**Comment by wangxihao** [comment]
May I ask how to solve it, I also encountered this problem,thank you!

**Comment by NuarkNoir** [comment]
> May I ask how to solve it, I also encountered this problem,thank you!

Okay, for me it was ControlNet section in setting, with default "Multi ControlNet: Max models amount" equal to 3 I had no tabs in UI, but increasing it to 5 (and restarting) revealed all 5 sub-tabs in ControlNet

**Comment by wangxihao** [comment]
> 

3Q!
