### ISSUE TITLE
[Bug]: two same attribute at func  "parse_remote_call" in controlnet.py

### ISSUE THREAD

**Issue by steffenchen** [Mikubill/sd-webui-controlnet#1740]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

In  the function "parse_remote_call" of script in controlnet.py, there are two "unit.guidance_end" inside but refer to two different params. of the UI...I think it is a mistake???

### Steps to reproduce the problem

controlnet.py -> line 424 line 425

### What should have happened?

I am not sure what is the consequence of this issuse.

### Commit where the problem happens

webui: 
controlnet: 

### Command Line Arguments

```Shell
no
```

### List of enabled extensions

noly controlnet

### Console logs

```Shell
no
```

**Comment by ljleb** [comment]
It is not a mistake. the mapping of guidance to guidance_end is for backwards compatibility.

**Comment by huchenlei** [comment]
> It is not a mistake. the mapping of guidance to guidance_end is for backwards compatibility.

Maybe we should leave a comment there so people don't get confused when reading it?

**Comment by ljleb** [comment]
Sure, why not.
