### ISSUE TITLE
[Bug]: Only generates noise after disable ControlNet

### ISSUE THREAD

**Issue by Morgens7ern** [Mikubill/sd-webui-controlnet#1746]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I found a bug when i disable ControlNet, it generates only noise, and i have to load another checkpoint to fix it.

I can generate normal, as long i dont disable CN.
If i try using ADetailer, the image generated is just noise

Example with just "woman" in promp, default settings
*Canny is just for testing, no matter which model i use, the bug happens if i disable CN*
*the ADetailer image is before disable CN*
![New Project](https://github.com/Mikubill/sd-webui-controlnet/assets/79327382/2f4f99f7-4cda-4713-849e-f628f1bdc41e)

After it happens, i have to load another checkpoint to fix. But if i use CN and disable, it happens again

### Steps to reproduce the problem

1. Gererate something without CN
2. Enable CN with any model and generate **(you have to generate something)**
3. Disable CN and try generate again, will generate just noise
4. Load another checkpoint and try generate, will generate normal

### What should have happened?

When disable CN, it should generate normal

### Commit where the problem happens

webui: AUTOMATIC1111 v1.4.0
controlnet: v1.1.227 [2785cbe6](https://github.com/Mikubill/sd-webui-controlnet/commit/2785cbe61a61c137d4e980752771f6329b03612a)

version: [v1.4.0]  •  python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.32.0  •  checkpoint: [9aba26abdf]

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
set COMMANDLINE_ARGS= --xformers --medvram --no-half --update-check
```

### List of enabled extensions

![msedge_8w8wULAJsH](https://github.com/Mikubill/sd-webui-controlnet/assets/79327382/a21b49f8-904a-4011-a18f-44fd350971f8)

### Console logs

```Shell
Already up to date.
venv "D:\SOFTWARES\stable-diffusion-webui-master\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.4.0
Commit hash: 394ffa7b0a7fff3ec484bcd084e673a8b301ccc8
Installing requirements



Installing requirements 1 for Infinite-Zoom






#######################################################################################################
Initializing Civitai Link
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Civitai Link revision: 2dfc03c17304278ca0b456366cc7871a2af8377b
SD-WebUI revision: 394ffa7b0a7fff3ec484bcd084e673a8b301ccc8

Checking Civitai Link requirements...
[!] python-socketio[client] version 5.7.2 NOT installed.

#######################################################################################################

You are up to date with the most recent release.
Launching Web UI with arguments: --xformers --medvram --no-half --update-check
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: D:\SOFTWARES\stable-diffusion-webui-master\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
Civitai Helper: No setting file, use default
[-] ADetailer initialized. version: 23.7.1, num models: 8
2023-07-02 15:55:05,815 - ControlNet - INFO - ControlNet v1.1.227
ControlNet preprocessor location: D:\SOFTWARES\stable-diffusion-webui-master\extensions\sd-webui-controlnet\annotator\downloads
2023-07-02 15:55:05,917 - ControlNet - INFO - ControlNet v1.1.227
Civitai: API loaded
Loading weights [9aba26abdf] from D:\SOFTWARES\stable-diffusion-webui-master\models\Stable-diffusion\deliberate_v2.safetensors
Creating model from config: D:\SOFTWARES\stable-diffusion-webui-master\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
*Deforum ControlNet support: enabled*
Applying attention optimization: xformers... done.
Textual inversion embeddings loaded(18): bad-artist, bad-artist-anime, bad-hands-5, bad_prompt_version2, BadDream, CyberRealistic_Negative, easynegative, epiCNegative, epiCRealism, FastNegativeV2, flame_surge_style, negative-deliberate, negative_hand, ng_deepnegative_v1_75t, style-swirlmagic, UnrealisticDream, verybadimagenegative_v1.3, vmpr
Model loaded in 2.7s (load weights from disk: 0.8s, create model: 0.8s, apply weights to model: 0.5s, calculate empty prompt: 0.4s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Civitai: Check resources for missing preview images
Startup time: 14.4s (import torch: 1.9s, import gradio: 1.0s, import ldm: 0.6s, other imports: 1.0s, list SD models: 0.1s, load scripts: 6.1s, create ui: 3.1s, gradio launch: 0.2s).
Civitai: Found 0 resources missing preview images
Civitai: No preview images found on Civitai
preload_extensions_git_metadata for 29 extensions took 2.09s
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:20<00:00,  1.02s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:26<00:00,  1.31s/it]
2023-07-02 15:57:11,434 - ControlNet - INFO - Loading model: control_v11p_sd15_canny [d14c016b][00:26<00:00,  1.26it/s]
2023-07-02 15:57:11,819 - ControlNet - INFO - Loaded state_dict from [D:\SOFTWARES\stable-diffusion-webui-master\extensions\sd-webui-controlnet\models\control_v11p_sd15_canny.pth]
2023-07-02 15:57:11,819 - ControlNet - INFO - Loading config: D:\SOFTWARES\stable-diffusion-webui-master\extensions\sd-webui-controlnet\models\control_v11p_sd15_canny.yaml
2023-07-02 15:57:14,209 - ControlNet - INFO - ControlNet model control_v11p_sd15_canny [d14c016b] loaded.
2023-07-02 15:57:14,299 - ControlNet - INFO - Loading preprocessor: canny
2023-07-02 15:57:14,299 - ControlNet - INFO - preprocessor resolution = 512
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:45<00:00,  2.27s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:44<00:00,  2.22s/it]
2023-07-02 15:58:15,536 - ControlNet - INFO - Loading model from cache: control_v11p_sd15_canny [d14c016b]0,  2.22s/it]
2023-07-02 15:58:15,537 - ControlNet - INFO - Loading preprocessor: canny
2023-07-02 15:58:15,537 - ControlNet - INFO - preprocessor resolution = 512
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:46<00:00,  2.32s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:42<00:00,  2.26s/it]
0: 640x640 1 face, 103.0ms
Speed: 4.0ms preprocess, 103.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:16<00:00,  1.19it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [01:05<00:00,  3.28s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:16<00:00,  1.19it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:17<00:00,  1.17it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:17<00:00,  1.25it/s]
```

### Additional information

My GPU : GTX 1660 super
Driver: 531.79 (downgraded)

**Comment by dermesut** [comment]
"I found a bug when i disable ControlNet, it generates only noise, and i have to load another checkpoint to fix it."

the same is true for me.
but only if i use the api. when using the webinterface, everything works as expected.

additionally:
i can not only fix it by loading another checkpoint, i can also "fix" it by activating, say, a lora.

here are some steps that produce repeating behaviour, when using via api:
1. generate image without cn -> normal image
2. enable cn, generate -> normal image with cn-influence
3. disable cn, generate -> noise
4. enable cn, generate -> normal image with cn-influence
5. disable cn, enable lora, generate -> normal image with lora influence
6. enable cn, enable lora, generate -> normal image with cn-influence & lora influence
7. enable cn, disable lora, generate -> normal image with cn-influence
8. disable cn, disable lora, generate -> noise
9. disable cn, enable lora, generate -> normal image with lora influence
10.  disable cn, disable lora, generate -> normal image

**Comment by hsz1273327** [comment]
the same

**Comment by dermesut** [comment]
> 10\. disable cn, disable lora, generate -> normal image

i updated the a1111 installation to the latest version and now the problem is gone.

**Comment by Morgens7ern** [comment]
I'm still having this bug, but now i can use Adetailer.

But whenever i disable CN, it generates noise.
![New Project](https://github.com/Mikubill/sd-webui-controlnet/assets/79327382/b1b5e241-01f9-4bda-8f27-84f59711ad38)

To generate without CN, i have to load another checkpoint, generate something and go back to the model i was using.
