### ISSUE TITLE
cv2 error[Bug]: 

### ISSUE THREAD

**Issue by xxtyy** [Mikubill/sd-webui-controlnet#1751]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

`from base64 import b64encode
import io
import cv2
import base64
import requests
from PIL import Image

def readImage(path):
    img = cv2.imread(path)
    retval, buffer = cv2.imencode('.jpg', img)
    b64img = b64encode(buffer).decode("utf-8")
    return b64img

b64img = readImage("/home/xiao/Downloads/demo.jpeg")
url = "http://localhost:7861/sdapi/v1/img2img"

body = {
    "init_images": [b64img],
    "resize_mode": 0,
    "denoising_strength": 0.75,
    "prompt": "Comic book style,(best quality, masterpiece), comic,line,be gounger,long long sleeves, blue shirt, red cape, skirt , belt ,thighhigh, fit female,<lora:supergirl:1>supergirl,Super hero,",
    "negative_prompt": "Unspeakable-Horrors-Composition-4v, bad_prompt_version2, ng_deepnegative_v1_75t, verybadimagenegative_v1.2-6400, easynegative, NEG_FACELIFT512, badhandv4, (worst quality:1.4, low quality:1.4), censorship, censor bars, missing fingers, (extra fingers), fewer digits, extra body parts, bad anatomy, censored, logo, child, loli, tattoo, pens, disfigured hands, hat with multiple points, multiple pages, multiple books, table, deformed body, detached penis, deformed penis, extra breasts <lora:soulcard:1.3> (SOUL CARD:1.2) LINE , ADetailer negative prompt: Unspeakable-Horrors-Composition-4v, bad_prompt_version2, ng_deepnegative_v1_75t, verybadimagenegative_v1.2-6400, easynegative, NEG_FACELIFT512, badhandv4, (worst quality:1.4, low quality:1.4), censorship, censor bars, mosaic, logo, signature, missing fingers, (extra fingers), fewer digits, extra body parts, bad anatomy, censored, collage, logo, border, child, loli, tattoo, multiple pages, table, pens, deformed hands, ADetailer conf: 30, ADetailer dilate/erode: 32, ADetailer mask blur: 4, ADetailer denoising strength: 0.4, ADetailer inpaint full: True, ADetailer inpaint padding: 0, ADetailer model 2nd: face_yolov8s.pt, ADetailer negative prompt 2nd: Unspeakable-Horrors-Composition-4v, bad_prompt_version2, ng_deepnegative_v1_75t, verybadimagenegative_v1.2-6400, easynegative, NEG_FACELIFT512, badhandv4, (worst quality:1.4, low quality:1.4), censorship, censor bars, mosaic, logo, signature, missing fingers, (extra fingers), fewer digits, extra body parts, bad anatomy, censored, collage, logo, border, child, loli, tattoo, multiple pages, table, pens, deformed hands, ADetailer conf 2nd: 30, ADetailer dilate/erode 2nd: 32, ADetailer mask blur 2nd: 4, ADetailer denoising strength 2nd: 0.4, ADetailer inpaint full 2nd: True, ADetailer inpaint padding 2nd: 0, ADetailer version: 23.5.14, Hires upscale: 1.25, Hires steps: 20, Hires upscaler: 4x_foolhardy_Remacri",
    "seed": -1,
    "sampler_name": "Euler a",
    "sampler_index": "Euler a",
    "batch_size": 1,
    "steps": 20,
    "cfg_scale": 7,
    "width": 512,
    "height": 512,
    "restore_faces": False,
    "tiling": False,
    "alwayson_scripts": {
        "controlnet": {
            "args": [
                {
                    "enabled": True,
                    "input_image": b64img,
                    "module": "normal_bae",
                    "model": "control_v11p_sd15_normalbae [316696f1]"
                }
            ]
        }
    }
}

r = requests.post(url, json=body)
response = r.json()
result = response['images'][0]
image = Image.open(io.BytesIO(base64.b64decode(result.split(",", 1)[0])))
image.save('output.png')
image.show()`

### Steps to reproduce the problem

The picture should be generated normally when calling the API

### What should have happened?

generate image

### Commit where the problem happens

webui: 
controlnet: 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
no
```

### List of enabled extensions

api_only（）

### Console logs

```Shell
*** Error running process: /home/xiao/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "/home/xiao/stable-diffusion-webui/modules/scripts.py", line 474, in process
        script.process(p, *script_args)
      File "/home/xiao/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 829, in process
        detected_map, is_image = preprocessor(
      File "/home/xiao/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 76, in decorated_func
        return cached_func(*args, **kwargs)
      File "/home/xiao/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 64, in cached_func
        return func(*args, **kwargs)
      File "/home/xiao/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 35, in unified_preprocessor
        return preprocessor_modules[preprocessor_name](*args, **kwargs)
      File "/home/xiao/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 531, in normal_bae
        img, remove_pad = resize_image_with_pad(img, res)
      File "/home/xiao/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 27, in resize_image_with_pad
        img = cv2.resize(img, (W_target, H_target), interpolation=interpolation)
    cv2.error: OpenCV(4.8.0) /io/opencv/modules/imgproc/src/resize.cpp:4065: error: (-215:Assertion failed) inv_scale_x > 0 in function 'resize'
```

**Comment by yes123qq** [comment]
Hi~ Do you have any progress on this issue?

**Comment by demenech** [comment]
Hey. I was having this error due to the name of the model being wrong. Double-check this.

**Comment by AuYuHui** [comment]
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/38815121/db88c639-a7b4-433c-9748-f6ae828ec528)

I have the same problem.

What should I do


```
alwayson_scripts: {
      controlnet: {
        args: [
          {
            enabled: true,
            input_image: encoded_image,
            module: 'pidinet_sketch',
            model: 't2iadapter_sketch_sd15v2 [f5789421]',
          },
        ],
      },
    },
```

**Comment by Linket-LYF** [comment]
> ![图像](https://user-images.githubusercontent.com/38815121/254492577-db88c639-a7b4-433c-9748-f6ae828ec528.png)
> 
> 我有同样的问题。
> 
> 我该怎么办
> 
> ```
> alwayson_scripts: {
>       controlnet: {
>         args: [
>           {
>             enabled: true,
>             input_image: encoded_image,
>             module: 'pidinet_sketch',
>             model: 't2iadapter_sketch_sd15v2 [f5789421]',
>           },
>         ],
>       },
>     },
> ```
I have also encountered this problem. Have you resolved it?

**Comment by demenech** [comment]
Found this error once again and this time I resolved it by setting the `processor_res` property to 512 (may vary depending on your model).

**Comment by Linket-LYF** [comment]
> Found this error once again and this time I resolved it by setting the property to 512 (may vary depending on your model).`processor_res`


I tried it and it was very effective. I want to know if this value is related to the width and height of the image. Is it a fixed setting of 512?

**Comment by demenech** [comment]
> > Found this error once again and this time I resolved it by setting the property to 512 (may vary depending on your model).`processor_res`
> 
> 
> I tried it and it was very effective. I want to know if this value is related to the width and height of the image. Is it a fixed setting of 512?

I believe that for better results it should be the same as the size of the images used to train the model you are using, but I'm not 100% sure.
