### ISSUE TITLE
[Bug]: When using ControlNet and Ddetailer in parallel, this error keeps appearing.

### ISSUE THREAD

**Issue by ayoora** [Mikubill/sd-webui-controlnet#1757]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When using ControlNet and Ddetailer in parallel, this error keeps appearing.
(https://github.com/dustysys/ddetailer) It's a problem that doesn't happen when Im not using ControlNet.

"NansException: A tensor with all NaNs was produced in Unet. This could be either because there's not enough precision to represent the picture, or because your video card does not support half type. Try setting the "Upcast cross attention layer to float32" option in Settings > Stable Diffusion or using the --no-half commandline argument to fix this. Use --disable-nan-check commandline argument to disable this check."

About 1 month ago, there was no problem using ControlNet and Ddetailer together, but this problem has been occurring continuously for the past week.

### Steps to reproduce the problem

I did 

"setting the "Upcast cross attention layer to float32" option in Settings"

but it is not working.

### What should have happened?

If possible, can you check and solve this part when updating?

### Commit where the problem happens

webui: O
controlnet: 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
-
```

### List of enabled extensions

-

### Console logs

```Shell
-
```

### Additional information

-

**Comment by huchenlei** [comment]
Following the console message instruction, add —no-half in your command line args.
