### ISSUE TITLE
img2img+inpaint broken

### ISSUE THREAD

**Issue by lllyasviel** [Mikubill/sd-webui-controlnet#1768]
someone told me that a1111 img2img + controlnet inpaint_global_harmonious is not working. I tested, it seems broken. 

To reproduce:

1. go to a1111 img2img, select img2img (the simple img2img without inpaint, not to confuse with a1111 img2img inpaint)
2. go to controlnet, select inpaint_global_harmonious
3. cannot upload image, cannot draw inpaint scribbles

This also make other modes broken, like a1111 img2img sketch + inpaint_global_harmonious, a1111 img2img inpaint sketch + inpaint_global_harmonious, a1111 img2img sketch + inpaint_only, a1111 img2img inpaint sketch + inpaint_only, etc

Besides, it seems that inpaint_global_harmonious's functionality to make soft transition is also broken in a1111 img2imh inpaint. Previously users can draw masks with larger holes in a1111 and draw different masks with a bit smaller holes in inpaint_global_harmonious to reduce seams in inpaint

**Comment by huchenlei** [comment]
https://github.com/Mikubill/sd-webui-controlnet/pull/1763 Disallows use of ControlNet input in img2img inpaint. If you click to upload an image it will display an alert let user use A1111 inpaint input.

If global harmonious requires the ControlNet input inpaint, for now, user can select `All` control type and select preprocessor/model to fallback to previous behaviour.

Or you can revert https://github.com/Mikubill/sd-webui-controlnet/pull/1763 for now. I will reland it later with global harmonious inpaint issue fixed.

**Comment by huchenlei** [comment]
If the revert is not straightforward, you can remove calls to https://github.com/Mikubill/sd-webui-controlnet/blob/f2a541dd8fc10b34c415b14412a97f596796306c/javascript/active_units.js#L142, which should remove the restrictions on inpaint.

**Comment by huchenlei** [comment]
Old behaviour restored in https://github.com/Mikubill/sd-webui-controlnet/pull/1769.

**Comment by huchenlei** [comment]
> 

Thanks for finding that comment! We should really document it somewhere more accessible. The new user would never be able to figure out how to properly use both masks together without guidance.
