### ISSUE TITLE
Where is the MIDAS Preprocessor?

### ISSUE THREAD

**Issue by ZeroCool22** [Mikubill/sd-webui-controlnet#177]
![Screenshot_5](https://user-images.githubusercontent.com/13344308/219842911-fa955d63-a317-4f7b-8e9c-5b829e8e6b95.png)

I downloaded everything but i don't see the MIDAS there or it changed the name?

**Comment by Mikubill** [comment]
depth is midas, renamed in https://github.com/Mikubill/sd-webui-controlnet/commit/0f200f195811a79096a1e48793e3f0eb783bcb28
