### ISSUE TITLE
[Bug] Controlnet inpaint always returns original image

### ISSUE THREAD

**Issue by FedorTarasow** [Mikubill/sd-webui-controlnet#1781]
**Is there an existing issue for this?**
  I have searched the existing issues and checked the recent builds/commits of both this extension and the webui
**What happened?**
  Controlnet inpaint always returns original image
![Screenshot_2](https://github.com/Mikubill/sd-webui-controlnet/assets/122746903/0b382b3a-56a6-46e3-84eb-2144d3fd6d8f)
![Screenshot_4](https://github.com/Mikubill/sd-webui-controlnet/assets/122746903/457941a2-51e8-45f2-bc43-c0cc0f077c40)
**Steps to reproduce the problem**
  Select img2img. Upload picture. Set denoising strength to 1. Enable controlnet impaint model. Upload same picture there. Set its control weight to 0.1.
**What should have happened?**
  SD should return changed picture, not original
**Commit where the problem happens**
  ControlNet v1.1.227
  webui: AUTOMATIC1111 v1.4.0
  model: control_v11p_sd15_inpaint [ebff9138],
  Checkpoint  deliberate_v2
  Python 3.10.6
**What browsers do you use to access the UI ?**
  Chrome

**Comment by huchenlei** [comment]
See https://github.com/Mikubill/sd-webui-controlnet/discussions/1771, for how to use img2img inpaint.
