### ISSUE TITLE
Training custom segmentation model 

### ISSUE THREAD

**Issue by SuroshAhmadZobair** [Mikubill/sd-webui-controlnet#1784]
Hi

Thanks for your effort on this great repo!

I know the normal procedure of training a controlnet model but I have difficulty understanding how to train a model that either outputs a semantic or an instance segmentation mask for an image.

I am curious about your insight.
Thanks in advance!

**Comment by linkedlist771** [comment]
You can find what you need at [this link](https://github.com/huggingface/diffusers/tree/main/examples/controlnet) .

**Comment by geroldmeisinger** [comment]
duplicate and crosspost of #459
