### ISSUE TITLE
Unable to run Controlnet v1.1.232 on Mac (M2 Pro)

### ISSUE THREAD

**Issue by theankittt** [Mikubill/sd-webui-controlnet#1785]
Getting this error: 
`(mpsFileLoc): /AppleInternal/Library/BuildRoots/97f6331a-ba75-11ed-a4bc-863efbbaf80d/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm:39:0: error: 'mps.matmul' op contracting dimensions differ 1024 & 768
(mpsFileLoc): /AppleInternal/Library/BuildRoots/97f6331a-ba75-11ed-a4bc-863efbbaf80d/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm:39:0: note: see current operation: %5 = "mps.matmul"(%arg0, %4) {transpose_lhs = false, transpose_rhs = false} : (tensor<2x77x1024xf32>, tensor<768x320xf32>) -> tensor<2x77x320xf32>
zsh: segmentation fault  ./webui.sh
(base) ankit@NLB-MAC-045 stable-diffusion-webui % /opt/homebrew/Cellar/python@3.10/3.10.12/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '`

**Comment by huchenlei** [comment]
Can you confirm that it is a ControlNet specific problem? i.e. The error does not occur when running A1111 alone, adding ControlNet will cause the error to appear consistently. From your stacktrace, I cannot see the connection to ControlNet being the culprit.

If ControlNet is causing the error, starting from which version the error starts to occur? I don't have a M2 Mac so you probably need to find the culprit PR, and I can revert it for you.

**Comment by WendyGinYu** [comment]
Hi, I have exactly the same issue. Could you let me know if you've been able to resolve it? I'm also using a Mac m chip with controller 1.1.410

**Comment by WendyGinYu** [comment]
Actually I resolved my issue. I got exactly same issue due to the version of stable diffusion and control net not matching... When using stable diffusion check point model based on SDXL together with control net 2.1 model I got same error. Changing to matching models resolve my issue. If any new user find this type of error maybe try check this first
