### ISSUE TITLE
How to get json from API ?

### ISSUE THREAD

**Issue by dchatel** [Mikubill/sd-webui-controlnet#1786]
I'm working some animation experiments, and I'd like to get the json representation of the pose programatically (from API or something else).

How can I do that ?

**Comment by huchenlei** [comment]
Currently there is no support to get openpose JSON from the API. Sorry about that. PR is welcome to add this feature.

**Comment by dchatel** [comment]
Any guidance on how to get it programatically directly from the extension itself?

**Comment by huchenlei** [comment]
If you are looking for a backend solution, i.e. invoke preprocessor in Python, you can reference https://github.com/Mikubill/sd-webui-controlnet/blob/main/tests/annotator_tests/openpose_tests/openpose_e2e_test.py.

If you are looking for a frone-end solution, you can just select following node and parse the base64 URL to a JSON object:
```html
<a href="data:application/json;base64,ewog..." download="pose.json" title="Download the pose as .json file">JSON</a>
```

**Comment by scholltan** [comment]
@huchenlei    hello， I revised code and got the json returned, while the keypoints is a little diffirent with the results from the webui

**Comment by 5shekel** [comment]
https://github.com/Mikubill/sd-webui-controlnet/pull/2033 !!

**Comment by huchenlei** [comment]
Yea, this issue should be closed by https://github.com/Mikubill/sd-webui-controlnet/pull/2033.
