### ISSUE TITLE
[Request] Using multi-inputs in openpose and enhancing the perspective relationship of bone images

### ISSUE THREAD

**Issue by Rorowalnuss** [Mikubill/sd-webui-controlnet#1791]
I have been using Controlnet since April, but the problem of physical deformities when multiple characters overlap has not been effectively resolved.
Especially when one person's arm covers another person's joints, limb deformities are almost inevitable, and one person's arms and legs are often connected to others.
As an example (this picture is not mine), if I want to use it as a reference, keep the composition and character movements unchanged, and replace everyone in the picture with adult men and women.

*Image deleted*

The general modification method is to use the openpose editor to modify the body ratio, and then use a plugin with partition prompts to edit each character's prompts.
But openpose didn't understand which arm and which leg belonged to whom. So you can always find very serious bad anatomy problems.

*Image deleted*

I have found that most of the multi-characters images generated using webui on the internet always have very little overlapping area of characters, but that only avoids the parts that openpose is not good at. And I asked CG artists around me for their opinions on this question, but the answer I received was simply 'No way, just paint it by yourself'.
Here is an image I recently created using webui.
![108932836_p0](https://github.com/Mikubill/sd-webui-controlnet/assets/129984754/450304f8-a554-4600-9822-0d882506dd1d)

I want to know if it's possible to solve the above problem?
The solutions I can think of now are as follows: 
①Enable the bone images to color indicate which parts belong to the same character. Although I can modify character skeletons to generate special races such as centaurs and mermaids, or to generate a tail, but in multi-character images, openpose sometimes interprets the tail as another person's leg or other strange thing.
②Enable the perspective levels of overlapping bone lines to be correctly recognized. The bone lines currently generated using the openpose preprocessor are actually semi transparent, so it seems unclear which one is above and which one is below the overlapping position.
③Increase support for external 3D models, but I think this may be very challenging.
④Using multi inputs, which involves simultaneously inputting multiple angle maps of a bone map, the model matches and fits the corresponding bone and joint positions in these maps to understand the 3D structure of the bone.
This is just a conjecture. This principle is often used in industrial 3D scanners, and I don't know if it can be applied to fields like machine vision or other fields. Because I am not an IT practitioner.

**Comment by huchenlei** [comment]
The open pose does not contain depth information. So you need to combine it with some form of depth information to tell SD what is in the front. For the limb belonging issue, what I found most useful is to inpaint one char at a time, instead of expecting 1 perfect generation of the whole image. For the example you give, tile is probably better than openpose if you want to control the pose and the relationship between characters. 

All your suggestions/requests are not very feasible at the moment as they all require training new custom control net model.

**Comment by shenmxd0762** [comment]
> The open pose does not contain depth information. So you need to combine it with some form of depth information to tell SD what is in the front. For the limb belonging issue, what I found most useful is to inpaint one char at a time, instead of expecting 1 perfect generation of the whole image. For the example you give, tile is probably better than openpose if you want to control the pose and the relationship between characters.
> 
> All your suggestions/requests are not very feasible at the moment as they all require training new custom control net model.

If I only want to preserve the character's movements, using tiles will bring some body shape information from the original image (such as changing the boy in the above image to a mature woman), reducing the weight of tiles, and using the prompts important mode can slightly make the generated image less like the original image, but it will also reduce the accuracy of limb position.
In addition, unlike openpose, the depth image generated by the depth preprocessor is difficult to edit, so I can only generate a Mannequin through external 3D software and then input controlnet for preprocessing, but the accuracy of the depth information after preprocessing is very poor.

The image of the 3D model looks like this
![Fv2mKcRagAM-_ih](https://github.com/Mikubill/sd-webui-controlnet/assets/31209203/7ff6eae9-d82d-435d-ac24-fa89021c5e54)

**Comment by 2blackbar** [comment]
Are You some kind of pedo dood? TF is with kids ? Can you change your images ?

**Comment by shenmxd0762** [comment]
> Are You some kind of pedo dood? TF is with kids ? Can you change your images ? Does your family know ? Where i can report this crap? The kid is clearly without underwear and it looks like a depiction of rape

All the female characters appearing here are 18 year old high school students, and I have removed any other content that may involve children

**Comment by shenmxd0762** [comment]
> Are You some kind of pedo dood? TF is with kids ? Can you change your images ? Does your family know ? Where i can report this crap? The kid is clearly without underwear and it looks like a depiction of rape

All the female characters appearing here are 18 year old high school students.The images of the boys may involve sensitive content, but I do not have permission to delete the images on the issue homepage

**Comment by Rorowalnuss** [comment]
> Are You some kind of pedo dood? TF is with kids ? Can you change your images ? Does your family know ? Where i can report this crap? The kid is clearly without underwear and it looks like a depiction of rape

I deleted the sensitive images

**Comment by Rorowalnuss** [comment]
> The open pose does not contain depth information. So you need to combine it with some form of depth information to tell SD what is in the front. For the limb belonging issue, what I found most useful is to inpaint one char at a time, instead of expecting 1 perfect generation of the whole image. For the example you give, tile is probably better than openpose if you want to control the pose and the relationship between characters.
> 
> All your suggestions/requests are not very feasible at the moment as they all require training new custom control net model.

I want to know if it's possible for the depth preprocessor to recognize the 3D model generated by other software, and if so, is there a requirement for the model material？
