### ISSUE TITLE
how can i save image created with controlnet using API I use normal map to img2img , how do I save that normal map while I'm using the API?

### ISSUE THREAD

**Issue by D-Mad** [Mikubill/sd-webui-controlnet#1792]
how can i save image created with controlnet using API I use normal map to img2img , how do I save that normal map while I'm using the API?

![Screenshot 2023-07-16 103952](https://github.com/Mikubill/sd-webui-controlnet/assets/8207507/b8dac370-4e9a-4ec5-a62a-1c8678f05aa9)

code of me :

import io
import cv2
import base64
import requests

from PIL import Image

# A1111 URL
url = "http://127.0.0.1:7860"

# Read Image in RGB order
img = cv2.imread('images/pexels-megan-ruth-15577641.jpg')

# Encode into PNG and send to ControlNet
retval, bytes = cv2.imencode('.png', img)
encoded_image = base64.b64encode(bytes).decode('utf-8')

# A1111 payload
payload = {
    "prompt": 'a beauty woman',
    "negative_prompt": "",
    "batch_size": 1,
    "steps": 20,
    "cfg_scale": 7,
    "alwayson_scripts": {
        "controlnet": {
            "args": [
                {
                    "input_image": encoded_image,
                    "module": "normal_bae",
                    "model": "control_v11p_sd15_normalba",
                }
            ]
        }
    }
}

# Trigger Generation
response = requests.post(url=f'{url}/sdapi/v1/txt2img', json=payload)

# Read results
r = response.json()
result = r['images'][0]
image = Image.open(io.BytesIO(base64.b64decode(result.split(",", 1)[0])))
image.save('output.png')

**Comment by huchenlei** [comment]
```python
result = r['images'][1]
```

Should be the controlnet preprocessor image if you keep batch_size = 1.
