### ISSUE TITLE
[Bug]: PNG info, not sending controlnet params 

### ISSUE THREAD

**Issue by S0ulMat3** [Mikubill/sd-webui-controlnet#1793]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Same issue as stated in:
#1203 

PNG info not sending ControlNet paramaters with  "Send to txt2img"

### Steps to reproduce the problem

1. Produce image with using controlnet
2. Load produced image in PNG info
3. From PNG info, Send to txt2img/img2img 

### What should have happened?

-

### Commit where the problem happens

webui: v1.4.1
controlnet: v1.1.232

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--xformers --allow-code --api --api-log --autolaunch --enable-insecure-extension-access --administrator
```

### List of enabled extensions

-

### Console logs

```Shell
-
```

**Comment by huchenlei** [comment]
I think you should submit an issue in A1111 repo, as the related code here has not been modified for 2 month. Also, the send PNG info feature is technically in A1111, unless you can prove that all other extension's param can be correctly transferred except ControlNet's param.
