### ISSUE TITLE
{HELP!!!}After updating the latest control network, the drawing speed is 10-20 times slower than before?? 

### ISSUE THREAD

**Issue by ponylin19780630** [Mikubill/sd-webui-controlnet#1794]
After updating the latest control network, the drawing speed is 10-20 times slower than before?? After closing the control network, the drawing speed is normal again!!??? The previous version will not be like this.

Model cache size=5
Multi ControlNet=3

**Comment by huchenlei** [comment]
Please do a `git bisect` to find the culprit PR. The good version is the version you upgraded from, the bad version is current version.

Here is instruction about how to perform a `git bisect`: https://stackoverflow.com/questions/4713088/how-to-use-git-bisect

The issue cannot be reproduced by us, so you have to figure out the suspect PR, and we can see if we can revert it or fix it.
