### ISSUE TITLE
Long Shot Question, Best way to use without Automatic1111

### ISSUE THREAD

**Issue by JemiloII** [Mikubill/sd-webui-controlnet#1795]
I know this is a longshot, but I don't use Automatic1111; any good way of using this without it? Currently, I've been using the diffuser library if that helps.

**Comment by z14git** [comment]
You can check out these repos:
- https://github.com/lllyasviel/ControlNet
- https://github.com/TencentARC/T2I-Adapter

**Comment by JemiloII** [comment]
awesome I appreciate it.
