### ISSUE TITLE
[Bug]: API controlnet/module_list no t2ia module 

### ISSUE THREAD

**Issue by AuYuHui** [Mikubill/sd-webui-controlnet#1799]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/38815121/47f0bb2f-e33e-4d12-8816-27edab34d0f2)

controlnet/module_list no t2ia module 

### Steps to reproduce the problem

[controlnet/module_list](http://192.168.10.142:7860/controlnet/module_list)

The number of models in the list is different

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/38815121/66324e8f-fc83-4e42-9480-a0642db6b6a5)
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/38815121/d99eac05-726c-4f7b-802b-9621c5d8732c)

### What should have happened?

consistent

### Commit where the problem happens

webui: 
controlnet: 

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
No
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/38815121/3948c247-b031-459f-912c-7dec5b128a39)

### Console logs

```Shell
no
```

**Comment by huchenlei** [comment]
See
```python
preprocessor_aliases = {
    "invert": "invert (from white bg & black line)",
    "lineart_standard": "lineart_standard (from white bg & black line)",
    "lineart": "lineart_realistic",
    "color": "t2ia_color_grid",
    "clip_vision": "t2ia_style_clipvision",
    "pidinet_sketch": "t2ia_sketch_pidi",
    "depth": "depth_midas",
    "normal_map": "normal_midas",
    "hed": "softedge_hed",
    "hed_safe": "softedge_hedsafe",
    "pidinet": "softedge_pidinet",
    "pidinet_safe": "softedge_pidisafe",
    "segmentation": "seg_ufade20k",
    "oneformer_coco": "seg_ofcoco",
    "oneformer_ade20k": "seg_ofade20k",
    "pidinet_scribble": "scribble_pidinet",
    "inpaint": "inpaint_global_harmonious",
}
```
t2ia preprocessors are just alias of `color`, `clip_vision` and `pidinet_sketch`.

**Comment by AuYuHui** [comment]
Setting this parameter is not useful

alwayson_scripts: {
      controlnet: {
        args: [
          {
            input_image: encoded_image,
            module: 'pidinet_sketch',
            model: 't2iadapter_sketch_sd15v2 [f5789421]',
          },
        ],
      },
    }

**Comment by huchenlei** [comment]
You have to set `enabled = True` in args.

**Comment by AuYuHui** [comment]
> You have to set `enabled = True` in args.
> 
> See example here: https://github.com/Mikubill/sd-webui-controlnet/blob/main/example/txt2img_example/api_txt2img.py

I tried, but it didn't work

**Comment by AuYuHui** [comment]
![1689749785349](https://github.com/Mikubill/sd-webui-controlnet/assets/38815121/5af8b621-978c-402c-bec7-c8a3a1cd94bd)

**Comment by AuYuHui** [comment]
> ![1689749785349](https://user-images.githubusercontent.com/38815121/254488742-5af8b621-978c-402c-bec7-c8a3a1cd94bd.png)

### I can use it after checking this. But a new problem has arisen

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/38815121/ebe370cb-2ebb-4313-b77c-75dad43924ea)


![image](https://github.com/Mikubill/sd-webui-controlnet/assets/38815121/d8bf3600-f268-4532-962d-d2df0015f8fa)
