### ISSUE TITLE
[Q / FR]: Batch Size and Multiple Input Image Support

### ISSUE THREAD

**Issue by bigahega** [Mikubill/sd-webui-controlnet#1800]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I am trying to use the "batch_size" option of the a1111 using multiple image inputs (img2img) but could not figure out if it is possible to configure the controlnet params to create individual control params for each image input. Right now it seems like it only uses the image in the first index of the input images to create the control params so each input image is controlled by the first image.

### Steps to reproduce the problem

1. use api mode for img2img
2. set batch_size > 1 and give multiple images for the image input
3. set controlnet params
4. each output image of the batch is controlled by the first image

### What should have happened?

each input image should be controlled by its own control mechanisms

### Commit where the problem happens

webui: f865d3e11647dfd6c7b2cdf90dde24680e58acd8
controlnet: 098f6cd887ac5f6f5f0e7cc9d81460095d2be012

### Command Line Arguments

```Shell
not relevant
```

### List of enabled extensions

not relevant

### Console logs

```Shell
not relevant
```

**Comment by huchenlei** [comment]
Duplicated https://github.com/Mikubill/sd-webui-controlnet/issues/1708
