### ISSUE TITLE
[Bug]: Does not work with 16-bit depthmaps

### ISSUE THREAD

**Issue by semjon00** [Mikubill/sd-webui-controlnet#1801]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?
Depthmaps are routinely stored in 16-bit monochrome single-channel images. However, currently 16-bit depthmaps can not be used for the depth preprocessor/control. When you try to use it, Gradio will try to convert it to RGB. Sadly, this "conversion" simply truncates values into [0;255]. This is incorrect, the values should have been scaled down.

This issue belongs here since 16-bit depthmaps are reasonably popular, but WebUI probably won't ship updated Gradio for some time - even if this issue is fixed on the Gradio side.

Please see https://github.com/thygate/stable-diffusion-webui-depthmap-script/issues/291

### Steps to reproduce the problem

1. Supply 16-bit depthmap to "Single Image"
2. Click "Run preprocessor" (this is an easy way to reproduce the issue)
3. Preview gives away that the image was not correctly read.

### What should have happened?

16-bit depthmap works in exactly the same way as 8-bit depthmap. I think that this is ok if some precision is sacrificed in this specific usecase.

### Commit where the problem happens

webui: 1.4.0
controlnet: 1.1.233

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
None
```

### List of enabled extensions

Only controlnet

### Console logs

```Shell
Nothing useful there
```

**Comment by thomaseding** [comment]
You do realize the depth models are not trained on 16-bit depthmaps. It's not like the model can understand it in the first place without converting it to RGB beforehand. (And if I'm not mistaken, doesn't ControlNet put the control image into latent space?) Simply put, the model isn't nuanced enough to even understand the data.

**Comment by thomaseding** [comment]
Please provide such a depth bitmap and I will take a look into it.

**Comment by semjon00** [comment]
![mushroom-photography-brown-slimy-waxcap-hygrocybe-irrigata](https://github.com/Mikubill/sd-webui-controlnet/assets/54073010/2d4519eb-eb45-412d-94b3-2181e5579e0a)
![depthmap-16900988530003](https://github.com/Mikubill/sd-webui-controlnet/assets/54073010/9de422e3-9055-4de4-97e2-9557b44ea4db)

**Comment by semjon00** [comment]
Discussed here: https://github.com/thygate/stable-diffusion-webui-depthmap-script/issues/291#issue-1810516049

**Comment by thomaseding** [comment]
![grass-blades](https://github.com/Mikubill/sd-webui-controlnet/assets/6971794/fe0bd8ee-5ee0-48a5-8e83-864c7b063f28)
Here is smaller a cropped image that is 16 bit grayscale.

**Comment by thomaseding** [comment]
https://github.com/Mikubill/sd-webui-controlnet/pull/1819
