### ISSUE TITLE
Is there any way to store ControlNet in a different directory?

### ISSUE THREAD

**Issue by kopyl** [Mikubill/sd-webui-controlnet#1805]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Not in `stable-diffusion-webui/extensions/sd-webui-controlnet/models`

### Steps to reproduce the problem

-

### What should have happened?

-

### Commit where the problem happens

-

### Command Line Arguments

```Shell
-
```

### List of enabled extensions

-

### Console logs

```Shell
-
```

**Comment by ljleb** [comment]
Yes, have a look at the settings tab. You can also pass the `--controlnet-dir` cli argument for adding a folder automatically.

**Comment by kopyl** [comment]
@ljleb thank you. Where shall i pass this thing to?

like `python launch.py --port 3000 --xformers --controlnet-dir="/cn"`?

And what is controlnet dir? is it the same directory like this? `stable-diffusion-webui/extensions/sd-webui-controlnet`
or like this? `stable-diffusion-webui/extensions/`
or anything else?
Not clear at all
and also why there is nothing on it here?: https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Command-Line-Arguments-and-Settings

**Comment by ljleb** [comment]
It is a directory to a folder that directly contains controlnet models.

The cli argument is added by controlnet, have a look at the readme here instead:
https://github.com/Mikubill/sd-webui-controlnet#command-line-arguments

**Comment by kopyl** [comment]
@ljleb thank you very much

**Comment by kopyl** [comment]
@ljleb did this:

https://github.com/Mikubill/sd-webui-controlnet/commit/e9679f8fc50880a92d6f1b6fc1aabad41079efd5

fix this:

https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/11695

?

**Comment by ljleb** [comment]
no, it's unrelated afaict. https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/11957 ended up being a better solution, as some scripts really cannot function by accepting a list instead of a batch tensor.

**Comment by kopyl** [comment]
@ljleb thanks.
