### ISSUE TITLE
An error occurred after the update

### ISSUE THREAD

**Issue by klossm** [Mikubill/sd-webui-controlnet#181]
This is the content of the error report

Error executing callback after_component_callback for L:\stable-diffusion2.0\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "L:\stable-diffusion2.0\modules\script_callbacks.py", line 185, in after_component_callback
    c.callback(component, **kwargs)
  File "L:\stable-diffusion2.0\extensions\sd-webui-controlnet\scripts\controlnet.py", line 592, in on_after_component_callback
    tab = component.parent
AttributeError: 'Textbox' object has no attribute 'parent'

**Comment by Mikubill** [comment]
cc @ljleb

**Comment by ljleb** [comment]
That's an odd one. Not sure why this happened, as the class hierarchy of gradio `TextBox` is:
`TextBox` -> `IOComponent` -> `Component` -> `Block`. Block initializes `parent` to `None` in its constructor.

Thanks for quick fix Mikubill!

**Comment by klossm** [comment]
Problem solved
