### ISSUE TITLE
[Feature]:  Use custom control Net model

### ISSUE THREAD

**Issue by linkedlist771** [Mikubill/sd-webui-controlnet#1810]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I have trained a custom control net model using the [diffuser guide](https://github.com/huggingface/diffusers/tree/main/examples/controlnet), but I do not how to use this model in the `extensions`. Then can use give the tutorial to use the custom trained model?

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

I could choose the custom model in the web UI. 

### Commit where the problem happens

controlnet:  extensions.

### Command Line Arguments

```Shell
`./sh`
```

### List of enabled extensions

just control net

### Console logs

```Shell
I have no idea about this.
```

### Additional information

Not yet

**Comment by DenkingOfficial** [comment]
You need to convert it from diffusers into checkpoint
Here is the link to the script and usage guide:
https://github.com/huggingface/diffusers/issues/3015#issuecomment-1500917937

Also, I'm interested to know how your model works :D

**Comment by linkedlist771** [comment]
It is so nice to hear from you, actually  I have trained this controlnet model with the tutorial dataset. 
It turns out that the prompt controlling effect is not such good. Here is the results：
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/72634327/e5814448-fe6c-4903-b7dd-bbcdb7b3a4e8)
