### ISSUE TITLE
[Bug]: controlnet is enabled but no input image is given after update to latest

### ISSUE THREAD

**Issue by hanrw** [Mikubill/sd-webui-controlnet#1815]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

got error -    ValueError: controlnet is enabled but no input image is given

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

controlnet should works as it before

### Commit where the problem happens

version: [v1.4.1](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/f865d3e11647dfd6c7b2cdf90dde24680e58acd8)  •  python: 3.10.6  •  torch: 1.13.1+cu117  •  xformers: N/A  •  gradio: 3.32.0  •  checkpoint: [fc2511737a](https://google.com/search?q=fc2511737a54c5e80b89ab03e0ab4b98d051ab187f92860f3cd664dc9d08b271)

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### List of enabled extensions

<img width="1185" alt="Snipaste_2023-07-22_19-38-06" src="https://github.com/Mikubill/sd-webui-controlnet/assets/1201118/7b598a8e-2f2a-4b50-af28-81aadd009013">

### Console logs

```Shell
2/2023 7:16:59 PM2023-07-22 11:16:59,217 - ControlNet - INFO - Loading config: /home/diffusion/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_v11p_sd15_mlsd.yaml
7/22/2023 7:17:01 PM2023-07-22 11:17:01,893 - ControlNet - INFO - ControlNet model control_v1p_sd15_brightness [5f6aa6ed] loaded.
7/22/2023 7:17:01 PM2023-07-22 11:17:01,917 - ControlNet - INFO - Loading preprocessor: none
7/22/2023 7:17:01 PM2023-07-22 11:17:01,917 - ControlNet - INFO - preprocessor resolution = 832
7/22/2023 7:17:01 PM2023-07-22 11:17:01,928 - ControlNet - INFO - Loading model from cache: control_v1p_sd15_brightness [5f6aa6ed]
7/22/2023 7:17:01 PM*** Error running process: /home/diffusion/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
7/22/2023 7:17:01 PM    Traceback (most recent call last):
7/22/2023 7:17:01 PM      File "/home/diffusion/stable-diffusion-webui/modules/scripts.py", line 474, in process
7/22/2023 7:17:01 PM        script.process(p, *script_args)
7/22/2023 7:17:01 PM      File "/home/diffusion/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 734, in process
7/22/2023 7:17:01 PM        input_image, image_from_a1111 = Script.choose_input_image(p, unit, idx)
7/22/2023 7:17:01 PM      File "/home/diffusion/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 652, in choose_input_image
7/22/2023 7:17:01 PM        raise ValueError('controlnet is enabled but no input image is given')
7/22/2023 7:17:01 PM    ValueError: controlnet is enabled but no input image is given
7/22/2023 7:17:01 PM
7/22/2023 7:17:01 PM---
```
```


### Additional information

_No response_

**Comment by huchenlei** [comment]
This exception is thrown because you are using txt2img mode but failed to provide an input image to controlnet.

**Comment by hanrw** [comment]
@huchenlei Thanks for explaining. but any idea to fix that? it's happened after update to latest SD webui and controlnet.

**Comment by hanrw** [comment]
Just found the issue was caused by the wrong settings.
<img width="697" alt="image" src="https://github.com/Mikubill/sd-webui-controlnet/assets/1201118/e9790c55-6c8d-4d76-8400-7a7490599192">
