### ISSUE TITLE
[Feature]: Option to select a path where the UI will have to go find the controlnel models.

### ISSUE THREAD

**Issue by StableInfo** [Mikubill/sd-webui-controlnet#1824]
Hello,
I am using VLAD A1111 fork and the initial A1111 UI at the same time. Both of them.
I would like to avoid having the same controlmodels twice and regain bit of my computer memory back,
Could there be an option to have the UI be able to go find the controlnel models in a different path than the usual one, and even multiple paths if needed?

Thanks a lot
Tell me if thats doable or is ever planned.

**Comment by huchenlei** [comment]
See https://github.com/Mikubill/sd-webui-controlnet#command-line-arguments
