### ISSUE TITLE
Is it possible to turn on a loopback for a controlnet unit programmatically?

### ISSUE THREAD

**Issue by frowenz** [Mikubill/sd-webui-controlnet#1837]

**Comment by ljleb** [comment]
The batch mode is not designed to be used programatically at the moment, it is a ui-only feature. The rationale was that if you need to have loopback through the api or another script, or any other similar complex batch behavior, you should be able to schedule the images yourself.

What is your use case? The rationale could be wrong.

**Comment by frowenz** [comment]
Thanks. That makes sense. I am trying to run temporalnet with the multi-frame video rendering script. I will just modify the script.

https://xanthius.itch.io/multi-frame-rendering-for-stablediffusion
