### ISSUE TITLE
Controlnet influence decay (?) when batch count > 1 and guidance < 0.94

### ISSUE THREAD

**Issue by R-N** [Mikubill/sd-webui-controlnet#184]
Here I'm using canny edge. No lora, hypernet, or embedding used. 

![image](https://user-images.githubusercontent.com/1442761/219854227-0891f89b-a34a-455e-9dc6-891f266d016e.png)

<details>
<summary>Here's an example with batch count=4, weight=1, and guidance=0.94 (or higher)</summary>

![00024-904911766-EimisAnimeDiff___](https://user-images.githubusercontent.com/1442761/219854248-59d3fb62-8adc-4d30-b785-7c47127c7af5.png)
![00025-904911767-EimisAnimeDiff___](https://user-images.githubusercontent.com/1442761/219854251-9b31eb35-15c6-48a3-8428-53c6d84df3d8.png)
![00026-904911768-EimisAnimeDiff___](https://user-images.githubusercontent.com/1442761/219854253-a7007b4f-5fad-4887-9984-7b1f84c60fd1.png)
![00027-904911769-EimisAnimeDiff___](https://user-images.githubusercontent.com/1442761/219854254-f1694ea0-cced-4a16-ba94-bb7a0278461b.png)

</details>

<details>
<summary>But when I lower guidance to 0.93 (or lower) only first image resembles the source</summary>

![00028-3863989860-EimisAnimeDif___](https://user-images.githubusercontent.com/1442761/219854364-3e190854-1e01-49d0-b65a-71ce447fa52b.png)
![00029-3863989861-EimisAnimeDif___](https://user-images.githubusercontent.com/1442761/219854362-bf54ed7b-63c4-47b7-80fa-18ab0e2d1601.png)
![00030-3863989862-EimisAnimeDif___](https://user-images.githubusercontent.com/1442761/219854363-e4729c49-7f96-4831-ae48-066a3eb075e3.png)
![00031-3863989863-EimisAnimeDif___](https://user-images.githubusercontent.com/1442761/219854365-0ef5ee23-4086-4200-9514-7dc102c6ce47.png)

</details>

Not sure what's going on. At first I thought it decayed with each batch, but 0.01 difference between 0.94 and 0.93 makes huge impact on the results. (I was looking for a value when it'd look like it's decaying with each batch)

**Comment by Mikubill** [comment]
Weird. Could you render some xyz image to diagnose?

**Comment by Mistborn-First-Era** [comment]
Same issue. The first image is correct then the next 3 are very very wrong. When I generate images one at a time it works.

![image](https://user-images.githubusercontent.com/100924753/219857967-b673abb2-bed9-458b-a930-bd5f44f3c70e.png)

**Comment by R-N** [comment]
Sorry I ran out of colab GPU hours. Maybe tomorrow

**Comment by Mikubill** [comment]
Now it should work properly. 
Note that even you set the guidance strength to 0, the controlnet may still run for a step or two - due to WebUI's cfg_denoiser_hook is located after unet pass. 

![xyz_grid-0010-1373004563-masterpiece, 1girl, high quality (1)](https://user-images.githubusercontent.com/31246794/219865630-da9be1c6-d2bc-4316-81ea-c2dc071ce36b.png)

**Comment by Mistborn-First-Era** [comment]
> Now it should work properly. Note that even you set the guidance strength to 0, the controlnet may still run for a step or two - due to WebUI's cfg_denoiser_hook is located after unet pass.
> 
> ![xyz_grid-0017-1373004563-masterpiece, 1girl, high quality-2](https://user-images.githubusercontent.com/31246794/219867069-e644e9b7-6fd7-42e3-bf4f-805e4168b5f6.png)

How did you make a grid with those variable?

**Comment by R-N** [comment]
Yep, it works now. Thank you!
