### ISSUE TITLE
Notice webui `1.5.0`~`1.5.1` img2img batch + controlnet is bugged

### ISSUE THREAD

**Issue by w-e-w** [Mikubill/sd-webui-controlnet#1848]
>this is just a notice for those who encounter this issue
the issue has been fixed and does not require action form this repo

There's currently an bug in webui `1.5.0`~`1.5.1` that cause `img2img batch` to failed using with controlnet
for details see issue post https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/12149

The fix has already been merged to `dev` see PR https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/12164

If you are on `1.5.0`~`1.5.1` and need `img2img batch` to work now
in `Settings` > `ContronNet` > check `Do not append detectmap to output`

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/40751091/7418c9fd-475d-4f70-8a4e-977a566526a2)

~~I suggest that either switch to `dev` brunch or downgread to `1.4.0`~~

>close this post after the fix is pushed to webui master

**Comment by huchenlei** [comment]
Thanks for the notice!

**Comment by w-e-w** [comment]
good news, I found a workaround

**Comment by CounterBeat** [comment]
Thanks, it works!
