### ISSUE TITLE
[Bug]: Enable controlNet Units by default!

### ISSUE THREAD

**Issue by p0mad** [Mikubill/sd-webui-controlnet#1854]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

How can i enable Controlnet Units by default without need to enable each one manually with their own configs!

Thanks
Regards

### Steps to reproduce the problem

N

### What should have happened?

N

### Commit where the problem happens

webui: version: [v1.5.1](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/68f336bd994bed5442ad95bad6b6ad5564a5409a)  •  python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.32.0  •  checkpoint: [ef49fbb25f](https://google.com/search?q=ef49fbb25fa908bb54ded95abf81ef4b0e21fa0a8de56c40c3d62e768ef7e49a)
controlnet: Latest

### Command Line Arguments

```Shell
n
```

### List of enabled extensions

n

### Console logs

```Shell
n
```

**Comment by huchenlei** [comment]
See https://github.com/Mikubill/sd-webui-controlnet/discussions/1703

**Comment by p0mad** [comment]
@huchenlei 
Thanks for the reply, but i meant something else!
in AUTO1111 i can put my default configs inside ui-config.json to follow them as a default option!
but there is no such a thing for ControlNET!

I mean the default to be enabled, or some default setting for each unit of CN
that would be fascinating in case of using other script or testing same CN units multiple times ...
Thanks
Regards

**Comment by huchenlei** [comment]
What do you mean `in case of using other scripts`? Are you expecting other scripts to manipulate ControlNet's UI? 

If you just want to do automation with some ControlNet presets, you should use the [Web API](https://github.com/Mikubill/sd-webui-controlnet/wiki/API) to achieve it.

**Comment by p0mad** [comment]
@huchenlei 
by other Scripts, i mean using m2m, ...
I mean if such a thing is provided, that would kill lots of manual processing of doing each steps by hand!

Something like this but for CN:
"txt2img/Prompt/visible": true,
    "txt2img/Prompt/value": "",
    "txt2img/Negative prompt/visible": true,
    "txt2img/Negative prompt/value": "",
    "txt2img/Interrupt/visible": true,
    "txt2img/Skip/visible": true,
    ...

**Comment by huchenlei** [comment]
Please specify what are the manual steps (Click/inputs) you are doing right now that will be solved if we provide the ability to set default values for each ControlNet unit

**Comment by p0mad** [comment]
@huchenlei 
Thank you so much
These are the steps for both T2I, I2I:
    cn0 [openpose]:
        upload image/name from the directory
        Check Pixel Perfect,
        Choose Control Type as OpenPose
         Select Preprocessor (openpose full / hand)
        Choose Model ( Defaults to control_v11p_sd15_openpose [cab727d4] )
        Control Weight : 1.4
        Starting Control Step 0.23
        Starting Control Step 0.53
        Control Mode: ControlNet is more important
        Resize Mode : Just Resize
        check or uncheck Loopback option


The same goes for canny on the second controlNet

For the third CN unit which is tile it has one more option 
Down Sampling Rate: 1.5

the Forth and 5th also has the same options are the 1st
weight 1.8, CNmoreimportant
    cn1 [Scribble]:
        001rm, weight 1.6, promptmoreimportant
    cn2 [Tile]:
        001rm, weight 0.9, downsamplingrate 1, promptmoreimportant
    cn3 [depth]:
        001rm, weight 1.35, balance

**Comment by huchenlei** [comment]
I think the real feature you are requesting is to have a preset of ControlNetUnit configuration to choose from instead of having all of them `enabled` by default.

**Comment by p0mad** [comment]
Not Enabled by default, but like this one
"txt2img/Prompt/visible": true,
"txt2img/Prompt/value": "",

That could be disabled by default and Eveyone who wants this process manually do it by hand and for peoples like me who are testing different images using the same config that would be much of help to set these once and use lots of times!

**Comment by jmilez** [comment]
I used the "Set Defaults" in the settings and it will remember the CN settings, but  it seems when the interface loads, CN isn't aware the controls "changed" by the host.  Another issue is I only had one unit enabled, but on load, it would enable all the units (even they weren't "highlighted" - had to disable them).  YMMV.  Would be real useful to remember the Tile settings for i2i and to remember the scale factor (it will set the scale, but it's not "recognized" because it's not done through the API I'm guessing).  There is a preset extension that does the same thing and had the same issues.

**Comment by p0mad** [comment]
@jmilez 
Where can i find the "set Defaults" option?

**Comment by jmilez** [comment]
It's near the bottom of the a1111 settings tab.

**Comment by jmilez** [comment]
You make all the changes to the user interface and then click on save
defaults.

**Comment by p0mad** [comment]
@jmilez 
can you show me the botton?
under which menu?

**Comment by jmilez** [comment]
Sure when I get back to my computer. might be a couple hours.

**Comment by p0mad** [comment]
@jmilez 
Thanks for the steps, but this does not affect the units in controlnet!
it just enables all with the same setting as the first unit!
