### ISSUE TITLE
[DevTask] Add DWPose version of Openpose preprocessor

### ISSUE THREAD

**Issue by huchenlei** [Mikubill/sd-webui-controlnet#1855]
https://github.com/IDEA-Research/DWPose
shows really promising results on more accurate pose detection with openpose output, especially on hands. 

We should port the implementation and make it available in the ControlNet extension.

**Comment by huchenlei** [comment]
As a side note, we should consider re-train the ControlNet openpose model with DWPose annotated data, as previously the annotation results are not very accuate, which results openpose hand skelelton has weak control on result image. 

https://github.com/IDEA-Research/DWPose/issues/2

**Comment by 2blackbar** [comment]
Training with feet would be great

**Comment by tanghengjian** [comment]
hi @2blackbar  
 i tested the controlnet openpose will not accurately produce similar number persons, such as the origial pose has three persons, while the output inference has four persons. 
So i want to re-train the openpose model with multi persons cases. Could the loss only care about the image's pose  rather not the original full  image pixel info?
Any suggestions would be greatly appreciated！！！thank you!
