### ISSUE TITLE
Install via terminal

### ISSUE THREAD

**Issue by rb-synth** [Mikubill/sd-webui-controlnet#1858]
I hope to only use A1111 via the API. I feel that currently, I need to use the web UI to get things set up before I can start using the API. For example, I ran `git clone` in the extensions folder (and downloaded the models), but controlnet only seems to be working if I install it in the UI. Is there any way around this?

Further, I'd like to set the maximum number of controlnets via the API. Is this possible?

**Comment by Adenialzz** [comment]
is this issue solved? how to install sd-webui controlnetnet using `git clont` ?
