### ISSUE TITLE
Is it possible to do a Batch run with Img2Img but keep init Image one

### ISSUE THREAD

**Issue by demirklvc** [Mikubill/sd-webui-controlnet#186]
Is it possible to do a Batch run with Img2Img but keep init Image one:

I mean: Changing only Control net input image input, but ''locking'' the standard img input-so it will be like an little color/style transfer. 

If so: Can someone point me out how to do that?

**Comment by ljleb** [comment]
The webui has sub-tabs in the img2img tab to support different modes of operation. Maybe we could use a similar design and use tabs? Maybe something like these tabs:

1. upload mode: import an image
2. draw sketch mode: button to create drawing canvas like it is implemented currently
3. batch processing mode: specify a path to batch process controlnet image

One advantage of separating drawing vs upload in different tabs is, the width/height sliders will be less confusing.

In img2img batch tab, maybe we could do the batch img2img n*m times, where n = number of controlnet image and m = number of img2img images?

**Comment by Mikubill** [comment]
Good idea. But at present gr.Accordion is already very crowded, adding more tabs may cause some ui issues

btw, we indeed need to redesign the ui to support composable guidance with multiple input/controlnet/adapters in the future

**Comment by demirklvc** [comment]
looking forward to this introduction!

**Comment by demirklvc** [comment]
> Good idea. But at present gr.Accordion is already very crowded, adding more tabs may cause some ui issues
> 
> btw, we indeed need to redesign the ui to support composable guidance with multiple input/controlnet/adapters in the future

how soon can we expect batch process for control net images? this would help alot to find the right poses for certain styles.

**Comment by rulyone** [comment]
> Good idea. But at present gr.Accordion is already very crowded, adding more tabs may cause some ui issues
> 
> btw, we indeed need to redesign the ui to support composable guidance with multiple input/controlnet/adapters in the future

This can be done with this pull request approved in both the AUTOMATIC1111 webui and the ControlNet extension here, by providing a single image in the new control images folder added.

I just created both pull requests, hope you can review it and improve/approve if possible.

https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/8125/files
https://github.com/Mikubill/sd-webui-controlnet/pull/383
