### ISSUE TITLE
Preview not showing if img2img image is being used

### ISSUE THREAD

**Issue by NoteToSelfFindGoodNickname** [Mikubill/sd-webui-controlnet#1867]
If you don't load an image into ControlNet, it will show a small green button showing "AI1111", and when you hover over it, it says "If you don't load an image here, the img2img will be used".

That is great. It does show the img2img2 image, I don't have it load it.

However, when I click the Explode button, no preview is shown.
Only when I load the image manually, the Explode button shows a preview.

**Comment by huchenlei** [comment]
See note of https://github.com/Mikubill/sd-webui-controlnet/pull/1747. 

I was trying to display an alert when there you click the run processor button without an input image, but obviously Gradio does not like vanilla JS `alert` which is blocking.

I will try to implement it another way. Thanks for reminding!

Trigger the preprocessor with the A1111 image directly is not quite feasible as the A1111 image has many sources (inpaint, inpaint upload, img2img, etc)
