### ISSUE TITLE
Just updated - lost the selector to turn on Controlnet.

### ISSUE THREAD

**Issue by egormly** [Mikubill/sd-webui-controlnet#187]
Just updated - lost the selector to turn on Controlnet, I now have just a little [image] symbol.

**Comment by Mikubill** [comment]
Maybe restart WebUI will help?

**Comment by egormly** [comment]
tried complete restart of everything including system twice, it's weird.

**Comment by egormly** [comment]
I just reinstalled Auto completely and I am getting the same thing. Small screen shot on imgurl:

[https://imgur.com/a/AmDbe6L](url)

**Comment by Mikubill** [comment]
Hmm..are you talking about the selector? Just a small note, controlnet's selector always located on right side of the toolbar.

<img width="791" alt="Scre" src="https://user-images.githubusercontent.com/31246794/219876620-78cd8f2d-2664-4cad-9a98-668cbd3d4451.png">

**Comment by egormly** [comment]
Ok, so I am an idiot... for some reason I saw that broken image and assumed it was on the upper left like many of the other extensions.  Feel free to mark my post _-closed because of a doofus_.  :)  Thanks and sorry for wasting your time.
