### ISSUE TITLE
How can I upload an Image from other Extension through SDWUI in Text-to-Image Tab in modern way?

### ISSUE THREAD

**Issue by MetallicPickaxe** [Mikubill/sd-webui-controlnet#1880]
I found here are some changes mentioned in source code:

>
    @staticmethod
    def choose_input_image(
            p: processing.StableDiffusionProcessing, 
            unit: external_code.ControlNetUnit,
            idx: int
        ) -> Tuple[np.ndarray, bool]:
        """ Choose input image from following sources with descending priority:
         - p.image_control: [Deprecated] Lagacy way to pass image to controlnet.
         - **p.control_net_input_image: [Deprecated]** Lagacy way to pass image to controlnet.
         - unit.image: 
           - ControlNet tab input image.
           - Input image from API call.
         - p.init_images: A1111 img2img tab input image.

        Returns:
            - The input image in ndarray form.
            - Whether input image is from A1111.
        """

And what is the replacement of `p.control_net_input_image` ?

**Comment by huchenlei** [comment]
You can access the `ControlNetUnit` in `p` with https://github.com/Mikubill/sd-webui-controlnet/blob/main/internal_controlnet/external_code.py and set the `image` attribute on the `ControlNetUnit`.

**Comment by MetallicPickaxe** [comment]
Thank you, very nice refactoring.
Hope more documents or examples.
