### ISSUE TITLE
sd21 openpose v2 controlnet doesn't work

### ISSUE THREAD

**Issue by Michaelwhite34** [Mikubill/sd-webui-controlnet#1885]
![Image0003](https://github.com/Mikubill/sd-webui-controlnet/assets/72028833/7402e931-a679-4252-b569-6a6779a45d2c)
It works for sd 1.5 but no effect for sd 2.1.

**Comment by huchenlei** [comment]
Sd 2.1 need to use sd 2.1 controlnet models, which you need to download separately. The models in the repo by default are all for sd 1.5.

**Comment by Michaelwhite34** [comment]
> Sd 2.1 need to use sd 2.1 controlnet models, which you need to download separately. The models in the repo by default are all for sd 1.5.

The model's name is "control_v11p_sd21_openposev2[f3edb4e5]", I think it's sd 2.1 model ?
