### ISSUE TITLE
Preview as Input API

### ISSUE THREAD

**Issue by rb-synth** [Mikubill/sd-webui-controlnet#1901]
I'm running the same image multiple times, so it's wasteful to repeatedly generate the controlnet images. How can I replicate the "Preview as Input" button from the API?

**Comment by huchenlei** [comment]
We do have cache for preprocessor results. You can set logging level to debug to verify that whether the call is getting result from cache or not.

**Comment by huchenlei** [comment]
See https://github.com/Mikubill/sd-webui-controlnet/blob/2daccd995d8c7e22e6af93bf7c433b2074097aff/scripts/global_state.py#L20

**Comment by rb-synth** [comment]
Thank you for your response, but it does not answer my question. How do I use it as part of the API, similar to this example?
```json
{
  "init_images": ["base64..."],
  "sampler_name": "Euler",
  "alwayson_scripts": {
    "controlnet": {
      "args": [
        {
          "module": "depth",
          "model": "diff_control_sd15_depth_fp16 [978ef0a1]"
        }
      ]
    }
  }
}
```

**Comment by rb-synth** [comment]
Ok, thanks
