### ISSUE TITLE
[Bug]: API does not work, error occurs when using the API

### ISSUE THREAD

**Issue by sharkDDD** [Mikubill/sd-webui-controlnet#1902]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Forgive my poor english. I update the stable diffusion webui to 1.5.1 and controlnet to the latest 2daccd99, the API does not work 
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/42758995/70480fd4-70e2-44cc-9b36-fd6be326b6db)
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/42758995/ff2c6cf7-6e28-46d7-a77e-87e76cb1f9f3)

### Steps to reproduce the problem

I dont know how to reproduce the problem, I install the latest verison of stable diffusion webui and controlnet and then the api of controlnet does not work.

### What should have happened?

No

### Commit where the problem happens

webui: 
controlnet: 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/42758995/054aac20-6d80-4da2-a807-07af3329f538)

### Console logs

```Shell
2023-08-10 16:16:19,867 - ControlNet - INFO - Loading model from cache: t2iadapter_sketch_sd15v2 [f5789421]
*** Error running process: /opt/data2/wangzhiqiang/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "/opt/data2/wangzhiqiang/stable-diffusion-webui/modules/scripts.py", line 519, in process
        script.process(p, *script_args)
      File "/opt/data2/wangzhiqiang/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 739, in process
        input_image, image_from_a1111 = Script.choose_input_image(p, unit, idx)
      File "/opt/data2/wangzhiqiang/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 607, in choose_input_image
        image = image_dict_from_any(unit.image)
      File "/opt/data2/wangzhiqiang/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 94, in image_dict_from_any
        image['image'] = external_code.to_base64_nparray(image['image'])
      File "/opt/data2/wangzhiqiang/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 194, in to_base64_nparray
        return np.array(api.decode_base64_to_image(encoding)).astype('uint8')
      File "/usr/local/anaconda3/envs/python3.10/lib/python3.10/site-packages/PIL/Image.py", line 696, in __array_interface__
        if self.mode == "1":
      File "/usr/local/anaconda3/envs/python3.10/lib/python3.10/site-packages/PIL/Image.py", line 754, in tobytes
      File "/usr/local/anaconda3/envs/python3.10/lib/python3.10/site-packages/PIL/WebPImagePlugin.py", line 158, in load
        # We need to load the image data for this frame
      File "/usr/local/anaconda3/envs/python3.10/lib/python3.10/site-packages/PIL/WebPImagePlugin.py", line 125, in _get_next
        # Get next frame
    OSError: failed to read next frame
```

**Comment by sharkDDD** [comment]
![1](https://github.com/Mikubill/sd-webui-controlnet/assets/42758995/3afb275d-6aa9-44b4-bf8c-dc1295300526)
I follow the API page https://github.com/Mikubill/sd-webui-controlnet/wiki/API and shown as the figure, but it does not work.

**Comment by huchenlei** [comment]
This seems to be a problem with your base64 encoded input image string. Please double check the string is valid.

**Comment by sharkDDD** [comment]
> This seems to be a problem with your base64 encoded input image string. Please double check the string is valid.

It is weird, The same base64 encoded image string worked in the old version of sd-webui and controlnet,  nothing changed, but it does not work right now after updating.  Another question is that the example code at the bottom of  https://github.com/Mikubill/sd-webui-controlnet/wiki/API also does not work. I only change the input image. The error is about the CV2.resize, it seems like something is wrong with the image, but I can not solve it. 
![lQLPJwIcFnlWIszNBcbNCVywuARBVHONzmYEyq2gTEDVAA_2396_1478](https://github.com/Mikubill/sd-webui-controlnet/assets/42758995/a798e0f4-80d4-4ebf-b65b-a73f13ba33bf)
![lQLPJxqNaWLZTMzNA5rNCl6wN8gRYR7XxfUEyq18uwDVAA_2654_922](https://github.com/Mikubill/sd-webui-controlnet/assets/42758995/bb3888cc-d641-43f0-a398-8542aa2d6570)
The image is successfully converted to base64, but the API does not work, and the error in the log file is shown in the screenshot.  Maybe this is a easy question but I can not deal with it, plz help me ...

**Comment by sharkDDD** [comment]
It is weird. The same base64 encoded image string worked in the old version of sd-webui and controlnet,  nothing changed, but it does not work right now after updating.  Another question is that the example code at the bottom of  https://github.com/Mikubill/sd-webui-controlnet/wiki/API also does not work. I only change the input image. The error is about the CV2.resize, it seems like something is wrong with the image, but I can not solve it. 
The image is successfully converted to base64, but the API does not work, and the error in the log file is shown in the screenshot.  Maybe this is a easy question but I can not deal with it, plz help me ...
![66e9800019e8398e960c298f31913b77](https://github.com/Mikubill/sd-webui-controlnet/assets/42758995/90dbff5b-3467-4840-b0ce-766953f717f8)
![lQLPJw1fL5e8uCzNAxTNCEywdYDIL3MbHSAEyrBUNcC7AA_2124_788](https://github.com/Mikubill/sd-webui-controlnet/assets/42758995/ee3d42c3-d735-4606-847e-9f99fd78606f)

**Comment by Charoncrat** [comment]
bro had you solved this problem right now? i got the same problem
