### ISSUE TITLE
[Bug]: ControlNet - WARNING - ControlNet does not support SDXL -- disabling

### ISSUE THREAD

**Issue by LgnGithub** [Mikubill/sd-webui-controlnet#1910]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Downloaded this depth model for SDXL1.0 to controlnet/models:

https://huggingface.co/SargeZT/controlnet-v1e-sdxl-depth

When I tried to actually use it with SDXL1.0 base model ControlNet gave an error 
```
ControlNet - WARNING - ControlNet does not support SDXL -- disabling
```
Should not happen since this depth model is meant for SDXL1.0

I already had a depth image ready and did not use a preprocessor, only the postprocessor

Device M1Pro Apple Silicon 32GB RAM

### Steps to reproduce the problem

1. Download https://huggingface.co/SargeZT/controlnet-v1e-sdxl-depth to controlnet/models
2. Enable depth option in ControlNet
3. Choose the appropriate depth model as postprocessor ( diffusion_pytorch_model.safetensors)
4. Do not choose preprocessor
5. Try to generate image with SDXL1.0 base model

### What should have happened?

It should have launched the depth model

### Commit where the problem happens

webui: version: [v1.5.1]
controlnet: ControlNet v1.1.237

### Command Line Arguments

```Shell
Launching Web UI with arguments: --no-half --disable-nan-check --skip-torch-cuda-test --upcast-sampling --opt-sub-quad-attention --use-cpu interrogate
```

### List of enabled extensions

sd-webui-controlnet
sd-webui-refiner
ultimate-upscale-for-automatic1111
LDSR
prompt-bracket-checkerLDSR 
Lora 	
ScuNET 	
SwinIR 	
canvas-zoom-and-pan 	
extra-options-section 	
mobile 	
prompt-bracket-checker

### Console logs

```Shell
-
```

**Comment by linsmalldragon** [comment]
https://huggingface.co/thibaud/controlnet-openpose-sdxl-1.0
Hope support sdxl model in auto1111

**Comment by slavakurilyak** [comment]
> Hope support sdxl model in auto1111

There's a fork of auto1111 that supports SDXL [here](https://github.com/vladmandic/automatic)

**Comment by T3chRomanc3r** [comment]
> > Hope support sdxl model in auto1111
> 
> There's a fork of auto1111 that supports SDXL [here](https://github.com/vladmandic/automatic)

Is canny SDXL controlnet works in SD NEXT?

**Comment by pnavitha** [comment]
Does this issue still exist Or is it fixed with the newer version of automatic1111?
