### ISSUE TITLE
Hybrid Tab not responding properly [Bug]: On Deforum

### ISSUE THREAD

**Issue by senpaiiss** [Mikubill/sd-webui-controlnet#1915]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

So what is happening with the new update i go onto the hybrid to select the setting and it just have a forever loading glitch. Please fix asap ty. Also control net section is bugging out. When I add 2 control nets sometimes it bugs out and not load or takes forever to load it.

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

1

### Commit where the problem happens

webui: 
controlnet: 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
1
```

### List of enabled extensions

Anime4K | https://github.com/bloc97/Anime4K.git | master | 8e39551c | Sat May 27 01:50:10 2023 | unknown
-- | -- | -- | -- | -- | --
Auto-Photoshop-StableDiffusion-Plugin | https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin.git | master | 1ae31637 | Sun Jul 16 10:08:10 2023 | unknown
Stable-Diffusion-Webui-Civitai-Helper | https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper.git | main | 920ca326 | Tue May 23 11:53:22 2023 | unknown
TemporalKit | https://github.com/CiaraStrawberry/TemporalKit | main | 3f5ef883 | Sat Aug 5 13:32:45 2023 | unknown
a1111-sd-webui-lycoris | https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris.git | main | 8e97bf54 | Sun Jul 9 07:44:58 2023 | unknown
adetailer | https://github.com/Bing-su/adetailer.git | main | f18e00b4 | Mon Jul 31 12:03:01 2023 | unknown
civitai-shortcut | https://github.com/sunnyark/civitai-shortcut.git | main | 4b3cf85d | Thu Aug 10 23:50:09 2023 | unknown
deforum-for-automatic1111-webui | https://github.com/deforum-art/deforum-for-automatic1111-webui.git | automatic1111-webui | 0949bf42 | Sun Aug 13 17:47:07 2023 | unknown
gif2gif | https://github.com/LonicaMewinsky/gif2gif.git | main | 5121851e | Sat May 13 14:56:04 2023 | unknown
multidiffusion-upscaler-for-automatic1111 | https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111.git | main | f9f8073e | Sat Jul 22 06:53:11 2023 | unknown
openpose-editor | https://github.com/fkunn1326/openpose-editor.git | master | 722bca6f | Sat Jun 3 04:54:52 2023 | unknown
posex | https://github.com/hnmr293/posex.git | master | 292f92d5 | Wed May 3 08:59:57 2023 | unknown
sd-3dmodel-loader | https://github.com/jtydhr88/sd-3dmodel-loader.git | master | 1e01cc16 | Fri Jun 30 01:16:04 2023 | unknown
sd-civitai-browser | https://github.com/Vetchems/sd-civitai-browser.git | main | dc1ff668 | Fri Apr 7 21:08:07 2023 | unknown
sd-webui-3d-open-pose-editor | https://github.com/nonnonstop/sd-webui-3d-open-pose-editor.git | main | f2d5aac5 | Sat Apr 15 13:21:06 2023 | unknown
sd-webui-animatediff | https://github.com/continue-revolution/sd-webui-animatediff.git | master | 19191b55 | Tue Aug 8 10:11:38 2023 | unknown
sd-webui-controlnet | https://github.com/Mikubill/sd-webui-controlnet.git | main | 4b815cc3 | Sat Aug 5 10:10:11 2023 | unknown
sd-webui-inpaint-anything | https://github.com/Uminosachi/sd-webui-inpaint-anything.git | main | f4699a10 | Sun Aug 13 13:03:07 2023 | unknown
sd-webui-mov2mov | https://github.com/Scholar01/sd-webui-mov2mov | master | 0ba11a1a | Wed Apr 19 08:44:24 2023 | unknown
sd-webui-openpose-editor | https://github.com/huchenlei/sd-webui-openpose-editor.git | main | d352f29e | Sat Jul 22 21:15:12 2023 | unknown
sd-webui-regional-prompter | https://github.com/hako-mikan/sd-webui-regional-prompter.git | main | e75f5b96 | Thu Aug 10 15:39:08 2023 | unknown
sd-webui-segment-anything | https://github.com/continue-revolution/sd-webui-segment-anything.git | master | 62ccb019 | Fri Aug 11 07:43:14 2023 | unknown
sd-webui-text2video | https://github.com/kabachuha/sd-webui-text2video.git | main | 5fc9f338 | Sun Aug 13 17:59:50 2023 | unknown
stable-diffusion-webui-composable-lora | https://github.com/a2569875/stable-diffusion-webui-composable-lora.git | main | a03d40eb | Wed Jul 26 08:58:15 2023 | unknown
stable-diffusion-webui-two-shot | https://github.com/ashen-sensored/stable-diffusion-webui-two-shot.git | main | 6b55dd52 | Sun Apr 2 11:24:25 2023 | unknown
ultimate-upscale-for-automatic1111 | https://github.com/Coyote-A/ultimate-upscale-for-automatic1111.git | master | c99f382b | Tue Jun 13 04:29:35 2023 | unknown
video_loopback_for_webui

</body>
</html>Anime4K	https://github.com/bloc97/Anime4K.git	master	[8e39551c](https://github.com/bloc97/Anime4K/commit/8e39551ce96ed172605c89b7dd8be855b5502cc9)	Sat May 27 01:50:10 2023	unknown
Auto-Photoshop-StableDiffusion-Plugin	https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin.git	master	[1ae31637](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/commit/1ae316373934183b75aaf59f918f1794343b22ee)	Sun Jul 16 10:08:10 2023	unknown
Stable-Diffusion-Webui-Civitai-Helper	https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper.git	main	[920ca326](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/commit/920ca3267f789a72e3225c99f069bf0be0db795d)	Tue May 23 11:53:22 2023	unknown
TemporalKit	https://github.com/CiaraStrawberry/TemporalKit	main	[3f5ef883](https://github.com/CiaraStrawberry/TemporalKit/commit/3f5ef8830badddc10029c97dab66018cfa3fa81a)	Sat Aug 5 13:32:45 2023	unknown
a1111-sd-webui-lycoris	https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris.git	main	[8e97bf54](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/commit/8e97bf54867c25d00fc480be1ab4dae5399b35ef)	Sun Jul 9 07:44:58 2023	unknown
adetailer	https://github.com/Bing-su/adetailer.git	main	[f18e00b4](https://github.com/Bing-su/adetailer/commit/f18e00b40826381352ab9d7ca75f7af85065a31b)	Mon Jul 31 12:03:01 2023	unknown
civitai-shortcut	https://github.com/sunnyark/civitai-shortcut.git	main	[4b3cf85d](https://github.com/sunnyark/civitai-shortcut/commit/4b3cf85d1f33cccd3cb4e41307ff4232cbde6369)	Thu Aug 10 23:50:09 2023	unknown
deforum-for-automatic1111-webui	https://github.com/deforum-art/deforum-for-automatic1111-webui.git	automatic1111-webui	[0949bf42](https://github.com/deforum-art/deforum-for-automatic1111-webui/commit/0949bf428d5ef9ce554e9cdcf5fc4190e2c1ba12)	Sun Aug 13 17:47:07 2023	unknown
gif2gif	https://github.com/LonicaMewinsky/gif2gif.git	main	[5121851e](https://github.com/LonicaMewinsky/gif2gif/commit/5121851e3941c420253f3a20a0f8e49bed86f0bb)	Sat May 13 14:56:04 2023	unknown
multidiffusion-upscaler-for-automatic1111	https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111.git	main	[f9f8073e](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/commit/f9f8073e64f4e682838f255215039ba7884553bf)	Sat Jul 22 06:53:11 2023	unknown
openpose-editor	https://github.com/fkunn1326/openpose-editor.git	master	[722bca6f](https://github.com/fkunn1326/openpose-editor/commit/722bca6fb9b062815d13b950e7040589abaec797)	Sat Jun 3 04:54:52 2023	unknown
posex	https://github.com/hnmr293/posex.git	master	[292f92d5](https://github.com/hnmr293/posex/commit/292f92d5068046f988fe002eb0a43b8841ad449e)	Wed May 3 08:59:57 2023	unknown
sd-3dmodel-loader	https://github.com/jtydhr88/sd-3dmodel-loader.git	master	[1e01cc16](https://github.com/jtydhr88/sd-3dmodel-loader/commit/1e01cc16c943594154558d92452e26b8f0156d7c)	Fri Jun 30 01:16:04 2023	unknown
sd-civitai-browser	https://github.com/Vetchems/sd-civitai-browser.git	main	[dc1ff668](https://github.com/Vetchems/sd-civitai-browser/commit/dc1ff6681556479042171fb5910d15e062e9baeb)	Fri Apr 7 21:08:07 2023	unknown
sd-webui-3d-open-pose-editor	https://github.com/nonnonstop/sd-webui-3d-open-pose-editor.git	main	[f2d5aac5](https://github.com/nonnonstop/sd-webui-3d-open-pose-editor/commit/f2d5aac51d891bc5f266b1549f3cf4495fc52160)	Sat Apr 15 13:21:06 2023	unknown
sd-webui-animatediff	https://github.com/continue-revolution/sd-webui-animatediff.git	master	[19191b55](https://github.com/continue-revolution/sd-webui-animatediff/commit/19191b55aaf4fce8b0c32de3fdae94d7a1fbd530)	Tue Aug 8 10:11:38 2023	unknown
sd-webui-controlnet	https://github.com/Mikubill/sd-webui-controlnet.git	main	[4b815cc3](https://github.com/Mikubill/sd-webui-controlnet/commit/4b815cc351ca5eeec489f573a9a6c2dbd47374d7)	Sat Aug 5 10:10:11 2023	unknown
sd-webui-inpaint-anything	https://github.com/Uminosachi/sd-webui-inpaint-anything.git	main	[f4699a10](https://github.com/Uminosachi/sd-webui-inpaint-anything/commit/f4699a108df970b278d973c7e99950c1559c9b45)	Sun Aug 13 13:03:07 2023	unknown
sd-webui-mov2mov	https://github.com/Scholar01/sd-webui-mov2mov	master	[0ba11a1a](https://github.com/Scholar01/sd-webui-mov2mov/commit/0ba11a1a759b724a021ac1dc6829a8f59b100f9c)	Wed Apr 19 08:44:24 2023	unknown
sd-webui-openpose-editor	https://github.com/huchenlei/sd-webui-openpose-editor.git	main	[d352f29e](https://github.com/huchenlei/sd-webui-openpose-editor/commit/d352f29edf71e88ae7ffc89a650bdfa169f2c8ab)	Sat Jul 22 21:15:12 2023	unknown
sd-webui-regional-prompter	https://github.com/hako-mikan/sd-webui-regional-prompter.git	main	[e75f5b96](https://github.com/hako-mikan/sd-webui-regional-prompter/commit/e75f5b9637dee8c1a1261c5197fe016be97c46c9)	Thu Aug 10 15:39:08 2023	unknown
sd-webui-segment-anything	https://github.com/continue-revolution/sd-webui-segment-anything.git	master	[62ccb019](https://github.com/continue-revolution/sd-webui-segment-anything/commit/62ccb01938face16480376ca5ef1a20d713972b7)	Fri Aug 11 07:43:14 2023	unknown
sd-webui-text2video	https://github.com/kabachuha/sd-webui-text2video.git	main	[5fc9f338](https://github.com/kabachuha/sd-webui-text2video/commit/5fc9f33821e0d7b69b98de2d7a556f2f9ece82b4)	Sun Aug 13 17:59:50 2023	unknown
stable-diffusion-webui-composable-lora	https://github.com/a2569875/stable-diffusion-webui-composable-lora.git	main	[a03d40eb](https://github.com/a2569875/stable-diffusion-webui-composable-lora/commit/a03d40eb3a3bc63728f46f1c00229310734c8fef)	Wed Jul 26 08:58:15 2023	unknown
stable-diffusion-webui-two-shot	https://github.com/ashen-sensored/stable-diffusion-webui-two-shot.git	main	[6b55dd52](https://github.com/ashen-sensored/stable-diffusion-webui-two-shot/commit/6b55dd5248fd07f55ffefbf9be369b439b239502)	Sun Apr 2 11:24:25 2023	unknown
ultimate-upscale-for-automatic1111	https://github.com/Coyote-A/ultimate-upscale-for-automatic1111.git	master	[c99f382b](https://github.com/Coyote-A/ultimate-upscale-for-automatic1111/commit/c99f382b31509b87b4d512e70e9caf08ae7a079f)	Tue Jun 13 04:29:35 2023	unknown
video_loopback_for_webui

### Console logs

```Shell
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:10<00:00,  1.87it/s]
2023-08-13 13:26:36,366 - ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: ().
*** Error running process: C:\AI\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py
    Traceback (most recent call last):
      File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 519, in process
        script.process(p, *script_args)
    TypeError: Script.process() missing 21 required positional arguments: 'enabled', 'method', 'overwrite_size', 'keep_input_size', 'image_width', 'image_height', 'tile_width', 'tile_height', 'overlap', 'tile_batch_size', 'upscaler_name', 'scale_factor', 'noise_inverse', 'noise_inverse_steps', 'noise_inverse_retouch', 'noise_inverse_renoise_strength', 'noise_inverse_renoise_kernel', 'control_tensor_cpu', 'enable_bbox_control', 'draw_background', and 'causal_layers'

---
*** Error running process: C:\AI\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\vae_optimize.py
    Traceback (most recent call last):
      File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 519, in process
        script.process(p, *script_args)
    TypeError: Script.process() missing 7 required positional arguments: 'enabled', 'encoder_tile_size', 'decoder_tile_size', 'vae_to_gpu', 'fast_decoder', 'fast_encoder', and 'color_fix'

---
*** Error running process: C:\AI\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\sam.py
    Traceback (most recent call last):
      File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 519, in process
        script.process(p, *script_args)
      File "C:\AI\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\sam.py", line 789, in process
        process_unit = SAMProcessUnit(args, is_img2img)
      File "C:\AI\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\process_params.py", line 63, in __init__
        self.sam_inpaint_unit = SAMInpaintUnit(args, is_img2img)
      File "C:\AI\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\process_params.py", line 25, in __init__
        self.init_sam_single_image_process(args)
      File "C:\AI\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\process_params.py", line 29, in init_sam_single_image_process
        self.inpaint_upload_enable      = args[0]
    IndexError: tuple index out of range

---
*** Error running process: C:\AI\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py
    Traceback (most recent call last):
      File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 519, in process
        script.process(p, *script_args)
    TypeError: Script.process() missing 19 required positional arguments: 'active', 'debug', 'rp_selected_tab', 'mmode', 'xmode', 'pmode', 'aratios', 'bratios', 'usebase', 'usecom', 'usencom', 'calcmode', 'nchangeand', 'lnter', 'lnur', 'threshold', 'polymask', 'lstop', and 'lstop_hr'

---
2023-08-13 13:26:36,368 - ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: ().
*** Error running process: C:\AI\stable-diffusion-webui\extensions\stable-diffusion-webui-composable-lora\scripts\composable_lora_script.py
    Traceback (most recent call last):
      File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 519, in process
        script.process(p, *script_args)
    TypeError: ComposableLoraScript.process() missing 7 required positional arguments: 'enabled', 'opt_composable_with_step', 'opt_uc_text_model_encoder', 'opt_uc_diffusion_model', 'opt_plot_lora_weight', 'opt_single_no_uc', and 'opt_hires_step_as_global'

---
*** Error running process: C:\AI\stable-diffusion-webui\extensions\stable-diffusion-webui-two-shot\scripts\two_shot.py
    Traceback (most recent call last):
      File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 519, in process
        script.process(p, *script_args)
      File "C:\AI\stable-diffusion-webui\extensions\stable-diffusion-webui-two-shot\scripts\two_shot.py", line 557, in process
        enabled, raw_divisions, raw_positions, raw_weights, raw_end_at_step, alpha_blend, *cur_weight_sliders = args
    ValueError: not enough values to unpack (expected at least 6, got 0)

---
*** Error running process_batch: C:\AI\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py
    Traceback (most recent call last):
      File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 543, in process_batch
        script.process_batch(p, *script_args, **kwargs)
    TypeError: Script.process_batch() missing 19 required positional arguments: 'active', 'debug', 'rp_selected_tab', 'mmode', 'xmode', 'pmode', 'aratios', 'bratios', 'usebase', 'usecom', 'usencom', 'calcmode', 'nchangeand', 'lnter', 'lnur', 'threshold', 'polymask', 'lstop', and 'lstop_hr'

---
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:08<00:00,  2.48it/s]
*** Error running postprocess_batch: C:\AI\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py
    Traceback (most recent call last):
      File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 559, in postprocess_batch
        script.postprocess_batch(p, *script_args, images=images, **kwargs)
    TypeError: Script.postprocess_batch() missing 1 required positional argument: 'enabled'

---
*** Error running postprocess: C:\AI\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py
    Traceback (most recent call last):
      File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 551, in postprocess
        script.postprocess(p, processed, *script_args)
    TypeError: Script.postprocess() missing 1 required positional argument: 'enabled'

---
*** Error running postprocess: C:\AI\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\vae_optimize.py
    Traceback (most recent call last):
      File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 551, in postprocess
        script.postprocess(p, processed, *script_args)
    TypeError: Script.postprocess() missing 1 required positional argument: 'enabled'
```

**Comment by inferno46n2** [comment]
I am having the same problem. Essentially can't even load the control net tabs just stuck in a forever loading loop on some and others don't load at all.

**Comment by MitPitt** [comment]
Same error. I fixed it by disabling every extension except deforum and controlnet. Then it works.
