### ISSUE TITLE
[Feature Request]: add an option for uploading a mask to a controlnet unit

### ISSUE THREAD

**Issue by Hugs288** [Mikubill/sd-webui-controlnet#1921]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

similar to img2img inpaint upload in a1111.
it would make controlnet compatible with custom masks or ones created by precise masking extensions like inpaint anything or segment anything.
https://github.com/Uminosachi/sd-webui-inpaint-anything
https://github.com/continue-revolution/sd-webui-segment-anything
I would highly appreciate it

### Steps to reproduce the problem

-

### What should have happened?

-

### Commit where the problem happens

-

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
-
```

### List of enabled extensions

-

### Console logs

```Shell
-
```

**Comment by huchenlei** [comment]
See https://github.com/Mikubill/sd-webui-controlnet/issues/1504 and https://github.com/Mikubill/sd-webui-controlnet/discussions/1312.
