### ISSUE TITLE
[Feature] Support Diffusers SDXL ControlNet models

### ISSUE THREAD

**Issue by dgcnz** [Mikubill/sd-webui-controlnet#1922]
Currently open-sourced SDXL 1.0 ControlNet models in HuggingFace trained by Diffusers:
* [Canny SDLX 1.0](https://huggingface.co/diffusers/controlnet-canny-sdxl-1.0)
* [Depth SDXL 1.0](https://huggingface.co/diffusers/controlnet-depth-sdxl-1.0)

**Comment by huchenlei** [comment]
We cannot support diffusers pipeline until A1111 fully supports it.

PRs are welcome (Both this repo and A1111 repo).

**Comment by huchenlei** [comment]
Closing this issue for now as there is already an discussion going on here:
#1658
