### ISSUE TITLE
[Feature] Support IP-Adapter

### ISSUE THREAD

**Issue by xiaohu2015** [Mikubill/sd-webui-controlnet#1927]
link: https://github.com/tencent-ailab/IP-Adapter
The image prompt adapter is designed to enable a pretrained text-to-image diffusion model to generate images with image prompt. IP-Adapter can be fully compatible with ControlNet.

**Comment by huchenlei** [comment]
It depends on diffusers so I don't expect we would port it until a1111 implements good support for diffusers.

**Comment by LiamTTT** [comment]
It seems that only the StableDiffusion process relies on diffusers. The main body of this method is based on torch (for IP adapter) and transformers (for CLIPImageEncoder)

**Comment by torridgristle** [comment]
It looks like it's generating image prompt embeds and using them like text prompt embeds. It doesn't seem to rely on anything from Diffusers for the actual image prompt part. Doesn't seem to modify the Diffusers model to work with the image prompts either.

**Comment by lllyasviel** [comment]
Basically, if codes (1) do not contain any dependency that needs compiled installation like mmcv/detectron, and (2) can be implemented by hacking the U-net, we should have no problem to make it work.

Nevertheless this will probably take a period of time for us to learn. If someone moves faster, help is also welcomed. (And we also welcome any contributions related to Prompt Free Diffusion.)

(And, although this @ is likely in vain, let me still try to @Mikubill )

Finally, we need to be very careful about implementing works under review. This is to avoid biases introduced in promotion, or biases from engineering mistakes. But recently Neurips reviewing seems ended and we can probably also work a bit more on some works from Neurips.

**Comment by toyxyz** [comment]
Here is a custom node that adds IP-adapter to Comfyui! 

https://github.com/laksjdjf/IPAdapter-ComfyUI

https://twitter.com/gcem156/status/1692142722625462378?s=20
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/8006000/d864b519-29bc-4218-9b51-a4172f177605)

**Comment by lllyasviel** [comment]
> Here is a custom node that adds IP-adapter to Comfyui!
> 


Wow this looks great! Interesting to see it generates a girl when the reference is a cabbage.

**Comment by toyxyz** [comment]
> > Here is a custom node that adds IP-adapter to Comfyui!
> 
> Wow this looks great! Interesting to see it generates a girl when the reference is a cabbage.

If the prompt is blank, the cabbage seems to be generated.

https://twitter.com/gcem156/status/1692070291617558802/photo/1
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/8006000/2e2eb6fe-293d-48b9-8421-77bdfb9ee9e0)
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/8006000/576ab60f-9d02-45ab-a725-37d29ee40424)

It worked well when I used it with an openpose Controlnet+WD 14 Tagger

![20230819122216183](https://github.com/Mikubill/sd-webui-controlnet/assets/8006000/f402b109-17b8-4b71-98d3-d8beed69245a)

**Comment by wandrzej** [comment]
> > Here is a custom node that adds IP-adapter to Comfyui!
> 
> Wow this looks great! Interesting to see it generates a girl when the reference is a cabbage.

I'd say '1girl' in the prompt does the trick, not to mention the checkpoint that probably is mostly finetuned for that purpose. 
IP adapter is actually quite promising, as it takes both text and image prompt, but can do contorlnet as well.

**Comment by lllyasviel** [comment]
Cool! let us take a look at this impl hopefully soon. And any related contribution is highly appreciated.

**Comment by ykk648** [comment]
animatediff + ipadapter in diffusers [ykk648/AnimateDiff](https://github.com/ykk648/AnimateDiff)   😬

**Comment by DarqueLilly** [comment]
@xiaohu2015 I don't see the instructions...

**Comment by LiamTTT** [comment]
> @xiaohu2015 I don't see the instructions...

https://github.com/Mikubill/sd-webui-controlnet/discussions/2039
