### ISSUE TITLE
[Bug]: Wrong colors in draw_bodypose

### ISSUE THREAD

**Issue by aschier** [Mikubill/sd-webui-controlnet#1928]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

The `draw_bodypose' function in https://github.com/Mikubill/sd-webui-controlnet/blob/4fa9190436e29dd7d88701b18a27330ef7743343/annotator/openpose/util.py#L81 uses the wrong colors for the generated OpenPose skeleton.

The problem is that https://github.com/Mikubill/sd-webui-controlnet/blob/4fa9190436e29dd7d88701b18a27330ef7743343/annotator/openpose/util.py#L110 specifies the correct RGB colors, but OpenCV uses BGR internally. Many operations on RGB arrays work correctly, but in the end `cv2.imwrite` saves images with wrong colors.

The problem may not be obvious, because when converting to PIL you usually need to do `img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)` for this reason, and if you use data from the RGB array that should be a BGR array and forget this call at the same time, the PIL image will be correct again.

### Steps to reproduce the problem

1. use `draw_bodypose`
2. Save the canvas using `cv2.imwrite`

### What should have happened?

The image should have the correct colors, e.g., an orange joint for the right shoulder (3rd vertex).

### Commit where the problem happens

webui: (not relevant)
controlnet: 4fa9190436e29dd7d88701b18a27330ef7743343

**Comment by aschier** [comment]
Here the colors list in BGR:
```python
    colors = [[0, 0, 255], [0, 85, 255], [0, 170, 255], [0, 255, 255], [0, 255, 170], [0, 255, 85], [0, 255, 0], \
              [85, 255, 0], [170, 255, 0], [255, 255, 0], [255, 170, 0], [255, 85, 0], [255, 0, 0], [255, 0, 85], \
              [255, 0, 170], [255, 0, 255], [170, 0, 255], [85, 0, 255]]
```

**Comment by huchenlei** [comment]
You should do the BGR RGB conversion when you call the function instead of making the function itself do BGR.

See example in
tests/annotator_tests/openpose_tests/openpose_e2e_test.py

**Comment by aschier** [comment]
> You should do the BGR RGB conversion when you call the function instead of making the function itself do BGR.

I did this in my code first, but then I decided to change it in my copy of this function for two reasons:
1) It is not obvious, that the function returns an RGB image, which is handled incorrectly by other OpenCV methods like `imwrite`. I first overlooked where the wrong colors are coming from myself and I think it is not obvious to other people reading the code as well.
2) You get an array for using with OpenCV, but not in the native OpenCV color order. While the function itself doesn't have a problem and converting it in the end fixes the colors, I wouldn't be sure if there aren't OpenCV functions which do not work correctly in the wrong colorspace.
When someone, for example, takes the image as output and then wants to set the B channel to zero in some post-processing, they will set the R channel to zero and later conversion back to the right colorspace won't recover the right color information.

So I think by the principle of least surprise it would be best to at least return the image as BGR (i.e. replace the return call with `return cv2.cvtColor(img, cv2.COLOR_RGB2BGR)`) which should work because none of the used primitives in your function depend on the color order, or document that the function returns an image that does not use the native color order of OpenCV.

I also find it confusing why OpenCV doesn't use RGB by default, but when I have to deal with it, I try to at least keep it consistant that all OpenCV images are in the OpenCV colorspace, so I don't have to think too much about it when working with other OpenCV functions that depend on the color order.
After some back and forth where to fix it I personally decided against converting the array in the end and replaced the colors array, so all primitives inside the function also work with the OpenCV colors, but for having the right result it doesn't matter if the array is replaced or the image is converted in the end.

It worksforme now, as I only use the single method and adapted it to how I use it, but I thought that others may have the same problem when they use the function.
It isn't directly obvious that it has another color order, especially since it is easy to overlook in the result, when one doesn't have another image with the correct colors next to it. A photo with wrong color order is easy to spot, but the skeletons seem to have almost the same colors, so it looks like the limbs are swapped and not the colors.

**Comment by huchenlei** [comment]
Here the images are in RGB because Gradio accepts images in that color format.

The annotator code is not bind to any image processing library. You can use anything you like to read/write images, not just opencv. We refuse to make the change just because one particular image processing library is using specific color format.
