### ISSUE TITLE
ModuleNotFoundError: No module named 'annotator.hed'

### ISSUE THREAD

**Issue by ekis93** [Mikubill/sd-webui-controlnet#193]
Hi. 

I am getting ModuleNotFoundError whenever I try to use any model, from canny.pth to seg.pth. It always throws ModuleNotFoundError (see file for full log). In this instance I used a blank canvas and scribbled some shapes onto it.

I've made sure to remove the webui-controlnet folder from the extentions and reinstall it from the github via url in the web-ui. I've applied the update and restarted. I am able to generate images with other extentions, so I don't think there's any issue with the Automatic111 install.

----
[Ny(tt) OpenDocument-text.odt](https://github.com/Mikubill/sd-webui-controlnet/files/10774713/Ny.tt.OpenDocument-text.odt)

Loading preprocessor: fake_scribble, model: control_sd15_scribble [fef5e48e]
Loaded state_dict from [D:\WUIREPO\stable-diffusion-webui\extensions\sd-webui-controlnet\models\control_sd15_scribble.pth]
ControlNet model control_sd15_scribble [fef5e48e] loaded.
using mask as input
Error running process: D:\WUIREPO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "D:\WUIREPO\stable-diffusion-webui\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "D:\WUIREPO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 482, in process
    detected_map = preprocessor(input_image, res=pres, thr_a=pthr_a, thr_b=pthr_b)
  File "D:\WUIREPO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 45, in fake_scribble
    result = hed(img, res)
  File "D:\WUIREPO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 33, in hed
    from annotator.hed import apply_hed
ModuleNotFoundError: No module named 'annotator.hed'

**Comment by ekis93** [comment]
Update: The issue seems to relate to the preprocessor only. I am able to create depthmaps and openPose through other extentions and use those with the models in sd-webui-controlnet, with the preprocessor set to None.

**Comment by shiranui1994** [comment]
Did u solve this problem? i have the same question, too.

**Comment by doskoi** [comment]
Check the root folder if the _annatator_ folder is exist, then move all content into extension/sd-webui-controlnet/annatator.
Becasue the annatator scripts is inside the extension folder. if the annatator folder under root but missing scripts will make this error.

**Comment by leadbreak** [comment]
I think this problem is due to system path. If you print sys.path in your code, maybe you wouldn't see controlnet extension path. So you should add that path, like this to controlnet init code.

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/71580035/65c7e208-3570-47f6-9b3f-639d3c1a3040)

Actually, I add this to preload.py in extensions/sd-webui-controlnet like this.

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/71580035/8a10dc2d-ce7b-46cd-ad5e-c07a51d1da83)

And it works for me.
