### ISSUE TITLE
[Bug]: loopback dosent work

### ISSUE THREAD

**Issue by revolverocelot1** [Mikubill/sd-webui-controlnet#1930]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

 im pretty sure i enabled it but the genrated image dosent go into control net

### Steps to reproduce the problem

enable loopback

### What should have happened?

the genrated image from img2img should be transferred into controlnet as base

### Commit where the problem happens

webui: 
controlnet: 
looback button

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
none
```

### List of enabled extensions

<html>
<body>

Extension | URL | Branch | Version | Date | Update
-- | -- | -- | -- | -- | --
Stable-Diffusion-WebUI-Image-Filters | https://github.com/Zuellni/Stable-Diffusion-WebUI-Image-Filters | main | 7b22bc06 | Thu May 18 13:44:54 2023 | unknown
Stable-Diffusion-Webui-Civitai-Helper | https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper | main | 920ca326 | Tue May 23 11:53:22 2023 | unknown
Umi-AI-debloat | https://github.com/Linaqruf/Umi-AI-debloat | master | 6195ba80 | Fri Jun 9 11:02:25 2023 | unknown
a1111-sd-webui-lycoris | https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris | main | 123d1da1 | Thu Jun 8 01:19:40 2023 | unknown
a1111-sd-webui-tagcomplete | https://github.com/DominikDoom/a1111-sd-webui-tagcomplete.git | main | 9b66d421 | Mon Jun 5 19:50:30 2023 | unknown
adetailer | https://github.com/Bing-su/adetailer | main | 76424252 | Mon Jun 5 05:32:16 2023 | unknown
batchlinks-webui | https://github.com/etherealxx/batchlinks-webui | main | d44bbb5e | Wed May 3 12:23:34 2023 | unknown
multidiffusion-upscaler-for-automatic1111 | https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111 | main | 70b3c5ea | Sun May 28 09:11:28 2023 | unknown
sd-civitai-browser | https://github.com/SignalFlagZ/sd-civitai-browser | mod | 0bd5c8c0 | Wed Jun 7 23:58:54 2023 | unknown
sd-dynamic-thresholding | https://github.com/mcmonkeyprojects/sd-dynamic-thresholding | master | f02cacfc | Mon May 22 14:20:30 2023 | unknown
sd-webui-additional-networks | https://github.com/kohya-ss/sd-webui-additional-networks.git | main | e9f3d622 | Tue May 23 12:31:15 2023 | unknown
sd-webui-aspect-ratio-helper | https://github.com/thomasasfk/sd-webui-aspect-ratio-helper.git | main | 99fcf9b0 | Sun Jun 4 15:39:07 2023 | unknown
sd-webui-controlnet | https://github.com/Mikubill/sd-webui-controlnet | main | 05e66969 | Fri Jun 9 05:50:02 2023 | unknown
sd-webui-cutoff | https://github.com/hnmr293/sd-webui-cutoff | main | 3a073e9c | Wed May 3 07:14:40 2023 | unknown
sd-webui-infinite-image-browsing | https://github.com/zanllp/sd-webui-infinite-image-browsing | main | 684dcb63 | Thu Jun 8 12:47:30 2023 | unknown
sd-webui-llul | https://github.com/hnmr293/sd-webui-llul | master | aa47b3ee | Thu May 4 16:14:34 2023 | unknown
sd-webui-regional-prompter | https://github.com/hako-mikan/sd-webui-regional-prompter | main | 1d179871 | Thu Jun 8 08:26:55 2023 | unknown
sd-webui-tunnels | https://github.com/camenduru/sd-webui-tunnels | main | 988edd1a | Fri May 19 15:49:54 2023 | unknown
sd_delete_button | https://github.com/AlUlkesh/sd_delete_button | main | fe1f0326 | Tue Mar 14 11:01:45 2023 | unknown
sd_webui_stealth_pnginfo | https://github.com/derrian-distro/sd_webui_stealth_pnginfo | main | 0a79d407 | Mon May 1 19:58:36 2023 | unknown
sdweb-merge-block-weighted-gui | https://github.com/bbc-mc/sdweb-merge-block-weighted-gui.git | master | 8a62a753 | Thu Jan 19 21:31:06 2023 | unknown
sdweb-xyplus | https://github.com/bbc-mc/sdweb-xyplus | master | 4198a6f6 | Mon Dec 19 13:46:56 2022 | unknown
stable-diffusion-webui-composable-lora | https://github.com/opparco/stable-diffusion-webui-composable-lora.git | main | d4963e48 | Mon Feb 27 17:40:08 2023 | unknown
stable-diffusion-webui-fix-image-paste | https://github.com/klimaleksus/stable-diffusion-webui-fix-image-paste | master | 2844e17e | Fri Feb 24 22:31:57 2023 | unknown
stable-diffusion-webui-model-toolkit | https://github.com/arenatemp/stable-diffusion-webui-model-toolkit | master | 4d8fea77 | Sun May 14 09:09:42 2023 | unknown
stable-diffusion-webui-state | https://github.com/ilian6806/stable-diffusion-webui-state | main | 8560a9c9 | Mon May 8 13:24:04 2023 | unknown
stable-diffusion-webui-two-shot | https://github.com/ashen-sensored/stable-diffusion-webui-two-shot | main | 6b55dd52 | Sun Apr 2 11:24:25 2023 | unknown
ultimate-upscale-for-automatic1111 | https://github.com/Coyote-A/ultimate-upscale-for-automatic1111.git | master | 756bb505 | Fri May 5 00:22:21 2023 | unknown
video_loopback_for_webui | https://github.com/fishslot/video_loopback_for_webui.git | main | 4e0bf8c5 | Fri Apr 21 12:08:15 2023 | unknown
LDSR | built-in | None |   | Thu Aug 17 17:05:18 2023 |  
Lora | built-in | None |   | Thu Aug 17 17:05:18 2023 |  
ScuNET | built-in | None |   | Thu Aug 17 17:05:18 2023 |  
SwinIR | built-in | None |   | Thu Aug 17 17:05:18 2023 |  
prompt-bracket-checker | built-in | None |   | Thu Aug 17 17:05:18 2023 |  

</body>
</html>Extension	URL	Branch	Version	Date	Update
Stable-Diffusion-WebUI-Image-Filters	https://github.com/Zuellni/Stable-Diffusion-WebUI-Image-Filters	main	[7b22bc06](https://github.com/Zuellni/Stable-Diffusion-WebUI-Image-Filters/commit/7b22bc06fee959f81c4aff914336dec1fdf73820)	Thu May 18 13:44:54 2023	unknown
Stable-Diffusion-Webui-Civitai-Helper	https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper	main	[920ca326](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/commit/920ca3267f789a72e3225c99f069bf0be0db795d)	Tue May 23 11:53:22 2023	unknown
Umi-AI-debloat	https://github.com/Linaqruf/Umi-AI-debloat	master	[6195ba80](https://github.com/Linaqruf/Umi-AI-debloat/commit/6195ba804dac7beba329e0c5a8640d682f6a0177)	Fri Jun 9 11:02:25 2023	unknown
a1111-sd-webui-lycoris	https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris	main	[123d1da1](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/commit/123d1da15d802823480f8020312ce449523f10e2)	Thu Jun 8 01:19:40 2023	unknown
a1111-sd-webui-tagcomplete	https://github.com/DominikDoom/a1111-sd-webui-tagcomplete.git	main	[9b66d421](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/commit/9b66d42111bd0cf0ac68596f9ee70c2b19982921)	Mon Jun 5 19:50:30 2023	unknown
adetailer	https://github.com/Bing-su/adetailer	main	[76424252](https://github.com/Bing-su/adetailer/commit/764242520cbba9c67f5a089d7baa8d04efa0df56)	Mon Jun 5 05:32:16 2023	unknown
batchlinks-webui	https://github.com/etherealxx/batchlinks-webui	main	[d44bbb5e](https://github.com/etherealxx/batchlinks-webui/commit/d44bbb5e2a043f2eed80c3945c0f2c676e41d0e5)	Wed May 3 12:23:34 2023	unknown
multidiffusion-upscaler-for-automatic1111	https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111	main	[70b3c5ea](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/commit/70b3c5ea3c9f684d04e7ff59167565974415735c)	Sun May 28 09:11:28 2023	unknown
sd-civitai-browser	https://github.com/SignalFlagZ/sd-civitai-browser	mod	[0bd5c8c0](https://github.com/SignalFlagZ/sd-civitai-browser/commit/0bd5c8c008e8329f21d03524a6560a0d88fd414e)	Wed Jun 7 23:58:54 2023	unknown
sd-dynamic-thresholding	https://github.com/mcmonkeyprojects/sd-dynamic-thresholding	master	[f02cacfc](https://github.com/mcmonkeyprojects/sd-dynamic-thresholding/commit/f02cacfc923e8bbf73f25327d722d50c458d66bb)	Mon May 22 14:20:30 2023	unknown
sd-webui-additional-networks	https://github.com/kohya-ss/sd-webui-additional-networks.git	main	[e9f3d622](https://github.com/kohya-ss/sd-webui-additional-networks/commit/e9f3d622b5a98650008a685ea23b27eb810da35a)	Tue May 23 12:31:15 2023	unknown
sd-webui-aspect-ratio-helper	https://github.com/thomasasfk/sd-webui-aspect-ratio-helper.git	main	[99fcf9b0](https://github.com/thomasasfk/sd-webui-aspect-ratio-helper/commit/99fcf9b0a4e3f8c8cac07b12d17b66f12297b828)	Sun Jun 4 15:39:07 2023	unknown
sd-webui-controlnet	https://github.com/Mikubill/sd-webui-controlnet	main	[05e66969](https://github.com/Mikubill/sd-webui-controlnet/commit/05e669696d119aa4a8e228a3743a773e363fabee)	Fri Jun 9 05:50:02 2023	unknown
sd-webui-cutoff	https://github.com/hnmr293/sd-webui-cutoff	main	[3a073e9c](https://github.com/hnmr293/sd-webui-cutoff/commit/3a073e9c4525c21b72ae4645125768457c9c98e1)	Wed May 3 07:14:40 2023	unknown
sd-webui-infinite-image-browsing	https://github.com/zanllp/sd-webui-infinite-image-browsing	main	[684dcb63](https://github.com/zanllp/sd-webui-infinite-image-browsing/commit/684dcb63fae43ca8edefc3f98c9ee6b7f4845b75)	Thu Jun 8 12:47:30 2023	unknown
sd-webui-llul	https://github.com/hnmr293/sd-webui-llul	master	[aa47b3ee](https://github.com/hnmr293/sd-webui-llul/commit/aa47b3eeb45c53f0d6ccaae59abf36e8ed6731f5)	Thu May 4 16:14:34 2023	unknown
sd-webui-regional-prompter	https://github.com/hako-mikan/sd-webui-regional-prompter	main	[1d179871](https://github.com/hako-mikan/sd-webui-regional-prompter/commit/1d1798716969ca6a7112e102ecf997ea3bf6de77)	Thu Jun 8 08:26:55 2023	unknown
sd-webui-tunnels	https://github.com/camenduru/sd-webui-tunnels	main	[988edd1a](https://github.com/camenduru/sd-webui-tunnels/commit/988edd1a579184b2fa3e35d68f718f7c62427132)	Fri May 19 15:49:54 2023	unknown
sd_delete_button	https://github.com/AlUlkesh/sd_delete_button	main	[fe1f0326](https://github.com/AlUlkesh/sd_delete_button/commit/fe1f032603982c03042fe2a758fe65066b9d1242)	Tue Mar 14 11:01:45 2023	unknown
sd_webui_stealth_pnginfo	https://github.com/derrian-distro/sd_webui_stealth_pnginfo	main	[0a79d407](https://github.com/derrian-distro/sd_webui_stealth_pnginfo/commit/0a79d407bbcd7cedd872288436deab765e2c799f)	Mon May 1 19:58:36 2023	unknown
sdweb-merge-block-weighted-gui	https://github.com/bbc-mc/sdweb-merge-block-weighted-gui.git	master	[8a62a753](https://github.com/bbc-mc/sdweb-merge-block-weighted-gui/commit/8a62a753e791a75273863dd04958753f0df7532f)	Thu Jan 19 21:31:06 2023	unknown
sdweb-xyplus	https://github.com/bbc-mc/sdweb-xyplus	master	[4198a6f6](https://github.com/bbc-mc/sdweb-xyplus/commit/4198a6f6c8e735f4fb25a8482d4bac139a2f81cc)	Mon Dec 19 13:46:56 2022	unknown
stable-diffusion-webui-composable-lora	https://github.com/opparco/stable-diffusion-webui-composable-lora.git	main	[d4963e48](https://github.com/opparco/stable-diffusion-webui-composable-lora/commit/d4963e487c55e2adb292fa2021fa5c05bf169a7d)	Mon Feb 27 17:40:08 2023	unknown
stable-diffusion-webui-fix-image-paste	https://github.com/klimaleksus/stable-diffusion-webui-fix-image-paste	master	[2844e17e](https://github.com/klimaleksus/stable-diffusion-webui-fix-image-paste/commit/2844e17e2806ed5bc76831b27f947909060d0aac)	Fri Feb 24 22:31:57 2023	unknown
stable-diffusion-webui-model-toolkit	https://github.com/arenatemp/stable-diffusion-webui-model-toolkit	master	[4d8fea77](https://github.com/arenatemp/stable-diffusion-webui-model-toolkit/commit/4d8fea77dba5643439691c1c6b003db4d330ff0b)	Sun May 14 09:09:42 2023	unknown
stable-diffusion-webui-state	https://github.com/ilian6806/stable-diffusion-webui-state	main	[8560a9c9](https://github.com/ilian6806/stable-diffusion-webui-state/commit/8560a9c9ebd3eefc63008f173db69b3168df3a2e)	Mon May 8 13:24:04 2023	unknown
stable-diffusion-webui-two-shot	https://github.com/ashen-sensored/stable-diffusion-webui-two-shot	main	[6b55dd52](https://github.com/ashen-sensored/stable-diffusion-webui-two-shot/commit/6b55dd5248fd07f55ffefbf9be369b439b239502)	Sun Apr 2 11:24:25 2023	unknown
ultimate-upscale-for-automatic1111	https://github.com/Coyote-A/ultimate-upscale-for-automatic1111.git	master	[756bb505](https://github.com/Coyote-A/ultimate-upscale-for-automatic1111/commit/756bb50573ccc86ad2620b49f01f46d91a6fd682)	Fri May 5 00:22:21 2023	unknown
video_loopback_for_webui	https://github.com/fishslot/video_loopback_for_webui.git	main	[4e0bf8c5](https://github.com/fishslot/video_loopback_for_webui/commit/4e0bf8c5b8dcf566b9f4f7ad8bc87fa9af0bba59)	Fri Apr 21 12:08:15 2023	unknown
LDSR	[built-in](https://5c3c9561-9529-45b0.gradio.live/?__theme=dark)	None		Thu Aug 17 17:05:18 2023	
Lora	[built-in](https://5c3c9561-9529-45b0.gradio.live/?__theme=dark)	None		Thu Aug 17 17:05:18 2023	
ScuNET	[built-in](https://5c3c9561-9529-45b0.gradio.live/?__theme=dark)	None		Thu Aug 17 17:05:18 2023	
SwinIR	[built-in](https://5c3c9561-9529-45b0.gradio.live/?__theme=dark)	None		Thu Aug 17 17:05:18 2023	
prompt-bracket-checker	[built-in](https://5c3c9561-9529-45b0.gradio.live/?__theme=dark)	None		Thu Aug 17 17:05:18 2023

### Console logs

```Shell
none
```

**Comment by Rokonuxa** [comment]
It appears that the loopback option does not do what one would intuit from its similarity to the inbuilt loopback script.
Its purpose is apparently to simply help with the processing of videos/image sequences that already exist, not feeding the last result into controlnet with every processed image.

**Comment by ljleb** [comment]
Unless the code changed or stopped working, loopback is a batch-only parameter that will take the last generated image *during the batch* and use it as the new controlmap after passing the preprocessor. The intent was to support temporalnet v1, a controlnet that makes processing video a little bit more consistent, although the checkbox can also be ticked for other models.
