### ISSUE TITLE
[Bug]: ControlNet adds 2 minutes to the launch time of A1111 WebUI

### ISSUE THREAD

**Issue by TheRealPhooney** [Mikubill/sd-webui-controlnet#1931]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I updated a few extensions all at once a couple of days ago, including Controlnet.  While using it today I noticed a much higher RAM usage than normal, and certain aspects of the WebUI were noticeably sluggish, such as clicking through to view each of the images when generating in a batch of 8.  Generation times were at about 10 it/s too, down from ~20 on the same settings.

So I restarted A1111, which freed up all the RAM, but this is when I first noticed just how long it was taking to start up, 157 seconds, which felt a lot longer than what it was previously.  In an effort to find out which extension was causing the problem, I started removing extensions from the extension folder one by one, starting with all the extensions I had updated most recently, and testing the startup time.  When I removed Controlnet, startup time dropped down to about 20 seconds, when I added Controlnet back, startup time jumped back up to 150+ seconds.

Lookting in the CLI, the only messages I can see about Controlnet each time I startup are as follows:

Installing sd-webui-controlnet requirement: changing opencv-python version from 4.7.0.72 to 4.8.0

2023-08-18 21:10:24,007 - ControlNet - INFO - ControlNet v1.1.238
ControlNet preprocessor location: C:\Users\itsame\Documents\StableDiffusion\stable-diffusion-webui-master2\webui\extensions\sd-webui-controlnet\annotator\downloads
2023-08-18 21:10:24,088 - ControlNet - INFO - ControlNet v1.1.238

Specs are 11900k, 64gb RAM, RTX4090
Launching Web UI with arguments: --opt-sdp-attention --api

### Steps to reproduce the problem

1. run webui-user.bat

### What should have happened?

Don't take almost 3 minutes to startup, like it used to a few days ago.  Also I suspect CN is the culprit behind that strange RAM usage and the slowdown of the image generation, but I can't put my finger on it.

### Commit where the problem happens

webui: 68f336bd994bed5442ad95bad6b6ad5564a5409a
controlnet: 1.1.238

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
Launching Web UI with arguments: --opt-sdp-attention --api
```

### List of enabled extensions

<html>
<body>

Extension | URL | Branch | Version | Date | Update
-- | -- | -- | -- | -- | --
a1111-sd-webui-lycoris | https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris.git | main | 8e97bf54 | Sun Jul 9 07:44:58 2023 | unknown
ebsynth_utility | https://github.com/s9roll7/ebsynth_utility.git | main | 3858f120 | Mon Aug 14 06:40:28 2023 | unknown
model-keyword | https://github.com/mix1009/model-keyword.git | main | 2a70e4c0 | Thu Aug 17 18:01:07 2023 | unknown
multidiffusion-upscaler-for-automatic1111 | https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111.git | main | f9f8073e | Sat Jul 22 06:53:11 2023 | unknown
openOutpaint-webUI-extension | https://github.com/zero01101/openOutpaint-webUI-extension.git | main | 726652f2 | Sat Aug 12 18:46:03 2023 | unknown
openpose-editor | https://github.com/fkunn1326/openpose-editor.git | master | 722bca6f | Sat Jun 3 04:54:52 2023 | unknown
sd-webui-controlnet | https://github.com/Mikubill/sd-webui-controlnet.git | main | 0cfc88b6 | Mon Aug 14 00:07:03 2023 | unknown
sd-webui-inpaint-anything | https://github.com/Uminosachi/sd-webui-inpaint-anything.git | main | 76818e7d | Thu Aug 17 10:55:12 2023 | unknown
sd-webui-segment-anything | https://github.com/continue-revolution/sd-webui-segment-anything.git | master | 62ccb019 | Fri Aug 11 07:43:14 2023 | unknown
stable-diffusion-webui-rembg | https://github.com/AUTOMATIC1111/stable-diffusion-webui-rembg.git | master | 3d9eedbb | Sun Jun 4 13:35:24 2023 | unknown
stable-diffusion-webui-two-shot | https://github.com/ashen-sensored/stable-diffusion-webui-two-shot.git | main | 6b55dd52 | Sun Apr 2 11:24:25 2023 | unknown
ultimate-upscale-for-automatic1111 | https://github.com/Coyote-A/ultimate-upscale-for-automatic1111.git | master | c99f382b | Tue Jun 13 04:29:35 2023 | unknown

</body>
</html>Extension	URL	Branch	Version	Date	Update
a1111-sd-webui-lycoris	https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris.git	main	[8e97bf54](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/commit/8e97bf54867c25d00fc480be1ab4dae5399b35ef)	Sun Jul 9 07:44:58 2023	unknown
ebsynth_utility	https://github.com/s9roll7/ebsynth_utility.git	main	[3858f120](https://github.com/s9roll7/ebsynth_utility/commit/3858f120a459edfded69ab9a0b4f37978ec87c07)	Mon Aug 14 06:40:28 2023	unknown
model-keyword	https://github.com/mix1009/model-keyword.git	main	[2a70e4c0](https://github.com/mix1009/model-keyword/commit/2a70e4c0aea98b2eb9ec11e0d68a44652f3ae1b4)	Thu Aug 17 18:01:07 2023	unknown
multidiffusion-upscaler-for-automatic1111	https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111.git	main	[f9f8073e](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/commit/f9f8073e64f4e682838f255215039ba7884553bf)	Sat Jul 22 06:53:11 2023	unknown
openOutpaint-webUI-extension	https://github.com/zero01101/openOutpaint-webUI-extension.git	main	[726652f2](https://github.com/zero01101/openOutpaint-webUI-extension/commit/726652f23de7725d51e3296c97517849e9405fa6)	Sat Aug 12 18:46:03 2023	unknown
openpose-editor	https://github.com/fkunn1326/openpose-editor.git	master	[722bca6f](https://github.com/fkunn1326/openpose-editor/commit/722bca6fb9b062815d13b950e7040589abaec797)	Sat Jun 3 04:54:52 2023	unknown
sd-webui-controlnet	https://github.com/Mikubill/sd-webui-controlnet.git	main	[0cfc88b6](https://github.com/Mikubill/sd-webui-controlnet/commit/0cfc88b6a892076d199e68c02e9c306ac6ab2ead)	Mon Aug 14 00:07:03 2023	unknown
sd-webui-inpaint-anything	https://github.com/Uminosachi/sd-webui-inpaint-anything.git	main	[76818e7d](https://github.com/Uminosachi/sd-webui-inpaint-anything/commit/76818e7d4f9d35195dee83560a04c732d0158809)	Thu Aug 17 10:55:12 2023	unknown
sd-webui-roop-uncensored	https://github.com/P2Enjoy/sd-webui-roop-uncensored.git	main	[a86c3221](https://github.com/P2Enjoy/sd-webui-roop-uncensored/commit/a86c32219bf9c2356ec27b2182df8d9899b4efc8)	Wed Jun 28 11:14:25 2023	unknown
sd-webui-segment-anything	https://github.com/continue-revolution/sd-webui-segment-anything.git	master	[62ccb019](https://github.com/continue-revolution/sd-webui-segment-anything/commit/62ccb01938face16480376ca5ef1a20d713972b7)	Fri Aug 11 07:43:14 2023	unknown
stable-diffusion-webui-rembg	https://github.com/AUTOMATIC1111/stable-diffusion-webui-rembg.git	master	[3d9eedbb](https://github.com/AUTOMATIC1111/stable-diffusion-webui-rembg/commit/3d9eedbbf0d585207f97d5b21e42f32c0042df70)	Sun Jun 4 13:35:24 2023	unknown
stable-diffusion-webui-two-shot	https://github.com/ashen-sensored/stable-diffusion-webui-two-shot.git	main	[6b55dd52](https://github.com/ashen-sensored/stable-diffusion-webui-two-shot/commit/6b55dd5248fd07f55ffefbf9be369b439b239502)	Sun Apr 2 11:24:25 2023	unknown
ultimate-upscale-for-automatic1111	https://github.com/Coyote-A/ultimate-upscale-for-automatic1111.git	master	[c99f382b](https://github.com/Coyote-A/ultimate-upscale-for-automatic1111/commit/c99f382b31509b87b4d512e70e9caf08ae7a079f)	Tue Jun 13 04:29:35 2023	unknown

### Console logs

```Shell
2023-08-18 21:10:24,007 - ControlNet - INFO - ControlNet v1.1.238
ControlNet preprocessor location: C:\Users\itsame\Documents\StableDiffusion\stable-diffusion-webui-master2\webui\extensions\sd-webui-controlnet\annotator\downloads
2023-08-18 21:10:24,088 - ControlNet - INFO - ControlNet v1.1.238
```

**Comment by huchenlei** [comment]
Following line is trying to upgrade your opencv to 4.8.0, which is a one time effort.

```
Installing sd-webui-controlnet requirement: changing opencv-python version from 4.7.0.72 to 4.8.0
```

You should not see it everytime you startup, unless you have an extension trying to downgrade opencv to an older version.

**Comment by TheRealPhooney** [comment]
OK, I've done some more updates and the startup issue has been resolved, sorry for wasting anybody's time.  There does still seem to be a memory leak somewhere in there... but I have no reason to think it's Controlnet.  Thanks for your help.
