### ISSUE TITLE
[DevTask] Support Stability AI's Control-LoRA for SDXL

### ISSUE THREAD

**Issue by huchenlei** [Mikubill/sd-webui-controlnet#1933]
Stability released the official ControlNet support for SDXL here:
https://huggingface.co/stabilityai/control-lora

Instead of 5GB original size model, they now offer option of ~800MB M size model and ~400MB S size model.

Stability's implementation in SwarmUI relies on Comfy's implementation here:
https://github.com/comfyanonymous/ComfyUI/commit/d6e4b342e6171e0c89fed1ec9998b608888af401

We should try to port the change here.

**Comment by huchenlei** [comment]
I took some time studying Comfy's impl. It seems like the main change to support ControlNet LoRA is replacing all calls of `linear`, `conv_nd` with following custom impl that accounts `up` and `down` tensors.

```python
# linear forward
def forward(self, input):
            if self.up is not None:
                return torch.nn.functional.linear(input, self.weight + (torch.mm(self.up.flatten(start_dim=1), self.down.flatten(start_dim=1))).reshape(self.weight.shape).type(self.weight.dtype), self.bias)
            else:
                return torch.nn.functional.linear(input, self.weight, self.bias)
```

```python
# conv_2d forward
def forward(self, input):
            if self.up is not None:
                return torch.nn.functional.conv2d(input, self.weight + (torch.mm(self.up.flatten(start_dim=1), self.down.flatten(start_dim=1))).reshape(self.weight.shape).type(self.weight.dtype), self.bias, self.stride, self.padding, self.dilation, self.groups)
            else:
                return torch.nn.functional.conv2d(input, self.weight, self.bias, self.stride, self.padding, self.dilation, self.groups)
```

Those callsites are not only in Comfy's ControlNet specific code, but also `ldm` code. I am not sure how should we handle that here, maybe we should also have a modified copy of ldm code? @lllyasviel

**Comment by lllyasviel** [comment]
> I took some time studying Comfy's impl. It seems like the main change to support ControlNet LoRA is replacing all calls of `linear`, `conv_nd` with following custom impl that accounts `up` and `down` tensors.
> 
> ```python
> # linear forward
> def forward(self, input):
>             if self.up is not None:
>                 return torch.nn.functional.linear(input, self.weight + (torch.mm(self.up.flatten(start_dim=1), self.down.flatten(start_dim=1))).reshape(self.weight.shape).type(self.weight.dtype), self.bias)
>             else:
>                 return torch.nn.functional.linear(input, self.weight, self.bias)
> ```
> 
> ```python
> # conv_2d forward
> def forward(self, input):
>             if self.up is not None:
>                 return torch.nn.functional.conv2d(input, self.weight + (torch.mm(self.up.flatten(start_dim=1), self.down.flatten(start_dim=1))).reshape(self.weight.shape).type(self.weight.dtype), self.bias, self.stride, self.padding, self.dilation, self.groups)
>             else:
>                 return torch.nn.functional.conv2d(input, self.weight, self.bias, self.stride, self.padding, self.dilation, self.groups)
> ```
> 
> Those callsites are not only in Comfy's ControlNet specific code, but also `ldm` code. I am not sure how should we handle that here, maybe we should also have a modified copy of ldm code? @lllyasviel

is that making a controlnet by adding lora to layers, or directly adding lora to layers for control?

**Comment by huchenlei** [comment]
According to Comfy's commit message, it seems like a mechanism to compress weights to smaller matrix. The modifyed `linear` and `conv_2d` are decompressing those `up` and `down` tensors.

Comfy's commit message:
```
Control loras are controlnets where some of the weights are stored in
"lora" format: an up and a down low rank matrice that when multiplied
together and added to the unet weight give the controlnet weight.
```

**Comment by lllyasviel** [comment]
the difference is that do we have another overhead of controlnet vram

**Comment by huchenlei** [comment]
Going to do some testing on Comfy UI to find that out.

**Comment by huchenlei** [comment]
I performed following tests:
- Generate with M size 800M canny model: 11.0 GB peak VRAM usage
- Generate with S size 400M canny model: 10.6 GB peak VRAM usage
- Generate with Full size 5GB diffusers canny model: 12.5 GB peak VRAM usage
- Generate with No ControlNet models: 10.1 GB peak VRAM usage

I think they are doing the correct thing on controlling VRAM footprint. The LoRA weights are loaded into VRAM, not the full decompressed weights, and the decompression is dynamic during inference.

**Comment by lllyasviel** [comment]
interesting. hopefully will take a look

**Comment by huchenlei** [comment]
Note:
Comfy uses following lines for `ControlNetConfig`:
```python
        controlnet_config = model.model_config.unet_config.copy()
        controlnet_config.pop("out_channels")
        controlnet_config["hint_channels"] = self.control_weights["input_hint_block.0.weight"].shape[1]
```

Dump
```python
{
    "use_checkpoint": False,
    "image_size": 32,
    "use_spatial_transformer": True,
    "legacy": False,
    "num_classes": "sequential",
    "adm_in_channels": 2816,
    "use_fp16": True,
    "in_channels": 4,
    "model_channels": 320,
    "num_res_blocks": 2,
    "attention_resolutions": [
        2,
        4
    ],
    "transformer_depth": [
        0,
        2,
        10
    ],
    "channel_mult": [
        1,
        2,
        4
    ],
    "transformer_depth_middle": 10,
    "use_linear_in_transformer": True,
    "context_dim": 2048,
    "num_heads": -1,
    "num_head_channels": 64,
    "hint_channels": 3
}
```
