### ISSUE TITLE
error occurs when importing external_code from sd webui scripts

### ISSUE THREAD

**Issue by AK2806** [Mikubill/sd-webui-controlnet#1949]
I wrote a script for sd-webui and want to use the function of controlnet, so I did as the document saying
```PYTHON
import importlib
external_code = importlib.import_module('extensions.sd-webui-controlnet.scripts.external_code', 'external_code')
```
But error occurs while starting up sd:
```
 File "C:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\external_code.py", line 1, in <module>
        from internal_controlnet.external_code import *
    ModuleNotFoundError: No module named 'internal_controlnet'
```
So how can I fix it or it‘s still not supported on sd-webui-controlnet?

**Comment by AK2806** [comment]
It's a bug that made by my script. This problem just fixed easily by importing external_code in the constructor of script class.

> Seems it works when importing as an instance variable, but another error occurs while generating image
> 
> ```
> *** Error running process: C:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
>     Traceback (most recent call last):
>       File "C:\stable-diffusion-webui\modules\scripts.py", line 519, in process
>         script.process(p, *script_args)
>       File "C:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 756, in process
>         input_image, image_from_a1111 = Script.choose_input_image(p, unit, idx)
>       File "C:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 643, in choose_input_image
>         input_image = HWC3(image['image'])
>       File "C:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\util.py", line 6, in HWC3
>         assert x.dtype == np.uint8
>       File "C:\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 528, in __getattr__
>         raise AttributeError(name)
>     AttributeError: dtype
> ```

**Comment by flysssss** [comment]
Hello, I have encountered the same problem. Can your program work well.

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/100752067/824160ae-8f63-4489-9305-6f32d4cc9759)
