### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by CryptoCoinTrader** [Mikubill/sd-webui-controlnet#1953]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I am new to stable diffusion but seasoned with Midjourney and Leonardo. I successfully install Automatic 1111 and several new extensions but I could not load Controlnet from Github.

This is what every recent tutorial refereed me to for the webUi:

https://github.com/Mikubill/sd-webui-controlnet.git

The error is stated like this:

JSONDecodeError: Expecting value: line 8 column 1 (char 7)

Can you help me resolve the issue?

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

see above

### Commit where the problem happens

webui: 
controlnet: 

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
JSONDecodeError: Expecting value: line 8 column 1 (char 7)
```

### List of enabled extensions

see above

### Console logs

```Shell
see above
```

### Additional information

see above

**Comment by huchenlei** [comment]
Closing for lack of context. Please file a new issue with more information.
