### ISSUE TITLE
[Bug]: Latest version of ControlNet (23/08/23) doesn't automatically add the 'active' image to ControlNet

### ISSUE THREAD

**Issue by LemzoCreative** [Mikubill/sd-webui-controlnet#1955]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I've been using ControlNet for a few months now. I decided to update today to the latest version and I noticed that the images I generate with A1111 don't automatically get added to my ControlNet anymore when I'm in IMG2IMG. 
I found the Loopback option, but it doesn't seem to work..

### Steps to reproduce the problem

1. Generate an image with A1111 and send to IMG2IMG 
2. Open ControlNet and look for the image automatically added to ControlNet
3. See that it hasn't been added

### What should have happened?

It should have been added to ControlNet automatically.

### Commit where the problem happens

webui: version 1.3.2
controlnet: [fb000270]

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
x
```

### List of enabled extensions

<img width="266" alt="Screen Shot 2023-08-23 at 21 15 48" src="https://github.com/Mikubill/sd-webui-controlnet/assets/143029923/169033b1-55b8-42a7-9454-f0761eebad77">

### Console logs

```Shell
X
```

**Comment by huchenlei** [comment]
The A1111 img2img fallback image preview feature was removed in https://github.com/Mikubill/sd-webui-controlnet/pull/1941.

It's lllyasviel's decision. You can see our discussion in that thread.

**Comment by lllyasviel** [comment]
This is updated again recently https://github.com/Mikubill/sd-webui-controlnet/pull/1956
