### ISSUE TITLE
[Bug]: infotext error

### ISSUE THREAD

**Issue by Lucifer-101** [Mikubill/sd-webui-controlnet#1966]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

today I try to run controlnet v311
and it give me infotext error
it was working fine at v306

### Steps to reproduce the problem

...

### What should have happened?

...

### Commit where the problem happens

webui: python: 3.10.12  •  torch: 1.13.1+cu116  •  xformers: 0.0.16  •  gradio: 3.16.2  •  commit: [0cc0ee1b] •  checkpoint: 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
...
```

### List of enabled extensions

...

### Console logs

```Shell
Error running process: /content/ui/extensions/sd-Webui-controlnet/scripts/controlnet.pyTraceback (most recent call last):  File "/content/ui/modules/scripts.py", line 386, in process    script.process(p, *script_args)  File "/content/ui/extensions/sd-Webui-controlnet/scripts/controlnet.py", line 702, in process    self.enabled_units = Script.get_enabled_units(p)  File "/content/ui/extensions/sd-Webui-controlnet/scripts/controlnet.py", line 582, in get_enabled_units    Infotext.write_infotext(enabled_units, p)  File "/content/ui/extensions/sd-Webui-controlnet/scripts/infotext.py", line 91, in write_infotext    {  File "/content/ui/extensions/sd-Webui-controlnet/scripts/infotext.py", line 92, in <dictcomp>    Infotext.unit_prefix(i): serialize_unit(unit)  File "/content/ui/extensions/sd-Webui-controlnet/scripts/infotext.py", line 39, in serialize_unit    assert all("," not in str(v) and ":" not in str(v) for v in log_value.values())AssertionError
```

**Comment by huchenlei** [comment]
Can you screenshot your ControlNet generation setup?

The assertion triggered because I was assuming there should not be `,` or `:` in the values, so that parsing can be straightforward.

**Comment by huchenlei** [comment]
The new infotext format should look like:
`Module: depth_midas, Model: control_v11f1p_sd15_depth [cfd03158], Weight: 1, Resize Mode: Crop and Resize, Low Vram: False, Processor Res: 512, Guidance Start: 0, Guidance End: 1, Pixel Perfect: False, Control Mode: Balanced`

The only field that could contain the illegal char here is the model field, as it contains the file name as part of the value. Are you using a custom ControlNet model that contains `,`/`:` in its name?

**Comment by Lucifer-101** [comment]
my setup never change from what iam using at v306 
--------
after ur update, this is the new log
--
This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
2023-08-24 13:52:20,092 - ControlNet - ERROR - Unexpected tokens encountered:
{'Module': 'lineart_standard (from white bg & black line)', 'Model': 'control_v11p_sd15_lineart [43d4be0d]', 'Weight': 1, 'Resize Mode': 'Crop and Resize', 'Low Vram': False, 'Processor Res': 512, 'Threshold B': {'visible': False, 'interactive': False, 'minimum': -1, 'maximum': -1, 'value': -1}, 'Guidance Start': 0, 'Guidance End': 1, 'Pixel Perfect': True, 'Control Mode': 'Balanced'}
2023-08-24 13:52:20,565 - ControlNet - INFO - Loading model: control_v11p_sd15_lineart [43d4be0d]
2023-08-24 13:52:27,722 - ControlNet - INFO - Loaded state_dict from [/content/ui/extensions/sd-Webui-controlnet/models/control_v11p_sd15_lineart.pth]
2023-08-24 13:52:27,722 - ControlNet - INFO - Loading config: /content/ui/extensions/sd-Webui-controlnet/models/control_v11p_sd15_lineart.yaml
2023-08-24 13:52:33,846 - ControlNet - INFO - ControlNet model control_v11p_sd15_lineart [43d4be0d] loaded.
2023-08-24 13:52:33,898 - ControlNet - INFO - Loading preprocessor: lineart_standard
2023-08-24 13:52:33,898 - ControlNet - INFO - preprocessor resolution = 384
Error running process: /content/ui/extensions/sd-Webui-controlnet/scripts/controlnet.py
Traceback (most recent call last):
  File "/content/ui/modules/scripts.py", line 386, in process
    script.process(p, *script_args)
  File "/content/ui/extensions/sd-Webui-controlnet/scripts/controlnet.py", line 834, in process
    detected_map, is_image = preprocessor(
  File "/content/ui/extensions/sd-Webui-controlnet/scripts/utils.py", line 79, in decorated_func
    return cached_func(*args, **kwargs)
TypeError: unhashable type: 'dict'

  0% 0/20 [00:00<?, ?it/s]
  5% 1/20 [00:08<02:43,  8.61s/it]
 15% 3/20 [00:08<00:34,  2.03s/it]
 25% 5/20 [00:09<00:12,  1.16it/s]
 30% 6/20 [00:09<00:08,  1.62it/s]
 35% 7/20 [00:09<00:05,  2.17it/s]
 40% 8/20 [00:09<00:04,  2.80it/s]
 45% 9/20 [00:09<00:03,  3.49it/s]
 50% 10/20 [00:09<00:02,  4.20it/s]
 55% 11/20 [00:09<00:01,  4.85it/s]
 60% 12/20 [00:10<00:01,  5.37it/s]
 65% 13/20 [00:10<00:01,  5.86it/s]
 70% 14/20 [00:10<00:00,  6.31it/s]
 75% 15/20 [00:10<00:00,  5.69it/s]
 80% 16/20 [00:10<00:00,  5.52it/s]
 85% 17/20 [00:10<00:0
-----
after generate done , contorlnet didnt take any effect in rhe generated image
![IMG_20230824_155726](https://github.com/Mikubill/sd-webui-controlnet/assets/65095993/476a089d-714f-4948-99f7-6a60f0dfbe79)
![IMG_20230824_155651](https://github.com/Mikubill/sd-webui-controlnet/assets/65095993/4d4fb34b-c24c-476c-9fcc-41efc00cb559)

**Comment by huchenlei** [comment]
I am not sure what happened, but it seems like
https://github.com/Mikubill/sd-webui-controlnet/blob/24bb7c572f30da437bb26164cfa4eaadb48f05b0/scripts/controlnet_ui/controlnet_ui_group.py#L490-L498
is being used as gr update value.

However, all 4 references of this variable are not being nested. I am going to deep copy the variable and you can see if this solves your problem.

**Comment by Lucifer-101** [comment]
thanks allot, controlnet v311 working now 💛
-
Steps: 30, Sampler: Euler a, CFG scale: 7, Seed: 2716774486, Size: 384x512, Model hash: e4b17ce185, Model: anything-v4.5-pruned, ControlNet 0: "Module: lineart_anime_denoise, Model: control_v11p_sd15_lineart [43d4be0d], Weight: 1, Resize Mode: Crop and Resize, Low Vram: False, Processor Res: 512, Guidance Start: 0, Guidance End: 1, Pixel Perfect: True, Control Mode: Balanced"
