### ISSUE TITLE
[Bug]: TypeError: OpenposeDetector.__call__() got an unexpected keyword argument 'use_dw_pose'

### ISSUE THREAD

**Issue by Acceleration2299** [Mikubill/sd-webui-controlnet#1975]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I have recently updated my CN from 277 to the latest of 311, Since updating, Parts of ControlNet work better then they were earlier (as some of it simply wasn't working _in general_). However, I'm experiencing a new issue that will also result in ControlNet simply not working.

### Steps to reproduce the problem

Step 1: Set generation Parameters
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/136127897/f2c8656c-2483-45e3-a393-b8f6c6fa7731)

Step 2: Import image to ControlNet and enable OpenPose
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/136127897/cb323f72-ebbe-4381-9552-de377dfebcda)
(also increase preprocessor resolution to 768)
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/136127897/d394660f-8dab-461b-b287-5df56a84b94f)

Step 3: Preprocess the image with the little explosion button in CN
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/136127897/dbc6c392-b8c1-4f1b-98a0-921480329232)

Step 4: Meltdown.
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/136127897/86885298-80c0-4554-b714-38a51292be49)

### What should have happened?

OpenPose should have drawn the funny lines to create a pose for the AI to follow on step 3, But the AI just creates an error instead

### Commit where the problem happens

webui: version: [v1.5.2](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/c9c8485bc1e8720aba70f029d25cba1c4abf2b5c)
controlnet: Version 1.1.311 (updated from V1.1.277)

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
--xformers --no-half-vae --api --listen --enable-insecure-extension-access
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/136127897/455a37b0-bdef-4fbd-b88e-568095858e4b)

### Console logs

```Shell
Already up to date.
venv "C:\Users\DireFloof\Desktop\ai\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.5.2
Commit hash: c9c8485bc1e8720aba70f029d25cba1c4abf2b5c

Launching Web UI with arguments: --xformers --no-half-vae --api --listen --enable-insecure-extension-access
2023-08-24 17:55:14,768 - ControlNet - INFO - ControlNet v1.1.311
ControlNet preprocessor location: C:\Users\DireFloof\Desktop\ai\stable-diffusion-webui\extensions\sd-webui-controlnet\models
2023-08-24 17:55:14,899 - ControlNet - INFO - ControlNet v1.1.311
Loading weights [6e430eb514] from C:\Users\DireFloof\Desktop\ai\stable-diffusion-webui\models\Stable-diffusion\anything-v4.5-pruned.safetensors
Creating model from config: C:\Users\DireFloof\Desktop\ai\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: C:\Users\DireFloof\Desktop\ai\stable-diffusion-webui\models\VAE\anything-v4.0.vae.pt
Applying attention optimization: xformers... done.
Model loaded in 4.5s (load weights from disk: 0.8s, create model: 0.4s, apply weights to model: 1.0s, apply half(): 0.8s, load VAE: 0.5s, move model to device: 0.9s).
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 15.5s (launcher: 2.8s, import torch: 3.3s, import gradio: 1.3s, setup paths: 0.7s, other imports: 0.8s, setup codeformer: 0.2s, load scripts: 1.4s, create ui: 0.6s, gradio launch: 4.3s).
2023-08-24 17:56:08,258 - ControlNet - INFO - Preview Resolution = 768
Traceback (most recent call last):
  File "C:\Users\DireFloof\Desktop\ai\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\DireFloof\Desktop\ai\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\Users\DireFloof\Desktop\ai\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\DireFloof\Desktop\ai\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\DireFloof\Desktop\ai\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\DireFloof\Desktop\ai\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\DireFloof\Desktop\ai\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 636, in run_annotator
    result, is_image = preprocessor(
  File "C:\Users\DireFloof\Desktop\ai\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 79, in decorated_func
    return cached_func(*args, **kwargs)
  File "C:\Users\DireFloof\Desktop\ai\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 67, in cached_func
    return func(*args, **kwargs)
  File "C:\Users\DireFloof\Desktop\ai\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 35, in unified_preprocessor
    return preprocessor_modules[preprocessor_name](*args, **kwargs)
  File "C:\Users\DireFloof\Desktop\ai\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 252, in run_model
    return remove_pad(self.model_openpose(
TypeError: OpenposeDetector.__call__() got an unexpected keyword argument 'use_dw_pose'
```

### Additional information

I have installed additional models for ControlNet, however i have not used _any_ of them as of now.
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/136127897/f51ec903-d6b2-47bc-b6bb-391d2e42bad8)

**Comment by lllyasviel** [comment]
did you try a restart of webui terminal, not only the ui reload

**Comment by Acceleration2299** [comment]
I have tried both about 3 times, i've even tried a computer reboot.

**Comment by Acceleration2299** [comment]
a windows reboot has not helped.

**Comment by lllyasviel** [comment]
I cannot reproduce the problem. My guess is that your python files are probably corrupted. You may try backup models, delete controlnet, and reinstall it in webui
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/19834515/7d6c9ce1-64aa-417c-95f6-449c59373e9e)

**Comment by Acceleration2299** [comment]
I dont expect anything, but i'll give it a shot!

**Comment by Acceleration2299** [comment]
Update, It works, but it doesnt feel quite right...
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/136127897/9c669e91-9c63-4cb8-b1c3-afb7590c5806)

**Comment by Acceleration2299** [comment]
Maybe i just need to mess with tuning? idk

**Comment by Acceleration2299** [comment]
However, Solved, mostly.

**Comment by lllyasviel** [comment]
if you can make sure that this flawed result is from exactly same parameters as my screenshot, open a issue

**Comment by Acceleration2299** [comment]
> if you can make sure that this flawed result is from exactly same parameters as my screenshot, open a issue

The real issue is my model kinda poofed on me
