### ISSUE TITLE
[Bug]: Controlnet ui Elements missing webui (Automatic1111/Vladmandic)

### ISSUE THREAD

**Issue by TonalDesigns** [Mikubill/sd-webui-controlnet#1977]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Launched Vladmandic today (24/08/2023) in the morning, generated a few images without issue, wanted to use controlnet for a second process using text2img, there was only a single controlnet model.

![Screenshot 2023-08-25 010835](https://github.com/Mikubill/sd-webui-controlnet/assets/14240112/8ffbdcbb-2eca-47f9-a2e3-53e366070a92)

Finding it strange but not wanting to restart the ui I moved to img2img for a different method to get that generation done before restarting, this time there was again, only a single controlnet model, and this time there was also no place to put the input image.

![Screenshot 2023-08-25 010821](https://github.com/Mikubill/sd-webui-controlnet/assets/14240112/261b41db-40ea-4ee6-bd14-c756723950e7)

Issue persisted after restarting ui
Issue persisted after using different browsers
Issue persisted after restarting PC
Issue persister after fresh installation
Issue persisted after using original automatic1111 webui (Rather than vladmandic fork)

Note: I have looked at settings in webui for Controlnet I do have max models set to 3 I have attempted changing each setting with no change in behaviour in the ui.

### Steps to reproduce the problem

I have no idea.

### What should have happened?

Multiple models and other ui elements should have been present.

### Commit where the problem happens

webui: Vladmandic: 2023-08-24
webui: Automatic1111: 1.5.2
controlnet: v1.1.311

### What browsers do you use to access the UI ?

Mozilla Firefox, Google Chrome, Microsoft Edge

### Command Line Arguments

```Shell
None
```

### List of enabled extensions

Automatic1111: None
Vladmandic: Default installed extentions

### Console logs

```Shell
Using VENV: F:\vladmandic\venv
02:38:39-751334 INFO     Starting SD.Next
02:38:39-754331 INFO     Python 3.10.11 on Windows
02:38:39-813227 INFO     Version: 0512e297 Thu Aug 24 10:01:39 2023 +0200
02:38:40-246749 INFO     nVidia CUDA toolkit detected
02:38:40-424271 INFO     Disabled extensions: []
02:38:40-426270 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
02:38:40-433250 INFO     Enabled extensions: []
02:38:40-434247 INFO     No changes detected: Quick launch active
02:38:40-435241 INFO     Verifying requirements
02:38:40-445218 INFO     Verifying packages
02:38:40-447213 INFO     Disabled extensions: []
02:38:40-448211 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
02:38:40-455192 INFO     Enabled extensions: []
02:38:40-460179 INFO     Extension preload: 0.0s F:\vladmandic\extensions-builtin
02:38:40-461203 INFO     Extension preload: 0.0s extensions
02:38:40-480126 INFO     Server arguments: []
No module 'xformers'. Proceeding without it.
02:38:46-911956 INFO     Pipeline: Backend.ORIGINAL
02:38:47-478110 INFO     Libraries loaded
02:38:47-480106 INFO     Using data path:
02:38:47-483096 INFO     Available VAEs: models\VAE items=8
02:38:47-496062 INFO     Available models: models\Stable-diffusion items=20
02:38:50-156953 INFO     ControlNet v1.1.311
ControlNet v1.1.311
ControlNet preprocessor location: F:\vladmandic\extensions-builtin\sd-webui-controlnet\annotator\downloads
02:38:50-398318 INFO     ControlNet v1.1.311
ControlNet v1.1.311
02:38:51-496064 INFO     Loading UI theme: name=black-orange style=Auto
Running on local URL:  http://127.0.0.1:7860
02:38:53-437831 INFO     Local URL: http://127.0.0.1:7860/
02:38:53-438828 INFO     Initializing middleware
02:38:53-552524 INFO     [AgentScheduler] Task queue is empty
02:38:53-553521 INFO     [AgentScheduler] Registering APIs
Loading weights: F:\vladmandic\models\Stable-diffusion\abyssorangemix2_Hard.safetensors ━━━━━━━━━━━━━ 0.0/2.1 GB -:--:--
02:38:53-987360 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
02:38:55-891653 INFO     Applying scaled dot product cross attention optimization
02:38:55-928520 INFO     Embeddings: loaded=22 skipped=0
02:38:55-934504 INFO     Model loaded in 2.1s (load=0.1s create=0.3s apply=0.4s vae=0.5s move=0.6s)
02:38:56-164893 INFO     Model load finished: {'ram': {'used': 3.08, 'total': 31.89}, 'gpu': {'used': 3.05, 'total':
                         12.0}, 'retries': 0, 'oom': 0} cached=0
02:38:56-479048 INFO     Startup time: 16.0s (torch=4.7s gradio=0.6s libraries=1.6s codeformer=0.1s scripts=3.8s
                         onchange=0.2s ui-txt2img=0.2s ui-img2img=0.1s ui-settings=0.1s ui-extensions=1.4s
                         ui-defaults=0.1s launch=0.2s app-started=0.2s checkpoint=2.8s)
```

**Comment by lllyasviel** [comment]
The ui in img2img is simplified and expected - you can upload images by checking "upload independent control image"
but if you cannot open multiple controlnet, it seems bugged. Do you have screenshots in default a1111?

**Comment by TonalDesigns** [comment]
Ah that's good to know at least, I either never had that option previously, or it was somehow checked by default. Here is a screenshot of how the element appears in default a1111, more or less the same as vladmandic. 

![Screenshot 2023-08-25 093722](https://github.com/Mikubill/sd-webui-controlnet/assets/14240112/1d9ccfa7-51be-45fe-aa12-2edc25b985e5)

**Comment by TonalDesigns** [comment]
Okay, so, for some unknown reason, I have been able to fix the issue? I tried this yesterday to no avail but for some reason it worked.

I set max controlnet models to 10 in the ui - 10 appeared
I set it back to 3 models and it returned to normal functionality.

It's odd because I tried precisely this multiple times yesterday when I first encountered the issue.

**Comment by TonalDesigns** [comment]
Restarting the server causes the issue to return but as long as I turn it up then down the issue seems to temporarily resolve.
