### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ShvetsAaa** [Mikubill/sd-webui-controlnet#1990]
not working in Batch with CN in fast-stable-diffusion

*** Error completing request
*** Arguments: ('task(21w7xi0lq56j8dk)', 5, 'man with blonde hair in silver texture jacket and black pants and big shoes runnig, detailed photoshoot', '', [], <PIL.Image.Image image mode=RGBA size=1920x1080 at 0x7F8F51697C40>, None, None, None, None, None, None, 26, 0, 4, 0, 1, False, False, 1, 1, 7, 1.5, 0.25, 1158323385.0, -1.0, 0, 0, 0, False, 0, 608, 1080, 1, 0, 0, 32, 0, '/notebooks/run/2', '/notebooks/run/run_rez', '', [], False, [], '', <gradio.routes.Request object at 0x7f8f5f099c40>, 0, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x7f8f5f02f490>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x7f8f5f1ce190>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x7f8f5ef1ec40>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x7f8f5eef11f0>, '

\n
CFG Scale should be 2 or lower.
\n
\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '
Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8

', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '
Will upscale the image by the selected scale factor; use width and height sliders to set tile size

', 64, 0, 2, 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, None, None, False, None, None, False, None, None, False, None, None, False, 50) {}
Traceback (most recent call last):
File "/notebooks/sd/stable-diffusion-webui/modules/call_queue.py", line 58, in f
res = list(func(*args, **kwargs))
File "/notebooks/sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f
res = func(*args, **kwargs)
File "/notebooks/sd/stable-diffusion-webui/modules/img2img.py", line 226, in img2img
process_batch(p, img2img_batch_input_dir, img2img_batch_output_dir, img2img_batch_inpaint_mask_dir, args, to_scale=selected_scale_tab == 1, scale_by=scale_by, use_png_info=img2img_batch_use_png_info, png_info_props=img2img_batch_png_info_props, png_info_dir=img2img_batch_png_info_dir)
File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 25, in img2img_process_batch_hijack
return getattr(img2img, '__controlnet_original_process_batch')(p, *args, **kwargs)
File "/notebooks/sd/stable-diffusion-webui/modules/img2img.py", line 118, in process_batch
infotext = proc.infotext(p, n)
File "/notebooks/sd/stable-diffusion-webui/modules/processing.py", line 457, in infotext
return create_infotext(p, self.all_prompts, self.all_seeds, self.all_subseeds, comments=[], position_in_batch=index % self.batch_size, iteration=index // self.batch_size)
File "/notebooks/sd/stable-diffusion-webui/modules/processing.py", line 624, in create_infotext
"Seed": p.all_seeds[0] if use_main_prompt else all_seeds[index],
IndexError: list index out of range

**Comment by Cornox** [comment]
same issue here, using local automatic1111 UI with img2img in batch mode.
It doesn't seems to matter which CN model I choose,
It generates one image, then it breaks.

---
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 10.85it/s]
Total progress:   3%|█▌                                                            | 35/1350 [05:50<3:39:16, 10.00s/it]
Will process 90 images, creating 1 new images for each.                            | 35/1350 [05:50<1:01:43,  2.82s/it]
2023-08-26 19:43:36,592 - ControlNet - INFO - Loading model from cache: control_v11f1p_sd15_depth [cfd03158]
2023-08-26 19:43:36,682 - ControlNet - INFO - Loading preprocessor: depth
2023-08-26 19:43:36,683 - ControlNet - INFO - preprocessor resolution = 733
2023-08-26 19:43:36,767 - ControlNet - INFO - Loading preprocessor: reference_only
2023-08-26 19:43:36,768 - ControlNet - INFO - preprocessor resolution = -1
  0%|                                                                                                                                                                                                                                                                                 | 0/15 [00:00<?, ?it/s]2023-08-26 19:43:39,881 - ControlNet - INFO - ControlNet used torch.float32 VAE to encode torch.Size([1, 4, 240, 135]).
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:32<00:00,  2.14s/it]
*** Error completing request                                                                                                                                                                                                                                               | 15/1350 [00:30<47:43,  2.15s/it]
*** Arguments: ('task(8gaze274sbsityc)', 5, 'ocean, waves, underwater, professional painting, masterpiece, highly detailed, 4k, 8k, ocean waves brushing against the shore, detailed water, water spash, turbulent waves, air bubbles <lora:openjourneyLora_v1:1> water, water, water', 'open mouth, talking', [], <PIL.Image.Image image mode=RGBA size=1080x1920 at 0x13864965EA0>, None, None, None, None, None, None, 15, 8, 4, 0, 1, False, False, 1, 1, 6, 1.5, 1, 1546533925.0, -1.0, 0, 0, 0, False, 0, 1920, 1080, 1, 0, 0, 32, 0, 'X:\\Stable Diffusion Win output\\t2i\\TikTok_Glaucus\\water_dark\\00023\\anim\\CoNet_0_and_i2i_heygen_0093-0182', 'X:\\Stable Diffusion Win output\\t2i\\TikTok_Glaucus\\water_dark\\00023\\anim\\out', '', [], False, [], '', <gradio.routes.Request object at 0x00000138649670D0>, 0, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000013739200A60>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000138CE0527D0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000013739200970>, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, None, None, False, None, None, False, None, None, False, 50) {}
    Traceback (most recent call last):
      File "C:\Users\dreiD\Documents\github\stable-diffusion\stable-diffusion-webui\modules\call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "C:\Users\dreiD\Documents\github\stable-diffusion\stable-diffusion-webui\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "C:\Users\dreiD\Documents\github\stable-diffusion\stable-diffusion-webui\modules\img2img.py", line 226, in img2img
        process_batch(p, img2img_batch_input_dir, img2img_batch_output_dir, img2img_batch_inpaint_mask_dir, args, to_scale=selected_scale_tab == 1, scale_by=scale_by, use_png_info=img2img_batch_use_png_info, png_info_props=img2img_batch_png_info_props, png_info_dir=img2img_batch_png_info_dir)
      File "C:\Users\dreiD\Documents\github\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 25, in img2img_process_batch_hijack
        return getattr(img2img, '__controlnet_original_process_batch')(p, *args, **kwargs)
      File "C:\Users\dreiD\Documents\github\stable-diffusion\stable-diffusion-webui\modules\img2img.py", line 118, in process_batch
        infotext = proc.infotext(p, n)
      File "C:\Users\dreiD\Documents\github\stable-diffusion\stable-diffusion-webui\modules\processing.py", line 457, in infotext
        return create_infotext(p, self.all_prompts, self.all_seeds, self.all_subseeds, comments=[], position_in_batch=index % self.batch_size, iteration=index // self.batch_size)
      File "C:\Users\dreiD\Documents\github\stable-diffusion\stable-diffusion-webui\modules\processing.py", line 624, in create_infotext
        "Seed": p.all_seeds[0] if use_main_prompt else all_seeds[index],
    IndexError: list index out of range
