### ISSUE TITLE
[Bug]: Something wrong in inpaint_only by txt2img API

### ISSUE THREAD

**Issue by LLLYF** [Mikubill/sd-webui-controlnet#2006]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When I add inpaint_only through txt2img API. Turn the mask part directly into white, which is different from my results on webui. 
The image I have passed in is a masked image that has already been drawn. After my repeated confirmation, using the inpaint module is normal, but I cannot obtain the desired result.
the first is by api
![out20230829124009](https://github.com/Mikubill/sd-webui-controlnet/assets/74784704/55670040-47f0-4f04-b971-914b68dbdfdb)
this is by webui
![00023-461810781](https://github.com/Mikubill/sd-webui-controlnet/assets/74784704/f8490a3f-28a5-485d-8639-45635dd536e1)

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

Generate the same effect as in webUI, more clear rather than blurry

### Commit where the problem happens

webui: 
controlnet: through api

### Command Line Arguments

```Shell
"alwayson_scripts": {
                "controlnet": {
                    "args": [
                        {
                            "enabled": True,
                            "input_image": imgstr1,       #my img wh
                            "module": "inpaint_only",
                            "model": "control_v11p_sd15_inpaint [ebff9138]",
                            "weight": 1,
                            "resize_mode": "Crop and Resize",
                            "lowvram": False,
                            "guidance_start": 0,
                            "guidance_end": 1,
                            "control_mode": 1,      #My prompt is more important
                        },
```

### List of enabled extensions

roop and controlnet

### Console logs

```Shell
normal
```

**Comment by huchenlei** [comment]
If using txt2img inpaint, you need to specify mask in controlnet unit's input image field like [image string, mask string].

**Comment by LLLYF** [comment]
> If using txt2img inpaint, you need to specify mask in controlnet unit's input image field like [image string, mask string].

But when I use inpaint module, the output is normal, is that right?

**Comment by 765144989** [comment]
> If using txt2img inpaint, you need to specify mask in controlnet unit's input image field like [image string, mask string].

I used your method and entered a list [image string base64, mask string base64] in "input_image": and it ran normally but it didn't seem to work. My mask image uses white on a black background, and the white part is my mask.

**Comment by tiimgreen** [comment]
@765144989 I have the same issue when passing the mask as a base64 string as @huchenlei suggested, did you find a solution to this?

I'm encoding an image from URL like this:

```python
base64.b64encode(requests.get(url).content).decode('utf-8')
```
