### ISSUE TITLE
PermissionError: [WinError 5] Access is denied ... again

### ISSUE THREAD

**Issue by Elaneor** [Mikubill/sd-webui-controlnet#2007]
Here's the list of what i tried so far:

1 as citrusian said [here ](https://github.com/Mikubill/sd-webui-controlnet/issues/1258#issuecomment-1575127507)Edited my webui-user.bat adding this in the beggining of file
> cd /d %~dp0

and then run webui-user.bat as administrator.

2  Run cmd as administrator [as mentioned here](https://github.com/Mikubill/sd-webui-controlnet/issues/1024), cd to my Stable-diffusion folder and run my web-user.bat from there

Stable diffusion in both ways starts OK.
BUT
When I try to install sd-webuic-controlnet in the **Extensions** tab - **Install from URL**

here's what I get

> *** Error completing request
> *** Arguments: ('', 'https://github.com/Mikubill/sd-webui-controlnet.git', '') {}
>     Traceback (most recent call last):
>       File "C:\stable-diffusion-webui\modules\call_queue.py", line 58, in f
>         res = list(func(*args, **kwargs))
>       File "C:\stable-diffusion-webui\modules\ui_extensions.py", line 620, in <lambda>
>         fn=modules.ui.wrap_gradio_call(lambda *args: [gr.update(), *install_extension_from_url(*args)], extra_outputs=[gr.update(), gr.update()]),
>       File "C:\stable-diffusion-webui\modules\ui_extensions.py", line 375, in install_extension_from_url
>         raise err
>       File "C:\stable-diffusion-webui\modules\ui_extensions.py", line 367, in install_extension_from_url
>         os.rename(tmpdir, target_dir)
>     PermissionError: [WinError 5] Access is denied: 'C:\\stable-diffusion-webui\\tmp\\sd-webui-controlnet' -> 'C:\\stable-diffusion-webui\\extensions\\sd-webui-controlnet'
> 
> ---
 Any more ideas please?
 It's Windows 10 Home version

**Comment by Elaneor** [comment]
So, the third option was to use the webui-user.bat with EMPTY COMMANDLINE_ARGS= parameter.

**Comment by khushil** [comment]
I have the very same issue, and oddly ONLY with this extension too. Everything else I install works fine:

*** Error completing request
*** Arguments: ('https://github.com/Mikubill/sd-webui-controlnet.git', ['ads', 'localization', 'installed'], 7, '') {}
    Traceback (most recent call last):
      File "H:\src\ai\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "H:\src\ai\stable-diffusion-webui\modules\ui_extensions.py", line 399, in install_extension_from_index
        ext_table, message = install_extension_from_url(None, url)
      File "H:\src\ai\stable-diffusion-webui\modules\ui_extensions.py", line 387, in install_extension_from_url
        raise err
      File "H:\src\ai\stable-diffusion-webui\modules\ui_extensions.py", line 379, in install_extension_from_url
        os.rename(tmpdir, target_dir)
    PermissionError: [WinError 5] Access is denied: 'H:\\src\\ai\\stable-diffusion-webui\\tmp\\sd-webui-controlnet' -> 'H:\\src\\ai\\stable-diffusion-webui\\extensions\\sd-webui-controlnet'

---

I've tried all three suggestions but it does this evertime. Any ideas follks?

**Comment by Elaneor** [comment]
> I have the very same issue, and oddly ONLY with this extension too. Everything else I install works fine:
>
> 
> I've tried all three suggestions but it does this evertime. Any ideas follks?
Well, I don't know if it matters, but

5 months later (just last week) I changed my command-line arguments in webui-user.bat
from

`....
set COMMANDLINE_ARGS= --medvram --xformers
....
`

to

```
cd /d %~dp0
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS= --no-half --xformers

call webui.bat
```

And just a day before yesterday I installed quite a few new extensions
(GeForce 1070 8GB here, if that can matter)

It was all I changed in my setup.

**Comment by huchenlei** [comment]
Issue filed on A1111. The workaround now is to run git command directly to clone the repo.

**Comment by w-e-w** [comment]
you should **_NEVER_** run a server application like web ui as administrator, not only that is potentially dangerous
but it's also known to cause issues
and permission issues seems exactly the type of thing that is caused by a mix of different privileges
