### ISSUE TITLE
[Bug]: There is an error in 1.6.0.

### ISSUE THREAD

**Issue by Neytiri7** [Mikubill/sd-webui-controlnet#2011]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Running causes an error.

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

When you enable the control net, it does not work.

### Commit where the problem happens

webui: 
controlnet: 

### Command Line Arguments

```Shell
GIT PULL
```

### List of enabled extensions

sd-webui-controlnet

### Console logs

```Shell
O:\AI\SynologyDrive\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py:163: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row(elem_classes=["cnet-image-row"]).style(
O:\AI\SynologyDrive\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py:184: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  self.generated_image = gr.Image(
Init / preset error.
```

**Comment by DarqueLilly** [comment]
I want to know the solution to this too

**Comment by lllyasviel** [comment]
will fix in next version
