### ISSUE TITLE
[Bug]: CN not working on deforum

### ISSUE THREAD

**Issue by aipicsstudio** [Mikubill/sd-webui-controlnet#2019]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

The video generation starts but controlnet isn't activated and doesn't modify my video on deforum. the problem starts 

### Steps to reproduce the problem

1. Go to .deforum
2. Enable CN (I used the tile model)
3. Generate Image

### What should have happened?

InputFrames should be modified thanks to ControlNet on Deforum

### Commit where the problem happens

webui: 
controlnet: 
deforum: https://github.com/deforum-art/sd-webui-deforum/commit/d8764419f93c484068309180d3343cece1d9b307

### Command Line Arguments

```Shell
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS= --xformers --autolaunch --medvram

call webui.bat
```

### List of enabled extensions

![enabled extentions](https://github.com/Mikubill/sd-webui-controlnet/assets/143832355/e8ebb3fb-1cda-429c-ace8-20439b3f38fa)

### Console logs

```Shell
venv "D:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Launching Web UI with arguments: --xformers --autolaunch --medvram
2023-09-01 19:10:22,573 - ControlNet - INFO - ControlNet v1.1.313
ControlNet preprocessor location: D:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-09-01 19:10:22,896 - ControlNet - INFO - ControlNet v1.1.313
Loading weights [76be5be1b2] from D:\stable-diffusion-webui\models\Stable-diffusion\epicrealism_pureEvolutionV5.safetensors
Creating model from config: D:\stable-diffusion-webui\configs\v1-inference.yaml
*Deforum ControlNet support: enabled*
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 38.4s (prepare environment: 13.3s, import torch: 9.9s, import gradio: 3.0s, setup paths: 3.0s, initialize shared: 0.9s, other imports: 2.3s, setup codeformer: 0.6s, setup gfpgan: 0.1s, load scripts: 2.8s, initialize extra networks: 0.2s, create ui: 1.3s, gradio launch: 1.1s).
Applying attention optimization: xformers... done.
Model loaded in 13.5s (load weights from disk: 1.0s, create model: 1.4s, apply weights to model: 8.7s, load VAE: 0.2s, calculate empty prompt: 2.1s).
started run_deforum
times_to_run: 1
Deforum extension for auto1111 webui
Git commit: d8764419
Starting job task(bzk47qqilc4pbr9)-0...
Copied CN Model 1's single input image to inputframes folder!
Saving animation frames to:
D:\stable-diffusion-webui\outputs\img2img-images\Deforum_20230901191202
Animation frame: 0/120
Seed: 1702500858
Prompt: tiny cute bunny, vibrant diffraction, highly detailed, intricate, ultra hd, sharp photo, crepuscular rays, in focus
Neg Prompt: nsfw, nude
Not using an init image (doing pure txt2img)
╭─────┬───┬───────┬─────┬──────┬──────┬──────┬────┬────╮
│Steps│CFG│Denoise│Angle│ Zoom │Tr C X│Tr C Y│Tr X│Tr Y│
├─────┼───┼───────┼─────┼──────┼──────┼──────┼────┼────┤
│ 25  │7.0│   0   │  0  │1.0025│ 0.5  │ 0.5  │ 0  │ 0  │
╰─────┴───┴───────┴─────┴──────┴──────┴──────┴────┴────╯
Reading ControlNet *static* base frame at D:\stable-diffusion-webui\outputs\img2img-images\Deforum_20230901191202\controlnet_1_inputframes\000000000.jpg
*** Error running setup: D:\stable-diffusion-webui\modules/processing_scripts\refiner.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui\modules\scripts.py", line 740, in setup_scrips
        script_args = p.script_args[script.args_from:script.args_to]
    TypeError: unhashable type: 'slice'

---
*** Error running setup: D:\stable-diffusion-webui\modules/processing_scripts\seed.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui\modules\scripts.py", line 740, in setup_scrips
        script_args = p.script_args[script.args_from:script.args_to]
    TypeError: unhashable type: 'slice'

---
*** Error running setup: D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui\modules\scripts.py", line 740, in setup_scrips
        script_args = p.script_args[script.args_from:script.args_to]
    TypeError: unhashable type: 'slice'

---
2023-09-01 19:12:04,076 - ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: [].
2023-09-01 19:12:04,078 - ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: [].
 56%|█████████████████████████████████████████████▉                                    | 14/25 [00:32<00:24,  2.24s/it]
Deforum progress:   1%|▊                                                             | 14/1096 [00:28<41:40,  2.31s/it]
```

**Comment by TheRealCrew** [comment]
I have the exact same problem since yesterday after I updated to SD V-1.6.   

*** Error running setup: E:\Stable_diffusion\stable-diffusion-webui\modules/processing_scripts\refiner.py
    Traceback (most recent call last):
      File "E:\Stable_diffusion\stable-diffusion-webui\modules\scripts.py", line 740, in setup_scrips
        script_args = p.script_args[script.args_from:script.args_to]
    TypeError: unhashable type: 'slice'

---
*** Error running setup: E:\Stable_diffusion\stable-diffusion-webui\modules/processing_scripts\seed.py
    Traceback (most recent call last):
      File "E:\Stable_diffusion\stable-diffusion-webui\modules\scripts.py", line 740, in setup_scrips
        script_args = p.script_args[script.args_from:script.args_to]
    TypeError: unhashable type: 'slice'

---
*** Error running setup: E:\Stable_diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "E:\Stable_diffusion\stable-diffusion-webui\modules\scripts.py", line 740, in setup_scrips
        script_args = p.script_args[script.args_from:script.args_to]
    TypeError: unhashable type: 'slice'

---
*** Error running setup: E:\Stable_diffusion\stable-diffusion-webui\extensions-builtin\extra-options-section\scripts\extra_options_section.py
    Traceback (most recent call last):
      File "E:\Stable_diffusion\stable-diffusion-webui\modules\scripts.py", line 740, in setup_scrips
        script_args = p.script_args[script.args_from:script.args_to]
    TypeError: unhashable type: 'slice'

---
2023-09-02 11:57:22,653 - ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: [].
2023-09-02 11:57:22,653 - ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: [].

**Comment by IlonaKova** [comment]
I have the same problem in Deforum, the controlnet does not work. After the update.

**Comment by TheRealCrew** [comment]
I have rolled back to the sd-webui version 1.5.2. Deforum is working with the older version. Add "git checkout v1.5.2" to your webui-user.bat

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/37497418/11179f1c-b57e-47d9-aafe-ec37ef7b86a2)

**Comment by stalkeet123** [comment]
same problem in deforum

**Comment by IlonaKova** [comment]
The problem has not been solved, download controlnet is written in the Deforum. I deleted, downloaded again. But so far controlnet does not work in Deforum. Tell me how to solve this problem?

**Comment by Nicomadreja87** [comment]
I have the same problem, i reinstall from 0 stable diffusion. Only Contronet and Deforum extension and i have this problem... i rollback to 1.5 but i want to stay in 1.6. any solution?

**Comment by Slider-Override** [comment]
> I have rolled back to the sd-webui version 1.5.2. Deforum is working with the older version. Add "git checkout v1.5.2" to your webui-user.bat
> 
> ![image](https://user-images.githubusercontent.com/37497418/265195306-11179f1c-b57e-47d9-aafe-ec37ef7b86a2.png)

This is also not working for me, its still the same :
 No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: [].

**Comment by Slider-Override** [comment]
I spend the whole day to search for a workaround, but no luck, did one of you are able to get it working ?

**Comment by GreggUrban** [comment]
**git checkout v1.5.2**

It worked. Thank you

**Comment by alexbofa** [comment]
I have the same problem in Deforum, in 1.6.0

**Comment by Slider-Override** [comment]
> **git checkout v1.5.2**
> 
> It worked. Thank you

Hi @GreggUrban I also try version: [v1.4.1]

But still the same:
2023-09-04 09:50:42,285 - ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: [].

Can you please share which version of sd-webui-controlnet you use ?

**Comment by Nicomadreja87** [comment]
Hello, 

WebUI: version: 1.6.0
python: 3.10.11
torch: 2.0.1+cu118
 xformers: 0.0.20
gradio: 3.41.2
checkpoint: 4199bcdd14

Extensions:
Defaunts... and:
deforum-for-automatic1111-webui > 2023-09-01 19:35:31
sd-webui-controlnet >2023-09-03 23:33:05

Yes, Yesterday a controlnet update came out. I updated it hoping it would work. But I still have the same problem.

I have tried performing a clean installation of WebUI 1.6.0 in another virtual environment but the problem persists. However, if I install version 1.5.2 of WebUi everything works normally.

**Comment by Slider-Override** [comment]
Thanks I will try to get all versions to the say you have, and test

**Comment by Nicomadreja87** [comment]
It has started to work for me.
WebUI 1.6.0
deforum-for-automatic1111 86921f79 2023-09-04 14:03:45 latest
sd-webui-controlnet 664ac74c 2023-09-04 15:06:46 latest

I have only updated the CN and Deforum extensions to the new versions that came out today.

For me, problem solved. :)
