### ISSUE TITLE
[Bug]: CN crashed

### ISSUE THREAD

**Issue by kaydenblake0812** [Mikubill/sd-webui-controlnet#2020]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: []
no control ned in deforum,,:(

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: []
no control ned in deforum,,:(

### Commit where the problem happens

webui: 
controlnet: 

### Command Line Arguments

```Shell
WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: []
no control ned in deforum,,:(
```

### List of enabled extensions

WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: []
no control ned in deforum,,:(

### Console logs

```Shell
WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: []
no control ned in deforum,,:(
```

**Comment by huchenlei** [comment]
https://github.com/Mikubill/sd-webui-controlnet/issues/2019?notification_referrer_id=NT_kwDOAT9bArM3NTgyNDg0OTE5OjIwOTI5Mjgy#issuecomment-1703733215

**Comment by IlonaKova** [comment]
The problem has not been solved, download controlnet is written in the Deforum. I deleted, downloaded again. But so far controlnet does not work in Deforum. Tell me how to solve this problem?

**Comment by Slider-Override** [comment]
Yeah I am dealing with the same issue, controlnet is not working in deforum anymore :-(
