### ISSUE TITLE
[Bug]: Controlnet does not work in Deforum

### ISSUE THREAD

**Issue by IlonaKova** [Mikubill/sd-webui-controlnet#2025]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

After updating SD to version 1.6. Controlnet does not work in Deforum. In the Controlnet tab, it says that you need to install this extension. I have it installed. I tried to uninstall and install, but controlnet does not work in deforum
![IMG_20230903_082710_530](https://github.com/Mikubill/sd-webui-controlnet/assets/143811355/e5a24470-b63f-4329-ae65-60fe22501c2b)
![IMG_20230903_082711_161](https://github.com/Mikubill/sd-webui-controlnet/assets/143811355/6ccb4d8b-db2e-4f06-b15a-b22ffcf56ef4)

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

Controlnet should work correctly in Deforum

### Commit where the problem happens

webui: 
controlnet: 

### What browsers do you use to access the UI ?

Google Chrome, Microsoft Edge

### Command Line Arguments

```Shell
No
```

### List of enabled extensions

![IMG_20230903_082711_192](https://github.com/Mikubill/sd-webui-controlnet/assets/143811355/30f4ce33-ea93-4c40-89f6-83eba26d2031)
![IMG_20230903_082710_975](https://github.com/Mikubill/sd-webui-controlnet/assets/143811355/4708f0f8-138a-4e7e-830c-02ff624edfb0)

### Console logs

```Shell
.
```

**Comment by Beshaney** [comment]
Please help, have same problem!!!

**Comment by Rovnova** [comment]
https://github.com/Mikubill/sd-webui-controlnet/assets/72410079/ac746c8b-7f3c-481c-9620-9e52293cec09
Help with the problem!
After the update, deforum control net (Colab notebooks,Google Chrome) works terribly.

**Comment by shofastyle** [comment]
i2i recognizes it, but I don't either.
in trouble.
I would like to know how to improve it.
please.

ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: [].

**Comment by alexbofa** [comment]
Yes, the same problem

**Comment by eduardonba1** [comment]
Disable all extentions. keep only controlnet and deforum activated, restart the ui and try again
Are you loading deforum settings through some .txt file?
If so, try setting manually

**Comment by UlyssesHeart** [comment]
This is still a major problem that I cannot find a fix for anywhere. Apparently others are saying that ControlNet often does not show up in Deforum due to some conflict in SD 1.6+. Many people are going so far as to downgrade to 1.5.2 just to access ControlNet within the Deforum tab, and then disable ALL extensions aside from ControlNet and Deforum. That just seems crazy to me. Spent hour on this reading through hundreds of posts about this problem, and I have tried everything... but still get "**ControlNet not found, Please install it**"

**Comment by plasm0-ai** [comment]
has the [ControlNet not found. Please install it :) issue been resolved?
