### ISSUE TITLE
cannot find the Allow Preview related setting parameters in the API.

### ISSUE THREAD

**Issue by 6666665** [Mikubill/sd-webui-controlnet#2026]
cannot find the Allow Preview related setting parameters in the API. Can you tell me how to set Allow Preview through the API. Thank you very much
![微信图片_20230903142313](https://github.com/Mikubill/sd-webui-controlnet/assets/44966362/56bec21a-048a-4c93-b9bb-88000fd2e7df)

**Comment by Charoncrat** [comment]
could you share this link to me, thanks

**Comment by chestnutpcj** [comment]
I also want to know how to preview. Is this problem solved now?

**Comment by huchenlei** [comment]
If you want to "preview" the preprocessed result, you can use /controlnet/detect endpoint. See https://github.com/Mikubill/sd-webui-controlnet/wiki/API#route-post-controlnetdetect.

**Comment by chestnutpcj** [comment]
来件收到辣收到辣╰(￣▽￣)╮
