### ISSUE TITLE
Images not saving to Output directory (or anywhere) when using img2img Batch mode with ControlNet

### ISSUE THREAD

**Issue by nikallasha** [Mikubill/sd-webui-controlnet#2027]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

After the latest Automatic1111 (1.6.0) and ControlNet updates, images aren't being saved anywhere when using Batch mode in img2img with ControlNet.

### Steps to reproduce the problem

1. Go to img2img
2. Choose Batch mode and type in the Input and Output directories for your images
3. Enable ControlNet, choose any Control Type
4. Generate

### What should have happened?

The generated images should save to the chosen Output directory

### Commit where the problem happens

webui: 
controlnet: 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--opt-sdp-attention --medvram --ckpt-dir C:\SD-Contents\sd-models --lora-dir C:\SD-Contents\Lora --embeddings-dir C:\SD-Contents\embeddings --controlnet-dir C:\SD-Contents\ControlNet
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/141487900/df51673b-e131-4f7f-ac6a-b6a241d8fb35)

### Console logs

```Shell
.
```

**Comment by aleksbos** [comment]
Similarly. There is no way to work in batch mode

**Comment by aleksbos** [comment]
Batch mode only works with these settings. At the same time, the images are saved to the standard Stable Diffusion folder. When specifying the output folder, the images are not saved anywhere at all. Also, TemporalNet stopped working. The generation rate has dropped by almost 3-4 times.
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/124212531/b2987172-1e25-4e3b-ab68-dfe8969c7e11)

**Comment by millbank14** [comment]
I experienced the same problem several days ago. I literally cannot work without this function operating. Is it being looked at?

**Comment by alexbofa** [comment]
The same, images are not saved when working with the batch

**Comment by lllyasviel** [comment]
so is this a controlnet problem or a webui problem?
if it is not controlnet then we are not going to take any action

**Comment by millbank14** [comment]
It must be a ControlNet problem because the images do go to the output directory when using img to img batch mode WITHOUT ControlNet.

**Comment by brandostrong** [comment]
confirming I also have this issue, batch tab loopback does not write to anywhere

**Comment by Mathssss** [comment]
> Batch mode only works with these settings. At the same time, the images are saved to the standard Stable Diffusion folder. When specifying the output folder, the images are not saved anywhere at all. Also, TemporalNet stopped working. The generation rate has dropped by almost 3-4 times. ![image](https://user-images.githubusercontent.com/124212531/265603550-b2987172-1e25-4e3b-ab68-dfe8969c7e11.png)

Where does it save to? mine isn't saving anywhere when i leave the output blank.... i need to figure this out asap as i have a video due in a month and NEEED this funcionality .
AAAAAAAAh

**Comment by jkyndir** [comment]
i'm having the same issue. With or without control net enabled, the img2img batch doesn't seem to generate any output anywhere.

can anyone plz help?

**Comment by jkyndir** [comment]
is there a fix for this problem?

i'm really in need of outputing image sequence right now

**Comment by alexbofa** [comment]
it seems to be solved in the DEV version, but there is a problem with https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/13627

**Comment by jkyndir** [comment]
> it seems to be solved in the DEV version, but there is a problem with [AUTOMATIC1111/stable-diffusion-webui#13627](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/13627)
hi there, much appreciate the help. but i just switch to the dev branch of webui, and the same problem still persists on my end. The generated images are not saved anywhere, when using batch img2img, no matter what settings i used.

**Comment by jkyndir** [comment]
> it seems to be solved in the DEV version, but there is a problem with [AUTOMATIC1111/stable-diffusion-webui#13627](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/13627)

hi there, much appreciate the help. but i just switch to the dev branch of webui, and the same problem still persists on my end. The generated images are not saved anywhere, when using batch img2img, no matter what settings i used.

**Comment by alexbofa** [comment]
@jkyndir 

it's strange, because of this [fix](https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/13170), saving works for me, but what I described above is very annoying. **Seed / Denoising strength**

**Comment by jkyndir** [comment]
i finally figured it out!

After switching to the dev branch, gotta check this option here as well, and then the batch images would be saved to the output directory.

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/57865763/7dc55dad-d55a-43a4-b24c-ec57de4599da)

**Comment by MadDogFG** [comment]
same
