### ISSUE TITLE
[Bug]: "Use Preview as input" gone

### ISSUE THREAD

**Issue by Hellrunner2k** [Mikubill/sd-webui-controlnet#2036]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

updated the extension and the essential "use preview as input" checkbox was gone.

### Steps to reproduce the problem

update the extension

### What should have happened?

the essential "use preview as input" checkbox should not have vanished.

### Commit where the problem happens

Automatic1111

### What browsers do you use to access the UI ?

Brave

### Command Line Arguments

```Shell
--xformers --medvram --no-half-vae
```

### List of enabled extensions

https://github.com/Zyin055/Config-Presets
https://github.com/chrisgoringe/Styles-Editor.git
https://github.com/Bing-su/adetailer.git
https://github.com/deforum-art/deforum-for-automatic1111-webui.git
https://github.com/CMU-Perceptual-Computing-Lab/openpose
https://github.com/ashen-sensored/sd-dynamic-thresholding-rcfg
https://github.com/alemelis/sd-webui-ar.git
https://git.mmaker.moe/mmaker/sd-webui-color-enhance.git
https://github.com/Mikubill/sd-webui-controlnet
https://github.com/pk5ls20/sd-webui-controlnet-fastload.git
https://github.com/Uminosachi/sd-webui-inpaint-anything.git
https://github.com/antis0007/sd-webui-multiple-hypernetworks.git
https://github.com/huchenlei/sd-webui-openpose-editor.git                <- vital to be used without preprocessor
https://github.com/wcde/sd-webui-refiner.git
https://github.com/continue-revolution/sd-webui-segment-anything.git
https://github.com/a2569875/stable-diffusion-webui-composable-lora.git
https://github.com/toshiaki1729/stable-diffusion-webui-dataset-tag-editor.git
https://github.com/AUTOMATIC1111/stable-diffusion-webui-wildcards.git
https://github.com/Coyote-A/ultimate-upscale-for-automatic1111
https://github.com/fishslot/video_loopback_for_webui.git
https://github.com/DingoBite/weight_gradient

### Console logs

```Shell
there are no errors in console. just loads control net. and i don't know where the logs are.
```

### Additional information

well... seems super straight forward to me... the checkbox is not there... bad

**Comment by Feynt** [comment]
I can confirm, no controlnet functions are working with the update I performed today outside of reference.  Error in console appears to be a reference to openpose editor, regardless of whether I'm using openpose or not (such as trying to use scribble, or lineart) when initiating a preprocessor action.

I performed the following rollback locally and it has re-enabled all controlnet functionality:
`git reset --hard 510bd66e3a8fd90311af133a63a1519af502b290`

I can confirm also that it was working properly as of Friday past when I last did an update, but I did a check/update this evening and controlnet broke as a result.

**Comment by lllyasviel** [comment]
"use preview as input" is automated now in a catching system if you do not change preview or if you used openpose editor.
the broken commit fixed just now

**Comment by Hellrunner2k** [comment]
you are missing the point ... it's VITAL to an openPose workflow that you can use the editor independent from the preprocessor ... that the openpose editor still works even with disabled preprocessor ... some ppl are actual artists you know... 
sorry your galaxy brain mod rubbed me the wrong way.

really appreciate the work... so .. you make a detection on an earlier created image... preprocessor to none ... edit ... send to controlNet ... make the next image ...
 edit again.. adjust pose ... make the next image ...
(optional) save refined pose ... make detection to add ppl ... preprocessor to none ... load refined pose .. edit ... send to controlNet ... make the next image ...   .. and so on
this workflow is busted now.

**Comment by Prince-Mars** [comment]
> That toggle will not do anything because “Use preview as input” is already automated, but users who are accustomed to the old interface will be happier.

No, it will. The picture for the pose can be deleted and only the constructed pose can be used. It seems to me that the source image influences the generated image.
