### ISSUE TITLE
[Bug]: A1111 won't launch properly after last update

### ISSUE THREAD

**Issue by Labraca** [Mikubill/sd-webui-controlnet#2043]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I updated A1111 and extensions to the latest version. After restarting UI nothing would work. I can't change model or list the installed extensions on the extensions tab.... Everything works fine if i remove the controlnet extension

### Steps to reproduce the problem

Just start webui-user.bat

### What should have happened?

Launch properly

### Commit where the problem happens

webui: 1.6.0
controlnet: 1.1.401

### Command Line Arguments

```Shell
--xformers --medvram --medvram-sdxl --no-half
```

### List of enabled extensions

sd-webui-additional-networks
sd-webui-controlnet
sd-webui-regional-prompter

### Console logs

```Shell
https://pastebin.com/9kFBeCXJ
```

### Additional information

I have traced back the problem to the commit https://github.com/Mikubill/sd-webui-controlnet/pull/1980. That's the first that won't work. The commit just before that one, https://github.com/Mikubill/sd-webui-controlnet/pull/1978, actually works.

**Comment by lllyasviel** [comment]
try update gradio

 if that does not works, try @huchenlei

**Comment by Labraca** [comment]
> try update gradio
> 
> if that does not works, try @huchenlei

I updated gradio to it's latest version (3.42.0) but it didn't work, same errors.

**Comment by huchenlei** [comment]
Hmmmm, interesting. Let me try to reproduce it. 

At minimum we can add an flag in settings to disable preset feature so the user can continue use other features.

**Comment by Labraca** [comment]
It seems to be something with the 1.6.0 A1111 version and yours. I have downgraded A1111 to 1.6.0-RC and works fine at first glance.

**Comment by Labraca** [comment]
I tried using a fresh installation of A1111 1.6.0 but it didn't work. What did work was downgrading the fresh installation to 1.6.0-RC (old installation gets the same error even after downgrading it). So it seems to be something of 1.6.0 version with CN 1.1.312 and above + something of my old installation.
