### ISSUE TITLE
[Feature] Support "Gamma Correction" in "ControlNet processing unit entirely" in api

### ISSUE THREAD

**Issue by SpenserCai** [Mikubill/sd-webui-controlnet#2046]
from [here](https://github.com/Mikubill/sd-webui-controlnet/blob/fd37e9fc7ced2c3a39aaa3860916672c8d0fbfe8/internal_controlnet/external_code.py#L144) , it can be seen that the "Gamma Correction" parameter is not currently supported in the API (txt2img, img2img). We hope you can support it. Thank you.

**Comment by SpenserCai** [comment]
@lllyasviel

**Comment by huchenlei** [comment]
Gamma Correction is `threshold_a` in API when you using corresponding preprocessors.

https://github.com/Mikubill/sd-webui-controlnet/blob/3011ff6e706d3fdd0cc7d2ac8ff0d59020b8f767/scripts/processor.py#L969-L989

**Comment by SpenserCai** [comment]
thank you so much!
