### ISSUE TITLE
[Bug]: controlnet 

### ISSUE THREAD

**Issue by daowaidao** [Mikubill/sd-webui-controlnet#2048]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

![CPT2309051358-965x428](https://github.com/Mikubill/sd-webui-controlnet/assets/125630842/230d0e2a-9c36-4ea2-8237-8be6f66ac8a8)
In the img to img, controlnet is automatically enabled but the green unit  mark is not displayed. Uncheck  "unit 0" and then it will enables all other units,the green mark shows. Moreover, even though the "Upload independent control image" checkbox is clearly selected, the image upload box does not appear. However, canceling the selection and then selecting it again will display the upload box.

### Steps to reproduce the problem

1. Go to img to img
2. open controlnet
3. ...

### What should have happened?

like the controlnet under txt to img,all units should be unchecked and show their Image Upload Boxes.

### Commit where the problem happens

webui: Automatic111 1.6
controlnet:  v1.1.4013 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
no
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/125630842/b5eecb6f-393b-4086-8cab-0fd01fffdf77)

### Console logs

```Shell
no
```

**Comment by huchenlei** [comment]
Current JavaScript logic in ControlNet does not account the value set by webui default ui config json file.

We recommend you use the preset manager if you want to restore a specific controlnet preset.

**Comment by daowaidao** [comment]
Why is it able to remain disabled by default under "txt to img" but the one under “img to img" can't?When open controlnet under "txt to img",there is a upload box,it's much easier then under "img to img". The preset manager keep the unit checked but I want it disabled by default.
