### ISSUE TITLE
ControlNet sample image remains in 'memory' of SD

### ISSUE THREAD

**Issue by MrJeJo** [Mikubill/sd-webui-controlnet#206]
I'm not able to reset the sample/pose image of ControlNet. When I use ControlNet to generate an image, the sample data is stored in 'memory' and I'm not able to reset it. I have to restart the webui cmd window to delete it.

Steps to reproduce:
1. Start the WebUI
2. Generate an image (without prompt, just default settings), it will generate a different image every time, as expected.
3. Fill in a prompt like 'a photo of a bird'
4. Use ControlNet to scribble a simple drawing of a bird.
5. Generate an image, it will generate a photo of a bird with guidance from the scribble, as expected.
6. Now reload the WebUI, all settings will be reset, as expected.
7. Generate an image (without prompt, just default settings, ControlNet is disabled), now the scribble of the bird will be present in all images and it remains in 'memory.

I think this is a bug, or I don't understand to reset ControlNet?

Cheers,

Jeff

**Comment by jvoxel** [comment]
I have the same happening to me

**Comment by Mikubill** [comment]
Maybe some state management issue with gradio or webui. Currently you need to disable it before/after reload UI by ticking `Enable` checkbox

**Comment by 2blackbar** [comment]
I had this happen few days ago and it did not returned but maybe it has to be triggered somehow, i had  it with txt2img when i disabled controlnet with tickbox

**Comment by chrisbward** [comment]
I've had this happen when using Controlnet in the UI, but then calling img2img in the API - seems to bleed through?

**Comment by Mikubill** [comment]
fixed in https://github.com/Mikubill/sd-webui-controlnet/commit/f46de9741018068cd2dc46b4a1d972283f6e3093
