### ISSUE TITLE
Google colab

### ISSUE THREAD

**Issue by AdamKnapp1** [Mikubill/sd-webui-controlnet#207]
Hello! I wanted to ask if it's possible to run this on the google colab Automatic 1111 or you can only run it locally?

**Comment by R-N** [comment]
Yes, you can run it on colab. Though it will increase RAM usage, so it may crash on big checkpoints (unpruned ones, like about 7GB). Even with pruned fp32 checkpoints (4GB) it crashed on me sometimes when switching to other controlnet.

**Comment by camenduru** [comment]
Hi @AdamKnapp1 👋 please try this https://github.com/camenduru/stable-diffusion-webui-colab/tree/v2.0

**Comment by cerarslan** [comment]
Can be implemented TheLastBen colabs?

> Hi @AdamKnapp1 👋 please try this https://github.com/camenduru/stable-diffusion-webui-colab/tree/v2.0
