### ISSUE TITLE
[Bug]: Error after updated to v1.1.408

### ISSUE THREAD

**Issue by Bullshin** [Mikubill/sd-webui-controlnet#2075]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Error after updated to v1.1.408
The controlnet is not working for both img2img and mov2mov, the txt2img is working
i am using sd v1.5.1 & v1.5.2 both not working
i tried on v1.6 img2img is working
i tried reinstall stable-diffusion and all plugin, also not working

### Steps to reproduce the problem

1. Update control net 
2. Go to img2img
3. insert img
4. Input prompt with <lora:koreanDollLikeness:0.6>
5. Enable adetailer using scribble model
6. Enable controlnet using Canny & Tile models
7. Click Generate
8. Warning appear on cmd

### What should have happened?

the lora face control should effect on img2img outcome

### Commit where the problem happens

webui: v1.5.1 & v1.5.2
controlnet: v1.1.408

### Command Line Arguments

```Shell
--xformers
```

### List of enabled extensions

<img width="674" alt="螢幕擷取畫面 2023-09-07 092925" src="https://github.com/Mikubill/sd-webui-controlnet/assets/144295360/8f04cada-de02-4a04-8871-9a47b314dc71">

### Console logs

```Shell
Total progress: 100%|████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.35it/s]
2023-09-07 09:28:01,813 - ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: ().

[-] ADetailer: Invalid arguments passed to ADetailer.
    input: ()
    ADetailer disabled.

2023-09-07 09:28:01,816 - ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: ().
100%|████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:01<00:00,  3.88it/s]
Total progress: 100%|████████████████████████████████████████████████████████████████████| 7/7 [00:01<00:00,  4.09it/s]
[-] ADetailer: Invalid arguments passed to ADetailer.
    input: ()
    ADetailer disabled.

Total progress: 100%|████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.34it/s]
Total progress: 100%|████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  4.09it/s]
```

### Additional information

<img width="590" alt="螢幕擷取畫面 2023-09-07 094742" src="https://github.com/Mikubill/sd-webui-controlnet/assets/144295360/78aa82b8-0543-45e5-9ffd-e5433194e903">
<img width="585" alt="螢幕擷取畫面 2023-09-07 094756" src="https://github.com/Mikubill/sd-webui-controlnet/assets/144295360/94ebc392-75a3-4857-85c7-7484793fce45">
<img width="589" alt="螢幕擷取畫面 2023-09-07 094805" src="https://github.com/Mikubill/sd-webui-controlnet/assets/144295360/098c4890-f426-4e64-bad7-3fd638a501d7">

<img width="870" alt="螢幕擷取畫面 2023-09-07 095034" src="https://github.com/Mikubill/sd-webui-controlnet/assets/144295360/9ad94439-154d-4403-90eb-de0811ab1237">

**Comment by drdancm** [comment]
After update to 1.1.408  the Preview Button is missing, otherwise things seem to work.
