### ISSUE TITLE
[Bug]: "Use Preview as input" gone

### ISSUE THREAD

**Issue by Hellrunner2k** [Mikubill/sd-webui-controlnet#2076]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

updated the extension and the essential "use preview as input" checkbox was gone. ... and someone closed an unresolved issue.

### Steps to reproduce the problem

update the extension

### What should have happened?

the essential "use preview as input" checkbox should not have vanished.

### Commit where the problem happens

Automatic1111

### Command Line Arguments

```Shell
Brave
```

### List of enabled extensions

https://github.com/Zyin055/Config-Presets
https://github.com/chrisgoringe/Styles-Editor.git
https://github.com/Bing-su/adetailer.git
https://github.com/deforum-art/deforum-for-automatic1111-webui.git
https://github.com/CMU-Perceptual-Computing-Lab/openpose
https://github.com/ashen-sensored/sd-dynamic-thresholding-rcfg
https://github.com/alemelis/sd-webui-ar.git
https://git.mmaker.moe/mmaker/sd-webui-color-enhance.git
https://github.com/Mikubill/sd-webui-controlnet
https://github.com/pk5ls20/sd-webui-controlnet-fastload.git
https://github.com/Uminosachi/sd-webui-inpaint-anything.git
https://github.com/antis0007/sd-webui-multiple-hypernetworks.git
https://github.com/huchenlei/sd-webui-openpose-editor.git <- vital to be used without preprocessor
https://github.com/wcde/sd-webui-refiner.git
https://github.com/continue-revolution/sd-webui-segment-anything.git
https://github.com/a2569875/stable-diffusion-webui-composable-lora.git
https://github.com/toshiaki1729/stable-diffusion-webui-dataset-tag-editor.git
https://github.com/AUTOMATIC1111/stable-diffusion-webui-wildcards.git
https://github.com/Coyote-A/ultimate-upscale-for-automatic1111
https://github.com/fishslot/video_loopback_for_webui.git
https://github.com/DingoBite/weight_gradient

### Console logs

```Shell
there are no errors in console. just loads control net. and i don't know where the logs are.
```

### Additional information

well... seems super straight forward to me... the checkbox is not there... bad

[lllyasviel](https://github.com/lllyasviel) commented:
If much needed, we should consider providing an option to show a fake toggle saying “Use preview as input” for user to select.

That toggle will not do anything because “Use preview as input” is already automated, but users who are accustomed to the old interface will be happier.

@Hellrunner2k

Author

i don't care about the literal checkbox... you are missing the point ... it's VITAL to an openPose workflow that you can use the editor independent from the preprocessor ... that the openpose editor still works even with disabled preprocessor ... some ppl are actual artists you know...

sorry your galaxy brain mod rubbed me the wrong way.

really appreciate the work... so .. you make a detection on an earlier created image... preprocessor to none ... edit ... send to controlNet ... make the next image ...
edit again.. adjust pose ... make the next image ...
(optional) save refined pose ... make detection to add ppl ... preprocessor to none ... load refined pose .. edit ... send to controlNet ... make the next image ... .. and so on
this workflow is busted now. ..

**Comment by lllyasviel** [comment]
"really appreciate the work... so .. you make a detection on an earlier created image... preprocessor to none ... edit ... send to controlNet ... make the next image ...
edit again.. adjust pose ... make the next image ...
(optional) save refined pose ... make detection to add ppl ... preprocessor to none ... load refined pose .. edit ... send to controlNet ... make the next image ... .. and so on"

this workflow has never existed in this software, if a pose is saved as image, openpose editor can not edit it.

people's memory about previous things is often inaccurate.

anything that is previously possible is still possible now.

if you edit the pose, now the software just use the edited pose.

**Comment by Hellrunner2k** [comment]
that workflow never existed... no, YOU didn't know about it. 

"pose is saved as image, openpose editor can not edit it.
... dismissive and offensive shit...
if you edit the pose, now the software just use the edited pose."

so ... i thought you CAN'T edit in the EDITor ... what is it?

So .. it CAN'T do all the things it did before... being working just as normal without preprocessor... and YOU should not do what you are doing here right now.. you are NOT the right kind of person to deal with issues... your impulsive behavior, dismissive attitude and fairly low IQ are creating enemies under friends.

**Comment by lllyasviel** [comment]
OpenPose editor can only edit detected poses. If you import pose as an image and set preprocessor as none, no previous or current versions of this extension can edit it.
If you detect pose and edit the pose with openpose editor in the current version, the software just uses the edited pose.
If you want to edit pose, you can just edit it like before.
If you want to iteratively edit poses according to generated results every time, you can drag results to controlnet, detect/edit whenever you want.
