### ISSUE TITLE
[Bug]:  Scribble/Sketch section preprocessor "invert (from white bg & black line)" is not showed.

### ISSUE THREAD

**Issue by coeyes** [Mikubill/sd-webui-controlnet#2078]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Scribble/Sketch section preprocessor "invert (from white bg & black line)" is not showed.

### Steps to reproduce the problem

1. Go to ControlNet tab
2. Press "Scribble/Sketch"
3. Press "[Preprocessor]" dropdown

### What should have happened?

it sould be show "invert (from white bg & black line)". 
because user image input may have a black line on a white background.

### Commit where the problem happens

webui: ver 1.6
controlnet: current main branch

### Command Line Arguments

```Shell
No
```

### List of enabled extensions

N/A

### Console logs

```Shell
N/A
```

### Additional information

N/A

**Comment by lllyasviel** [comment]
fixed
