### ISSUE TITLE
Warning: ControlNet failed to load SGM - will use LDM instead

### ISSUE THREAD

**Issue by fckbauer** [Mikubill/sd-webui-controlnet#2080]
I just installed, InPaint Anything/ Segment Anything and this issue appeared?  How do I fix it? I am on Mac M1.  Thanks!

**Comment by obirdobird** [comment]
SGM does not support M1

**Comment by fckbauer** [comment]
NVM. i just freshly installed the latest webUi version.  Since no one seems to know how to fix it.

**Comment by violatordead** [comment]
did you reinstall automatic1111 or just webui for control net?
