### ISSUE TITLE
[UI issue]: using ControlNet without preprocessor, impossible

### ISSUE THREAD

**Issue by Hellrunner2k** [Mikubill/sd-webui-controlnet#2081]
https://github.com/Mikubill/sd-webui-controlnet/issues/2036 https://github.com/Mikubill/sd-webui-controlnet/issues/2076

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

switching preprocessor to none resets UI, making further editing and using controlNet without overhead impossible.
and [lllyasviel](https://github.com/lllyasviel) keeps closing unresolved issues.

### Steps to reproduce the problem

OpenPose Editor does not work without preprocessor (at least UI wise).

### What should have happened?

[lllyasviel](https://github.com/lllyasviel) should have listened and the issue should have been treated with the respect it deserves.

### Commit where the problem happens

Automatic1111

### What browsers do you use to access the UI ?

Brave

### Command Line Arguments

```Shell
--xformers --medvram --no-half-vae
```

### List of enabled extensions

https://github.com/Zyin055/Config-Presets
https://github.com/chrisgoringe/Styles-Editor.git
https://github.com/Bing-su/adetailer.git
https://github.com/deforum-art/deforum-for-automatic1111-webui.git
https://github.com/CMU-Perceptual-Computing-Lab/openpose
https://github.com/ashen-sensored/sd-dynamic-thresholding-rcfg
https://github.com/alemelis/sd-webui-ar.git
https://git.mmaker.moe/mmaker/sd-webui-color-enhance.git
https://github.com/Mikubill/sd-webui-controlnet
https://github.com/pk5ls20/sd-webui-controlnet-fastload.git
https://github.com/Uminosachi/sd-webui-inpaint-anything.git
https://github.com/antis0007/sd-webui-multiple-hypernetworks.git
https://github.com/huchenlei/sd-webui-openpose-editor.git <- vital to be used without preprocessor
https://github.com/wcde/sd-webui-refiner.git
https://github.com/continue-revolution/sd-webui-segment-anything.git
https://github.com/a2569875/stable-diffusion-webui-composable-lora.git
https://github.com/toshiaki1729/stable-diffusion-webui-dataset-tag-editor.git
https://github.com/AUTOMATIC1111/stable-diffusion-webui-wildcards.git
https://github.com/Coyote-A/ultimate-upscale-for-automatic1111
https://github.com/fishslot/video_loopback_for_webui.git
https://github.com/DingoBite/weight_gradient

### Console logs

```Shell
there are no errors in console. just loads control net. and i don't know where the logs are.
```

### Additional information

that workflow never existed... no, YOU didn't know about it. 

[lllyasviel](https://github.com/lllyasviel) commented:
"pose is saved as image, openpose editor can not edit it.
people's memory about previous things is often inaccurate.
anything that is previously possible is still possible now.
if you edit the pose, now the software just use the edited pose."

so ... i thought you CAN'T edit in the EDITor ... which one is it?

and it CAN'T do all the things it did before... being working just as normal without preprocessor... and YOU should not do what you are doing here right now.. you are NOT the right kind of person to deal with issues... your impulsive behavior and dismissive attitude are offensive and are creating enemies among friends.

HISTORY: 
well... seems super straight forward to me... the checkbox is not there... bad

[lllyasviel](https://github.com/lllyasviel) commented:
If much needed, we should consider providing an option to show a fake toggle saying “Use preview as input” for user to select.

That toggle will not do anything because “Use preview as input” is already automated, but users who are accustomed to the old interface will be happier.

@Hellrunner2k

Author

i don't care about the literal checkbox... you are missing the point ... it's VITAL to an openPose workflow that you can use the editor independent from the preprocessor ... that the openpose editor still works even with disabled preprocessor ... some ppl are actual artists you know...

sorry your galaxy brain mod rubbed me the wrong way.

really appreciate the work... so .. you make a detection on an earlier created image... preprocessor to none ... edit ... send to controlNet ... make the next image ...
edit again.. adjust pose ... make the next image ...
(optional) save refined pose ... make detection to add ppl ... preprocessor to none ... load refined pose .. edit ... send to controlNet ... make the next image ... .. and so on
this workflow is busted now. ..

**Comment by lllyasviel** [comment]
## iterative editing with generated results

openpose (before edit)
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/19834515/9bb437fd-9e57-4f0d-9237-fb48528b08d9)
click "edit" and edit
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/19834515/31e87892-b0f8-4b61-961d-5e66e45243c5)
generate (after edit)
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/19834515/eaf8e2f9-0e04-41c2-9826-b4c3f523cbd5)
drag the generated image to detect and edit again
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/19834515/7196d0ec-1be3-4c45-b68e-37ad789f9111)
click "edit" and edit again
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/19834515/eb5fc1f3-6f53-498a-ac42-a7efc10921be)
generate again
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/19834515/51740c7b-c1a0-4cd7-9561-b48fe8c1959c)

## What if set preprocessor to none

In previous 1.1.238 with "Use preview as input", if users upload pose as image, there is no "edit" button
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/19834515/35571d5a-9b5d-4ef3-8ee5-7b59bf5e22d0)

In current 1.1.408, if users upload pose as image, there is no "edit" button, (same as before)
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/19834515/14ad5c7d-0033-4daa-9d7d-3d34b8b6bc27)

**Comment by lllyasviel** [comment]
if anyone is able to understand what is broken, please let us know

**Comment by lllyasviel** [comment]
Considering you have created same issues three times, before I close this, you may
1.	provide more descriptions so that I can understand what workflow is broken and what feature is impossible now. Right now, I cannot see anything broken, all previously possible things are still working.
2.	you may want to @huchenlei if you want someone else to help understand what happens. But you may still want to add more evidences otherwise other maintainers are also less likely to understand what is wrong.
3.	or this will be closed in 24 hours if nothing is added and no real problem can be verified.

**Comment by Hellrunner2k** [comment]
okay... lets get through this SLOWLY ... 
it seems to me you make the UI layout dependent on the preprocessor selection. This results in: if you DISABLE the preprocessor (setting it to none) it clears out everything, incl. the openpose edit. that should not happen. what if i have a nice edge detection.. or painted softedges myself ... I made an external program that generates openpose stick figures (hypothetical) ... i just want the controlNet Model to get to work on MY input not on the regular output of the preprocessor.
if that is already possible just link the openpose editor output to the controlNet model and do not kill everything when you select "none" in the preprocessors. ... what if i want to make a detection manually and use that image without the processor going to town on each frame?.. that should be possible... I can live with automation for ease of use for rookies... I NOT cool with taking AWAY functionality. ControlNet is the most important tool in stable diffusion.

**Comment by Hellrunner2k** [comment]
HUH.. will ya look at that... 
the preprocessor doesn't override the preview anymore when you edit it? Did it ever... Did i learn it wrong?

*time passed* 

so after intensive testing i found that the openPose preprocessor pipeline works seemingly differently than the others. it doesn't override the preview like the others do. everything works, fine... the workflow is preserved. PEW

I am equally embarrassed and sorry for the scene. It shows how important this is to me. I hope you can forgive me for my persistence and that you continue your work in the highest spirits. 

all the best wishes and appreciation
