### ISSUE TITLE
Proposal for the webui tab 

### ISSUE THREAD

**Issue by camenduru** [Mikubill/sd-webui-controlnet#209]
Hi @Mikubill  👋 thanks for the repo ❤ how about a tab like this collecting everything in a one place + https://github.com/Mikubill/sd-webui-controlnet/discussions/153

![controlnet_tab](https://user-images.githubusercontent.com/54370274/219922427-c6d27d4c-bd53-48c7-9306-a794e8ae8aa1.png)

working sample 

https://colab.research.google.com/github/camenduru/controlnet-colab/blob/main/a_certain_model_controlnet_colab.ipynb
https://github.com/camenduru/controlnet-colab/blob/main/a_certain_model_controlnet_colab.ipynb
https://github.com/camenduru/ControlNet-with-other-models

**Comment by lllyasviel** [comment]
Pherhaps not. we need to consider the support of https://www.reddit.com/r/StableDiffusion/comments/1152ius/mindblowing_controlnet_trick_mixed_composition/ and https://www.reddit.com/r/StableDiffusion/comments/115okp4/insane_light_composition_trick_contronet_blend/

**Comment by camenduru** [comment]
I see thanks @lllyasviel ❤
