### ISSUE TITLE
[Feature]: Disable controlnet during "highres-fix" pass per controlnet instead of global

### ISSUE THREAD

**Issue by AquilaAbriel** [Mikubill/sd-webui-controlnet#2091]
Right now the only way to disable control net during the highres fix pass seems to be by checking the "Do not apply ControlNet during highres fix" checkbox under ControlNet settings.

But I would much rather disable control net during highres fix on a per controlnet model basis.
That way, I could still have the "lineart" and "openpose" control active, but disable "tile/blur" for example.

I have no idea how complicated it would be to implement such a selective enable/disable switch, but if possible, I would really appreciate it.
A big thank you to the devs by the way! Without ControlNet, stable diffusion wouldn't be nearly as powerful as it is.

**Comment by huchenlei** [comment]
Merged into https://github.com/Mikubill/sd-webui-controlnet/issues/2146
