### ISSUE TITLE
[Bug]: controllite models no effect

### ISSUE THREAD

**Issue by CCRcmcpe** [Mikubill/sd-webui-controlnet#2092]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Kohya's controllite series model have no effect when any generation dimension is not multiple of 16, and does not print any errors to console.

### Steps to reproduce the problem

Load a controllite model, generate image using 1024x888, and notice it does not affect generation.

### What should have happened?

Generate using 1024x896 instead, notice this time it does have effects.

### Commit where the problem happens

webui: https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/924642331b13b73adbada3270a52cc5c7ae85ace
controlnet: https://github.com/Mikubill/sd-webui-controlnet/commit/b15636ed35eff934af69985bcdfbc407cfedfe7d

### Command Line Arguments

```Shell
Not related.
```

### List of enabled extensions

Not related. Experimented with all non-built in extensions disabled.

### Console logs

```Shell
Does not have any messages so not related.
```

**Comment by lllyasviel** [comment]
will take a look soon
