### ISSUE TITLE
REQEUST/BUG: Load Independent Control Image for t2i removed ?

### ISSUE THREAD

**Issue by Duemellon** [Mikubill/sd-webui-controlnet#2094]
Was the feature to use a control image in text2image removed?

Load Independent Control Image is an option in i2i but not t2i? Is this issue just me or was it removed? If it's removed can it be restored? I do use it.

**Comment by lllyasviel** [comment]
t2i always "Load Independent Control Image"

**Comment by Duemellon** [comment]
ah, I figured it out. I was loading a hand-drawn depth map (by turning off Preprocessor) but it wasn't following it. Turns out I had (at some point) activated a 2nd tab of ControlNet so that was interfering.

**Comment by Duemellon** [comment]
thanks
