### ISSUE TITLE
Hide hand option?

### ISSUE THREAD

**Issue by lllyasviel** [Mikubill/sd-webui-controlnet#210]
Perhaps we may consider hide the hand option because the model is not trained on hands. We have plan to extend our models a bit; and we may add these back after the model is finished. (Face keypoints is also in the consideration of us)

**Comment by Mikubill** [comment]
temporary disabled in https://github.com/Mikubill/sd-webui-controlnet/commit/3a5a12d96e5bb12f65c5599410a30bd08f1f6265.
