### ISSUE TITLE
[Bug]: Unable to start the AUTOMATIC1111 GUI

### ISSUE THREAD

**Issue by blue6659** [Mikubill/sd-webui-controlnet#2104]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

After installing the ControlNet plugin, I encountered difficulties launching AUTOMATIC1111 the following day. However, upon removing the plugin's folder, everything returned to normal.

### Steps to reproduce the problem

help me,thanks

### What should have happened?

help me,thanks

### Commit where the problem happens

webui: 
controlnet: 

### Command Line Arguments

```Shell
123
```

### List of enabled extensions

123

### Console logs

```Shell
123
```

**Comment by Kansaku** [comment]
Cant confirm. latest controlnet extension working correctly on latest automatic Version 1.6.0
Maybe check if any of your extensions interfere with the controlnet extension.
Also, if you seriously want some help with it, providing webui and controlnet versions or errors from the command line would help very much.
Its hard to help you with only some vague information, and the ppl behind controlnet work very hard for this extension^^

But as i said. First I would try to disable all other extensions and look for one that might errors your webui in combination with controlnet enabled.

**Comment by Yuhyeong** [comment]
u could try upgrading the gradio

**Comment by caboosetp** [comment]
I don't know if I'm running into the same problem they are, but I was unable to start the web-ui in the DirectML fork of automatic1111. I got the same error as in [Mikubill/sd-webui-controlnet#1630](https://github.com/Mikubill/sd-webui-controlnet/issues/1630)

> Loading model deliberate_v3.safetensors [aadddd3d75] (2 out of 3)██████████████████████| 20/20 [00:07<00:00,  5.86it/s]
> Loading weights [aadddd3d75] from G:\stable\stable-amd\models\Stable-diffusion\deliberate_v3.safetensors
> Creating model from config: XXXXXXXXX\configs\v1-inference.yaml
> [F D:\a\_work\1\s\pytorch-directml-plugin\torch_directml\csrc\engine\dml_util.cc:118] Invalid or unsupported data type.

I figured out it was when loading deliberate v3. Since it was the last checkpoint I had loaded, I crashed on startup every time. I changed the startup checkpoint to a different one and everything works fine as long as I avoid trying to pick deliberate v3.

And I did update gradio first.

**Comment by YumoeZhung** [comment]
> u could try upgrading the gradio

This is usefull for me! And after a long time wait, ControlNet is appear in the interface! Thank U!

**Comment by luminousluna** [comment]
Hey folks, had similar issue, installing controlnet took forever, reinstalled everything, installed from url nothing worked.
without the controlnet folder the gui started as usual. 

The solution in my case was to delete the **venv** folder and reloading the data via usual webui-user bat and the gui starts without issues.
