### ISSUE TITLE
[Bug]: When sending a image from txt2img to img2img, controlnet settings get transfered

### ISSUE THREAD

**Issue by Diamond-Shark-art** [Mikubill/sd-webui-controlnet#2112]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Most of the time i dont use controlnet in txt2img. I send images i like to img2img and use Tile for upscaling. It was set it and forget it.

Now when i send a image to img2img the controlnet settings get send to. So when not using anything the Enable checkmark is unchecked. When for example i used openpose, openpose prepocessor and model are loaded in img2img. So everytime i either have to recheck Enable or reselect Tile.

### Steps to reproduce the problem

1. Go to txt2img, and send it to img2img
2. txt2img controlnet settings are also send to img2img.
3. ...

### What should have happened?

Dont know if this is intentional, but maybe an option to disable this?

### Commit where the problem happens

webui: 1.6.0
controlnet: latest, 1.4.140

### What browsers do you use to access the UI ?

Apple Safari, Microsoft Edge

### Command Line Arguments

```Shell
--opt-sdp-attention --no-half-vae --update-all-extensions --listen
```

### List of enabled extensions

Extension	URL	Branch	Version	Date	Update
--sd-webui-ar-plus	https://github.com/LEv145/--sd-webui-ar-plus	main	[a7ac063a](https://github.com/LEv145/--sd-webui-ar-plus/commit/a7ac063a11675d0b8e7d64fb0b2fe4084926995b)	2023-07-30 13:45:00	unknown
CloneCleaner	https://github.com/artyfacialintelagent/CloneCleaner.git	main	[76348e1a](https://github.com/artyfacialintelagent/CloneCleaner/commit/76348e1a70fac280e1f02569c92ece46796a458d)	2023-06-26 18:42:33	unknown
DWPose	https://github.com/IDEA-Research/DWPose	onnx	[c6af7ac1](https://github.com/IDEA-Research/DWPose/commit/c6af7ac1d3a3cc67cef6555b6da66f4e10097f85)	2023-08-17 03:08:01	unknown
Stable-Diffusion-Webui-Civitai-Helper	https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper	main	[920ca326](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/commit/920ca3267f789a72e3225c99f069bf0be0db795d)	2023-05-23 13:53:22	unknown
clip-interrogator-ext	https://github.com/pharmapsychotic/clip-interrogator-ext.git	main	[0f1a4591](https://github.com/pharmapsychotic/clip-interrogator-ext/commit/0f1a4591f82b93859a1b854afb79494f39384662)	2023-09-10 03:35:46	unknown
openpose-editor	https://github.com/fkunn1326/openpose-editor.git	master	[db07b9c6](https://github.com/fkunn1326/openpose-editor/commit/db07b9c69c224d1d64f9f70713b2908f2da29912)	2023-09-10 02:15:17	unknown
sd-civitai-browser-plus	https://github.com/BlafKing/sd-civitai-browser-plus.git	main	[c1b13e12](https://github.com/BlafKing/sd-civitai-browser-plus/commit/c1b13e1279290f9f30ed54717c8c7a26b76fbfbe)	2023-09-13 08:32:56	unknown
sd-dynamic-prompts	https://github.com/adieyal/sd-dynamic-prompts.git	main	[39c06b30](https://github.com/adieyal/sd-dynamic-prompts/commit/39c06b30409df6259c4430338123f7d4e05d8dc1)	2023-08-28 11:21:32	unknown
sd-extension-system-info	https://github.com/vladmandic/sd-extension-system-info.git	main	[83dd4d8f](https://github.com/vladmandic/sd-extension-system-info/commit/83dd4d8f65511af720ddb034125fe4ac0a46fb18)	2023-09-07 16:40:20	unknown
sd-webui-agent-scheduler	https://github.com/ArtVentureX/sd-webui-agent-scheduler.git	main	[097fe4e5](https://github.com/ArtVentureX/sd-webui-agent-scheduler/commit/097fe4e5c97612520b3e4d80d44f36088c53e2c4)	2023-09-11 16:22:42	unknown
sd-webui-controlnet	https://github.com/Mikubill/sd-webui-controlnet.git	main	[e67e0177](https://github.com/Mikubill/sd-webui-controlnet/commit/e67e017731aad05796b9615dc6eadce911298ea1)	2023-09-11 09:56:10	unknown
sd-webui-openpose-editor	https://github.com/huchenlei/sd-webui-openpose-editor	main	[870f9113](https://github.com/huchenlei/sd-webui-openpose-editor/commit/870f9113c2d43575838fb7eba9f2a629cbbd74f6)	2023-08-27 04:43:59	unknown
sd-webui-prompt-all-in-one	https://github.com/Physton/sd-webui-prompt-all-in-one	main	[c925945f](https://github.com/Physton/sd-webui-prompt-all-in-one/commit/c925945f4d70fb4831e042fb8407351d78a56c82)	2023-09-11 12:12:36	unknown
sd-webui-reactor	https://github.com/Gourieff/sd-webui-reactor	main	[376c19c6](https://github.com/Gourieff/sd-webui-reactor/commit/376c19c62fdd280b2b1f3f6483204d479978c0a2)	2023-09-04 13:38:20	unknown
sd-webui-regional-prompter	https://github.com/hako-mikan/sd-webui-regional-prompter	main	[0b3ac220](https://github.com/hako-mikan/sd-webui-regional-prompter/commit/0b3ac22095fd9129e949effb4dda76797a5a2efc)	2023-09-05 13:23:27	unknown
stable-diffusion-webui-images-browser	https://github.com/AlUlkesh/stable-diffusion-webui-images-browser.git	main	[9f95e6d4](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/commit/9f95e6d4812ca7acb3ec56cbf45fbc85aef0236d)	2023-09-11 14:55:51	unknown
stable-diffusion-webui-wildcards	https://github.com/AUTOMATIC1111/stable-diffusion-webui-wildcards	master	[c7d49e18](https://github.com/AUTOMATIC1111/stable-diffusion-webui-wildcards/commit/c7d49e18398a95f2d13e2e4c063fe2f63fc2a432)	2023-07-30 22:08:05	unknown
ultimate-upscale-for-automatic1111	https://github.com/Coyote-A/ultimate-upscale-for-automatic1111.git	master	[728ffcec](https://github.com/Coyote-A/ultimate-upscale-for-automatic1111/commit/728ffcec7fa69c83b9e653bf5b96932acdce750f)	2023-09-09 12:47:23	unknown
z-adetailer	https://github.com/Bing-su/adetailer	main	[a0b4c56e](https://github.com/Bing-su/adetailer/commit/a0b4c56eb75eceabf07f2ede28986a58cef2bebe)	2023-09-10 15:14:54	unknown
LDSR	[built-in](https://github.com/Mikubill/sd-webui-controlnet/issues/new?assignees=&labels=bug-report&projects=&template=bug_report.yml&title=%5BBug%5D%3A+)	None			
Lora	[built-in](https://github.com/Mikubill/sd-webui-controlnet/issues/new?assignees=&labels=bug-report&projects=&template=bug_report.yml&title=%5BBug%5D%3A+)	None			
ScuNET	[built-in](https://github.com/Mikubill/sd-webui-controlnet/issues/new?assignees=&labels=bug-report&projects=&template=bug_report.yml&title=%5BBug%5D%3A+)	None			
SwinIR	[built-in](https://github.com/Mikubill/sd-webui-controlnet/issues/new?assignees=&labels=bug-report&projects=&template=bug_report.yml&title=%5BBug%5D%3A+)	None			
canvas-zoom-and-pan	[built-in](https://github.com/Mikubill/sd-webui-controlnet/issues/new?assignees=&labels=bug-report&projects=&template=bug_report.yml&title=%5BBug%5D%3A+)	None			
extra-options-section	[built-in](https://github.com/Mikubill/sd-webui-controlnet/issues/new?assignees=&labels=bug-report&projects=&template=bug_report.yml&title=%5BBug%5D%3A+)	None			
mobile	[built-in](https://github.com/Mikubill/sd-webui-controlnet/issues/new?assignees=&labels=bug-report&projects=&template=bug_report.yml&title=%5BBug%5D%3A+)	None			
prompt-bracket-checker	[built-in](https://github.com/Mikubill/sd-webui-controlnet/issues/new?assignees=&labels=bug-report&projects=&template=bug_report.yml&title=%5BBug%5D%3A+)	None

### Console logs

```Shell
.
```

**Comment by fbellgr** [comment]
I also reported issues regarding sending to img2img here: #1997.

In fact, it resets most contolnet settings. The only "workaround" is to have a preset that you reapply each time you send to img2img, and it is rather counter productive. It used to be set and forget, as you say, which made it more productive.

My solution for now is to actually force it to eeec9d8d6d31784a1583744528402f1bc7bcbd3d.

**Comment by Diamond-Shark-art** [comment]
It started happening to me only 2 days ago, i see you have this problem a lot longer then me but its exactly the same issue yes. Even though i have the autoupdate enabled in A1111. I will look into how to roll back to eec9d8, thanks for the tip.

**Comment by fbellgr** [comment]
Maybe you did not systematically update the extensions each time there were new commits. I use vladmandic/automatic amd it updates extensions automatically.

**Comment by fbellgr** [comment]
To roll back the extension, simply open a terminal to the extension folder and run:

`git checkout eeec9d8d6d31784a1583744528402f1bc7bcbd3d`

I don't know if automatic1111 updates the extension when launching. I don't think so, which would be why you're just having the issue now. I think you have to update explicitly from the extensions tab in automatic1111, so you should be fine.

With vladmandic/automatic, there is a `--skip-git` command line param to disable fetching new commits. Pretty sure you don't have that.

**Comment by Diamond-Shark-art** [comment]
I removed the update all extensions arg. I used that because when using --listen i can acces the webui running on my pc from my laptop. But with that argument updates or installs dont work. I reverted to the commit above, but i still have the same issue. As a test i enabled controlnet in txt2img with openpose, send a image to img2img while Tile was enabled there. It kept Tile selected but the openpose preprocessor and model where loaded.

**Comment by fbellgr** [comment]
when I say the extension folder, I mean of course `extension/sd-webui-controlnet`.

**Comment by fbellgr** [comment]
This was closed, but the behaviour remains the same. Settings are transfered from text2img over to img2img, which overrides whatever workflow you were using in img2img.

Also, now when selecting the control type Title/Blur, the preprocessor is automatically selected, but not the model. In fact, the models list is no longer pre-filled.

**Comment by huchenlei** [comment]
- In A1111 1.6.0+, there is no such button in txt2img panel to send settings to img2img.
- Both preprocessor and model are automatically selected. Model will be set to None if you don't have any valid model available for the control type.

**Comment by fbellgr** [comment]
There is in vladmandic/automatic. I did not know they removed it in A1111.

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/27892962/c8b2c83a-a953-4b4e-84b7-c30d32aefb4a)

**Comment by fbellgr** [comment]
Here. The button is the one inside the red box. And clicking on it does exactly what I described.

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/27892962/95e3ef2e-dc82-4867-912a-f1083b3d9002)

**Comment by huchenlei** [comment]
It is the expected behaviour as sending to img2img carries everything from infotext, and paste in img2img panel. This is an A1111 feature.

There was a period where ControlNet's infotext pasting was broken, but we have fixed it several months ago.

**Comment by fbellgr** [comment]
That is strange. Why assume that we want to use controlnet exactly the same in both tabs on the same image?

Until eeec9d8d6d31784a1583744528402f1bc7bcbd3d, it kept the settings in both tabs independently. Which means you couls do a simple image with a pose in one tab and use sf ultimate upscale in img2img without ever having to change controlenet settings in either tab.

**Comment by huchenlei** [comment]
You need to ask A1111/SDNext to fix this, as we are only implementing the infotext protocol.

**Comment by fbellgr** [comment]
Worth a try. I'd point out that if I check out eeec9d8d6d31784a1583744528402f1bc7bcbd3d in either UI, it works as it used to. So here is where things changed.

Now, if you're saying that the old controlnet behaviour was wrong and that now it works as intended, I mean, I guess you decide how your app works, but here is where the change occurred.

**Comment by huchenlei** [comment]
Infotext was fixed on Aug23, 2023 https://github.com/Mikubill/sd-webui-controlnet/commit/cde4619c5dea047589b82a42aaba6a3900e965d9. You can checkout one commit before that one if you prefer infotext broken.

**Comment by fbellgr** [comment]
I anyone is interested in having something resembling the original behaviour, a neat trick is to go through the Process tab.

- Generate image
- Send to Process 
- Sent to Image (from the source panel)

This way you do not have to copy & paste the image + positive prompt + negative prompt.
And ControlNet settings are preserved.

**Comment by Diamond-Shark-art** [comment]
Thanks, i want to try this. But where do i find the 'Send to Process' option? Is that in A1111?

**Comment by fbellgr** [comment]
In A111, it's called Extras, and it is the ruler icon.

But sorry, this wont as well in A111 because their Extras does not have the same buttons in the source panel as SD.Next.

Though you can to an upscale of 1 without upscaler then user the send to img2img icon.

Kind of weird, but it works.

**Comment by Diamond-Shark-art** [comment]
Good to know this is an option in SD.Next, will look into it. Thanks!

**Comment by fbellgr** [comment]
As I said, the upscale of 1 in Extras without an upscaler is a similar uglier workaround in A1111.
