### ISSUE TITLE
[Bug]: Tile doesn't work in SD 1.6

### ISSUE THREAD

**Issue by dongyun-kim-arch** [Mikubill/sd-webui-controlnet#2115]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Trying to use tile resamples in Controlnet.

The tab is changed from tile to 'Tile/Blur'.

The result looks blurred, not tile applied.

### Steps to reproduce the problem

1. Go to Tile/Blur in Controlnet
2. Import tile_resample and control_v11f1e_sd15_tile model
3. The result looks blurry

### What should have happened?

It is supposed to add more detail, not blur.

### Commit where the problem happens

webui: automatic1111
controlnet: newest

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### List of enabled extensions

Controlnet.

### Console logs

```Shell
Not error.
```

**Comment by fckbauer** [comment]
<img width="616" alt="Screenshot 2023-09-15 at 6 23 32 PM" src="https://github.com/Mikubill/sd-webui-controlnet/assets/139547063/625aa1a9-5825-4160-a843-bd7572b9e2c5">
<img width="648" alt="Screenshot 2023-09-15 at 6 23 55 PM" src="https://github.com/Mikubill/sd-webui-controlnet/assets/139547063/8d5b2659-daad-419a-b786-07ab5267aa6b">


 Use these settings instead :)
