### ISSUE TITLE
[Bug]: txt2img API ignores sd_model_checkpoint when enabling controlnet

### ISSUE THREAD

**Issue by cdavidr1** [Mikubill/sd-webui-controlnet#2120]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I keep generating the same controlnet input image, without the prompt affecting it.

When I comment out the alwayson_scripts..controlnet then it generates but without controlnet

Not sure why

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/123332084/6a91ed02-2185-43cb-841c-e9883637e9cd)

### Steps to reproduce the problem

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/123332084/4182bbda-14e2-49ec-bce3-8ca695086f6b)

### What should have happened?

It should take all settings into effect

Using SD1.6

### Commit where the problem happens

webui: 
controlnet: 

### Command Line Arguments

```Shell
no
```

### List of enabled extensions

n/a

### Console logs

```Shell
n/a
```

**Comment by huchenlei** [comment]
See example in https://github.com/Mikubill/sd-webui-controlnet/blob/main/example/txt2img_example/api_txt2img.py.
