### ISSUE TITLE
[Bug]: Generated Image From Inpaintinng Model (Outpainting method) differs from what it should be

### ISSUE THREAD

**Issue by YouYouTheBoxx** [Mikubill/sd-webui-controlnet#2121]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Every time I generate a new outpainted image using Inpaint Only+Lama preprocessor and Inpainting model for SD 1.5, two images gets generated. 

Only the second one which is always an unfinished image (and also stays the same wherever seed change) is the one I would see finished as my final outpainting image.

### Steps to reproduce the problem

1. Go to Automatic1111 txt2img tab
2. Select an image in Controlnet first unit
3. Choose Inpaint Only+Lama preprocessor and Inpaiting Controlnet Model SD1.5 v11
4. Change the size of the image width.
5. Hit generate.

### What should have happened?

I should only have the second image fully generated.

### Commit where the problem happens

webui: 1.6.0
controlnet: 5ae9b4a1

### What browsers do you use to access the UI ?

Google Chrome, Microsoft Edge

### Command Line Arguments

```Shell
Nothing needed here
```

### List of enabled extensions

Nothing needed here

### Console logs

```Shell
Nothing needed here
```

**Comment by omercraft** [comment]
I have the exact same issue. not sure what to do yet
