### ISSUE TITLE
[Feature Request]: Control Net image file name with EXIF

### ISSUE THREAD

**Issue by gymdreams8** [Mikubill/sd-webui-controlnet#2125]
_This was originally posted to the A1111 repo, but I was asked to post here instead._

Right now, the parameters saved with the images contain almost everything required to reproduce the image — with the exception of the image name. Often, and especially when using with the Shuffle control net, I would try many similar images in order to apply the correct style. The issue with this workflow means that while I know approximately which collection of images I have used to drive the style, I never quite know which one I used after the fact.

What I would like to see is if the name of the image used to drive the control nets can be saved as part of the parameters. 

Since this can potentially create a privacy issues (e.g. path names containing username etc), perhaps what you could do is add options in the settings such that users can select:

- do not include any image filenames
- include image filename
- include full path

This will help greatly for me (and no doubt many users) to (re)work on images produced months before.

I am requesting this feature on this repo because I believe that the EXIF saving happen here, and you can read the parameters  via the dict sent from the extension — at least, when I read the source a while ago, that appears to be the behavior.

I’ll be happy to open another issue on the extension if you feel that making the request there would be more appropriate.

Thanks + rock on!

### Proposed workflow

1. Use an image in a control net
2. When the image is saved, include the name of the image alongside the exif parmaters 
3. If the generated image is dragged into PNG info, then subsequently sent to txt2img, attempt to load from the path if available.

Original issue: https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/13308 — with some comments that could be of interests.

**Comment by huchenlei** [comment]
Image names are not available when gradio handles image upload. So not viable right now.
