### ISSUE TITLE
[Bug]: Unexpected behaviour when doing img2img batch process.

### ISSUE THREAD

**Issue by szriru** [Mikubill/sd-webui-controlnet#2128]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

This issue occurs for me since I have updated auto1111 to the latest version (version 1.6.0 5ef669de080814067961f28357256e8fe27544f4 )

**When doing img2img batch process with controlnets' batch tab on, generated images won't be put in the specified output folder nor default output folder (output/img2img-images/~/).**  (Where did they go?)
However, when I switch the tab to Single Image, it worked fine except the name of generated images are different from what it used to be.  (expected: same name of the original image from img2img, result: order number + expected name)

- pls make an option to name them by a convensional way. I don't like it.
- Is this a new expected feature? If so, why is there still "batch tab".

Pls consider fix this issue. Thank you.

-----------------------

original image name: 00003.png
expected: 00003.png
result: 00001-00003.png

-----------------------

**This used to work fine, but it doesn't now. Where did the generated images go?**
![スクリーンショット 2023-09-18 214744](https://github.com/Mikubill/sd-webui-controlnet/assets/106813119/c264ce05-137d-4bcc-87d6-389f4a8cf643)

**This does work fine, but the names of generated images are order number + expected name**
![スクリーンショット 2023-09-18 214736](https://github.com/Mikubill/sd-webui-controlnet/assets/106813119/09da597f-90e9-4b2b-b40b-4fc82c0d1f03)

### Steps to reproduce the problem

auto1111 -> img2img -> Generation -> batch.
fill in "input directory", "output directory", "inpaint batch mask directory".
and select "batch" tab in a controlnet unit.

### What should have happened?

Generated images go in a specified output folder. And names are same as original images

### Commit where the problem happens

webui: 1.6.0 (5ef669de080814067961f28357256e8fe27544f4)
controlnet: [0cfc88b6](https://github.com/Mikubill/sd-webui-controlnet/commit/0cfc88b6a892076d199e68c02e9c306ac6ab2ead)

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
./webui.bat --xformers
```

### List of enabled extensions

![スクリーンショット 2023-09-18 221909](https://github.com/Mikubill/sd-webui-controlnet/assets/106813119/9c39fd24-14a7-4fb8-8673-abed610243ac)

### Console logs

```Shell
no errors
```

**Comment by roshea6** [comment]
I am experiencing a similar issue with A1111 v1.6.0-RC, ControlNet v1.1.401 and fd37e9fc. When I use the Controlnet unit normally it works totally fine and saved my output images during batch img2img. But when I use the Upload independent control image and select the batch option for that it stops saving my output images. 

I tried turning on the sd_save_intermediate_images extension (https://github.com/AlUlkesh/sd_save_intermediate_images) to see if I could save any images at all and it saved all the intermediate images but still did not save the final image.

**Comment by andynakal** [comment]
it is related to this issue
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/13172

**Comment by huchenlei** [comment]
Confirm fixed in latest A1111.
