### ISSUE TITLE
Controlnet Openpose doesnt take costum input

### ISSUE THREAD

**Issue by demirklvc** [Mikubill/sd-webui-controlnet#214]
<img width="1440" alt="Bildschirmfoto 2023-02-19 um 12 42 30" src="https://user-images.githubusercontent.com/78754525/219945788-b4b62136-bccf-4d42-88eb-6896ec65641e.png">

How to fix? been using this new extension. Tried to send it with the extension to Control Net aswell as downloading my costum Pose mask and putting the File in.

https://github.com/fkunn1326/openpose-editor

By the way: Ive tried also without Scribble mode of course.

**Comment by Mikubill** [comment]
set preprocessor to none.

**Comment by demirklvc** [comment]
thanks alot.
