### ISSUE TITLE
[Bug]: White brush on white canvas

### ISSUE THREAD

**Issue by gabeacid** [Mikubill/sd-webui-controlnet#2141]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

After creating a new canvas in control unit the standard brush is white coloured. After change the preprocessor to lineart/scrible/invert etc. the brush is still white. I can't find any settings to change the brush color.

### Steps to reproduce the problem

1. Go to Control net unit 
2. Create new Canvas
3. Try to draw on canvas with different preprocessor settings like lineart / scribble or invert

### What should have happened?

After getting a new canvas the brush needs to be black or inverted like in the past.

### Commit where the problem happens

controlnet: After commit 5fc952793aa97bdd0078574b3be8bc98e1fcf2cd

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--api --opt-split-attention --medvram
```

### List of enabled extensions

builtins
openpose-editor
posex
sd-webui-controlnet
ultimate-upscale-for-automatic1111

### Console logs

```Shell
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Launching Web UI with arguments: --api --opt-split-attention --medvram
No module 'xformers'. Proceeding without it.
2023-09-23 20:58:15,556 - ControlNet - INFO - ControlNet v1.1.410
ControlNet preprocessor location: ...\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-09-23 20:58:15,736 - ControlNet - INFO - ControlNet v1.1.410
Loading weights [cc6cb27103] from ...\stable-diffusion\v1-5-pruned-emaonly.ckpt
Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.
Startup time: 18.0s (prepare environment: 4.5s, import torch: 5.3s, import gradio: 2.0s, setup paths: 1.3s, initialize shared: 0.4s, other imports: 0.9s, setup codeformer: 0.2s, load scripts: 1.9s, create ui: 0.6s, gradio launch: 0.7s, add APIs: 0.1s).
Creating model from config: ...\stable-diffusion-webui\configs\v1-inference.yaml
Applying attention optimization: Doggettx... done.
Model loaded in 15.0s (load weights from disk: 7.1s, create model: 0.5s, apply weights to model: 2.4s, apply half(): 1.3s, calculate empty prompt: 3.6s).
```

**Comment by ottodeng** [comment]
same issue with me.

**Comment by wimdoan** [comment]
<img width="512" alt="image" src="https://github.com/Mikubill/sd-webui-controlnet/assets/1529662/fc3c7b02-c67e-477b-b08b-d7acb2f1f2d8">
<img width="624" alt="image" src="https://github.com/Mikubill/sd-webui-controlnet/assets/1529662/ee494ea0-027c-4896-803f-f4e249e93330">
set the brush color here

**Comment by ottodeng** [comment]
@wimdoan works, many thanks!!!!

**Comment by hnmas** [comment]
> set the brush color in img2img settings <img alt="image" width="512" src="https://private-user-images.githubusercontent.com/1529662/277995609-fc3c7b02-c67e-477b-b08b-d7acb2f1f2d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTM2OTEwOTYsIm5iZiI6MTc1MzY5MDc5NiwicGF0aCI6Ii8xNTI5NjYyLzI3Nzk5NTYwOS1mYzNjN2IwMi1jNjdlLTQ3N2ItYjA4Yi1kN2FjYjJmMWYyZDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDcyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA3MjhUMDgxOTU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTljYzk3NzllODljNThjMDhiYjg0ZmNmYjIxMWExNmU3NTFmMGJkZTAzMjFmMjk0NDUyODgyMGFkNWVmOTAxOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.6SUphHj2YGd6d824xhgrqBwYrbZAEDuenFt9dyU53ss"> <img alt="image" width="624" src="https://private-user-images.githubusercontent.com/1529662/277995871-ee494ea0-027c-4896-803f-f4e249e93330.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTM2OTEwOTYsIm5iZiI6MTc1MzY5MDc5NiwicGF0aCI6Ii8xNTI5NjYyLzI3Nzk5NTg3MS1lZTQ5NGVhMC0wMjdjLTQ4OTYtODAzZi1mNGUyNDllOTMzMzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDcyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA3MjhUMDgxOTU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzY3MTkwNDFjNGFmZGY2YWE3OTI1ZDU3YTlmZDlkN2Q3NzQzYTY2ZjRkMzE4OTdiMGQyNTU2ZWI0MzA1OTVmNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.xXnhJDbP5-zBkQ6ekTUcEG3sEbLJy8BhiUWFOFLLTA0">

where can find this setting?
