### ISSUE TITLE
[Bug]: "Loopback" not doing anything

### ISSUE THREAD

**Issue by MotherSoraka** [Mikubill/sd-webui-controlnet#2145]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

No matter what i do the [Loopback] feature does not have any effect.

It's supposed to feed the latest generated image back to the Control-net when doing Batch img2img processing, but it does not happen.

Uploading an image or nothing at all, or Switching to Batch mode and linking to the the batch output folder either with a single reference image or nothing at all, [Loopback] has 0 effects on the output. clearly not looping back the output back to the controlnet.

### Steps to reproduce the problem

1. Go to img2img tab and try a batch process and enable a controlnet like TemporalNet or Tiles style or anything.
2. Enable "Upload independent control image". (Either upload an image or nothing at all, or Switch to Batch mode and link to the the batch output folder either with a single reference image or nothing at all)
3. Enable [Loopback].
4.Hit Generate, and notice how Loopback has 0 effects.

### What should have happened?

The latest generated image should be fed back into the Controlnet's preprocessor .

### Commit where the problem happens

**webui:** 
version: [v1.6.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5ef669de080814067961f28357256e8fe27544f4)  •  python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.41.2  •  checkpoint: [879db523c3](https://google.com/search?q=879db523c30d3b9017143d56705015e15a2cb5628762c11d086fed9538abd7fd)

**controlnet:** 
[7a4805c8] (https://github.com/Mikubill/sd-webui-controlnet/commit/7a4805c8ea3256a0eab3512280bd4f84ca0c8182)

### Command Line Arguments

```Shell
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=--enable-insecure-extension-access --xformers --api --gradio-queue --disable-safe-unpickle --skip-install

call webui.bat
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/72297825/d576a9ae-3c41-4f7d-8cc1-a4a8615c797c)

### Console logs

```Shell
No Errors occurring.
```

**Comment by huchenlei** [comment]
Img2img loopback is working as expected in lastest version of A1111 (1.7.0) and ControlNet extension (1.1.424).
