### ISSUE TITLE
Separate bypass highres fix to units & only apply during highres fix

### ISSUE THREAD

**Issue by Aeka0** [Mikubill/sd-webui-controlnet#2146]
Currently, there is a checkbox to allow to bypass ControlNet during Highres fix, which is very useful for enhancing the quality of images in specific scenarios. However, when using ControlNet for stylization, there may be times when it is necessary to do the opposite - apply only during Highres fix without applying it in the initial stages.

In some cases, some users' expectations may be more complex: it could be used only for Highres fix, only not used for Highres fix, or fully apply throughout one unit and only in a certain stage in another unit.

Maybe it's better to consider moving the option from the settings to the basic functionality of units, allowing users to choose when to enable it at each stage for each unit. If this can be achieved, it would be very helpful.

**Comment by huchenlei** [comment]
Implemented in https://github.com/Mikubill/sd-webui-controlnet/pull/2379.
