### ISSUE TITLE
In image-to-image (i2i) mode, I couldn't find the preview feature.

### ISSUE THREAD

**Issue by Lvjinhong** [Mikubill/sd-webui-controlnet#2160]
Hello, I am using version 1.1.410 of ControlNet, and I have noticed that the image-to-image mode cannot activate previews. It only allows independent image control. I would like to know if it's intended that image-to-image mode doesn't support previews like text-to-image mode. If not, how can I adjust poses similar to text-to-image mode without enabling independent upload control?

This is how it works in text-to-image mode.：

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/96970081/429a7227-8870-4f1b-a686-949326e65acc)

This is how it works in image-to-image mode (including redrawing, etc.).
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/96970081/34c445b1-f1d5-421b-ae03-01a6050dd538)

**Comment by lllyasviel** [comment]
load same image to CN

**Comment by Lvjinhong** [comment]
thanks
