### ISSUE TITLE
[Bug]: Add extentions is disable

### ISSUE THREAD

**Issue by Neo-Crucifer** [Mikubill/sd-webui-controlnet#2161]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Hi ! I´m new here ! 

I have installed SD in my PC to learn how it works and I´m trying to upload some models to work with the SD, but when I try to upload the .pth files appers a message saying the option to upload file is disabled and I need a push request. What that means ? Someone needs to allow me to upload a model ? How can I upload the models I have downloaded in hugginface ?

### Steps to reproduce the problem

1. Go to .... https://github.com/Mikubill/sd-webui-controlnet/tree/main/models
2. Press ....Add file 
3. Upload files
4. Message : "Uploads are disabled. File uploads require push access to this repository."

### What should have happened?

I go to the Add file and upload the models I had downloaded.

### Commit where the problem happens

webui: I don´t know what that means.
controlnet: v.1.1.410

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No.
```

### List of enabled extensions

Controlnet
LDSR
Lora
ScuNET
SwinIR
canvas-zoom-and-pan
extra-option-section
mobile

### Console logs

```Shell
I don´t know, I only start to use this program.
```

### Additional information

Well, as I said, I´m new here and I´m trying to learn how to use SD. I´m following a tutorial in the internet and in this tutorial it´s asked to download these models in Hugginface.

**Comment by huchenlei** [comment]
You do not need to upload models to the github repo. You need to download models from huggingface and put them in your local A1111 models directory.
