### ISSUE TITLE
"controlnet is enabled but no input image is given"

### ISSUE THREAD

**Issue by avivedri** [Mikubill/sd-webui-controlnet#2164]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Yesterday I installed Stable Diffusion and ControlNet, and after a few hours control stopped working:

I've uninstalled everything and installed again, worked fine until just now- the same exact problem returned.

This is the video I've referred to when installing: https://www.youtube.com/watch?v=onmqbI5XPH8

### Steps to reproduce the problem

1. Install sd with cnet
2. insert a photo cnet
3. Generate a photo

### What should have happened?

Produce an image that incorporates cnet

### Commit where the problem happens

webui: 1.6.0
controlnet: 1.1

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
—lowvram
```

### List of enabled extensions

Only cnet

### Console logs

```Shell
*** Error running process: C:\Program Files\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py

Traceback (most recent call last):

File "C:\Program Files\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 619, in process

script.process(p, *script_args)

File "C:\Program Files\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 977, in process

self.controlnet_hack(p)

File "C:\Program Files\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 966, in controlnet_hack

self.controlnet_main_entry(p)

File "C:\Program Files\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 696, in controlnet_main_entry

input_image, image_from_a1111 = Script.choose_input_image(p, unit, idx)

File "C:\Program Files\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 608, in choose_input_image

raise ValueError('controlnet is enabled but no input image is given')

ValueError: controlnet is enabled but no input image is given
```

**Comment by Dreamz-Dziner** [comment]
This exact issue has been driving me crazy since last 2-3 days. Deleted controlnet and reinstalled almost everything from controlnet extension(including old versions), venv folder, xformers. Still struggling to solve the issue. I noticed this in txt2img first and now even in img2img its happening.

**Comment by avivedri** [comment]
> This exact issue has been driving me crazy since last 2-3 days. Deleted controlnet and reinstalled almost everything from controlnet extension(including old versions), venv folder, xformers. Still struggling to solve the issue. I noticed this in txt2img first and now even in img2img its happening.

Can you please inform me if you ever fix it?

**Comment by Dreamz-Dziner** [comment]
> > This exact issue has been driving me crazy since last 2-3 days. Deleted controlnet and reinstalled almost everything from controlnet extension(including old versions), venv folder, xformers. Still struggling to solve the issue. I noticed this in txt2img first and now even in img2img its happening.
> 
> Can you please inform me if you ever fix it?

No idea mate. I am kinda lost and constantly deleting repo and reinstalling every possible version out there. Even downgraded my python from 3.10.7 to 3.10.6. Sometimes it works and other times its all throwing all sorts of error. Controlnet is totally messed up everything somehow after update.

**Comment by dayunbao** [comment]
I've received this error when using the API and not included the base64 stringified version of the input image (by accident).  Are you using the API?  I've never had this error when using the web UI.

**Comment by avivedri** [comment]
> I've received this error when using the API and not included the base64 stringified version of the input image (by accident). Are you using the API? I've never had this error when using the web UI.

Im using the web IU, through Chrome

**Comment by Lukeable** [comment]
Somebody knows already how to fix it? Got the same Problem and tried everything.

**Comment by huchenlei** [comment]
Cannot reproduce following the steps.
