### ISSUE TITLE
[Bug]:  FileNotFoundError: [Errno 2] No such file or directory: ''

### ISSUE THREAD

**Issue by Zhiyuanooo** [Mikubill/sd-webui-controlnet#2167]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Cant use controlnet batch,
*** Error completing request
*** Arguments: ('task(r119t67m33nfo6v)', 'image is a tessel spear with chinese style,game icon,official art, well structured, HD,2d, game prop icon (black background) <lora:lance_V15_BLIP:0.3>', '<easynegative:0.8>, black,low resolution,blur, light, shadow', [], 30, 'Euler a', 2, 4, 7, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x7fa743f98d00>, 0, False, '', 0.8, 3528174820, False, -1, 0, 0, 0, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x7fa743f990f0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x7fa7b8395ae0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x7fa7b8397910>, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, None, None, False, None, None, False, None, None, False, 50) {}
    Traceback (most recent call last):
      File "/opt/SD/stable-diffusion-webui/modules/call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "/opt/SD/stable-diffusion-webui/modules/call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "/opt/SD/stable-diffusion-webui/modules/txt2img.py", line 55, in txt2img
        processed = processing.process_images(p)
      File "/opt/SD/stable-diffusion-webui/modules/processing.py", line 732, in process_images
        res = process_images_inner(p)
      File "/opt/SD/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 39, in processing_process_images_hijack
        cn_is_batch, batches, output_dir, input_file_names = get_cn_batches(p)
      File "/opt/SD/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 194, in get_cn_batches
        unit.batch_images = shared.listfiles(unit.batch_images)
      File "/opt/SD/stable-diffusion-webui/modules/util.py", line 13, in listfiles
        filenames = [os.path.join(dirname, x) for x in sorted(os.listdir(dirname), key=natural_sort_key) if not x.startswith(".")]
    FileNotFoundError: [Errno 2] No such file or directory: ''

### Steps to reproduce the problem

1. Go to txt2img
2. Press generate
3. 

### What should have happened?

    FileNotFoundError: [Errno 2] No such file or directory: ''

### Commit where the problem happens

webui: 1.6
controlnet: 1.1.410

### Command Line Arguments

```Shell
CUDA_VISIBLE_DEVICES=5 ./webui.sh --listen --enable-insecure-extension-access --xformers --share
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/97418841/3bf45aab-0062-4dbc-b195-5b57f4d1e1e3)

### Console logs

```Shell
CUDA_VISIBLE_DEVICES=5 ./webui.sh --listen --enable-insecure-extension-access --xformers --share
```

**Comment by huchenlei** [comment]
Cannot reproduce
