### ISSUE TITLE
Using inpaint "only masked" cropped region as image?

### ISSUE THREAD

**Issue by FNSpd** [Mikubill/sd-webui-controlnet#217]
Right now it just crops original picture at center ignoring masked region

**Comment by 2blackbar** [comment]
yes a coupoe issues were made about it, it needs to intercept the final cropped image from webui to do controlnet detection on it

**Comment by Mikubill** [comment]
fixed in https://github.com/Mikubill/sd-webui-controlnet/commit/da7a3609e1011b7a2a1f020b77cb630743d11b2f
