### ISSUE TITLE
[Bug]: OpenPose models are not working when using the API

### ISSUE THREAD

**Issue by dayunbao** [Mikubill/sd-webui-controlnet#2170]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When using SD XL + ControlNet + an OpenPose model via the API, the OpenPose keypoints are ignored.  However, when using SD XL + ControlNet + an OpenPose model in the web UI, the OpenPose keypoints are recognized (although not always 100% of the time).

See https://github.com/Mikubill/sd-webui-controlnet/discussions/2153 for multiple examples, screenshots, API logs, and request bodies.

### Steps to reproduce the problem

Use the API with SD XL + ControlNet + any OpenPose model.  Then do the same thing in the web UI, and you'll see the difference.

### What should have happened?

The OpenPose keypoints should have been recoginzed, and the physical pose of the characters in the generated image should have reflected that.

### Commit where the problem happens

I'm not sure, but I think it started when yaml files were no longer used when loading the models.

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
`--xformers --listen --api --api-log --no-half-controlnet --disable-safe-unpickle`

and also `--xformers --listen --api --api-log --no-half-controlnet --disable-safe-unpickle --no-half-vae`

I've tried it with the full VAE and the fp16 VAE.
```

### List of enabled extensions

sd-webui-controlnet
sd-webui-openpose-editor
sd-webui-regional-prompter
and the built-in extensions

### Console logs

```Shell
See https://github.com/Mikubill/sd-webui-controlnet/discussions/2153 for multiple examples, screenshots, API logs, and request bodies.
```

**Comment by rockhward** [comment]
> @lllyasviel

Hello, I have a similar problem. When using the API, it can only recognize movements, but cannot recognize facial features and facial positions. The same parameters and configurations are used.

你好，我的问题也似类似的，在api使用时，仅能识别动作，无法识别五官和脸部位置，使用一样的参数和配置。

**Comment by dayunbao** [comment]
> > @lllyasviel
> 
> Hello, I have a similar problem. When using the API, it can only recognize movements, but cannot recognize facial features and facial positions. The same parameters and configurations are used.
> 
> 你好，我的问题也似类似的，在api使用时，仅能识别动作，无法识别五官和脸部位置，使用一样的参数和配置。

The OpenPose models don't all work with the face and hand keypoints. You have to chose the right model, and I was told none of the SD XL OpenPose models were trained on the face and hand keypoints. 

If you're using the SD 1.5 OpenPose models that were trained on the face and hand keypoints, then you'll want to use the DW OpenPose preprocessor. The other preprocessors aren't as good as creating the face and hand keypoints

**Comment by rockhward** [comment]
> > > @lllyasviel
> > 
> > 
> > Hello, I have a similar problem. When using the API, it can only recognize movements, but cannot recognize facial features and facial positions. The same parameters and configurations are used.
> > 你好，我的问题也似类似的，在api使用时，仅能识别动作，无法识别五官和脸部位置，使用一样的参数和配置。
> 
> The OpenPose models don't all work with the face and hand keypoints. You have to chose the right model, and I was told none of the SD XL OpenPose models were trained on the face and hand keypoints.
> 
> If you're using the SD 1.5 OpenPose models that were trained on the face and hand keypoints, then you'll want to use the DW OpenPose preprocessor. The other preprocessors aren't as good as creating the face and hand keypoints

I tested it. Even if the preprocessor selects dw, the face and fingers cannot be recognized using the API.
Is it a program problem or an API problem?

**Comment by dayunbao** [comment]
Which model are you using?

**Comment by rockhward** [comment]
> Which model are you using? And which version of Stable Diffusion?

my weChat is rockhward,Is it convenient for us to communicate more?
I used to have a program that could call dw openpose and sd1.5, but the current program cannot.

**Comment by dayunbao** [comment]
> I used to have a program that could call dw openpose and sd1.5, but the current program cannot.

It sounds like you aren't using  AUTOMATIC1111's web UI.  If that's the case, then I don't know what to tell you other than you need 2 things to use OpenPose with ControlNet: the preprocessor and the model (see the screenshot).  `dw_openpose_full` is the preprocessor.  The preprocessor is responsible for doing some formatting of the image as well as finding the face, hands, and body keypoints.  The image that is the output of the preprocessor is passed to Stable Diffusion along with the model (you're only option is the `openpose_full` model if you're using SD 1.5).  The model works with Stable Diffusion to generate the image that respects the keypoints.  If you're using a client other than AUTOMATIC1111's web UI, and you have no control over which model is used, then you'll have to start using AUTOMATIC1111's web UI or build your own solution.

Just to avoid confusion, in the screenshot I attached, I'm using the `openpose` preprocessor with a model meant to be used with SD XL.

![web_ui_controlnet_setting](https://github.com/Mikubill/sd-webui-controlnet/assets/11196050/d6172b0d-7cc8-455e-b379-a758c69f9b0e)

**Comment by rockhward** [comment]
> > 我曾经有一个可以调用 dw openpose 和 sd1.5 的程序，但现在的程序不能。
> 
> 听起来您没有使用 AUTOMATIC1111 的 Web UI。如果是这样的话，那么我不知道该告诉你什么，除了你需要 2 件事才能将 OpenPose 与 ControlNet 一起使用：预处理器和模型（见屏幕截图）。 是预处理器。预处理器负责对图像进行一些格式化，以及查找面部、手部和身体关键点。作为预处理器输出的图像与模型一起传递到 Stable Diffusion（如果您使用的是 SD 1.5 并且想要面部、手部和身体关键点，则唯一的选项是模型）。该模型与 Stable Diffusion 配合使用，以生成尊重关键点的图像。如果使用的客户端不是 AUTOMATIC1111 的 Web UI，并且无法控制使用的模型，则必须开始使用 AUTOMATIC1111 的 Web UI 或构建自己的解决方案。`dw_openpose_full``openpose_full`
> 
> 为了避免混淆，在我附上的屏幕截图中，我将预处理器与用于 SD XL 的模型一起使用。`openpose`
> 
> ![web_ui_controlnet_setting](https://user-images.githubusercontent.com/11196050/280189498-d6172b0d-7cc8-455e-b379-a758c69f9b0e.png)

Thank you, the problem has been solved. The name of the parameter is wrong. The parameter names of webui are different from those of the api. For example, the preprocessor of webui is called module in the api.

**Comment by dayunbao** [comment]
Oh, yes, they are different.  Glad you got it figured out!
