### ISSUE TITLE
[Bug]: multi controlnet api doesn't work

### ISSUE THREAD

**Issue by Nomination-NRB** [Mikubill/sd-webui-controlnet#2181]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

when I am running two control nets using new alwayson_scripts API
the control nets are working one by one, but once combined they are both ignored

### Steps to reproduce the problem

This is the payload:
![image](https://github.com/AUTOMATIC1111/stable-diffusion-webui/assets/83486284/8b1a83d2-d8b1-42fc-9017-b44f3c072d12)

### What should have happened?

the multi controlnet should both work

### Commit where the problem happens

webui: the multi controlnet both work 
controlnet api: it works only one controlnet, if I combine them, they didn't work anymore 

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
No
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/83486284/d5d9b512-d569-4a7a-aaaa-519e6104acb7)

### Console logs

```Shell
None
```

**Comment by huchenlei** [comment]
The controlnet unit keys do not seem to be correct, e.g. `starting/ending` is not a valid param key. You can reference following example:
https://github.com/Mikubill/sd-webui-controlnet/blob/main/example/txt2img_example/api_txt2img.py

**Comment by Nomination-NRB** [comment]
> The controlnet unit keys do not seem to be correct, e.g. `starting/ending` is not a valid param key. You can reference following example: https://github.com/Mikubill/sd-webui-controlnet/blob/main/example/txt2img_example/api_txt2img.py

Thank you very much for your reply, but I changed the starting/ending to "guidance_start": 0.0, and "guidance_end": 1.0, which did not work, or deleting the starting/ending directly did not work.

when I use this payload, it will return 3 images, the same in the webui, but it seems that the softedge doesn't work.

using api:
![W2 E3ZTD7MT06KSPUD_UCF](https://github.com/Mikubill/sd-webui-controlnet/assets/83486284/ab0f2027-89a2-40e3-baee-5a2dab4c2119)
![XI(}K~TM7B)W7BPS}OWSJA9](https://github.com/Mikubill/sd-webui-controlnet/assets/83486284/09cfaf3e-3df9-466e-a912-11f63a101237)

using webui:
![{KFY6N5LO08E3ZKRHG}97_P](https://github.com/Mikubill/sd-webui-controlnet/assets/83486284/d72986fa-0e75-4b0f-abbb-ef2298a7a576)
![D9H%5FB1DC2VY%M2IMI)NHY](https://github.com/Mikubill/sd-webui-controlnet/assets/83486284/5cafeacd-16f3-4cdc-8c26-ff5846bc7487)

If I use only one controlnet, either openpose or softedge will work, but not both together

**Comment by huchenlei** [comment]
You can try to dump out payload of the WebUI generation with this extension: https://github.com/huchenlei/sd-webui-api-payload-display

**Comment by Nomination-NRB** [comment]
> You can try to dump out payload of the WebUI generation with this extension: https://github.com/huchenlei/sd-webui-api-payload-display, and adjust your payload accordingly.

Thanks for your help
