### ISSUE TITLE
[About Code] How to understand the threshold_a in prepoccessor?

### ISSUE THREAD

**Issue by Z-YuPeng** [Mikubill/sd-webui-controlnet#2182]
Recently I dived into the code of controlnet-webui, hoping to understand how it works and develop based on it.
 I did not understand the following and hope to be helped:
1. What is the meaning of “threshold_a” and "threshold_b"? I did not find it in the webui panel and the controllnet paper.
2. what is the usage of "AutoMachine.Write or Read" and bank? Are they just designed for reference control?

**Comment by huchenlei** [comment]
threshold a/b simply provides 2 optional params to the preprocessor to adjust preprocessor behaviours. It represents different things for different preprocessors.
