### ISSUE TITLE
[Bug]: guidance_start和Starting Control Step guidance_end和Ending Control Step好像有问题

### ISSUE THREAD

**Issue by rockhward** [Mikubill/sd-webui-controlnet#2194]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

经过本人测试，
guidance_start和Starting Control Step
guidance_end和Ending Control Step
这个是对应的，但是产生的效果不同，应该是bug

After my own testing,
guidance_start and Starting Control Step
guidance_end and Ending Control Step
This is corresponding, but the effect is different. It should be a bug.

### Steps to reproduce the problem

1比如我在webui设定Starting Control Step 0.5 Ending Control Step 1，
2用相同的值设定guidance_end和Ending Control Step，锁定种子的情况下，出来的图象完全不同

1 For example, I set Starting Control Step 0.5 Ending Control Step 1 in webui, 
2 and set guidance_end and Ending Control Step with the same values. When the seed is locked, the image that comes out is completely different.

### What should have happened?

正常情况下，在webui和调用api，应该出现一致的图象
Under normal circumstances, consistent images should appear in the webui and when calling the api.

### Commit where the problem happens

webui: 
controlnet: 
在网页中调用api时出现
Appears when calling api in web page

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
否
```

### List of enabled extensions

否

### Console logs

```Shell
否
```

**Comment by shitianfang** [comment]
遇到了同样的问题

**Comment by huchenlei** [comment]
Cannot reproduce. Guidance start / end both produce exact same result as in A1111. Please confirm that you are using the exact same setting from A1111.

You can use https://github.com/huchenlei/sd-webui-api-payload-display to dump payload after your generation in A1111, so that you can be sure all other params are the same.
