### ISSUE TITLE
Guidance Strength isn't saved to PNG metadata

### ISSUE THREAD

**Issue by skribb** [Mikubill/sd-webui-controlnet#220]
Hi, Guidance Strength isn't saved to PNG metadata.
Is it possible to fix this or is this a limitation with Controlnet or perhaps automatic1111?

The information that is currently saved to the metadata is the following:
`ControlNet Enabled: True, ControlNet Module: canny, ControlNet Model: diff_control_sd15_canny_fp16 [ea6e3b9c], ControlNet Weight: 1`

**Comment by Mikubill** [comment]
fixed in https://github.com/Mikubill/sd-webui-controlnet/commit/a8c5b4e25516cbaf8457dfc3ee863a174eb0678d
