### ISSUE TITLE
need ControlNet 1.1.153? for Reference Only?

### ISSUE THREAD

**Issue by MonkaiMonai** [Mikubill/sd-webui-controlnet#2205]
Hi I am new here, i see that for optimal reference only usage, it says to have controlnet 1.1.53. I am both new to github/SD

(my system is windows a1111 webui, but i also have a colab webui setup that i am testing/trying new things)

![Untitled](https://github.com/Mikubill/sd-webui-controlnet/assets/149369509/d66a6ada-30a1-4941-bf56-366afb3b6cde)

As additional questions:
1. I have controlnet 1.1.40 -> can that alone recreate the centralized characters in the image or does it need to be coupled with other models like Segmentation?
2. does controlnet segmentation categorize what it is segmenting? So if the image has a tree, person, and car; and my prompt has Person jumping. (with settings controlnet segmentation on 2 + balanced). Will SD take just person from segmentation and make them jump? Or is that where reference controlnet also comes in?

I have been testing things and i seem to fail to completely understand how it all works, also because i was testing amidst various extensions causing controlnet failures, which i think ive finally fully debugged on my local system.

**Comment by huchenlei** [comment]
v1.1.153 is a very old version of the extension. The lastest version is v1.1.411.

**Comment by MonkaiMonai** [comment]
> v1.1.153 is a very old version of the extension. The lastest version is v1.1.411.

Ohhh thank you! I guess i have been getting what i need, just not fully understanding how to use the tool
