### ISSUE TITLE
[Bug]: ControlNet failed to load SGM - will use LDM instead / Error calling controlnet-py/ui

### ISSUE THREAD

**Issue by lor2222** [Mikubill/sd-webui-controlnet#2209]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

controlnet was working fine untill the last update. Now it doesn´t work anynore. Please see in attached the error log. Any help?

### Steps to reproduce the problem

1. lunch webui-user.bat
2. error

### What should have happened?

it should work

### Commit where the problem happens

webui: Automatic1111 728ffcec
controlnet: 3011ff6e

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
no
```

### List of enabled extensions

no

### Console logs

```Shell
https://www.dropbox.com/scl/fi/9wr68dy4o6qvv822mu2ks/screen.jpg?rlkey=uesxy8aspwaikeifctepa1ors&dl=0
```

**Comment by lor2222** [comment]
P.S. I have downloaded the old version from here: https://github.com/lllyasviel/webui-controlnet-v1-archived and that one is working...

**Comment by huchenlei** [comment]
See https://github.com/Mikubill/sd-webui-controlnet/issues/1983. Upgrade your gradio version should fix the issue.
