### ISSUE TITLE
[DevTask] Automatically filter ControlNet models based on active SD model version

### ISSUE THREAD

**Issue by huchenlei** [Mikubill/sd-webui-controlnet#2222]
There are many issues caused by users accidentally choosed wrong ControlNet model that does not fit the active SD model. For example, using SDXL ControlNet model for SD1.5 SD model. #2221, #2155

We should implement a mechanism to automatically filter ControlNet model selections based on current active SD model in A1111, and give meaningful warning/error messages if mismatches are detected in A1111 API calls.

**Comment by sdbds** [comment]
I remember that sd-webui 1.6 had the ability to filter the corresponding version of LORA. Maybe refer to that section.
