### ISSUE TITLE
[DevTask] Allow users directly upload openpose JSON file as input

### ISSUE THREAD

**Issue by huchenlei** [Mikubill/sd-webui-controlnet#2236]
See https://github.com/huchenlei/sd-webui-openpose-editor/discussions/20#discussioncomment-7481668

To make openpose JSON file more easy to use, we should find a way to allow user directly upload a JSON file to ControlNet.

**Comment by peterpernhofer** [comment]
### ValueError: controlnet is enabled but no input image is given
Unfortunately the "Upload Json" Button does not work any more :-(
No matter, if "Allow Preview" is checked or not, or if I choose a preprocessor or not (I think I don't need it, when I'm using a JSON open pose file).
The following error appears:

```
*** Error running process: C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
      File "C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1053, in process
        self.controlnet_hack(p)
      File "C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1042, in controlnet_hack
        self.controlnet_main_entry(p)
      File "C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 766, in controlnet_main_entry
        input_image, image_from_a1111 = Script.choose_input_image(p, unit, idx)
      File "C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 651, in choose_input_image
        raise ValueError('controlnet is enabled but no input image is given')
      ValueError: controlnet is enabled but no input image is given
```

**Comment by huchenlei** [comment]
@peterpernhofer I cannot reproduce the issue locally. Please file an issue with reproduction steps. Thanks!

**Comment by peterpernhofer** [comment]
Ok, I've done some tests again. It seems, that the issue happens, when you close the preprocessor preview. I do the following:
1. Enable the ControlNet-Unit
2. choose control-type "Open Pose"
3. Press button "Upload JSON" an upload a json-file
4. the expected preprocessor-image (the pose) appears on the right side
5. Generate the image => works well

Steps 3 - 5 can be repeated and it works!
But if I just close the preprocessor-preview **on the right side with the "Close" button**, than it no longer works. I have to choose another control-type, run preprocessor, and go back to open-pose (or restart Auto1111).
So, if you know that, you can live with it.

Nevertheless many thanks for the "Upload JSON" button. It's very helpful. I also discovered that it's possible to drag/drop a JSON-file onto the button. That's great. Thank you :-)

**Comment by peterpernhofer** [comment]
Yes, its solved with this version. Thank you for your fast response :-)
