### ISSUE TITLE
[Bug]: inpaint_only+lama inpainting via API adds new faces

### ISSUE THREAD

**Issue by victorbianconi** [Mikubill/sd-webui-controlnet#2237]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When using the API for Auto1111 and Controlnet, I cannot get Lama to remove the objects. In fact, the output image always shows a face or a person in the inpainted area. What's odd is that it works perfectly fine when used on the Web UI without the API. I wonder if the API scripts are different. 

### Steps to reproduce the problem

1. Inpaint the area you want to remove.
2. Call API route img2img via API with params 

```
params.init_images = [base64Content];
 params.mask = base64ContentMask;
params.denoising_strength = 0.75;
params["alwayson_scripts"]["controlnet"]["args"][0]["enabled"] = true;
params["alwayson_scripts"]["controlnet"]["args"][0]["module"] =
            "inpaint_only+lama";
          params["alwayson_scripts"]["controlnet"]["args"][0]["model"] =
            "control_v11p_sd15_inpaint [ebff9138]";
          params["alwayson_scripts"]["controlnet"]["args"][0]["weight"] = 1;
          params["alwayson_scripts"]["controlnet"]["args"][0][
            "control_mode"
          ] = 2;
```

### What should have happened?

The inpainted area should look coherent and remove the object, while it 'adds' a face of a person or weird objects, as if SD generates a new picture on the inpainted area.

### Commit where the problem happens

webui: v1.5.1
controlnet: 41011bea

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--listen
```

### List of enabled extensions

controlnet

### Console logs

```Shell
n/a
```

**Comment by huchenlei** [comment]
We have verified that A1111 UI and A1111 API can produce the exact same result if params are the same.

You can use this extension to dump out payload of your generation on A1111 UI.
https://github.com/huchenlei/sd-webui-api-payload-display

P.S. Current version of ControlNet aims to support A1111 1.6.0+. Please update your A1111 and ControlNet to avoid any inconvenience dur to version issues.
