### ISSUE TITLE
[Bug]: sam mask not run in api，very magical error

### ISSUE THREAD

**Issue by shitianfang** [Mikubill/sd-webui-controlnet#2239]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I used the extracted webui payload API，Very magical error, when I use inpaint, the mask I manually smear and generate works fine, whether it is base64 or url, but the mask I generate through sam can't be used anyway, even though they all have the same rgb value, both black and white, 255 and 0，If the mask generated by sam cannot be used, it will return to the original image, and the mask manually generated by inpaint can be changed normally
"ControlNet": {
            "args": [
                {
                    "batch_images": "",
                    "control_mode": "Balanced",
                    "enabled": true,
                    "guidance_end": 1,
                    "guidance_start": 0,
                    "image": {
                        "image": "origin base64",
                        "mask": "mask base64"
                    },
                    "input_mode": "simple",
                    "is_ui": true,
                    "loopback": false,
                    "low_vram": false,
                    "model": "control_v11p_sd15_inpaint_fp16 [be8bc0ed]",
                    "module": "inpaint_only",
                    "output_dir": "",
                    "pixel_perfect": false,
                    "processor_res": -1,
                    "resize_mode": "Crop and Resize",
                    "threshold_a": -1,
                    "threshold_b": -1,
                    "weight": 1
                },

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

no

### Commit where the problem happens

webui: 
controlnet: 

### Command Line Arguments

```Shell
no
```

### List of enabled extensions

no

### Console logs

```Shell
no
```

**Comment by shitianfang** [comment]
Manual inpainting：![tmpehvutyaz](https://github.com/Mikubill/sd-webui-controlnet/assets/61344989/16e9e015-0895-4174-b393-8138043c1e67)
SAM：![download (6)](https://github.com/Mikubill/sd-webui-controlnet/assets/61344989/acc80fba-bbf5-41c2-a945-d2928c079e45)

**Comment by shitianfang** [comment]
@huchenlei Hi, it's convenient to help take a look at this question. It's really difficult for me. It's too strange. I have repeatedly confirmed three different pictures, and it does happen.

**Comment by huchenlei** [comment]
Please provide steps to reproduce the problem. Thanks!

Essentially SAM is outputing an image, which should be treated the same way as the mask image you saved from A1111.

**Comment by shitianfang** [comment]
@huchenlei You can try the above two images through the webui payload api of txt2img, use inpaint controlnet to pass the mask, no matter what prompt I enter, any mask generated by SAM, including the hair cutout above, will not change

**Comment by shitianfang** [comment]
{
    "alwayson_scripts": {
        "API payload": {
            "args": []
        },
        "ControlNet": {
            "args": [
                {
                    "batch_images": "",
                    "control_mode": "Balanced",
                    "enabled": true,
                    "guidance_end": 1,
                    "guidance_start": 0,
                    "image": {
                        "image": "https://filter-max-1254149036.cos.ap-shanghai.myqcloud.com/test%2Ff62b97b1-1f7d-477e-834b-48b262d8217f.png",
                        "mask": "https://filter-max-1254149036.cos.ap-shanghai.myqcloud.com/test%2Ftmpehvutyaz.png"
                    },
                    "input_mode": "simple",
                    "is_ui": true,
                    "loopback": false,
                    "low_vram": false,
                    "model": "control_v11p_sd15_inpaint_fp16 [be8bc0ed]",
                    "module": "inpaint_only",
                    "output_dir": "",
                    "pixel_perfect": false,
                    "processor_res": -1,
                    "resize_mode": "Crop and Resize",
                    "threshold_a": -1,
                    "threshold_b": -1,
                    "weight": 1
                },
                {
                    "batch_images": "",
                    "control_mode": "Balanced",
                    "enabled": false,
                    "guidance_end": 1,
                    "guidance_start": 0,
                    "image": null,
                    "input_mode": "simple",
                    "is_ui": true,
                    "loopback": false,
                    "low_vram": false,
                    "model": "None",
                    "module": "none",
                    "output_dir": "",
                    "pixel_perfect": false,
                    "processor_res": -1,
                    "resize_mode": "Crop and Resize",
                    "threshold_a": -1,
                    "threshold_b": -1,
                    "weight": 1
                },
                {
                    "batch_images": "",
                    "control_mode": "Balanced",
                    "enabled": false,
                    "guidance_end": 1,
                    "guidance_start": 0,
                    "image": null,
                    "input_mode": "simple",
                    "is_ui": true,
                    "loopback": false,
                    "low_vram": false,
                    "model": "None",
                    "module": "none",
                    "output_dir": "",
                    "pixel_perfect": false,
                    "processor_res": -1,
                    "resize_mode": "Crop and Resize",
                    "threshold_a": -1,
                    "threshold_b": -1,
                    "weight": 1
                }
            ]
        },
        "Dynamic Prompts v2.16.3": {
            "args": [
                true,
                false,
                1,
                false,
                false,
                false,
                1.1,
                1.5,
                100,
                0.7,
                false,
                false,
                true,
                false,
                false,
                0,
                "Gustavosta/MagicPrompt-Stable-Diffusion",
                ""
            ]
        },
        "Extra options": {
            "args": []
        },
        "Refiner": {
            "args": [
                false,
                "",
                0.8
            ]
        },
        "Seed": {
            "args": [
                -1,
                false,
                -1,
                0,
                0,
                0
            ]
        },
        "Segment Anything": {
            "args": [
                false,
                false,
                0,
                null,
                [],
                0,
                false,
                [],
                [],
                false,
                0,
                1,
                false,
                false,
                0,
                null,
                [],
                -2,
                false,
                [],
                false,
                0,
                null,
                null
            ]
        },
        "Tiled Diffusion": {
            "args": [
                false,
                "MultiDiffusion",
                false,
                true,
                1024,
                1024,
                96,
                96,
                48,
                4,
                "None",
                2,
                false,
                10,
                1,
                1,
                64,
                false,
                false,
                false,
                false,
                false,
                0.4,
                0.4,
                0.2,
                0.2,
                "",
                "",
                "Background",
                0.2,
                -1,
                false,
                0.4,
                0.4,
                0.2,
                0.2,
                "",
                "",
                "Background",
                0.2,
                -1,
                false,
                0.4,
                0.4,
                0.2,
                0.2,
                "",
                "",
                "Background",
                0.2,
                -1,
                false,
                0.4,
                0.4,
                0.2,
                0.2,
                "",
                "",
                "Background",
                0.2,
                -1,
                false,
                0.4,
                0.4,
                0.2,
                0.2,
                "",
                "",
                "Background",
                0.2,
                -1,
                false,
                0.4,
                0.4,
                0.2,
                0.2,
                "",
                "",
                "Background",
                0.2,
                -1,
                false,
                0.4,
                0.4,
                0.2,
                0.2,
                "",
                "",
                "Background",
                0.2,
                -1,
                false,
                0.4,
                0.4,
                0.2,
                0.2,
                "",
                "",
                "Background",
                0.2,
                -1
            ]
        },
        "Tiled VAE": {
            "args": [
                false,
                3072,
                192,
                true,
                true,
                true,
                false
            ]
        }
    },
    "batch_size": 1,
    "cfg_scale": 7,
    "comments": {},
    "disable_extra_networks": false,
    "do_not_save_grid": false,
    "do_not_save_samples": false,
    "enable_hr": false,
    "height": 512,
    "hr_negative_prompt": "",
    "hr_prompt": "",
    "hr_resize_x": 0,
    "hr_resize_y": 0,
    "hr_scale": 2,
    "hr_second_pass_steps": 0,
    "hr_upscaler": "Latent",
    "n_iter": 1,
    "negative_prompt": "2",
    "override_settings": {},
    "override_settings_restore_afterwards": true,
    "prompt": "(blue hair:1.5)",
    "restore_faces": false,
    "s_churn": 0,
    "s_min_uncond": 0,
    "s_noise": 1,
    "s_tmax": null,
    "s_tmin": 0,
    "sampler_name": "Euler",
    "script_args": [],
    "script_name": null,
    "seed": 2630000426,
    "seed_enable_extras": true,
    "seed_resize_from_h": -1,
    "seed_resize_from_w": -1,
    "steps": 20,
    "styles": [],
    "subseed": 2884386191,
    "subseed_strength": 0,
    "tiling": false,
    "width": 512
}

**Comment by shitianfang** [comment]
@huchenlei This is the parameter, via the txt2img api.
