### ISSUE TITLE
[Feature Request] Multiple images in a single IP Adapter

### ISSUE THREAD

**Issue by josephrocca** [Mikubill/sd-webui-controlnet#2245]
I recently [asked](https://github.com/cubiq/Diffusers_IPAdapter/issues/3) about this on this repo which supports multiple images: https://github.com/cubiq/Diffusers_IPAdapter and cubiq, the dev @.cubiq said this:

> I had a very quick look at a1111 code, it looks very familiar, I don't see any issue with adding multiple images but I'm not familiar with their code. All they have to do is to patch the number of tokens in attn_processor with (number_of_images * ipadapter tokens)

Here are some examples of using multiple images with IP Adapter - e.g. one for character, one for background, etc. - or specifying multiple images of a particular art style so IP Adapter doesn't get caught up in the specific "subjects" of the image and instead focuses on the style:
* https://www.youtube.com/watch?v=HtmIC6fqsMQ
* https://www.youtube.com/watch?v=7m9ZZFU3HWo

**Comment by George0726** [comment]
it would be great if we can support multiple IP-Adapters, like using face-plus and XL plus simultaneously.

**Comment by 2blackbar** [comment]
Will this come eventually? This is very helpful to mix images , sadly its not possible to load multipe images in this extension.

I tried 2 seperate instances of ipadapter cnets but it does not work  as well.

**Comment by strawberrymelonpanda** [comment]
I'd love to see combining multiple images to a single ControlNet (called "batch images" in ComfyUI) supported in the WebUI ControlNet extension.
