### ISSUE TITLE
[Request]: IP Adapter Full Face Support

### ISSUE THREAD

**Issue by Kujoz** [Mikubill/sd-webui-controlnet#2250]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

IP Adapter Folks recently released a new IP face adapter shortly after safetensor support was added, less than 30 hours ago. However the new file is not supported out the box even when changing extension to pth, or using the provided safetensor file. This new face adapter appears to be significantly better at stylizing faces and I would like it very much. 

**Demo showcase:** 
<img width="505" alt="image" src="https://github.com/Mikubill/sd-webui-controlnet/assets/127086096/03217734-54f0-4c55-b382-5afa25ad70c5">

**Error shown:** 
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/127086096/51fe085b-1275-4838-836b-782b4b3639cf)

**Link to Model:**
https://huggingface.co/h94/IP-Adapter/blob/main/models/ip-adapter-full-face_sd15.safetensors

### Steps to reproduce the problem

Demo documentation link here: https://github.com/tencent-ailab/IP-Adapter/blob/main/ip_adapter-full-face_demo.ipynb

### What should have happened?

NA

### Commit where the problem happens

When trying to hook the IP adapter. 

### Command Line Arguments

```Shell
No
```

### List of enabled extensions

NA

### Console logs

```Shell
NA
```

**Comment by sdbds** [comment]
this model use different state dict.
wait a minute...

**Comment by sdbds** [comment]
you can tested it in pr #2252  now
