### ISSUE TITLE
[Feature Request]: Animal Pose Preprocessor (RTMPose AP-10K)

### ISSUE THREAD

**Issue by Fannovel16** [Mikubill/sd-webui-controlnet#2258]
https://github.com/abehonest/ControlNet_AnimalPose
DWPose but for animal
The original implementation doesn't use a object detector so it can only recognize one animal in the image. From my test, YOLOX used by DWPose works pretty well.
MMPose can be replaced with this [onnx checkpoint](https://download.openmmlab.com/mmpose/v1/projects/rtmposev1/onnx_sdk/rtmpose-m_simcc-ap10k_pt-aic-coco_210e-256x256-7a041aa1_20230206.zip)
![](https://raw.githubusercontent.com/Fannovel16/comfyui_controlnet_aux/main/example_animal_pose.png)

**Comment by sdbds** [comment]
https://github.com/Deci-AI/super-gradients/blob/master/YOLONAS.md
I've actually only recently tried using yolo-nas instead of yolox, and yolo-nas-pose seems to be faster and more accurate than the current openpose. 
However my own testing of onnx converted to fp16 doesn't seem to be compatible with the current setup.

**Comment by Fannovel16** [comment]
@sdbds Which model do you use? Small or medium?

**Comment by sdbds** [comment]
> @sdbds Which model do you use? Small or medium?

dwpose use yolox_l,so i used yolo-nas-l fp16

**Comment by Fannovel16** [comment]
@sdbds I wrote some code to support YOLO-NAS: https://github.com/Fannovel16/comfyui_controlnet_aux/blob/main/src/controlnet_aux/dwpose/yolo_nas.py#L25
`inference_detector` is compatible with https://github.com/Fannovel16/comfyui_controlnet_aux/blob/main/src/controlnet_aux/dwpose/cv_ox_pose.py

Also, it requires the exported onnx model having built-in NMS
```
from super_gradients.conversion.conversion_enums import ExportQuantizationMode
from super_gradients.common.object_names import Models
from super_gradients.training import models

model = models.get(Models.YOLO_NAS_L, pretrained_weights="coco")

export_result = model.export(
    "yolo_nas/yolo_nas_l_fp16.onnx",
    quantization_mode=ExportQuantizationMode.FP16,
    device="cuda"
)
```

**Comment by sdbds** [comment]
> @sdbds I wrote some code to support YOLO-NAS: https://github.com/Fannovel16/comfyui_controlnet_aux/blob/main/src/controlnet_aux/dwpose/yolo_nas.py#L25
> 
> It might work with this extension since both my extension and this one have similar code Also, it requires the exported onnx model to have built-in NMS
> 
> ```python
> from super_gradients.conversion.conversion_enums import ExportQuantizationMode
> from super_gradients.common.object_names import Models
> from super_gradients.training import models
> 
> model = models.get(Models.YOLO_NAS_L, pretrained_weights="coco")
> 
> export_result = model.export(
>     "yolo_nas/yolo_nas_l_fp16.onnx",
>     quantization_mode=ExportQuantizationMode.FP16,
>     device="cuda"
> )
> ```

Thank U！I will test it soon.

**Comment by Fannovel16** [comment]
The dtype have to be `uint8` for both INT8 and FP16 models

**Comment by sdbds** [comment]
i found another animal pose estimation, i will compare them
https://github.com/DeepLabCut/DeepLabCut

**Comment by Fannovel16** [comment]
@sdbds Its keypoints aren't similar to AP-10K used by that ControlNet

**Comment by sdbds** [comment]
I separated the GPU part of the code and added a separate animalpose preprocesser.
And i will train a SDXL controlnet lllite for it.

**Comment by avinashc27** [comment]
> I separated the GPU part of the code and added a separate animalpose preprocesser. And i will train a SDXL controlnet lllite for it. ![image](https://private-user-images.githubusercontent.com/8085926/288164254-ef30bbd0-9dd3-44ed-92f6-06936172ddd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NzI2NDMsIm5iZiI6MTcwMzc3MjM0MywicGF0aCI6Ii84MDg1OTI2LzI4ODE2NDI1NC1lZjMwYmJkMC05ZGQzLTQ0ZWQtOTJmNi0wNjkzNjE3MmRkZDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjhUMTQwNTQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODJkMTY5ZmRhN2U2NzYwYzQzYzViNDAzYWQ1M2UyY2YxY2M2N2QzZTgwM2E0NGVjOWRkZGI2ODhhOWI4OTI1NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.had0h9WgNhidvlT_W_Fh59DxYal5tB35H52yrLRuQ3E)



> I separated the GPU part of the code and added a separate animalpose preprocesser. And i will train a SDXL controlnet lllite for it. ![image](https://private-user-images.githubusercontent.com/8085926/288164254-ef30bbd0-9dd3-44ed-92f6-06936172ddd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NzI2NDMsIm5iZiI6MTcwMzc3MjM0MywicGF0aCI6Ii84MDg1OTI2LzI4ODE2NDI1NC1lZjMwYmJkMC05ZGQzLTQ0ZWQtOTJmNi0wNjkzNjE3MmRkZDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjhUMTQwNTQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODJkMTY5ZmRhN2U2NzYwYzQzYzViNDAzYWQ1M2UyY2YxY2M2N2QzZTgwM2E0NGVjOWRkZGI2ODhhOWI4OTI1NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.had0h9WgNhidvlT_W_Fh59DxYal5tB35H52yrLRuQ3E)

I would love to try SDXL controlnet lllite for animalpose, please let me know if you have released in public domain.

**Comment by avinashchakravarthi** [comment]
> I separated the GPU part of the code and added a separate animalpose preprocesser. And i will train a SDXL controlnet lllite for it. ![image](https://private-user-images.githubusercontent.com/8085926/288164254-ef30bbd0-9dd3-44ed-92f6-06936172ddd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NzMxMjcsIm5iZiI6MTcwMzc3MjgyNywicGF0aCI6Ii84MDg1OTI2LzI4ODE2NDI1NC1lZjMwYmJkMC05ZGQzLTQ0ZWQtOTJmNi0wNjkzNjE3MmRkZDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjhUMTQxMzQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTM2Y2VmNDI0ZDZkZTY2OWQ4NzcyM2RkNTQzNGIyNzg3N2U1NTgxMThjOTFmNDM1ZWU1OWFlZWYwMGNhMzhlMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dDIs-zei8MjlyR7dXMRS9UH-EoVbtXMRmkI8QpmN8Mg)

I would love to try "SDXL controlnet" for Animal openpose, pls let me know if you have released in public domain.

**Comment by sdbds** [comment]
> > I separated the GPU part of the code and added a separate animalpose preprocesser. And i will train a SDXL controlnet lllite for it. ![image](https://private-user-images.githubusercontent.com/8085926/288164254-ef30bbd0-9dd3-44ed-92f6-06936172ddd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NzMxMjcsIm5iZiI6MTcwMzc3MjgyNywicGF0aCI6Ii84MDg1OTI2LzI4ODE2NDI1NC1lZjMwYmJkMC05ZGQzLTQ0ZWQtOTJmNi0wNjkzNjE3MmRkZDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjhUMTQxMzQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTM2Y2VmNDI0ZDZkZTY2OWQ4NzcyM2RkNTQzNGIyNzg3N2U1NTgxMThjOTFmNDM1ZWU1OWFlZWYwMGNhMzhlMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dDIs-zei8MjlyR7dXMRS9UH-EoVbtXMRmkI8QpmN8Mg)
> 
> I would love to try "SDXL controlnet" for Animal openpose, pls let me know if you have released in public domain.

I've had a lot of development work lately, and I'm not trained for now

**Comment by andreszs** [comment]
> i found another animal pose estimation, i will compare them https://github.com/DeepLabCut/DeepLabCut

No **.pth** files for SDXL ControlNet are available on that repo.

**Comment by andreszs** [comment]
> I would love to try "SDXL controlnet" for Animal openpose, pls let me know if you have released in public domain.

Any news on this? Pose detection works well with the AP10K estimator, but there's no controlnet to apply it and SD1.5 models do nothing.
