### ISSUE TITLE
[Bug]: AttributeError: 'ControlNet' object has no attribute 'label_emb'

### ISSUE THREAD

**Issue by billy7676** [Mikubill/sd-webui-controlnet#2259]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I am new to Stable Diffusion. The txt2im and img2img option work well, but when I activate ControNet it gives me this error.
I have the controlnet models downloaded into models folder and models/ControlNet folder but th isue continues.
Anyone can help me?

### Steps to reproduce the problem

1. Go to ControlNet
2. Press Generate
3. AttributeError: 'ControlNet' object has no attribute 'label_emb' OR controlnet RuntimeError: mat1 and mat2 shapes cannot be multiplied

### What should have happened?

Tile model/openpose/lineart in control net works

### Commit where the problem happens

webui: deforum-for-automatic1111-webui
controlnet: https://github.com/Mikubill/sd-webui-controlnet.git  version [c1f3d6f8]

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
set COMMANDLINE_ARGS= --enable-insecure-extension-access --opt-sub-quad-attention --disable-nan-check --no-half --precision full --no-half-vae --opt-sub-quad-attention --opt-split-attention-v1 --autolaunch --listen --lowvram --precision full --opt-split-attention-v1 --no-half --no-half-vae --opt-sub-quad-attention --disable-nan-check --opt-sdp-no-mem-attention --skip-torch-cuda-test
```

### List of enabled extensions

Only Deforum and ControlNet, as I have heard that havig others activated could cause problems

### Console logs

```Shell
AttributeError: 'ControlNet' object has no attribute 'label_emb' OR controlnet RuntimeError: mat1 and mat2 shapes cannot be multiplied
```

### Additional information

I would appreciate so much some help asap. Thanks!!

**Comment by huchenlei** [comment]
https://github.com/Mikubill/sd-webui-controlnet/issues/2155?notification_referrer_id=NT_kwDOAT9bArM3OTI4MzI0NjMyOjIwOTI5Mjgy#issuecomment-1809614497
