### ISSUE TITLE
[Feature Request] YOLO-NAS Large fp16 + DWPose-large 256x192 fp32

### ISSUE THREAD

**Issue by Fannovel16** [Mikubill/sd-webui-controlnet#2261]
I used https://colab.research.google.com/drive/1GEv25A9UsngCohZOtf9de4aAV_eSpHQN?usp=sharing to compare YOLOX and YOLO-NAS, different version of DWPose on T4
The result:
* YOLOX Lfp32: 52.17ms
* NAS L fp16: 33.13ms
* NAS M fp16: 23.33ms
* NAS S fp16: 18.58ms
* DW-LL 386 fp32: 73.22ms
* DW-LL fp32: 36.61ms
* DW-MM fp32: 30.12ms
* DW-SS fp32: 24.52ms

YOLO-NAS clearly outperforms YOLO-X in speed. It also has a slightly higher mAP compared to yolo-x ([52.22](https://docs.ultralytics.com/models/yolo-nas/) vs [51.1](https://github.com/Megvii-BaseDetection/YOLOX#standard-models)). Whole AP of DWPose Large 368 is only [3.2% smaller](https://github.com/IDEA-Research/DWPose/tree/onnx#-dwpose-on-coco-we-release-a-series-of-dwpose-models) than DWPose Large, yet it is faster by twice.

**Comment by huchenlei** [comment]
Currently inference of dwpose runs on CPU, as we deem speed is fast enough. Please re-open if speed of inference becomes an issue for your specific usecase.
