### ISSUE TITLE
Unable to load 2.1 based controlnet model 

### ISSUE THREAD

**Issue by AndyLonly** [Mikubill/sd-webui-controlnet#228]
My model based on stable diffusion 2.1 was created using the method provided by controlnet and works fine on gradio_canny2image.py
when I try to use it in the extension, I get the following error
Both model is base on stable diffusion 2.1
```py
Loaded state_dict from [stable-diffusion-webui-master\extensions\sd-webui-controlnet\models\control_sd21v_canny.ckpt]
Error running process: stable-diffusion-webui-master\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "stable-diffusion-webui-master\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "stable-diffusion-webui-master\extensions\sd-webui-controlnet\scripts\controlnet.py", line 476, in process
    network = network_module(
  File "stable-diffusion-webui-master\extensions\sd-webui-controlnet\scripts\cldm.py", line 107, in __init__
    self.control_model.load_state_dict(state_dict)
  File "stable-diffusion-webui-master\venv\lib\site-packages\torch\nn\modules\module.py", line 2018, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ControlNet:
        size mismatch for input_blocks.1.1.proj_in.weight: copying a param with shape torch.Size([320, 320]) from checkpoint, the shape in current model is torch.Size([320, 320, 1, 1]).
        size mismatch for input_blocks.1.1.transformer_blocks.0.attn2.to_k.weight: copying a param with shape torch.Size([320, 1024]) from checkpoint, the shape in current model is torch.Size([320, 768]).
        size mismatch for input_blocks.1.1.transformer_blocks.0.attn2.to_v.weight: copying a param with shape torch.Size([320, 1024]) from checkpoint, the shape in current model is torch.Size([320, 768]).
        size mismatch for input_blocks.1.1.proj_out.weight: copying a param with shape torch.Size([320, 320]) from checkpoint, the shape in current model is torch.Size([320, 320, 1, 1]).
        size mismatch for input_blocks.2.1.proj_in.weight: copying a param with shape torch.Size([320, 320]) from checkpoint, the shape in current model is torch.Size([320, 320, 1, 1]).
        size mismatch for input_blocks.2.1.transformer_blocks.0.attn2.to_k.weight: copying a param with shape torch.Size([320, 1024]) from checkpoint, the shape in current model is torch.Size([320, 768]).
        size mismatch for input_blocks.2.1.transformer_blocks.0.attn2.to_v.weight: copying a param with shape torch.Size([320, 1024]) from checkpoint, the shape in current model is torch.Size([320, 768]).
        size mismatch for input_blocks.2.1.proj_out.weight: copying a param with shape torch.Size([320, 320]) from checkpoint, the shape in current model is torch.Size([320, 320, 1, 1]).
        size mismatch for input_blocks.4.1.proj_in.weight: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([640, 640, 1, 1]).
        size mismatch for input_blocks.4.1.transformer_blocks.0.attn2.to_k.weight: copying a param with shape torch.Size([640, 1024]) from checkpoint, the shape in current model is torch.Size([640, 768]).
        size mismatch for input_blocks.4.1.transformer_blocks.0.attn2.to_v.weight: copying a param with shape torch.Size([640, 1024]) from checkpoint, the shape in current model is torch.Size([640, 768]).
        size mismatch for input_blocks.4.1.proj_out.weight: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([640, 640, 1, 1]).
        size mismatch for input_blocks.5.1.proj_in.weight: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([640, 640, 1, 1]).
        size mismatch for input_blocks.5.1.transformer_blocks.0.attn2.to_k.weight: copying a param with shape torch.Size([640, 1024]) from checkpoint, the shape in current model is torch.Size([640, 768]).
        size mismatch for input_blocks.5.1.transformer_blocks.0.attn2.to_v.weight: copying a param with shape torch.Size([640, 1024]) from checkpoint, the shape in current model is torch.Size([640, 768]).
        size mismatch for input_blocks.5.1.proj_out.weight: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([640, 640, 1, 1]).
        size mismatch for input_blocks.7.1.proj_in.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1280, 1, 1]).
        size mismatch for input_blocks.7.1.transformer_blocks.0.attn2.to_k.weight: copying a param with shape torch.Size([1280, 1024]) from checkpoint, the shape in current model is torch.Size([1280, 768]).
        size mismatch for input_blocks.7.1.transformer_blocks.0.attn2.to_v.weight: copying a param with shape torch.Size([1280, 1024]) from checkpoint, the shape in current model is torch.Size([1280, 768]).
        size mismatch for input_blocks.7.1.proj_out.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1280, 1, 1]).
        size mismatch for input_blocks.8.1.proj_in.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1280, 1, 1]).
        size mismatch for input_blocks.8.1.transformer_blocks.0.attn2.to_k.weight: copying a param with shape torch.Size([1280, 1024]) from checkpoint, the shape in current model is torch.Size([1280, 768]).
        size mismatch for input_blocks.8.1.transformer_blocks.0.attn2.to_v.weight: copying a param with shape torch.Size([1280, 1024]) from checkpoint, the shape in current model is torch.Size([1280, 768]).
        size mismatch for input_blocks.8.1.proj_out.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1280, 1, 1]).
        size mismatch for middle_block.1.proj_in.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1280, 1, 1]).
        size mismatch for middle_block.1.transformer_blocks.0.attn2.to_k.weight: copying a param with shape torch.Size([1280, 1024]) from checkpoint, the shape in current model is torch.Size([1280, 768]).
        size mismatch for middle_block.1.transformer_blocks.0.attn2.to_v.weight: copying a param with shape torch.Size([1280, 1024]) from checkpoint, the shape in current model is torch.Size([1280, 768]).
        size mismatch for middle_block.1.proj_out.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1280, 1, 1]).
```

**Comment by Mikubill** [comment]
You may need to change the config file in settings

**Comment by lllyasviel** [comment]
wait, u already have trained 2.1 controlnets? amazing

**Comment by gdx09090909** [comment]
a 2.1 controlnet？

**Comment by AndyLonly** [comment]
> You may need to change the config file in settings

I tried changing the contents of default_conf in controlnet.py before posting this issue, but it didn't work
```diff
-default_conf = os.path.join(cn_models_dir, "cldm_v15.yaml")
+default_conf = os.path.join(cn_models_dir, "cldm_v21_v.yaml")
````
And I forgot to look at the settings, my bad
now working/

**Comment by AndyLonly** [comment]
![image](https://user-images.githubusercontent.com/15814794/220066280-d5bcc28c-7472-44c5-80eb-86e418b51b90.png)
![image](https://user-images.githubusercontent.com/15814794/220066310-d680d7fa-8139-47da-be87-16fc7b6db75e.png)

still working on it
> wait, u already have trained 2.1 controlnets? amazing

Yes, since I trained SD2.1 myself and therefore have a huge dataset, I just need to export the data from the dataset to generate the corresponding Ground Truth.
![image](https://user-images.githubusercontent.com/15814794/220065122-1c72b28e-b982-41dd-ac00-c00a41085ba9.png)

> a 2.1 controlnet？

If someone has trained the SD2.1 model, then they can train the controlnet2.1 model, just more slowly

**Comment by gdx09090909** [comment]
> 

amazing job ……You have done a great job. Do you need a special database for 2.1 independent model training? I see that the data released by the author are some circles. I don't know if it is possible to train good canny and openpose models with these circles for 2.1……

**Comment by AndyLonly** [comment]
> > 
> 
> amazing job ……You have done a great job. Do you need a special database for 2.1 independent model training? I see that the data released by the author are some circles. I don't know if it is possible to train good canny and openpose models with these circles for 2.1……

The dataset provided by the author is for your testing purposes only, the sole purpose is to allow you to quickly check if your code is trained correctly or to quickly verify the author's theory.

Let me share some my training details
### Processing the training set
I have never used the author's dataset, I just have the dataset for my BASE model(Yes, you need a basic model to create the controlnet model),I resized all the images in the dataset to a size of 768px and cropped using the interest points of the images. Perhaps using buckets (with different aspect ratios) would give better results, but my habit is to test the training with square images first, and switching aspect ratios slows down the training, which is already slow enough.

Currently looking for a reliable pose estimator. Although there are models that can predict anime, they cannot predict hands, and I aim to improve hands.
![5536487](https://user-images.githubusercontent.com/15814794/220110190-080abf67-6c68-4c9b-a584-0c3aad3f3e4e.png)


### Training
I wasn't quite sure how to use xformers here so I tried using mixed precision but that caused the model to break, so I was keeping to using full precision|accumulate grad = 4|batch size = 4|lr=1e-4. At this setting you may need 22GB of GPU memory.
The model is approximately 8.9GB
![image](https://user-images.githubusercontent.com/15814794/220112277-0c5466ca-fdab-4f92-ae2d-61190a053725.png)

This image is the result of 8K steps
> ![image](https://user-images.githubusercontent.com/15814794/220066280-d5bcc28c-7472-44c5-80eb-86e418b51b90.png) ![image](https://user-images.githubusercontent.com/15814794/220066310-d680d7fa-8139-47da-be87-16fc7b6db75e.png)

**Comment by Verte71** [comment]
> > > 
> > 
> > 
> > amazing job ……You have done a great job. Do you need a special database for 2.1 independent model training? I see that the data released by the author are some circles. I don't know if it is possible to train good canny and openpose models with these circles for 2.1……
> 
> The dataset provided by the author is for your testing purposes only, the sole purpose is to allow you to quickly check if your code is trained correctly or to quickly verify the author's theory.
> 
> Let me share some my training details
> 
> ### Processing the training set
> I have never used the author's dataset, I just have the dataset for my BASE model(Yes, you need a basic model to create the controlnet model),I resized all the images in the dataset to a size of 768px and cropped using the interest points of the images. Perhaps using buckets (with different aspect ratios) would give better results, but my habit is to test the training with square images first, and switching aspect ratios slows down the training, which is already slow enough.
> 
> Currently looking for a reliable pose estimator. Although there are models that can predict anime, they cannot predict hands, and I aim to improve hands. ![5536487](https://user-images.githubusercontent.com/15814794/220110190-080abf67-6c68-4c9b-a584-0c3aad3f3e4e.png)
> 
> ### Training
> I wasn't quite sure how to use xformers here so I tried using mixed precision but that caused the model to break, so I was keeping to using full precision|accumulate grad = 4|batch size = 4|lr=1e-4. At this setting you may need 22GB of GPU memory. The model is approximately 8.9GB ![image](https://user-images.githubusercontent.com/15814794/220112277-0c5466ca-fdab-4f92-ae2d-61190a053725.png)
> 
> This image is the result of 8K steps
> 
> > ![image](https://user-images.githubusercontent.com/15814794/220066280-d5bcc28c-7472-44c5-80eb-86e418b51b90.png) ![image](https://user-images.githubusercontent.com/15814794/220066310-d680d7fa-8139-47da-be87-16fc7b6db75e.png)

any chance for sharing the models for 2.1 version?

**Comment by Verte71** [comment]
any chance for sharing the models for 2.1 version?

**Comment by VladPedro** [comment]
> any chance for sharing the models for 2.1 version?

https://civitai.com/models/17292/controlnet-furusus-sd21-models

**Comment by Natotela** [comment]
> ```diff
> cldm_v21_v
> ```

not sure if you got some special treatment named cldm_v21_v.yaml
but trying to work with the much more salient and reachable cldm_v21.yaml
I'm still getting these 
```
size mismatch for middle_block.1.transformer_blocks.0.attn2.to_k.weight: copying a param with shape torch.Size([1280, 1024]) from checkpoint, the shape in current model is torch.Size([1280, 768]).
        size mismatch for middle_block.1.transformer_blocks.0.attn2.to_v.weight: copying a param with shape torch.Size([1280, 1024]) from checkpoint, the shape in current model is torch.Size([1280, 768]).
        size mismatch for middle_block.1.proj_out.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1280, 1, 1]).
```
lines of error, trying to use the sd21 v11 CN models.
Would appreciate some clarification how u made it work
or i'd just stick with 1.5 forever

**Comment by cheezecrisp** [comment]
encountered same issue. I tried sd2.1 512 and 768 models, both of them showed error message.
the control net model was control_v11p_sd21_lineart.safetensors with control_v11p_sd21_lineart.yaml, and I DO HAVE set cldm_v21.yaml in setting.
following is error message:

`Loading model: control_v11p_sd21_lineart [38981577]████████████████████████████████████| 20/20 [00:02<00:00, 11.39it/s]
Loaded state_dict from [C:\Users\cheezecrisp\MyApps\stable-diffusion-webui-1.1.0\extensions\sd-webui-controlnet\models\control_v11p_sd21_lineart.safetensors]
Loading config: C:\Users\cheezecrisp\MyApps\stable-diffusion-webui-1.1.0\extensions\sd-webui-controlnet\models\control_v11p_sd21_lineart.yaml
Error running process: C:\Users\cheezecrisp\MyApps\stable-diffusion-webui-1.1.0\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "C:\Users\cheezecrisp\MyApps\stable-diffusion-webui-1.1.0\modules\scripts.py", line 418, in process
    script.process(p, *script_args)
  File "C:\Users\cheezecrisp\MyApps\stable-diffusion-webui-1.1.0\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1073, in process
    model_net = self.load_control_model(p, unet, unit.model, unit.low_vram)
  File "C:\Users\cheezecrisp\MyApps\stable-diffusion-webui-1.1.0\extensions\sd-webui-controlnet\scripts\controlnet.py", line 734, in load_control_model
    model_net = self.build_control_model(p, unet, model, lowvram)
  File "C:\Users\cheezecrisp\MyApps\stable-diffusion-webui-1.1.0\extensions\sd-webui-controlnet\scripts\controlnet.py", line 814, in build_control_model
    network = network_module(
  File "C:\Users\cheezecrisp\MyApps\stable-diffusion-webui-1.1.0\extensions\sd-webui-controlnet\scripts\cldm.py", line 91, in __init__
    self.control_model.load_state_dict(state_dict)
  File "C:\Users\cheezecrisp\MyApps\stable-diffusion-webui-1.1.0\venv\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ControlNet:
        size mismatch for input_blocks.1.1.proj_in.weight: copying a param with shape torch.Size([320, 320]) from checkpoint, the shape in current model is torch.Size([320, 320, 1, 1]).
        size mismatch for input_blocks.1.1.transformer_blocks.0.attn2.to_k.weight: copying a param with shape torch.Size([320, 1024]) from checkpoint, the shape in current model is torch.Size([320, 768]).
        size mismatch for input_blocks.1.1.transformer_blocks.0.attn2.to_v.weight: copying a param with shape torch.Size([320, 1024]) from checkpoint, the shape in current model is torch.Size([320, 768]).
        size mismatch for input_blocks.1.1.proj_out.weight: copying a param with shape torch.Size([320, 320]) from checkpoint, the shape in current model is torch.Size([320, 320, 1, 1]).
        size mismatch for input_blocks.2.1.proj_in.weight: copying a param with shape torch.Size([320, 320]) from checkpoint, the shape in current model is torch.Size([320, 320, 1, 1]).
        size mismatch for input_blocks.2.1.transformer_blocks.0.attn2.to_k.weight: copying a param with shape torch.Size([320, 1024]) from checkpoint, the shape in current model is torch.Size([320, 768]).
        size mismatch for input_blocks.2.1.transformer_blocks.0.attn2.to_v.weight: copying a param with shape torch.Size([320, 1024]) from checkpoint, the shape in current model is torch.Size([320, 768]).
        size mismatch for input_blocks.2.1.proj_out.weight: copying a param with shape torch.Size([320, 320]) from checkpoint, the shape in current model is torch.Size([320, 320, 1, 1]).
        size mismatch for input_blocks.4.1.proj_in.weight: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([640, 640, 1, 1]).
        size mismatch for input_blocks.4.1.transformer_blocks.0.attn2.to_k.weight: copying a param with shape torch.Size([640, 1024]) from checkpoint, the shape in current model is torch.Size([640, 768]).
        size mismatch for input_blocks.4.1.transformer_blocks.0.attn2.to_v.weight: copying a param with shape torch.Size([640, 1024]) from checkpoint, the shape in current model is torch.Size([640, 768]).
        size mismatch for input_blocks.4.1.proj_out.weight: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([640, 640, 1, 1]).
        size mismatch for input_blocks.5.1.proj_in.weight: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([640, 640, 1, 1]).
        size mismatch for input_blocks.5.1.transformer_blocks.0.attn2.to_k.weight: copying a param with shape torch.Size([640, 1024]) from checkpoint, the shape in current model is torch.Size([640, 768]).
        size mismatch for input_blocks.5.1.transformer_blocks.0.attn2.to_v.weight: copying a param with shape torch.Size([640, 1024]) from checkpoint, the shape in current model is torch.Size([640, 768]).
        size mismatch for input_blocks.5.1.proj_out.weight: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([640, 640, 1, 1]).
        size mismatch for input_blocks.7.1.proj_in.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1280, 1, 1]).
        size mismatch for input_blocks.7.1.transformer_blocks.0.attn2.to_k.weight: copying a param with shape torch.Size([1280, 1024]) from checkpoint, the shape in current model is torch.Size([1280, 768]).
        size mismatch for input_blocks.7.1.transformer_blocks.0.attn2.to_v.weight: copying a param with shape torch.Size([1280, 1024]) from checkpoint, the shape in current model is torch.Size([1280, 768]).
        size mismatch for input_blocks.7.1.proj_out.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1280, 1, 1]).
        size mismatch for input_blocks.8.1.proj_in.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1280, 1, 1]).
        size mismatch for input_blocks.8.1.transformer_blocks.0.attn2.to_k.weight: copying a param with shape torch.Size([1280, 1024]) from checkpoint, the shape in current model is torch.Size([1280, 768]).
        size mismatch for input_blocks.8.1.transformer_blocks.0.attn2.to_v.weight: copying a param with shape torch.Size([1280, 1024]) from checkpoint, the shape in current model is torch.Size([1280, 768]).
        size mismatch for input_blocks.8.1.proj_out.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1280, 1, 1]).
        size mismatch for middle_block.1.proj_in.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1280, 1, 1]).
        size mismatch for middle_block.1.transformer_blocks.0.attn2.to_k.weight: copying a param with shape torch.Size([1280, 1024]) from checkpoint, the shape in current model is torch.Size([1280, 768]).
        size mismatch for middle_block.1.transformer_blocks.0.attn2.to_v.weight: copying a param with shape torch.Size([1280, 1024]) from checkpoint, the shape in current model is torch.Size([1280, 768]).
        size mismatch for middle_block.1.proj_out.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1280, 1, 1]).`
