### ISSUE TITLE
[Bug]: 5 types Controlnet,5 types deforum,5 types of everyything and always something dont work,can somebody make paid verysion po400-500$ and stop loosing our time 

### ISSUE THREAD

**Issue by dreadlocko** [Mikubill/sd-webui-controlnet#2282]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Always something happenaed .How to detele the wrong extensions,where  to upload VEA,LORA ,Embennding hidden,Lora privew dont work ,now Error: 'The feature encoder should downsample H and W by 8'. Before reporting, please check your schedules/ init values. Full error message is in your terminal/ cli.

### Steps to reproduce the problem

1. Go to .... deforrum
2. Press ....pres everythiing for hybrid video
3. ...and finally dont work 

### What should have happened?

I Ii should stAART TO EXPOORT .

### Commit where the problem happens

webui: [v1.6.0-2-g4afaaf8a](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/4afaaf8a020c1df457bcf7250cb1c7f609699fa7)
controlnet: 1.419

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
NO
```

### List of enabled extensions

deforum
sd-webui-controlnet
LDSR
Lora
ScuNET
SwinIR
<html>
<body>

canvas-zoom-and-pan | built-in | None |   |   |  
-- | -- | -- | -- | -- | --
extra-options-section | built-in | None |   |   |  
mobile | built-in | None |   |   |  
prompt-bracket-checker | built-

</body>
</html>canvas-zoom-and-pan	[built-in](http://127.0.0.1:7860/)	None			
extra-options-section	[built-in](http://127.0.0.1:7860/)	None			
mobile	[built-in](http://127.0.0.1:7860/)	None			
prompt-bracket-checker	[built-](http://127.0.0.1:7860/)

### Console logs

```Shell
canvas-zoom-and-pan	built-in	None			
extra-options-section	built-in	None			
mobile	built-in	None			
prompt-bracket-checker	built-
I CLOSED ,iT is no user friendly, lest somebody tAKE CONTROL i
```

### Additional information

i AM REALLY Sick of theis shitI am reallly sick  I prefer to delete

**Comment by huchenlei** [comment]
See https://github.com/Mikubill/sd-webui-controlnet/issues/1153 for general guideline on deforum issue.

I cannot confirm that it's ControlNet causing the problem. Please file a new issue with stacktrace attached if you are sure that ControlNet is responsible. Thanks!
