### ISSUE TITLE
not an issue - question on densepose 

### ISSUE THREAD

**Issue by johndpope** [Mikubill/sd-webui-controlnet#2287]
is there a reason why there's no densepose for controlnet? seems superior option for body detection.

https://www.reddit.com/r/StableDiffusion/comments/17yirws/openpose_alternatives_humansd_densepose/

https://github.com/facebookresearch/detectron2/issues/5166

related
https://github.com/lllyasviel/ControlNet/issues/445

**Comment by sdbds** [comment]
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/8085926/06310fd6-1c23-408b-b603-e0a772101505)
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/8085926/b82e52e6-6f2d-46c0-ba6e-fef51af59dbb)

Actually densepose should be categorized as a semantic segmentation. 
But since it doesn't have specific semantics, it doesn't work very well.
 I had a plan for a fashion segmentation, but I was too busy to deploy it.

**Comment by johndpope** [comment]
looks mint - is this done with public code - or stuff you haven't released? It's exactly what I want to do.
this guy has this model - but I don't understand how it can work. 
https://civitai.com/models/120149/controlnet-for-densepose

I did look through detectron2 stuff in repo - but there's no specific densepose references in code unless I'm mistaken.

UPDATE - I did check again and saw - but it doesn't correspond specifically to that code from facebook.
<img width="1036" alt="Screenshot 2023-12-04 at 3 33 41 pm" src="https://github.com/Mikubill/sd-webui-controlnet/assets/289994/dfef1040-4d0d-40c9-b11f-80c17dcd4786">



the segmentation - yes did see - but again does not equal the densepose.
do these lines / squiggles not carry enough information / annotations - could we extend it to give us this ? 
<img width="516" alt="Screenshot 2023-12-04 at 3 36 12 pm" src="https://github.com/Mikubill/sd-webui-controlnet/assets/289994/cf06c8a8-fc0c-44ff-a97a-e8bc0daf428d">

I'm very keen to help and see this live. would be delighted to test a branch of fashion stuff. 

I'm using chatgpt to decipher more complex code and if you haven't tried it - I recommend.
You can ask it to code up complicated algorithms and it will spit it out for you. 
It's read your repo and knows it inside out. Maybe it can help you get the fashion stuff over the line.


here's some sample code I threw at it


**comment this code from sd-webui-controlnet/controlnet-lora.py import torch**

```

Certainly! Here's a commented version of the `controlnet-lora.py` script from `sd-webui-controlnet`. The comments explain the purpose and functionality of the classes and methods within the code.

```python
import torch
from contextlib import contextmanager
from typing import Union, Tuple

# Define a type that can either be a single integer or a tuple of two integers.
_size_2_t = Union[int, Tuple[int, int]]

# Define a class for a linear layer with LoRA (Low-Rank Adaptation) modifications.
class LinearWithLoRA(torch.nn.Module):
    def __init__(
            self,
            in_features: int,
            out_features: int,
            bias: bool = True,
            device=None,
            dtype=None) -> None:
        super().__init__()
        # Initialize member variables to store layer properties and state.
        self.weight_module = None  # Will hold the original weight module for binding LoRA parameters.
        self.up = None  # LoRA-specific parameter.
        self.down = None  # LoRA-specific parameter.
        self.bias = None  # Bias parameter if used in the layer.
        self.in_features = in_features  # Number of input features.
        self.out_features = out_features  # Number of output features.
        self.device = device  # Device to which tensors will be moved.
        self.dtype = dtype  # Data type for the tensors.
        self.weight = None  # Placeholder for weight parameter.

    # Method to bind LoRA parameters to the original weights of the model.
    def bind_lora(self, weight_module):
        self.weight_module = [weight_module]

    # Method to unbind LoRA parameters from the model.
    def unbind_lora(self):
        if self.up is not None and self.down is not None:  # A condition specific to SAI's model.
            self.weight_module = None

    # Method to retrieve the original weights of the model.
    def get_original_weight(self):
        if self.weight_module is None:
            return None
        return self.weight_module[0].weight

    # Forward pass computation for the linear layer with LoRA.
    def forward(self, x):
        if self.weight is not None:
            # If weight is set manually, use it for the linear transformation.
            return torch.nn.functional.linear(x, self.weight.to(x),
                                              self.bias.to(x) if self.bias is not None else None)

        # Retrieve the original weight.
        original_weight = self.get_original_weight()

        if original_weight is None:
            return None  # If original weight is not available, return None.

        # Compute the new weight using LoRA parameters if they are bound.
        if self.up is not None and self.down is not None:
            weight = original_weight.to(x) + torch.mm(self.up, self.down).to(x)
        else:
            weight = original_weight.to(x)

        # Perform the linear transformation using the computed weights.
        return torch.nn.functional.linear(x, weight, self.bias.to(x) if self.bias is not None else None)

# Define a class for a 2D convolutional layer with LoRA modifications.
# This class is similar to LinearWithLoRA but for convolutional layers.
class Conv2dWithLoRA(torch.nn.Module):
    # The __init__ method initializes layer properties similar to the linear layer.
    # The forward method performs the convolution operation using possibly modified weights due to LoRA.

    # ... (Similar methods for convolutional layers as in LinearWithLoRA)

# Context manager to temporarily hijack the torch.nn.Linear and torch.nn.Conv2d
# classes to use LinearWithLoRA and Conv2dWithLoRA classes instead.
@contextmanager
def controlnet_lora_hijack():
    # Save references to the original Linear and Conv2d classes.
    linear, conv2d = torch.nn.Linear, torch.nn.Conv2d
    # Replace the original classes with the LoRA-equipped versions.
    torch.nn.Linear, torch.nn.Conv2d = LinearWithLoRA, Conv2dWithLoRA
    try:
        # Yield control back to the caller, allowing them to run code with the hijacked classes.
        yield
    finally:
        # After the caller's code is done, restore the original Linear and Conv2d classes.
        torch.nn.Linear, torch.nn.Conv2d = linear, conv2d

# Recursive function to set attributes on an object, supporting nested attributes.
def recursive_set(obj, key, value):
    # ... (Code to set a nested attribute value)

# Function to forcibly load a state dictionary into a model.
# This ignores the usual checks performed by PyTorch's load_state_dict method.
def force_load_state_dict(model, state_dict):
    # ... (Code to force state_dict values into the model)

# Recursive function to bind LoRA parameters to the model.
def recursive_bind_lora(obj, key, value
```

**Comment by FurkanGozukara** [comment]
anyone found a way to convert a video into densepose video?

https://github.com/facebookresearch/detectron2/issues/5170

**Comment by lllyasviel** [comment]
Because in 2022 I tried all dense pose, and all SMPL-based models like [HybrIK](https://github.com/Jeff-sjtu/HybrIK) (that are even better as claimed by many research) but none of them is robust enough to process dataset as noisy as LAION AES. Those methods seem only work for monocular camera with a very aligned person in the main view, and never generalize to in-the-wild LAION, let alone artworks.

However, if someone only needs datasets like TikTok dancing, perhaps some of these would work, but I am still not sure.

I also hope that I am wrong about this - if someone can use some data to show that those SMPL-based pose methods are better than my tests in 2022. but again, if only for some TikTok dancing, perhaps we do not need really robust annotations.

BTW, if you try to install densepose or HybrIK, you will find that those codes extremely difficult to set up - last year I spent 5 weeks to figure out how to install them - if you are interested, then begin your 5-week journey now

**Comment by sdbds** [comment]
> looks mint - is this done with public code - or stuff you haven't released? It's exactly what I want to do. this guy has this model - but I don't understand how it can work. https://civitai.com/models/120149/controlnet-for-densepose
> 
> I did look through detectron2 stuff in repo - but there's no specific densepose references in code unless I'm mistaken.
> 
> UPDATE - I did check again and saw - but it doesn't correspond specifically to that code from facebook. <img alt="Screenshot 2023-12-04 at 3 33 41 pm" width="1036" src="https://private-user-images.githubusercontent.com/289994/287591807-dfef1040-4d0d-40c9-b11f-80c17dcd4786.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3OTA1ODksIm5iZiI6MTcwMTc5MDI4OSwicGF0aCI6Ii8yODk5OTQvMjg3NTkxODA3LWRmZWYxMDQwLTRkMGQtNDBjOS1iMTFmLTgwYzE3ZGNkNDc4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNVQxNTMxMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDcwNDc0MzNhMzZhNDNmODJjMTkzNTAzM2E4YmE2MWIzZDhjMGE3ZmE0N2RjODc3MDk4NTQ0OTQxN2ZiZjJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hyMwFtpzykuWhd7tfKTLh1JEKAnJn-_H4Fk6ted_UG0">
> 
> the segmentation - yes did see - but again does not equal the densepose. do these lines / squiggles not carry enough information / annotations - could we extend it to give us this ? <img alt="Screenshot 2023-12-04 at 3 36 12 pm" width="516" src="https://private-user-images.githubusercontent.com/289994/287591915-cf06c8a8-fc0c-44ff-a97a-e8bc0daf428d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3OTA1ODksIm5iZiI6MTcwMTc5MDI4OSwicGF0aCI6Ii8yODk5OTQvMjg3NTkxOTE1LWNmMDZjOGE4LWZjMGMtNDRmZi1hOTdhLWU4YmMwZGFmNDI4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNVQxNTMxMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZGE3ZTE4MjcyOGZiOWQwYTQ5ZDc1YzNmZjYxOWNiYTc5NGY1ZjczYWQ4M2M2MjFhNDg2MzIzYTE2MTY3MzJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qn19LChBKUsKkGhPZzuefcH3aJ4arXrhagzvroW6u80">
> 
> I'm very keen to help and see this live. would be delighted to test a branch of fashion stuff.
> 
> I'm using chatgpt to decipher more complex code and if you haven't tried it - I recommend. You can ask it to code up complicated algorithms and it will spit it out for you. It's read your repo and knows it inside out. Maybe it can help you get the fashion stuff over the line.
> 
> here's some sample code I threw at it
> 
> **comment this code from sd-webui-controlnet/controlnet-lora.py import torch**
> 
> Certainly! Here's a commented version of the `controlnet-lora.py` script from `sd-webui-controlnet`. The comments explain the purpose and functionality of the classes and methods within the code.
> 
> ```python
> import torch
> from contextlib import contextmanager
> from typing import Union, Tuple
> 
> # Define a type that can either be a single integer or a tuple of two integers.
> _size_2_t = Union[int, Tuple[int, int]]
> 
> # Define a class for a linear layer with LoRA (Low-Rank Adaptation) modifications.
> class LinearWithLoRA(torch.nn.Module):
>     def __init__(
>             self,
>             in_features: int,
>             out_features: int,
>             bias: bool = True,
>             device=None,
>             dtype=None) -> None:
>         super().__init__()
>         # Initialize member variables to store layer properties and state.
>         self.weight_module = None  # Will hold the original weight module for binding LoRA parameters.
>         self.up = None  # LoRA-specific parameter.
>         self.down = None  # LoRA-specific parameter.
>         self.bias = None  # Bias parameter if used in the layer.
>         self.in_features = in_features  # Number of input features.
>         self.out_features = out_features  # Number of output features.
>         self.device = device  # Device to which tensors will be moved.
>         self.dtype = dtype  # Data type for the tensors.
>         self.weight = None  # Placeholder for weight parameter.
> 
>     # Method to bind LoRA parameters to the original weights of the model.
>     def bind_lora(self, weight_module):
>         self.weight_module = [weight_module]
> 
>     # Method to unbind LoRA parameters from the model.
>     def unbind_lora(self):
>         if self.up is not None and self.down is not None:  # A condition specific to SAI's model.
>             self.weight_module = None
> 
>     # Method to retrieve the original weights of the model.
>     def get_original_weight(self):
>         if self.weight_module is None:
>             return None
>         return self.weight_module[0].weight
> 
>     # Forward pass computation for the linear layer with LoRA.
>     def forward(self, x):
>         if self.weight is not None:
>             # If weight is set manually, use it for the linear transformation.
>             return torch.nn.functional.linear(x, self.weight.to(x),
>                                               self.bias.to(x) if self.bias is not None else None)
> 
>         # Retrieve the original weight.
>         original_weight = self.get_original_weight()
> 
>         if original_weight is None:
>             return None  # If original weight is not available, return None.
> 
>         # Compute the new weight using LoRA parameters if they are bound.
>         if self.up is not None and self.down is not None:
>             weight = original_weight.to(x) + torch.mm(self.up, self.down).to(x)
>         else:
>             weight = original_weight.to(x)
> 
>         # Perform the linear transformation using the computed weights.
>         return torch.nn.functional.linear(x, weight, self.bias.to(x) if self.bias is not None else None)
> 
> # Define a class for a 2D convolutional layer with LoRA modifications.
> # This class is similar to LinearWithLoRA but for convolutional layers.
> class Conv2dWithLoRA(torch.nn.Module):
>     # The __init__ method initializes layer properties similar to the linear layer.
>     # The forward method performs the convolution operation using possibly modified weights due to LoRA.
> 
>     # ... (Similar methods for convolutional layers as in LinearWithLoRA)
> 
> # Context manager to temporarily hijack the torch.nn.Linear and torch.nn.Conv2d
> # classes to use LinearWithLoRA and Conv2dWithLoRA classes instead.
> @contextmanager
> def controlnet_lora_hijack():
>     # Save references to the original Linear and Conv2d classes.
>     linear, conv2d = torch.nn.Linear, torch.nn.Conv2d
>     # Replace the original classes with the LoRA-equipped versions.
>     torch.nn.Linear, torch.nn.Conv2d = LinearWithLoRA, Conv2dWithLoRA
>     try:
>         # Yield control back to the caller, allowing them to run code with the hijacked classes.
>         yield
>     finally:
>         # After the caller's code is done, restore the original Linear and Conv2d classes.
>         torch.nn.Linear, torch.nn.Conv2d = linear, conv2d
> 
> # Recursive function to set attributes on an object, supporting nested attributes.
> def recursive_set(obj, key, value):
>     # ... (Code to set a nested attribute value)
> 
> # Function to forcibly load a state dictionary into a model.
> # This ignores the usual checks performed by PyTorch's load_state_dict method.
> def force_load_state_dict(model, state_dict):
>     # ... (Code to force state_dict values into the model)
> 
> # Recursive function to bind LoRA parameters to the model.
> def recursive_bind_lora(obj, key, value
> ```

https://github.com/yumingj/Text2Human

Here.I have not finished it, if they had pretrained model, i can directly use it and make a controlnet.

**Comment by Fannovel16** [comment]
> BTW, if you try to install densepose or HybrIK, you will find that those codes extremely difficult to set up - last year I spent 5 weeks to figure out how to install them - if you are interested, then begin your 5-week journey now

I can install it on Colab after three days of searching a fork that supports pytorch 2 and another week to understand how their TracingAdapter work. But yeah I agree that it's difficult to install detectron2

**Comment by johndpope** [comment]
seems like dwpose takes the lead here -
https://www.reddit.com/r/StableDiffusion/comments/18g52mv/magicanimate_dwpose_preprocessor_is_actually/

controlnet implementation here 
https://github.com/IDEA-Research/DWPose/tree/onnx/ControlNet-v1-1-nightly
