### ISSUE TITLE
[Feature Request] Support for StyleAlign

### ISSUE THREAD

**Issue by catboxanon** [Mikubill/sd-webui-controlnet#2290]
Title. Recent paper from Google. https://github.com/google/style-aligned/

One of the relevant ControlNet-related samples they provide:

![cn_example](https://raw.githubusercontent.com/google/style-aligned/main/doc/cn_example.jpg)

If this is out of scope for implementing as part of this extension, feel free to close.

**Comment by lllyasviel** [comment]
this method’s input seems a set of prompts like 
[
  "a toy train. macro photo. 3d game asset",
  "a toy airplane. macro photo. 3d game asset",
  "a toy bicycle. macro photo. 3d game asset",
  "a toy car. macro photo. 3d game asset",
  "a toy boat. macro photo. 3d game asset",
]
And outputs are a batch of images with same style.
The same style is based on sharing reference attention and adain.
This should not be difficult to implement – does webui prompt processing support permutation grammar like “a toy {train, airplane, bicycle}. macro photo. 3d game asset” in a same batch? For example, {train, airplane, bicycle} needs a batch size 3.
And ... If it has, is that permutation still functioning in recent versions?

**Comment by huchenlei** [comment]
I think the permutation support is from this extension https://github.com/adieyal/sd-dynamic-prompts.

**Comment by lllyasviel** [comment]
but I remember somewhere that things like "a toy {train, airplane, bicycle}"  are natively supported in some way
I thought I read some doc for this a long time ago
