### ISSUE TITLE
Any instruction how to install under M1 MAC ?

### ISSUE THREAD

**Issue by organicmind-pixel** [Mikubill/sd-webui-controlnet#230]
Any instruction how to install under M1 MAC .. please ?

**Comment by missionfloyd** [comment]
Assuming you've already [installed](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Installation-on-Apple-Silicon) AUTO1111, follow the instructions in the [readme](https://github.com/Mikubill/sd-webui-controlnet/blob/main/README.md).

**Comment by organicmind-pixel** [comment]
Thank You .. i will try
