### ISSUE TITLE
[feature request] load weights of unlocked diffusion model 

### ISSUE THREAD

**Issue by BigDevil82** [Mikubill/sd-webui-controlnet#2327]
I've trained a ControlNet on my dataset, and setting sd_locked = False turns out to improve model performance significantly.
I learned that unlocking sd will also train some parts of the diffusion model, so the base model also changed. But it seems this extension does not support this feature, it only loads ControlNet, leaving sd base model unchanged. In this case, I can not make full use of the trained model because the fine-tuned diffusion model is not used. I rely on automatical1111's webui to combine capabilities of different techniques like LoRA and ControlNet.
Thanks for any advice!

**Comment by huchenlei** [comment]
Just load your trained SD model in A1111. This extension does not handle loading of SD base model.
