### ISSUE TITLE
It worked for one image, and now gives me constant expected - got errors

### ISSUE THREAD

**Issue by Oem42** [Mikubill/sd-webui-controlnet#233]
i keep getting RuntimeError: Given groups=1, weight of size [320, 4, 3, 3], expected input[1, 9, 64, 64] to have 4 channels, but got 9 channels instead

tried restarting ui, different models

**Comment by Mikubill** [comment]
fixed in https://github.com/Mikubill/sd-webui-controlnet/commit/1b2cf8dd137a18d8cbcc71b0fcb6cf3e55cc8b15.
