### ISSUE TITLE
[Bug]: Style database not found: /content/gdrive/MyDrive/sd/stable-diffusion-webui/styles.csv

### ISSUE THREAD

**Issue by Rovnova** [Mikubill/sd-webui-controlnet#2343]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

hi!
 after the update there is still an issue with fast_stable_diffusion_AUTOMATIC1111.ipynb for google colab: Style database not found(also since yesterday (I don't think it's related) ERROR: Exception in ASGI application appeared).
It is also impossible to install any extension - infinite loading is going on......
![Снимок экрана 2023-12-20 в 12 19 03](https://github.com/Mikubill/sd-webui-controlnet/assets/72410079/079d364e-b47f-428b-b348-d64bdbea7e3f)
![Снимок экрана 2023-12-20 в 12 23 35](https://github.com/Mikubill/sd-webui-controlnet/assets/72410079/442234cd-258c-
![Снимок экрана 2023-12-20 в 12 23 42](https://github.com/Mikubill/sd-webui-controlnet/assets/72410079/7f9228e7-792e-4bd2-9e2f-96d5720058ec)
4b3a-8e57-e69c5f15ba57)

### Steps to reproduce the problem

1. Go to fast_stable_diffusion_AUTOMATIC1111.ipynb in google colab 
2. try changing the model (loading from 0.0)
3. go to Extensions, click Load from 

### What should have happened?

should load models when selected, and be able to install any extension  in the Extensions

### Commit where the problem happens

webui: 
controlnet: 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
no
```

### List of enabled extensions

![Снимок экрана 2023-12-20 в 12 23 42](https://github.com/Mikubill/sd-webui-controlnet/assets/72410079/130f95f7-f0e6-41be-8e9c-b6bb7da3446e)
![Снимок экрана 2023-12-20 в 12 23 35](https://github.com/Mikubill/sd-webui-controlnet/assets/72410079/26d07311-f6c7-4cda-84bf-8f513a6d8d0f)

### Console logs

```Shell
https://colab.research.google.com/drive/1ECSMOHt8bg5KMjpuxZNHRX9fP_3vvLND#scrollTo=PjzwxTkPSPHf
```

**Comment by huchenlei** [comment]
I am not convinced that the issue is caused by ControlNet extension. The log message you see does not come from code in this repo. You can file an issue in https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues instead.
