### ISSUE TITLE
[Bug]: ONLY MASKED not working with IPAdapter

### ISSUE THREAD

**Issue by 2blackbar** [Mikubill/sd-webui-controlnet#2347]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

You cant really use ipadapter in inpaint only masked mode now, cause when i use face image in ipadapter and only masked mode then i get this out of whole face in ipadapter preview after generation 
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/33694664/601b55ad-a70d-42ef-9302-ca6c5a020abd)

### Steps to reproduce the problem

IT just uses small chunk of the top left corner of the image when you use only masked, this is not how otther models work , other models properly use only masked inpaint mode so . So i hink pipeline for it is still borked.

I mean other models work fine cause they take a chunk but this one needs to take whole image as input to work in only masked mode, not a chunk.

### What should have happened?

They way it should work is i use face image for ipadapter, i mask the face in inpaint only masked mode , and it inpaints the face using ipadapter.

### Commit where the problem happens

webui: 
controlnet: 

### Command Line Arguments

```Shell
...
```

### List of enabled extensions

...

### Console logs

```Shell
...
```

**Comment by huchenlei** [comment]
See #2148
