### ISSUE TITLE
[Bug]: Controlnet seting Elements missing  (A111-Version: v1.7.0） 

### ISSUE THREAD

**Issue by Macroeye** [Mikubill/sd-webui-controlnet#2353]
Sorry, the first time I asked the question, I didn't ask it in the correct way.Also forgot to set the label.

 I have searched the existing issues and checked the recent builds/commits of both this extension and the webui 

After I updated SD and controlnet, the default settings bar is different from your settings and I cannot select different versions of models.
stable-diffusion-webui[Version: v1.7.0]
sd-webui-controlnet[v1.1.424]
OS[win]
Browser[Microsoft Edge]

This is your setting
![ControlNet-Default Setting](https://github.com/Mikubill/sd-webui-controlnet/assets/34118808/b73fc278-fb21-4b6b-b5aa-f33067a30b1c)

This is my setting
![my setting](https://github.com/Mikubill/sd-webui-controlnet/assets/34118808/7efd5ecf-60a1-4b29-a41f-22f78509a0d0)

Missing 
Config file for Control Net models
Config file for Adapter models

**Comment by huchenlei** [comment]
Those yaml config files are no longer needed since version v1.1.400.
