### ISSUE TITLE
[Bug]: FaceID adapter support

### ISSUE THREAD

**Issue by dan4ik94** [Mikubill/sd-webui-controlnet#2354]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

The new FaceID adapter model doesn't work currently, controlnet throws an error.
https://huggingface.co/h94/IP-Adapter-FaceID

### Steps to reproduce the problem

-

### What should have happened?

-

### Commit where the problem happens

webui: -
controlnet: [4ceb6e8](https://github.com/Mikubill/sd-webui-controlnet/commit/4ceb6e8a4b86605cdeb6cd7087d1d7ef34452d85)

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
-
```

### List of enabled extensions

-

### Console logs

```Shell
RuntimeError: Error(s) in loading state_dict for MLPProjModel:
        Missing key(s) in state_dict: "proj.3.weight", "proj.3.bias".
        Unexpected key(s) in state_dict: "norm.weight", "norm.bias".
        size mismatch for proj.0.weight: copying a param with shape torch.Size([1024, 512]) from checkpoint, the shape
in current model is torch.Size([512, 512]).
        size mismatch for proj.0.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in
current model is torch.Size([512]).
        size mismatch for proj.2.weight: copying a param with shape torch.Size([3072, 1024]) from checkpoint, the shape
in current model is torch.Size([768, 512]).
        size mismatch for proj.2.bias: copying a param with shape torch.Size([3072]) from checkpoint, the shape in
current model is torch.Size([768]).
```

**Comment by sdbds** [comment]
This model is not currently supported because it uses the external insightface library. 
The author of ipadapter has been contacted and is currently on the development schedule.

**Comment by nicksonit** [comment]
okay, thanks

> This model is not currently supported because it uses the external insightface library. The author of ipadapter has been contacted and is currently on the development schedule.

okay, thanks

**Comment by huchenlei** [comment]
Done in https://github.com/Mikubill/sd-webui-controlnet/pull/2434.
