### ISSUE TITLE
[Bug]: Control Type Model list is empty for any type but ALL

### ISSUE THREAD

**Issue by zexcster** [Mikubill/sd-webui-controlnet#2363]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Upgraded to 1.7.0 A1111, all extensions updated to the latest. ControlNet v1.1.424
Now you cannot select any model from the drop down list if you use Control Type selection and if you select any type but All
 (btw the option Disable Control Type Selection is also removed from the settings)

### Steps to reproduce the problem

1 Open ControlNet panel
2 Click Canny/ Depth or any other existing template
3 Open Preprocessor list, it works fine
4 Open Model drop down list, it's empty

P.S. if you select ALL, it shows all models and preprocessors, so the bug is not critical
5 Open ControlNet settings in the settings tab, "Disable Control Type selection" is gone

### What should have happened?

The model list should have all models preloaded according to the type selected

### Commit where the problem happens

webui: 1.7.0
controlnet:  v1.1.424
 

### Command Line Arguments

```Shell
no
```

### List of enabled extensions

controlnet:  v1.1.424

### Console logs

```Shell
There's no any errors in logs or developer console
```

**Comment by zexcster** [comment]
addition
4.1 press refresh button for models, it will load all existing models, not only connected to the preprocessor selected

**Comment by huchenlei** [comment]
Now we filter controlnet models based on your active SD base model's version. If you use sdxl base model and do not have any sdxl controlnet model available, the selection will be empty.

**Comment by zexcster** [comment]
Hmm, I  didn't use SDXL models (v 1.5), 
it seems you've changed filename filters. it cannot find names like 
controlnet11Models_canny, 
controlnet11Models_depth, 
controlnet11Models_openpose.safetensors

Although it can see find coadapter-depth-sd15v1.pth  

But it was Ok before with the same filenames, it gave me all existing OpenPose models, or Canny, etc. accordingly

I'll try to find the code to see the changes

**Comment by huchenlei** [comment]
The code basically infers SD version based on filename. File names need to contain sd15 for SD1.5 or xl for SDXL.

**Comment by zexcster** [comment]
understood, thank you for the tip :)
but I would show controlnet models with StableDiffusionVersion.UNKNOWN anyway for models < XL if no other compatible found (or even for XL) . **Or just put the most compatible on top. ** 

Otherwise it's not user friendly when you have lots of files and they suddenly stopped showing in the list.

v15 and 15.v2 in most cases are compatible with each other, in worse  scenario it just gives a bad generation. At least user can change a model after it. I would be a user error.

Many models from civitai or hugging face does not contain V15 in the names (those were downloaded from civitai). But 99% of them contain XL.

**Comment by huchenlei** [comment]
These file naming detection is only for ControlNet model files. For SD base model, the detection is not based on file name.
