### ISSUE TITLE
[Bug]: Anyone else getting weird scribble results like this (SDXL)?

### ISSUE THREAD

**Issue by F0xbite** [Mikubill/sd-webui-controlnet#2364]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?
Checkpoint: SDXLFaetastic_v20.safetensors [f02c2a8d29]
CN Model: kohya_controllllite_xl_scribble_anime [d39b679a]
Preprocessor: scribble_pidinet 
Sampler: Euler a
1024x1024 (no HRF)

Source image:
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/133003026/f019a34d-3eb2-4d3d-bb60-35fbd1aed6bf)
Prompt: sheep
Result:
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/133003026/7a695f30-6a21-4e99-af25-435ef78e6b33)
(bad result)

But if i use a different prompt (with exact same settings, model, checkpoint, everything)
Prompt: dog
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/133003026/8617b3b9-2bd5-4953-ae7e-cf3411054c62)
(good result)

Using another prompt: rainbow
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/133003026/75c7745f-8dbb-413c-ae57-6653b8f5f30b)
Bad result

Same settings, different prompt: cat
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/133003026/59eb9d93-b47d-4961-a2fc-b3dcbed8ba54)
Good result

I'm thoroughly confused...
I'm not changing any settings at all with any of these examples, only the prompt.

### Steps to reproduce the problem

use the settings above 

### What should have happened?

Consistently good results with no weird artifacts

### Commit where the problem happens

webui: latest
controlnet: latest

### Command Line Arguments

```Shell
--medvram
```

### List of enabled extensions

controlnet

### Console logs

```Shell
n/a
```

**Comment by sdbds** [comment]
it seems like model problem not webui-controlnet

**Comment by F0xbite** [comment]
> it seems like model problem not webui-controlnet

Agreed, but i've tried these 3 models, and all of them yielded basically the same kind of results (hard lines)
t2i-adapter-sketch-sdxl-1.0
sai_xl_sketch_256lora
kohya_controllllite_xl_scribble_anime

It seems that there are no good scribble models that exist for XL. Kohya did the best of these 3, but as you see in the examples, it's hit and miss

**Comment by sdbds** [comment]
> > it seems like model problem not webui-controlnet
> 
> Agreed, but i've tried these 3 models, and all of them yielded basically the same kind of results (hard lines) t2i-adapter-sketch-sdxl-1.0 sai_xl_sketch_256lora kohya_controllllite_xl_scribble_anime
> 
> It seems that there are no good scribble models that exist for XL. Kohya did the best of these 3, but as you see in the examples, it's hit and miss

try this
https://huggingface.co/bdsqlsz/qinglong_controlnet-lllite

**Comment by F0xbite** [comment]
> > > it seems like model problem not webui-controlnet
> > 
> > 
> > Agreed, but i've tried these 3 models, and all of them yielded basically the same kind of results (hard lines) t2i-adapter-sketch-sdxl-1.0 sai_xl_sketch_256lora kohya_controllllite_xl_scribble_anime
> > It seems that there are no good scribble models that exist for XL. Kohya did the best of these 3, but as you see in the examples, it's hit and miss
> 
> try this https://huggingface.co/bdsqlsz/qinglong_controlnet-lllite

Thank you! It actually gave the same sort of results, but I discovered something

Using Highres fix, i get a good clean result every time, but without it, it consistently gives me the weird lines.

That's a little unfortunate though, as Highres fix has a tendency to mess up small details like text, but for Scribble, that's not a major concern since it doesn't exactly adhere to the lines anyway.
