### ISSUE TITLE
[Feature Request] MeshGraphormer Hand Refiner Preprocessor

### ISSUE THREAD

**Issue by Fannovel16** [Mikubill/sd-webui-controlnet#2382]
The depth map preprocessor used in [HandRefiner](https://github.com/wenquanlu/HandRefiner)
My implementation (bundled a fork of MeshGraphormer and manopth, works on MPS and removed chumpy): https://github.com/Fannovel16/comfyui_controlnet_aux/blob/main/src/controlnet_aux/mesh_graphormer/__init__.py
Bundled dependencies: [manopth](https://github.com/Fannovel16/comfyui_controlnet_aux/tree/main/src/custom_manopth), [MeshGraphormer](https://github.com/Fannovel16/comfyui_controlnet_aux/tree/main/src/custom_mesh_graphormer)
Additional dependencies: yacs, trimesh[easy]
Note that I used `comfy.model_management.get_torch_device()` to get torch device.
Expected result:
![example_mesh_graphormer](https://github.com/Mikubill/sd-webui-controlnet/assets/16047777/8bb54634-bb8e-4185-81ea-cb0f9f2e3313)

**Comment by huchenlei** [comment]
Ok, I am going to try implement it here.

**Comment by huchenlei** [comment]
I think the impl can go with 2 stages:
- A depth preprocessor that outputs the hand depth map added to the preprocessor list
- A new mechanism to wire the output mask back to a1111 inpaint. In img2img mode, directly modify the generation processing object? This maybe similar to what ADetailer does.

In first stage, user can manually draw inpaint mask.

**Comment by huchenlei** [comment]
Reference ComfyUI workflow:
[hand_refiner_cnet.json](https://github.com/Mikubill/sd-webui-controlnet/files/13806089/hand_refiner_cnet.json)

**Comment by Gushousekai195** [comment]
How soon will this be done?

**Comment by 2blackbar** [comment]
id wire it to inpaint masked cause it can then go 512res on each hand separately and get higher quality

**Comment by huchenlei** [comment]
@2blackbar please file a separate issue for inpaint fill mode bug.
