### ISSUE TITLE
[Feature Request] Connect to photopea only when used

### ISSUE THREAD

**Issue by chr1st0ph3rGG** [Mikubill/sd-webui-controlnet#2384]
To put it simple, I am not a big fan of ad supported software (like photopea) and having controlnet loading photopea right when starting webui without even opening the controlnet part in the ui is really annoying as it increases the load time of my webui setup (I dont have a fast connection right now)... my current solution is having the whole controlnet extension deactivate if im not using anything controlnet related, but thats not a good solution either... 

So my request is simply, connect to photopea only when the edit modal is opened... 

Beside that and out of curiosity, how well does using photopea work with the fact that this extension is licensed under GPL3?

**Comment by huchenlei** [comment]
This extension is licensed under GPL, not AGPL(A1111), so the services provided through network does not need to be opensourced. I will add a config switch to let you disable load of photopea edit.
