### ISSUE TITLE
[Bug]: The Remove Near % and Remove Far % for the depth_leres preprocessors are not exposed in the API

### ISSUE THREAD

**Issue by dayunbao** [Mikubill/sd-webui-controlnet#2389]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

The API does not accept the Remove Near % and Remove Far % parameters for the depth_leres preprocessors

### Steps to reproduce the problem

Check the api.py module to see that they are not accepted.

### What should have happened?

I should be able to send those values via the API.

### Commit where the problem happens

NA

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
NA
```

### List of enabled extensions

NA

### Console logs

```Shell
NA
```

### Additional information

I want to be able to send that information via the API.

**Comment by huchenlei** [comment]
Use `threadhold_a` and `threshold_b` in the API.
