### ISSUE TITLE
[Bug]: After the latest update, which added the hires-fix option, ControlNet began to work incorrectly for me.

### ISSUE THREAD

**Issue by GlukXP** [Mikubill/sd-webui-controlnet#2390]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

After the latest update, which added the hires-fix option, ControlNet began to work incorrectly for me.
1) Tab 0 glows green when turned on, but the rest do not. With any variations.
2) When you enable the zero tab, the page freezes in any browser, and models also change with a huge delay.
No errors are displayed in the program window.
3) If you use only one 0 tab, everything works, if you use 2-3 ControlNet tabs, it simply generates as if they are disabled. If you use the other tabs without tab 0, everything works too. There are no errors or anything else in the window.

Developer,
Please do not need to reply, etc., to this message. Just check the latest update for code changes that could cause similar errors.

### Steps to reproduce the problem

1. Go to webui
2. Press ControlNet
3. Tab 0 does not work with other tabs

### What should have happened?

Just check the update code where the hires-fix option was added.

### Commit where the problem happens

webui: 
controlnet: 

### Command Line Arguments

```Shell
set COMMANDLINE_ARGS=--opt-sdp-attention --upcast-sampling --opt-channelslast --lowram --api
```

### List of enabled extensions

minimum

### Console logs

```Shell
no
```

**Comment by IvanKorobko** [comment]
On these points everything works fine for me(on SD v1.7.0, CN v1.1.426). All 0-3 tabs works correctly(together and separately). Nothing freezes or lags. When turned on, every tab lights up green ¯\_(ツ)_/¯

**Comment by huchenlei** [comment]
I cannot reproduce the issue locally. Can you share your browser console log and A1111 log?

**Comment by lellotrek** [comment]
Hi guys, i had the same issue before. I was on SD v1.6.0-2 so i updated to version 1.7.0  and all fix now, just to let you know, thanks.

**Comment by ARZUMATA** [comment]
Here is how it works on A1111 - 1.6.1

Firefox console


```
error running callback 
function () : TypeError: can't access property "addEventListener", hr_checkbox is null
```



attachA1111HrObserver always spam to the console.

New commits seems to orient on newer version of a1111:

On 1.7.0 it works because in A1111 they changed UI and now HiresFix drop down includes the check box.
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/54457203/e472b095-47c1-46de-878f-c359fe04c836)
Older versions on A1111 didn't have that.

**Comment by huchenlei** [comment]
Thanks for the insight. Going to fix it for backward compatibility.
