### ISSUE TITLE
IPAdapter determinism?

### ISSUE THREAD

**Issue by onewhoflies** [Mikubill/sd-webui-controlnet#2395]
When using A1111 and ControlNet, generating an image with the `ip-adapter_clip_sd15` preprocessor and `ip-adapter-plus_sd15` model generates slightly (very slightly) different images every time, so my results can’t be recreated via PNG info. Is this intended behavior? Sometimes the differences are very subtle, and other times they aren't (depending on the subject).

Overall, images are generated in txt2img w/ **ADetailer**, **ControlNet IP Adapter**, and **Dynamic Thresholding**.

I am using `sdp-no-mem` for cross attention optimization (deterministic), **no** Xformers, and `Low VRAM` is **not** checked in the active ControlNet unit.

When I disable IP-Adapter in CN, I get the same images with all variables staying the same as expected.

I’ll keep investigating, but I just wanted to post here to see if anyone else has experienced this issue (or know if this is intended behavior of this IP-Adapter setup). I also tried downgrading webui-CN to different versions to no avail as well.

Running A1111 on an RTX 4090 + i9-14900K.

Example generation params below.

Model: epicphotogasm_lastUnicorn

**Positive prompt**: philosopher sculpture
**Negative prompt**: BadDream, (UnrealisticDream:1.2)
**Seed**: 1083703543

**IP Adapter input image:**
![seneca](https://github.com/Mikubill/sd-webui-controlnet/assets/20614633/59ee5275-a0e6-493b-8579-e27939a9a11e)

Outputs when generating 1 image, then generating again right after with the same parameters:

![42808-1083703543-philosopher sculpture](https://github.com/Mikubill/sd-webui-controlnet/assets/20614633/06a278d8-e552-4af1-83c7-c2f7006951ef)

![42809-1083703543-philosopher sculpture](https://github.com/Mikubill/sd-webui-controlnet/assets/20614633/655baebd-f9a8-4a5f-b675-7ae0f7ded6b4)

(differences are subtle but can be seen by switching back and forth between these images)

PNG Info:
`Steps: 30, Sampler: DPM++ 2M SDE Karras, CFG scale: 20, Seed: 1083703543, Size: 640x800, Model hash: 62bb78983a, Model: epicphotogasm_lastUnicorn, ControlNet 0: "Module: ip-adapter_clip_sd15, Model: ip-adapter-plus_sd15 [836b5c2e], Weight: 0.35, Resize Mode: Crop and Resize, Low Vram: False, Processor Res: 512, Guidance Start: 0, Guidance End: 1, Pixel Perfect: True, Control Mode: ControlNet is more important, Save Detected Map: True", Dynamic thresholding enabled: True, Mimic scale: 7, Separate Feature Channels: True, Scaling Startpoint: MEAN, Variability Measure: AD, Interpolate Phi: 1, Threshold percentile: 99.5, Mimic mode: Half Cosine Up, Mimic scale minimum: 4, CFG mode: Half Cosine Up, CFG scale minimum: 4
`
Same generation parameters with IP Adapter CN disabled:

![42810-1083703543-philosopher sculpture](https://github.com/Mikubill/sd-webui-controlnet/assets/20614633/81f17876-70b0-478a-95d1-a94f60de1492)

![42811-1083703543-philosopher sculpture](https://github.com/Mikubill/sd-webui-controlnet/assets/20614633/9d6f7c92-a5aa-48a2-8a09-a0b9fe8c7c65)

Generated back to back (batch size 1, batch count 1), and the images are the exact same (as expected).

**Comment by sdbds** [comment]
It's not deterministic because it also uses the UNET architecture.
