### ISSUE TITLE
Midas loads repeatedly without unloading?

### ISSUE THREAD

**Issue by Dekker3D** [Mikubill/sd-webui-controlnet#24]
So one thing I'm noticing is that, when I change away from a depth-based model (or just disable the ControlNet stuff for a few gens), and then switch back, it tries to load Midas again, and fails with a CUDA memory error. I think it tries to reload the model without having first properly unloaded it. I have to restart the entire program each time this happens, with 16 gb ram and 10 gb vram.

**Comment by Mikubill** [comment]
Need to cleanup model loaders in annotator

**Comment by Danamir** [comment]
I had the same problem of VRAM leak yesterday when switching from many models.

**Comment by ChinatsuHS** [comment]
yea..seems the controlnet models do not unload after generations , so switching to another one just adds to the already loaded VRAM... hope there will be a checkmark or button to unload models before switching.

**Comment by Dekker3D** [comment]
Seems like c7c9f936d0fb1baee7c19776a0b93207ece023c9 probably fixed this?

**Comment by joemamafue** [comment]
> Seems like [c7c9f93](https://github.com/Mikubill/sd-webui-controlnet/commit/c7c9f936d0fb1baee7c19776a0b93207ece023c9) probably fixed this?

still having the issue at least with Midas model, but i think with others, too, it's just less obvious because they don't eat up that extra half a gig each time.

**Comment by hansolocambo** [comment]
Use extracted ControlNet Neural Networks instead. No need to change the model anymore. They're all in one and the file is less than 700MB. I tried many X/Y comparisons and results are perfectly identical.
https://civitai.com/models/9251/controlnet-pre-trained-models
or
https://civitai.com/models/9868/controlnet-pre-trained-difference-models

Put one of (or both) these files in ...\extensions\sd-webui-controlnet\models, and delete everything else (except .yaml)

**Comment by woodywood117** [comment]
I'm having this issue. I've updated to the commit as of this comment. Every time I change models and run a generation, I get a pretty large vram leak.
