### ISSUE TITLE
[Known Issue] A1111 trys to install trimesh[easy] at every startup

### ISSUE THREAD

**Issue by huchenlei** [Mikubill/sd-webui-controlnet#2401]
`trimesh[easy]` is introduced as dependency on hand refiner. However, current install script cannot correctly detects that the module has already been installed, so it will attempt to install it every time A1111 starts.

Sample console log:
```
Installing sd-webui-controlnet requirement: trimesh[easy]
```

**Comment by Flickarus** [comment]
same problem here, did anyone manage to solve it?
