### ISSUE TITLE
[Bug]: crop input image checkbox missing and false with default settings

### ISSUE THREAD

**Issue by strawberrymelonpanda** [Mikubill/sd-webui-controlnet#2414]
After fully updating, I was unable to see the new checkbox until I toggled to "inpaint not masked" and then back to "inpaint masked".  Might possibly be related to a stored default of Control Type: inpaint, but toggling control types didn't fix it.

Saving new defaults after toggling the mask mode and then checking the box (which was false) confirms that nothing else changed other than the new checkbox.

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/152940198/3ef26799-4ead-4db5-a2a4-62a647d88947)

_(Apologies for skipping the template, it has a lot of required info I don't have available. Just wanted to share what info I have.)_

**Comment by huchenlei** [comment]
The visibility is only controlled by 2 things:
- img2img tab selection
- inpaint area selection

Changing control type is expected to have no effect on visibility of the checkbox.

**Comment by strawberrymelonpanda** [comment]
However, all those being true (img2img tab, with an inpaint mask, and inpaint mask selected), it was still not visible until I toggled the mask type to "not masked" and then back to what it started as, which was "masked".  Then the new checkbox appeared, even though nothing had actually changed.

Prior to doing this, my inpainting results were very poor, which lead me here to debug.

**Comment by huchenlei** [comment]
Do you have your A1111 set the default img2img tab to inpaint and inpaint area to only masked?

The initial default value probably does not trigger the visibility control callback.

**Comment by strawberrymelonpanda** [comment]
I'm not sure if it's possible to set the tab to "inpaint" by default, but yes to the "only masked". 

> The initial default value probably does not trigger the visibility control callback.

That is what I'm thinking as well.  Just wanted to give a head's up in case it can be worked around, as until reading the related threads I had no indication of the new checkbox.

There's a similar issue (that may be an A1111 issue) where if you set controlnet to "enabled" by default, it won't actually appear or be enabled by default, even though the default settings believes that it is.  (Easy to confirm using a fixed seed.)

**Comment by huchenlei** [comment]
I cannot reproduce the issue even I have inpaint area default set to "Only masked". As long as you interact with the img2img tab selection, and click any tab among those 3 tabs, the checkbox does appear as expected in my local experiment.

![1704488385482](https://github.com/Mikubill/sd-webui-controlnet/assets/20929282/2e12c861-c52f-4df9-985e-da6b84073da4)

**Comment by huchenlei** [comment]
The might be a Gradio timing issue involved on when callbacks are executed. I am going to fix it real quick and you can try if the feature work now after the fix in #2416.

**Comment by strawberrymelonpanda** [comment]
> I cannot reproduce the issue

Understood, thanks for trying.  

I have been trying to find a way to reproduce it, but can't find a reliable way.  Through refreshing and going to img2img -> inpaint tab -> Controlnet accordion, I have gotten the checkbox to _not_ appear 4 times now.  

Most of the time however, it is successfully appearing.  I haven't been able to catch any useful console logs or find anything different with the times it has not appeared.  I'll give the new update in #2416 a try when it's available, but unfortunately I too lack a reliable test.

**Comment by huchenlei** [comment]
If it's flaky, probably the root cause is the gradio timing issue fixed in #2416. BTW #2416 has been merged now.

**Comment by strawberrymelonpanda** [comment]
Thanks, just updated.  Looks OK so far, and since we lack a more reliable test, I'll go ahead and mark this as closed.  Thanks for looking into it.
