### ISSUE TITLE
[Proposal] Make it easier to develop new preprocessors

### ISSUE THREAD

**Issue by huchenlei** [Mikubill/sd-webui-controlnet#2419]
Currently there are a bunch of code developer need to change in `global_states.py` and `processors.py` in order to add a new preprocessor. This can make development / sharing / customization of preprocessors hard.

What I am proposing here is to introduce an API that allows preprocessor to be self-contained modules like an A1111 extensions or ComfyUI custom nodes, that are easy to plug-in and remove. The API is ideally compatible with ComfyUI custom node implementation so that with minimal effort we can port the implementation from ComfyUI here.

These preprocessors should be hosted in their own repository and embed as submodules under `annotator/`.

**Comment by sdbds** [comment]
Very good idea! 
Also more and more preprocessors are using the unet architecture these days(like marigold), we should consider taking the part where diffusers read the config and generate the unet network and using it separately.

**Comment by celticsha** [comment]
I'm just trying to work out how to add a preprocessor myself. Is it worth waiting?

**Comment by huchenlei** [comment]
It will probably be a large refactoring that takes at least 1 ~ 2 weeks to implement and migrate.
