### ISSUE TITLE
[Bug] Invalid huggingface path for hand refiner for Windows user

### ISSUE THREAD

**Issue by AmidoriA** [Mikubill/sd-webui-controlnet#2423]
https://github.com/Mikubill/sd-webui-controlnet/blame/9d1f0a07fa2754338a6b260fad2abaf9d3f42ade/scripts/processor.py#L672

```python
os.path.join("hr16", "ControlNet-HandRefiner-pruned")
```

This will result as `hr16\ControlNet-HandRefiner-pruned` (backslash) for WIndows users. Which is the incorrect path.

**Comment by huchenlei** [comment]
problematic PR reverted.
