### ISSUE TITLE
hand refiener error since last update

### ISSUE THREAD

**Issue by kalle07** [Mikubill/sd-webui-controlnet#2427]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

error, i dont know what that error mean btw

### Steps to reproduce the problem

while start automatic1111  v1.7.0

### What should have happened?

-

### Commit where the problem happens

webui: 
controlnet: 

### Command Line Arguments

```Shell
-
```

### List of enabled extensions

FreeU 	https://github.com/ChenyangSi/FreeU 	main 	33e90be3 	2023-11-28 15:01:32 	unknown
Hypernetwork-MonkeyPatch-Extension 	https://github.com/aria1th/Hypernetwork-MonkeyPatch-Extension.git 	main 	0b28b3d1 	2023-08-28 15:35:26 	unknown
PBRemTools 	https://github.com/mattyamonaca/PBRemTools.git 	main 	91e16d32 	2023-08-01 12:08:11 	unknown
StyleSelectorXL 	https://github.com/ahgsql/StyleSelectorXL.git 	main 	5a093f5a 	2023-09-26 11:19:39 	unknown
adetailer 	https://github.com/Bing-su/adetailer 	main 	92692191 	2024-01-04 12:14:10 	unknown
https://github.com/vladmandic/sd-extension-system-info.git 	main 	f9348086 	2023-12-14 16:35:44 	unknown
sd-webui-additional-networks 	https://github.com/kohya-ss/sd-webui-additional-networks.git 	main 	e9f3d622 	2023-05-23 14:31:15 	unknown
sd-webui-aspect-ratio-helper 	https://github.com/thomasasfk/sd-webui-aspect-ratio-helper.git 	main 	99fcf9b0 	2023-06-04 17:39:07 	unknown
sd-webui-controlnet 	https://github.com/Mikubill/sd-webui-controlnet.git 	main 	94c93c67 	2024-01-06 18:27:32 	unknown
sd-webui-freeu 	https://github.com/ljleb/sd-webui-freeu 	main 	08a1734f 	2023-10-18 23:45:52 	unknown
sd-webui-inpaint-anything 	https://github.com/Uminosachi/sd-webui-inpaint-anything.git 	main 	a08995a7 	2023-10-18 04:31:34 	unknown
https://github.com/cheald/sd-webui-loractl.git 	master 	b48cf602 	2023-09-20 03:16:38 	unknown
sd-webui-openpose-editor 	https://github.com/huchenlei/sd-webui-openpose-editor.git 	main 	cebe13e0 	2023-12-19 04:58:26 	unknown
sd-webui-refiner 	https://github.com/wcde/sd-webui-refiner.git 	main 	0ad12e75 	2023-08-12 20:07:55 	unknown
https://github.com/continue-revolution/sd-webui-segment-anything.git 	master 	d80220ec 	2023-10-10 10:17:18 	unknown
sd-webui-supermerger 	https://github.com/hako-mikan/sd-webui-supermerger.git 	main 	f2be9fa8 	2023-12-17 01:24:50 	unknown
stable-diffusion-webui-rembg 	https://github.com/AUTOMATIC1111/stable-diffusion-webui-rembg.git 	master 	a4c07b85 	2023-12-30 14:04:03 	unknown

### Console logs

```Shell
*** Error running install.py for extension D:\stable-diffusion\webui\extensions\sd-webui-controlnet.
*** Command: "D:\stable-diffusion\system\python\python.exe" "D:\stable-diffusion\webui\extensions\sd-webui-controlnet\install.py"
*** Error code: 1
*** stdout: Command '['git', 'submodule', 'init']' returned non-zero exit status 1.
*** Warning: ControlNet failed to sync submodules. Please try run `git submodule init` and `git submodule update` manually.
***
*** stderr: D:\stable-diffusion\webui\extensions\sd-webui-controlnet\install.py:3: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
***   import pkg_resources
*** git: 'submodule' is not a git command. See 'git --help'.
*** Traceback (most recent call last):
***   File "D:\stable-diffusion\webui\extensions\sd-webui-controlnet\install.py", line 80, in <module>
***     install_requirements(hand_refiner_req_file)
***   File "D:\stable-diffusion\webui\extensions\sd-webui-controlnet\install.py", line 44, in install_requirements
***     with open(req_file) as file:
*** FileNotFoundError: [Errno 2] No such file or directory: 'D:\\stable-diffusion\\webui\\extensions\\sd-webui-controlnet\\annotator\\hand_refiner_portable\\requirements.txt'
```

**Comment by huchenlei** [comment]
Please reopen if issue persists. Thanks!
