### ISSUE TITLE
Separate Batch in ControlNet 💯 (for animations and more ?)

### ISSUE THREAD

**Issue by zhoobin021** [Mikubill/sd-webui-controlnet#243]
Batch In the ControlNet tab in both txt2img & img2img.

In txt2img, to have single prompt and have batch dir to input image sequences to be affected by the specified ControlNet.

In img2img, to have a single img in img2img sub-tab and apply the effect of that img on an image sequence batch ControlNet.
This can be in Inpainting too.

In img2img(Batch), to have each img in a dir of a img sequence be effected with each ControlNet batch.
Meaning that in img2img batch sub-tab put the dir of the image sequence in both img2img batch sub-tab and also in ControlNet batch, and then have each image run individually and have individual process.
e.g. 
image[0054] in img2img, and also image[0054] in ControlNet pose model and then output.
image[0055] in img2img, and also image[0055] in ControlNet pose model and then output.
image[0056] in img2img, and also image[0056] in ControlNet pose model and then output.
etc..

**Comment by marcsyp** [comment]
I'm blown away by the ControlNet implementation!  I came to this repo to make a few requests, and this was one of them.  My biggest challenge for batch processing at the moment is that the source image and the controlnet source need to be set individually and does not seem to be integrated with Automatic1111's Batch functionality, so this makes efficient batch processing very very painful.  

The simplest MVP solution to be instantly helpful is having the controlnet image have a toggle that says "use source image" that when checked, would reproduce the above scenario from zhoobin021.  It would simply always take the source image as input, and would in fact make img2img setup easier in general for many use cases, not just batch mode.  But this only cover's a simple "stylize" use case.

For more flexibility and control, a useful solution would add a directory field to point to controlnet images that would be used in the same order as the source batch directory, much like the inpaint mask directory.
e.g.,
{source directory}\sourceimage[0] in img2img, and {controlnet directory}\cnsourceimage[0] in ControlNet
{source directory}\sourceimage[1] in img2img, and {controlnet directory}\cnsourceimage[1] in ControlNet
{source directory}\sourceimage[2] in img2img, and {controlnet directory}\cnsourceimage[2] in ControlNet

Finally, I don't know if this is a related issue or not, but the gif2gif extension does not currently work with a gif loaded in ControlNet, but this would be a mindblowing update if it could be leveraged by the gif2gif developer to integrate.

Cheers.

**Comment by zhoobin021** [comment]
I found a video that has a way around it almost..
https://youtu.be/3FZuJdJGFfE

@7:14 he removes the images from both img2img and controlnet, and then do the batch.
I did this, it kinda works, but the style from img2img in contronet is not in effects on the output images!
However it's much clearer and has less flicker at the end on the image sequences.
I'm not sure if this is the effect on controlnet from just a single image or a batch tho.

**Comment by marcsyp** [comment]
I was able to execute controlnet batches using the method you linked above -- thank you!  I did see good controlnet influence on my batched images -- particularly after checking the "skip img2img" button in the ControlNet settings area.  A separate batch function will still be useful for allowing independent effects on source images via controlnet -- I believe this is a hot topic and I'd be surprised if it's not coming soon.  Cheers.

**Comment by ljleb** [comment]
One thing we need to take into consideration is multi-controlnet batch. To handle the controlnet batch feature, we could add a batch input directory field for each controlnet unit, and then let the user decide on a strategy to handle the case when the batch dirs sizes mismatch (i.e. when some batch dirs contain a different number of images):
- handle similarly to `zip` python function, i.e. "zip" together all batch dirs, and strip the resulting list to the length of the batch dir with the least number of images. generates n images, with n = number of images in the smallest batch dir
- multiplex batch dirs, i.e. for n given batch dirs, for each image in each batch dir, generate 1 image. generates `N1 * N2 * N3 *... * Nx` batch images, with x = number of batch dirs

I suggest these 3 subtabs for each controlnet unit as a way to not clutter the ui more than it is already while implementing this:
https://github.com/Mikubill/sd-webui-controlnet/issues/186#issuecomment-1435665154

**Comment by ljleb** [comment]
To illustrate what I had in mind for this feature:

## Upload ControlNet

![image](https://user-images.githubusercontent.com/32277961/221754409-45108bc7-a8cb-4c72-a2e3-97428688e1f0.png)

## Sketch ControlNet

![image](https://user-images.githubusercontent.com/32277961/221754466-4578e67f-0f43-4ebe-ae1a-39c68d2f7503.png)

## Batch ControlNet

![image](https://user-images.githubusercontent.com/32277961/221754511-c9f9416b-60a8-4ff3-8237-5a7757b82275.png)

**Comment by AbyszOne** [comment]
That structure looks efficient! Personally I think it would be better to change the title to Layer0, Layer1, etc. Not only is it very space saving and simpler, but it would be more intuitive when creating a folder structure for multi batches.
In addition to the parity option, which seems to me the most flexible but requires editing names, I propose a folder-parity combination.
Example:
Layer1/1-30/xxx.jpg, etc.
Layer1/65-80/xxx.jpg etc.
Where 1-30 is a subfolder that would activate frames 1-30, and then 65-80 would activate, and so on. This would allow you to throw images into each folder without worrying about the names, just the order and quantity.
Parity would come into play only in the internal order, not in the names. That is, if the third frame number sequence of a folder is skipped, the batch should also ignore it. 
Ex: random34.jpg, random35.jpg, random37.jpg
There the third frame of that folder (let say 80-100) is gonna be skipped. 
This would allow frames to be removed without disturbing overall coherence, nor the need for real parity between names other than the order of the frames within each subfolder.
I hope I wasn't confusing, I think it's quite a friendly and efficient method. Don't know if the best, ofc.

**Comment by enn-nafnlaus** [comment]
A caution about implementing batch: think about broad use cases.  Don't hyperfocus on just img2img.

For example, I use ControlNet with Prompt Travel.  If I specify a batch of images, it should use one image per output image in prompt travel.  Same with Shift Attention, Seed Travel, etc.  

The TL/DR is, every time SD generates an image, the ControlNet batch should increment to the next image on its list. Whether it's txt2img, img2img, etc, and no matter what called the image generation.

**Comment by marcsyp** [comment]
Hi all.  Any update on this feature set?  This is going to be amazing when it becomes available! 

Thanks.

**Comment by AbyszOne** [comment]
> Hi all. Any update on this feature set? This is going to be amazing when it becomes available!
> 
> Thanks.
A1111 not taking PRs for a while. Maybe there is some alternative. I asked on discussions whats happening with that delay, and they almost killed me.

**Comment by KEDI103** [comment]
> ## Batch ControlNet
> 
> ![image](https://user-images.githubusercontent.com/32277961/221754511-c9f9416b-60a8-4ff3-8237-5a7757b82275.png)

This I really need right now. I have been looking this for days. I got render from Source filmmaker img sequence with also depth rendered. And need to batch render in AI. I need give AI 2 different path for each different controlnet
1. For canny directly 3d render from sfm
![sakura_samurai_miku001839](https://user-images.githubusercontent.com/52115509/225785892-b342c922-5480-4ae4-81d9-cbdf3be1355e.png)
2. For depth render from sfm only depth
![sakura_samurai_miku001839_depth](https://user-images.githubusercontent.com/52115509/225785609-ec8322be-6d76-4d2c-81bf-6bec78b9a872.png)
but right now without this options it impossible I am stuck. Is this feature possible in future or is it released already or is it canceled?
I really need that. It fix my all problems. 
Also is it possible to batch 2 control net with 2 different path import for each control net with this conditions?

**Comment by enn-nafnlaus** [comment]
Lots of people need it.  We just have to hope someone picks up the ball on this.  :(  I know they're busy.

**Comment by AbyszOne** [comment]
> Lots of people need it. We just have to hope someone picks up the ball on this. :( I know they're busy.

Im lose about how the most powerful temporal coherence function is still being avoided so hard. Ive trying to push this to happen since controlnet release without success.

**Comment by enn-nafnlaus** [comment]
> > Lots of people need it. We just have to hope someone picks up the ball on this. :( I know they're busy.
> 
> Im lose about how the most powerful temporal coherence function is still being avoided so hard. Ive trying to push this to happen since controlnet release without success.

I keep getting better and better results with the Prompt Travel script combined custom scripts and ControlNet (though they keep accidentally breaking the Prompt Travel script with ControlNet changes so I can rarely run the latest version, lol   ;)  This isn't a criticism, I know how development is difficult, and the devs genuinely seem to care!).  But I can't take that next step and combine prompt travel with actual physical motion.  You can imagine what the effect would be like to have a moving scene, but the environment keeps slowly shifting around the subject(s)!

**Comment by AbyszOne** [comment]
> > > Lots of people need it. We just have to hope someone picks up the ball on this. :( I know they're busy.
> > 
> > 
> > Im lose about how the most powerful temporal coherence function is still being avoided so hard. Ive trying to push this to happen since controlnet release without success.
> 
> I keep getting better and better results with the Prompt Travel script combined custom scripts and ControlNet (though they keep accidentally breaking the Prompt Travel script with ControlNet changes so I can rarely run the latest version, lol ;) This isn't a criticism, I know how development is difficult, and the devs genuinely seem to care!). But I can't take that next step and combine prompt travel with actual physical motion. You can imagine what the effect would be like to have a moving scene, but the environment keeps slowly shifting around the subject(s)!

Check my new extension. Maybe can help you somewhat: https://github.com/AbyszOne/Abysz-LAB-Ext/

**Comment by enn-nafnlaus** [comment]
Interesting work, but it doesn't help me at all.

**Comment by 4lt3r3go** [comment]
is there a way to drop an image in img2img and same image will be automatically used by all controlNET tabs? 
without the need to drop the image also in there everytime

**Comment by ljleb** [comment]
I implemented a draft PR for this, see #683
