### ISSUE TITLE
Error while installing Controlnet

### ISSUE THREAD

**Issue by CagatayGit** [Mikubill/sd-webui-controlnet#2431]
Hello,
I tried to install Controlnet on A1111 but always error shows up " ValueError: Reference at 'HEAD' does not exist "
I tried to -restart my computer 
-reinstall A1111
-Install from url or install from directly A1111

But always i have same error.

Please anyone can help me?

**Comment by huchenlei** [comment]
This means you are in detached HEAD mode in git. You need to open git bash in ControlNet extension directory and execute "git checkout main" to set HEAD to branch"main".

**Comment by huchenlei** [comment]
If you still have issue, please reopen with more detailed reproduction steps. I just tried install the extension from a fresh A1111 checkout and it works fine.
