### ISSUE TITLE
[1.1.427] New preprocessor depth_hand_refiner

### ISSUE THREAD

**Issue by fireantsmore** [Mikubill/sd-webui-controlnet#2433]
### Discussed in https://github.com/Mikubill/sd-webui-controlnet/discussions/2400

<div type='discussions-op-text'>

<sup>Originally posted by **huchenlei** January  4, 2024</sup>
Thanks [Fannovel16](https://github.com/Fannovel16) for his hard work extracting dependencies out for [hand refiner](https://github.com/wenquanlu/HandRefiner) in https://github.com/Fannovel16/comfyui_controlnet_aux/.

Previously users need to use extensions like https://github.com/jexom/sd-webui-depth-lib to pick a matching hand gesture and move it to a correct location. `depth_hand_refiner` preprocess now does this job automatically for you.

# How to use
Now you can manually draw the inpaint mask on hands and use a depth ControlNet unit to fix hands with following steps:
## Step 1: Generate an image with bad hand.
![00009-603936670](https://github.com/Mikubill/sd-webui-controlnet/assets/20929282/5fb0c91e-df9d-45af-bc96-3a1659c6ad4b)

## Step 2: Switch to img2img inpaint. Draw inpaint mask on hands.
![1704329180304](https://github.com/Mikubill/sd-webui-controlnet/assets/20929282/bb821cf3-fb4b-4fa1-ba89-e709421291e6)

## Step 3: Enable ControlNet unit and select `depth_hand_refiner` preprocessor.
![1704329221720](https://github.com/Mikubill/sd-webui-controlnet/assets/20929282/2a26f16f-47ef-4c17-bd4b-d72c6746bb20)

## Step 4: Generate
![1704329401241](https://github.com/Mikubill/sd-webui-controlnet/assets/20929282/af72ba3a-3a87-4926-8397-7f48f8a77e0f)

# ADetailer usage example (https://github.com/Bing-su/adetailer/pull/460):
You need to wait for ADetailer author to merge that PR or checkout the PR manually. This section is independent of previous img2img inpaint example. Here the generation is txt2img.

## Image generated without ADetailer
![00019-3875947387](https://github.com/Bing-su/adetailer/assets/20929282/b1b4222f-7005-47e4-bc70-efe4f9f76a96)

## Image generated with ADetailer
![00020-3875947387adetailer](https://github.com/Bing-su/adetailer/assets/20929282/da2027fb-e825-4f59-8854-b1d4f9150f53)

## ADetailer setting
![1704335057409](https://github.com/Bing-su/adetailer/assets/20929282/d0802eec-3f4b-4c27-8450-d266d951d655)

Make sure you adjust denoising strength so that depth map can take control of hand rendering.

# Known issues
Hand refiner cannot handle complex hand gestures such as crossed fingers. Example: only 1 hand detected when finger are crossed:
![1704390318094](https://github.com/Mikubill/sd-webui-controlnet/assets/20929282/3097c33d-f0ec-43e0-83f2-05a33040a00d)
</div>

**Comment by huchenlei** [comment]
Why copy/repost the discussion thread here?
