### ISSUE TITLE
[Bug]: Can't launch the WebUI after installing extension

### ISSUE THREAD

**Issue by HUIZ-A** [Mikubill/sd-webui-controlnet#2438]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I put the sd-webui-controlnet in the extensions folder of SDWebUI, then the WebUI can't be launched, and there is no error provided in terminal. Once the extension is removed, the launching works again. 

I have checked if this error would happen when using another extension, but it didn't take place again,

### Steps to reproduce the problem

1. Download the code zip and unzip it in the extensions folder of A1111
2. Run python launch.py to launch the webui

### What should have happened?

Successfully launch the UI

### Commit where the problem happens

webui: works with other extensions
controlnet: 

### Command Line Arguments

```Shell
python launch.py --port 60000 --device-id 0
```

### List of enabled extensions

built-in

### Console logs

```Shell
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Python 3.10.6 (main, Oct 24 2022, 16:07:47) [GCC 11.2.0]
Version: 1.6.1
Commit hash: <none>
！！！It stucks here without any errors

It supposed to be:
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Python 3.10.6 (main, Oct 24 2022, 16:07:47) [GCC 11.2.0]
Version: 1.6.1
Commit hash: <none>
Launching Web UI with arguments: --port 60000 --device-id 0
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Loading weights [e6bb9ea85b] from /new_data/gehui/projects/stable-diffusion-webui-master/models/Stable-diffusion/sd_xl_base_1.0_0.9vae.safeten
sors
/new_data/xxx/projects/stable-diffusion-webui-master/extensions/stable-diffusion-webui-aesthetic-gradients-master/scripts/aesthetic.py:52: G
radioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row().style(equal_height=False):
Running on local URL:  http://127.0.0.1:60000

To create a public link, set `share=True` in `launch()`.
Unable to connect to VS Code server: Error in request.
Error: connect ECONNREFUSED /tmp/vscode-ipc-d068a8c3-d122-4623-9662-1d2799ee3476.sock
...
```

**Comment by huchenlei** [comment]
Please try update your a1111 to latest version (1.7) and see if problem persists.

**Comment by huchenlei** [comment]
Probably the issues is how you install the extension. If you install it in WebUI extension install panel, the git repository will be checked out, but if you download the zip file from github, it won't be a git repo. ControlNet git repo has a submodule on hand_refiner annotator, which require the extension running as a git repo.

However, the code handling sync of submodule is guarded by try-catch block, so any exceptions there should not block you from launching.

You can also try press `Enter` when commandline got stuck.
