### ISSUE TITLE
[Enhancement] Support region condition on each ControlNet unit

### ISSUE THREAD

**Issue by huchenlei** [Mikubill/sd-webui-controlnet#2451]
https://github.com/cubiq/ComfyUI_IPAdapter_plus has support for attn_mask on IP-Adapter to limit the prompt effect to a specific region in the generated image. It is similar to regional prompter, but for IP-Adapter embeddings.

In ControlNet, some models (canny, openpose) has pure black being empty space, i.e. no control will be applied to pure black regions. However, for other models (tile, depth), there is no way to specify the control region. Pure black region has its own semantics for these models.

We should build an integrated editor that allow easy edit of control regions, and use the mask from the editor to limit the region of control.

**Comment by huchenlei** [comment]
TODOs:
- [ ] Currently mask is only used by inpaint preprocessors. Need to find a way to make masking universal.
- [ ] Make sure masking works for HiRes. Fix.
- [ ] Support masking for ControlNet models
- [ ] Support masking for IP-Adapters

**Comment by mikedreambooth** [comment]
This is something I have thought about for a while but I don't know enough about the extension to contribute here! I had noticed if you use a higher weight on a canny control for example, certain models will generate images with little detail outside of the canny regions. So it's a trade of at the minute.

An option similar to the inpaint tab where you can choose to fill the masked region with original/latent noise/latent nothing could be useful here too?

**Comment by huchenlei** [comment]
Feature implemented in Issue solved in https://github.com/lllyasviel/stable-diffusion-webui-forge
