### ISSUE TITLE
[Bug]: PermissionError: [WinError 5] Access is denied:

### ISSUE THREAD

**Issue by Sorkan72** [Mikubill/sd-webui-controlnet#2452]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Trying to install ControlNet causes a strange access denied error. This seems to only happen for this extension.

### Steps to reproduce the problem

Attempting to install controlnet through the "available" or the "install from url" tabs in Automatic1111 webui.
"Available": "sd-webui-controlnet, manipulations"
"Install from url": installing through "https://github.com/Mikubill/sd-webui-controlnet.git"

### What should have happened?

"Installed into S:\stable-diffusion-webui\extensions\[extension]. Use Installed tab to restart." is what you should see. ControlNet should install properly.

### Commit where the problem happens

webui: Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e , Latest commit: cf2772f , Version: v1.7.0
controlnet: Commithash: 488b32e55f17bbbbae932f87c72818af6a110ca0, Latest commit: 488b32e

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No/Irrelevant
Tested with and without args
```

### List of enabled extensions

None/Built-in

### Console logs

```Shell
venv "C:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.7.0
Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e
Launching Web UI with arguments:
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Style database not found: C:\stable-diffusion-webui\styles.csv
Loading weights [6ce0161689] from C:\stable-diffusion-webui\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Creating model from config: C:\stable-diffusion-webui\configs\v1-inference.yaml
Startup time: 9.7s (prepare environment: 2.0s, import torch: 2.9s, import gradio: 1.0s, setup paths: 0.8s, initialize shared: 0.2s, other imports: 0.6s, setup codeformer: 0.1s, load scripts: 1.0s, create ui: 0.5s, gradio launch: 0.6s).
Applying attention optimization: Doggettx... done.
Model loaded in 4.0s (load weights from disk: 0.7s, create model: 0.3s, apply weights to model: 2.7s, calculate empty prompt: 0.1s).
*** Error completing request
*** Arguments: ('https://github.com/Mikubill/sd-webui-controlnet.git', ['ads', 'localization', 'installed'], 0, 'controlnet') {}
    Traceback (most recent call last):
      File "C:\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "C:\stable-diffusion-webui\modules\ui_extensions.py", line 399, in install_extension_from_index
        ext_table, message = install_extension_from_url(None, url)
      File "C:\stable-diffusion-webui\modules\ui_extensions.py", line 387, in install_extension_from_url
        raise err
      File "C:\stable-diffusion-webui\modules\ui_extensions.py", line 379, in install_extension_from_url
        os.rename(tmpdir, target_dir)
    PermissionError: [WinError 5] Access is denied: 'C:\\stable-diffusion-webui\\tmp\\sd-webui-controlnet' -> 'C:\\stable-diffusion-webui\\extensions\\sd-webui-controlnet'

---
```

### Additional information

Yes I am able to install other commonly used extensions without issues, such as: Adetailer, Civitai browser+, Ultimate SD upscaler.

Yes my permissions have been set accordingly. I only recently encountered this bug in the first place because I had to reinstall SD-webui, due to implementing more storage. However even when installing back into my original C: drive the same issue happens (can't install controlnet extension)

To clarify:
*I have full permissions/"full control".
*my user is the one and only admin/user.
*Tested with different folder owners.
*Read-only has been tested on, and off for the folder/subfolders
*Tested with "takeown /f "[folder]" /r /d y"

I genuinely don't know how to solve this problem. I have searched many many different forms to fix, burning hours". If there is a way to just manually install completely, please link to it. That or any true direct fix for this specific issue. Thank you

**Comment by huchenlei** [comment]
You can git bash in extensions directory and run "git clone https://github.com/Mikubill/sd-webui-controlnet" to manually download the extension.

**Comment by Sorkan72** [comment]
This works, thanks. Also no issues with dependencies.
