### ISSUE TITLE
ip adapter is not working in api mode of webui

### ISSUE THREAD

**Issue by HaozhouPang** [Mikubill/sd-webui-controlnet#2462]
when I use python api to call ip-adapter, it throws an Index error.

below is my payload info when using webui api,  the first onpenpose controlnet works well
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/16600283/1ffcaf53-5111-4a9e-bd32-b931b86867cb)
but the ip adapter throws the following error
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/16600283/1c605238-56c7-494f-81c2-6f30b27b2755)

Any help will be appreciated.

**Comment by huchenlei** [comment]
IP adapter accept clip as input. If you give it image and don't specify a preprocessor to convert it to clip, it throws this error.
