### ISSUE TITLE
Error whenever I try to use the new Hand Preprocessor, something about Protobuf

### ISSUE THREAD

**Issue by jpbarior** [Mikubill/sd-webui-controlnet#2467]
This error always shows when I try to use the hand preprocessor:

ImportError: cannot import name 'builder' from 'google.protobuf.internal' (C:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\google\protobuf\internal\__init__.py)

**Comment by sdbds** [comment]
update protobuf >=3.20.3
some deps auto use 3.19.6
