### ISSUE TITLE
[Bug]: No mask detected for ControlNet inpaint

### ISSUE THREAD

**Issue by vixenius** [Mikubill/sd-webui-controlnet#2475]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When using controlnet inpaint control type in txt2img im getting the following error, even though mask upload option is not checked. 

*** Error running process: D:\AINOVO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\AINOVO\stable-diffusion-webui\modules\scripts.py", line 718, in process
        script.process(p, *script_args)
      File "D:\AINOVO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1062, in process
        self.controlnet_hack(p)
      File "D:\AINOVO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1047, in controlnet_hack
        self.controlnet_main_entry(p)
      File "D:\AINOVO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 761, in controlnet_main_entry
        input_image, resize_mode = Script.choose_input_image(p, unit, idx)
      File "D:\AINOVO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 647, in choose_input_image
        raise ValueError("No mask detected for ControlNet inpaint")
    ValueError: No mask detected for ControlNet inpaint
    
    
    On the other hand, when i do enable mask upload option and drag and drop mask image, its working as intended, its seems that new mask upload option is expecting picture to be fed to it whether you use(check) the option or not.

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

ControlNet is expected to generate an image even when no mask image is provided.

### Commit where the problem happens

webui: 1.7.0
controlnet: v1.1.431

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
--xformers --autolaunch --api
```

### List of enabled extensions

![ext](https://github.com/Mikubill/sd-webui-controlnet/assets/11150079/414c673a-d789-4e4a-8690-b2aa637880dc)

### Console logs

```Shell
*** Error running process: D:\AINOVO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\AINOVO\stable-diffusion-webui\modules\scripts.py", line 718, in process
        script.process(p, *script_args)
      File "D:\AINOVO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1062, in process
        self.controlnet_hack(p)
      File "D:\AINOVO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1047, in controlnet_hack
        self.controlnet_main_entry(p)
      File "D:\AINOVO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 761, in controlnet_main_entry
        input_image, resize_mode = Script.choose_input_image(p, unit, idx)
      File "D:\AINOVO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 647, in choose_input_image
        raise ValueError("No mask detected for ControlNet inpaint")
    ValueError: No mask detected for ControlNet inpaint
```

**Comment by huchenlei** [comment]
Do you have hand drawn mask on txt2img controlnet input? Since you are using inpaint model, I expect you pass in the mask at least one way or the other.

**Comment by vixenius** [comment]
> Do you have hand drawn mask on txt2img controlnet input? Since you are using inpaint model, I expect you pass in the mask at least one way or the other.

No i just add the image i get from the internet to do a faceswap, its regular image, not a mask. It used to work, but now i get the error.

**Comment by huchenlei** [comment]
I mean did you draw on the image to specify the area that you want to inpaint?

**Comment by vixenius** [comment]
> I mean did you draw on the image to specify the area that you want to inpaint?

No sir, i did not. It's in txt2img.

**Comment by huchenlei** [comment]
Following is an example using inpaint model in txt2img:
ControlNet setup
![1705330761492](https://github.com/Mikubill/sd-webui-controlnet/assets/20929282/d5c4bed8-582b-4d76-ab2d-16e45591854b)
Prompt: Red hair
Output: 
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/20929282/4fdefb19-d304-456d-b55a-d6534ac30886)

**Comment by huchenlei** [comment]
If you use inpaint model without the mask, how does it swap the face?

**Comment by vixenius** [comment]
> If you use inpaint model without the mask, how does it swap the face?

With faceswaplab. Here's the screenshot.
![faceswap](https://github.com/Mikubill/sd-webui-controlnet/assets/11150079/2355925c-0991-4663-bf3d-61f47b27bb74)

**Comment by huchenlei** [comment]
In the case no mask is provided, ControlNet inpaint will keep the generated image exactly the same as input. Why don't you just run img2img with denoise strength = 0 + FaceSwapLab. It would be faster than invoking txt2img with ControlNet inpaint as well.
