### ISSUE TITLE
[DevTask] Port TencentARC/PhotoMaker

### ISSUE THREAD

**Issue by huchenlei** [Mikubill/sd-webui-controlnet#2478]
https://github.com/TencentARC/PhotoMaker released code. The mechanism is similar to ip-adapter with varitations on how input are preprocessed.

**Comment by 2blackbar** [comment]
Yeah but it accepts multiple images, which is something that IP adapters in auto11 controlnet should also accept and issue for that already exists but looks like nobody cares 

IMO this needs to finally be addressed cause we can only feed one image in controlned currently and that limits ipadapters useage cause they can accept multiple images at once in batch, 

In comfy thanks to feeding multiple images with batch we can create instant lora, i just give it my folder path and it takes all iamges from that path in comfy to send to ipadapter.
Something like this would be very nice in auto11

**Comment by huchenlei** [comment]
Multiple inputs to IP-Adapter has been fixed. See https://github.com/Mikubill/sd-webui-controlnet/discussions/2472

**Comment by 2blackbar** [comment]
Yes but that just 1 pic per controlnet which is not enough to do what comfyui does, the fix is appreciated tho cause i tried one pic per cnet and it wasnt working before , thanks.

**Comment by lhucklen** [comment]
Any word on support?

**Comment by hben35096** [comment]
https://github.com/InstantID/InstantID
This one has a similar function, and the results are amazing
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/139383150/5425bb28-3525-4b5f-8fa5-922d159684e5)
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/139383150/c45cf81f-7213-4975-a92d-f008aa835194)

**Comment by sdbds** [comment]
After test,
InstantID>ipadapter face IDv2>PhotoMaker
https://github.com/InstantID/InstantID

InstantID specially train a controlnetxl for using in here
https://huggingface.co/InstantX/InstantID

**Comment by hben35096** [comment]
> 经过测试，InstantID>ipadapter face IDv2>PhotoMaker

So, would you consider adding InstantID to ControlNet? :D

**Comment by haofanwang** [comment]
It would be very appreciated if you can add InstantID.

**Comment by anilken** [comment]
We would be grateful for support InstantID

**Comment by lhucklen** [comment]
I fourth this! I would like to try out both

**Comment by Paper99** [comment]
@huchenlei
https://twitter.com/PurzBeats/status/1751781133241421867

**Comment by EriIaz** [comment]
Is PhotoMaker implementation still being developed? 
I've got a tad better results with it and SDXL in Comfy as opposed to FaceID, assuming multiple references, and I can't run InstantID in A1111's UI at adequate speed because the current implementation only takes effect with a secondary ControlNet, which is insanely VRAM hungry.

**Comment by huchenlei** [comment]
Photomaker supported in https://github.com/lllyasviel/stable-diffusion-webui-forge

**Comment by mykeehu** [comment]
Any news for Auto1111?

**Comment by mykeehu** [comment]
Any news for Auto1111?
`AssertionError: ip-adapter-photomaker-v1-sdxl not found in ipadapter presets. Please try manually pick preprocessor.`
