### ISSUE TITLE
[Bug] （ MAC）Has created a picture of OPENPOSE but it still has not stop , other Preprocessors don't work  (OPENPOSE用好后产生了图片但是终端始终没有停止运行）

### ISSUE THREAD

**Issue by jingyenoting** [Mikubill/sd-webui-controlnet#2487]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Mac os (14.2.1 (23C71))

M2 chip , 16GB RAM 

The Automatic1111 ahs been uploaded to the latest ， WEB UI 已经是最新的了

Extensions :

<img width="1133" alt="截屏2024-01-16 21 18 38" src="https://github.com/Mikubill/sd-webui-controlnet/assets/145183948/3be6a1b9-970d-4f7e-b678-cf2da9e4a018">

( Has been tried every way that supported this problem but don't work ) 已经试过了所有方法了但仍然没法工作

Problem 1:

<img width="1086" alt="截屏2024-01-16 21 03 07" src="https://github.com/Mikubill/sd-webui-controlnet/assets/145183948/3ac2fb1a-305a-46e7-a496-e9357571c9d8">

<img width="567" alt="截屏2024-01-16 21 08 19" src="https://github.com/Mikubill/sd-webui-controlnet/assets/145183948/4201ef28-63d7-4b46-baac-a687d41d9cbd">

AS the picture upload，the terminal still don't stop after it has created a preview picture 
正如上面图片一样，产生了一张预览照片后，终端并没有停止指令，而是继续创作

Here is the what Terminal looks like :
这是终端运行界面：

<img width="567" alt="截屏2024-01-16 21 04 10" src="https://github.com/Mikubill/sd-webui-controlnet/assets/145183948/83644b8f-ca5c-4436-98d0-4f9257403efc">

Problem 2 : Other Preprocessors don't work : 
其他预处理器不工作

<img width="1133" alt="截屏2024-01-16 21 11 01" src="https://github.com/Mikubill/sd-webui-controlnet/assets/145183948/2bb2116b-a905-4487-9e9e-989ae813ca14">

<img width="1133" alt="截屏2024-01-16 21 12 05" src="https://github.com/Mikubill/sd-webui-controlnet/assets/145183948/00cbe689-4254-4848-8643-e9f2d413921d">

As the picture show the Preprocessor don't work after I wating for a long time , and the Terminal don't give me any response of how the Preprocessor going 
 
正如图片所示，这些预处理器已经运行了很长时间却仍热没有正常工作，终端也没有任何答复

### Steps to reproduce the problem

AS I Described upwards 

### What should have happened?

The preprocessor don't work .

### Commit where the problem happens

<img width="1133" alt="截屏2024-01-16 21 22 21" src="https://github.com/Mikubill/sd-webui-controlnet/assets/145183948/63690d7c-d829-469f-9bf4-5a8c56b2fdda">

https://github.com/Mikubill/sd-webui-controlnet

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
Mac OS 

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208
```

### List of enabled extensions

<img width="1133" alt="截屏2024-01-16 21 24 38" src="https://github.com/Mikubill/sd-webui-controlnet/assets/145183948/2a309987-7c19-4c18-9013-ad00b9d81556">

### Console logs

```Shell
Last login: Tue Jan 16 21:08:33 on ttys000
cd stable-diffusion-webui

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
..deMacBook-Air:~ yansun$ cd stable-diffusion-webui
..deMacBook-Air:stable-diffusion-webui yansun$ ./webui.sh

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye), Fedora 34+ and openSUSE Leap 15.4 or newer.
################################################################

################################################################
Running on yansun user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Python 3.10.13 (main, Aug 24 2023, 12:59:26) [Clang 15.0.0 (clang-1500.0.40.1)]
Version: v1.7.0
Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e
ControlNet init warning: Unable to install insightface automatically. Please try run `pip install insightface` manually.
Launching Web UI with arguments: --skip-torch-cuda-test --upcast-sampling --no-half-vae --use-cpu interrogate
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Style database not found: /Users/../stable-diffusion-webui/styles.csv
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
ControlNet preprocessor location: /Users/../stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
2024-01-16 21:08:39,904 - ControlNet - INFO - ControlNet v1.1.431
2024-01-16 21:08:39,951 - ControlNet - INFO - ControlNet v1.1.431
Loading weights [43c75e6831] from /Users/../stable-diffusion-webui/models/Stable-diffusion/kohakuXLBeta_beta7.safetensors
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Creating model from config: /Users/../stable-diffusion-webui/repositories/generative-models/configs/inference/sd_xl_base.yaml
Startup time: 5.6s (prepare environment: 0.8s, import torch: 1.5s, import gradio: 0.6s, setup paths: 0.6s, other imports: 0.6s, load scripts: 0.4s, create ui: 0.4s, gradio launch: 0.5s).
Applying attention optimization: sub-quadratic... done.
Model loaded in 79.9s (load weights from disk: 1.0s, create model: 0.7s, apply weights to model: 76.6s, apply dtype to VAE: 0.2s, move model to device: 0.2s, hijack: 0.1s, calculate empty prompt: 0.9s).
```

**Comment by huchenlei** [comment]
Did your setup work before? Or this is the first time install?

Also, if you do not preview the preprocessor result, directly hit generate, does the generation get stuck as well?

**Comment by jingyenoting** [comment]
> Did your setup work before? Or this is the first time install?
> 
> Also, if you do not preview the preprocessor result, directly hit generate, does the generation get stuck as well?

I have set up work in control net V-1, https://github.com/lllyasviel/webui-controlnet-v1-archived it works well

Yea it well still get stuck

**Comment by jingyenoting** [comment]
some new bug right here : I have looked the issue before but it didn't work:

<img width="1709" alt="截屏2024-01-17 01 31 58" src="https://github.com/Mikubill/sd-webui-controlnet/assets/145183948/3148b2f3-a619-4a4d-b20f-a324885aef93">

**Comment by jingyenoting** [comment]
![Uploading 截屏2024-01-17 01.35.10.png…]()

**Comment by jingyenoting** [comment]
<img width="1709" alt="截屏2024-01-17 01 35 10" src="https://github.com/Mikubill/sd-webui-controlnet/assets/145183948/3051a5f7-7429-4dcc-a9ca-cc85ca11d129">
