### ISSUE TITLE
[Bug]: FileNotFoundError: [WinError 3] The system cannot find the specified path: ''

### ISSUE THREAD

**Issue by demirklvc** [Mikubill/sd-webui-controlnet#2489]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

[Bug]: File not found when trying to use Batch.

Im using an older commit of Auto1111 and i cant use control net Batch with the reference+adapter. it always gives me the file/path not found error. what are my options? does the newest version of this extension run on older commits of auto? or is it possible to install a certain commit of yours where this bug was fixed? please help me. i dont want to update my whole auto1111

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...
.

### What should have happened?

..

### Commit where the problem happens

webui: 
controlnet: 
python: 3.10.6  •  torch: 1.12.1+cu113  •  xformers: N/A  •  gradio: 3.16.2  •  commit: a9fed7c3  •  

### Command Line Arguments

```Shell
..
```

### List of enabled extensions

.

### Console logs

```Shell
.FileNotFoundError: [WinError 3] The system cannot find the specified path: ''
```

### Additional information

.

**Comment by huchenlei** [comment]
Which version of A1111 do you use?

**Comment by demirklvc** [comment]
this the info you need?

**Comment by huchenlei** [comment]
The version is probably too old. We do development based on most recent A1111 stable version. You need update your A1111 or just an older version of ControlNet extension.

https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/a9fed7c364061ae6efb37f797b6b522cb3cf7aa2
[AUTOMATIC1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commits?author=AUTOMATIC1111) committed on Mar 14, 2023
