### ISSUE TITLE
[Bug]: Checkbox invisible "Crop Input image with A1111 mask“

### ISSUE THREAD

**Issue by mlsnr** [Mikubill/sd-webui-controlnet#2492]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Hi, I’m trying to use inpaint with “masked only” while using a custom CN image for ipadapter. 

Seems like there’s supposed to be a checkbox for disabling the automatic cropping that occurs on the CN image according to the masked region.
However, this checkbox does not appear in my webui, even though I’ve updated the extension.

I have already read all the threads I could find on this issue which seems to have been common in December.

I’d be more than grateful for help on this, as it would greatly improve my workflow. Thanks!

### Steps to reproduce the problem

Inpaint “masked only” while using a custom CN image for ipadapter. 

### What should have happened?

Visible checkbox

### Commit where the problem happens

webui: 1.6.0
controlnet: Latest

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### List of enabled extensions

Disabled all but Controlnet

### Console logs

```Shell
None
```

**Comment by huchenlei** [comment]
Try update your a1111 to 1.7.0? I have not tested if the checkbox work in 1.6.0 so a1111 version might be the cause.

**Comment by mlsnr** [comment]
> Try update your a1111 to 1.7.0? I have not tested if the checkbox work in 1.6.0 so a1111 version might be the cause.

That worked! Thanks and sorry - I should have figured that out myself🙏

**Comment by huchenlei** [comment]
I will try to make it compatible with A1111 version < 1.7.0 later. The checkbox probably should just be always visible for previous versions as some A1111 components either just don't exist or have different name.

**Comment by huchenlei** [comment]
Well, it does not seem to be easy to access A1111 version in the extension script. I will reconsider this if more users are reporting the issue.
