### ISSUE TITLE
[DevTask] Allow users specify low_vram for preprocessor

### ISSUE THREAD

**Issue by huchenlei** [Mikubill/sd-webui-controlnet#2497]
Currently, low_vram checkbox does not control where preprocessor models will be load to. So for some expensive preprocessor models such as CLIP, it might be problematic to keep preprocessor models in VRAM for users with limited VRAM.

The original issue was raised here:
https://github.com/Mikubill/sd-webui-controlnet/discussions/2472#discussioncomment-8156201

**Comment by theSha1do1w** [comment]
Has this already been resolved in this [PR](https://github.com/Mikubill/sd-webui-controlnet/pull/2495)?
