### ISSUE TITLE
Hand Pose Estimation

### ISSUE THREAD

**Issue by edgartaor** [Mikubill/sd-webui-controlnet#25]
Is possible to include this model to generate images with good hands?

I think [is already part of ControlNet](https://huggingface.co/lllyasviel/ControlNet/blob/main/annotator/ckpts/hand_pose_model.pth), but it does not create a hand pose estimation in my experiments with this extension.

If anyone have more info, please comment.
https://github.com/CMU-Perceptual-Computing-Lab/openpose
![image](https://user-images.githubusercontent.com/430438/218670494-4a71238c-9f2b-4328-b5a2-1f0ff3dd2ba2.png)

https://github.com/Hzzone/pytorch-openpose#hand-pose-estimation
![image](https://user-images.githubusercontent.com/430438/218669465-be8e6c69-d169-48eb-8086-2955cf7c0269.png)

![image](https://user-images.githubusercontent.com/430438/218668799-aa1d88bf-6c66-4b8b-8b9d-0234d2d62e06.png)

**Comment by Mikubill** [comment]
Hand Pose Estimation is disabled by default, you may need to enable it manually.
https://github.com/Mikubill/sd-webui-controlnet/blob/fca33937af7bf45dac94616531643ce228c88d6b/scripts/processor.py#L69
(Maybe we should add a setting tab to configure such things)

**Comment by trihardseven** [comment]
A toggle for it on the UI would be ideal, this is crazy good for assisting the AI with hands.

**Comment by toyxyz** [comment]
However, it may not work if pos2model is trained with openpose images without hands.

**Comment by matsuvr** [comment]
Put those .pth files to annotetor/ckpts/ , and hand detection will work.
https://huggingface.co/lllyasviel/ControlNet/tree/main/annotator/ckpts
<img width="324" alt="image" src="https://user-images.githubusercontent.com/32435004/218769218-bda36c85-cbfb-4845-b492-e2ef262120a5.png">

**Comment by toyxyz** [comment]
Quick test!
![image](https://user-images.githubusercontent.com/8006000/218774103-84a26639-bbde-40b7-b61b-70c8aa42fa3d.png)

**Comment by YukiSakuma** [comment]
Don't know if I did the right thing but I downloaded the `hand_pose_model.pth` put it in the annotator folder, then chose the `openpose_hand` preprocessor then used `control_any3_openpose `model

![test](https://user-images.githubusercontent.com/16185735/218808511-3f041e90-55c6-48a9-9225-9652fb4c4aaf.PNG)

**Comment by 2blackbar** [comment]
> Quick test! ![image](https://user-images.githubusercontent.com/8006000/218774103-84a26639-bbde-40b7-b61b-70c8aa42fa3d.png) ![image](https://user-images.githubusercontent.com/8006000/218816185-b27de12c-4e31-47e3-9920-812988888ea5.png)

looks like hand model doesnt work and makes it worse

**Comment by trihardseven** [comment]
I guess the models need to be retrained with hands in mind

**Comment by flufy3d** [comment]
> Put those .pth files to annotetor/ckpts/ , and hand detection will work. https://huggingface.co/lllyasviel/ControlNet/tree/main/annotator/ckpts <img alt="image" width="324" src="https://user-images.githubusercontent.com/32435004/218769218-bda36c85-cbfb-4845-b492-e2ef262120a5.png">

not good
