### ISSUE TITLE
[Feature request]: Crop the same region on after annotation that masked inpainting does, when no image is provided

### ISSUE THREAD

**Issue by MalOMaw** [Mikubill/sd-webui-controlnet#250]
Currently it makes no sense to use ControlNet while inpainting in "masked only" mode, which severly limits detailing capabilities that controlnet would otherwise provide. It only makes sense to inpaint in whole image mode. By default, if you don't provide an image, it uses the source image. It is great for simple img2img or inpainting the whole image, but not for masked inpainting in only masked mode.

**Comment by MalOMaw** [comment]
I was researching around it, Automatic's WebUI currently does not expose the cropped version to outside extensions, as far as I understood the code. Anybody thinks it's a good idea to request it on auto's repo?

**Comment by Mikubill** [comment]
fixed in https://github.com/Mikubill/sd-webui-controlnet/commit/da7a3609e1011b7a2a1f020b77cb630743d11b2f

**Comment by MalOMaw** [comment]
Just works
