### ISSUE TITLE
'HandRefinerPortableHandRefinerPortable' Error with A111 and Latest Version ControlNet

### ISSUE THREAD

**Issue by masacimace** [Mikubill/sd-webui-controlnet#2501]
latest version Controlnet give this error '**HandRefinerPortable**'

Couldn't install sd-webui-controlnet requirement: handrefinerportable@git+https://github.com/huchenlei/HandRefinerPortable.git.
Command: "D:\Z-DIFUSION\system\python\python.exe" -m pip install handrefinerportable@git+https://github.com/huchenlei/HandRefinerPortable.git --prefer-binary
Error code: 1
stdout: Collecting handrefinerportable@ git+https://github.com/huchenlei/HandRefinerPortable.git
  Cloning https://github.com/huchenlei/HandRefinerPortable.git to c:\users\mistik\appdata\local\temp\pip-install-2qy54u7s\handrefinerportable_9009365d2f87410d8880d046497a8755
  Resolved https://github.com/huchenlei/HandRefinerPortable.git to commit d9c5506a1c13b396499dfdbaada9b7650e5d6d65
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

stderr:   Running command git clone --filter=blob:none --quiet https://github.com/huchenlei/HandRefinerPortable.git 'C:\Users\Mistik\AppData\Local\Temp\pip-install-2qy54u7s\handrefinerportable_9009365d2f87410d8880d046497a8755'
  error: subprocess-exited-with-error

  Getting requirements to build wheel did not run successfully.
  exit code: 1

**Comment by DavideAlidosi** [comment]
Same here.

**Comment by wwei0819** [comment]
Same here +1
