### ISSUE TITLE
[Bug]: After changing the checkpoint, processor is reset and saved preview is removed

### ISSUE THREAD

**Issue by CurtisDS** [Mikubill/sd-webui-controlnet#2520]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When you change the active checkpoint model while you are using Control net, once the new model loads, Control Net resets the selected processors and removes any existing previews.

### Steps to reproduce the problem

1. Enable a control net
2. Add a source image
3. Enable preview
4. Change Processor to "lineart_anime" (anything that isn't the default for the type)
5. Generate the preview
6. Change Checkpoints

![control net bug](https://github.com/Mikubill/sd-webui-controlnet/assets/20732674/05f1f70c-04aa-4cfa-853e-2835c4d210a6)

### What should have happened?

The selected processor and preview should not be reset when you change checkpoints.

### Commit where the problem happens

webui: cf2772fab0af5573da775e7437e6acdca424f26e
controlnet: fb9320150129eb4ca5c58bd74ac28e75102a0c5b

### Command Line Arguments

```Shell
--xformers
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/20732674/4520d062-54d5-4f22-9f0e-e042daee56ec)

### Console logs

```Shell
Nothing in the log
```

### Additional information

This was not an issue in commit: c1f3d6f8505074d73b13eaf67f331bf869d7b940

**Comment by Vitoqqqs** [comment]
I also got many problems with control net today. It does not select preprocessor and model automatically in **text to img**, like it did before, and in **img to img** it simply refuses to input an image, when i click "Upload independent control image"

**Comment by huchenlei** [comment]
> I also got many problems with control net today. It does not select preprocessor and model automatically in **text to img**, like it did before, and in **img to img** it simply refuses to input an image, when i click "Upload independent control image"

Update your A1111 to 1.7.0 or update ControlNet after this PR(https://github.com/Mikubill/sd-webui-controlnet/pull/2518).

**Comment by Vitoqqqs** [comment]
> Update your A1111 to 1.7.0 or update ControlNet after this PR(#2518).
Thanks
