### ISSUE TITLE
[Bug] After calling the api, all pictures affected by the controlnet

### ISSUE THREAD

**Issue by Oyaxira** [Mikubill/sd-webui-controlnet#254]
After I call controlnet/txt2img and pass the initial image,
when i request sdapi/v1/txt2img, the generated picture is obviously affected by the last picture sent to controlnet/txt2img

I try to read the source code of webui api and this project api but can't understand.
Judging from the log, the parameters passed into the interface are correct.
script_args is also an empty array in the processing flow of sdapi/v1/txt2img

**Comment by Mikubill** [comment]
Could you share some log/reproduce steps/screenshots?

**Comment by Oyaxira** [comment]
![result](https://user-images.githubusercontent.com/18203308/220322170-037981f4-169a-41b1-877a-2a27dd2ab43f.png)

source
1.jpg
2.jpg

**Comment by Mikubill** [comment]
Fixed in https://github.com/Mikubill/sd-webui-controlnet/pull/278

**Comment by Oyaxira** [comment]
The problem has been solved, thank you very much!
