### ISSUE TITLE
 Issue with Weighting in sd15_face_id_portrait

### ISSUE THREAD

**Issue by hben35096** [Mikubill/sd-webui-controlnet#2540]
It seems there is an issue with the weighting of the sd15_face_id_portrait model. It appears that the weights are being accumulated based on the number of images.

### Test 1:
Inputting 1 image with a weight of 0.5 yields a relatively normal result.
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/139383150/d7b25f35-7ea3-4271-b9b4-f571af7ff471)

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/139383150/41a433f5-68a8-4f11-963a-a065bbab0196)

### Test 2:
Inputting 4 images with a weight of 0.5 produces disturbing results.

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/139383150/b40e8f84-e220-41f5-bbfc-469da1dcd006)

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/139383150/9eb917ea-50ba-447f-8c56-f590c2b9ef20)

### Test 3:
Inputting 4 images with a weight adjusted to 0.5 divided by 4, approximately 0.12, yields a relatively normal result again.

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/139383150/3b886779-6b0b-4788-8fc0-1dc13f5a9abb)

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/139383150/cf688c05-f8a0-4f46-b913-b336b57756dd)

### Test 4:
Inputting 6 images with a weight of 0.5 produces disturbing results.

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/139383150/18de860c-4588-4e25-863f-69964b0a2cab)

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/139383150/1ef06c8f-6d67-4fd4-9fb0-96388eecac0f)

**Comment by huchenlei** [comment]
![1705904623739](https://github.com/Mikubill/sd-webui-controlnet/assets/20929282/7a6d909a-184b-454f-8f90-9a7fd919490f)

**Comment by hben35096** [comment]
Thank you for your attention to this issue :)
