### ISSUE TITLE
ip-adapters doesn't work. torch.cuda.FloatTensor

### ISSUE THREAD

**Issue by mikheys** [Mikubill/sd-webui-controlnet#2558]
Hello. Today ip-adapters stopped working. I tried uninstalling CN completely and installing it again. I tried uninstalling venv A1111. What can it be?
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/34010273/2064ac82-8bcf-4eba-a9f8-5c137a6d3395)

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/34010273/4694c283-31d7-45b5-a644-50c685b2be7e)

**Comment by huchenlei** [comment]
Successfully reproduced.

**Comment by huchenlei** [comment]
Might be caused by https://github.com/Mikubill/sd-webui-controlnet/pull/2556.

**Comment by Mozoloa** [comment]
I was literally searching for people having the same problem, this also happens to me with ip adapter face id v2, just generating the preview fails
