### ISSUE TITLE
[Bug]: AttributeError: 'StableDiffusionProcessingTxt2Img' object has no attribute 'rng' while using Controlnet inpaint_only+lama preprocessor

### ISSUE THREAD

**Issue by marchcat69** [Mikubill/sd-webui-controlnet#2576]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When I use the preprocessor inpaint_only+lama in Controlnet I get an error message in the console: "AttributeError: 'StableDiffusionProcessingTxt2Img' object has no attribute 'rng'". But the inpaint completes normally with expected results. This appeared after updating Controlnet to version 1.1.436. I returned to version 1.1.419, but the error persisted. Why does this error occur and how to get rid of it? I use WebUI v1.5.2 and I can't update it to later versions (1.6 or 1.7). Other functions I need do not work in them.

### Steps to reproduce the problem

1. Put image in Controlnet window and paint some area
2. Select preprocessor inpaint_only+lama and corresponding inpainting model
3. Press "Generate"

### What should have happened?

The error should not appear in the console.

### Commit where the problem happens

webui: v.1.5.2
controlnet: v1.1.419 and later

### Command Line Arguments

```Shell
"--opt-sdp-no-mem-attention --no-half-vae --upcast-sampling --no-hashing --medvram --always-batch-cond-uncond"
```

### List of enabled extensions

sd-webui-controlnet	https://github.com/Mikubill/sd-webui-controlnet.git	tmp	[aa4747ab](https://github.com/Mikubill/sd-webui-controlnet/commit/aa4747ab5f949b5d7aa1ccae238571ddca6ef33f)	Tue Nov 21
sd-webui-inpaint-anything	https://github.com/Uminosachi/sd-webui-inpaint-anything.git	main	[a08995a7](https://github.com/Uminosachi/sd-webui-inpaint-anything/commit/a08995a7d251c9088d6e359a4093044d75b23605)
sd-webui-openpose-editor	https://github.com/huchenlei/sd-webui-openpose-editor.git	main	[cebe13e0](https://github.com/huchenlei/sd-webui-openpose-editor/commit/cebe13e092fa3c5d810f4afbd7a45987ba8275d0)

### Console logs

```Shell
2024-01-24 19:44:09,243 - ControlNet - INFO - Loading model from cache: control_v11p_sd15_inpaint [ebff9138]████████████████████████████████████| 20/20 [00:26<00:00,  1.02s/it]
2024-01-24 19:44:09,244 - ControlNet - INFO - using inpaint as input
2024-01-24 19:44:09,250 - ControlNet - INFO - Loading preprocessor: inpaint_only+lama
2024-01-24 19:44:09,339 - ControlNet - INFO - preprocessor resolution = 768
2024-01-24 19:44:12,797 - ControlNet - INFO - ControlNet used torch.float32 VAE to encode torch.Size([1, 4, 96, 128]).
2024-01-24 19:44:12,812 - ControlNet - INFO - ControlNet Hooked - Time = 3.5691351890563965
*** Error running before_process_batch: /root/1data/apps/local/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "/root/1data/apps/local/stable-diffusion-webui/modules/scripts.py", line 527, in before_process_batch
        script.before_process_batch(p, *script_args, **kwargs)
      File "/root/1data/apps/local/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 998, in before_process_batch
        p.rng = HackedImageRNG(rng=p.rng,
                                   ^^^^^
    AttributeError: 'StableDiffusionProcessingTxt2Img' object has no attribute 'rng'

---
```

**Comment by fu-jianhua** [comment]
Hello, I have also encountered this problem. Have you resolved it

**Comment by marchcat69** [comment]
> Hello, I have also encountered this problem. Have you resolved it

Finally I updated Webui to v1.7.0. Now I don't get this error. The issues I previously encountered with Webui v1.7.0 have also been resolved.
