### ISSUE TITLE
[Bug]: ip-adapter-faceid-portrait_sd15 doesn't work on docker.

### ISSUE THREAD

**Issue by adeng-wc** [Mikubill/sd-webui-controlnet#2581]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

ip-adapter-faceid-portrait_sd15 doesn't work on docker.

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

ip-adapter-faceid-portrait_sd15 doesn't work on docker.

### Commit where the problem happens

webui: 
controlnet: 1.1.438
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/12425576/92974bde-7ffb-473f-9906-a98ade8e3660)

### Command Line Arguments

```Shell
bash ./webui.sh  --listen --api --xformers --enable-insecure-extension-access
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/12425576/0821084b-5d51-4e8a-9ab2-d57d829e858f)

### Console logs

```Shell
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/12425576/842e61c6-fc7f-41be-b918-aa60020d8137)
```

### Additional information

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/12425576/7a2b2e19-2553-4e1d-9cf2-b80a6f34c87d)

**Comment by adeng-wc** [comment]
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/12425576/842e61c6-fc7f-41be-b918-aa60020d8137)

**Comment by adeng-wc** [comment]
I don't know much about `touch.cat()`. Please help me. @huchenlei

**Comment by huchenlei** [comment]
I have reverted #2583, which introduced the code in stacktrace. Can you share your input image so that I can try to reproduce it locally?

**Comment by adeng-wc** [comment]
> I have reverted #2583, which introduced the code in stacktrace. Can you share your input image so that I can try to reproduce it locally?

Sorry, the photo owner is not allowed to provide it.

**Comment by adeng-wc** [comment]
the problem still exists.

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/12425576/3bdcc093-4183-45d0-b30f-31b641abceb8)

**Comment by adeng-wc** [comment]
I do not know why？“Insightface: No face found in image 0” 

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/12425576/2516b934-7921-489c-9e5d-1b86477aa140)

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/12425576/e6439a40-97a2-414f-bfe1-7dc5bd0fc5df)

**Comment by adeng-wc** [comment]
I found that Insightface could not recognize the close-up photo of the face.

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/12425576/f53c1079-0742-4714-923b-4567fbe7a703)

This photo can be used to identify faces.
