### ISSUE TITLE
[Bug]:  "Send Dimensions to Stable Diffusion" Icon is not working in the TXT2IMG tab at the moment (works in IMG2IMG)

### ISSUE THREAD

**Issue by CCpt5** [Mikubill/sd-webui-controlnet#2587]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

The little up icon that usually changes the TXT2IMG (or IMG2IMG) resolution to match the image in the controlnet window is not functioning (for me) at the moment in the TXT2IMG tab. It is working in IMG2IMG. 

### Steps to reproduce the problem

1. TXT2IMG tab
2. Load image in Controlnet
3. Click "Send Dimensions to Stable Diffusion" icon
4. Notice no change in resolution settings above

### What should have happened?

Clicking that icon should change the resolution to match the image in Controlnet.

### Commit where the problem happens

webui: 1.7
controlnet: e081a3a0

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
{
    "Platform": "Windows-10-10.0.19045-SP0",
    "Python": "3.10.6",
    "Version": "v1.7.0",
    "Commit": "cf2772fab0af5573da775e7437e6acdca424f26e",
    "Script path": "D:\\stable-diffusion-webui",
    "Data path": "D:\\stable-diffusion-webui",
    "Extensions dir": "D:\\stable-diffusion-webui\\extensions",
    "Checksum": "2f6a801742d050e30f53d7fe6e0543d0b1622a22b36eaf8920d585db3dd04a6c",
    "Commandline": [
        "launch.py",
        "--opt-sdp-attention",
        "--no-half-vae",
        "--opt-channelslast",
        "--disable-safe-unpickle",
        "--skip-torch-cuda-test",
        "--disable-nan-check",
        "--skip-version-check",
        "--ckpt-dir",
        "e:\\stable Diffusion Checkpoints"
    ],
    "Torch env info": {
        "torch_version": "2.1.2+cu121",
        "is_debug_build": "False",
        "cuda_compiled_version": "12.1",
        "gcc_version": null,
        "clang_version": null,
        "cmake_version": null,
        "os": "Microsoft Windows 10 Pro",
        "libc_version": "N/A",
        "python_version": "3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] (64-bit runtime)",
        "python_platform": "Windows-10-10.0.19045-SP0",
        "is_cuda_available": "True",
        "cuda_runtime_version": null,
        "cuda_module_loading": "LAZY",
        "nvidia_driver_version": "546.29",
        "nvidia_gpu_models": "GPU 0: NVIDIA GeForce RTX 4090",
        "cudnn_version": null,
        "pip_version": "pip3",
        "pip_packages": [
            "numpy==1.23.5",
            "open-clip-torch==2.20.0",
            "pytorch-lightning==1.9.4",
            "torch==2.1.2+cu121",
            "torchdiffeq==0.2.3",
            "torchmetrics==1.2.1",
            "torchsde==0.2.6",
            "torchvision==0.16.2+cu121"
        ],
        "conda_packages": null,
        "hip_compiled_version": "N/A",
        "hip_runtime_version": "N/A",
        "miopen_runtime_version": "N/A",
        "caching_allocator_config": "",
        "is_xnnpack_available": "True",
        "cpu_info": [
            "Architecture=9",
            "CurrentClockSpeed=3200",
            "DeviceID=CPU0",
            "Family=207",
            "L2CacheSize=16384",
            "L2CacheSpeed=",
            "Manufacturer=GenuineIntel",
            "MaxClockSpeed=3200",
            "Name=Intel(R) Core(TM) i9-14900K",
            "ProcessorType=3",
            "Revision="
        ]
    },
    "Exceptions": [],
    "CPU": {
        "model": "Intel64 Family 6 Model 183 Stepping 1, GenuineIntel",
        "count logical": 32,
        "count physical": 24
    },
    "RAM": {
        "total": "64GB",
        "used": "17GB",
        "free": "46GB"
```

### List of enabled extensions

    },
    "Extensions": [
        {
            "name": "3sd-webui-controlnet",
            "path": "D:\\stable-diffusion-webui\\extensions\\3sd-webui-controlnet",
            "version": "e081a3a0",
            "branch": "main",
            "remote": "https://github.com/Mikubill/sd-webui-controlnet.git"
        },
        {
            "name": "Styles-Editor",
            "path": "D:\\stable-diffusion-webui\\extensions\\Styles-Editor",
            "version": "025f17f7",
            "branch": "main",
            "remote": "https://github.com/chrisgoringe/Styles-Editor.git"
        },
        {
            "name": "a2-adetailer",
            "path": "D:\\stable-diffusion-webui\\extensions\\a2-adetailer",
            "version": "a0b4c56e",
            "branch": "main",
            "remote": "https://github.com/Bing-su/adetailer.git"
        },
        {
            "name": "b1111-sd-webui-tagcomplete",
            "path": "D:\\stable-diffusion-webui\\extensions\\b1111-sd-webui-tagcomplete",
            "version": "c659ed21",
            "branch": "main",
            "remote": "https://github.com/DominikDoom/a1111-sd-webui-tagcomplete.git"
        },
        {
            "name": "extension-style-vars",
            "path": "D:\\stable-diffusion-webui\\extensions\\extension-style-vars",
            "version": "92976f1e",
            "branch": "master",
            "remote": "https://github.com/SirVeggie/extension-style-vars"
        },
        {
            "name": "sd-Img2img-batch-interrogator",
            "path": "D:\\stable-diffusion-webui\\extensions\\sd-Img2img-batch-interrogator",
            "version": "7f4e4eb0",
            "branch": "main",
            "remote": "https://github.com/Alvi-alvarez/sd-Img2img-batch-interrogator.git"
        },
        {
            "name": "sd-dynamic-prompts",
            "path": "D:\\stable-diffusion-webui\\extensions\\sd-dynamic-prompts",
            "version": "284d3ef3",
            "branch": "main",
            "remote": "https://github.com/adieyal/sd-dynamic-prompts.git"
        },
        {
            "name": "sd-extension-system-info",
            "path": "D:\\stable-diffusion-webui\\extensions\\sd-extension-system-info",
            "version": "72d871b4",
            "branch": "main",
            "remote": "https://github.com/vladmandic/sd-extension-system-info.git"
        },
        {
            "name": "sd-webui-aspect-ratio-helper",
            "path": "D:\\stable-diffusion-webui\\extensions\\sd-webui-aspect-ratio-helper",
            "version": "99fcf9b0",
            "branch": "main",
            "remote": "https://github.com/thomasasfk/sd-webui-aspect-ratio-helper.git"
        },
        {
            "name": "sd-webui-freeu",
            "path": "D:\\stable-diffusion-webui\\extensions\\sd-webui-freeu",
            "version": "08a1734f",
            "branch": "main",
            "remote": "https://github.com/ljleb/sd-webui-freeu"
        },
        {
            "name": "sd-webui-model-mixer",
            "path": "D:\\stable-diffusion-webui\\extensions\\sd-webui-model-mixer",
            "version": "54cb1929",
            "branch": "master",
            "remote": "https://github.com/wkpark/sd-webui-model-mixer.git"
        },
        {
            "name": "sd-webui-stablesr",
            "path": "D:\\stable-diffusion-webui\\extensions\\sd-webui-stablesr",
            "version": "4499d796",
            "branch": "master",
            "remote": "https://github.com/pkuliyi2015/sd-webui-stablesr.git"
        },
        {
            "name": "sd-webui-supermerger",
            "path": "D:\\stable-diffusion-webui\\extensions\\sd-webui-supermerger",
            "version": "f2be9fa8",
            "branch": "main",
            "remote": "https://github.com/hako-mikan/sd-webui-supermerger.git"
        },
        {
            "name": "sd-webui-zmultidiffusion-upscaler-for-automatic1111",
            "path": "D:\\stable-diffusion-webui\\extensions\\sd-webui-zmultidiffusion-upscaler-for-automatic1111",
            "version": "fbb24736",
            "branch": "main",
            "remote": "https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111.git"
        },
        {
            "name": "stable-diffusion-webui-model-toolkit",
            "path": "D:\\stable-diffusion-webui\\extensions\\stable-diffusion-webui-model-toolkit",
            "version": "cf824587",
            "branch": "master",
            "remote": "https://github.com/arenasys/stable-diffusion-webui-model-toolkit.git"
        },
        {
            "name": "ultimate-upscale-for-automatic1111",
            "path": "D:\\stable-diffusion-webui\\extensions\\ultimate-upscale-for-automatic1111",
            "version": "728ffcec",
            "branch": "master",
            "remote": "https://github.com/Coyote-A/ultimate-upscale-for-automatic1111.git"
        }

### Console logs

```Shell
Nothing / never is for this.
```

![sdfsfdsdf](https://github.com/Mikubill/sd-webui-controlnet/assets/37972078/c1263718-ed79-4b64-9964-4e76cfe3fd31)

**Comment by huchenlei** [comment]
Can you attach console log with `--controlnet-loglevel DEBUG` added to your launch script's args?

**Comment by huchenlei** [comment]
This seems normal, so we are actually detecting the A1111 width/height slider components and callbacks are registered, but still clicking on the button does not trigger the callback?

**Comment by huchenlei** [comment]
These log lines seem fishy. Why are we setting txt2img_width/height components multiple times?
```
2024-01-26 10:10:54,990 - ControlNet - DEBUG - Setting txt2img_width.
2024-01-26 10:10:54,990 - ControlNet - DEBUG - A1111 initialized 16/17.
2024-01-26 10:10:54,991 - ControlNet - DEBUG - Setting txt2img_height.
2024-01-26 10:10:54,991 - ControlNet - DEBUG - A1111 initialized 16/17.
```
