### ISSUE TITLE
AnimateDiff still not recognizing ControlNet anymore...

### ISSUE THREAD

**Issue by HappyBoyPat** [Mikubill/sd-webui-controlnet#2609]
hello smart people,

My animateDiff stopped working with controlnet a few weeks ago and is still not functional. I  noticed an update to both animateDiff and Controlnet this morning (Jan 31, 2024), and I was hopeful that was the fix I was waiting for, but sadly animateDiff is still no longer honoring any form of controlnet.  

AnimateDiff version: e9db9f28

ControlNet version : 0ee02811

Anyone else having this issue ? Anyone know of any help on the horizon ?  

Thanks so much.
-Patrick

**Comment by huchenlei** [comment]
The owner of sd-webui-animatediff is inactive right now. I have already open a PR to fix this https://github.com/continue-revolution/sd-webui-animatediff/pull/409.

Users have already verified that the PR works. You can manually patch that PR before animatediff author comes back and merge it.

**Comment by Danny-707** [comment]
I have the same problem.

*The solution through changing some 'PR' is completely unclear (to me). And I have a portable version of SD installed, which means Git is not installed in the system, so I think it won't work.
Although I have no slightest idea)
