### ISSUE TITLE
Option to use image prompts from png file in txt2img

### ISSUE THREAD

**Issue by outlandish1** [Mikubill/sd-webui-controlnet#2610]
Would it be possible to use the image prompt (from the image file) in controlnet on txt2img rather than the main prompts?

You can do this via batch in img2img with "PNG info", but it would be handy to have this option in txt2img controlnet.

This would mean we could do a batch of controlnet images, each with their own prompt.

**Comment by huchenlei** [comment]
If you want more customized ControlNet batch, please use ControlNet's web API.

You can fine documentation [here](https://github.com/Mikubill/sd-webui-controlnet/wiki/API), and examples [here](https://github.com/Mikubill/sd-webui-controlnet/tree/main/example).
