### ISSUE TITLE
[Bug]: ip-adapter_sd15_vit-G

### ISSUE THREAD

**Issue by Kuvshin8** [Mikubill/sd-webui-controlnet#2617]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

ip-adapter_clip_sdxl and ip-adapter_clip_sd15 - don't work with ip-adapter_sd15_vit-G. We need **vit-G** for 1.5

### Steps to reproduce the problem

1. Go to controlnet
2. Press ip-adapter_clip_sdxl and ip-adapter_sd15_vit-G
3. don't work

### What should have happened?

New ip-adapter_sd15_vit-G 

### Commit where the problem happens

controlnet

### Command Line Arguments

```Shell
ip-adapter_clip_sdxl and ip-adapter_sd15_vit-G
```

### List of enabled extensions

controlnet

### Console logs

```Shell
File "/workspace/venv/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
 return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x1024 and 1280x3072)
```

**Comment by huchenlei** [comment]
Should be addressed by https://github.com/Mikubill/sd-webui-controlnet/pull/2710.
