### ISSUE TITLE
question: How to add my own controlnet to webui

### ISSUE THREAD

**Issue by XiangjiBU** [Mikubill/sd-webui-controlnet#2621]
Hi, thanks for this greet work!
I trained my own controlnet model using [https://github.com/lllyasviel/ControlNet](url). I want to use this model together with pose control model (already exist in your project) on  **A1111 WebUI**. Beside, my controlnet model need my own Preprocessor( a segment model).

could you tell me  how to add my own controlnet model and segment model (as a Preprocessor) to the webui?

**Comment by sdbds** [comment]
example：
#2212

**Comment by huchenlei** [comment]
We are switching to https://github.com/lllyasviel/stable-diffusion-webui-forge 
You can find very detailed example and guide there on how to add a preprocessor and model.
