### ISSUE TITLE
Blank Square from PreProcessor

### ISSUE THREAD

**Issue by g2asell2019** [Mikubill/sd-webui-controlnet#263]
Thanks to your extension, we can generate a lot of image with same pose

It seems I found a bug, I can not get preprocessor to work on [colab](https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb)

What I have tried:
- delete extension and re-install
- manually upload extension and models from my local machine (my local machine works fine)
- re-install opencv
- find if someone has got same problems as me but could not find any reports

If I set preprocessor to None, it works like normal

Output will either blank white or blank black
Example:

Input:
![image](https://user-images.githubusercontent.com/51025883/220382325-f5f3ae0e-4157-491f-b614-29d855c41e00.png)

Output:
![image](https://user-images.githubusercontent.com/51025883/220382190-88221613-793e-4c6e-8e04-9af9a72acc6d.png)

Input:
![image](https://user-images.githubusercontent.com/51025883/220387516-47a44413-d00d-42b8-b0e6-f088a05fee02.png)

Output:
![image](https://user-images.githubusercontent.com/51025883/220387372-64244e31-0c75-44fa-beba-caa545af6c3e.png)

**Comment by Mikubill** [comment]
Quick test (colab), everything works good.

![Screenshot 2023-02-22 at 0 41 05](https://user-images.githubusercontent.com/31246794/220391501-e54568fe-08df-4bf5-be70-29801dc3b33a.png)

**Comment by g2asell2019** [comment]
> Quick test (colab), everything works good.
> 

is it same as this [colab](https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb)

**Comment by Mikubill** [comment]
Yes, directly run without any modify

**Comment by g2asell2019** [comment]
Maybe I should empty my drive then try again

**Comment by g2asell2019** [comment]
I found the root cause is my Brave browser, change to chrome it works good.
Thank you very much.

Solutions: change to chrome or disable Brave Shield on gradio site
