### ISSUE TITLE
Generate an image with IP-Adapter

### ISSUE THREAD

**Issue by dongyun-kim-arch** [Mikubill/sd-webui-controlnet#2630]
Hello

I am trying to create some SD API code with ControlNet. What I am working is to get the right settings in WebUI, and write the settings I used in API call. and then make sure WebUI and API results are the same.

Everything is going well with all other ControlNet models such as OpenPose, Canny, but whenever I use IP-Adapter, it doesn't give the same result (generated image from WebUI is different from generated image from API even though I put the same settings). The PNG info of two images are the same..

I feel there are some hidden default settings, or I am overwriting some options, but not sure where I could find the related parameters in API.

This is the json file I used for API call.
{
    "steps": 30,
    "width": 512,
    "height": 512,
    "cfg_scale": 7,
    "sampler_name": "DPM++ 2M Karras",
    "n_iter": 1,
    "batch_size": 1,
    "alwayson_scripts": {
        "ControlNet": {
            "args": [
                {
                    "batch_images": "",
                    "control_mode": "Balanced",
                    "enabled": true,
                    "guidance_end": 1,
                    "guidance_start": 0,
                    "image": {
                        "image": $IMAGE_PATH,
                        "mask": null
                    },
                    "input_mode": "simple",
                    "is_ui": true,
                    "loopback": false,
                    "low_vram": false,
                    "model": "control_v11p_sd15_openpose [cab727d4]",
                    "module": null,
                    "output_dir": "",
                    "pixel_perfect": true,
                    "resize_mode": "Crop and Resize",
                    "weight": 1
                },
                {
                    "batch_images": "",
                    "control_mode": "Balanced",
                    "enabled": false,
                    "guidance_end": 1,
                    "guidance_start": 0,
                    "image": {
                        "image": $IMAGE_PATH,
                        "mask": null
                    },
                    "input_mode": "simple",
                    "is_ui": true,
                    "loopback": false,
                    "low_vram": false,
                    "processor_res": 512,
                    "model": "ip-adapter-plus-face_sd15 [71693645]",
                    "module": "ip-adapter_clip_sd15",
                    "output_dir": "",
                    "pixel_perfect": true,
                    "resize_mode": "Crop and Resize",
                    "weight": 1
                }
            ]
        }
    },
    "enable_hr": true,
    "hr_upscaler": "R-ESRGAN 4x+",
    "hr_scale": 2.5,
    "hr_second_pass_steps": 20,
    "denoising_strength": 0.4,
    "override_settings": {
        "sd_model_checkpoint": $SD_MODEL
    }
}

I believe there might be some issues in IP-Adapter tab, but not sure what causes the issue...

**Comment by huchenlei** [comment]
Can you share the result you get both from UI and from API?

**Comment by dongyun-kim-arch** [comment]
@huchenlei 
api_generated and webui_generated.
They are definitely similar, but not same..
![api_generated](https://github.com/Mikubill/sd-webui-controlnet/assets/70664694/be6a2b3d-a863-4b2b-b46b-44fe7e5507d0)
![webui_generated](https://github.com/Mikubill/sd-webui-controlnet/assets/70664694/eca92010-0269-4519-bab1-7b933bda7226)

**Comment by dongyun-kim-arch** [comment]
It's weird that I get the same results when using openpose only, but when adding IP-Adapter with openpose, the results are different... so I believe something happens in IP-Adapter...

**Comment by xddun** [comment]
I want to use the ControlNet WebUI API, and I want to send multiple images to IPAdapter at once. It's possible to do this via the UI, but I don't know how to pass the parameters when writing the interface.


This is an incorrect call, mainly because the image parameter probably cannot be passed in this way:

```
"controlnet": {
    "args": [
        {
            "enabled": True,  # Enable
            "control_mode": "Balanced",
            # "Balanced" "My prompt is more important" "ControlNet is more important"
            "model": "ip-adapter-faceid-plusv2_sdxl [187cb962]",  # Corresponding Model in webui
            "module": "ip-adapter-auto",  # Corresponding Preprocessor in webui
            "weight": 1,  # Corresponding Control Weight in webui
            "resize_mode": "Crop and Resize",
            # "threshold_a": 200,  # Threshold a, used by some control modules
            # "threshold_b": 245,  # Threshold b
            "guidance_start": 0,  # When to start, corresponding to Starting Control Step in webui
            "guidance_end": 1,  # When to end, corresponding to Ending Control Step in webui
            "pixel_perfect": True,  # Pixel Perfect
            # "processor_res": 1024,  # Preprocessor Resolution
            "save_detected_map": False,  # ControlNet API returns a generated ControlNet effect image by default, set to False if not needed
            "image": [image_to_base64("img.png"), image_to_base64("20240507-094810.jpg")],
            # "image": image_to_base64("img.png"),
        }
        # For multiple controlnets, just copy the dictionary above
    ]
}


```

Here is my call error.


![image](https://github.com/Mikubill/sd-webui-controlnet/assets/25652821/c4f8da9a-1c45-4f1b-b8f0-5be17c7f4d54)


The WebUI displays the interface like this.

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/25652821/98cf3d76-b47d-420a-8695-f13af9c35acf)

**Comment by xddun** [comment]
@huchenlei  help...

**Comment by xddun** [comment]
@huchenlei  help...

**Comment by xddun** [comment]
The shapes ((1080, 1080)) and ((1440, 1080)) happen to be the shapes of the two images I passed in. Do I need to perform center cropping locally before transmitting them like this? Or is it that IPAdapter doesn't accept the 'image' parameter when passing images?

*** Error running process: /home/xiedong/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "/home/xiedong/stable-diffusion-webui/modules/scripts.py", line 825, in process
        script.process(p, *script_args)
      File "/home/xiedong/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 1222, in process
        self.controlnet_hack(p)
      File "/home/xiedong/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 1207, in controlnet_hack
        self.controlnet_main_entry(p)
      File "/home/xiedong/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 941, in controlnet_main_entry
        controls, hr_controls, additional_maps = get_control(
      File "/home/xiedong/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 206, in get_control
        input_image, resize_mode = Script.choose_input_image(p, unit, idx)
      File "/home/xiedong/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 692, in choose_input_image
        image = unit.get_input_images_rgba()
      File "/home/xiedong/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/args.py", line 411, in get_input_images_rgba
        self.combine_image_and_mask(np_image, np_mask)
      File "/home/xiedong/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/args.py", line 309, in combine_image_and_mask
        raise ValueError(
    ValueError: image shape ((1080, 1080)) not aligned with mask shape ((1440, 1080))

**Comment by xddun** [comment]
I've looked at the code for the unit tests, and it seems like this is how it's called. Could you help me verify if this call is correct? It seems right to me.

"image": [{"image": image_to_base64("img.png")},
                                  {"image": image_to_base64("20240507-094810.jpg")}]
                                  
                                  
```
"controlnet":
            {
                "args": [
                    {
                        "enabled": True,  # 启用
                        "control_mode": "Balanced",
                        # "Balanced" "My prompt is more important" "ControlNet is more important"
                        "model": "ip-adapter-faceid-plusv2_sdxl [187cb962]",  # 对应webui 的 Model
                        "module": "ip-adapter-auto",  # 对应webui 的 Preprocessor
                        "weight": 1,  # 对应webui 的Control Weight
                        "resize_mode": "Crop and Resize",
                        # "threshold_a": 200,  # 阈值a 部分control module会用上
                        # "threshold_b": 245,  # 阈值b
                        "guidance_start": 0,  # 什么时候介入 对应webui 的 Starting Control Step
                        "guidance_end": 1,  # 什么时候退出 对应webui 的 Ending Control Step
                        "pixel_perfect": True,  # 像素完美
                        "processor_res": 1024,  # 预处理器分辨率
                        "save_detected_map": False,  # 因为使用了 controlnet API会返回生成controlnet的效果图，默认是True，如何不需要，改成False
                        # "image": [image_to_base64("img.png"), image_to_base64("20240507-094810.jpg")],
                        # "image": image_to_base64("img.png"),
                        "image": [{"image": image_to_base64("img.png")},
                                  {"image": image_to_base64("20240507-094810.jpg")}]

                    }
                    # 多个controlnet 在复制上面一个字典下来就行
                ]
            },
            
```

**Comment by phucbienvan** [comment]
hi @xddun @huchenlei @dongyun-kim-arch 
I also encountered a similar issue with using multi-inputs. How did you fix it?

**Comment by RituSingha** [comment]
I think this is not yet solved, reopen the issue.

**Comment by cjkangme** [comment]
I have the same issue. I think IP-Adapter dose not work if I use with other ControlNets when using API.
