### ISSUE TITLE
[Bug]: No Instant_ID Control Type

### ISSUE THREAD

**Issue by heartforheart** [Mikubill/sd-webui-controlnet#2632]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

After updating ControlNet 'https://github.com/Mikubill/sd-webui-controlnet.git' and uploading my models into both my extensions folder for controlnet and the default install location models folder for controlnet, I still do not have the Instant_ID control type under controlnet :/

### Steps to reproduce the problem

As outlined above.

### What should have happened?

Control Type Instant_ID should have been there to select.

### Commit where the problem happens

webui: 
controlnet: 

### Command Line Arguments

```Shell
No
```

### List of enabled extensions

Controlnet

### Console logs

```Shell
.
```

### Additional information

.

**Comment by huchenlei** [comment]
Please attach your console log. Thanks!

**Comment by heartforheart** [comment]
> Please attach your console log. Thanks!

Hi @huchenlei, is it just the console logs when I launch A111?

**Comment by heartforheart** [comment]
venv "F:\DiffusionStable\webui\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.7.0
Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e
Launching Web UI with arguments: --theme dark --disable-nan-check
No module 'xformers'. Proceeding without it.
*** Error loading script: lora_script.py
    Traceback (most recent call last):
      File "F:\DiffusionStable\webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "F:\DiffusionStable\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\DiffusionStable\webui\extensions-builtin\Lora\scripts\lora_script.py", line 99, in <module>
        shared.opts.onchange("lora_in_memory_limit", networks.purge_networks_from_memory)
      File "F:\DiffusionStable\webui\modules\options.py", line 209, in onchange
        func()
      File "F:\DiffusionStable\webui\extensions-builtin\Lora\networks.py", line 242, in purge_networks_from_memory
        while len(networks_in_memory) > shared.opts.lora_in_memory_limit and len(networks_in_memory) > 0:
    TypeError: '>' not supported between instances of 'int' and 'NoneType'

---
ControlNet preprocessor location: F:\DiffusionStable\webui\extensions\sd-webui-controlnet\annotator\downloads
2024-02-09 17:41:00,102 - ControlNet - INFO - ControlNet v1.1.432
2024-02-09 17:41:00,514 - ControlNet - INFO - ControlNet v1.1.432
Loading weights [ec41bd2a82] from F:\DiffusionStable\webui\models\Stable-diffusion\photon_v1.safetensors
*Deforum ControlNet support: enabled*
Running on local URL:  http://127.0.0.1:7860
Creating model from config: F:\DiffusionStable\webui\configs\v1-inference.yaml

To create a public link, set `share=True` in `launch()`.
Startup time: 76.8s (initial startup: 0.2s, prepare environment: 21.8s, import torch: 21.5s, import gradio: 7.5s, setup paths: 7.5s, initialize shared: 0.8s, other imports: 6.4s, setup codeformer: 1.8s, setup gfpgan: 0.3s, list SD models: 0.8s, load scripts: 4.2s, reload hypernetworks: 0.2s, create ui: 2.7s, gradio launch: 1.8s).

**Comment by huchenlei** [comment]
Following logs indicate that you are not on lastest version of ControlNet extension.
```
2024-02-09 17:41:00,102 - ControlNet - INFO - ControlNet v1.1.432
2024-02-09 17:41:00,514 - ControlNet - INFO - ControlNet v1.1.432
```

**Comment by heartforheart** [comment]
> Following logs indicate that you are not on lastest version of ControlNet extension.
> 
> ```
> 2024-02-09 17:41:00,102 - ControlNet - INFO - ControlNet v1.1.432
> 2024-02-09 17:41:00,514 - ControlNet - INFO - ControlNet v1.1.432
> ```

I have clicked check for updates, but, it does not update, then. How would you go about updating then?

**Comment by huchenlei** [comment]
You can run some git commands to manually update.

Make sure you are on main branch
- git checkout main 

Pull changes from remote
- git fetch origin

Update
- git rebase

**Comment by heartforheart** [comment]
I had deleted the control net folder in extensions and reinstalled it and it has updated to
2024-02-10 14:16:59,506 - ControlNet - INFO - ControlNet v1.1.440

this gives me the Instant_ID tab now
thank you @huchenlei for pointing this out for me!!!!

I do not know why check for updates does not update though :/
