### ISSUE TITLE
/controlnet/detect return image?

### ISSUE THREAD

**Issue by Graylington** [Mikubill/sd-webui-controlnet#2637]
I'm looking for a way to save processing time in my python code.

Since it generates 10 images in a row using the same ControlNet images, I figure I should be able to run preprocessor once and then reuse the resulting image in the ControlNet for all 10 generations.

I came across /controlnet/detect which seemed to be what I was looking for, however it doesn't return the preprocessed image. Is there any way around this? Any ideas?

Thanks!

**Comment by huchenlei** [comment]
If you use the same input image for preprocessor and do 10 generations, the built-in preprocessor result cache will make preprocessor only run once.

Detect endpoint returns image as base64 strings. You need to convert them back to PIL image if you want to save them.

**Comment by Graylington** [comment]
> If you use the same input image for preprocessor and do 10 generations, the built-in preprocessor result cache will make preprocessor only run once.
> 
> Detect endpoint returns image as base64 strings. You need to convert them back to PIL image if you want to save them.

Thanks! I was mistaken, it does indeed return the preprocessed image.

Does the built-in preprocessor result cache work in the WebUI itself? I've never experienced it being smart enough to reuse the preprocessed images when the input image remained the same.

**Comment by huchenlei** [comment]
You can find caching related logic here. The cache layer log only shows if you set `--controlnet-loglevel DEBUG`.

https://github.com/Mikubill/sd-webui-controlnet/blob/416c345072c9c2066101e225964e3986abe6945e/scripts/global_state.py#L22-L50
