### ISSUE TITLE
Why can't my openpose algorithm and model take effect? Other models are normal.

### ISSUE THREAD

**Issue by Saktawdi** [Mikubill/sd-webui-controlnet#264]
- openpose

![image](https://user-images.githubusercontent.com/100117291/220392039-b532a033-8bd5-4453-bccb-0870bf3cf97b.png)
![image](https://user-images.githubusercontent.com/100117291/220392070-7beb972c-9a9d-40d8-b431-2aeaba2944fc.png)

- by Bone

![image](https://user-images.githubusercontent.com/100117291/220393056-a6b80e99-47d9-4c48-b6b1-77302392a4cc.png)
![image](https://user-images.githubusercontent.com/100117291/220393201-09bf393a-1d30-4322-a82e-b54583dc70a7.png)

- hed

![image](https://user-images.githubusercontent.com/100117291/220392464-c062ec53-16b0-43a8-8381-49fb8e93cd08.png)

**Comment by Saktawdi** [comment]
![image](https://user-images.githubusercontent.com/100117291/220397703-5633d245-c081-4fda-9829-e8085c2f88fa.png)

**Comment by Lexcess** [comment]
Not quite sure what you are doing from screenshots, but if you already have an open pose image (from the extension perhaps), leaving the preprocessor as 'none' and selecting the model as normal seems to work.

**Comment by ClashSAN** [comment]
@Saktawdi 
the openpose preprocessor outputs blank black images when it is unsuccessful at detecting the pose figure. This is the only preprocessor that has some possiblity to fail at detection, the others are fine.

However, you can send your own pose figure in, by setting the preprocessor to none, and the model to openpose, as @Lexcess says.
This is going to guarantee your picture follows the pose.
