### ISSUE TITLE
[Bug]: batch input doesnt work properly

### ISSUE THREAD

**Issue by Hugs288** [Mikubill/sd-webui-controlnet#2644]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I try to generate an image with batch input ipadater, instead of making 1 image it tries to make as many images as there are in the batch folder. (if the batch folder has 300 images, webui will try generate 300 images)

### Steps to reproduce the problem

1. Go to txt2img
2. turn on ipadater with batch input
3. generate

### What should have happened?

the webui should have generated 1 image.

### Commit where the problem happens

webui: cf2772fab0af5573da775e7437e6acdca424f26e (1.7.0)
controlnet: 9a5f28838a3670018fe00af48e4a3ee91582d279

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--opt-sdp-no-mem-attention --no-half-vae --no-half
```

### List of enabled extensions

-

### Console logs

```Shell
there are no errors
```

**Comment by huchenlei** [comment]
batch tab is different with multi-inputs tab.

See documentation for `InputMode` here:
```python
class InputMode(Enum):
    # Single image to a single ControlNet unit.
    SIMPLE = "simple"
    # Input is a directory. N generations. Each generation takes 1 input image
    # from the directory.
    BATCH = "batch"
    # Input is a gallery. 1 generation. Each generation takes N input image
    # from the gallery.
    MERGE = "merge"
```

**Comment by Hugs288** [comment]
can i select a folder of images to be used in the multi inputs tab?

**Comment by huchenlei** [comment]
Currently it is not supported. It is also not recommended to upload too many input images for ipadapter, as each input's weight will become very low, and there can be a lot of noise.

**Comment by Hugs288** [comment]
alright, thank you for clarification
