### ISSUE TITLE
[Bug]: Crop input image based on A1111 mask not working in API

### ISSUE THREAD

**Issue by john-backlot** [Mikubill/sd-webui-controlnet#2645]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

IP Adapter and inpainting only masked dont work as expected in the API. I've been unable to find something like "Crop input image based on A1111 mask" inside the API that can be used to set to False, since the API results seem to not be true to the face I want.

### Steps to reproduce the problem

Run the API and try IP Adapter + inpainting only masked.

### What should have happened?

Should NOT crop the controlnet input image when using IP Adapter.

### Commit where the problem happens

latest commit (feb 15)

### Command Line Arguments

```Shell
No
```

### List of enabled extensions

fresh install with ControlNet only

### Console logs

```Shell
N/A
```

**Comment by huchenlei** [comment]
If you are using API, it is very easy to just crop the inpaint area out and use inpaint area = whole image.
