### ISSUE TITLE
[Bug]: sd-webui-controlnet always disabled in extensions tab

### ISSUE THREAD

**Issue by iamsuper123** [Mikubill/sd-webui-controlnet#2655]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

the controlnet extension is always disabled in the extensions tab. if I press enable and reload ui, it disables itself again. i've tried reinstalling it, but it still doesn't work. 

### Steps to reproduce the problem

1. Go to extensions tab
2. install controlnet webui

### What should have happened?

controlnet-webui should've been enabled when i restarted it
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/160750182/90833ce1-09cb-43da-8f5d-af7e2f6eb76b)

### Commit where the problem happens

webui: version: [f0.0.14v1.8.0rc-latest-184-g43c9e3b5](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/43c9e3b5ce1642073c7a9684e36b45489eeb4a49)
controlnet: [679b6279](https://github.com/Mikubill/sd-webui-controlnet/commit/679b62790b22319a6833130c23986fb4fa47337b)	2024-02-19 10:52:46	
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/160750182/ea3e9496-a356-4ede-bccc-c202e20f55c5)

### Command Line Arguments

```Shell
I am using forge stable diffusion, vivaldi web browser.
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/160750182/827d4ce1-9cc2-407b-b608-e1c0fc0091a8)

### Console logs

```Shell
none
```

### Additional information

none

**Comment by huchenlei** [comment]
You should not use this extension in forge. This extension is not build for forge's backend. Please stick to the built-in version of ControlNet extension in forge.

**Comment by iamsuper123** [comment]
> You should not use this extension in forge. This extension is not build for forge's backend. Please stick to the built-in version of ControlNet extension in forge.

thx but the problem with forge's in built controlnet is it doesn't support video files in deforum when enabling controlnet models. oh well. its fine i remember one guy replaced a couple of .py files and said that it fixes some compatibility issues with forge, imma try that
