### ISSUE TITLE
Hugginface ControlNet Models Download issue

### ISSUE THREAD

**Issue by Bobcatie** [Mikubill/sd-webui-controlnet#2658]
The 14 ControlNet Models found at
https://huggingface.co/lllyasviel/ControlNet-v1-1/tree/main
total around 21GB in size given that each ".pth" is 1.45gb

The Models for whatever reason are Very Very Slow to Donwload.
so much so tat its actually painfully slow

![Screenshot from 2024-02-22 14-34-43](https://github.com/Mikubill/sd-webui-controlnet/assets/125765334/975ce876-1640-4216-b61e-d689e478ca4c)

is there anyway to host these files elsewhere possibly a google drive so that they can be dolwnloaded in an acceptable length of time?

**Comment by huchenlei** [comment]
There are ControlLoRA and fp16 ControlNet for SD1.5 here: https://huggingface.co/comfyanonymous/ControlNet-v1-1_fp16_safetensors/tree/main

You can also find other models in this wiki page: https://github.com/lllyasviel/stable-diffusion-webui-forge/wiki/ControlNet-model-download

**Comment by Bobcatie** [comment]
Thankyou for your reply. I managed to download the smaller 16bit safetensors but im a bit confused at how to implement them as they are noty a pth extension.

**Comment by Bobcatie** [comment]
I got it working, thankyou so much for your help
