### ISSUE TITLE
[Bug]depth_hand_refiner not inpainting by controlnet module

### ISSUE THREAD

**Issue by yumianhuli1** [Mikubill/sd-webui-controlnet#2673]
by sd-webui-aki-v4.6.1
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/13059391/1d7cf0a7-b53b-4501-93b9-f097ed4d15d2)
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/13059391/6032ae1e-1bab-4e41-bfa9-af40379f8a74)

but it works fine for adtailer img2img mode
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/13059391/d96b9262-550c-426f-8a1e-734942a04649)
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/13059391/d3d31831-4dd5-4557-a19b-2cd5c66b236e)
But adtailer's biggest problem is that it tries to fix all hands, and sometimes good hands turn into bad ones

**Comment by huchenlei** [comment]
The denosing strength might be too low. I saw you set it as 0.3 in the first picture. Try increase the value and see if it becomes better.

**Comment by yumianhuli1** [comment]
ok，thank u！close

**Comment by yumianhuli1** [comment]
> The denosing strength might be too low. I saw you set it as 0.3 in the first picture. Try increase the value and see if it becomes better.

ok，thank u！close
