### ISSUE TITLE
[Enhancement]: Default preprocessor (module) via API

### ISSUE THREAD

**Issue by altoiddealer** [Mikubill/sd-webui-controlnet#2679]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

First and foremost, I want to express my gratitude for ControlNet as a whole, and that it actually works (very well!!) via A1111's and Forge's API.

I've implemented a very basic level of cnet support in [my discord bot](https://github.com/altoiddealer/ad_discordbot), which currently sends values for: `image`, `model`, `module`, `guidance_end`, `weight`, and `enabled`.

**If I do not send a key for `module` in the payload**, it errors with `AttributeError: 'NoneType' object has no attribute 'slider_resolution'`

I understand this is intended behavior (not a bug), and users are expected to provide this key/value.  My bot code typically assigns the key with default value of 'None'.

## What I think would be really amazing for the API, though, is for missing keys to default to an appropriate `module` and/or `model` in the same way that ticking a "Control Type" radio button does in the WebUI.

Or, at least some API method to retrieve the values these radio buttons yield:
<img width="905" alt="Screenshot 2024-03-05 123418" src="https://github.com/Mikubill/sd-webui-controlnet/assets/1613484/43f3d018-b844-4022-8a5e-fd4610b30da2">

### Steps to reproduce the problem

Use Controlnet via API

### What should have happened?

Less restrictive payload requirements

### Commit where the problem happens

webui: current
controlnet: current

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--api --listen --cuda-stream --pin-shared-memory
```

### List of enabled extensions

controlnet

### Console logs

```Shell
*** Error running process: C:\0_SD\stable-diffusion-webui-forge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\0_SD\stable-diffusion-webui-forge\modules\scripts.py", line 803, in process
        script.process(p, *script_args)
      File "C:\0_SD\stable-diffusion-webui-forge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "C:\0_SD\stable-diffusion-webui-forge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 546, in process
        self.bound_check_params(unit)
      File "C:\0_SD\stable-diffusion-webui-forge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 519, in bound_check_params
        unit.processor_res = int(preprocessor.slider_resolution.gradio_update_kwargs.get('value', 512))
    AttributeError: 'NoneType' object has no attribute 'slider_resolution'

---
*** Error running process_before_every_sampling: C:\0_SD\stable-diffusion-webui-forge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\0_SD\stable-diffusion-webui-forge\modules\scripts.py", line 835, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "C:\0_SD\stable-diffusion-webui-forge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "C:\0_SD\stable-diffusion-webui-forge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 555, in process_before_every_sampling
        self.process_unit_before_every_sampling(p, unit, self.current_params[i], *args, **kwargs)
    KeyError: 0

---
To load target model SDXL
Begin to load 1 model
Reuse 1 loaded models
[Memory Management] Current Free GPU Memory (MB) =  234.470703125
[Memory Management] Model Memory (MB) =  0.0
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  -789.529296875
[Memory Management] Requested ASYNC Preserved Memory (MB) =  0.0
[Memory Management] Parameters Loaded to ASYNC Stream (MB) =  4897.0483474731445
[Memory Management] Parameters Loaded to GPU (MB) =  0.0
Moving model(s) has taken 2.89 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:10<00:00,  2.93it/s]
To load target model AutoencoderKL█████████████████████████████████████████████████████| 30/30 [00:09<00:00,  3.19it/s]
```

**Comment by altoiddealer** [comment]
Frankly, I think `control_type` should be a new optional key which would assert a default `model` and `module` by the same mechanism as the Radio buttons.  Any explicitly specified `model` or `module` would then override the aforementioned default.

**Comment by huchenlei** [comment]
I think this is a forge specific problem.

**Comment by huchenlei** [comment]
I don't think it can be any smarter, as we don't know the type of controlnet model until actually loading it, so there is no way infer what module (preprocessor) to use.
