### ISSUE TITLE
[Feature?] Deforum can use Batch Controlnet (but it's pretty jank)

### ISSUE THREAD

**Issue by FizzleDorf** [Mikubill/sd-webui-controlnet#268]
I found a way to leak controlnet into Deforum img2img modes to create this sort of effect when I was doing some tests. Keep in mind it was pretty sloppy and took a few gens for me to realize what was happening.

[Original video, Deforum only](https://imgur.com/kiorU01) + Deforum project txt: [20230129152804_settings.txt](https://github.com/Mikubill/sd-webui-controlnet/files/10795954/20230129152804_settings.txt)

[Controlnet + Deforum](https://imgur.com/L5mpQjc) + Deforum project txt (same as original): [20230221114219_settings.txt](https://github.com/Mikubill/sd-webui-controlnet/files/10795988/20230221114219_settings.txt)

[Controlnet input from batch img2img](https://imgur.com/f76LaGy)

"It's a feature"

Steps to reproduce:
1. use controlnet in batch img2img using only controlnet (skip img2img process).
2. Using Deforum img2img modes (2D or 3D modes) prompt an animation in the animation promt input.
3. generate.

I haven't played around with the camera controls yet as I thought I should share for the possibility this gets implemented in a cleaner way but it is already possible without any sort of implementation in Deforum.

**Comment by yengalvez** [comment]
> Steps to reproduce:
> 
> 1. use controlnet in batch img2img using only controlnet (skip img2img process).
> 2. Using Deforum img2img modes (2D or 3D modes) prompt an animation in the animation promt input.
> 3. generate.
> 

I don't understand well... I'm trying to use Batch img2img to force Multi-ControlNet over 3D mode of Deforum. It's supposed that with this method I can do it? I tried this process but it doesn't work even with only canny. Deforum ControlNet works well, but i want to try multicontrolnet + deforum. Thanks
