### ISSUE TITLE
[Feature] i find suitable scales for t2i adapter guess mode

### ISSUE THREAD

**Issue by lllyasviel** [Mikubill/sd-webui-controlnet#269]
Because t2i adapter has fewer layers, weightings like 0.825**n will not work very well. After trying many possible weights, the below weights seem to work:

feature_64: 0.25
feature_32: 0.62
feature_16: 0.825
feature_8: 1.0

Let me know what you think or should i post some examples

**Comment by lllyasviel** [comment]
Because t2i adapter's encoder is lighter, their guess mode will look like this
![image](https://user-images.githubusercontent.com/19834515/220461770-f7f8f33d-4fcb-46e6-8f6d-ea3b0b090c4d.png)
![image](https://user-images.githubusercontent.com/19834515/220461784-b0e42b31-89ca-4e7e-9511-56ce998d3c2f.png)
![image](https://user-images.githubusercontent.com/19834515/220461807-97d6956d-cd25-4a72-a512-9e5502b631dd.png)
![image](https://user-images.githubusercontent.com/19834515/220461817-9b528ec9-81e7-4d04-86ef-558aba6105a5.png)
These results may be interesting in "pure guesses"; but with prompts, perhaps in some cases it will still improve the result a bit.
But since we already have guess mode for some models, perhaps we should implement all.

**Comment by lllyasviel** [comment]
thanks very much! is it possible to put this in a bit higher priority? we are trying to perform some experiments in webui but if we can get this done we can simply reuse your codes. I tried this plugin today and this plugin is really awesome well done!

**Comment by Mikubill** [comment]
already added in https://github.com/Mikubill/sd-webui-controlnet/pull/262, will merge later after some tests

**Comment by lllyasviel** [comment]
thanks! looking forward!

**Comment by lllyasviel** [comment]
Hi the quality of results do not look similar to my results. seems something is not very correct.
![image](https://user-images.githubusercontent.com/19834515/220546687-6f52a05a-3930-4f40-856b-e510666edfb8.png)

**Comment by lllyasviel** [comment]
My results are achieved by disconnect t2i adapter in uncond, and then on the cond size we use 0.25, 0.62, 0.825, 1.0 as weights. 1.0 is for the 8*8 layer.

**Comment by lllyasviel** [comment]
clearly not a problem of PLMS
![image](https://user-images.githubusercontent.com/19834515/220547552-088d119f-b5e3-4fc0-84b3-0f88f99078bd.png)

**Comment by Mikubill** [comment]
Seems like adapter haven't disconnect on unconditional side, will fix later

**Comment by Mikubill** [comment]
misclicked. try with the latest commit

**Comment by lllyasviel** [comment]
let me try

**Comment by lllyasviel** [comment]
what happened?
![image](https://user-images.githubusercontent.com/19834515/220552773-b34f3fbd-ee98-4374-9b37-db8ef2fce7ea.png)

**Comment by lllyasviel** [comment]
clearly a bug, but why is this even possible? ? ? i do not input prompts but image quality very high!

**Comment by lllyasviel** [comment]
and

Traceback (most recent call last):
  File "C:\Users\lvmin\.conda\envs\automatic\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\lvmin\.conda\envs\automatic\lib\site-packages\gradio\blocks.py", line 1013, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\Users\lvmin\.conda\envs\automatic\lib\site-packages\gradio\blocks.py", line 911, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
IndexError: list index out of range

**Comment by lllyasviel** [comment]
find a way to reproduce it. load a img, generate, then click guesss mode, then generate, then change to ddim, then generate. boom! bug happens

**Comment by lllyasviel** [comment]
god. these steps not needed. just guess mode+ ddim+pidnet+t2i sketch

**Comment by lllyasviel** [comment]
absolutely impossible
![image](https://user-images.githubusercontent.com/19834515/220555039-39e5d322-55d7-4963-936f-7318da7f1d75.png)

**Comment by lllyasviel** [comment]
I must know what happens.

**Comment by lllyasviel** [comment]
my controlnet also has this
![image](https://user-images.githubusercontent.com/19834515/220555851-3b1b935f-edca-44bc-b998-d5dcfeb4de46.png)

amazing. what happens????

**Comment by Mikubill** [comment]
Tested with Euler a and it seems….fine?
![grid-0104-2](https://user-images.githubusercontent.com/31246794/220555868-754f9df6-8bd4-4a5b-a804-6fb6ef640f11.png)
Maybe some assertions not fully compatible with non-k-diffusion samplers.

**Comment by lllyasviel** [comment]
but what happens with ddim? 
this deserves a new paper! can we use this to extract the entire dataset of a diffusion model?

**Comment by lllyasviel** [comment]
goddess. We need to delete this issue and not let others know.
