### ISSUE TITLE
[Bug]: Error executing callback cfg_denoiser_callback

### ISSUE THREAD

**Issue by thiagojramos** [Mikubill/sd-webui-controlnet#2699]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When I try to generate an image with controlnet, whether with SD 1.5 or XL, at each step it shows the following error message:
`---
 98%|█████████▊| 39/40 [00:19<00:00,  2.23it/s]*** Error executing callback cfg_denoiser_callback for C:\AI\Packages\WebUI\extensions\sd-webui-controlnet\scripts\hook.py
    Traceback (most recent call last):
      File "C:\AI\Packages\WebUI\modules\script_callbacks.py", line 333, in cfg_denoiser_callback
        c.callback(params)
      File "C:\AI\Packages\WebUI\extensions\sd-webui-controlnet\scripts\hook.py", line 419, in guidance_schedule_handler
        for param in self.control_params:
    TypeError: 'NoneType' object is not iterable
`

### Steps to reproduce the problem

1. Place the positive/negative prompt
2. Activate the control net
3. Put the image
4. Choose the type of control
5. Choose the preprocessor
6. Choose the model
7. Press the generate button

### What should have happened?

Generate the image without error messages

### Commit where the problem happens

webui: https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/57727e554d8f87b4cf438390d6cb05a27d1734f5
controlnet: https://github.com/Mikubill/sd-webui-controlnet/commit/2091b6fb21d9c76becb2a8860c8d2975ad3e428a

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
--xformers --skip-python-version-check --skip-install --update-all-extensions --disable-nan-check --xformers-flash-attention --log-startup --disable-safe-unpickle --enable-insecure-extension-access
```

### List of enabled extensions

![Captura de tela_22-3-2024_211530_127 0 0 1](https://github.com/Mikubill/sd-webui-controlnet/assets/45890502/3db74fde-a0a4-4595-a1b7-0f09564923e1)

### Console logs

```Shell
https://pastebin.com/7qDH0tpq
```

**Comment by sipie800** [comment]
same here, it begin to buzz right recently updating

**Comment by huchenlei** [comment]
Bug confirmed.
