### ISSUE TITLE
Is there any parameter can adjust it's controlling strength?

### ISSUE THREAD

**Issue by butaixianran** [Mikubill/sd-webui-controlnet#27]
Hi, greate tool, but there is one problem.

When source image is a 2D image and use a realistic model to generate target image,  it copied everything from that 2D image, which makes output image not realistic anymore. More like a 3D rendering result.  

Even I choose openpose as control net's model, still has this issue. Character's eyes are too big, mouth size is unrealistic, hair is super big. All those 2D image's feature, comes to the result, even with openpose.

So, is there a way to add a parameter to control its strength?

Thanks

**Comment by Mikubill** [comment]
How about changing the `Weight`?

**Comment by butaixianran** [comment]
Sorry, my bad
