### ISSUE TITLE
[Bug]: densepose (pruple bg & purple torso) issue (SD 1.5)

### ISSUE THREAD

**Issue by Reshaflame** [Mikubill/sd-webui-controlnet#2712]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Generating image with Controlnet openpose 'densepose (pruple bg & purple torso)' as preprocessor generates messed up poses in txt2img (img2img with denoising strength of 0.75 and below keeps thing "ok")

### Steps to reproduce the problem

1. use standard txt2img process (512X512, o	sampling steps: 20, CFG Scale: 7, o	Sampling method: DPM++ 2M Karras, batches count: 4, batches size: 1)
2. Use Controlnet default values, choose openpose
3. choose densepose (pruple bg & purple torso) as preprocessor
4. use same size image as output (512X512) with a clear person with a clear pose
5. generate images.
6. images generated are in different pose from the source image. a purple densepose map did generated correctly.

### What should have happened?

a 512X512 purple densepose map should be generated and images generated should have the same pose as the densepose map generated by the preprocessor.

### Commit where the problem happens

webui: AUTOMATIC1111
controlnet: 1.1.442

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--xformers --autolaunch --api
```

### List of enabled extensions

LDSR 
Lora 
ScuNET
SwinIR
canvas-zoom-and-pan 
extra-options-section 
hypertile
mobile
prompt-bracket-checker 
soft-inpainting 
Auto-Photoshop-StableDiffusion-Plugin
Stable-Diffusion-Webui-Civitai-Helper
adetailer
multidiffusion-upscaler-for-automatic1111
openOutpaint-webUI-extension
sd-webui-controlnet
sd-webui-reactor
sd-webui-stablesr
sdwebui-close-confirmation-dialogue
ultimate-upscale-for-automatic1111

### Console logs

```Shell
2024-03-30 19:42:05,691 - ControlNet - INFO - unit_separate = False, style_align = False 64/64 [00:29<00:00,  3.30it/s]
2024-03-30 19:42:05,748 - ControlNet - INFO - Loading model from cache: control_v11p_sd15_openpose [cab727d4]
2024-03-30 19:42:05,750 - ControlNet - INFO - Using preprocessor: densepose
2024-03-30 19:42:05,751 - ControlNet - INFO - preprocessor resolution = 512
2024-03-30 19:42:07,951 - ControlNet - INFO - ControlNet Hooked - Time = 2.263814687728882
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:08<00:00,  2.34it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:09<00:00,  2.15it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:13<00:00,  1.43it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:13<00:00,  1.51it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 80/80 [00:48<00:00,  1.64it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 80/80 [00:48<00:00,  2.30it/s]
```

**Comment by huchenlei** [comment]
You are using wrong controlnet model. Please follow instruction in https://github.com/Mikubill/sd-webui-controlnet/pull/2314 to download densepose controlnet model.
