### ISSUE TITLE
[Bug]: animal_openpose txt2img on SD 1.5 not working as intended

### ISSUE THREAD

**Issue by Reshaflame** [Mikubill/sd-webui-controlnet#2713]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

generating images of a dog using only controlnet animal_openpose and a text prompt doesn't generate the expected results

### Steps to reproduce the problem

1. use standard txt2img process (512X512, o sampling steps: 20, CFG Scale: 7, o Sampling method: DPM++ 2M Karras, batches count: 4, batches size: 1)
2. Use Controlnet default values, choose openpose
3. choose animal_openpose as preprocessor
4. use same size image as output (512X512) with a clear dog with a clear pose
5. generate images.
6. images generated are in different pose from the source image. an openpose map did generated correctly.

### What should have happened?

Generated images should have been of dogs with a pose similar to the source image/openpose map.

### Commit where the problem happens

webui: AUTOMATIC1111
controlnet: 1.1.442

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--xformers --autolaunch --api
```

### List of enabled extensions

LDSR
Lora
ScuNET
SwinIR
canvas-zoom-and-pan 
extra-options-section 
hypertile
mobile
prompt-bracket-checker 
soft-inpainting 
Auto-Photoshop-StableDiffusion-Plugin
Stable-Diffusion-Webui-Civitai-Helper
adetailer
multidiffusion-upscaler-for-automatic1111
openOutpaint-webUI-extension
sd-webui-controlnet
sd-webui-reactor
sd-webui-stablesr
sdwebui-close-confirmation-dialogue
ultimate-upscale-for-automatic1111

### Console logs

```Shell
2024-03-30 19:51:37,696 - ControlNet - INFO - unit_separate = False, style_align = False 80/80 [00:48<00:00,  2.30it/s]
2024-03-30 19:51:37,760 - ControlNet - INFO - Loading model from cache: control_v11p_sd15_openpose [cab727d4]
2024-03-30 19:51:37,761 - ControlNet - INFO - Using preprocessor: animal_openpose
2024-03-30 19:51:37,762 - ControlNet - INFO - preprocessor resolution = 512
2024-03-30 19:51:37,824 - ControlNet - INFO - ControlNet Hooked - Time = 0.13504433631896973
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:13<00:00,  1.53it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:13<00:00,  1.50it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:13<00:00,  1.50it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:13<00:00,  1.50it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 80/80 [00:52<00:00,  1.52it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 80/80 [00:52<00:00,  2.34it/s]
```

### Additional information

![tmpa8b881ny](https://github.com/Mikubill/sd-webui-controlnet/assets/102427924/388da6d7-4e05-412b-b977-fd08ad787172)
![grid-0043](https://github.com/Mikubill/sd-webui-controlnet/assets/102427924/f9f054c8-13d3-4bf7-800f-fe6169b0d37e)
![2024-03-30_14-56-25](https://github.com/Mikubill/sd-webui-controlnet/assets/102427924/21fa6d26-7d37-43cb-bf9f-c5228c0c0f87)

A black dog posing for a picture in a garden
Negative prompt: (monochrome:1.3), (deformed, distorted, disfigured:1.3), tattoo, wet, water, shadow, 3d render, cartoon, ((blurry)), duplicate, ((duplicate body parts)), (disfigured), (poorly drawn), ((missing limbs)), logo, signature, text, words, low res, boring, artifacts, bad art, gross, ugly, poor quality, low quality, poorly drawn, bad anatomy, wrong anatomy
Steps: 20, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 405761530, Size: 512x512, Model hash: 879db523c3, Model: dreamshaper_8, ControlNet 0: "Module: animal_openpose, Model: control_v11p_sd15_openpose [cab727d4], Weight: 1, Resize Mode: Crop and Resize, Low Vram: False, Processor Res: 512, Guidance Start: 0, Guidance End: 1, Pixel Perfect: False, Control Mode: Balanced, Hr Option: Both, Save Detected Map: True", Version: v1.7.0-528-gbef51aed

**Comment by huchenlei** [comment]
Based on `2024-03-30 19:51:37,760 - ControlNet - INFO - Loading model from cache: control_v11p_sd15_openpose [cab727d4]`, you are using wrong model. Please follow https://github.com/Mikubill/sd-webui-controlnet/discussions/2351 to download correct controlnet model for animal pose.
