### ISSUE TITLE
Bug: Progress API doesn't work with ControlNet requests

### ISSUE THREAD

**Issue by brennanerbz** [Mikubill/sd-webui-controlnet#273]
How can we use the progress API from 1111 with ControlNet?

**Comment by brennanerbz** [comment]
Is there anyway to not lock the queue during the img2img request? That's preventing the progress API from getting hit

**Comment by brennanerbz** [comment]
@Mikubill is there a way to have non-blocking API methods?

**Comment by ljleb** [comment]
@brennanerbz can you verify that this is still the case? now the api is using the original routes from the webui, it shouldn't be a problem anymore IIUC.
