### ISSUE TITLE
KeyError: 'ip-adapter-auto'

### ISSUE THREAD

**Issue by thejohnd0e** [Mikubill/sd-webui-controlnet#2733]
![Screenshot - 2024-04-04 12 49 47](https://github.com/Mikubill/sd-webui-controlnet/assets/115493464/33a4c35c-ded9-41ac-8149-0708295bb549)

**Comment by huchenlei** [comment]
ip-adapter-auto is only for actual generation when model is picked, as it decided which preprocessor to use based on model.
