### ISSUE TITLE
[Request]: New API Endpoint - Post Control Type to Get Filtered Data

### ISSUE THREAD

**Issue by altoiddealer** [Mikubill/sd-webui-controlnet#2737]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

## As of this writing, the ControlNet API endpoints are few and barely helpful.

<img width="1259" alt="Screenshot 2024-04-09 200854" src="https://github.com/Mikubill/sd-webui-controlnet/assets/1613484/5e9a203c-cc45-4f71-a579-92d05cb04fd3">

### POST Detect is probably the most useful, and I don't have any use for it.

- You can get a model list, likely a crap ton of them.
- You can get the module list, again likely a crap ton of them.
....The thought of filtering these lists on the user end is absurd.

## The ControlNet script has those amazing functions for filtering the data in the UI, based simply on "Control Type" and checking the current SD Model.

# It would be super duper awesome to be able to get a dictionary response containing all that filtered data via API request!!

<img width="683" alt="Screenshot 2024-04-09 201914" src="https://github.com/Mikubill/sd-webui-controlnet/assets/1613484/51b46194-fdb2-414f-9015-d0491e42ed8d">

# Glorious filtered data... I want you so badly via API

### Steps to reproduce the problem

- Create a script that uses SD WebUI via API
- Add ControlNet integrations
- Cry

### What should have happened?

An API endpoint to get that juicy filtered data would be freakin' sweet.

### Commit where the problem happens

webui: Current
controlnet: Current

### Command Line Arguments

```Shell
No
```

### List of enabled extensions

ControlNet

### Console logs

```Shell
None required
```

**Comment by huchenlei** [comment]
We already have `/controlnet/control_types` API endpoint to return the filtered preprocessor/models.

`models` are futher filtered by the active SD version. You can obtain SD version from existing A1111 API.

Revelant code:
https://github.com/Mikubill/sd-webui-controlnet/blob/22f63dc2dca25a26bb4ad183ffe5c41406c702fc/scripts/api.py#L70-L92

**Comment by altoiddealer** [comment]
> We already have `/controlnet/control_types` API endpoint to return the filtered preprocessor/models.
> 
> `models` are futher filtered by the active SD version. You can obtain SD version from existing A1111 API.
> 
> Revelant code:
> 
> https://github.com/Mikubill/sd-webui-controlnet/blob/22f63dc2dca25a26bb4ad183ffe5c41406c702fc/scripts/api.py#L70-L92

At first I thought you were pulling my leg, but you are 100% correct.  Hot damn that is amazing!

This is a **colossal** blunder by [sd-webui-forge](https://github.com/lllyasviel/stable-diffusion-webui-forge) - I made this report because I thought ControlNet lacked such an API endpoint.

...Wrong!  Only Forge is missing it.  SMH.

This is immensely useful.  Such a shame that Forge doesn't have it.

**Comment by altoiddealer** [comment]
@huchenlei proud to say, I actually made this happen.

I consider myself a bottom tier coder, but a crap ton of guess-and-check and asking ChatGPT for help.

Now, hopefully Forge merges this.
