### ISSUE TITLE
[Question] Is there any way to save all ControlNet generated images to a directory?

### ISSUE THREAD

**Issue by NAKAN0M** [Mikubill/sd-webui-controlnet#2739]
I am trying to create a depth map of a video, and I am using its frames as input (around 17,000 images/frames). The images saved is all img2img generated(?) ones, and none of my depth maps were saved.

Are there is any options or way I can save the images?
Sorry if something doesn't make sense. I am very new to this field. Feel free to ask anything you need to solve this issue.

※In the image I uploaded, I want to save the black and white depth map images, but only the coloured ones were saved.
![タイトルなし](https://github.com/Mikubill/sd-webui-controlnet/assets/128028118/4d5423a7-3bc6-40b0-bee3-255164340dc7)

**Comment by huchenlei** [comment]
You should be able to find detected maps under `stable-diffusion-webui\outputs\img2img-images\detected_maps\depth\{date}`

**Comment by NAKAN0M** [comment]
Unfortunately, the file did not exist under the "img2img-images" folder. Are these files saved as soon as the depthmaps are generated? I did not do anything after the process ended, so perhaps I have missed some process to save these files?

**Comment by huchenlei** [comment]
Hmmm. I am not sure whether following code will execute under batch. Need to verify. I am not very familiar about how batch works in A1111.

https://github.com/Mikubill/sd-webui-controlnet/blob/a99998141673129a59cbc4de9628667666c2cb5e/scripts/controlnet.py#L1286-L1294

**Comment by NAKAN0M** [comment]
FYI, I am using the release package from https://github.com/AUTOMATIC1111/stable-diffusion-webui#installation-on-windows-1011-with-nvidia-gpus-using-release-package . I hope this information helps. 
Also, I had to use this version because in other versions the batch process itself did not work in my environment, and this was the only way I could make it process multiply files. Therefore, I cannot verify if this problem exists in other versions in my environment.

**Comment by w-e-w** [comment]
I think you can just use these two extentions by light-and-ray
Video in Extras tab https://github.com/light-and-ray/sd-webui-video-extras-tab
ControlNet Preprocessor in extras tab https://github.com/light-and-ray/sd-webui-cn-in-extras-tab

**Comment by NAKAN0M** [comment]
> I think you can just use these two extentions by light-and-ray Video in Extras tab https://github.com/light-and-ray/sd-webui-video-extras-tab ControlNet Preprocessor in extras tab https://github.com/light-and-ray/sd-webui-cn-in-extras-tab

Thank you, will give it a try.

> btw are those cows?

They are gnus!

**Comment by NAKAN0M** [comment]
It worked! It’s lovely to be able to directly input videos, but I wish we don’t have to install a package to do that :P
