### ISSUE TITLE
[Feature Request]: Controlnet random select file from directory

### ISSUE THREAD

**Issue by obs945** [Mikubill/sd-webui-controlnet#2740]
Originally Controlnet can load images from directory but can only batch process whole the images in the directory.
Hope there is a function made Controlnet randomly load image from directory and process.

Proposed workflow
1. Enable Controlnet
2. Select Random Load Tab
3. Choose Input Directory
4. Input random load processing times (Default= 1)

**Comment by huchenlei** [comment]
Please use the API to gain this level of control. Thanks.
https://github.com/Mikubill/sd-webui-controlnet/wiki/API
