### ISSUE TITLE
Openpose editor not working

### ISSUE THREAD

**Issue by ema7569** [Mikubill/sd-webui-controlnet#2742]
a1111 v1.8, sd1.5, windows 10, nvidia 1070,
I tested to edit a pose but the button edit show just an empty windows. After I installed openpose editor https://github.com/fkunn1326/openpose-editor.git, restarted, ect... And it's the same result: The edit button show an empty window.

![Screenshot 2024-04-12 at 21-28-27 Stable Diffusion](https://github.com/Mikubill/sd-webui-controlnet/assets/39129290/fc2f32e5-e3a9-44ef-bdca-45e6ba04bef3)

**Comment by huchenlei** [comment]
Can you attach your browser console log? The embedded openpose editor is this extension: https://github.com/huchenlei/sd-webui-openpose-editor. However, if you don't have the extension installed, we will try to load remote hosted here: https://huchenlei.github.io/sd-webui-openpose-editor/ by default.

**Comment by Alex-Afin** [comment]
v1.8, sd1.5, windows 10, nvidia 1070,
I also stopped displaying the open pose editor. The error in the console is this:

Error loading script: main.py
    Traceback (most recent call last):
      File "H:\stable-diffusion-webui-master\modules\scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "H:\stable-diffusion-webui-master\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "H:\stable-diffusion-webui-master\extensions\openpose-editor\scripts\main.py", line 12, in <module>
        from basicsr.utils.download_util import load_file_from_url
    ModuleNotFoundError: No module named 'basicsr'

**Comment by huchenlei** [comment]
Please attach browser console log, not the server console log. Thanks! You can inspect browser console log by pressing F12.   https://github.com/fkunn1326/openpose-editor.git is not the integrated editor, so the error it reports in server console is not the cause for your issue.

**Comment by Alex-Afin** [comment]
Your extension has appeared in the tab. But it still doesn't work. Having inactive buttons. I am attaching a screenshot. 
![13-58-52](https://github.com/Mikubill/sd-webui-controlnet/assets/167197696/26525057-cf26-46d9-ac76-c0559ef0edad)

**Comment by huchenlei** [comment]
> Your extension has appeared in the tab. But it still doesn't work. Having inactive buttons. I am attaching a screenshot. ![13-58-52](https://private-user-images.githubusercontent.com/167197696/323192942-26525057-cf26-46d9-ac76-c0559ef0edad.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNTU4OTEsIm5iZiI6MTcxMzM1NTU5MSwicGF0aCI6Ii8xNjcxOTc2OTYvMzIzMTkyOTQyLTI2NTI1MDU3LWNmMjYtNDZkOS1hYzc2LWMwNTU5ZWYwZWRhZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QxMjA2MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZTU4NWI3M2JjYTc4NDc2MjA3ODM5NmEwZDk5ODVjZjNjN2QxNTI4NGM4NjA3ZTRhNzUwYjUwODNlY2ZmYjQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3ZVtiVG2ViRrAaTu_ZZ7T-8BYOM1GiR2izbGhNwyqZE)

this is not the extension I own.
