### ISSUE TITLE
[Question]How the Multi-Controlnet is implemented？

### ISSUE THREAD

**Issue by THEZ1015** [Mikubill/sd-webui-controlnet#2743]
I'm learning the principles of the ControlNet, and I can't find the relevant papers and explanations when I learn the Multi-ControlNet. Because I'm a beginner, I don't know much about the code, so I would like to ask you what part of the code of the Multi-ControlNet is in, or if there is an article explaining the principle of it.

![1e199a7a00eacad00e3a8bf261a830db](https://github.com/Mikubill/sd-webui-controlnet/assets/161303173/93be6900-4a09-422f-9ca6-17443921a4bc)

**Comment by huchenlei** [comment]
The related code is:
https://github.com/Mikubill/sd-webui-controlnet/blob/a99998141673129a59cbc4de9628667666c2cb5e/scripts/hook.py#L796-L800

Outputs of multiple units are added together to decoder's output blocks' output.

**Comment by THEZ1015** [comment]
Thanks for your answer！
