### ISSUE TITLE
[DevTask] Port preprocessor structure from SD Forge

### ISSUE THREAD

**Issue by huchenlei** [Mikubill/sd-webui-controlnet#2748]
[SD Forge](https://github.com/lllyasviel/stable-diffusion-webui-forge) introduces a new way of managing preprocessors. We probably want to port the changes here to make future development easier.

**Comment by zzzhengqi** [comment]
Could you please instruct me on how to make Anyline appear in the controlnet interface within Forge? After downloading the MTEED.pth file, which folder should I store it in, and how should I properly name this file? If there is a page that provides these instructions, please direct me to it.
