### ISSUE TITLE
[Bug]: Not possible to load Instant_ID models

### ISSUE THREAD

**Issue by HonZuna** [Mikubill/sd-webui-controlnet#2750]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Hello i struggle with loading Instand_ID models in ControlNet (AUTOMATIC1111).

Every time press "Generate" with CN and selected control type "Instant_ID" it show message like this while generating ("Error running process: .... controlnet.py"):

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/14128510/02c56b77-2b0a-4bc0-802b-4ea19b3d4524)
Unit1
![Snímek obrazovky 2024-04-15 182335](https://github.com/Mikubill/sd-webui-controlnet/assets/14128510/9583dbee-45b7-4639-a3c4-fcb623267ed2)
Unit2
![Snímek obrazovky 2024-04-15 182348](https://github.com/Mikubill/sd-webui-controlnet/assets/14128510/b1ae74a3-3d9c-4a51-a0ce-4bf515632a8b)

### Steps to reproduce the problem

1. Download Instant_ID models from here https://github.com/Mikubill/sd-webui-controlnet/discussions/2589
2. Place them in to the "AUTOMATIC1111\models\ControlNet"
3. Select 2 unites with Instant_ID
4. Get errors

### What should have happened?

Pass action

### Commit where the problem happens

webui: 
controlnet: 
instant_id:

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
set COMMANDLINE_ARGS=--xformers (currently with --controlnet-loglevel DEBUG)
```

### List of enabled extensions

AA_sd-webui-ar_xhox | https://github.com/xhoxye/sd-webui-ar_xhox.git | main | 4c11b19e | 2024-03-15 13:36:11 | unknown
AC_sd-webui-reactor | https://github.com/Gourieff/sd-webui-reactor.git | main | ae571499 | 2024-03-15 11:20:38 | unknown
StyleSelectorXL | https://github.com/ahgsql/StyleSelectorXL.git | main | d538b0c4 | 2024-01-17 22:41:01 | unknown
ZZ_sd-extension-nudenet | https://github.com/vladmandic/sd-extension-nudenet | main | bf5d1b98 | 2024-01-29 13:50:28 | unknown
sd-webui-controlnet | https://github.com/Mikubill/sd-webui-controlnet.git | main | eb451a00 | 2024-04-01 05:54:20 | unknown
sd-webui-openpose-editor | https://github.com/huchenlei/sd-webui-openpose-editor.git | main | cebe13e0 | 2023-12-19 04:58:26 | unknown
ultimate-upscale-for-automatic1111 | https://github.com/Coyote-A/ultimate-upscale-for-automatic1111.git | master | 2322caa4 | 2024-03-08 17:55:37 | unknown

### Console logs

```Shell
*** Error running process: E:\AUTOMATIC1111\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "E:\AUTOMATIC1111\modules\scripts.py", line 825, in process
        script.process(p, *script_args)
      File "E:\AUTOMATIC1111\extensions\sd-webui-controlnet\scripts\utils.py", line 96, in wrapper
        result = func(*args, **kwargs)
      File "E:\AUTOMATIC1111\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1245, in process
        self.controlnet_hack(p)
      File "E:\AUTOMATIC1111\extensions\sd-webui-controlnet\scripts\utils.py", line 96, in wrapper
        result = func(*args, **kwargs)
      File "E:\AUTOMATIC1111\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1230, in controlnet_hack
        self.controlnet_main_entry(p)
      File "E:\AUTOMATIC1111\extensions\sd-webui-controlnet\scripts\utils.py", line 96, in wrapper
        result = func(*args, **kwargs)
      File "E:\AUTOMATIC1111\extensions\sd-webui-controlnet\scripts\controlnet.py", line 849, in controlnet_main_entry
        self.enabled_units = Script.get_enabled_units(p)
      File "E:\AUTOMATIC1111\extensions\sd-webui-controlnet\scripts\utils.py", line 96, in wrapper
        result = func(*args, **kwargs)
      File "E:\AUTOMATIC1111\extensions\sd-webui-controlnet\scripts\controlnet.py", line 570, in get_enabled_units
        local_unit.module = IPAdapterPreset.match_model(local_unit.model).module
      File "E:\AUTOMATIC1111\extensions\sd-webui-controlnet\scripts\ipadapter\presets.py", line 19, in match_model
        return _preset_by_model[model_name]
    KeyError: 'None'
```

### Additional information

It seems running normaly on ComfyUI. I have Windows 11, RTX 3090, Cuda 11.8, GeForce driver 552.12. I am ussing AUTO1111 version 1.9.

**Comment by huchenlei** [comment]
Please attach full console logs.

The code in question is
https://github.com/Mikubill/sd-webui-controlnet/blob/8af7577c45394209dd6bf024c6ebf09e990c2809/scripts/controlnet.py#L568-L571

In theory, if you choose `instant_id_face_embedding` as preprocessor, the `IPAdapterPreset.match_model` line should not execute.

**Comment by huchenlei** [comment]
Can you clear the setting in ControlNet Unit2 [IPAdapter]? It might be that unit causing the issue.

**Comment by HonZuna** [comment]
Thank you, it truly did change things on its own in Unit2.
