### ISSUE TITLE
[Bug]: New update broke Ending Control Step

### ISSUE THREAD

**Issue by guzuligo** [Mikubill/sd-webui-controlnet#2755]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Ending Control step no longer works as expected. You can only use it once, and then it will no longer work.

I thin even starting control step has the same issue.

### Steps to reproduce the problem

1. Use any controlnet and put ending control step to any low value
2. Press generate. It will work as expected.
3. Press generate again. It will fail.
4. Press generate again and it will always fail again.
5. Disable the controlNet and press generate. Re-enable the controlnet and generate again. It will work.
6. Press generate again, it will fail again.

### What should have happened?

Ending control step should stop the controlnet no matter how many times I generate without the need of disable and re-enable.

### Commit where the problem happens

webui: [v1.9.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases/tag/v1.9.0)
controlnet: [bbcae309](https://github.com/Mikubill/sd-webui-controlnet/commit/bbcae309d1c0921c212bfb9719169db8826b795f)

### Command Line Arguments

```Shell
--xformers
```

### List of enabled extensions

--

### Console logs

```Shell
2024-04-17 01:55:46,721 - ControlNet - INFO - unit_separate = False, style_align = False
2024-04-17 01:55:46,722 - ControlNet - INFO - Loading model from cache: control_lora_rank128_v11f1e_sd15_tile_fp16 [d258993f]
2024-04-17 01:55:46,732 - ControlNet - INFO - Using preprocessor: tile_resample
2024-04-17 01:55:46,733 - ControlNet - INFO - preprocessor resolution = -1
2024-04-17 01:55:46,756 - ControlNet - INFO - ControlNet Hooked - Time = 0.037999629974365234
```

**Comment by huchenlei** [comment]
Duplicate https://github.com/Mikubill/sd-webui-controlnet/issues/2752
