### ISSUE TITLE
I found a small bug

### ISSUE THREAD

**Issue by GrapHY427** [Mikubill/sd-webui-controlnet#276]
I tried to install this extension, when I tried to activate openpose model ,it automatically downloads two .pth file,. Usually it works well, but when the download process interrupt unexpectedly, the undownloaded .pth files still exist in the directory,which prevent program from redownloading the undownloaded file. When I try to figure out why it doesn't work properly, I found an ''if'' statement can cause this problem, where it is loacted at line 30 at ''sd-webui-controlnet\annotator\openpose\__init__.py''

```
  if not os.path.exists(hand_modelpath):
              from basicsr.utils.download_util import load_file_from_url
              load_file_from_url(body_model_path, model_dir=modeldir)
              load_file_from_url(hand_model_path, model_dir=modeldir)
```

if hand_model download successfully but body_model didn't download successfully,this if statement will cause program error, to avid this problem, I separate this if statement to avoid this problem.

```
if not os.path.exists(hand_modelpath):
            from basicsr.utils.download_util import load_file_from_url
            load_file_from_url(hand_model_path, model_dir=modeldir)

if not os.path.exists(body_model_path):
    from basicsr.utils.download_util import load_file_from_url
    load_file_from_url(body_model_path, model_dir=modeldir)
```

I modify this code as follows because I use cellular network to download this .pth file.which can be expensive. Ijust want to let the code work properly.  Maybe you have other ways to avoid this problem. I hope this could help other people.

**Comment by Mikubill** [comment]
Fixed in the latest commit
