### ISSUE TITLE
[Bug]: Using IP Adapter XL with Ending Step <0.9 it doesn's work anymore 

### ISSUE THREAD

**Issue by INTstinkt** [Mikubill/sd-webui-controlnet#2772]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

So after updating ControlNet today to use the new features i found that if you try using no matter what ip adapter xl model  while setting the Ending Step below 0.9 it just kind of stop working. In Consol i get no Error or anything 

### Steps to reproduce the problem

1. Go to .... Controlnet 
2. Press ....Preprocessor : ip-adapter-auto   Model: Literally every Model    Everything else default except Ending Control Step <0.9    Weight Typ: Normal 
3. Generate

### What should have happened?

Output should Use IP Adapter till the specific ending step instead of not working at all 

### Commit where the problem happens

webui: version: [v1.9.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/adadb4e3c7382bf3e4f7519126cd6c70f4f8557b)  •  python: 3.10.11  •  torch: 2.1.2+cu121  •  xformers: 0.0.23.post1  •  gradio: 3.41.2  •  checkpoint: [c9e3e68f89](https://google.com/search?q=c9e3e68f89b8e38689e1097d4be4573cf308de4e3fd044c64ca697bdb4aa8bca)
controlnet: V1.1.445

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--xformers
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/133846628/9333a0be-8664-4d5b-8a10-0d54277c0864)

### Console logs

```Shell
To create a public link, set `share=True` in `launch()`.
Startup time: 32.5s (prepare environment: 11.7s, import torch: 3.0s, import gradio: 1.0s, setup paths: 4.8s, initialize shared: 0.2s, other imports: 0.5s, load scripts: 5.5s, create ui: 5.1s, gradio launch: 0.6s).
2024-04-21 06:56:36,249 - ControlNet - INFO - unit_separate = False, style_align = False
2024-04-21 06:56:36,543 - ControlNet - INFO - Loading model: ip-adapter-faceid-plusv2_sdxl [187cb962]
2024-04-21 06:56:36,821 - ControlNet - INFO - Loaded state_dict from [C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\models\ip-adapter-faceid-plusv2_sdxl.bin]
2024-04-21 06:56:39,176 - ControlNet - INFO - ControlNet model ip-adapter-faceid-plusv2_sdxl [187cb962](ControlModelType.IPAdapter) loaded.
2024-04-21 06:56:39,177 - ControlNet - INFO - using mask
2024-04-21 06:56:39,181 - ControlNet - INFO - Using preprocessor: ip-adapter-auto
2024-04-21 06:56:39,181 - ControlNet - INFO - preprocessor resolution = 512
2024-04-21 06:56:39,182 - ControlNet - INFO - ip-adapter-auto => ip-adapter_face_id_plus
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads\insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads\insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads\insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads\insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads\insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
2024-04-21 06:56:46,408 - ControlNet - INFO - ControlNet Hooked - Time = 10.16440486907959
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:14<00:00,  1.36it/s]
postprocess_batch00%|██████████████████████████████████████████████████████████████████| 20/20 [00:12<00:00,  1.59it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:12<00:00,  1.54it/s]
2024-04-21 06:57:14,988 - ControlNet - INFO - unit_separate = False, style_align = False 20/20 [00:12<00:00,  1.59it/s]
2024-04-21 06:57:14,988 - ControlNet - INFO - Loading model from cache: ip-adapter-faceid-plusv2_sdxl [187cb962]
2024-04-21 06:57:14,988 - ControlNet - INFO - using mask
2024-04-21 06:57:14,990 - ControlNet - INFO - Using preprocessor: ip-adapter-auto
2024-04-21 06:57:14,990 - ControlNet - INFO - preprocessor resolution = 512
2024-04-21 06:57:15,276 - ControlNet - INFO - ControlNet Hooked - Time = 0.2940239906311035
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:11<00:00,  1.74it/s]
postprocess_batch00%|██████████████████████████████████████████████████████████████████| 20/20 [00:11<00:00,  1.71it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:12<00:00,  1.63it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:12<00:00,  1.71it/s]
```

### Additional information

Example Using FaceID V2XL but basically goes for every IPAdapter model
First Picture with Endingstep 0.9
Second Picture with Endingstep 0.89    (I blacked out random NSFW stuff) 
![00008-3650980302](https://github.com/Mikubill/sd-webui-controlnet/assets/133846628/f6f9224e-8fd9-4352-a384-a2038d65b73a)
![00009-3650980302](https://github.com/Mikubill/sd-webui-controlnet/assets/133846628/cdba1fab-3555-43b4-8163-dfb8392f0d06)

Model Used :Juggernaut XLv9
Sampler : DPM++SDE karras  20 steps
CFG 2

**Comment by INTstinkt** [comment]
Forgot Input Picture for Reference 
![file (4)](https://github.com/Mikubill/sd-webui-controlnet/assets/133846628/1e5f9998-3fa2-4878-a158-c83682ee11f5)

**Comment by huchenlei** [comment]
Issue confirmed reproducable.

**Comment by huchenlei** [comment]
I believe it is caused by upstream change described in https://github.com/Mikubill/sd-webui-controlnet/issues/2752. You can checkout A1111 dev branch that includes this PR https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/15533 to solve this issue.
