### ISSUE TITLE
HELP!  Script 'controlnet' not found

### ISSUE THREAD

**Issue by Macon-WEI** [Mikubill/sd-webui-controlnet#2776]
I've deployed the stable diffusion webui on a cloud server and I'm attempting to use it in API mode. I'm currently able to successfully use its text2img service. However, when I include the controlnet parameter in the body of the POST request, it doesn't work. I've downloaded the controlnet model file and placed it in \extensions\sd-webui-controlnet\models, then initiated a POST request using apifox. Here's the response:
{
    "error": "HTTPException",
    "detail": "Script 'controlnet' not found",
    "body": "",
    "errors": ""
}

**Comment by Macon-WEI** [comment]
It will fill when i include param "alwayson_scripts" in my post body, but success without it.

**Comment by huchenlei** [comment]
Please see https://github.com/Mikubill/sd-webui-controlnet/wiki/API and https://github.com/Mikubill/sd-webui-controlnet/blob/main/example/txt2img_example/api_txt2img.py for API usage examples.

**Comment by Macon-WEI** [comment]
I followed the example in text2img.py to make requests to my server. When I don't use the alwayson_scripts parameter, I can successfully receive images from the server. However, adding the alwayson_scripts parameter leads to the error I mentioned. Regarding the external code API, I'm a bit confused. Should I first run the code under "Create ControlNet Arguments"? Is this error occurring because I haven't yet installed my controlnet into the diffusion service? If so, does this mean I need to execute run_extension_installer in stable-diffusion-webui/modules/launch_utils.py?
