### ISSUE TITLE
You've made a critical typo

### ISSUE THREAD

**Issue by Ichimikichiki** [Mikubill/sd-webui-controlnet#2787]
sd-webui-controlnet/scripts/batch_hijack.py

Line 25:
```py
             if ad_params and ad_params.enable:
```
**Should be**
```py
            if ad_params and ad_params.enabled:
```
Line 47:
```py
             if ad_params and ad_params.enable:
```
**Should be**
```py
             if ad_params and ad_params.enabled:
```

**Comment by huchenlei** [comment]
Code was introduced by #2661

**Comment by continue-revolution** [comment]
this is NOT a typo but should be like this because my repo names this paramter as `enable` instead of `enabled` and I won't change it.

**Comment by Ichimikichiki** [comment]
> this is NOT a typo but should be like this because my repo sd-webu-animatediff names this paramter as `enable` instead of `enabled` and I won't change it.

Up to you. It breaks the entire stable-diffusion-webui even with your sd-webui-animatediff disabled.

**Comment by continue-revolution** [comment]
If you make such claim, you need to attach the whole terminal log. I never meet such issue.
