### ISSUE TITLE
Couldn't make extract_controlnet models work

### ISSUE THREAD

**Issue by Meghpal** [Mikubill/sd-webui-controlnet#279]
In the README
**Use `extract_controlnet.py` to extract controlnet from original `.pth` file.**

I want to understand what the **original** `.pth` file means? Is it just any regular SD model? If so, can it be applied to `.ckpt` as well?

**Comment by Mikubill** [comment]
`extract_controlnet.py` could only applies to controlnet checkpoints.
checkout https://github.com/Mikubill/sd-webui-controlnet#extraction and https://github.com/Mikubill/sd-webui-controlnet/issues/73#issuecomment-1437011581 for difference

**Comment by Meghpal** [comment]
Okay I think I am more clear now, I want to ask if there is any script that does:

```
My_model.control_model.weights 
= SD15.control_model.weights + My_model.model.diffusion_model.weights - SD15.model.diffusion_model.weights
```

as discussed in the other thread? Or is it the default way for inference to add the difference `SD15.control_model.weights - SD15.model.diffusion_model.weights` to the main SD model weights selected on the top?
