### ISSUE TITLE
IPadpater 1.1.445 Issue in Stable Diffusion 1.5

### ISSUE THREAD

**Issue by hrz009** [Mikubill/sd-webui-controlnet#2796]
I'm using Stable Diffusion 1.5 and after this update, ip adapter is not working.  All the pics generated from ipadapter are just green blurry images in Stable Diffusion 1.5. The advance control weight setting is not compatible with SD 1.5 . Also the setting of Control Mode is missing. Kindly fix this

**Comment by huchenlei** [comment]
Please use bug template to file bug and include all necessary information such as screenshot and reproduction steps.
