### ISSUE TITLE
[feature request]will it support 2.1_768model？

### ISSUE THREAD

**Issue by gdx09090909** [Mikubill/sd-webui-controlnet#28]
i trained some lora on 2.1, wonder if there is an opportunity for thie extension to cooperate with 2.1?

**Comment by ClashSAN** [comment]
@gdx09090909 fyi, you could write: [feature request] next to your title.
this is so that the developer does not feel like they have to answer many questions on their repo and become tired.

**Comment by jav12z** [comment]
I'm wondering the same, but I don't know if it is a limitation of the extension or a limitation of the desing of controlnet.

**Comment by cerarslan** [comment]
Any progress? I find this one but idk how can be implement. https://github.com/lllyasviel/ControlNet/commit/2a4424c1c0623d76592d2ef2f486c3de487ef4b5

**Comment by prometx11** [comment]
For SD2.1 to work, one has to train a new controlnet model with a SD2.1 base model. 
Some people are already doing this, but it takes a long time and you need a pretty big dataset. 
I saw an openpose controlnet model for 2.1 already here: https://huggingface.co/alfredplpl/ControlNetForSD2
its not perfect but it definitely works with sd 2.1
