### ISSUE TITLE
Update Broken

### ISSUE THREAD

**Issue by AbyszOne** [Mikubill/sd-webui-controlnet#282]
I've tried multiple controlnets, but all models launch the same image (even with only one enabled). Also, it does not create a map and throws that error in the console. Wait a few hours to update, but still the same problem.

ControlNet model control_hed-fp16 [13fee50b] loaded.
Error running process: J:\A1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "J:\A1111\stable-diffusion-webui\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "J:\A1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 508, in process
    model_net.reset()
  File "J:\A1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'PlugableControlModel' object has no attribute 'reset'

**Comment by Mikubill** [comment]
The latest update requires fully restart of WebUI

**Comment by AbyszOne** [comment]
> The latest update requires fully restart of WebUI

Great. It's working fine for now. As an initial idea, I think that eventually there will be a need for an individual "presence" parameter for each layer. I mean, all the controlnets are mixed with the same intensity, and that makes it difficult to make flexible compositions. Each layer should be able to regulate how much is applied to the mix, in addition to the weight and guide values.

**Comment by AbyszOne** [comment]
I have noticed that the weight works as a presence selector when layers are activated. This is very useful, but it also takes away the original function of the parameter. I don't know if it is intentional, or a natural effect of the program, but it would be interesting to have both functions, if possible. 👍

**Comment by Mikubill** [comment]
Currently weights calculate independently from every ControlNet. 
It's simply `Net1 * [Layer Weight] + Net2 * [Layer Weight]`.

**Comment by AbyszOne** [comment]
Yes, I got it now, I created my own confusion by trying too many combinations of parameters and extensions. Weight works perfect as is.👍
