### ISSUE TITLE
cannot write mode RGBA as JPEG 

### ISSUE THREAD

**Issue by huanggou666** [Mikubill/sd-webui-controlnet#283]
![Snipaste_2023-02-22_17-28-22](https://user-images.githubusercontent.com/123738707/220578779-832be78d-9d0e-4882-afbe-3c8a1327647e.png)
when try to do batch with controlnet, this happened,
    raise OSError(msg) from e
OSError: cannot write mode RGBA as JPEG

**Comment by Meghpal** [comment]
Could this be a problem with the base Stable Diffusion WebUI img2img? Does it happen if controlnet is not enabled?

There was an [issue](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/7642) in stable diffusion related to this which was [fixed 3 days ago](https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/7650). You could try updating your repo and retrying.
