### ISSUE TITLE
[DevTask] Port PuLID

### ISSUE THREAD

**Issue by huchenlei** [Mikubill/sd-webui-controlnet#2835]
https://github.com/ToTheBeginning/PuLID

**Comment by 3blackbar** [comment]
I think this one works better than instantid on a face, gets likeness better, cant wait to see it working

**Comment by huchenlei** [comment]
> I think this one works better than instantid on a face, gets likeness better, cant wait to see it working, huggingface demo surprised me.. ok tried some more, its kinda on par, some photos work better, some ok

Considering PuLID is essentially pure ipadapter guided, while instant-id uses both ipadapter and controlnet, I think PuLID is still better as it consumes less vram.
