### ISSUE TITLE
[Bug]: presets disapeared

### ISSUE THREAD

**Issue by light-and-ray** [Mikubill/sd-webui-controlnet#2864]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

There are no presets in the last version of the extension :(

![Screenshot 2024-05-08 at 00-04-33 Stable Diffusion](https://github.com/Mikubill/sd-webui-controlnet/assets/33491867/33cca243-b522-4790-8d3d-f1ebe41bf320)

**Comment by huchenlei** [comment]
See https://github.com/Mikubill/sd-webui-controlnet/discussions/2854. There are other WebUI state extensions that does the job of saving workflow out there that you can migrate to.
