### ISSUE TITLE
ADetailer xyz plot issue with 1.1.448

### ISSUE THREAD

**Issue by Surran-Peng** [Mikubill/sd-webui-controlnet#2871]
something wrong with 1.1.448

the mode "adetailer + controlnet + x/y/z plot" worked fine before v447. but now it generates difference images after the second image.

example:
step 1:Use "controlnet + x/y/z plot" to find the sets of Steps and CFG value.
step 2:Add "adetailer" to get a good image. Except for the first image, the others will be different. not the one found by step 1.

_Originally posted by @Surran-Peng in https://github.com/Mikubill/sd-webui-controlnet/discussions/2854#discussioncomment-9353493_

**Comment by huchenlei** [comment]
Issue confirmed reproducable.
![xyz_grid-0003-3966258177](https://github.com/Mikubill/sd-webui-controlnet/assets/20929282/5121fe73-879e-4c36-b3da-3666d069766d)

**Comment by huchenlei** [comment]
Log messages:
```
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                | 18/20 [00:01<00:00, 12.76it/s]D:\stable-diffusion-webui\modules\sd_samplers_common.py:68: RuntimeWarning: invalid value encountered in cast                                                                | 37/100 [00:07<00:06,  9.92it/s] 
  x_sample = x_sample.astype(np.uint8)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 12.30it/s]
D:\stable-diffusion-webui\modules\processing.py:1020: RuntimeWarning: invalid value encountered in cast                                                                     | 39/100 [00:07<00:06,  9.62it/s]
  x_sample = x_sample.astype(np.uint8)
```
