### ISSUE TITLE
Feature Request: Region Mask for Multi-Inputs

### ISSUE THREAD

**Issue by AviceProjects** [Mikubill/sd-webui-controlnet#2872]
I would like to see the "Effective Region Mask" available for Multi-Inputs as well.

**Comment by huchenlei** [comment]
I think it is already useable for Multi-inputs just a bit counter intuitive. You set the effective region mask in single input, and switch to multi-inputs to upload images.

I will work on a patch that makes effective region mask always appear.

For now you can follow these steps:
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/20929282/2a98a0b7-7b17-49f5-b170-62443479f54e)
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/20929282/d803b014-79c9-4b2a-9544-daaf30ed9cd4)
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/20929282/065fc444-9d2a-4418-b663-82c9e516b8a8)
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/20929282/dd45921b-2400-4dfd-95e4-b0bca1741e44)
