### ISSUE TITLE
ValueError: "ControlNetUnit" object has no field "batch_modifiers"

### ISSUE THREAD

**Issue by light-and-ray** [Mikubill/sd-webui-controlnet#2876]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Another one. Two to be more precise. I decided to find them all, and there are 2 fields:

```python
    batch_modifiers: list = []
    batch_image_files: list = []
```

With them AD works again. But I'm not sure are they only used for AD comparability. There are regular controlnet batch and multi input features, I didn't test them, maybe they use them too

**Comment by huchenlei** [comment]
It is annoying that people directly add attribute on ControlNetUnit instead of extending the class in a more proper way. 🙃 I am going to quick fix this for now.
