### ISSUE TITLE
Ask about the understanding of Weight Type

### ISSUE THREAD

**Issue by D-Mad** [Mikubill/sd-webui-controlnet#2883]
I don't understand the Weight Type and Weights in controlnet, can someone explain it to me?
![Screenshot 2024-05-12 073815](https://github.com/Mikubill/sd-webui-controlnet/assets/8207507/098d72b6-40cf-4b09-b024-7e7ec0bc335a)

**Comment by huchenlei** [comment]
See https://github.com/Mikubill/sd-webui-controlnet/discussions/2770
