### ISSUE TITLE
[Bug]: Batch mode skip half of the images

### ISSUE THREAD

**Issue by fastjhone0** [Mikubill/sd-webui-controlnet#2886]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

 if 1 one was taken 2nd one skip then 3rd one take and 4th one skip and goes on

### Steps to reproduce the problem

try batch with 10 images and only 5 will produce

### What should have happened?

generate all 1o images

### Commit where the problem happens

webui: 
controlnet: 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
no
```

### List of enabled extensions

no

### Console logs

```Shell
no
```

**Comment by huchenlei** [comment]
Please provide detailed reproduction steps including screenshots. Thanks!

**Comment by fastjhone0** [comment]
***         [119, 109, 114],
***         [119, 109, 114],
***         ...,
***         [ 97,  91,  90],
***         [ 97,  91,  90],
***         [ 97,  91,  90]],
***
***        [[119, 109, 114],
***         [119, 109, 114],
***         [119, 109, 114],
***         ...,
***         [ 97,  91,  90],
***         [ 97,  91,  90],
***         [ 97,  91,  90]],
***
***        [[119, 109, 114],
***         [119, 109, 114],
***         [119, 109, 114],
***         ...,
***         [ 97,  91,  90],
***         [ 97,  91,  90],
***         [ 97,  91,  90]],
***
***        ...,
***
***        [[132,  95,  60],
***         [132,  95,  60],
***         [132,  95,  60],
***         ...,
***         [118,  80,  50],
***         [118,  80,  50],
***         [118,  80,  50]],
***
***        [[130,  92,  58],
***         [130,  92,  58],
***         [130,  92,  58],
***         ...,
***         [117,  79,  49],
***         [117,  79,  49],
***         [117,  79,  49]],
***
***        [[130,  92,  58],
***         [130,  92,  58],
***         [130,  92,  58],
***         ...,
***         [117,  79,  49],
***         [117,  79,  49],
***         [117,  79,  49]]], dtype=uint8), 'mask': array([[[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        ...,
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]]], dtype=uint8)}, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, low_vram=False, processor_res=512, threshold_a=0.5, threshold_b=0.5, guidance_start=0.0, guidance_end=1.0, pixel_perfect=True, control_mode=<ControlMode.PROMPT: 'My prompt is more important'>, inpaint_crop_input_image=False, hr_option=<HiResFixOption.BOTH: 'Both'>, save_detected_map=True, advanced_weighting=None, effective_region_mask=None, pulid_mode=<PuLIDMode.FIDELITY: 'Fidelity'>, ipadapter_input=None, mask=None, batch_mask_dir=None, animatediff_batch=False, batch_modifiers=[], batch_image_files=[]), False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, False, False, False, 0, False, None, None, False, None, None, False, None, None, False, None, None, False, None, None, False, 50) {}
    Traceback (most recent call last):
      File "E:\SD\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "E:\SD\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "E:\SD\stable-diffusion-webui\modules\txt2img.py", line 109, in txt2img
        processed = processing.process_images(p)
      File "E:\SD\stable-diffusion-webui\modules\processing.py", line 845, in process_images
        res = process_images_inner(p)
      File "E:\SD\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 66, in processing_process_images_hijack
        processed = self.process_images_cn_batch(p, *args, **kwargs)
      File "E:\SD\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 87, in process_images_cn_batch
        self.dispatch_callbacks(self.process_batch_each_callbacks, p)
      File "E:\SD\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 179, in dispatch_callbacks
        callback(*args)
      File "E:\SD\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1307, in batch_tab_process_each
        unit.image = next(unit.batch_images)
    StopIteration

---

**Comment by fastjhone0** [comment]
i just put input my images folder to Input Directory and it works but the thing is after new update only produce half of it. i tried with the old version again and it works, at the end of it it shows that error too. its like it generate 1 image and skip the next one and goes on
sorry for my bad explanation

**Comment by heckles** [comment]
> i just put input my images folder to Input Directory and it works but the thing is after new update only produce half of it. i tried with the old version again and it works, at the end of it it shows that error too. its like it generate 1 image and skip the next one and goes on sorry for my bad explanation

the same problem happened for me too

**Comment by fastjhone0** [comment]
> > i just put input my images folder to Input Directory and it works but the thing is after new update only produce half of it. i tried with the old version again and it works, at the end of it it shows that error too. its like it generate 1 image and skip the next one and goes on sorry for my bad explanation
> 
> the same problem happened for me too

currently i am using old version hope it fixed its just with the most recent ones, try like week or 2 old ones

**Comment by wicherek1** [comment]
I have the same problem. From an input of 263 images, I have 85 images as output.

**Comment by huchenlei** [comment]
Please provide detailed reproduction steps with screenshots.

I need at least the screenshot of
- Your input directory
- Which input box in the UI you pass the input directory string to
- How ControlNet unit is configured

**Comment by fastjhone0** [comment]
> I have the same problem. From an input of 263 images, I have 85 images as output. How did you downgrade the version to the older one?

i manually downloaded the zip file of old commit file then extract and put it in the extension folder then put models in to that folder

**Comment by fastjhone0** [comment]
> Please provide detailed reproduction steps with screenshots.
> 
> I need at least the screenshot of
> 
> * Your input directory
> * Which input box in the UI you pass the input directory string to
> * How ControlNet unit is configured

![Opera Snapshot_2024-05-19_205447_127 0 0 1](https://github.com/Mikubill/sd-webui-controlnet/assets/67064592/7a6d9fe8-84e5-46a8-81bd-c40379db049d)

i put input here

**Comment by fastjhone0** [comment]
> > Please provide detailed reproduction steps with screenshots.
> > I need at least the screenshot of
> > 
> > * Your input directory
> > * Which input box in the UI you pass the input directory string to
> > * How ControlNet unit is configured
> 
> ![Opera Snapshot_2024-05-19_205447_127 0 0 1](https://private-user-images.githubusercontent.com/67064592/331882227-7a6d9fe8-84e5-46a8-81bd-c40379db049d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMzI2ODYsIm5iZiI6MTcxNjEzMjM4NiwicGF0aCI6Ii82NzA2NDU5Mi8zMzE4ODIyMjctN2E2ZDlmZTgtODRlNS00NmE4LTgxYmQtYzQwMzc5ZGIwNDlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDE1MjYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5OTE4ZjcyY2QwOWRjYmQ0YWI3YjdjMTIzZWQ5ZWY2N2I0NzZmYWYyMDFjNDVlYWM1NjVmMDdmOTFjNmU0NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a5K1iE-P-j1ISLSFzyRI4stEZybr7M8ZsUAvA9IcPqc)
> 
> i put input here

then its generate half it skips 1 then generate next then skip 1 then generate next one goes on it just generate half of it and gets a error at the end


*** [119, 109, 114],
*** [119, 109, 114],
*** ...,
*** [ 97, 91, 90],
*** [ 97, 91, 90],
*** [ 97, 91, 90]],

*** [[119, 109, 114],
*** [119, 109, 114],
*** [119, 109, 114],
*** ...,
*** [ 97, 91, 90],
*** [ 97, 91, 90],
*** [ 97, 91, 90]],

*** [[119, 109, 114],
*** [119, 109, 114],
*** [119, 109, 114],
*** ...,
*** [ 97, 91, 90],
*** [ 97, 91, 90],
*** [ 97, 91, 90]],

*** ...,

*** [[132, 95, 60],
*** [132, 95, 60],
*** [132, 95, 60],
*** ...,
*** [118, 80, 50],
*** [118, 80, 50],
*** [118, 80, 50]],

*** [[130, 92, 58],
*** [130, 92, 58],
*** [130, 92, 58],
*** ...,
*** [117, 79, 49],
*** [117, 79, 49],
*** [117, 79, 49]],

*** [[130, 92, 58],
*** [130, 92, 58],
*** [130, 92, 58],
*** ...,
*** [117, 79, 49],
*** [117, 79, 49],
*** [117, 79, 49]]], dtype=uint8), 'mask': array([[[0, 0, 0],
*** [0, 0, 0],
*** [0, 0, 0],
*** ...,
*** [0, 0, 0],
*** [0, 0, 0],
*** [0, 0, 0]],

*** [[0, 0, 0],
*** [0, 0, 0],
*** [0, 0, 0],
*** ...,
*** [0, 0, 0],
*** [0, 0, 0],
*** [0, 0, 0]],

*** [[0, 0, 0],
*** [0, 0, 0],
*** [0, 0, 0],
*** ...,
*** [0, 0, 0],
*** [0, 0, 0],
*** [0, 0, 0]],

*** ...,

*** [[0, 0, 0],
*** [0, 0, 0],
*** [0, 0, 0],
*** ...,
*** [0, 0, 0],
*** [0, 0, 0],
*** [0, 0, 0]],

*** [[0, 0, 0],
*** [0, 0, 0],
*** [0, 0, 0],
*** ...,
*** [0, 0, 0],
*** [0, 0, 0],
*** [0, 0, 0]],

*** [[0, 0, 0],
*** [0, 0, 0],
*** [0, 0, 0],
*** ...,
*** [0, 0, 0],
*** [0, 0, 0],
*** [0, 0, 0]]], dtype=uint8)}, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, low_vram=False, processor_res=512, threshold_a=0.5, threshold_b=0.5, guidance_start=0.0, guidance_end=1.0, pixel_perfect=True, control_mode=<ControlMode.PROMPT: 'My prompt is more important'>, inpaint_crop_input_image=False, hr_option=<HiResFixOption.BOTH: 'Both'>, save_detected_map=True, advanced_weighting=None, effective_region_mask=None, pulid_mode=<PuLIDMode.FIDELITY: 'Fidelity'>, ipadapter_input=None, mask=None, batch_mask_dir=None, animatediff_batch=False, batch_modifiers=[], batch_image_files=[]), False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, False, False, False, 0, False, None, None, False, None, None, False, None, None, False, None, None, False, None, None, False, 50) {}
Traceback (most recent call last):
File "E:\SD\stable-diffusion-webui\modules\call_queue.py", line 57, in f
res = list(func(*args, **kwargs))
File "E:\SD\stable-diffusion-webui\modules\call_queue.py", line 36, in f
res = func(*args, **kwargs)
File "E:\SD\stable-diffusion-webui\modules\txt2img.py", line 109, in txt2img
processed = processing.process_images(p)
File "E:\SD\stable-diffusion-webui\modules\processing.py", line 845, in process_images
res = process_images_inner(p)
File "E:\SD\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 66, in processing_process_images_hijack
processed = self.process_images_cn_batch(p, *args, **kwargs)
File "E:\SD\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 87, in process_images_cn_batch
self.dispatch_callbacks(self.process_batch_each_callbacks, p)
File "E:\SD\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 179, in dispatch_callbacks
callback(*args)
File "E:\SD\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1307, in batch_tab_process_each
unit.image = next(unit.batch_images)
StopIteration
