### ISSUE TITLE
The model is affected by factors that are not subject to the photo

### ISSUE THREAD

**Issue by richadlee** [Mikubill/sd-webui-controlnet#289]
If I cut out the character and the background is white, then the picture that runs out is also without background or a very simple background, and will not run according to prompt, this situation will appear when I use hed, depth, canny, normalmap models, and if I use openpose, it will not be affected by other factors in the photo.
I don't know if this is normal, because I see examples in readme documents running out the same result, which is affected by the non-subject factor of the photo. But actually I want these models to run according to my prompt
![(I) ~%P1V) ECAU3NFE1V6B](https://user-images.githubusercontent.com/31947064/220647327-27d1c900-2720-4c7d-8505-d3914d364644.png)

**Comment by Mikubill** [comment]
you might need to reduce the weight or/and guidance strength

**Comment by richadlee** [comment]
> you might need to reduce the weight or/and guidance strength

I want the result to draw the person according to the outline of the character read by Controlnet, so that it maintains a specific posture, but the details outside the outline are determined by the prompt, and if I lower the weight or guidence strength, the final character pose may be deformed

**Comment by AbyszOne** [comment]
Are you using "diff_control" models or "control" models? Have you tried also the "transfer control" option in settings.

**Comment by fappaz** [comment]
If you're using the same picture in both the ControlNet and img2img panels, you should increase the denoising strength (at least 0.51) while keeping the ControlNet weight close to 1.

Another option is to use a different picture in img2img (e.g.: edit the original with different colors), given that it will affect the colors and structure of the output.

**Comment by richadlee** [comment]
> 

Im using control Pre-extracted control models.
Where to find the option transfer control, I did not find it in the controlnet tab in the settings。

**Comment by richadlee** [comment]
> Are you using "diff_control" models or "control" models? Have you tried also the "transfer control" option in settings.

Im using control Pre-extracted control models.
Where to find the option transfer control, I did not find it in the controlnet tab in the settings。

**Comment by richadlee** [comment]
> > Are you using "diff_control" models or "control" models? Have you tried also the "transfer control" option in settings.
> 
> Im using Pre-extracted control models. Where to find the option "transfer control", I did not find it in the controlnet tab in the settings。

**Comment by Mikubill** [comment]
Just an idea, you can try combine multiple controlnet (such as character + background, etc) and see if things change.

**Comment by richadlee** [comment]
> If you're using the same picture in both the ControlNet and img2img panels, you should increase the denoising strength (at least 0.51) while keeping the ControlNet weight close to 1.
> 
> Another option is to use a different picture in img2img (e.g.: edit the original with different colors), given that it will affect the colors and structure of the output.

When using ControlNet, I usually employ text2img. Would the output differ if I use img2img or continue using text2img?

**Comment by richadlee** [comment]
> Just an idea, you can try combine multiple controlnet (such as character + background, etc) and see if things change.

Thanks for the new feature. I'll give it a try later.

**Comment by fappaz** [comment]
> > If you're using the same picture in both the ControlNet and img2img panels, you should increase the denoising strength (at least 0.51) while keeping the ControlNet weight close to 1.
> > Another option is to use a different picture in img2img (e.g.: edit the original with different colors), given that it will affect the colors and structure of the output.
> 
> When using ControlNet, I usually employ text2img. Would the output differ if I use img2img or continue using text2img?

I haven't compared it myself, but would assume that yes it will differ, because with img2img you have an image to use as a color reference, which is what you're trying to achieve.
