### ISSUE TITLE
How do you extract face embeddings?

### ISSUE THREAD

**Issue by alexblattner** [Mikubill/sd-webui-controlnet#2895]
Hello, it seems that you do a more convoluted preprocessing than showed here: https://huggingface.co/h94/IP-Adapter-FaceID

Would you mind explaining why you don't crop the face image as much? How does the image embedding extraction work exactly?

thank you in advance

**Comment by alexblattner** [comment]
@huchenlei I am not complaining, I am asking for the difference with the official implementation. Your implementation gives better results for some reason

**Comment by huchenlei** [comment]
BTW, the insightface preprocessor logic is very simple. It just call into insightface and nothing more.
https://github.com/Mikubill/sd-webui-controlnet/blob/e338a861dc4b4087db001c7fee8e1b0f916e0c3b/scripts/preprocessor/legacy/processor.py#L691-L696

**Comment by huchenlei** [comment]
Do you think it would be helpful if we return the detected face image as preprocessor detected image in generation result? Currently we are just attaching the original image for most preprocessors that returns tensor.

**Comment by alexblattner** [comment]
@huchenlei thank you very much. It is the exact same preprocessing in the official implementation. I'll see what's different between implementations
