### ISSUE TITLE
help!!!,Error running process: extensions\sd-webui-controlnet\scripts\controlnet.py

### ISSUE THREAD

**Issue by knight753951** [Mikubill/sd-webui-controlnet#291]
Loading model: control_openpose-fp16 [9ca67cc5]
Loaded state_dict from [D:\AIpainting\stable-diffusion-webui_23-02-17\extensions\sd-webui-controlnet\models\control_openpose-fp16.safetensors]
Error running process: D:\AIpainting\stable-diffusion-webui_23-02-17\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "D:\AIpainting\stable-diffusion-webui_23-02-17\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "D:\AIpainting\stable-diffusion-webui_23-02-17\extensions\sd-webui-controlnet\scripts\controlnet.py", line 506, in process
    else self.build_control_model(p, unet, model, lowvram)
  File "D:\AIpainting\stable-diffusion-webui_23-02-17\extensions\sd-webui-controlnet\scripts\controlnet.py", line 414, in build_control_model
    network = network_module(
  File "D:\AIpainting\stable-diffusion-webui_23-02-17\extensions\sd-webui-controlnet\scripts\cldm.py", line 63, in __init__
    config = OmegaConf.load(config_path)
  File "D:\AIpainting\stable-diffusion-webui_23-02-17\python\lib\site-packages\omegaconf\omegaconf.py", line 187, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\NewSD2\\stable-diffusion-webui_23-01-23\\extensions\\sd-webui-controlnet\\models\\cldm_v15.yaml'

**Comment by Mikubill** [comment]
Check that the configuration file "cldm_v15.yaml" is present in the directory "D:\AIpainting\stable-diffusion-webui_23-02-17\extensions\sd-webui-controlnet\models". If it is not there, you may need to locate it or obtain it from https://github.com/Mikubill/sd-webui-controlnet/raw/main/models/cldm_v15.yaml

**Comment by knight753951** [comment]
I have Checked and "cldm_v15.yaml" is present in the directory "D:\AIpainting\stable-diffusion-webui_23-02-17\extensions\sd-webui-controlnet\models"
but Error running process: D:\AIpainting\stable-diffusion-webui_23-02-17\extensions\sd-webui-controlnet\scripts\controlnet.py still

**Comment by knight753951** [comment]
> Check that the configuration file "cldm_v15.yaml" is present in the directory "D:\AIpainting\stable-diffusion-webui_23-02-17\extensions\sd-webui-controlnet\models". If it is not there, you may need to locate it or obtain it from https://github.com/Mikubill/sd-webui-controlnet/raw/main/models/cldm_v15.yaml

and I haved download controlnet twice, but error still

**Comment by knight753951** [comment]
i change control_net_model_config, the problem is over

**Comment by liangjiaying** [comment]
> 
  File "C:\tools\ai\stable-diffusion-webui-master\venv\lib\site-packages\omegaconf\omegaconf.py", line 187, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\WorkSpace\\stable-diffusion-webui-master\\extensions\\sd-webui-controlnet\\models\\cldm_v15.yaml'
我这里也是，我电脑只有C盘不可能有F盘，我不知道怎么改路径，你试试能不能改

**Comment by russell-shu** [comment]
您的来信已经收到啦，祝生活愉快~

**Comment by 210000o** [comment]
@liangjiaying 不知道你有没有解决，但以防有其他人问还是详细说一下：在Stable Diffusion网站的设置里找到ControlNet，将其中的Config file for Control Net models改成你的cldm_v15.yaml路径。
In Stable Diffusion [Setting], find ControlNet, change [Config file for Control Net models] to your [cldm_v15.yaml] path.

**Comment by liangjiaying** [comment]
> 

感谢

**Comment by russell-shu** [comment]
您的来信已经收到啦，祝生活愉快~
