### ISSUE TITLE
ip-adapter_face_id  not working

### ISSUE THREAD

**Issue by Victoryship** [Mikubill/sd-webui-controlnet#2913]
# What happened?
After I downloaded and installed it, nothing worked. no error found.
![企业微信截图_17161725921245](https://github.com/Mikubill/sd-webui-controlnet/assets/19524632/8bf470fc-d978-411f-b647-1949f6e83bb6)

![企业微信截图_17161730926007](https://github.com/Mikubill/sd-webui-controlnet/assets/19524632/d56e823c-493e-4b89-8ea4-c11ffd60e0b2)

```
1girl,<lora:ip-adapter-faceid-plusv2_sd15_lora:0.6>
Steps: 20, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 3215997870, Size: 512x512, Model: GSMaleto, VAE: vae-ft-mse-840000-ema-pruned.safetensors, Clip skip: 2, ControlNet 0: "Module: ip-adapter_face_id_plus, Model: ip-adapter-faceid-plusv2_sd15 [6e14fc1a], Weight: 1.0, Resize Mode: Crop and Resize, Processor Res: 512, Threshold A: 0.5, Threshold B: 0.5, Guidance Start: 0.0, Guidance End: 1.0, Pixel Perfect: False, Control Mode: Balanced", Version: v1.6.0-2-g4afaaf8a
```

# What should have happened?
The face reference pictures I put up should work, like these pictures

![企业微信截图_17117004207979](https://github.com/Mikubill/sd-webui-controlnet/assets/19524632/7449b470-695b-4150-888a-003135bc8314)

# Commit where the problem happens
OS: ubuntu
webui: [v1.6.0-2-g4afaaf8a](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/4afaaf8a020c1df457bcf7250cb1c7f609699fa7)
controlnet: v1.1.448

# List of enabled extensions
![企业微信截图_17161726374785](https://github.com/Mikubill/sd-webui-controlnet/assets/19524632/d74b8ef0-7473-43eb-aaa4-ecca16a453c3)

# Console logs
```
Version: v1.6.0-2-g4afaaf8a
Commit hash: 4afaaf8a020c1df457bcf7250cb1c7f609699fa7
Launching Web UI with arguments: --listen --api --api-log --xformers --no-hashing --no-half-vae --port 7860 --skip-torch-cuda-test --disable-console-progressbars --enable-console-prompts
[-] ADetailer: Failed to load model 'face_yolov8n.pt' from huggingface
[-] ADetailer initialized. version: 23.11.0, num models: 8
ControlNet preprocessor location: /data/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
2024-05-20 10:26:25,686 - ControlNet - INFO - ControlNet v1.1.448
Loading weights [None] from /data/stable-diffusion-webui/models/Stable-diffusion/animics_v12.safetensors
2024-05-20 10:26:26,398 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 18.0s (prepare environment: 0.3s, import torch: 2.8s, import gradio: 0.7s, setup paths: 1.2s, initialize shared: 0.1s, other imports: 0.5s, load scripts: 11.2s, create ui: 0.6s, gradio launch: 0.4s).
Creating model from config: /data/stable-diffusion-webui/configs/v1-inference.yaml
Loading VAE weights specified in settings: /data/stable-diffusion-webui/models/VAE/vae-ft-mse-840000-ema-pruned.safetensors
Applying attention optimization: xformers... done.
Model loaded in 4.8s (load weights from disk: 1.2s, create model: 0.5s, apply weights to model: 2.6s, load VAE: 0.1s, calculate empty prompt: 0.4s).

txt2img: 1girl,<lora:ip-adapter-faceid-plusv2_sd15_lora:0.6>
2024-05-20 10:28:13,157 - ControlNet - INFO - unit_separate = False, style_align = False
2024-05-20 10:28:13,398 - ControlNet - INFO - Loading model: ip-adapter-faceid-plusv2_sd15 [6e14fc1a]
2024-05-20 10:28:13,505 - ControlNet - INFO - Loaded state_dict from [/data/stable-diffusion-webui/models/ControlNet/ip-adapter-faceid-plusv2_sd15.bin]
2024-05-20 10:28:14,062 - ControlNet - INFO - ControlNet model ip-adapter-faceid-plusv2_sd15 [6e14fc1a](ControlModelType.IPAdapter) loaded.
2024-05-20 10:28:14,079 - ControlNet - INFO - Using preprocessor: ip-adapter_face_id_plus
2024-05-20 10:28:14,079 - ControlNet - INFO - preprocessor resolution = 512
Reusing loaded model animics_v12.safetensors to load GSMaleto.safetensors
Loading weights [None] from /data/stable-diffusion-webui/models/Stable-diffusion/GSMaleto.safetensors
Loading VAE weights specified in settings: /data/stable-diffusion-webui/models/VAE/vae-ft-mse-840000-ema-pruned.safetensors
Applying attention optimization: xformers... done.
Weights loaded in 14.4s (send model to cpu: 2.0s, load weights from disk: 0.7s, apply weights to model: 11.0s, move model to device: 0.7s).
```

**Comment by Victoryship** [comment]
https://github.com/Mikubill/sd-webui-controlnet/discussions/2442

**Comment by huchenlei** [comment]
You probably want to update your A1111. 1.6 is a very old version.

**Comment by Victoryship** [comment]
> You probably want to update your A1111. 1.6 is a very old version.

I found where the problem occurs and it has nothing to do with A1111. 1.6 version. I found that the `buffalo_l` folder in the `stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads/insightface/models` directory is empty and the `buffalo_l.zip` file in this directory is only 55MB.

So I re-downloaded this file from `https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip`. And put it in the `stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads/insightface/models` directory and extract it to the `buffalo_l` folder in the current directory. like this
![企业微信截图_17162577399941](https://github.com/Mikubill/sd-webui-controlnet/assets/19524632/8df8104c-b06e-44d5-b8f5-362e437e61c0)

 and it works

**Comment by Victoryship** [comment]
> > You probably want to update your A1111. 1.6 is a very old version.
> 
> I found where the problem occurs and it has nothing to do with A1111. 1.6 version. I found that the `buffalo_l` folder in the `stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads/insightface/models` directory is empty and the `buffalo_l.zip` file in this directory is only 55MB.
> 
> So I re-downloaded this file from `https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip`. And put it in the `stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads/insightface/models` directory and extract it to the `buffalo_l` folder in the current directory. like this ![企业微信截图_17162577399941](https://private-user-images.githubusercontent.com/19524632/332254214-8df8104c-b06e-44d5-b8f5-362e437e61c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNTgwNTUsIm5iZiI6MTcxNjI1Nzc1NSwicGF0aCI6Ii8xOTUyNDYzMi8zMzIyNTQyMTQtOGRmODEwNGMtYjA2ZS00NGQ1LWI4ZjUtMzYyZTQzN2U2MWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDAyMTU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5NzEyM2UxNjIwZTc3NGYyMGI0NWI1OTdkNzQ0ZGJiMDUzZjY3NjdiMzJhMjlkYTk3MmMyMGYyODVjYTMyODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HR1PkB2WMGni_2yt0i3EZ9x5SYTPF

**Comment by Victoryship** [comment]
> You probably want to update your A1111. 1.6 is a very old version.

If key files are missing like this one, can you add some error messages?
