### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by qingweng123** [Mikubill/sd-webui-controlnet#2916]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

The webui controlnet plugin's masked upload feature is not working at all, or rather it's working in a strange way.<img width="1064" alt="屏幕截图 2024-05-20 162436" src="https://github.com/Mikubill/sd-webui-controlnet/assets/170290821/25df7006-0772-4dfe-b806-5860509db933"><img width="1025" alt="屏幕截图 2024-05-20 162950" src="https://github.com/Mikubill/sd-webui-controlnet/assets/170290821/3b64f516-dd05-47e1-9f29-27fd62a650cc">
First of all, the text of the raw image controlnet inpaint (local repaint) no matter how you upload the black and white mask, it does not work, that is, the black area does not block the effect of inpaint, the white area does not work the effect of inpaint, and even in the generation of the result is not a black and white mask, either black and white mask to play the shape of the control and so on.
<img width="1004" alt="屏幕截图 2024-05-20 163316" src="https://github.com/Mikubill/sd-webui-controlnet/assets/170290821/939dd0a6-8418-47f9-8e31-2bd4e3fc09fa">
The forge webui has no problem uploading masks, but the normal webui doesn't work at all!

### Steps to reproduce the problem

First upload the image in the control net inpanint tab and upload a black and white mask with the same resolution, check the perfect pixel, upload the size size, select the inpaint only preprocessor with the corresponding model, and directly generate the image

### What should have happened?

.

### Commit where the problem happens

webui: 
controlnet: 

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
.
```

### List of enabled extensions

.

### Console logs

```Shell
.
```

**Comment by huchenlei** [comment]
See pinned issue: https://github.com/Mikubill/sd-webui-controlnet/issues/2829.

Mask upload feature is replaced by effective region mask to align with behaviour in SD Forge.

**Comment by khanhvp2k** [comment]
> See pinned issue: #2829.
> 
> Mask upload feature is replaced by effective region mask to align with behaviour in SD Forge.

then how can I use my mask image in Inpaint controlnet?
