### ISSUE TITLE
deforum not decting the controlnet

### ISSUE THREAD

**Issue by ShubhanshuJain** [Mikubill/sd-webui-controlnet#2917]
controlnet is not working, i have installed the controlnet but it is not enabling 
![Screenshot 2024-05-20 191351](https://github.com/Mikubill/sd-webui-controlnet/assets/98007637/ef3f6b75-f4de-4a54-a0df-def559744fe8)
![Screenshot 2024-05-20 191404](https://github.com/Mikubill/sd-webui-controlnet/assets/98007637/669a5051-c8d4-4e27-8eb1-599421b02503)
i tried reinstalling but still not working

**Comment by huchenlei** [comment]
Please file the issue in deforum repo.
