### ISSUE TITLE
controlNet disables itself after running inpainting and img2img - AttributeError: 'NoneType' object has no attribute 'convert'

### ISSUE THREAD

**Issue by Chaciej** [Mikubill/sd-webui-controlnet#292]
How to recreate:

Go to img2img tab => load your image and any controlNet model (you can type some prompt too) and check "enable"

Click "generate" and wait

Click send to inpaint and check "only masked" => then use inpainting on some fragment, click generate

After you get the result click on "send to img2img"

Try to generate again => boom, you got error and from this time onwards controlNet has no influence on your images until you restart everything

![2023-02-22 14_42_01-](https://user-images.githubusercontent.com/18661408/220652558-ff59699f-0947-47e7-b22d-644bab94dfa0.png)

**Comment by Mikubill** [comment]
fixed in https://github.com/Mikubill/sd-webui-controlnet/commit/06dd9934d6cba5e48a047652a3f3fb3fe7852423
