### ISSUE TITLE
[Bug]: Segmentation generated behavior not as expected

### ISSUE THREAD

**Issue by alexknows** [Mikubill/sd-webui-controlnet#2932]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I recently came across [OlivioTutorials](https://www.youtube.com/watch?v=8wpn7UO3FSk) video on ControlNet's segmentation, but it seems that the generated images is not adhering to it.

Steps:

1. I generated the map in the ControlNet's section.
2. I Downloaded map and made a few small tweaks in Photoshop. (e.g to remove a piece of wall and an object)
3. I replaced the original with the map.
4. I added the prompts and adjusted all the settings accordingly.
5. The image it generates has no similarity what so ever to the map I provided in ControlNet.

It seems as if ControlNet is not even enabled (but it is). No errors are thrown.

### Steps to reproduce the problem

1. I generated the map in the ControlNet's section using an image of a bathroom.
2. I Downloaded map and made a few small tweaks in Photoshop. (e.g to remove a piece of wall and an object)
3. I replaced the original with the map.
4. I added the prompts and adjusted all the settings accordingly.
5. The image it generates has no similarity what so ever to the map I provided in ControlNet.

First, I added the image to controlnet:
![herringbone-floor-bathroon-2](https://github.com/Mikubill/sd-webui-controlnet/assets/6269334/4de81500-fda8-41f0-bb67-c9dbb3915d8e)

I generated the following map:
![orginal-map](https://github.com/Mikubill/sd-webui-controlnet/assets/6269334/34cfe0fe-8892-4621-8a37-9f56e167dad0)

I saved the map and made minor tweaks to it in photoshop:
![segmentation-ad-bathroom](https://github.com/Mikubill/sd-webui-controlnet/assets/6269334/265133e5-e955-4c41-a28c-66f5d6ccc8f5)

I added the prompt: 
RAW photo, a modern bathroom with a tub, sink, toilet,  center area with a wooden two-tone flooring tile, a jigsaw puzzle style flooring, isometric view, (high detailed), 8k uhd, high quality

Negative prompt
semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, duplicates

Adjusted all the controls: 
<img width="1608" alt="Screenshot 2024-05-24 at 8 28 46 PM" src="https://github.com/Mikubill/sd-webui-controlnet/assets/6269334/8b8d7f89-ab4b-477f-8217-e7ccb1b92995">

As you can see in the above screenshot the generated image does not match at all the map in the ControlNet.

### What should have happened?

Generated image should match the map. 

### Commit where the problem happens

webui: 
controlnet: 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### List of enabled extensions

<img width="1140" alt="Screenshot 2024-05-24 at 8 38 37 PM" src="https://github.com/Mikubill/sd-webui-controlnet/assets/6269334/66be1733-a97f-456b-b4a0-89cfb104878d">

### Console logs

```Shell
NA
```

**Comment by huchenlei** [comment]
See https://github.com/Mikubill/sd-webui-controlnet/discussions/2931
