### ISSUE TITLE
Canvas does not display manually drawn lines

### ISSUE THREAD

**Issue by CooperCorona** [Mikubill/sd-webui-controlnet#2946]
When clicking Open New Canvas > Create Canvas, the drawings on the canvas doesn't actually appear. It's stored on the backend correctly, because ControlNet will properly reflect the lineart, and running the preprocessor will display it. But you can't actually see it in the canvas, which makes the canvas impossible to use effectively.

I tested this on Google Chrome Version 125.0.6422.141 on Ubuntu 24.04. Running commit bb3c2a9bf7329c7d39e7b8b85a606cd5d567e57a of sd-webui-controlnet.

![A canvas I drew an X on next to its preprocessed version](https://github.com/Mikubill/sd-webui-controlnet/assets/8322684/4df20f5d-d570-43c1-995a-2b58f26d65f7)

**Comment by huchenlei** [comment]
See https://github.com/Mikubill/sd-webui-controlnet/issues/2141
