### ISSUE TITLE
Error when trying to use any ip-adapter-faceid models.

### ISSUE THREAD

**Issue by nternan** [Mikubill/sd-webui-controlnet#2962]
hello, i keep getting an error when trying to use any ip-adapter-faceid models. other ip-adapter models will work but not those. My GPU Drivers are up to date, and so is my Webui. I deleted and reinstalled venv, but this still occurs. i copied what error occurs in attached doc. Any advice? Thanks
[message.txt](https://github.com/user-attachments/files/15937892/message.txt)

**Comment by INTstinkt** [comment]
i think i have the exact same issue but only on my second drive F: on C: it still works. searched for a solution to set the path to C: folder but didnt find anything

**Comment by nternan** [comment]
it appears mine was a cuda conflict, so i removed cuda and reinstalled venv
