### ISSUE TITLE
I want to know how I can send an adjusted openpose image through the API

### ISSUE THREAD

**Issue by caicaicaibeiqie** [Mikubill/sd-webui-controlnet#2963]

**Comment by caicaicaibeiqie** [comment]
These are my parameters：
{
          "advanced_weighting": null,
          "batch_images": "",
          "control_mode": "Balanced",
          "enabled": true,
          "guidance_end": 1,
          "guidance_start": 0,
          "hr_option": "Both",
          "image": null,
          "inpaint_crop_input_image": true,
          "input_mode": "simple",
          "is_ui": true,
          "loopback": false,
          "low_vram": false,
          "model": "control_v11p_sd15_openpose_fp16 [73c2b67d]",
          "module": "none",
          "input_image":"{\"people\":[{\"pose_keypoints_2d\":[230,134,1,288,252,1,212,243,1,98,165,1,193,76,1,362,266,1,428,453,1,329,556,1,182,556,1,156,767,1,0,0,0,284,578,1,0,0,0,0,0,0,221,113,1,254,113,1,0,0,0,313,118,1],\"hand_right_keypoints_2d\":[0,0,0,0,0,0,0,0,0,285,30,1,0,0,0,285,12,1,293,24.999999046325684,1,290,30,1,287,30,1,282,13.000000476837158,1,292,27,1,287,33,1,281,30.999999046325684,1,278,15,1,285,27.999999046325684,1,282,35.000000953674316,1,278,33,1,273,19.000000476837158,1,279,30,1,278,35.000000953674316,1,273,35.000000953674316,1],\"hand_left_keypoints_2d\":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],\"face_keypoints_2d\":[221,129.99999618530273,1,221,135,1,221,141,1,221,150.99999618530273,1,222,156.99999618530273,1,227,168,1,232,177.99999618530273,1,237,188.00000381469727,1,243,193.00000762939453,1,258,189,1,269,183.99999618530273,1,284,177.99999618530273,1,295,168,1,300,156.99999618530273,1,305,141,1,306,125.00000381469727,1,305,110.00000381469727,1,216,108.99999618530273,1,216,108.99999618530273,1,216,108.99999618530273,1,221,108.99999618530273,1,226,108.99999618530273,1,237,104.00000381469727,1,242,99,1,253,98.00000381469727,1,263,98.00000381469727,1,274,99,1,232,120,1,231,125.00000381469727,1,226,129.99999618530273,1,226,135.99999618530273,1,221,146.00000381469727,1,226,146.00000381469727,1,227,146.00000381469727,1,232,146.00000381469727,1,237,146.00000381469727,1,221,125.00000381469727,1,221,120,1,226,120,1,227,125.00000381469727,1,226,125.00000381469727,1,221,125.00000381469727,1,247,120,1,253,119.00000381469727,1,258,114.99999618530273,1,263,114.99999618530273,1,258,120,1,253,120,1,231,162,1,227,156.99999618530273,1,231,156.99999618530273,1,232,156.99999618530273,1,237,156.99999618530273,1,242,156.99999618530273,1,253,162,1,247,167.00000381469727,1,237,171.99999618530273,1,237,171.99999618530273,1,232,171.99999618530273,1,231,167.00000381469727,1,232,162,1,232,162,1,232,162,1,237,162,1,248,162,1,237,162,1,232,162,1,232,162,1,226,125.00000381469727,1,253,120,1,232,120,1]}],\"animals\":[],\"canvas_width\":512,\"canvas_height\":768}",
          "output_dir": "",
          "pixel_perfect": true,
          "processor_res": 512,
          "resize_mode": "Crop and Resize",
          "save_detected_map": false,
          "threshold_a": 0,
          "threshold_b": 0,
          "weight": 1
        }
And it bring a error like this:
<title>Not Found</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>

**Comment by caicaicaibeiqie** [comment]
Sorry,It seems I used a wrong link of webui.
But my pose json still not working when after Fixed the domain name. 
Some body help me

**Comment by huchenlei** [comment]
There is an API endpoint to convert openpose JSON to image:
https://github.com/Mikubill/sd-webui-controlnet/blob/8bbbd0e55ef6e5d71b09c2de2727b36e7bc825b0/scripts/api.py#L213C5-L234C14

**Comment by phucbienvan** [comment]
hi @huchenlei 
Is there a way to convert from image pose to JSON pose?

**Comment by phucbienvan** [comment]
> hi @huchenlei Is there a way to convert from image pose to JSON pose?

http://127.0.0.1:7860/controlnet/detect'
i found it
