### ISSUE TITLE
where is the setting panel?

### ISSUE THREAD

**Issue by zffffff** [Mikubill/sd-webui-controlnet#297]
there's something that confuses me

Somewhere in the instructions it mentions a settings panel, but I can't find where

![N~EV4$Q7XVW6O6LGZ%K79 3](https://user-images.githubusercontent.com/21136110/220703901-8aac1b0e-3efe-4f14-983d-ee43d96d40f5.png)
![CIN_0096B_5 G 0KWAJ}NYY](https://user-images.githubusercontent.com/21136110/220703956-d9075b29-9776-4df3-b18e-32018cec5ab9.png)
![CD8S8H5CHB_5AOU7C55L83Q](https://user-images.githubusercontent.com/21136110/220704194-71c972c3-42b2-4bc1-a0b3-3da890f48887.png)

**Comment by EfourC** [comment]
Maybe there was a problem installing the extension.

It should look like this:
![9rkSeIHyTt](https://user-images.githubusercontent.com/121468033/220772498-05e0d402-075f-4b86-86ad-6bf9735aec2a.png)

Do you see the ControlNet section in the txt2img and img2img tabs?

![9rOWj0ir6S b](https://user-images.githubusercontent.com/121468033/220772856-8c925a15-d9f2-475e-ad45-8d3099cf8994.png)

**Comment by zffffff** [comment]
Yes, I can see the ControlNet section, and have been using it for a while. But there is no controlnet in the settings.
This option didn't exist before the update too.

![image](https://user-images.githubusercontent.com/21136110/220801553-32093575-0f0b-4624-806c-adbf9fcf618d.png)

**Comment by Mikubill** [comment]
Update the extension and you will see it.

**Comment by zffffff** [comment]
> Update the extension and you will see it.

This issue was happened after the update.
![image](https://user-images.githubusercontent.com/21136110/220803970-a9b4657d-e835-45bc-a299-b43d16065764.png)
But yesterday it was showing the latest

**Comment by zffffff** [comment]
> Hmm... How about trying to reinstall it? btw, this UI is definitely an old version and has already been updated in #83.

I was thinking the same thing, I just deleted the folder
