### ISSUE TITLE
[Request]: Xinsir controlnet union support 

### ISSUE THREAD

**Issue by 3blackbar** [Mikubill/sd-webui-controlnet#2986]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

he added controlnet union, with all of them built in into one 
https://huggingface.co/xinsir/controlnet-union-sdxl-1.0

Can You add support for it ? so when we are in canny or openpose or depth etc preprocessor it will send proper number to it  automatically ?  
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/162857724/65acbdbd-c37b-4e02-9dc4-d4d9ea75edb9)

### Steps to reproduce the problem

.

### What should have happened?

.

### Commit where the problem happens

.

### Command Line Arguments

```Shell
.
```

### List of enabled extensions

.

### Console logs

```Shell
.
```

**Comment by skyliwq** [comment]
+1
