### ISSUE TITLE
openpose 更新姿态后， 如何在文生图中调用

### ISSUE THREAD

**Issue by dhp666** [Mikubill/sd-webui-controlnet#2987]
openpose 更新姿态后， 如何在文生图中调用？是将任务姿态json数据传到文生图参数当中吗，求助谢谢大佬

**Comment by huchenlei** [comment]
See https://github.com/Mikubill/sd-webui-controlnet/issues/2963

**Comment by dhp666** [comment]
我这里还是不行，这是我的请求参数您看有问题吗 {
    "enable_hr": false,
    "denoising_strength": 0.7,
    "firstphase_width": 0,
    "firstphase_height": 0,
    "hr_scale": 2,
    "hr_second_pass_steps": 0,
    "hr_resize_x": 0,
    "hr_resize_y": 0,
    "prompt": "a girl with sky",
    "styles": [],
    "seed": -1,
    "subseed": 0,
    "subseed_strength": 0.0,
    "seed_resize_from_h": 0,
    "seed_resize_from_w": 0,
    "sampler_name": "DPM++ 2M Karras",
    "batch_size": 1,
    "n_iter": 1,
    "steps": 10,
    "cfg_scale": 7.0,
    "width": 512,
    "height": 512,
    "restore_faces": false,
    "tiling": false,
    "do_not_save_samples": false,
    "do_not_save_grid": true,
    "negative_prompt": "ugly, out of frame",
    "eta": 1.0,
    "s_churn": 0,
    "s_tmax": 0,
    "s_tmin": 0,
    "s_noise": 1,
    "override_settings_restore_afterwards": true,
    "script_args": [],
    "send_images": true,
    "save_images": false,
    "alwayson_scripts": {
        "save_dir": "/code/stable-diffusion-webui/data-standard/outputs",
        "sd_model_checkpoint": "deliberate_v2.safetensors",
        "controlnet": {
            "args": [
                {
                    "enabled": true,
                    "module": "None",
                    "model": "control_v11p_sd15_openpose [2e90891e]",
                    "weight": 1,
                    "input_image": "{\"people\":[{\"pose_keypoints_2d\":[230,134,1,288,252,1,212,243,1,98,165,1,193,76,1,362,266,1,428,453,1,329,556,1,182,556,1,156,767,1,0,0,0,284,578,1,0,0,0,0,0,0,221,113,1,254,113,1,0,0,0,313,118,1],\"hand_right_keypoints_2d\":[0,0,0,0,0,0,0,0,0,285,30,1,0,0,0,285,12,1,293,24.999999046325684,1,290,30,1,287,30,1,282,13.000000476837158,1,292,27,1,287,33,1,281,30.999999046325684,1,278,15,1,285,27.999999046325684,1,282,35.000000953674316,1,278,33,1,273,19.000000476837158,1,279,30,1,278,35.000000953674316,1,273,35.000000953674316,1],\"hand_left_keypoints_2d\":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],\"face_keypoints_2d\":[221,129.99999618530273,1,221,135,1,221,141,1,221,150.99999618530273,1,222,156.99999618530273,1,227,168,1,232,177.99999618530273,1,237,188.00000381469727,1,243,193.00000762939453,1,258,189,1,269,183.99999618530273,1,284,177.99999618530273,1,295,168,1,300,156.99999618530273,1,305,141,1,306,125.00000381469727,1,305,110.00000381469727,1,216,108.99999618530273,1,216,108.99999618530273,1,216,108.99999618530273,1,221,108.99999618530273,1,226,108.99999618530273,1,237,104.00000381469727,1,242,99,1,253,98.00000381469727,1,263,98.00000381469727,1,274,99,1,232,120,1,231,125.00000381469727,1,226,129.99999618530273,1,226,135.99999618530273,1,221,146.00000381469727,1,226,146.00000381469727,1,227,146.00000381469727,1,232,146.00000381469727,1,237,146.00000381469727,1,221,125.00000381469727,1,221,120,1,226,120,1,227,125.00000381469727,1,226,125.00000381469727,1,221,125.00000381469727,1,247,120,1,253,119.00000381469727,1,258,114.99999618530273,1,263,114.99999618530273,1,258,120,1,253,120,1,231,162,1,227,156.99999618530273,1,231,156.99999618530273,1,232,156.99999618530273,1,237,156.99999618530273,1,242,156.99999618530273,1,253,162,1,247,167.00000381469727,1,237,171.99999618530273,1,237,171.99999618530273,1,232,171.99999618530273,1,231,167.00000381469727,1,232,162,1,232,162,1,232,162,1,237,162,1,248,162,1,237,162,1,232,162,1,232,162,1,226,125.00000381469727,1,253,120,1,232,120,1]}],\"animals\":[],\"canvas_width\":512,\"canvas_height\":768}",
                    "resize_mode": "Crop and Resize",
                    "lowvram": false,
                    "threshold_a": 0,
                    "threshold_b": 0,
                    "guidance_start": 0.1,
                    "guidance_end": 0.9,
                    "control_mode": "Balanced",
                    "save_detected_map": false,
                    "pixel_perfect": true
                }
            ]
        }
    }
}
