### ISSUE TITLE
[Bug]: Controlnet Union doesn't necessarily need a control type

### ISSUE THREAD

**Issue by PladsElsker** [Mikubill/sd-webui-controlnet#2994]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I tested the new controlnet union model without control type information (so no condition transformer, no control encoder), and it works really well. You can combine multiple input types into the same input image, and it will work as you would expect. See examples below for what I mean: 
<table>
  <tr>
    <td>OpenPose + background image</td>
    <td><img src="https://github.com/user-attachments/assets/ec5d81a3-5dff-4644-925c-ad25d92fbd67" alt="Image 1" style="width: 100%;"></td>
    <td><img src="https://github.com/user-attachments/assets/c48c69ee-0377-46c0-bd26-08c786701afd" alt="Image 2" style="width: 100%;"></td>
  </tr>
  <tr>
    <td>Canny + background image</td>
    <td><img src="https://github.com/user-attachments/assets/14dc613b-6a9c-415c-ab4d-8a079be43432" alt="Image 1" style="width: 100%;"></td>
    <td><img src="https://github.com/user-attachments/assets/c7df74b5-6f3c-473e-b06b-2379e7723f09" alt="Image 2" style="width: 100%;"></td>
  </tr>
  <tr>
    <td>Raw 3D scene</td>
    <td><img src="https://github.com/user-attachments/assets/ac3d032f-baf2-48c1-aa63-59a5500e15c7" alt="Image 1" style="width: 100%;"></td>
    <td><img src="https://github.com/user-attachments/assets/79eef247-47e5-4b0c-91bd-aec34f488fdd" alt="Image 2" style="width: 100%;"></td>
  </tr>
  <tr>
    <td>Raw image, no preprocessor</td>
    <td><img src="https://github.com/user-attachments/assets/7d67ef3b-b81a-41b2-9411-ea68c41e7cb3" alt="Image 1" style="width: 100%;"></td>
    <td><img src="https://github.com/user-attachments/assets/0eb326e5-1c25-44b8-bd9f-9486c36eabcc" alt="Image 2" style="width: 100%;"></td>
  </tr>
</table>

I hope I'm getting the point accross, the amount of combinations possible is very interesting and might be useful to a lot of users. 

### Steps to reproduce the problem

1. Select the union model when the control type is "All"
2. Generate. You will get an error saying no control type is selected

### What should have happened?

The union controlnet model should run normally without running the condition transformer nor the control encoder. 

### Commit where the problem happens

webui: feee37d75f1b168768014e4634dcb156ee649c05
controlnet: 9fae97fe292f3aec30d7694cdf7ecf8c854b5cdb

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--theme dark --api --xformers --no-half-vae --opt-sdp-attention
```

### List of enabled extensions

- [ControlNet](https://github.com/Mikubill/sd-webui-controlnet)

### Console logs

This line throws:
https://github.com/Mikubill/sd-webui-controlnet/blob/9fae97fe292f3aec30d7694cdf7ecf8c854b5cdb/scripts/enums.py#L334

### Additional information

Proposed architecture when using control type "All" (image from https://huggingface.co/xinsir/controlnet-union-sdxl-1.0):  

![image](https://github.com/user-attachments/assets/4631490d-fcd8-44a7-a1d3-ef6aa111c03b)

**Comment by PladsElsker** [comment]
Proposed architecture when using control type "All" (image from https://huggingface.co/xinsir/controlnet-union-sdxl-1.0):  

![image](https://github.com/user-attachments/assets/4631490d-fcd8-44a7-a1d3-ef6aa111c03b)

**Comment by 3blackbar** [comment]
Except it does cause i got bad gens where limbs looked like openpose skeleton in auto11

**Comment by PladsElsker** [comment]
> Except it does cause i got bad gens where limbs looked like openpose skeleton in auto11

It was obviously not built for that architecture, but it's still very useful and somehow works well enough to be consistent, as shown with my examples. I'm sure there are a lot more combinations that could be super interesting to try.
