### ISSUE TITLE
 使用API 调用controlnet++_union_sdxl 出现错误

### ISSUE THREAD

**Issue by skyliwq** [Mikubill/sd-webui-controlnet#2997]
{'error': 'ValueError', 'detail': '', 'body': '', 'errors': 'Unknown control type cannot be encoded.'} 使用API 调用controlnet++_union_sdxl 出现错误

**Comment by huchenlei** [comment]
Should be fixed by https://github.com/Mikubill/sd-webui-controlnet/pull/2995
