### ISSUE TITLE
Resize modes not working?

### ISSUE THREAD

**Issue by Jonseed** [Mikubill/sd-webui-controlnet#300]
Both the "envelope (outer fit)" and "scale to fit (inner fit)" modes seem to do the same thing.

**Comment by Jonseed** [comment]
If I have a square canvas, and a tall input image, then it seems to always fit the full bounds of the square canvas, extending the original input image over the edges, in both modes. Shouldn't it be quite different in those two modes? In one of the modes, it should fit the input image fully inside the bounds of the square canvas. I'm not sure if it is resizing the canvas to fit, or the input image to fit, but either way, the two modes should result in a very different image.

**Comment by mghill** [comment]
Experiencing the same issue. Fiddled around with controlnet.py lines 664-671, where you can see the condition for inner-fit is `h if h<w else w` which only covers certain cases (i.e. a square controlnet image and a long output image) but not others. I haven't found an elegant way to account for them all.

**Comment by Dradows** [comment]
> 

https://github.com/Mikubill/sd-webui-controlnet/pull/621

This PR should be able to solve this problem, but there is no person in charge to respond to it yet.
