### ISSUE TITLE
Annotator ignores uploaded image

### ISSUE THREAD

**Issue by alexkorol** [Mikubill/sd-webui-controlnet#302]
I am running the controlnet extension in webui on paperspace. 
I had it working correctly about 4 days ago, however, after creating a new machine and installing everything from scratch I am having an issue where the images I upload in txt2img and img2img tabs have no effect on the output. For example, canny model always creates a white annotator result and depth model makes a seemingly random gradient. When I draw on the image, the scribble is correctly picked up up by the annotator, but the underlying image is still ignored. Guess mode also produces annotator results that are completely white images.

**Comment by SepticSpoons** [comment]
Pretty sure it's a browser related issue.  #117, #263 For me, (using Firefox) I had to allow extract canvas data for it to work.

**Comment by alexkorol** [comment]
> Pretty sure it's a browser related issue. #117, #263 For me, (using Firefox) I had to allow extract canvas data for it to work.

Thanks so much, that was the problem! Apparently Brave browser has this canvas permission disabled. It's working fine in Chrome now.

**Comment by dathide** [comment]
When I didn't use a preprocessor, the images would be blank white. I fixed it by disabling the Canvas Blocker Firefox extension for the Stable Diffusion webpage.
