### ISSUE TITLE
[Bug]: controlnet_aux错误

### ISSUE THREAD

**Issue by xiahongyu939** [Mikubill/sd-webui-controlnet#3023]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

启用stablediffusion时，代码显示no module named:controlnet_aux

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

修复

### Commit where the problem happens

webui: webui
controlnet: controlnet

### Command Line Arguments

```Shell
是
```

### List of enabled extensions

无

### Console logs

```Shell
无
```

**Comment by paboum** [comment]
Reverting to commit `3ff69b9ea32f59ac866780b19a6465f9b9d28053` helps as a workaround

**Comment by sdbds** [comment]
换镜像源，安装最新版controlnet_aux。
