### ISSUE TITLE
Error using Scribble

### ISSUE THREAD

**Issue by rethink-studios** [Mikubill/sd-webui-controlnet#304]
After updating today, this is the error I receive with a simple black on white image:

To create a public link, set `share=True` in `launch()`.
Error completing request
Arguments: ('task(i7f5has60l0j2vn)', 0, 'ornate masterpiece, [intricate], a digital painting, [3d render:0.5], muted colors, muted shadows', 'sepia, gray, frame, vignette, hand, black, spots', [], None, None, None, None, None, None, None, 20, 0, 4, 0, 1, False, False, 1, 1, 7, 1.5, 0.75, -1.0, -1.0, 0, 0, 0, False, 512, 512, 0, 0, 32, 0, '', '', '', [], 0, False, True, False, 0, -1, True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', True, 'scribble', 'control_sd15_scribble [fef5e48e]', 1, {'image': array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]], dtype=uint8), 'mask': array([[[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       ...,

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]]], dtype=uint8)}, True, 'Scale to Fit (Inner Fit)', False, False, 512, 64, 64, 1, False, 0.9, 5, '0.0001', False, 'None', '', 0.1, False, '', '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', 0, '', True, False, False, False, 0, False, True, True, '', False, 1, 'Both ▦', False, '', False, True, False, False, False, False, 0, False, '', '', '', 'generateMasksTab', 1, 4, 2.5, 30, 1.03, 1, 1, 5, 0.5, 5, False, True, False, 0, True, 384, 384, False, 2, True, True, False, False, False, 4.0, '', 10.0, 'Linear', 3, False, True, 30.0, True, False, False, 0, 0.0, 'Lanczos', 1, True, 0, 0, 512, 512, False, False, True, True, True, False, False, 1, False, False, 2.5, 4, 0, False, 0, 1, False, False, 'u2net', False, False, False, False) {}
Traceback (most recent call last):
  File "G:\StableDiffusion\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "G:\StableDiffusion\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "G:\StableDiffusion\stable-diffusion-webui\modules\img2img.py", line 87, in img2img
    image = init_img.convert("RGB")
AttributeError: 'NoneType' object has no attribute 'convert'

**Comment by Mikubill** [comment]
Could you provide more details about how to replicate this error?

**Comment by rethink-studios** [comment]
Used img2img, and dragged an image from the web into the DROP window.
I wanted to test scribble, so dragged the image in 

https://static.vecteezy.com/system/resources/previews/005/385/224/original/hand-drawn-love-with-heart-on-white-background-illustration-free-vector.jpg

Enabled the script and activated Scribble mode.

PreProcessor = Scribble
Model = sd15_Scribble
Just Resize

everything else is stock

**Comment by FullBleed** [comment]
> Used img2img, and dragged an image from the web into the DROP window. I wanted to test scribble, so dragged the image in
> 
> https://static.vecteezy.com/system/resources/previews/005/385/224/original/hand-drawn-love-with-heart-on-white-background-illustration-free-vector.jpg

Not sure if this is the problem, but when I try to save that image it wants to save it as a webp format.  If you download it and convert it to a jpg manually, does it still have a problem?

**Comment by Meghpal** [comment]
Did the image get set in the UI? Drag and drop from URL is not supported I think, did you try downloading and then drag and dropping from your system?

**Comment by Meghpal** [comment]
Also when you use img2img there are 2 drop windows, were both filled with the same image?

**Comment by Meghpal** [comment]
For an example see the input images on the left.
![image](https://user-images.githubusercontent.com/40922889/220826675-56990a36-d459-47f2-be09-001e496e9473.png)

img2img

**Comment by rethink-studios** [comment]
Hey hey,
@FullBleed Didn't matter. 
@Meghpal Drag and Drop from web does work for me and thanks for point out the error, img2img without a top image, is repeatable. Is there a way to prompt the user to add images to the top and bottom when using img2img, in the event one or the other image is missing?

Updated to the latest, and seems to be working again..

![image](https://user-images.githubusercontent.com/60104539/220943811-07992fd5-1269-44fd-a059-f9dd168dc94a.png)
