### ISSUE TITLE
Scribble Mode vs "Invert Input Color"?

### ISSUE THREAD

**Issue by lllyasviel** [Mikubill/sd-webui-controlnet#309]
More than one people asked me how to use existing canny edge maps without detect the edges again, and they all send me screenshots with white background black edge and without selecting scribble mode. Perhaps the current name is not very eazy for them to find out that they need to select this to invert the color of their outside canny maps

**Comment by lllyasviel** [comment]
Also perhaps we can consider use white background black edge in pidinet to make all edge maps consistent. But this is less important.

**Comment by lllyasviel** [comment]
and a nice trick is to always invert the color of the gradio scribbles. Not sure if friendly for old users but definatly good for new users

**Comment by Mikubill** [comment]
Added in the latest commit. Hope this could help reducing such issues

**Comment by lllyasviel** [comment]
great job
