### ISSUE TITLE
How to use Normal Map?

### ISSUE THREAD

**Issue by scor2** [Mikubill/sd-webui-controlnet#31]
![p18](https://user-images.githubusercontent.com/117506473/218731375-a1727214-daf2-4caa-a74d-10f627a0c5fb.png)

I set the preprocessor - midas / model - control_sd15_normal, but it doesn't work.

How can I use Normal map in this extension.

**Comment by Mikubill** [comment]
Added in https://github.com/Mikubill/sd-webui-controlnet/commit/98d24916f44ea8b024aa03180d9e0dd9f9472ae4

**Comment by radiodus** [comment]
<img width="401" alt="스크린샷_20230214_115457" src="https://user-images.githubusercontent.com/87018364/218774060-fa7dcc4f-ac5a-4380-9200-e07992668656.png">

Thx! I tested it, But it doesn't work.
It make normal map correctly, but final image is broken.

**Comment by Mikubill** [comment]
Fixed, update and try again

**Comment by scor2** [comment]
It works very well! Thank you :)

**Comment by AugmentedRealityCat** [comment]
Thanks a lot for fixing this !
