### ISSUE TITLE
error loading controlnet/xyz_grid_support

### ISSUE THREAD

**Issue by ChangYaQi** [Mikubill/sd-webui-controlnet#312]
after adding controlnet extensions, an error occir when webui starting:
```
Error loading script: xyz_grid_support.py
Traceback (most recent call last):
  File "D:\project\stable-webui\modules\scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "D:\project\stable-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "D:\project\stable-webui\extensions\sd-webui-controlnet-main\scripts\xyz_grid_support.py", line 70, in <module>
    add_axis_options(xyz_grid)
  File "D:\project\stable-webui\extensions\sd-webui-controlnet-main\scripts\xyz_grid_support.py", line 54, in add_axis_options
    xyz_grid.AxisOption("[ControlNet] Model", str, apply_field("control_net_model"), choices=choices_model, confirm=confirm_model, cost=0.9),
TypeError: AxisOption.__new__() got an unexpected keyword argument 'choices'
```
 
I tried to find this function, but can't understand why this error would come up? Not only this line, all of the line in the below pic which include choices will all report error? I want to know why and how to fix it?

![1](https://user-images.githubusercontent.com/52132819/220832991-7b92b4d2-fa4d-42af-bbcf-4bba97a9ff4b.png)

**Comment by Mikubill** [comment]
Could you provide your Gradio version and WebUI version?

**Comment by ChangYaQi** [comment]
> Could you provide your Gradio version and WebUI version?

my gradio vwesion == 3.16.0 , webUI is updated by last week

**Comment by Mikubill** [comment]
Maybe fixed by https://github.com/Mikubill/sd-webui-controlnet/commit/ecad77ed65dac0dd51072cedaea5b7a7dfe7c795
