### ISSUE TITLE
[BUG] After latest update WebUI not loading 

### ISSUE THREAD

**Issue by Rogal80** [Mikubill/sd-webui-controlnet#315]
Hi, I have issue after latest update - my WebUi won't start - cmd it just stop after loading model with this text 
![image](https://user-images.githubusercontent.com/112553453/220852203-996b974a-b1fb-4029-8f92-00881eb9090c.png)

any clue how to solve this?

- win10
-  Auto1111 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8
- Firefox
--xformers --api --listen --enable-insecure-extension-access --no-half-vae
ControlNet only works for me until this revision 2c1bb46c7ad5b4536f6587d327a03f0ff7811c5d  :(

**Comment by Mikubill** [comment]
Can't reproduce on linux with WebUI commit 0cc0ee1. Maybe some issue with the env?

**Comment by Rogal80** [comment]
I found it don't work with one of extension that is outside Auto1111 - I just removed and it's fixed
