### ISSUE TITLE
binascii Error when using txt2img API

### ISSUE THREAD

**Issue by killamonis** [Mikubill/sd-webui-controlnet#318]
Getting the following error when trying to use the `/controlnet/txt2img` API path. 

<img width="997" alt="Screen Shot 2023-02-23 at 1 15 55 AM" src="https://user-images.githubusercontent.com/52933919/220865999-4d2a9c8e-da55-46b7-bfd8-45b1e8ffea77.png">

And this is my API call body 

`{
  "prompt": "xyz",
  "negative_prompt": "",
  "controlnet_input_image": ["/home/ubuntu/controlnet/business-0.jpeg"],
  "controlnet_mask": [],
  "controlnet_module": "canny",
  "controlnet_model": "control_sd15_canny [fef5e48e]",
  "controlnet_weight": 0.4,
  "controlnet_resize_mode": "Scale to Fit (Inner Fit)",
  "controlnet_lowvram": false,
  "controlnet_processor_res": 512,
  "controlnet_threshold_a": 64,
  "controlnet_threshold_b": 64,
  "controlnet_guidance": 1,
  "controlnet_guessmode": false,
  "enable_hr": true,
  "denoising_strength": 0.5,
  "hr_scale": 2,
  "hr_upscale": "Latent",
  "seed": -1,
  "subseed": -1,
  "subseed_strength": -1,
  "sampler_index": "",
  "batch_size": 4,
  "n_iter": 1,
  "steps": 20,
  "cfg_scale": 7,
  "width": 512,
  "height": 512,
  "restore_faces": true,
  "override_settings": {},
  "override_settings_restore_afterwards": true
}`

**Comment by Mikubill** [comment]
See https://github.com/Mikubill/sd-webui-controlnet/blob/main/example/test_api.ipynb, you may need to use a base64-encoded image as input
