### ISSUE TITLE
any update on batch control net  process

### ISSUE THREAD

**Issue by demirklvc** [Mikubill/sd-webui-controlnet#319]
hello! appreciate your work. thanks alot. any update on batch control net  process? it would help alot :)

**Comment by Mikubill** [comment]
Currently you can generate images with controlnet in batch using the API or img2img -> Batch tab + `skip img2img process` in settings. Not very handy, will consider add it to somewhere later.

**Comment by AbyszOne** [comment]
> Currently you can generate images with controlnet in batch using the API or img2img -> Batch tab + `skip img2img process` in settings. Not very handy, will consider add it to somewhere later.

The problem is that there is an astronomical difference between having a reference image in img2img and not having one. To give an example, a denoising 0.5 running the same image simultaneously allows applying styles with a very high temporal and compositional coherence. I cannot stress enough how essential independent batch and multibatch are.
Currently it is already possible to make much better quality videos, but it is impossible to work if you have to manually put in two or more nets + img2img each frame. It's a monumental pain in the ass, seriously.

**Comment by AbyszOne** [comment]
![hombremanoscabeza_000028](https://user-images.githubusercontent.com/112580728/220891354-9e0220f5-3b3c-4ec6-8b17-64ba8e4f24bd.jpeg)
![hombremanoscabeza_000030](https://user-images.githubusercontent.com/112580728/220891362-f67c2aa1-fc2b-4a4e-a693-0dc83c0e3179.jpeg)
![03329-860764529-a woman, cartoon style](https://user-images.githubusercontent.com/112580728/220891513-e4e119eb-c9b2-427a-bcd2-ea5060120dc5.jpg)
![03330-860764529-a woman, cartoon style](https://user-images.githubusercontent.com/112580728/220891518-0d4c49f7-5fb6-416c-8f16-106ed06b8167.jpg)

Just a quick example. Thats only possible with a blend batch. Not even cherry picked.

**Comment by demirklvc** [comment]
> Currently you can generate images with controlnet in batch using the API or img2img -> Batch tab + `skip img2img process` in settings. Not very handy, will consider add it to somewhere later.

<img width="1440" alt="Bildschirmfoto 2023-02-23 um 13 14 30" src="https://user-images.githubusercontent.com/78754525/220902766-41564743-1e69-4ca7-8fbd-b9bf993f6dbd.png">

**Comment by demirklvc** [comment]
> > [#319 (comment)](https://github.com/Mikubill/sd-webui-controlnet/issues/319#issuecomment-1441585173)
> 
> I see, will try if we could integrate with controlnet
> 
> > no attribute "save"
> 
> checkout #182

thanks alot!

**Comment by AbyszOne** [comment]
> > [#319 (comment)](https://github.com/Mikubill/sd-webui-controlnet/issues/319#issuecomment-1441585173)
> 
> I see, will try if we could integrate with controlnet
> 
> > no attribute "save"
> 
> checkout #182

Thank you! I am afraid that the relevance of this function is underestimated.
I understand that it can be a tricky integration if you factor multinets into the equation. The bare minimum is to be able to multibatch 1 net and img2img. From there, many things could be improved, but that would already be a total qualitative leap. Thanks again for your time and effort. Unfortunately I don't know how to program.

**Comment by VladPedro** [comment]
> 

set Denoising strength = 1
