### ISSUE TITLE
[feature request]It would be nice to add batch processing from a specific directory!

### ISSUE THREAD

**Issue by toyxyz** [Mikubill/sd-webui-controlnet#32]
It would be nice to be able to process poses and depth images in batches! This blender addon can export openpose images from character bones. Using this, we will be able to create animations too!
https://twitter.com/toni_nimono/status/1625411494602055685

https://user-images.githubusercontent.com/8006000/218740703-f31c8367-7424-4cb9-9897-76b5005a2022.mp4

**Comment by 2blackbar** [comment]
I agree, batch is a must for animation

**Comment by numz** [comment]
also ok, adding batch support will give awesome results

**Comment by toyxyz** [comment]
gif2gif extension supports ControlNet!
https://github.com/LonicaMewinsky/gif2gif
![image](https://user-images.githubusercontent.com/8006000/218959459-a2de71cb-ff16-4ce2-bc73-4b50e1b9bdcc.png)

![dance-dancing](https://user-images.githubusercontent.com/8006000/218959754-8b1da1bd-7ab6-49d5-883c-80fd60c23414.gif)
![pose2image](https://user-images.githubusercontent.com/8006000/218959773-f56d0021-a1de-4c1a-b3e5-8d6bb607a42b.gif)
![OnTQ](https://user-images.githubusercontent.com/8006000/218959808-15fa6877-0492-4b59-acb2-ecc7d4a29d28.gif)
![gif2gif-0027](https://user-images.githubusercontent.com/8006000/218959832-4248dbfe-0650-4a86-89e1-83249b03fe0d.gif)
