### ISSUE TITLE
[FEATURE REQUEST] Interlaping detection in open pose model.

### ISSUE THREAD

**Issue by Drakmour** [Mikubill/sd-webui-controlnet#325]
Open pose model struggles with moments when bones interlap each other. It confuses where is what even on a single model. And if there are 2 skeletons that interact with each other it creates abomination mess. Is there a way to add detection that bones are behind another bone or object? Not just deleting joints and bones but to "explain" the generation that some bones are "there, but not visible" so that it would understand where limb should go from one side of interlapping object and where to pop out from the other side of interlapping object.

IDK how all this controlnet magic is working, I hope that genius boys and girls from GIT will figure it out!

**Comment by lendrick** [comment]
Your best way to deal with this is probably to use it in conjunction with a depth map.

**Comment by Drakmour** [comment]
Maybe not depth, maybe there is something like % of visibility that can be changed for bones and joints, or special color change like being darker, lighter or decrease hue of colors to show that bones are not visible. Who knows.
