### ISSUE TITLE
openpose

### ISSUE THREAD

**Issue by archJude** [Mikubill/sd-webui-controlnet#328]
Using the openpose model, I tried many times, the skeleton is correct, but the pictures all look like the picture below

![00030-2376154769](https://user-images.githubusercontent.com/7632112/220973343-5be0db04-83d3-40bb-aa65-14cac8be750a.png)

**Comment by Mikubill** [comment]
What's your input image?

**Comment by rainx** [comment]
Hi @Mikubill . I meet the same issue. I installed the extension last night(Beijing time, around 8 hours ago), I tried different Sampling methods, Checkpoints, and Prompts. the following is the input image I used

<img width="1442" alt="image" src="https://user-images.githubusercontent.com/101971/221067005-264253b8-4645-46bc-9321-38bd36be7fc7.png">

**Comment by rainx** [comment]
This is what it looks like with a high res version prompt when using image to image way
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/101971/221076851-0e57d06a-673d-4194-81e5-3fb2b7feaee7.png">

**Comment by archJude** [comment]
> What's your input image?

Thank you for your reply
Here are the image I input, and the skeleton, it looks correct
In fact, I have tried other pictures, and the results are similar
<img width="957" alt="WechatIMG95530" src="https://user-images.githubusercontent.com/7632112/221077058-99e9a4d4-c99b-4953-bfc1-42bdf79861c8.png">

In addition, supplement my running environment below:
Device: MacBook Pro M1 chip
Python 3.10.6

Preprocessor & Model
<img width="706" alt="WechatIMG95532" src="https://user-images.githubusercontent.com/7632112/221077090-4ae49827-8ff2-4ac7-a79b-0db485127d95.png">

In fact, after I installed ControlNet
I also tried Scribble, and the result seems to be wrong

**Comment by Mikubill** [comment]
> rainx: I meet the same issue. I installed the extension last night(Beijing time, around 8 hours ago), I tried different Sampling methods, Checkpoints, and Prompts. the following is the input image I used

In this case you may need to use openpose_hand model which is still training(probably) and not released yet.
see https://github.com/Mikubill/sd-webui-controlnet/issues/25 https://github.com/Mikubill/sd-webui-controlnet/issues/241 https://github.com/Mikubill/sd-webui-controlnet/issues/210

> MacBook Pro M1 chip

On mps device sometimes you may need to enable no-half to get correct result (it's a bug and we're working on it.)

**Comment by castaneai** [comment]
Hi, I have the same problem as archJude on the Apple M1 Max chip.
I solved it by adding the `--no-half` option as Mikubill mentioned. Thanks!

```diff
diff --git a/webui-macos-env.sh b/webui-macos-env.sh
index 37cac4fb..0e53f445 100644
--- a/webui-macos-env.sh
+++ b/webui-macos-env.sh
@@ -10,7 +10,7 @@ then
 fi
 
 export install_dir="$HOME"
-export COMMANDLINE_ARGS="--skip-torch-cuda-test --upcast-sampling --no-half-vae --use-cpu interrogate"
+export COMMANDLINE_ARGS="--skip-torch-cuda-test --upcast-sampling --no-half-vae --use-cpu interrogate --no-half"
 export TORCH_COMMAND="pip install torch==1.12.1 torchvision==0.13.1"
 export K_DIFFUSION_REPO="https://github.com/brkirch/k-diffusion.git"
 export K_DIFFUSION_COMMIT_HASH="51c9778f269cedb55a4d88c79c0246d35bdadb71"
```

**Comment by rainx** [comment]
Hi @Mikubill @castaneai I am on Apple M1 Pro Chip and the  `--no-half` option works for me. thanks for your help

**Comment by barryanders** [comment]
> Hi @Mikubill @castaneai I am on Apple M1 Pro Chip and the `--no-half` option works for me. thanks for your help

Same

**Comment by archJude** [comment]
Hi @Mikubill @castaneai 
This is the best result I got
while the calculation continues, the image turns black
<img width="1109" alt="WechatIMG632" src="https://user-images.githubusercontent.com/7632112/221329247-f41ad6bd-00b5-45b8-8886-a28f5dedd601.png">
