### ISSUE TITLE
Error when trying to update via a1

### ISSUE THREAD

**Issue by specblades** [Mikubill/sd-webui-controlnet#33]
When I try to update the repo, it gives out this:

`File "D:\AI_WORKPLACE\AUTOMATIC1111\current\stable-diffusion-webui\modules\scripts.py", line 270, in initialize_scripts
    script = script_class()
  File "D:\AI_WORKPLACE\AUTOMATIC1111\current\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 118, in __init__
    "normal_map": midas_normal,
NameError: name 'midas_normal' is not defined`

**Comment by Mikubill** [comment]
Try restart webui

**Comment by joetech** [comment]
I received a similar error after applying the latest ControlNet update:
```NameError: name 'leres' is not defined```

I did a `git pull` on sd-webui and that fixed it.  Just leaving this note for anyone else who runs into that.
