### ISSUE TITLE
[f] automatically detect "image_adapter_v14.yaml" vs "sketch_adapter_v14.yaml"

### ISSUE THREAD

**Issue by lllyasviel** [Mikubill/sd-webui-controlnet#331]
perhaps a good idea is to make them both two into the setting (using two input fields in the setting) and then when loading state dicts, we can use the channel of that first layer to decide which config to use. This will make our tests on further t2ia models easier, eg, the new t2ia depth model https://github.com/TencentARC/T2I-Adapter

**Comment by Mikubill** [comment]
added in https://github.com/Mikubill/sd-webui-controlnet/commit/f94b453d10c2eb4e3ad57b7cdfdd17e60a557b3e. Now user can specify per-model config by simply adding a config file with same name as the model.

**Comment by lllyasviel** [comment]
great. very web-ui style. very automatic1111
