### ISSUE TITLE
Where is preprocessor button or RUN button?

### ISSUE THREAD

**Issue by bbggkk** [Mikubill/sd-webui-controlnet#34]
![未标题-1](https://user-images.githubusercontent.com/65471489/218756704-cab33aec-b9ef-4f61-9f98-9052881ca59d.png)

 AUTOMATIC1111 SD webIU is not capatiable?

**Comment by Mikubill** [comment]
Preprocessor will process image on-the-fly, just click generate

**Comment by bbggkk** [comment]
> Preprocessor will process image on-the-fly, just click generate
> 
> btw, note that multi cond(image+mask) input is not supported yet

I see,THX
