### ISSUE TITLE
runtime error on most recent commit

### ISSUE THREAD

**Issue by Wax-Replica** [Mikubill/sd-webui-controlnet#343]
Hi. This plugin was working for me yesterday, but as of today it produces the following error for all settings I've tried: 
![image](https://user-images.githubusercontent.com/3742404/221219460-02b8eb97-c3ed-414a-828b-13d6b90a02d4.png)

**Comment by Mikubill** [comment]
Inpainting model (9 channels) and difference controlnet (4 channels) could not be merged/applied automatically since channels are different. (extracted controlnet should works)

**Comment by Wax-Replica** [comment]
i see. im pretty sure i wasnt using an inpainting model but it works now so i guess i was. thanks

**Comment by brianebeling** [comment]
> Inpainting model (9 channels) and difference controlnet (4 channels) could not be merged/applied automatically since channels are different. (extracted controlnet should works)

Will there be a "fix" (or feature at this point) to support this? Sometimes the inpaint models work just that much better, it'd be nice to get more control over them just like with the other ones.
