### ISSUE TITLE
Cuda error when usin hires.fix and 2 controlnet

### ISSUE THREAD

**Issue by DrMacabre** [Mikubill/sd-webui-controlnet#344]
Hello, 

i keep getting this error when using hires.fix and 2 controlnet instances with default settings,

RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)`

it happens during the hires.fix second pass (between 50% and 100%) 

when this happen, all my displays goes to black for 2 seconds and SD stops after displaying the error message.

im running Automatic1111 on a 3090FE GPU.

**Comment by Mikubill** [comment]
Not familiar with cublas issues. Does it only happen when hires enabled?

**Comment by DrMacabre** [comment]
so far yes, im running a bunch of tests with only 1 controlnet enabled (in settings) and its working fine. It's started when the option to have multiple controlnet was added.

**Comment by Mikubill** [comment]
Is there any further errlog? I'm trying to find where the error starts..

**Comment by DrMacabre** [comment]
i just tried to replicate but after bringing back the model cache setting to 1 and it's not crashing anymore. Default was 2 if i remember correctly and the crash occurs when setting the cache to 4.

**Comment by DrMacabre** [comment]
can't even reproduce with cache set back to 4 so i'm clueless. It was happening at every generation, multiple relaunch, it even crashed windows once with a reboot and now it's gone. 🤔
