### ISSUE TITLE
API `/controlnet/txt2img` seems broken from one of the commits over last 24 hours

### ISSUE THREAD

**Issue by entmike** [Mikubill/sd-webui-controlnet#347]
API calls work from commit `b0c6d973380eb8fdd2d53387ebce4071cb1e8e5b` but fail (and fail relatively silently) after.  For instance, when I run the API call off of commit `b0c6d973380eb8fdd2d53387ebce4071cb1e8e5b`, I get 2 images for `/controlnet/txt2img`, it will run but only return one image (with no ControlNet applied to it, looks like a regular txt2img render) instead of the usual 2 images (the rendered image and the depth/canny/etc reference image)

**Comment by Mikubill** [comment]
Have you enabled `Allow other script to control this extension` in settings ?

**Comment by andresesfm** [comment]
checking that option and restarting the UI fixed it for me @Mikubill . Thank you

**Comment by entmike** [comment]
Confirming here, too.  Setting `control_net_allow_script_control` to `true` in `config.json` fixed this.  Thanks, @Mikubill!

**Comment by kkiqq22** [comment]
Yes, the video memory will not be released at all. Even if I choose 0 cache models, it cannot be released.

**Comment by kkiqq22** [comment]
img2img
