### ISSUE TITLE
RuntimeError: model not found: None

### ISSUE THREAD

**Issue by arjunbanker** [Mikubill/sd-webui-controlnet#348]
Steps to reproduce:
1) installed sd-webui-controlnet extension (mac os, intel)
2) Downloaded control_*safetensors and placed in:
  2a) stable-diffusion-ui/extensions/sd-webui-controlnet/models/ControlNet
  2b) stable-diffusion-ui/extensions/sd-webui-controlnet/models/
  2c) stable-diffusion-ui/models/ControlNet
3) launch web-ui, enable controlnet, generate

RESULT:
In all cases 2a,2b,2c - get this error indicating some kind of missing model -

traceback (most recent call last):
  File "/Development/ml/stable-diffusion-webui/modules/scripts.py", line 386, in process
    script.process(p, *script_args)
  File "/Development/ml/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 557, in process
    else self.build_control_model(p, unet, model, lowvram)
  File "/Development/ml/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 420, in build_control_model
    raise RuntimeError(f"model not found: {model}")
RuntimeError: model not found: None

--
file list from models folder -

README.md
cldm_v15.yaml
cldm_v21.yaml
control_canny-fp16.safetensors
control_depth-fp16.safetensors
control_hed-fp16.safetensors
control_mlsd-fp16.safetensors
control_normal-fp16.safetensors
control_scribble-fp16.safetensors
control_seg-fp16.safetensors
controlnetPreTrained_cannyDifferenceV10.safetensors
image_adapter_v14.yaml
sketch_adapter_v14.yaml
t2iadapter_keypose-fp16.safetensors
t2iadapter_seg-fp16.safetensors
t2iadapter_sketch-fp16.safetensors

**Comment by arjunbanker** [comment]
user error, realized that while i had enabled controlnet i also had to choose the specific model

**Comment by pdw2002** [comment]
> 用户错误，意识到虽然我启用了 ControlNet，但我还必须选择特定的型号

您好，我也遇到了和上面一样的错误，请问可以描述的具体点嘛，新入坑还不太懂到底怎么解决

**Comment by palin83157701** [comment]
This should be caused by model name changed from 1.0 to 1.1.
Try to navigate to Settings -> stable diffusion, and change “Config file for Control Net models” to "models\control_v11p_sd15_mlsd.yaml"

**Comment by Mahdigouadria7** [comment]
i got the same error but i cant fix it
