### ISSUE TITLE
Bug: preprocessor not woking

### ISSUE THREAD

**Issue by qdwang** [Mikubill/sd-webui-controlnet#354]
Preview the annotator will get an empty result
![image](https://user-images.githubusercontent.com/403616/221331490-a07b815a-d500-485c-8300-8bcec4d6ad06.png)

When try to generate, the console will always print `using mask as input`, but i didn't touch mask at all. 
It seems `if not ((image['mask'][:, :, 0]==0).all() or (image['mask'][:, :, 0]==255).all()):` is always True in kaggle vm.

https://github.com/Mikubill/sd-webui-controlnet/blob/main/scripts/controlnet.py#L581

I'm using SD webui in kaggle with a brand new install with the latest packages.

**Comment by Mikubill** [comment]
Which browsers/versions does it happen on?

**Comment by qdwang** [comment]
Brave version 1.48 Chromium 110 both macos and windows

**Comment by Mikubill** [comment]
see https://github.com/Mikubill/sd-webui-controlnet/issues/95

**Comment by qdwang** [comment]
Great, I've tried this on safari macos. No problem at all. It seems an issue comes with Chromium only.

**Comment by qdwang** [comment]
The only extension i used in brave is bitwarden - a password manager which shouldn't be the cause of the issue. And i leave all the settings to default.
