### ISSUE TITLE
OOM error does not release GPU VRAM

### ISSUE THREAD

**Issue by entmike** [Mikubill/sd-webui-controlnet#360]
If an API call is done and goes CUDA OOM, a lot of memory is left allocated when looking in`nvidia-smi` and does not seem to release it without restarting A1111.

**Comment by Mikubill** [comment]
Try using a lower model cache size may help

**Comment by entmike** [comment]
> Try using a lower model cache size may help

Sorry I should have given more details.  I am only using 1 model loaded ever.  RTX 3090 in Linux.

**Comment by entmike** [comment]
I think this fixed this: https://github.com/Mikubill/sd-webui-controlnet/issues/347#issuecomment-1444647723 - Closing unless I can cause it to happen again.

**Comment by entmike** [comment]
Reopening actually.  It still will not release any memory after an OOM error, after all.  Looking for a hand here, please let me know if I can provide additional details!

**Comment by kkiqq22** [comment]
Yes, the video memory will not be released at all. Even if I choose 0 cache models, it cannot be released.
