### ISSUE TITLE
[Feature request] Random images from a directory for ControlNet

### ISSUE THREAD

**Issue by Padusarbor** [Mikubill/sd-webui-controlnet#362]
For example, choose an image directory and get a random pose from one of these images every time you click generate. It would probably be a good idea to implement, to make the workflow more entertaining, so the character would have different poses and you don't have to change the image for control net every time.

**Comment by marcsyp** [comment]
This could be combined with the various requests to be able to run a batch from a directory (or multiple directories with multiple control nets) by having a checkbox that allows you to "random indexed image from directory" checkbox.  Same essential interface elements: fields to define directories for each controlnet you have activated, and toggle to toggle between "batch mode" (executes all directory images for all control nets in order by index, in parallel) and "random index mode", which pulls the indexed image for each active controlnet from the directories provided for each single image based on a random index.

Related:
https://github.com/lllyasviel/ControlNet/issues/171

**Comment by enn-nafnlaus** [comment]
Also related:
https://github.com/Mikubill/sd-webui-controlnet/issues/296
