### ISSUE TITLE
webui “weight” control bar means？

### ISSUE THREAD

**Issue by bluesharkchen** [Mikubill/sd-webui-controlnet#365]
Greetings, May i ask that the 'weight' control bar "0~2",will control what things in the CN webui plug-in ?There is no obvious feeling in actual use. thanks a lot.
![image](https://user-images.githubusercontent.com/126317726/221346371-1ce1e1c6-df7c-4b93-96f1-1f4c1cc1b570.png)

**Comment by Mikubill** [comment]
see https://github.com/Mikubill/sd-webui-controlnet/discussions/175

**Comment by bluesharkchen** [comment]
> Greetings, May i ask that the 'weight' control bar "0~2",will control what things in the CN webui plug-in ?There is no obvious feeling in actual use. thanks a lot. ![image](https://user-images.githubusercontent.com/126317726/221346371-1ce1e1c6-df7c-4b93-96f1-1f4c1cc1b570.png)



> see #175

thank you for your help，Now the control bar works as I want it to do.
