### ISSUE TITLE
Minimum Support?

### ISSUE THREAD

**Issue by samsonsite1** [Mikubill/sd-webui-controlnet#367]
Does rhe ControlNet extension work for Python 3.8.5?  Because it doesn't work for me.

**Comment by Mikubill** [comment]
Please describe the error you encountered.

**Comment by samsonsite1** [comment]
I believe my issue is with the preprocessors.  None of them work for me.  They produce no results.  The command prompt logs no errors, so I have nothing to show.

I can only suspect it has something to do with my Python version, so I was wondering if anyone is using ControlNet successfully with Python 3.8.5.  Unfortunately, I cannot update it, as I'm stuck on Windows 7.

**Comment by ljleb** [comment]
Have you checked the webui [wiki](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Dependencies#required-dependencies)? There seems to be a [link](https://github.com/adang1345/PythonWin7/raw/master/3.10.6/python-3.10.6-amd64-full.exe) to a windows 7 supported version of python 3.10.6:

![image](https://user-images.githubusercontent.com/32277961/221373163-b80fb9f3-07ce-4a1b-896d-bac7cc68d7a9.png)

If this does not work, you could try running the webui using WSL, docker or on a separate linux install. The webui is built around 3.10.6 so you may encounter unexpected errors here and there if you use an older or more recent version.

**Comment by samsonsite1** [comment]
Thanks, I will try that.

One question, if I have Python installed under Anaconda3, how can I update it with the Windows 7 version, and not the official version?

**Comment by samsonsite1** [comment]
Didn't work.

It seems if I install Python 3.10.6, Automatic1111 is trying to load cudart64_110.dll, which fails.  Cuda version 11 not supported for Windows 7.

Is there anyway to force Automatic1111 to use Cuda 10 instead?  Adding this parameter, --skip-torch-cuda-test, does not resolve the issue.  Everyting ran ok before updating to Python 3.10.6, so I don't understand why Automatic1111 now insists on using Cuda 11 instead of Cuda 10.

**Comment by samsonsite1** [comment]
I was able to get CUDA 11 for Windows 7 installed. Fix here:

https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/7379

Two DLLs need to be replaced:
envs\<whatever>\Lib\site-packages\torch\lib\cudart64_110.dll
envs\<whatever>\Lib\site-packages\torchvision\cudart64_110.dll

AUTOMATIC1111 is now running again with Python 3.10.6 and CUDA 11.  But I still have ControlNet issues.

txt2img:
ControlNet image is ignored. Doesn't seem to do anything.

img2img:
This doesn't seem to work either.  If I clear the ControlNet image, it seems to work, but only if I set Denoising strength to 1.0. Otherwise it just copies the same skeleton pose picture to the output window.

So, I think something is still screwed up.

**Comment by ljleb** [comment]
This sounds like a web browser extension is messing up with the page code. Could definitely be something else entirely but can you try disabling all your web browser extensions like duckduckgo and cie?

**Comment by samsonsite1** [comment]
Problem fixed!  It was the browser all along.  I had some AdBlockers and other dubious extensions installed, and that messed with ControlNet.  I disabled them all, and ControlNet started working.

But I don't really understand why AdBlockers affected ControlNet so badly, while everything else works ok.

Developer needs to put a **BIG** warning at the top of the readme file, to disable all AdBlocking browser extensions, because I dumped my entire installation trying to fix this issue.  That would have saved me much time and aggravation.

**Comment by samsonsite1** [comment]
BTW, there is another Internet browser called Brave that is even more privacy-focused than Firefox. So, if I'm having problems with script blocking extensions, I have no doubt Brave users are affected as well.

Stable Diffusion is running within a browser, so developer needs a warning for this kind of behavior.

**Comment by ljleb** [comment]
Browser issues with the webui have been a thing for a while, and are not limited to this extension. We could add warnings and guidance in this extension, but I think it would make a lot more sense to add this information in the webui repo instead of here.

For example, this comment has 2 thumbs, I assume it fixed an issue for 1 or 2 people:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/1738#issuecomment-1280000827

**Comment by samsonsite1** [comment]
Thanks!
