### ISSUE TITLE
[FEATURE REQUEST] Add "Paste from clipboard" button

### ISSUE THREAD

**Issue by DocZ80** [Mikubill/sd-webui-controlnet#369]
It would be great if you could add a button "insert from clipboard"
![image](https://user-images.githubusercontent.com/41061285/221358007-a8b8abb8-ca41-4d3b-b663-0b04aa96896b.png)

**Comment by 2blackbar** [comment]
just install clipboard extension, works across webui with ctrl+v

**Comment by ClashSAN** [comment]
um, my guy needs a link

**Comment by ClashSAN** [comment]
this> https://github.com/klimaleksus/stable-diffusion-webui-fix-image-paste ?

**Comment by DocZ80** [comment]
> this> https://github.com/klimaleksus/stable-diffusion-webui-fix-image-paste ?

good solution
