### ISSUE TITLE
Change "midas" preprocessor text to "depth"

### ISSUE THREAD

**Issue by Neverdusk** [Mikubill/sd-webui-controlnet#37]
This is a minor request, but changing the preprocessor text of the midas depth model from "midas" to "depth" would allow it to match the model's actual name, like with the other ControlNet preprocessors. This could help prevent some potential confusion for users who download the depth model but don't immediately see a "depth" option. Personally, even though I'm aware that midas = depth, it's still an extra reminder I have to give myself to select the right preprocessor each time. As a bonus, the sorting for the preprocessors and the models will also match better.

**Comment by Mikubill** [comment]
Done in 0f200f195811a79096a1e48793e3f0eb783bcb28
