### ISSUE TITLE
[Feature Request] Display uploaded image size to UI.  Workflow improvement

### ISSUE THREAD

**Issue by Alchete** [Mikubill/sd-webui-controlnet#378]
The more I use SD and ControlNet I'm finding that for every random picture I want to try, I first need to:

1. Open that picture in another photo editor
2. Write down or remember the picture dimensions
3. Use a calculator to compute the aspect ratio
4. Input the scaled version of that aspect ratio into the output image dimensions (in txt2img or img2img)

Steps 1 & 2 are in ControlNet.
Steps 3 & 4 are in base A1111.

Steps 1 & 2 can be eliminated if ControlNet simply reports the H & W of the uploaded image somewhere in the UI.

In playing with this there appears to be space just below the Image component to report this info in read-only Textboxes.

Possible implementation:

![image](https://user-images.githubusercontent.com/4705189/221375251-9951b956-aeae-4cb9-8f31-7d13d648065e.png)

The Textboxes could be made even smaller, if Gradio supports that.

I'd be willing to take a crack at implementing this and filing a PR, but unfortunately, I'm from the desktop UI world and am apparently clueless on how the Gradio components and callbacks work together.  🙃

```
        input_image.orgpreprocess=input_image.preprocess
        input_image.preprocess=svgPreprocess
        input_image.upload(fn=get_image_dimensions, inputs=input_image, outputs=[])
```

I tried adding an "upload" callback to the input_image component but this ends up throwing errors from the svgPreprocess() method, which I'm guessing gets called first?

All that's needed is to get the image dimensions when an image is 'uploaded' or 'changed", perhaps.  Any guidance on making this work?  It seems rather simple, in theory.  😂

**Comment by ljleb** [comment]
You're pretty close! The missing piece is that you have to put the text fields you want to update in the `outputs` array, otherwise gradio doesn't update any of its components.

**Comment by ljleb** [comment]
For some reason, adding these lines:
```
input_image_dims_txt = gr.HTML(value='')
input_image.change(fn=lambda img: '0x0', inputs=input_image, outputs=input_image_dims_txt)
```
just under this line:
https://github.com/Mikubill/sd-webui-controlnet/blob/fe40f206450aa60105bd146f48f0cbe6f3c1f497/scripts/controlnet.py#L218
ends up creating an infinite loop? Both the lambda and `svgPreprocess` are called turn by turn infinitely. Pretty fun!

**Comment by Alchete** [comment]
Yeah, I'm not having much luck here.  How hard can it be to get two numbers from an image??? 😂

UI code:
```
        with gr.Row():
            gr.HTML(value='<p>Invert colors if your image has white background.<br >Change your brush width to make it thinner if you want to draw something.<br ></p>')
            cnet_image_width  = gr.Textbox(css="{width: 100px;}", visible=True, show_label=True, label='Image Width')
            cnet_image_height = gr.Textbox(visible=True, show_label=True, label='Image Height') #.style("{width: 100px;}")
            webcam_enable = ToolButton(value=camera_symbol)
            webcam_mirror = ToolButton(value=reverse_symbol)
```
Callback attempt:
```
        input_image.orgpreprocess=input_image.preprocess
        input_image.preprocess=svgPreprocess
        input_image.upload(fn=get_image_dimensions, inputs=input_image, outputs=[cnet_image_width, cnet_image_height])
```
Error output from svgPreprocess
******svgPreprocess************
```
Traceback (most recent call last):
  File "E:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1013, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "E:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 911, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "E:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 364, in svgPreprocess
    return input_image.orgpreprocess(inputs)
  File "E:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1508, in preprocess
    mask_im = processing_utils.decode_base64_to_image(mask)
  File "E:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 53, in decode_base64_to_image
    content = encoding.split(";")[1]
AttributeError: 'NoneType' object has no attribute 'split'

```

**Comment by LonicaMewinsky** [comment]
Maybe a button for "Send dimensions to img2img"? Rather than relying on upload function, that is.

**Comment by marcsyp** [comment]
I agree with this wholeheartedly. A way to get the dimensions of the uploaded image, drag a multiplier spider and send to the img dimensions would be an amazing workflow improvement.

**Comment by Alchete** [comment]
Thanks @LonicaMewinsky -- agree that your idea would be even more useful.   A button to just inject the dimensions into txt2img and img2img.  Then we can add a "lock aspect ratio" button to the base A1111 UI and users would be able to scale any random pic with just two clicks.

Unfortunately, I'm a newborn infant at Gradio & HTML.

I tried adding a button and creating a function, but the processed output of the input_image is empty.  I can't figure out how to get the dimensions from the uploaded image.  Any ideas?

```
        def send_image_dimensions(image):
            print("sending dimensions")
            out_image = np.asarray(image)
            print(out_image.shape[0:1])
            return None
            
        send_dimensions.click(fn=send_image_dimensions, inputs=input_image, outputs=None)
        webcam_enable.click(fn=webcam_toggle, inputs=None, outputs=input_image)
        webcam_mirror.click(fn=webcam_mirror_toggle, inputs=None, outputs=input_image)
```

OUTPUT:

To create a public link, set `share=True` in `launch()`.
******svgPreprocess************
sending dimensions
()

**Comment by LonicaMewinsky** [comment]
Looks like the image value is coming through as a dict. This spits out the dimensions:
```
        def send_dimensions(image):
            if(image): #do nothing if there's no value there
                interm = np.asarray(image.get('image'))
                print(interm.shape)
            return None
```

**Comment by LonicaMewinsky** [comment]
In retrospect this is probably better suited for Discussions. That said, I'm not exactly a Gradio/Python wizard either, but here's a fork with "send dimensions to *2img" implemented: https://github.com/LonicaMewinsky/sd-webui-controlnet_lonica

Hooking into vanilla UI components is not obvious, or at least wasn't to me, so here are some details:

Initialized 4 variables in script class:
```
        self.txt2img_w_slider = gr.Slider()
        self.txt2img_h_slider = gr.Slider()
        self.img2img_w_slider = gr.Slider()
        self.img2img_h_slider = gr.Slider()
```
Capture the 4 variables from the vanilla UI using def after_component():
```
    def after_component(self, component, **kwargs):
        if component.elem_id == "txt2img_width":
            self.txt2img_w_slider = component
            return self.txt2img_w_slider
        if component.elem_id == "txt2img_height":
            self.txt2img_h_slider = component
            return self.txt2img_h_slider
        if component.elem_id == "img2img_width":
            self.img2img_w_slider = component
            return self.img2img_w_slider
        if component.elem_id == "img2img_height":
            self.img2img_h_slider = component
            return self.img2img_h_slider
```
There might be a better way to hook the vanilla UI components, but like I said, I'm not a wizard. All the above function does is capture the UI components (in this case the w/h sliders) so the class variables are pointed to them.

Add the button...
```
        if is_img2img: tabstring = "img2img"
        else: tabstring = "txt2img"
        send_dimen_button = gr.Button(value=f"Send dimensions to {tabstring}")
```
This function returns the shape of the image to the two sliders if the image input is valid:
```
        def send_dimensions(image):
            if(image):
                interm = np.asarray(image.get('image'))
                return gr.Slider.update(value=interm.shape[0]), gr.Slider.update(value=interm.shape[1])
            else:
                return gr.Slider.update(), gr.Slider.update()
```
Here are the listeners. The outputs are assigned differently depending on whether the img2img tab is selected or not:
```
        if is_img2img:
            send_dimen_button.click(fn=send_dimensions, inputs=[input_image], outputs=[self.img2img_w_slider, self.img2img_h_slider])
        else:
            send_dimen_button.click(fn=send_dimensions, inputs=[input_image], outputs=[self.txt2img_w_slider, self.txt2img_h_slider])
```
![image](https://user-images.githubusercontent.com/93007558/221388442-c9f01f8f-df07-4f8d-9193-fbb7767638c9.png)

**Comment by marcsyp** [comment]
This is great Lonica! Any chance we could get a multiplier slider as well? Often I'll have a 1920x1080 image but I want to generate at 960x540 so a 0.5 slider with a preview of the cosplayed result that you can send to the image dimensions would be awesome. Thanks!

**Comment by Mikubill** [comment]
Maybe we could make changes based on GL's PR: #336

**Comment by Alchete** [comment]
@LonicaMewinsky Excellent!  I was playing with a button on the top row for the same purpose, but since tooltips are so difficult with this toolkit your implementation seems more obvious for end users.

![image](https://user-images.githubusercontent.com/4705189/221391503-7595136b-87e6-49b1-bebd-4f7aac50a492.png)

I would only note that your Width and Height seem reversed.  That picture seems landscape.  Separately I noticed that Gradio seems to report "height" first, not "width".

Cheers.

**Comment by LonicaMewinsky** [comment]
Derp, thanks. Totally reversed w/h.

Definitely like the toolbutton more.

**Comment by Alchete** [comment]
@LonicaMewinsky Good collaboration.  You have good UX instincts. :)

@marcsyp I think the next step is to implement a "lock" aspect ratio feature in base A1111, like most image editing programs have, rather than implement the slider here.

Imagine if this were a "lock icon".  Then one could enter a number or adjust the sliders and it would just work even if it didn't come from ControlNet.

![image](https://user-images.githubusercontent.com/4705189/221392290-4b21cca4-d78f-4e65-9913-06690834225b.png)

**Comment by missionfloyd** [comment]
> since tooltips are so difficult

Copy https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/javascript/hints.js to `sd-webui-controlnet/javascript` and edit it accordingly.

**Comment by Alchete** [comment]
> > since tooltips are so difficult
> 
> Copy https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/javascript/hints.js to `sd-webui-controlnet/javascript` and edit it accordingly.

How does that work for Extensions?  How do we provide tooltips for ControlNet?

**Comment by missionfloyd** [comment]
Just erase what's there and fill in your own. It goes `"Control Text": "Tooltip"`

```javascript
titles = {
    "Enable": "Enable ControlNet",
    "\u{1f53c}", "Send dimensions to text2img",
    // etc...
}
```

**Comment by GeorgLegato** [comment]
Hi all,
i have implemented the input-image-size inside of the "(svg)preprocess" method and using the Canvas-Width/Height Sliders to indicate the height/widgt to the user. So no extra html/javascript etc.
we have a clash of concepts.
@Mikubill please deceide which concept to follow:
a) re-use of canvas-sliders (mine)
b) add additional buttons/boxes for height/width/ (this)

**Comment by GeorgLegato** [comment]
> Just replace what's there with your own. It goes `"Control Text": "Tooltip"`
> 
> ```js
> titles = {
>     "Enable": "Enable ControlNet",
>     "\u{1f53c}": "Send dimensions to txt2img",
>     // etc...
> }
> ```

Gradio would offer another, low level option: using custom _css style per gradio.component and there you define ":hover" class. but have a central textfile is better, esp. for localization issues

**Comment by LonicaMewinsky** [comment]
@Alchete, I haven't seen any better ideas or work since I forked with the "send dimensions" button, so I just made a PR that adds a ToolButton: 
![image](https://user-images.githubusercontent.com/93007558/221990985-d71fa50e-4716-49aa-b676-7042b10a2a16.png)

I've also got an extension that locks the dimensions of the sliders, but I don't think this is something that should be folded into ControlNet. Way out of scope.

**Comment by Alchete** [comment]
@LonicaMewinsky Thanks.  Go for it,  Even sending the dimensions would be a huge upgrade.

I've got working, stand-alone code that locks the W/H sliders, however, when placing it into the base A1111 UI it's really, really slow.  I also had issues trying to use the "variant" parameter of the Gradio button, which would perfectly emulate a toggle button, but the A1111 UI blows up when using it.

Do you want to continue that discussion over there?  Here's my issue submission, showing some trials and issues.  If you hop over there we can compare our solutions.  And maybe you have some ideas on the issues encountered.  Cheers
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/8063
