### ISSUE TITLE
traceback error on startup

### ISSUE THREAD

**Issue by gsgoldma** [Mikubill/sd-webui-controlnet#38]
─ Traceback (most recent call last) ────────────────────────────────╮
│ D:\stable-diffusion-webui\launch.py:361 in <module>                                              │
│                                                                                                  │
│   358                                                                                            │
│   359 if __name__ == "__main__":                                                                 │
│   360 │   prepare_environment()                                                                  │
│ ❱ 361 │   start()                                                                                │
│   362                                                                                            │
│                                                                                                  │
│ D:\stable-diffusion-webui\launch.py:356 in start                                                 │
│                                                                                                  │
│   353 │   if '--nowebui' in sys.argv:                                                            │
│   354 │   │   webui.api_only()                                                                   │
│   355 │   else:                                                                                  │
│ ❱ 356 │   │   webui.webui()                                                                      │
│   357                                                                                            │
│   358                                                                                            │
│   359 if __name__ == "__main__":                                                                 │
│                                                                                                  │
│ D:\stable-diffusion-webui\webui.py:205 in webui                                                  │
│                                                                                                  │
│   202 │   │                                                                                      │
│   203 │   │   modules.script_callbacks.before_ui_callback()                                      │
│   204 │   │                                                                                      │
│ ❱ 205 │   │   shared.demo = modules.ui.create_ui()                                               │
│   206 │   │                                                                                      │
│   207 │   │   if cmd_opts.gradio_queue:                                                          │
│   208 │   │   │   shared.demo.queue(64)                                                          │
│                                                                                                  │
│ D:\stable-diffusion-webui\modules\ui.py:458 in create_ui                                         │
│                                                                                                  │
│    455 │   parameters_copypaste.reset()                                                          │
│    456 │                                                                                         │
│    457 │   modules.scripts.scripts_current = modules.scripts.scripts_txt2img                     │
│ ❱  458 │   modules.scripts.scripts_txt2img.initialize_scripts(is_img2img=False)                  │
│    459 │                                                                                         │
│    460 │   with gr.Blocks(analytics_enabled=False) as txt2img_interface:                         │
│    461 │   │   txt2img_prompt, txt2img_prompt_styles, txt2img_negative_prompt, submit, _, _, tx  │
│                                                                                                  │
│ D:\stable-diffusion-webui\modules\scripts.py:270 in initialize_scripts                           │
│                                                                                                  │
│   267 │   │   auto_processing_scripts = scripts_auto_postprocessing.create_auto_preprocessing_   │
│   268 │   │                                                                                      │
│   269 │   │   for script_class, path, basedir, script_module in auto_processing_scripts + scri   │
│ ❱ 270 │   │   │   script = script_class()                                                        │
│   271 │   │   │   script.filename = path                                                         │
│   272 │   │   │   script.is_txt2img = not is_img2img                                             │
│   273 │   │   │   script.is_img2img = is_img2img                                                 │
│                                                                                                  │
│ D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py:115 in __init__   │
│                                                                                                  │
│   112 │   │   │   "depth": midas,                                                                │
│   113 │   │   │   "hed": hed,                                                                    │
│   114 │   │   │   "mlsd": mlsd,                                                                  │
│ ❱ 115 │   │   │   "normal_map": midas_normal,                                                    │
│   116 │   │   │   "openpose": openpose,                                                          │
│   117 │   │   │   "openpose_hand": openpose_hand,                                                │
│   118 │   │   │   "fake_scribble": fake_scribble,                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
NameError: name 'midas_normal' is not defined

**Comment by Mikubill** [comment]
Try run `git pull` in `extensions\sd-webui-controlnet` and restart again may help

**Comment by gsgoldma** [comment]
just restarting fixed it i guess
