### ISSUE TITLE
RuntimeError: The size of tensor a (768) must match the size of tensor b (1024) at non-singleton dimension 1

### ISSUE THREAD

**Issue by OneLittleWolf** [Mikubill/sd-webui-controlnet#385]
When I use ControlNet, regardless of image size (i.e. 512x512 or 512x768) when run it in txt2img I see my RAM usage climbing all the way up so all 32GB are used, and 50GB+ of "Private Bytes" are in use and it takes a long time to run. Eventually it releases resources to the computer, and completes the image but not before stating the following:

Error running process: C:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "C:\stable-diffusion\stable-diffusion-webui\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "C:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 571, in process
    else self.build_control_model(p, unet, model, lowvram)
  File "C:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 446, in build_control_model
    network = network_module(
  File "C:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\cldm.py", line 90, in __init__
    p_new = p + unet_state_dict[key_name].clone().cpu()
RuntimeError: The size of tensor a (768) must match the size of tensor b (1024) at non-singleton dimension 1

Also, no depth map (or canny if I try that) is displayed alongside the image. Updated ControlNet, closed and restarted SD completely. ControlNet version: 

c16489c0 (Sun Feb 26 03:08:03 2023)

**Comment by thulle** [comment]
@OneLittleWolf what model are you trying to use? This looks like the error I got when I tried using it with SD2

**Comment by OneLittleWolf** [comment]
> @OneLittleWolf what model are you trying to use? This looks like the error I got when I tried using it with SD2

@thulle Good call! I was using v2 models. This issue doesn't happen on a v1.5 model I tried. Also updated ControlNet this morning, still an issue with v2 models. Version:

0c45b5ad (Sun Feb 26 18:37:20 2023)

**Comment by brianebeling** [comment]
Hey, SD 2.X models are not supported at the moment due to the difference in model architecture. SD 1.5 models are though. Also be careful to not use an inpaint model, even if it is SD 1.5, you will receive the same mismatch in tensors then. Hopefully that will be added to ControlNet as inpainting models can perform substantially better inpainting specific tasks.

**Comment by OneLittleWolf** [comment]
> Hey, SD 2.X models are not supported at the moment due to the difference in model architecture. SD 1.5 models are though. Also be careful to not use an inpaint model, even if it is SD 1.5, you will receive the same mismatch in tensors then. Hopefully that will be added to ControlNet as inpainting models can perform substantially better inpainting specific tasks.

@brianebeling Thanks! I didn't even know there were inpainting models.

**Comment by OneLittleWolf** [comment]
It would also be great (I guess I should put in a feature request) to see, next to the model picker field, what version of model it is (1.x/2.x). I'm sure that will come eventually.
