### ISSUE TITLE
[Feature Request] Add generating hand depth map tab

### ISSUE THREAD

**Issue by Fannovel16** [Mikubill/sd-webui-controlnet#388]
Quote from [Twitter user @toyxyz3](https://twitter.com/toyxyz3/status/1629620938894643200?s=20):
> By separately rendering the hand mesh depth and open pose bones and inputting them to Multi-ControlNet, various poses and character images can be generated while controlling the fingers more precisely.

Example results (credit to toyxyz3):
![](https://pbs.twimg.com/media/Fp2O7VVaIAErOnq?format=jpg&name=orig)
![](https://pbs.twimg.com/media/Fp2PSeEakAAT6Fc?format=jpg&name=orig)
![](https://pbs.twimg.com/media/Fp2PB33aYAA5xh4?format=jpg&name=orig)
![](https://pbs.twimg.com/media/Fp2O1Z8aMAAIdqL?format=jpg&name=orig)

I have a idea to get hand mesh depth map automatically from an image: 
Use Openpose to get hands location -> process that image through MiDaS -> Crop hand images from depth map -> Paste them to a black canvas

Can it be implemented to this repo? I can't implement it due to the complexity of the code.
P/s: Ig this function get hands location: https://github.com/Mikubill/sd-webui-controlnet/blob/c16489c0182f15c19ad3570b3e4352d99efd0ae1/annotator/openpose/util.py#L94

**Comment by demirklvc** [comment]
Wow! this might fix the hand issue forever

**Comment by coding2themoon** [comment]
sad, too much vram required.

**Comment by Observerspy** [comment]
fantastic!

**Comment by Zvandaa** [comment]
wow !

**Comment by Zvandaa** [comment]
hi~我是周曦文~您的邮件我已经收到。
