### ISSUE TITLE
[Feature Request] Support MultiControlNet in XYZplot script

### ISSUE THREAD

**Issue by deklesen** [Mikubill/sd-webui-controlnet#392]
It would be nice if we could have support for multicontrolnet in the XYZplot script.
I.e. if you have two models you should have separate entries in the XYZplot, e.g. "[ControlNet Model - 1] Weight".

Related issue that added XYZ for single model:
https://github.com/Mikubill/sd-webui-controlnet/issues/96

**Comment by ljleb** [comment]
The api will soon allow for an arbitrary amount of controlnet models to be used simultaneously, so we might need a way to specify a number greater than the 1 - 10 range for the controlnet processing unit id in x/y/z grid keys.

Maybe supporting only processing units 1 to 10 in x/y/z grid would be acceptable? I'm guessing 10*processing unit parameters could clutter the x/y/z grid dropdown options quite a lot. Maybe what this needs is something like an additional small text field to appear besides the x/y/z option dropdown when selecting any of the "[ControlNet] ..." options? Specify `1` to `10` to pick a specific controlnet processing unit, and `*` to alternate the selected parameter on all the processing units simultaneously maybe? Not sure if this is the right way to do it or if it can be implemented easily.

**Comment by aiton-sd** [comment]
We are modifying it to support multi-controlnet without increasing menu items by enabling list notation.👍

**Comment by aiton-sd** [comment]
If this pull request is approved, lists will be enabled.
#407
