### ISSUE TITLE
[Bug]: When Posting /controlnet/txt2img generate image, causing Web-UI and other API blocked.

### ISSUE THREAD

**Issue by DiaoDaiaChan** [Mikubill/sd-webui-controlnet#400]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Posting /controlnet/txt2img.
I discovered that when API processing control images, You can not load WebUI or using other API

Posting /sdapi/v1/txt2img will not happen, you can still using other API and loading WebUI

My English is poor, if you can not understand my expression. 
Here is video :D

https://drive.google.com/file/d/1bJjlqSWIRFklaXk98inxW_Fs-eu3cO6k/view?usp=sharing

### Steps to reproduce the problem

1. Posting API /controlnet/txt2img
2. Try to get /sdapi/v1/progress 
![WYS4XL55%NGTH{8`J$67%Q9](https://user-images.githubusercontent.com/126318917/221462707-008c8193-dadf-4dc2-aec3-c408f881b099.png)
(loading until control draw image complete.)
by the way, other API is NOT available too
3. When I try to refresh WebUI, I discovered that WebUI is blocked (refresh sucessfully after control draw image complete)
4. ...

### What should have happened?

Posting /controlnet/txt2img.
get /sdapi/v1/progress or refresh WebUI successfully during control net drawing image.

I'm writing a simple load balance program to hand out task to different backend.

although there are many ways to check backend is available or not. But using bulit-in API can make it simple and more controlable.

### Commit where the problem happens

webui:0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8\t\t
controlnet:0c45b5ad6b9482e8e4eb580fd69b11bbe482c5d2\t

### Command Line Arguments

```Shell
--api --xformers --disable-safe-unpickle --listen --enable-insecure-extension-access
```

### Console logs

```Shell
When using commit 9831aa3006d30b9d94085b2f653b8a3554de0dce no errors occur,but API/WebUI still blocked 


The error below occur when using commit 0c45b5ad6b9482e8e4eb580fd69b11bbe482c5d2
but, It semms no releative?

Error running process_batch: C:\Users\43701\github\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py
Traceback (most recent call last):
  File "C:\Users\43701\github\stable-diffusion-webui\modules\scripts.py", line 395, in process_batch
    script.process_batch(p, *script_args, **kwargs)
  File "C:\Users\43701\github\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 158, in process_batch
    if not args[0]:
IndexError: tuple index out of range
```

**Comment by Mikubill** [comment]
Pending fix: https://github.com/Mikubill/sd-webui-controlnet/pull/384

**Comment by ljleb** [comment]
Could you test again with the latest commit? The controlnet routes have been updated to use the original webui txt2img and img2img routes under `/sdapi/v1`.

**Comment by DiaoJSC** [comment]
> Could you test again with the latest commit? The `/controlnet` routes have been updated to use the original `/sdapi/v1` txt2img and img2img routes under the hood.

My pleasure
After my test, the newest commit work perfectly!!
Thank everyone for their efforts!
:D
