### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by enn-nafnlaus** [Mikubill/sd-webui-controlnet#406]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Simple task: the default maximum dimensions for ControlNet images are far too small - especially given that ControlNet, by means of forcing the model to specific geometry, can be run at dimensions far higher than the underlying model's native dimensions.  It should be increased to at least 2048x2048, like AUTOMATIC1111 itself, which would allow dimensions like 1920x108[8], 1600x1200, etc.  Better yet would be to allow it to be user-configured.

(Great work, BTW!)

### Steps to reproduce the problem

Look at the resolution.

### What should have happened?

It should not be limited so low.

### Commit where the problem happens

All

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
None needed
```

**Comment by enn-nafnlaus** [comment]
> As far i understand, the size is driven by the gui settings, not the canvas. Thats just for scribbles.

If you mean the limits on what values can be entered, no, they don't match the gui's resolution limits.

**Comment by AbyszOne** [comment]
> > As far i understand, the size is driven by the gui settings, not the canvas. Thats just for scribbles.
> 
> If you mean the limits on what values can be entered, no, they don't match the gui's resolution limits.

Resolution depends on normal img2img/txt2img settings. The canvas resolution is for scribbles, not the final output.

**Comment by enn-nafnlaus** [comment]
So if someone pastes in or uploads an image, it doesn't get downscaled? Are you sure?

**Comment by AbyszOne** [comment]
At least im sure that the 3 resize options into controlnet works with the main parameters, not the canvas. You can use any aspect ratio and size witout touching that parameters at all. The owner must confirm it, but so far for me that parameters are the same as inexistent in my workflow.

**Comment by ljleb** [comment]
The width and height sliders are only used by the `Create Blank Canvas` button. The sliders are a bit confusing at the moment, this has been discussed here:

https://github.com/Mikubill/sd-webui-controlnet/issues/186#issuecomment-1435665154

**Comment by AbyszOne** [comment]
> The width and height sliders are only used by the `Create Blank Canvas` button. The sliders are a bit confusing at the moment, this has been discussed here:
> 
> [#186 (comment)](https://github.com/Mikubill/sd-webui-controlnet/issues/186#issuecomment-1435665154)

Its confusing indeed. I think it would be better as an extensible option. So you only see the parameters if you need it, and most people dont get lose about.

**Comment by GeorgLegato** [comment]
check my PR #336, where ratio of input size is considered and actually ignore the slider maximal values.
then the user find quick button to scale down his input image to 512/768 height or width
