### ISSUE TITLE
When i post to the webui in api mode, controlnet/img2img doesnt work properly 

### ISSUE THREAD

**Issue by GibsonHu** [Mikubill/sd-webui-controlnet#408]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When i post to the api on http://127.0.0.1:7860/controlnet/img2img , when using, webui.py --nowebui, the output image i get is identical to my input image (using any modules). 

However when i post to http://127.0.0.1:7861/controlnet/img2img, running the web GUI, i get the correct image results.

How come it doesnt work for the api mode of webui.py?

Much help would be appreciated, Thanks

### Steps to reproduce the problem

post on http://127.0.0.1:7860/controlnet/img2img
output image same as original

post on http://127.0.0.1:7861/controlnet/img2img
output image is correct

### What should have happened?

output image should have been updated using api mode

### Commit where the problem happens

webui:\t\t
controlnet:\t

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
webui.py --nowebui

and

webui.py
```

### Console logs

```Shell
console logs dont show anything wrong happening
```

**Comment by ljleb** [comment]
Ah I didn't test with --nowebui, will investigate.

**Comment by ljleb** [comment]
Can you verify that you are using the latest version of the extension? I could not reproduce with the latest commit.
