### ISSUE TITLE
clarify the install procedure to install inside venv

### ISSUE THREAD

**Issue by sould3mon** [Mikubill/sd-webui-controlnet#409]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

i saw a youtube video and he followed your instructions exactly
installing opencv  to the system python (and telling people to do this )

but  this should do nothing for the python enviroment stable diffusion is using 
 i am pretty sure it's ment to be done inside the virtual enviroment
 ( since you are hinting at upgrading gradio wich should only exist inside the venv)

hope to save some people  making their system install dirty  by installing stuff that never gets used

### Steps to reproduce the problem

..

### What should have happened?

..

### Commit where the problem happens

..

### Command Line Arguments

```Shell
..
```

### Console logs

```Shell
..
```

**Comment by ljleb** [comment]
the webui installs `opencv-contrib-python` on its own in the venv. It seems that you don't need to install `opencv-python` when the contrib version is installed:
https://stackoverflow.com/a/67687886
