### ISSUE TITLE
Can we mix amd match preprocessors with models?

### ISSUE THREAD

**Issue by gsgoldma** [Mikubill/sd-webui-controlnet#41]
it seems that some have the same names as the models. not sure which are compatible or how they interact

**Comment by Mikubill** [comment]
Compatible, just match and use.

**Comment by gsgoldma** [comment]
Okay. But since I can use the models without preprocessors, how do they affect the results? I don't see any information about them.

**Comment by toyxyz** [comment]
Since there are times when models are used without preprocessors, it would be nice to have a separate option. "Enable/Disable Auto preprocessors"

**Comment by gsgoldma** [comment]
So does the preprcessor just affect the scribble image to the right? and the model the image on the left that it produces? Because I think I'm more confused than I was before. Each preprocessor seems to do what the models can do too, or am I wrong about that?
