### ISSUE TITLE
TypeError: ControlParams.__init__() takes 9 positional arguments but 10 were given

### ISSUE THREAD

**Issue by soulhighwing** [Mikubill/sd-webui-controlnet#411]
just upgraded my controlNet,trying to test the new multi controlnet funciton. but here comes an error. Any help?
**NOT A BUG!!!!RESTART YOUR SERVER TO SLOVE THE PROBLEM**
Loading model: control_openpose-fp16 [9ca67cc5]
Loaded state_dict from [C:\stable-diffusion-webui\extensions\sd-webui-controlnet\models\control_openpose-fp16.safetensors]
ControlNet model control_openpose-fp16 [9ca67cc5] loaded.
Loading preprocessor: openpose
Error running process: C:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "C:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 669, in process
    forward_param = ControlParams(model_net, control, guess_mode, weight, False, guidance_start, guidance_end, None, isinstance(model_net, PlugableAdapter))
TypeError: ControlParams.__init__() takes 9 positional arguments but 10 were given

**Comment by QuantD-VAM** [comment]
same error here ... since the last update a couple of minutes ago:
```
Error running process: G:\Automatic1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "G:\Automatic1111\stable-diffusion-webui\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "G:\Automatic1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 669, in process
    forward_param = ControlParams(model_net, control, guess_mode, weight, False, guidance_start, guidance_end, None, isinstance(model_net, PlugableAdapter))
TypeError: ControlParams.__init__() takes 9 positional arguments but 10 were given
```
version: fc8a8855 (Mon Feb 27 10:32:23 2023)

this is a show stopping bug since controlNet is not working anymore in A1111

**Comment by soulhighwing** [comment]
I figured, need to restart your server

**Comment by QuantD-VAM** [comment]
here is my A1111 version: python: 3.10.9  •  torch: 1.13.1+cu117  •  xformers: 0.0.16rc425  •  gradio: 3.16.2  •  commit: [0cc0ee1b](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8)  •  checkpoint: [c35782bad8](https://google.com/search?q=c35782bad87a6c8d461fa88861d9ee6974d7a16cc19014bfaf89f586dd42ca63)

**Comment by QuantD-VAM** [comment]
> I figured, need to restart your server

yes that works .. thanks. Everybody updating controlNet via WebUI A1111 will run into this issue if they just restart the UI. You really need to shut down the instance and reopen it.

**Comment by leonearts** [comment]
> I figured, need to restart your server

Worked for me :)
