### ISSUE TITLE
[Bug]: API can't use any custom image as input, independent of model.

### ISSUE THREAD

**Issue by dermesut** [Mikubill/sd-webui-controlnet#414]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Since using the latest version. Only concerns API. WebUi version works as expected.
When i try to use a custom input, e.g. a custom depth map, I receive the following message (see section Console logs)

### Steps to reproduce the problem

1. Go to .... "controlnet_units": "input_image": "here's my custom input image"
2. Press .... api-request procedure
3. ... enjoy error message

### What should have happened?

I should be able to use a custom (e.g.) depth map.

### Commit where the problem happens

webui:\t\t 0cc0ee1b
controlnet:\t 0fe4907b (Mon Feb 27 15:31:48 2023)

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--medvram --allow-code --xformers --api --api-log --port 7861 --device-id 1
```

### Console logs

```Shell
Error running process: (...)\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "(...)\sd.webui\webui\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "(...)\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 604, in process
    if not ((image['mask'][:, :, 0]==0).all() or (image['mask'][:, :, 0]==255).all()):
IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed
```

**Comment by ljleb** [comment]
Found the bug, only grayscale images are affected by this.

**Comment by dermesut** [comment]
I just realized: if I let the controlnet_module create a depth map and use that as my custom depth image, without changing anything else, the error does not appear.
Once I put in an image other than a controlnet generated one, the error comes back.

This is the request, that's being sent with a controlnet generated image, that is then used as a custom input image (not generating an error):
{"images": ["...", "..."], "parameters": {"init_images": null, "resize_mode": 1, "denoising_strength": 1.0, "image_cfg_scale": null, "mask": null, "mask_blur": 0, "inpainting_fill": 0, "inpaint_full_res": false, "inpaint_full_res_padding": 32, "inpainting_mask_invert": 0, "initial_noise_multiplier": null, "prompt": "a nice loft", "styles": [""], "seed": -1, "subseed": -1, "subseed_strength": 0.0, "seed_resize_from_h": -1, "seed_resize_from_w": -1, "sampler_name": null, "batch_size": 1, "n_iter": 1, "steps": 20, "cfg_scale": 7.0, "width": 512, "height": 768, "restore_faces": false, "tiling": false, "negative_prompt": "", "eta": 0.0, "s_churn": 0.0, "s_tmax": 0.0, "s_tmin": 0.0, "s_noise": 1.0, "override_settings": {}, "override_settings_restore_afterwards": true, "script_args": [], "sampler_index": "Euler a", "include_init_images": false, "script_name": null}, "info": "{\"prompt\": \"a nice loft\", \"all_prompts\": [\"a nice loft\"], \"negative_prompt\": \"\", \"all_negative_prompts\": [\"\"], \"seed\": 3712550745, \"all_seeds\": [3712550745], \"subseed\": 3641065144, \"all_subseeds\": [3641065144], \"subseed_strength\": 0.0, \"width\": 512, \"height\": 768, \"sampler_name\": \"Euler a\", \"cfg_scale\": 7.0, \"steps\": 20, \"batch_size\": 1, \"restore_faces\": false, \"face_restoration_model\": null, \"sd_model_hash\": \"c35782bad8\", \"seed_resize_from_w\": -1, \"seed_resize_from_h\": -1, \"denoising_strength\": 1.0, \"extra_generation_params\": {\"ControlNet Enabled\": true, \"ControlNet Module\": \"none\", \"ControlNet Model\": \"control_sd15_depth [fef5e48e]\", \"ControlNet Weight\": 1.0, \"ControlNet Guidance Start\": 0.0, \"ControlNet Guidance End\": 1.0, \"Eta\": 0.0}, \"index_of_first_image\": 0, \"infotexts\": [\"a nice loft\\nSteps: 20, Sampler: Euler a, CFG scale: 7.0, Seed: 3712550745, Size: 512x768, Model hash: c35782bad8, Model: realisticVisionV13_v13VAEIncluded, Seed resize from: -1x-1, Denoising strength: 1.0, ControlNet Enabled: True, ControlNet Module: none, ControlNet Model: control_sd15_depth [fef5e48e], ControlNet Weight: 1.0, ControlNet Guidance Start: 0.0, ControlNet Guidance End: 1.0, Eta: 0.0\"], \"styles\": [\"\"], \"job_timestamp\": \"20230227202433\", \"clip_skip\": 1, \"is_using_inpainting_conditioning\": false}"}

This is the corresponding json-payload (not generating an error):
"{\"controlnet_units\": [{\"input_image\": \"iVBOR...\", \"mask\": \"\", \"module\": \"none\", \"model\": \"control_sd15_depth [fef5e48e]\", \"weight\": 1.0, \"resize_mode\": \"Scale to Fit (Inner Fit)\", \"lowvram\": false, \"processor_res\": 512, \"threshold_a\": 0, \"threshold_b\": 0, \"guidance\": 1.0, \"guidance_start\": 0, \"guidance_end\": 1.0, \"guessmode\": false}], \"override_settings\": {}, \"override_settings_restore_afterwards\": true, \"init_images\": [\"data:image/png;base64,iVBOR...\"], \"resize_mode\": \"1\", \"denoising_strength\": \"1.0\", \"mask\": null, \"mask_blur\": \"0\", \"inpainting_fill\": \"0\", \"inpaint_full_res\": false, \"inpaint_full_res_padding\": \"32\", \"inpainting_mask_invert\": \"0\", \"prompt\": \"a nice loft\", \"styles\": [\"\"], \"seed\": -1, \"subseed\": -1, \"subseed_strength\": 0, \"seed_resize_from_h\": -1, \"seed_resize_from_w\": -1, \"batch_size\": 1, \"n_iter\": 1, \"steps\": \"20\", \"cfg_scale\": \"7.0\", \"width\": \"512\", \"height\": \"768\", \"restore_faces\": false, \"tiling\": false, \"negative_prompt\": \"\", \"eta\": 0, \"s_churn\": 0, \"s_tmax\": 0, \"s_tmin\": 0, \"s_noise\": 1, \"sampler_index\": \"Euler a\"}"

This is the request, that's being sent with an individually generated image, that is then used as a custom input image (generating an error):
{"images": ["..."], "parameters": {"init_images": null, "resize_mode": 1, "denoising_strength": 1.0, "image_cfg_scale": null, "mask": null, "mask_blur": 0, "inpainting_fill": 0, "inpaint_full_res": false, "inpaint_full_res_padding": 32, "inpainting_mask_invert": 0, "initial_noise_multiplier": null, "prompt": "a nice loft", "styles": [""], "seed": -1, "subseed": -1, "subseed_strength": 0.0, "seed_resize_from_h": -1, "seed_resize_from_w": -1, "sampler_name": null, "batch_size": 1, "n_iter": 1, "steps": 20, "cfg_scale": 7.0, "width": 512, "height": 768, "restore_faces": false, "tiling": false, "negative_prompt": "", "eta": 0.0, "s_churn": 0.0, "s_tmax": 0.0, "s_tmin": 0.0, "s_noise": 1.0, "override_settings": {}, "override_settings_restore_afterwards": true, "script_args": [], "sampler_index": "Euler a", "include_init_images": false, "script_name": null}, "info": "{\"prompt\": \"a nice loft\", \"all_prompts\": [\"a nice loft\"], \"negative_prompt\": \"\", \"all_negative_prompts\": [\"\"], \"seed\": 701433282, \"all_seeds\": [701433282], \"subseed\": 3871297427, \"all_subseeds\": [3871297427], \"subseed_strength\": 0.0, \"width\": 512, \"height\": 768, \"sampler_name\": \"Euler a\", \"cfg_scale\": 7.0, \"steps\": 20, \"batch_size\": 1, \"restore_faces\": false, \"face_restoration_model\": null, \"sd_model_hash\": \"c35782bad8\", \"seed_resize_from_w\": -1, \"seed_resize_from_h\": -1, \"denoising_strength\": 1.0, \"extra_generation_params\": {\"ControlNet Enabled\": true, \"ControlNet Module\": \"none\", \"ControlNet Model\": \"control_sd15_depth [fef5e48e]\", \"ControlNet Weight\": 1.0, \"ControlNet Guidance Start\": 0.0, \"ControlNet Guidance End\": 1.0, \"Eta\": 0.0}, \"index_of_first_image\": 0, \"infotexts\": [\"a nice loft\\nSteps: 20, Sampler: Euler a, CFG scale: 7.0, Seed: 701433282, Size: 512x768, Model hash: c35782bad8, Model: realisticVisionV13_v13VAEIncluded, Seed resize from: -1x-1, Denoising strength: 1.0, ControlNet Enabled: True, ControlNet Module: none, ControlNet Model: control_sd15_depth [fef5e48e], ControlNet Weight: 1.0, ControlNet Guidance Start: 0.0, ControlNet Guidance End: 1.0, Eta: 0.0\"], \"styles\": [\"\"], \"job_timestamp\": \"20230227202610\", \"clip_skip\": 1, \"is_using_inpainting_conditioning\": false}"}

The corresponding json-payload (generating an error):
"{\"controlnet_units\": [{\"input_image\": \"iVBOR...\", \"mask\": \"\", \"module\": \"none\", \"model\": \"control_sd15_depth [fef5e48e]\", \"weight\": 1.0, \"resize_mode\": \"Scale to Fit (Inner Fit)\", \"lowvram\": false, \"processor_res\": 512, \"threshold_a\": 0, \"threshold_b\": 0, \"guidance\": 1.0, \"guidance_start\": 0, \"guidance_end\": 1.0, \"guessmode\": false}], \"override_settings\": {}, \"override_settings_restore_afterwards\": true, \"init_images\": [\"data:image/png;base64,iVBOR...\"], \"resize_mode\": \"1\", \"denoising_strength\": \"1.0\", \"mask\": null, \"mask_blur\": \"0\", \"inpainting_fill\": \"0\", \"inpaint_full_res\": false, \"inpaint_full_res_padding\": \"32\", \"inpainting_mask_invert\": \"0\", \"prompt\": \"a nice loft\", \"styles\": [\"\"], \"seed\": -1, \"subseed\": -1, \"subseed_strength\": 0, \"seed_resize_from_h\": -1, \"seed_resize_from_w\": -1, \"batch_size\": 1, \"n_iter\": 1, \"steps\": \"20\", \"cfg_scale\": \"7.0\", \"width\": \"512\", \"height\": \"768\", \"restore_faces\": false, \"tiling\": false, \"negative_prompt\": \"\", \"eta\": 0, \"s_churn\": 0, \"s_tmax\": 0, \"s_tmin\": 0, \"s_noise\": 1, \"sampler_index\": \"Euler a\"}"
