### ISSUE TITLE
ControlNet Not Working In Text To Image

### ISSUE THREAD

**Issue by vienduong88** [Mikubill/sd-webui-controlnet#426]
Hello, I don't know why ControlNet doesn't work in text2Img, but it works in img2img.
![image](https://user-images.githubusercontent.com/33787514/221938959-4d8ce2b2-bb92-4ead-ad9a-02b67fc492a5.png)
Annotator result always be black or white, it doesn't use the input open pose.
I appreciate your help. Thank you!

**Comment by efwds** [comment]
I meet the same problem. who can fix it?

**Comment by vienduong88** [comment]
So the openpose preprocess detection works in img2img but when I use pose image from openpose editor it can't use it at input pose, result in black annotator.

**Comment by Semanual** [comment]
@efwds @vienduong88 that's on the browser, canvas has no permission to export the image or something like this, for me it was solved by disabling "Canvas Fingerprint Defender"
#302

**Comment by efwds** [comment]
@Semanual Thank you very much! This issue confused me about one month. Hope you have a good health in now and future!

**Comment by DeahtKalif** [comment]
> @efwds @vienduong88 that's on the browser, canvas has no permission to export the image or something like this, for me it was solved by disabling "Canvas Fingerprint Defender" #302

what is "canvas fingerprint defender"?

**Comment by Semanual** [comment]
that's a privacy extension, I guess you don't have it
that was my case, try using another browser or disabling any extension that could alter canvas working

**Comment by midcoastal** [comment]
Running OpenPose in Chrome and Firefox, both in standard and Incognito/Private, and it still does not work.  I do have uBlock and ScriptSafe installed on both browsers, but I have additionally disabled them, and still Black Annotator result...
