### ISSUE TITLE
controlnet models keep getting reloaded after every api request although the parameters are the same between the requests!

### ISSUE THREAD

**Issue by samsal** [Mikubill/sd-webui-controlnet#429]
the controlnet models keep getting reloaded again and again but the settings are kept the same between the api requests. It wastes alot of time!
![image](https://user-images.githubusercontent.com/4302694/221984474-0190619f-2b57-479c-852e-4a28e11e1202.png)

**Comment by samsal** [comment]
Same thing from the GUI. I updated the extension today and I'm not sure which version I had before, but this problem was not there before.

**Comment by Mikubill** [comment]
Have you checked the model cache size in settings? Using cache size 0 will always trigger reload on generation.

**Comment by peteallen** [comment]
I believe this is related to and possibly duplicates #375.

**Comment by peteallen** [comment]
> Have you checked the model cache size in settings? Using cache size 0 will always trigger reload on generation.

This worked, thank you. The cache size was set at 2, and I'm only using 2 ControlNet models, so I'm not sure why it was a problem. But increasing this value solved the problem for me. In fact, I have the model size limit set to 2, so I'm certain I wasn't using more. This behavior started a few days ago with no changes to my ControlNet settings.

For anyone else trying to fix this in Automatic1111 WebUI:

1. Go to the Settings tab
2. Choose ControlNet on the left
3. Increase the slider value for "Model cache size (requires restart)"

**Comment by samsal** [comment]
> Have you checked the model cache size in settings? Using cache size 0 will always trigger reload on generation.

Yes it was set at 2. I increased it to 5 on the latest version of the extension but it didn't change anything. 
Unlike @peteallen for me even after increasing the "Model cache size" proprocessor and model are still being reloaded. 
This definitly was not the case before I did the update yesterday (unfortunatly I don't know with which commit this was introduced because I didn't update the extension for a few days before yesterday)

**Comment by samsal** [comment]
After some debugging I found out that `self.latest_model_hash` and `self.model_cache` do not keep their values between requests. I'm not sure why that is because I'm not familiar with the code, but I will try to find out more.

**Comment by Petas3** [comment]
I am a python noob yet I have figured out you need to make the 2 variables static on the class, then it works for api.
![image](https://user-images.githubusercontent.com/58807841/222287487-7b6c5a19-310c-457b-8ba5-ce512049608d.png)

Update controlnet.py like this
![image](https://user-images.githubusercontent.com/58807841/222287626-77b9f3d6-1bc9-42ed-b0ef-a28a2009ad1e.png)
+all usages as Script.var instead of self

**Comment by Petas3** [comment]
Can someone please integrate the fix and check for sideeffects? My knownledge of Python is not good enough. Thanks

**Comment by dermesut** [comment]
Has there been progress on this issue? For me it's the same behaviour via API: it's reloading everytime, while it's perfectly re-using the model, if not changed, with thw WebUi.

**Comment by ljleb** [comment]
Ah I think I know why now. The api does not reuse the same controlnet script as the webui, it makes a copy of it to make sure it doesn't break something when changing `args_from` and `args_to`. I'll look into it.

**Comment by dermesut** [comment]
Great! Thank you!

**Comment by dermesut** [comment]
Perfect! Thank you.
