### ISSUE TITLE
XYZ plot unable to compare the weights between two different controlnets.

### ISSUE THREAD

**Issue by BugMonkey42335** [Mikubill/sd-webui-controlnet#433]
Attempting to compare weights between two different controlnets with the new XYZ list notation just results in only the first axis being used.

**Comment by aiton-sd** [comment]
There may be an error in the input values. Please refer to the following and make corrections.

**X Values = 0, [2, 0], [0, 2], 2**
**Y Values = 0, [1, 0], [0, 1], 1**

|           | X: 0                         | X: [2, 0]                    | X: [0, 2]                    | X: 2                         | 
| --------- | ---------------------------- | ---------------------------- | ---------------------------- | ---------------------------- | 
| Y: 0      |CN0: X=0 Y=0<br>CN1: X=0 Y=0 | CN0: X=2 Y=0<br>CN1: X=0 Y=0 | CN0: X=0 Y=0<br>CN1: X=2 Y=0 | CN0: X=2 Y=0<br>CN1: X=2 Y=0 | 
| Y: [1, 0] | CN0: X=0 Y=1<br>CN1: X=0 Y=0 | CN0: X=2 Y=1<br>CN1: X=0 Y=0 | CN0: X=0 Y=1<br>CN1: X=2 Y=0 | CN0: X=2 Y=1<br>CN1: X=2 Y=0 | 
| Y: [0, 1] | CN0: X=0 Y=0<br>CN1: X=0 Y=1 | CN0: X=2 Y=0<br>CN1: X=0 Y=1 | CN0: X=0 Y=0<br>CN1: X=2 Y=1 | CN0: X=2 Y=0<br>CN1: X=2 Y=1 | 
| Y: 1      | CN0: X=0 Y=1<br>CN1: X=0 Y=1 | CN0: X=2 Y=1<br>CN1: X=0 Y=1 | CN0: X=0 Y=1<br>CN1: X=2 Y=1 | CN0: X=2 Y=1<br>CN1: X=2 Y=1 |

**Comment by BugMonkey42335** [comment]
Can you give an example where your comparing the weights of two different controlnets?

**Comment by vrai17** [comment]
How to target specific controlnet?
