### ISSUE TITLE
Any way to control SD generate variant images like Dall-E 2

### ISSUE THREAD

**Issue by wodsoe** [Mikubill/sd-webui-controlnet#435]
Is there any way to control SD generate variant images like Dall-E 2 ?

**Comment by AbyszOne** [comment]
As a control method, the variations will tend to be structurally similar. If you want something more flexible, it's much simpler to use the same image at low denoising or just seed variation (extra option in automatic gui).

**Comment by ljleb** [comment]
companion post in webui:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/5505

**Comment by ljleb** [comment]
Alternatively, you could use one of the models shared in the webui issue above to generate image variations, and train a controlnet to behave the same maybe?

To train a controlnet you can use this: https://github.com/rubbrband/rubbrband

**Comment by wodsoe** [comment]
Thank you! @AbyszOne @ljleb
