### ISSUE TITLE
[Feature Request] Upload our own DepthMap/NormalMap/Pose/etc...

### ISSUE THREAD

**Issue by ilcane87** [Mikubill/sd-webui-controlnet#44]
This would be a useful feature for example when starting from a 3D Model you rendered, which means you can also render better maps than the auto-generated ones, and they could be fed to the process for more accurate results.
Pretty sure there is an extension for the 2.0 depth model exactly for this purpose.

Thanks for listening.

**Comment by cstone1991** [comment]
You can do this already. Just select "none" for preprocessor, and use the depth map as the init image. I've also manually drawn my own skeletons for openpose.

**Comment by ilcane87** [comment]
Oh I wasn't aware, thanks a lot, I'm closing the issue then.
