### ISSUE TITLE
[Feature Request] move models and midas to stable-diffusion-webui\models\

### ISSUE THREAD

**Issue by brunogcar** [Mikubill/sd-webui-controlnet#45]
Examples:
https://github.com/thygate/stable-diffusion-webui-depthmap-script  - uses MiDaS and LeReS directly from webui\models\ so  its not needed to download it again, can be shared by multiple extensions
https://github.com/Extraltodeus/depthmap2mask - for midas as well

https://github.com/arenatemp/stable-diffusion-webui-model-toolkit  - dont remember if it downloads something to models, but it extracts components from checkpoints to a folder there
https://github.com/Klace/stable-diffusion-webui-instruct-pix2pix - was already doing that before being integrated into main 

there are some other extensions that either share or create their own folders in models

also ControlNet folder in default path IMO would be better suited

anyway, outstanding job, really well done, thanks

EDIT:
dpt_hybrid-midas-501f0c75 - specificly i have it already in stable-diffusion-webui\models\midas, for depth extensions, aslo:
dpt_beit_large_384.pt
dpt_beit_large_512.pt
dpt_large-midas-2f21e586.pt
midas_v21_small-70d6b9c8.pt
midas_v21-f6b98070.pt

**Comment by 2blackbar** [comment]
yeah  weights are now buried in extensions folder when theres a specific models folder for just that so other extensions can use the same weights if needed

**Comment by abi** [comment]
Yeah this would be much better!

**Comment by ljleb** [comment]
Note that there is a webui flag for this at the moment `--controlnet-dir <path-to-pth-dir>`. see #60 (PR also adds a text field in the settings for additional control models directory).

**Comment by brunogcar** [comment]
this extension is probably gonna be the most popular if not already, so the longer it takes, more ppl will have issues when its done and it actually needs to be done.

not just the models in controlsnet, but the ones in anotator subfolders as well, should be in default path models folder,  so other extensions can also use it, some already do it, so waste of space, bandwidth having to download things more than once

actual file structure made logic when it was a standalone project, but now it is in a framework where extensions share common resources , and it actually opened the doors for some other projects, i can see for example eventually someone creating draw by color and using the same model,  etc 

eventually might be integrated to webui, but would be in best practice to use default path and as it is already popular and frankly game changer, set example for future extensions and even inspire future devlopment
