### ISSUE TITLE
SDv2 and (V-Parameterization) support

### ISSUE THREAD

**Issue by SirTrippsalot** [Mikubill/sd-webui-controlnet#47]
Currently when using an SD2 model an error is received. An error is received on a normal working SD V2 model, and a V-Parameterization model (SD v2.1 768)

> RuntimeError: mat1 and mat2 shapes cannot be multiplied (154x1024 and 768x320)

Full error log attached.
[error.log](https://github.com/Mikubill/sd-webui-controlnet/files/10737451/error.log)

**Comment by brunogcar** [comment]
https://huggingface.co/lllyasviel/ControlNet/tree/main/models all the models there are for SD v1.5, so not compatible with SD v2.1

**Comment by SirTrippsalot** [comment]
Ah, so if I'm following, the issue isn't the extension itself, but rather the models. So for 2.x there would need to be 2.x based controlnet models?

**Comment by brunogcar** [comment]
if and when SD 2.x models are released, code will need to be adapted as well, but , there are different instructions and as far as I can tell, those are not compatible, same way as for embeddings, hypernetworks and loras, 1x and 2x are not interchangeable

**Comment by SirTrippsalot** [comment]
That certainly makes sense. It's a shame as my 2.x model runs circles around my 1.x model (in many but not all ways), but as most people are kind of stuck in 1.x I get that would be the focus.

**Comment by Echolink50** [comment]
> That certainly makes sense. It's a shame as my 2.x model runs circles around my 1.x model (in many but not all ways), but as most people are kind of stuck in 1.x I get that would be the focus.

I like SD V2 based models as well because they give me better results and run faster, but they can't make tits so nobody bothers to make any cool stuff for them lol.

**Comment by SirTrippsalot** [comment]
I won't go into detail, but check out SlateModel
