### ISSUE TITLE
Feature request: support for new T2i Canny Adapter 

### ISSUE THREAD

**Issue by AugmentedRealityCat** [Mikubill/sd-webui-controlnet#477]
New T2i models have been released, and one of them is the T2i Canny Edge Adapter. This seems to be based on the same principles as the Canny Edge adapter for ControlNet. 

I've downloaded the model over here:
https://huggingface.co/TencentARC/T2I-Adapter/tree/main/models

I've installed it with the other T2i and ControlNet models in `stable-diffusion-webui-master\extensions\sd-webui-controlnet\models`

But it doesn't seem to work. I tried both with and without the Canny Edge pre-processor, with and without the `Invert Input Color` checkbox, even tried `low vram`, but it just doesn't have any effect besides giving me the following error message on the console:
```

Loading model: t2iadapter_canny_sd14v1 [80bfd79b]
Loaded state_dict from [C:\stable-diffusion-webui-master\extensions\sd-webui-controlnet\models\t2iadapter_canny_sd14v1.pth]
Error running process: C:\stable-diffusion-webui-master\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui-master\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "C:\stable-diffusion-webui-master\extensions\sd-webui-controlnet\scripts\controlnet.py", line 608, in process
    else self.build_control_model(p, unet, model, lowvram)
  File "C:\stable-diffusion-webui-master\extensions\sd-webui-controlnet\scripts\controlnet.py", line 467, in build_control_model
    network = network_module(
  File "C:\stable-diffusion-webui-master\extensions\sd-webui-controlnet\scripts\adapter.py", line 65, in __init__
    self.control_model.load_state_dict(state_dict)
  File "C:\stable-diffusion-webui-master\venv\lib\site-packages\torch\nn\modules\module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Adapter:
        size mismatch for conv_in.weight: copying a param with shape torch.Size([320, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 192, 3, 3]).

100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  8.49it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  8.04it/s]
```

**Comment by ClashSAN** [comment]
@AugmentedRealityCat this one seems to be working, make a file with the same name for the model so you don't need to switch between configs.
Use the sketch config.
![image](https://user-images.githubusercontent.com/98228077/222854376-e99232f1-1b5c-49d2-921e-7eeac6d71616.png)

**Comment by AugmentedRealityCat** [comment]
I completely forgot about the config ! That must be it. Thanks a lot for reminding me.
I'll test it in a few hours when I get back in front of my workstation, and I'll close the issue if all is good (I suppose it will be !).

**Comment by ClashSAN** [comment]
great, thanks.
These should be much speedier and lighter than controlnet, 👍 to Tencent, and [lllyasviel](https://huggingface.co/lllyasviel) for this revolutionary training saga!

**Comment by AugmentedRealityCat** [comment]
It was indeed the config file !
As a reminder if anyone has the same problem, here is the documentation about those configs:
https://github.com/Mikubill/sd-webui-controlnet#t2i-adapter-support-experimental

Thanks for the help @ClashSAN and @catboxanon . I'm closing this Issue as it has been resolved.
