### ISSUE TITLE
[Bug]: when I use controlnet preprocessor, genertate no useful image 

### ISSUE THREAD

**Issue by zhiyuanily** [Mikubill/sd-webui-controlnet#480]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

when I generate image with no controlnet preprocessor model, I can get normal image, But when I choose a controlnet model,  I will get a image than have no useful infomation.

is NVIDIA Graphics card necessary for controlnet ?  I use my macbook(Intel UHD Graphics 630 1536 MB), 

it generate image like this:
![image](https://user-images.githubusercontent.com/1639640/222868436-58cb26a9-7673-4d1a-90d5-b07a7463fa0c.png)

### Steps to reproduce the problem

Just choose a control net model,  when start preview, I can see the hemun pose line, but get error image result 

### What should have happened?

generate normal image with the demo pose

### Commit where the problem happens

no

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
webui console output: 
Loading preprocessor: openpose 100%
Total progress: 100%| 20/20 [01:45<00:00,  5.25s/it]
```

### Additional information

error screenshot 
![image](https://user-images.githubusercontent.com/1639640/222868732-3bd4eb7a-7f1e-41d8-9003-54a3ecf94777.png)

**Comment by Mikubill** [comment]
See https://github.com/Mikubill/sd-webui-controlnet#macos-support. You may need to use `--no-half` or PyTorch 2.0/nightly to make it works on mps' devices

**Comment by zhiyuanily** [comment]
> See https://github.com/Mikubill/sd-webui-controlnet#macos-support. You may need to use `--no-half` or PyTorch 2.0/nightly to make it works on mps' devices

greate, it works!
