### ISSUE TITLE
MPS error on Apple M2Pro?

### ISSUE THREAD

**Issue by atpxu** [Mikubill/sd-webui-controlnet#484]
According to previous issues, I added --use-cpu all and --no-half to webui-user.sh like:

> export COMMANDLINE_ARGS="--skip-torch-cuda-test --upcast-sampling --no-half-vae --use-cpu all --no-half --disable-nan-check"

and add environment to webui-macos-env.sh

> export PYTORCH_ENABLE_MPS_FALLBACK=1

however it report error:

`
RuntimeError: Input type (MPSFloatType) and weight type (torch.FloatTensor) should be the same
`

I traced into the code and found line 663 in controlnet.py:
`
control = torch.from_numpy(detected_map.copy()).float().to(devices.get_device_for("controlnet"))
`
and 
<img width="412" alt="image" src="https://user-images.githubusercontent.com/34542841/222886144-10990164-bf1b-4110-9a17-dce6afc8a5b2.png">

which returns "mps". Does it mean `control` is using MPS although I set use_cpu?

I wonder if I used wrong command_argument or it's a bug? Any solutions?

**Comment by atpxu** [comment]
I removed
`
if has_mps():
    return "mps"
`

and it works.

**Comment by trendland** [comment]
> I removed `if has_mps(): return "mps"`
> 
> and it works.

is it related to just controlnet or also the t2iadapter (style adapter) ?

**Comment by trendland** [comment]
testing to see if it works, but i do not find MPS calls in the controlnet.py

**Comment by tabledevil** [comment]
I have the same issue with the extension when trying to run diff_control_sd15_scribble_fp16 [1f29174d] from https://huggingface.co/webui/ControlNet-modules-safetensors/tree/main
the Controlnets are working just fine.
