### ISSUE TITLE
Feature Request: Directly feed openpose data

### ISSUE THREAD

**Issue by jwvanderbeck** [Mikubill/sd-webui-controlnet#49]
It would be amazing if I could take existing openpose pose data and feed it directly into the txt2img or img2img process rather than it trying to first generate the pose estimation from a given image (which it may or may not get right).

**Comment by toyxyz** [comment]
Set the preprocessor to none and input the openpose image. 
Here is a blender model that looks similar to Openpose. : https://toyxyz.gumroad.com/l/ciojz?layout=profile
![image](https://user-images.githubusercontent.com/8006000/218918623-1dcfa4e8-642d-4ff8-96b0-2c046f665991.png)

**Comment by jwvanderbeck** [comment]
Ahh thank you this is what I was doing wrong.  I had been going off a tutorial and din't quite understand clearly what the preproccesor was but now it makes sense.  Turning that off indeed lets me load in a standard openpose output.  Thank you!
