### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (616x1024 and 768x320)

### ISSUE THREAD

**Issue by Rartist** [Mikubill/sd-webui-controlnet#5]
Thanks for this, I hope I can get it to work soon!

I tried the Scribble Model, but I got this error once I ran it:
`RuntimeError: mat1 and mat2 shapes cannot be multiplied (616x1024 and 768x320)`

I resized the input image to 512 x 704 pixels and set the normal Width & Height accordingly. I tried running it without any Preprocessor or with the Fake_Scribble processor, but got the same error message both times. Weight left at 1, Scribble Mode On & Off tried.

**Comment by Mikubill** [comment]
Could you share the full output when this error occurred, or the input args of process func? Seems like some configure not compatible with controlnet

**Comment by Rartist** [comment]
Might have been because I had a V2-1 Model loaded. With a 1-5 Model I don't get an error anymore, but I don't see the image change (at all), either. It generates 1 normal image and gives me my input image back (unchanged).

**Comment by Xenocyde3000** [comment]
I get a similar RuntimeError: mat1 and mat2 shapes cannot be multiplied (77x1024 and 768x320)

Tried to crop the input image to match the aspect ratio of the rendered image (768 x 512), too. I'm using an SD 2.1 model, though. Could this be the problem? Or maybe I need a 1:1 aspect ratio?

**Comment by YooPita** [comment]
I also ran into an error using 2.1. After switching to 1.5 everything began to work.

**Comment by ll2pakll** [comment]
I have the same problem. But what is interesting, initially, immediately after installing the extension, everything worked on the model 2.1. But after restarting it, I started getting this error. So the problem is not the model, but something else that changes with the model change.

**Comment by jaycecd** [comment]
@Mikubill 
The same error message reporting! 
Please tell me why this issue was turned off? I've pulled the latest code but it still doesn't work with SD2.1(v2-1_512-ema-pruned.ckpt [88ecb78256])

**Comment by deloyed** [comment]
Anyone could fix the problem?

**Comment by ljleb** [comment]
It seems this was caused by the active model and enabled controlnet units not being the same type of model. For example, mixing v2.1 with v1.5 models would result into this error, according to prior discussion IIUC.

**Comment by deloyed** [comment]
how do i know the units for different models

**Comment by ljleb** [comment]
It's in the model name. models for v1.5 have `sd15` in their name.

> I have the same problem. But what is interesting, initially, immediately after installing the extension, everything worked on the model 2.1. But after restarting it, I started getting this error. So the problem is not the model, but something else that changes with the model change.

Maybe this isn't the issue though, according to this ^. It could still be related however.

**Comment by korronald** [comment]
I have a Very similar problem, with all models.

RuntimeError: linear(): input and weight.T shapes cannot be multiplied (77x1024 and 768x320)

Mac M1, Stable Diffusion 2.1, Automatic 1111, 
When changing webui-user.sh acording to others suggestion (adding --no-half etc.) I'm ending up with problem:

RuntimeError: Placeholder storage has not been allocated on MPS device!

**Comment by korronald** [comment]
> 

looks like it works after changing models to 21 models. Thanmks!
