### ISSUE TITLE
[Bug]: StyleAdapter incompatible with --medvram and --lowvram arguments

### ISSUE THREAD

**Issue by Danamir** [Mikubill/sd-webui-controlnet#502]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

The `clip_vision` and/or `t2iadapter_style` seems to be incompatible with `--medvram` and `--lowvram` command line arguments.

### Steps to reproduce the problem

1. Launch Automatic1111 webui with `--medvram` or `--lowvram` in `COMMANDLINE_ARGS`
2. Enable ControlNet with `clip_vision` preprocessor and `t2iadapter_style` model, add an input style image
2. Generate an image
3. The image generated is the same as one without ControlNet enabled
4. Relaunch the webui without the med/lowvram arguments
5. Generate an image with ControlNet StyleAdapter
6. The image is now generated with the correct style

### What should have happened?

The style of the input image should have been applied.

### Commit where the problem happens

webui: a5a4fb70
controlnet: 84a2b22d 

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
--medvram --xformers --no-half-vae
```

### Console logs

```Shell
Launching Web UI with arguments: --xformers --no-half-vae
Loading model: t2iadapter_style [202e85cc]
Loaded state_dict from [E:\Program Files\stable-diffusion-webui\extensions\sd-webui-controlnet\models\t2iadapter_style.pth]
ControlNet model t2iadapter_style [202e85cc] loaded
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:01<00:00, 11.60it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 16/16 [00:02<00:00,  7.33it/s]
```

**Comment by Danamir** [comment]
It seems that having more than 75 tokens also breaks the StyleAdapter model.

**Comment by specblades** [comment]
> It seems that having more than 75 tokens also breaks the StyleAdapter model.

Acknowledged. Correspondingly ceases to have an effect when using BREAK as well

**Comment by Kanareika** [comment]
> It seems that having more than 75 tokens also breaks the StyleAdapter model.
Including negative as well.

**Comment by SeBL4RD** [comment]
Can confirm the bug wih --medvram....
Can't use clip_vision without a restart of SD without --medvram, and so, can't do better than 768x768, instead of 1400x1400 with medvram
