### ISSUE TITLE
the control models are loaded every time I press generate

### ISSUE THREAD

**Issue by loboere** [Mikubill/sd-webui-controlnet#505]
I'm using TheLastBen's colab notebook. Every time I press generate the models are loaded and this is very time consuming. Is there a way to not load them every time an image is generated?

![image](https://user-images.githubusercontent.com/15265895/222995494-8bedd3dd-faf7-4a49-b81e-7859af37b17c.png)

**Comment by Mikubill** [comment]
Change the value of model cache size (in settings) to cache more models.

**Comment by ljleb** [comment]
Closing as the cache logic was updated recently. Feel free to open a new issue if the bug persists.
