### ISSUE TITLE
[Bug]: MLSD delivers blank map

### ISSUE THREAD

**Issue by corebro** [Mikubill/sd-webui-controlnet#509]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

https://www.reddit.com/r/StableDiffusion/comments/11ju936/why_mlsd_doesnt_work/

Some people have problems using MLSD including me. When I try to use it (as preproc and model) it always delivers a blank or sometimes black map with some lines, but most of the time it is empty,

### Steps to reproduce the problem

Its in the description

### What should have happened?

MLSD map properly generated

### Commit where the problem happens

webui: newest
controlnet: newest

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--xformers --api
```

### Console logs

```Shell
No errors displayed during generation
```

**Comment by Mikubill** [comment]
tested with the image in that thread, everything seems working fine..

![Screenshot](https://user-images.githubusercontent.com/31246794/223082905-9c6e5f8a-c78a-45a1-8a21-7029b2d19d67.png)
