### ISSUE TITLE
Cant replicate style transfer

### ISSUE THREAD

**Issue by FurkanGozukara** [Mikubill/sd-webui-controlnet#512]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I have installed the extension from zero

Everything looks like working

![image](https://user-images.githubusercontent.com/19240467/223155447-829e5d38-d2c5-4fb0-8e66-ecff08740b23.png)

I am trying to apply this style image

![image](https://user-images.githubusercontent.com/19240467/223154506-b980b80e-d9dd-4733-a7a0-aba8a76d6c52.png)

into this image

![image](https://user-images.githubusercontent.com/19240467/223154561-93c394c5-d457-4cab-b0e2-1a94c3656e4e.png)

but the results are totally unrelated

here my setup

![image](https://user-images.githubusercontent.com/19240467/223154714-1804b337-5251-4ecd-a95f-cdda466a1d2c.png)

![image](https://user-images.githubusercontent.com/19240467/223154788-1ce1efda-0c87-4327-903f-0198efc9ee4b.png)

![image](https://user-images.githubusercontent.com/19240467/223154890-e2e5beda-ae93-4af7-8525-2e475855d9ff.png)

![image](https://user-images.githubusercontent.com/19240467/223155034-c132d553-8330-4c7a-a5e0-d28ae9d6d923.png)

![image](https://user-images.githubusercontent.com/19240467/223155084-f9f94b97-7364-4d9a-922e-6ea82eafc616.png)

![image](https://user-images.githubusercontent.com/19240467/223155122-55bd65ec-87c7-4102-b6f6-d46c1be64bf1.png)

I want to replicate like here nothing like that i am getting

![image](https://user-images.githubusercontent.com/19240467/223155198-6fc7d30a-defe-48d1-a981-9fe15dfdab17.png)

### Steps to reproduce the problem

explained

### What should have happened?

explained

### Commit where the problem happens

explained

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
explained
```

### Console logs

```Shell
explained
```

### Additional information

explained

**Comment by Mikubill** [comment]
T2I-Adapter just made a large modify on their codebase 6 hours ago (https://huggingface.co/spaces/Adapter/T2I-Adapter/commit/b3478e431020e7a6611ecb2e4daa251a960b7f5f.diff), no idea why they could even do this after their paper published. I will try my best to follow their changes.

**Comment by FurkanGozukara** [comment]
> T2I-Adapter just made a large modify on their codebase 6 hours ago (https://huggingface.co/spaces/Adapter/T2I-Adapter/commit/b3478e431020e7a6611ecb2e4daa251a960b7f5f.diff), no idea why they could even do this after their paper published. I will try my best to follow their changes.

That is why. I recorded a tutorial video and now I am stuck since not working :/

**Comment by Mikubill** [comment]
ok now it should works. quick test:

![00024-2858487664-2-2](https://user-images.githubusercontent.com/31246794/223180979-0238478a-177a-4144-b47d-faba7f438aae.png)

**Comment by demirklvc** [comment]
wait so you're telling me it didint work 100& before? i havent updated yet  because i like how it functions. is it an big change?

**Comment by demirklvc** [comment]
> wait so you're telling me it didint work 100& before? i havent updated yet because i like how my current style adapter tool functions. is it an big change?

**Comment by FurkanGozukara** [comment]
> ok now it should works. quick test:
> 
> ![00024-2858487664-2-2](https://user-images.githubusercontent.com/31246794/223180979-0238478a-177a-4144-b47d-faba7f438aae.png)

Awesome waiting

**Comment by FurkanGozukara** [comment]
> > wait so you're telling me it didint work 100& before? i havent updated yet because i like how my current style adapter tool functions. is it an big change?

I didn't see previous

**Comment by Mikubill** [comment]
> wait so you're telling me it didint work 100& before? i havent updated yet because i like how it functions. is it an big change?

No it only affects when you're using multi-controlnet with canny, depth and style-adapters. Single controlnet/adapter's result remains unchanged and reproducible

**Comment by demirklvc** [comment]
good to know. thanks for clarification/your work :)

**Comment by FurkanGozukara** [comment]
completed the tutorial

ty @Mikubill 

21.) Automatic1111 Web UI - PC - Free
[New Style Transfer Extension, ControlNet of Automatic1111 Stable Diffusion T2I-Adapter Color Control](https://youtu.be/tXaQAkOgezQ)
[![image](https://user-images.githubusercontent.com/19240467/223283277-eaaf6e53-df43-40ac-8096-c08f9a14cc8d.png)
](https://youtu.be/tXaQAkOgezQ)
