### ISSUE TITLE
[Bug]: TypeError: Adapter.__init__() got an unexpected keyword argument 'linear_start'

### ISSUE THREAD

**Issue by ProGamerGov** [Mikubill/sd-webui-controlnet#513]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When attempting to use the adapter for txt2img, I get an error message and then it continues rendering without using controlnet.

### Steps to reproduce the problem

1. Use txt2img with any of the controlnet models.

### What should have happened?

It should work without error

### Commit where the problem happens

webui: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8
controlnet: 6dd043aad3211cc9f25c711bb1f49387ee9e4260

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
Loading model: t2iadapter_sketch-fp16 [75b15924]
Loaded state_dict from [C:\Users\user\Desktop\sd.webui\webui\extensions\sd-webui-controlnet\models\t2iadapter_sketch-fp16.safetensors]
Error running process: C:\Users\user\Desktop\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "C:\Users\user\Desktop\sd.webui\webui\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "C:\Users\user\Desktop\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 735, in process
    model_net = self.load_control_model(p, unet, model, lowvram)
  File "C:\Users\user\Desktop\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 534, in load_control_model
    model_net = self.build_control_model(p, unet, model, lowvram)
  File "C:\Users\user\Desktop\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 572, in build_control_model
    network = network_module(
  File "C:\Users\user\Desktop\sd.webui\webui\extensions\sd-webui-controlnet\scripts\adapter.py", line 80, in __init__
    self.control_model = model(**config.model.params)
TypeError: Adapter.__init__() got an unexpected keyword argument 'linear_start'
```
```


### Additional information

_No response_

**Comment by Mikubill** [comment]
Try with the latest commit

**Comment by Mikubill** [comment]
t2iadapter_seg-fp16 requires `image_adapter_v14.yaml` (default is `sketch_adapter_v14.yaml`). You need to 

1. change `Config file for Adapter models` in settings
2. or copy `image_adapter_v14.yaml` and rename it to `t2iadapter_seg-fp16.yaml`

to make seg works.

**Comment by SlimeVRX** [comment]
I will try it. Thanks for the quick response!

**Comment by camenduru** [comment]
thanks @Mikubill ❤
