### ISSUE TITLE
[Bug]: t2iadapter_style works only on first half of a batch

### ISSUE THREAD

**Issue by Kanareika** [Mikubill/sd-webui-controlnet#518]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When using a t2iadapter_style, a style part applied only on a first half of a batch, i.e. only first image, if batch of two, only 1 and 2, if batch of 4. Example grids (same seed, different images for style adapter, downsized after generation):

batch of 2:
![tmpui_fk2an](https://user-images.githubusercontent.com/10144329/223357567-80cc95b8-0a8a-4c2e-bd85-848b0f2fc5b4.png)
![tmpflrs1euw](https://user-images.githubusercontent.com/10144329/223357610-fe0219b6-3644-4959-b49c-9871a4941d74.png)

batch of 4:
![tmpp78mi3iw](https://user-images.githubusercontent.com/10144329/223357655-e5bf8ced-4f2e-49f3-b326-dcaaaeab8f83.png)
![tmpsobwwx_5](https://user-images.githubusercontent.com/10144329/223357702-d57b8571-52d7-4bd3-aac2-d4bdee030fc8.png)

### Steps to reproduce the problem

1. Usual steps to use style adapter (sketch or canny adapters in first MultiControlNet tab, style in second)
2. Use batch size of 2 or 4 images (set batch count to see it, using same image for style)
3. Result

### What should have happened?

Every single image from batch should have style adapter applied, not only first half.

### Commit where the problem happens

webui: 0cc0ee1b
controlnet: 457f01bc

### Command Line Arguments

```Shell
--no-half-vae --xformers
```

### Console logs

```Shell
Usual log, no errors present:
Loading model from cache: t2iadapter_canny_sd14v1 [80bfd79b]
Loading preprocessor: canny
Loading model from cache: t2iadapter_style_sd14v1 [202e85cc]
Loading preprocessor: clip_vision
100%|██████████████████████████████████████████████████████████████████████████████████| 32/32 [00:24<00:00,  1.28it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 32/32 [00:27<00:00,  1.16it/s]
```

**Comment by ZGCTroy** [comment]
Same for OpenPose. 
<img width="400" alt="image" src="https://user-images.githubusercontent.com/28867789/223410455-8c4d6235-2a25-482d-af26-52d7e0863483.png">

After i close "enable CFG-based Guidance" in Setting/ControlNet, it works correctly. 

<img width="400" alt="image" src="https://user-images.githubusercontent.com/28867789/223410865-53776135-489e-4b14-a73e-d0c9e9026bf4.png">

**Comment by Kanareika** [comment]
> "enable CFG-based Guidance"


Turned on: second image nowhere near a style, and follow original image in sketch adapter very loosely:
![tmpxoec3ick](https://user-images.githubusercontent.com/10144329/223427901-ceeb3f38-5caa-4fb3-94aa-aca367067b0d.png)

Turned off: now second image follows sketch, but style still did not applied:
![tmpuz9gvfiz](https://user-images.githubusercontent.com/10144329/223427971-5e0f3450-f436-4c8a-b1ae-9105672ca68f.png)

**Comment by Mikubill** [comment]
Will do some investigate later. Also note that openpose is working as designed.

disabled:
![grid-0012-2](https://user-images.githubusercontent.com/31246794/223439735-8bad9ee1-2898-4bff-a76e-150c69ed3d9a.png)

enabled:
![grid-0011-2](https://user-images.githubusercontent.com/31246794/223439746-7c7c5938-8f7e-4495-bdbd-199d5c07095b.png)

**Comment by Mikubill** [comment]
Maybe related: https://github.com/Mikubill/sd-webui-controlnet/discussions/521

**Comment by Kadah** [comment]
Turning off "Enable CFG-Based guidance" prevents this bug from happening for me. I am not using any low vrams options.
