### ISSUE TITLE
[Bug]: Errors when generating with Style Adapter (and color Adapter)

### ISSUE THREAD

**Issue by trendland** [Mikubill/sd-webui-controlnet#523]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Trying to do a style transfer with Model checkpoint SD 1.5
They are both loading about 50% and then these two errors :/
Any help would be great as I would really like to try these style transfers

ControlNet 0:
Preprocessor: Canny -- Model: control canny
ControlNet 1:
Preprocessor: Clip_vision -- Model: T2iadapter_style_sd14V1

RuntimeError: !(has_different_input_dtypes && !config.promote_inputs_to_common_dtype_ && (has_undefined_outputs || config.enforce_safe_casting_to_output_ || config.cast_common_dtype_to_outputs_)) INTERNAL ASSERT FAILED at "/Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/TensorIterator.cpp":407, please report a bug to PyTorch.

Error with Color Adapter

Controlnet 0:
Preprocessor: Canny -- Model: control canny
ControlNet 1:
Preprocessor: Clip_vision -- Model: T2iadapter_color_sd14V1

RuntimeError: pixel_unshuffle expects height to be divisible by downscale_factor, but input.size(-2)=257 is not divisible by 8

Thank you!

### Steps to reproduce the problem

ControlNet 0:
Preprocessor: Canny -- Model: control canny
ControlNet 1:
Preprocessor: Clip_vision -- Model: T2iadapter_style_sd14V1

Start generating and then Error: 

RuntimeError: !(has_different_input_dtypes && !config.promote_inputs_to_common_dtype_ && (has_undefined_outputs || config.enforce_safe_casting_to_output_ || config.cast_common_dtype_to_outputs_)) INTERNAL ASSERT FAILED at "/Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/TensorIterator.cpp":407, please report a bug to PyTorch.

### What should have happened?

Applied style transfer into Canny Image 

### Commit where the problem happens

webui: commit: [0cc0ee1b]
controlnet: fed7a529

### What browsers do you use to access the UI ?

Brave

### Command Line Arguments

```Shell
COMMANDLINE_ARGS="--skip-torch-cuda-test --upcast-sampling --no-half-vae --use-cpu interrogate --api --disable-safe-unpickle"

(On a Mac)
```

### Console logs

```Shell
RuntimeError: !(has_different_input_dtypes && !config.promote_inputs_to_common_dtype_ && (has_undefined_outputs || config.enforce_safe_casting_to_output_ || config.cast_common_dtype_to_outputs_)) INTERNAL ASSERT FAILED at "/Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/TensorIterator.cpp":407, please report a bug to PyTorch.
```

**Comment by Mikubill** [comment]
Maybe related: https://github.com/Mikubill/sd-webui-controlnet/issues/354

**Comment by trendland** [comment]
unfortuenataly not related - Ive tried with Safari and it gives the same error for both Style Adapters

**Comment by RADesigner** [comment]
I have the exact same error. Also running a Mac.

**Comment by ptppan** [comment]
Same here, also Mac

**Comment by orfeaus** [comment]
Also on Mac getting errors when trying to use the new color and style adapters. I wonder if this is because Apple silicon doesn't support xformers? Or perhaps it's related to pytorch?

**Comment by trendland** [comment]
> Also on Mac getting errors when trying to use the new color and style adapters. I wonder if this is because Apple silicon doesn't support xformers? Or perhaps it's related to pytorch?

I dont know but I would really like to try these new styles - 
Ive tried to update to Pytorch 13 and it's all up to date on my machine but for some reasons SD is still telling me that I have the 12.1 version - Maybe related ? 

let's just hope it gets fixed and we can use it soon

**Comment by edgardmello** [comment]
An error here too. Macbook Pro M1 14"

**Comment by RADesigner** [comment]
> > Also on Mac getting errors when trying to use the new color and style adapters. I wonder if this is because Apple silicon doesn't support xformers? Or perhaps it's related to pytorch?
> 
> I dont know but I would really like to try these new styles - Ive tried to update to Pytorch 13 and it's all up to date on my machine but for some reasons SD is still telling me that I have the 12.1 version - Maybe related ?
> 
> let's just hope it gets fixed and we can use it soon

I also cannot get SD to show 13, it always says I have 12.1

**Comment by ClashSAN** [comment]
macos support is limited to controlnet.
cc: @brkirch (but he may be inactive)
you could make a feature request for cpu only option for `clip_vision` preprocessor

**Comment by gcohen-dev** [comment]
Is there any way around this? I'm getting the same error with M1 max.

**Comment by ingling** [comment]
Same error here. Seems like this is quite common, possibly all M-series processors.

**Comment by trendland** [comment]
> Same error here. Seems like this is quite common, possibly all M-series processors.

Not only M-series, I think here it is related to all Mac - Still having issues with Style & color adapters, it is just not working. And ive tried on multiple browsers, with multiple python versions and arguments... 

I guess they will work on it, but it seems they don't have Mac available for testing... Hopefully it will be fixed soon as I would really like to use these with my controlnet settings.

**Comment by gcohen-dev** [comment]
Has anyone tried to use CPU instead of GPU as a param and see if it's working?

**Comment by WhoIsFishie** [comment]
getting same error on windows. nvidia card

**Comment by jackhagley** [comment]
still get this error.
Chrome on M1 Studio
