### ISSUE TITLE
[feature request]: api endpoint to change 1.4/2.1 configs 

### ISSUE THREAD

**Issue by devilismyfriend** [Mikubill/sd-webui-controlnet#526]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Right now it can only be changed by going to the settings menu, would be great to have it exposed on the API so we can change it as needed, or better yet, detect if the model is 2.1 or 1.4 and set it internally to save the hassle.

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

auto change or api change

### Commit where the problem happens

webui: nan
controlnet: nan 

### Command Line Arguments

```Shell
nan
```

### Console logs

```Shell
nan
```

**Comment by ljleb** [comment]
The webui contains code to automatically detects whether a 1.x or 2.x checkpoint is in use. I don't know if it's possible to do the same with controlnet, maybe it is possible to reuse bits of code here and there from the webui if the architecture is similar and the checkpoints contain enough metadata.

**Comment by Mikubill** [comment]
you can name the configuration the same as the model filename to override default settings, just like the WebUI's model/yaml does.
