### ISSUE TITLE
[Bug]: Gradio error on launch - "UserWarning: You have unused kwarg parameters in tab, please remove them: {'open' : false}

### ISSUE THREAD

**Issue by CCpt5** [Mikubill/sd-webui-controlnet#531]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

On A1111 launch I'm getting the following error. I went one by one moving out extensions from my extension folder and I had 3 different extensions that cause this, but Control net is one (pops up when it's the only extension in the extension folder / doesn't when i remove it). I have had some issues w/ SD failing to get to running on local URL (aka start) before crashing the past week. I think this error could be related. Please review if possible.

And thanks so much for all of your work - excellent extension - really appreciate it!

Here's what happens when I launch A1111 when the only extension I have in the folder is control net (sometimes it doesn't get to the running part and I have to reopen it and try again - eventually it goes):

----
venv "C:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8
Installing requirements for Web UI

Launching Web UI with arguments: --xformers --api --ckpt-dir e:\Stable Diffusion Checkpoints
Loading weights [396c3fd2fa] from e:\Stable Diffusion Checkpoints\2022-12-29 - Topnotch 8 - (Topnotch Artstyle) - 36img contd of 7 - 7000 steps - (50img to 4000steps + 36img to 3000).ckpt
Creating model from config: C:\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: C:\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0):
Model loaded in 2.3s (load weights from disk: 0.4s, create model: 0.2s, apply weights to model: 0.2s, apply half(): 0.3s, load VAE: 0.1s, move model to device: 0.4s, load textual inversion embeddings: 0.6s).
C:\stable-diffusion-webui\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Tab, please remove them: {'open': False}
  warnings.warn(
Running on local URL:  http://127.0.0.1:7860

### Steps to reproduce the problem

1. Make sure "Show warnings in console." is toggled in the A1111 settings (System tab)
2.  Launch webui-user.bat
2. Look for "you have unused kwarg parameters in tab" etc

### What should have happened?

No error / launch. 

### Commit where the problem happens

webui: python: 3.10.6  •  torch: 1.13.1+cu117  •  xformers: 0.0.16rc425  •  gradio: 3.16.2  •  commit: [0cc0ee1b](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8)  •  checkpoint: [396c3fd2fa](https://google.com/search?q=396c3fd2faa17b989bd28d73ecb461826199684383c922b38b867d4ab12d92e9)

controlnet: Current

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
set COMMANDLINE_ARGS=--xformers --api --skip-torch-cuda-test --ckpt-dir "e:\Stable Diffusion Checkpoints"
```

### Console logs

```Shell
venv "C:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8
Installing requirements for Web UI

Launching Web UI with arguments: --xformers --api --ckpt-dir e:\Stable Diffusion Checkpoints
Loading weights [396c3fd2fa] from e:\Stable Diffusion Checkpoints\2022-12-29 - Topnotch 8 - (Topnotch Artstyle) - 36img contd of 7 - 7000 steps - (50img to 4000steps + 36img to 3000).ckpt
Creating model from config: C:\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: C:\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0):
Model loaded in 2.3s (load weights from disk: 0.4s, create model: 0.2s, apply weights to model: 0.2s, apply half(): 0.3s, load VAE: 0.1s, move model to device: 0.4s, load textual inversion embeddings: 0.6s).
C:\stable-diffusion-webui\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Tab, please remove them: {'open': False}
  warnings.warn(
Running on local URL:  http://127.0.0.1:7860
```

**Comment by justsonghua** [comment]
I reinstall, but this warning is still there. And also I found if I disable Control Net and no warning will be reported. But sadly Control Net is useful for me, I can't disable it.
