### ISSUE TITLE
[Bug]: models don't show in checkpoints dropdown

### ISSUE THREAD

**Issue by theoden8** [Mikubill/sd-webui-controlnet#548]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I install sd-webui-controlnet as instructed, but checkpoints don't appear in the dropdown

### Steps to reproduce the problem

1. Set up environment for stable-diffusion-webui
2. Clone all the repositories as in https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Install-and-Run-on-NVidia-GPUs
3. `pip install -r` for these repositories' requirements.txt
4. Downloaded a bunch stable-diffusion checkpoints as described [here](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Dependencies) and [here](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Features#stable-diffusion-20) into `models/Stable-Diffusion`
5. Launch webui with --xformers --medvram
6. Install ControlNet extension as explained in the readme (extension tab, paste link, click install, reload UI)
7. Download a bunch of ControlNet checkpoints from https://huggingface.co/webui/ControlNet-modules-safetensors/tree/main into `models/ControlNet` of the stable-diffusion-webui repo
8. Reload available models
9. (After nothing happens) try restarting the UI.

### What should have happened?

ControlNet checkpoints should appear in the top-left dropdown. Instead, I only see the stable-diffusion ones.

### Commit where the problem happens

webui: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8
controlnet: e5ed9fccdc4fbbe5ec4aae134371683528f7bd60

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
--xformers --medvram
```

### Console logs

```Shell
################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on ***** user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Launching launch.py...
################################################################
Python 3.9.16 (main, Jan 11 2023, 16:05:54)
[GCC 11.2.0]
Commit hash: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8
Installing requirements for Web UI

Launching Web UI with arguments: --medvram --xformers
Loading weights [ab800444cd] from ./stable-diffusion-webui/models/Stable-diffusion/512-base-ema.safetensors
Creating model from config: ./stable-diffusion-webui/models/Stable-diffusion/512-base-ema.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 865.91 M params.
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0):
Model loaded in 3.0s (create model: 0.3s, apply weights to model: 0.8s, apply half(): 1.5s, move model to device: 0.2s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
```

### Additional information

* I have tried using the `.pth` files instead of the `safetensor` ones, not successful.
* I have tried copying all possible checkpoints into the old search directory (extensions/sd-webui-controlnet/models) or explicitly specifying a search directory in the settings.
* Print-tracing shows that `get_all_models` and `update_cn_models` find all the checkpoints as expected. However, it doesn't make it to the dropdown (`checkpoints_list` in the `stable-diffusion-webui/modules/sd_modules.py`) .
* I have tried re-cloning the stable-diffusion-webui and re-installing everything.

**Comment by brunogcar** [comment]
everything seems fine, but  controlnet models are not supposed to show on top left models dropdown anyway, those are SD models (checkpoints)

try to scroll down a bit, 
search for a module ControlNet, 
should be below Restore faces - Tiling - Hires. fix and 
above Scripts

click on that module and you will see all the controlnet options, including 
Preprocessor - Model


to prevent future bug report
actual loaded model 512-base-ema, dont use 2.X models, with controlnet, 
currently all controlnet models are for 1.X, AFAIK

**Comment by theoden8** [comment]
Right. I can see it all. I think I was confused by

> Press "Refresh models" and select the model you want to use. (If nothing appears, try reload/restart the webui)

The cldm21.yaml should work for SB2.1 models, right?

**Comment by brunogcar** [comment]
> The cldm21.yaml should work for SB2.1 models, right?

yeap, but when 2.x controlnet models are avaiable, i think
never tested, but i dont think you can mix them, same goes for lora, hypernetwork and embeddings

**Comment by theoden8** [comment]
Understood. Thanks for explaining.
I'd be happy to call this issue solved :)

**Comment by Tedrer** [comment]
Same problem with mine
<img width="463" alt="image" src="https://github.com/Mikubill/sd-webui-controlnet/assets/132005432/b0ca3c55-e9c9-40e0-bdfd-f73d16ae62a3">

**Comment by roseyyy2022ai** [comment]
> Same problem with mine <img alt="image" width="463" src="https://user-images.githubusercontent.com/132005432/238422086-b0ca3c55-e9c9-40e0-bdfd-f73d16ae62a3.png">

Having the same issue right now, just randomly happenned...
