### ISSUE TITLE
Error when running in google colab

### ISSUE THREAD

**Issue by yesyeahvh123** [Mikubill/sd-webui-controlnet#55]
i got this error, how to fix?
`Loading preprocessor: canny, model: body_pose_model(f14788ab)
Loaded state_dict from [/content/stable-diffusion-webui/extensions/sd-webui-controlnet/models/body_pose_model.pth]
Error running process: /content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 386, in process
    script.process(p, *script_args)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 252, in process
    network = PlugableControlModel(model_path, os.path.join(cn_models_dir, "cldm_v15.yaml"), weight, lowvram=lowvram)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/cldm.py", line 57, in __init__
    self.control_model.load_state_dict(state_dict)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ControlNet:
	Missing key(s) in state_dict: "time_embed.0.weight", "time_embed.0.bias", "time_embed.2.weight", "time_embed.2.bias", "input_blocks.0.0.weight", "input_blocks.0.0.bias", "input_blocks.1.0.in_layers.0.weight", "input_blocks.1.0.in_layers.0.bias", "input_blocks.1.0.in_layers.2.weight", "input_blocks.1.0.in_layers.2.bias", "input_blocks.1.0.emb_layers.1.weight", "input_blocks.1.0.emb_layers.1.bias", "input_blocks.1.0.out_layers.0.weight", "input_blocks.1.0.out_layers.0.bias", "input_blocks.1.0.out_layers.3.weight", "input_blocks.1.0.out_layers.3.bias", "input_blocks.1.1.norm.weight", "input_blocks.1.1.norm.bias", "input_blocks.1.1.proj_in.weight", "input_blocks.1.1.proj_in.bias", "input_blocks.1.1.transformer_blocks.0.attn1.to_q.weight", "input_blocks.1.1.transformer_blocks.0.attn1.to_k.weight", "input_blocks.1.1.transformer_blocks.0.attn1.to_v.weight", "input_blocks.1.1.transformer_blocks.0.attn1.to_out.0.weight", "input_blocks.1.1.transformer_blocks.0.attn1.to_out.0.bias", "input_blocks.1.1.transformer_blocks.0.ff.net.0.proj.weight", "input_blocks.1.1.transformer_blocks.0.ff.net.0.proj.bias", "input_blocks.1.1.transformer_blocks.0.ff.net.2.weight", "input_blocks.1.1.transformer_blocks.0.ff.net.2.bias", "input_blocks.1.1.transformer_blocks.0.attn2.to_q.weight", "input_blocks.1.1.transformer_blocks.0.attn2.to_k.weight", "input_blocks.1.1.transformer_blocks.0.attn2.to_v.weight", "input_blocks.1.1.transformer_blocks.0.attn2.to_out.0.weight", "input_blocks.1.1.transformer_blocks.0.attn2.to_out.0.bias", "input_blocks.1.1.transformer_blocks.0.norm1.weight", "input_blocks.1.1.transformer_blocks.0.norm1.bias", "input_blocks.1.1.transformer_blocks.0.norm2.weight", "input_blocks.1.1.transformer_blocks.0.norm2.bias", "input_blocks.1.1.transformer_blocks.0.norm3.weight", "input_blocks.1.1.transformer_blocks.0.norm3.bias", "input_blocks.1.1.proj_out.weight", "input_blocks.1.1.proj_out.bias", "input_blocks.2.0.in_layers.0.weight", "input_blocks.2.0.in_layers.0.bias", "input_blocks.2.0.in_layers.2.weight", "input_blocks.2.0.in_layers.2.bias", "input_blocks.2.0.emb_layers.1.weight", "input_blocks.2.0.emb_layers.1.bias", "input_blocks.2.0.out_layers.0.weight", "input_blocks.2.0.out_layers.0.bias", "input_blocks.2.0.out_layers.3.weight", "input_blocks.2.0.out_layers.3.bias", "input_blocks.2.1.norm.weight", "input_blocks.2.1.norm.bias", "input_blocks.2.1.proj_in.weight", "input_blocks.2.1.proj_in.bias", "input_blocks.2.1.transformer_blocks.0.attn1.to_q.weight", "input_blocks.2.1.transformer_blocks.0.attn1.to_k.weight", "input_blocks.2.1.transformer_blocks.0.attn1.to_v.weight", "input_blocks.2.1.transformer_blocks.0.attn1.to_out.0.weight", "input_blocks.2.1.transformer_blocks.0.attn1.to_out.0.bias", "input_blocks.2.1.transformer_blocks.0.ff.net.0.proj.weight", "input_blocks.2.1.transformer_blocks.0.ff.net.0.proj.bias", "input_blocks.2.1.transformer_blocks.0.ff.net.2.weight", "input_blocks.2.1.transformer_blocks.0.ff.net.2.bias", "input_blocks.2.1.transformer_blocks.0.attn2.to_q.weight", "input_blocks.2.1.transformer_blocks.0.attn2.to_k.weight", "input_blocks.2.1.transformer_blocks.0.attn2.to_v.weight", "input_blocks.2.1.transformer_blocks.0.attn2.to_out.0.weight", "input_blocks.2.1.transformer_blocks.0.attn2.to_out.0.bias", "input_blocks.2.1.transformer_blocks.0.norm1.weight", "input_blocks.2.1.transformer_blocks.0.norm1.bias", "input_blocks.2.1.transformer_blocks.0.norm2.weight", "input_blocks.2.1.transformer_blocks.0.norm2.bias", "input_blocks.2.1.transformer_blocks.0.norm3.weight", "input_blocks.2.1.transformer_blocks.0.norm3.bias", "input_blocks.2.1.proj_out.weight", "input_blocks.2.1.proj_out.bias", "input_blocks.3.0.op.weight", "input_blocks.3.0.op.bias", "input_blocks.4.0.in_layers.0.weight", "input_blocks.4.0.in_layers.0.bias", "input_blocks.4.0.in_layers.2.weight", "input_blocks.4.0.in_layers.2.bias", "input_blocks.4.0.emb_layers.1.weight", "input_blocks.4.0.emb_layers.1.bias", "input_blocks.4.0.out_layers.0.weight", "input_blocks.4.0.out_layers.0.bias", "input_blocks.4.0.out_layers.3.weight", "input_blocks.4.0.out_layers.3.bias", "input_blocks.4.0.skip_connection.weight", "input_blocks.4.0.skip_connection.bias", "input_blocks.4.1.norm.weight", "input_blocks.4.1.norm.bias", "input_blocks.4.1.proj_in.weight", "input_blocks.4.1.proj_in.bias", "input_blocks.4.1.transformer_blocks.0.attn1.to_q.weight", "input_blocks.4.1.transformer_blocks.0.attn1.to_k.weight", "input_blocks.4.1.transformer_blocks.0.attn1.to_v.weight", "input_blocks.4.1.transformer_blocks.0.attn1.to_out.0.weight", "input_blocks.4.1.transformer_blocks.0.attn1.to_out.0.bias", "input_blocks.4.1.transformer_blocks.0.ff.net.0.proj.weight", "input_blocks.4.1.transformer_blocks.0.ff.net.0.proj.bias", "input_blocks.4.1.transformer_blocks.0.ff.net.2.weight", "input_blocks.4.1.transformer_blocks.0.ff.net.2.bias", "input_blocks.4.1.transformer_blocks.0.attn2.to_q.weight", "input_blocks.4.1.transformer_blocks.0.attn2.to_k.weight", "input_blocks.4.1.transformer_blocks.0.attn2.to_v.weight", "input_blocks.4.1.transformer_blocks.0.attn2.to_out.0.weight", "input_blocks.4.1.transformer_blocks.0.attn2.to_out.0.bias", "input_blocks.4.1.transformer_blocks.0.norm1.weight", "input_blocks.4.1.transformer_blocks.0.norm1.bias", "input_blocks.4.1.transformer_blocks.0.norm2.weight", "input_blocks.4.1.transformer_blocks.0.norm2.bias", "input_blocks.4.1.transformer_blocks.0.norm3.weight", "input_blocks.4.1.transformer_blocks.0.norm3.bias", "input_blocks.4.1.proj_out.weight", "input_blocks.4.1.proj_out.bias", "input_blocks.5.0.in_layers.0.weight", "input_blocks.5.0.in_layers.0.bias", "input_blocks.5.0.in_layers.2.weight", "input_blocks.5.0.in_layers.2.bias", "input_blocks.5.0.emb_layers.1.weight", "input_blocks.5.0.emb_layers.1.bias", "input_blocks.5.0.out_layers.0.weight", "input_blocks.5.0.out_layers.0.bias", "input_blocks.5.0.out_layers.3.weight", "input_blocks.5.0.out_layers.3.bias", "input_blocks.5.1.norm.weight", "input_blocks.5.1.norm.bias", "input_blocks.5.1.proj_in.weight", "input_blocks.5.1.proj_in.bias", "input_blocks.5.1.transformer_blocks.0.attn1.to_q.weight", "input_blocks.5.1.transformer_blocks.0.attn1.to_k.weight", "input_blocks.5.1.transformer_blocks.0.attn1.to_v.weight", "input_blocks.5.1.transformer_blocks.0.attn1.to_out.0.weight", "input_blocks.5.1.transformer_blocks.0.attn1.to_out.0.bias", "input_blocks.5.1.transformer_blocks.0.ff.net.0.proj.weight", "input_blocks.5.1.transformer_blocks.0.ff.net.0.proj.bias", "input_blocks.5.1.transformer_blocks.0.ff.net.2.weight", "input_blocks.5.1.transformer_blocks.0.ff.net.2.bias", "input_blocks.5.1.transformer_blocks.0.attn2.to_q.weight", "input_blocks.5.1.transformer_blocks.0.attn2.to_k.weight", "input_blocks.5.1.transformer_blocks.0.attn2.to_v.weight", "input_blocks.5.1.transformer_blocks.0.attn2.to_out.0.weight", "input_blocks.5.1.transformer_blocks.0.attn2.to_out.0.bias", "input_blocks.5.1.transformer_blocks.0.norm1.weight", "input_blocks.5.1.transformer_blocks.0.norm1.bias", "input_blocks.5.1.transformer_blocks.0.norm2.weight", "input_blocks.5.1.transformer_blocks.0.norm2.bias", "input_blocks.5.1.transformer_blocks.0.norm3.weight", "input_blocks.5.1.transformer_blocks.0.norm3.bias", "input_blocks.5.1.proj_out.weight", "input_blocks.5.1.proj_out.bias", "input_blocks.6.0.op.weight", "input_blocks.6.0.op.bias", "input_blocks.7.0.in_layers.0.weight", "input_blocks.7.0.in_layers.0.bias", "input_blocks.7.0.in_layers.2.weight", "input_blocks.7.0.in_layers.2.bias", "input_blocks.7.0.emb_layers.1.weight", "input_blocks.7.0.emb_layers.1.bias", "input_blocks.7.0.out_layers.0.weight", "input_blocks.7.0.out_layers.0.bias", "input_blocks.7.0.out_layers.3.weight", "input_blocks.7.0.out_layers.3.bias", "input_blocks.7.0.skip_connection.weight", "input_blocks.7.0.skip_connection.bias", "input_blocks.7.1.norm.weight", "input_blocks.7.1.norm.bias", "input_blocks.7.1.proj_in.weight", "input_blocks.7.1.proj_in.bias", "input_blocks.7.1.transformer_blocks.0.attn1.to_q.weight", "input_blocks.7.1.transformer_blocks.0.attn1.to_k.weight", "input_blocks.7.1.transformer_blocks.0.attn1.to_v.weight", "input_blocks.7.1.transformer_blocks.0.attn1.to_out.0.weight", "input_blocks.7.1.transformer_blocks.0.attn1.to_out.0.bias", "input_blocks.7.1.transformer_blocks.0.ff.net.0.proj.weight", "input_blocks.7.1.transformer_blocks.0.ff.net.0.proj.bias", "input_blocks.7.1.transformer_blocks.0.ff.net.2.weight", "input_blocks.7.1.transformer_blocks.0.ff.net.2.bias", "input_blocks.7.1.transformer_blocks.0.attn2.to_q.weight", "input_blocks.7.1.transformer_blocks.0.attn2.to_k.weight", "input_blocks.7.1.transformer_blocks.0.attn2.to_v.weight", "input_blocks.7.1.transformer_blocks.0.attn2.to_out.0.weight", "input_blocks.7.1.transformer_blocks.0.attn2.to_out.0.bias", "input_blocks.7.1.transformer_blocks.0.norm1.weight", "input_blocks.7.1.transformer_blocks.0.norm1.bias", "input_blocks.7.1.transformer_blocks.0.norm2.weight", "input_blocks.7.1.transformer_blocks.0.norm2.bias", "input_blocks.7.1.transformer_blocks.0.norm3.weight", "input_blocks.7.1.transformer_blocks.0.norm3.bias", "input_blocks.7.1.proj_out.weight", "input_blocks.7.1.proj_out.bias", "input_blocks.8.0.in_layers.0.weight", "input_blocks.8.0.in_layers.0.bias", "input_blocks.8.0.in_layers.2.weight", "input_blocks.8.0.in_layers.2.bias", "input_blocks.8.0.emb_layers.1.weight", "input_blocks.8.0.emb_layers.1.bias", "input_blocks.8.0.out_layers.0.weight", "input_blocks.8.0.out_layers.0.bias", "input_blocks.8.0.out_layers.3.weight", "input_blocks.8.0.out_layers.3.bias", "input_blocks.8.1.norm.weight", "input_blocks.8.1.norm.bias", "input_blocks.8.1.proj_in.weight", "input_blocks.8.1.proj_in.bias", "input_blocks.8.1.transformer_blocks.0.attn1.to_q.weight", "input_blocks.8.1.transformer_blocks.0.attn1.to_k.weight", "input_blocks.8.1.transformer_blocks.0.attn1.to_v.weight", "input_blocks.8.1.transformer_blocks.0.attn1.to_out.0.weight", "input_blocks.8.1.transformer_blocks.0.attn1.to_out.0.bias", "input_blocks.8.1.transformer_blocks.0.ff.net.0.proj.weight", "input_blocks.8.1.transformer_blocks.0.ff.net.0.proj.bias", "input_blocks.8.1.transformer_blocks.0.ff.net.2.weight", "input_blocks.8.1.transformer_blocks.0.ff.net.2.bias", "input_blocks.8.1.transformer_blocks.0.attn2.to_q.weight", "input_blocks.8.1.transformer_blocks.0.attn2.to_k.weight", "input_blocks.8.1.transformer_blocks.0.attn2.to_v.weight", "input_blocks.8.1.transformer_blocks.0.attn2.to_out.0.weight", "input_blocks.8.1.transformer_blocks.0.attn2.to_out.0.bias", "input_blocks.8.1.transformer_blocks.0.norm1.weight", "input_blocks.8.1.transformer_blocks.0.norm1.bias", "input_blocks.8.1.transformer_blocks.0.norm2.weight", "input_blocks.8.1.transformer_blocks.0.norm2.bias", "input_blocks.8.1.transformer_blocks.0.norm3.weight", "input_blocks.8.1.transformer_blocks.0.norm3.bias", "input_blocks.8.1.proj_out.weight", "input_blocks.8.1.proj_out.bias", "input_blocks.9.0.op.weight", "input_blocks.9.0.op.bias", "input_blocks.10.0.in_layers.0.weight", "input_blocks.10.0.in_layers.0.bias", "input_blocks.10.0.in_layers.2.weight", "input_blocks.10.0.in_layers.2.bias", "input_blocks.10.0.emb_layers.1.weight", "input_blocks.10.0.emb_layers.1.bias", "input_blocks.10.0.out_layers.0.weight", "input_blocks.10.0.out_layers.0.bias", "input_blocks.10.0.out_layers.3.weight", "input_blocks.10.0.out_layers.3.bias", "input_blocks.11.0.in_layers.0.weight", "input_blocks.11.0.in_layers.0.bias", "input_blocks.11.0.in_layers.2.weight", "input_blocks.11.0.in_layers.2.bias", "input_blocks.11.0.emb_layers.1.weight", "input_blocks.11.0.emb_layers.1.bias", "input_blocks.11.0.out_layers.0.weight", "input_blocks.11.0.out_layers.0.bias", "input_blocks.11.0.out_layers.3.weight", "input_blocks.11.0.out_layers.3.bias", "zero_convs.0.0.weight", "zero_convs.0.0.bias", "zero_convs.1.0.weight", "zero_convs.1.0.bias", "zero_convs.2.0.weight", "zero_convs.2.0.bias", "zero_convs.3.0.weight", "zero_convs.3.0.bias", "zero_convs.4.0.weight", "zero_convs.4.0.bias", "zero_convs.5.0.weight", "zero_convs.5.0.bias", "zero_convs.6.0.weight", "zero_convs.6.0.bias", "zero_convs.7.0.weight", "zero_convs.7.0.bias", "zero_convs.8.0.weight", "zero_convs.8.0.bias", "zero_convs.9.0.weight", "zero_convs.9.0.bias", "zero_convs.10.0.weight", "zero_convs.10.0.bias", "zero_convs.11.0.weight", "zero_convs.11.0.bias", "input_hint_block.0.weight", "input_hint_block.0.bias", "input_hint_block.2.weight", "input_hint_block.2.bias", "input_hint_block.4.weight", "input_hint_block.4.bias", "input_hint_block.6.weight", "input_hint_block.6.bias", "input_hint_block.8.weight", "input_hint_block.8.bias", "input_hint_block.10.weight", "input_hint_block.10.bias", "input_hint_block.12.weight", "input_hint_block.12.bias", "input_hint_block.14.weight", "input_hint_block.14.bias", "middle_block.0.in_layers.0.weight", "middle_block.0.in_layers.0.bias", "middle_block.0.in_layers.2.weight", "middle_block.0.in_layers.2.bias", "middle_block.0.emb_layers.1.weight", "middle_block.0.emb_layers.1.bias", "middle_block.0.out_layers.0.weight", "middle_block.0.out_layers.0.bias", "middle_block.0.out_layers.3.weight", "middle_block.0.out_layers.3.bias", "middle_block.1.norm.weight", "middle_block.1.norm.bias", "middle_block.1.proj_in.weight", "middle_block.1.proj_in.bias", "middle_block.1.transformer_blocks.0.attn1.to_q.weight", "middle_block.1.transformer_blocks.0.attn1.to_k.weight", "middle_block.1.transformer_blocks.0.attn1.to_v.weight", "middle_block.1.transformer_blocks.0.attn1.to_out.0.weight", "middle_block.1.transformer_blocks.0.attn1.to_out.0.bias", "middle_block.1.transformer_blocks.0.ff.net.0.proj.weight", "middle_block.1.transformer_blocks.0.ff.net.0.proj.bias", "middle_block.1.transformer_blocks.0.ff.net.2.weight", "middle_block.1.transformer_blocks.0.ff.net.2.bias", "middle_block.1.transformer_blocks.0.attn2.to_q.weight", "middle_block.1.transformer_blocks.0.attn2.to_k.weight", "middle_block.1.transformer_blocks.0.attn2.to_v.weight", "middle_block.1.transformer_blocks.0.attn2.to_out.0.weight", "middle_block.1.transformer_blocks.0.attn2.to_out.0.bias", "middle_block.1.transformer_blocks.0.norm1.weight", "middle_block.1.transformer_blocks.0.norm1.bias", "middle_block.1.transformer_blocks.0.norm2.weight", "middle_block.1.transformer_blocks.0.norm2.bias", "middle_block.1.transformer_blocks.0.norm3.weight", "middle_block.1.transformer_blocks.0.norm3.bias", "middle_block.1.proj_out.weight", "middle_block.1.proj_out.bias", "middle_block.2.in_layers.0.weight", "middle_block.2.in_layers.0.bias", "middle_block.2.in_layers.2.weight", "middle_block.2.in_layers.2.bias", "middle_block.2.emb_layers.1.weight", "middle_block.2.emb_layers.1.bias", "middle_block.2.out_layers.0.weight", "middle_block.2.out_layers.0.bias", "middle_block.2.out_layers.3.weight", "middle_block.2.out_layers.3.bias", "middle_block_out.0.weight", "middle_block_out.0.bias". 
	Unexpected key(s) in state_dict: "conv3_3.bias", "Mconv5_stage2_L2.bias", "conv5_3_CPM_L2.bias", "conv5_1_CPM_L2.bias", "Mconv3_stage3_L1.bias", "Mconv1_stage2_L1.weight", "Mconv2_stage5_L1.weight", "Mconv7_stage2_L1.bias", "Mconv3_stage2_L2.weight", "Mconv6_stage5_L1.weight", "conv3_1.weight", "Mconv1_stage2_L2.bias", "Mconv3_stage5_L1.weight", "Mconv1_stage3_L1.weight", "Mconv7_stage2_L2.weight", "Mconv5_stage3_L1.bias", "Mconv6_stage3_L2.bias", "Mconv4_stage6_L1.bias", "conv3_3.weight", "Mconv1_stage5_L2.weight", "Mconv2_stage4_L2.bias", "Mconv6_stage2_L2.weight", "Mconv2_stage2_L1.bias", "Mconv5_stage4_L1.bias", "Mconv5_stage2_L1.weight", "conv3_2.weight", "Mconv6_stage3_L1.bias", "conv5_2_CPM_L2.bias", "conv5_1_CPM_L2.weight", "Mconv1_stage5_L1.bias", "Mconv5_stage6_L2.bias", "Mconv2_stage4_L1.bias", "Mconv5_stage3_L2.bias", "conv5_5_CPM_L1.weight", "Mconv4_stage4_L1.weight", "Mconv5_stage4_L2.bias", "Mconv4_stage5_L1.bias", "Mconv3_stage5_L1.bias", "Mconv4_stage2_L1.bias", "Mconv1_stage5_L2.bias", "Mconv6_stage6_L2.bias", "Mconv5_stage6_L1.bias", "Mconv6_stage6_L1.weight", "Mconv7_stage3_L1.bias", "Mconv7_stage6_L1.bias", "Mconv6_stage6_L2.weight", "Mconv7_stage2_L1.weight", "Mconv6_stage3_L1.weight", "Mconv6_stage2_L1.bias", "Mconv6_stage2_L1.weight", "conv5_1_CPM_L1.weight", "Mconv5_stage6_L1.weight", "Mconv4_stage3_L1.bias", "conv5_2_CPM_L1.weight", "Mconv1_stage4_L2.weight", "Mconv2_stage2_L1.weight", "Mconv4_stage3_L2.weight", "conv4_2.weight", "conv2_2.bias", "Mconv6_stage3_L2.weight", "Mconv2_stage6_L1.bias", "conv1_2.bias", "Mconv3_stage2_L2.bias", "Mconv3_stage5_L2.weight", "Mconv7_stage5_L1.weight", "Mconv1_stage4_L2.bias", "Mconv3_stage3_L1.weight", "conv1_1.bias", "Mconv1_stage5_L1.weight", "Mconv4_stage2_L1.weight", "conv4_3_CPM.weight", "conv4_1.bias", "Mconv1_stage2_L1.bias", "conv2_2.weight", "conv4_3_CPM.bias", "Mconv2_stage3_L1.bias", "conv5_2_CPM_L2.weight", "conv5_5_CPM_L2.weight", "Mconv7_stage5_L2.bias", "Mconv3_stage3_L2.weight", "Mconv5_stage3_L1.weight", "Mconv2_stage5_L1.bias", "Mconv3_stage6_L2.bias", "Mconv1_stage3_L2.weight", "conv4_2.bias", "conv5_1_CPM_L1.bias", "Mconv6_stage4_L2.bias", "conv5_5_CPM_L1.bias", "Mconv5_stage4_L1.weight", "conv5_4_CPM_L2.bias", "Mconv6_stage2_L2.bias", "Mconv2_stage3_L1.weight", "Mconv6_stage4_L1.weight", "Mconv5_stage6_L2.weight", "Mconv3_stage4_L2.weight", "Mconv3_stage4_L2.bias", "Mconv3_stage6_L1.bias", "conv5_5_CPM_L2.bias", "Mconv7_stage6_L2.weight", "Mconv7_stage3_L1.weight", "Mconv6_stage5_L2.weight", "Mconv4_stage6_L2.bias", "Mconv7_stage5_L1.bias", "Mconv3_stage6_L2.weight", "Mconv1_stage6_L1.weight", "Mconv4_stage6_L2.weight", "Mconv5_stage2_L1.bias", "Mconv3_stage2_L1.weight", "Mconv3_stage3_L2.bias", "Mconv2_stage4_L1.weight", "Mconv6_stage6_L1.bias", "Mconv5_stage2_L2.weight", "Mconv4_stage3_L1.weight", "Mconv7_stage4_L2.weight", "Mconv4_stage4_L1.bias", "Mconv4_stage5_L2.bias", "conv4_4_CPM.weight", "Mconv2_stage4_L2.weight", "Mconv2_stage5_L2.weight", "Mconv7_stage6_L1.weight", "conv4_1.weight", "Mconv2_stage6_L2.weight", "conv2_1.bias", "Mconv6_stage5_L2.bias", "Mconv4_stage5_L1.weight", "Mconv2_stage3_L2.weight", "conv3_2.bias", "conv4_4_CPM.bias", "Mconv5_stage3_L2.weight", "Mconv3_stage4_L1.bias", "conv5_3_CPM_L1.bias", "Mconv5_stage5_L1.weight", "conv1_2.weight", "conv5_3_CPM_L1.weight", "Mconv4_stage4_L2.weight", "Mconv3_stage2_L1.bias", "Mconv3_stage4_L1.weight", "Mconv3_stage6_L1.weight", "conv5_2_CPM_L1.bias", "Mconv1_stage6_L1.bias", "Mconv2_stage3_L2.bias", "Mconv2_stage6_L1.weight", "Mconv7_stage4_L2.bias", "Mconv4_stage3_L2.bias", "conv3_1.bias", "Mconv2_stage2_L2.bias", "Mconv3_stage5_L2.bias", "Mconv4_stage2_L2.bias", "Mconv1_stage4_L1.bias", "Mconv4_stage6_L1.weight", "Mconv5_stage5_L2.weight", "Mconv6_stage5_L1.bias", "Mconv2_stage2_L2.weight", "Mconv4_stage2_L2.weight", "Mconv7_stage6_L2.bias", "Mconv1_stage6_L2.weight", "Mconv1_stage2_L2.weight", "Mconv1_stage4_L1.weight", "Mconv1_stage3_L1.bias", "conv5_4_CPM_L1.weight", "Mconv7_stage4_L1.bias", "Mconv6_stage4_L1.bias", "Mconv2_stage5_L2.bias", "conv3_4.weight", "conv3_4.bias", "Mconv5_stage5_L1.bias", "Mconv7_stage3_L2.weight", "Mconv1_stage6_L2.bias", "conv5_3_CPM_L2.weight", "Mconv5_stage4_L2.weight", "Mconv4_stage4_L2.bias", "Mconv7_stage4_L1.weight", "conv5_4_CPM_L1.bias", "conv5_4_CPM_L2.weight", "conv1_1.weight", "Mconv7_stage2_L2.bias", "Mconv7_stage3_L2.bias", "conv2_1.weight", "Mconv1_stage3_L2.bias", "Mconv2_stage6_L2.bias", "Mconv4_stage5_L2.weight", "Mconv5_stage5_L2.bias", "Mconv7_stage5_L2.weight", "Mconv6_stage4_L2.weight". 
`

**Comment by Mikubill** [comment]
Seems like the model file is incorrect, could you redownload it and try again? Make sure it's ControlNet (full/pruned) not sd model

**Comment by yesyeahvh123** [comment]
this 
![Capture](https://user-images.githubusercontent.com/69633089/218934089-db88b3d5-94a6-4c59-a26f-23b1d3f1b66b.PNG)

**Comment by yesyeahvh123** [comment]
@Mikubill i download model from this https://huggingface.co/lllyasviel/ControlNet/resolve/main/annotator/ckpts/body_pose_model.pth ,I'm new so I don't know much, is that right?

**Comment by yesyeahvh123** [comment]
![Capture1](https://user-images.githubusercontent.com/69633089/218935587-14f41f83-82da-452c-9a5a-d892a8b827e1.PNG)
![Capture](https://user-images.githubusercontent.com/69633089/218935594-a5f55ef8-90e7-4718-b994-a16e6f037873.PNG)

**Comment by Mikubill** [comment]
> Put the ControlNet models (.pt, .pth, .ckpt or .safetensors) inside the sd-webui-controlnet/models folder.

Download it from:
https://huggingface.co/lllyasviel/ControlNet/tree/main/models or https://huggingface.co/webui/ControlNet-modules-safetensors

**Comment by yesyeahvh123** [comment]
@Mikubill thank you, what model good for realistic character?
