### ISSUE TITLE
[Bug]: Crash when using t2iadapter_style-fp16

### ISSUE THREAD

**Issue by ernestp** [Mikubill/sd-webui-controlnet#551]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Automatic1111 crashed

### Steps to reproduce the problem

set appropriate adapter in settings
enable controlnet
choose clip_vision and style adapter
generate image

same error happens with pth model

### What should have happened?

style applied

### Commit where the problem happens

webui: python: 3.10.10  •  torch: 2.0.0.dev20230210  •  xformers: N/A  •  gradio: 3.16.2  •  commit: [0cc0ee1b](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8)  •  checkpoint: [cc6cb27103](https://google.com/search?q=cc6cb27103417325ff94f52b7a5d2dde45a7515b25c255d8e396c90014281516)
controlnet: e5ed9fccdc4fbbe5ec4aae134371683528f7bd60

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--upcast-sampling --opt-sub-quad-attention --use-cpu interrogate --no-half-vae
```

### Console logs

```Shell
Loading model: t2iadapter_style-fp16 [0e2e8330]
Loaded state_dict from [/Users/nemo/stable-diffusion-webui/extensions/sd-webui-controlnet/models/t2iadapter_style-fp16.safetensors]
ControlNet model t2iadapter_style-fp16 [0e2e8330] loaded.
Loading preprocessor: clip_vision
  0%|                                                                                       | 0/20 [00:00<?, ?it/s]loc("mps_multiply"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/9e200cfa-7d96-11ed-886f-a23c4f261b56/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":228:0)): error: input types 'tensor<1x265x1024xf32>' and 'tensor<1024xf16>' are not broadcast compatible
LLVM ERROR: Failed to infer result type(s).
```

**Comment by ClashSAN** [comment]
mac issue https://github.com/Mikubill/sd-webui-controlnet/issues/523

**Comment by ernestp** [comment]
Interstingly, if I change command line parameters to 

--use-cpu interrogate --no-half-vae --no-half

then error is different:

/AppleInternal/Library/BuildRoots/c651a45f-806e-11ed-a221-7ef33c48bc85/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSCore/Types/MPSNDArray.mm:82: failed assertion `[MPSNDArrayDescriptor sliceDimension:withSubrange:] error: subRange.start (52992) is not less than length of dimension[1] (77)'

**Comment by ernestp** [comment]
I'm using pytorch 2.0.0.dev20230210

if use pytorch v0.12.1 then getting the same issue as in https://github.com/Mikubill/sd-webui-controlnet/issues/523
