### ISSUE TITLE
How can I add lowvram mode on the controlnet?

### ISSUE THREAD

**Issue by TeppiTa2009** [Mikubill/sd-webui-controlnet#554]
Hi, I just find out that in the original controlnet github, there is an option to use the lowvram mode and it require to change the config in the file config.py. However, I cannot find any file that name config.py, maybe there is in somewhere but I cannot see it, could you tell me how to do so?

**Comment by rayofshadow23** [comment]
there is a checkbox to flag
![image](https://user-images.githubusercontent.com/63224259/224319933-2fc06f42-416d-4358-bd51-7c7e35038ee0.png)

**Comment by TeppiTa2009** [comment]
oh thank you so much
