### ISSUE TITLE
[Bug]: color adapter error

### ISSUE THREAD

**Issue by demirklvc** [Mikubill/sd-webui-controlnet#559]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

RuntimeError: pixel_unshuffle expects height to be divisible by downscale_factor, but input.size(-2)=257 is not divisible by 8

after updating, it gives me this error. -.-

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...
.

### What should have happened?

.

### Commit where the problem happens

webui: 
controlnet: 
auto1111, locally, windows

### Command Line Arguments

```Shell
.
```

### Console logs

```Shell
.
```

**Comment by TimpaniniTiger** [comment]
I had the same issue, you need to use the t2i_color_grid preprocessor with the t2iadaptor_color model (not the t2ia_style_clipvision preprocessor which will cause this error).
