### ISSUE TITLE
Issue: Error Running Process - Controlnet.py

### ISSUE THREAD

**Issue by ThatBrett** [Mikubill/sd-webui-controlnet#562]
I get an error when I try to use ControlNet.  It seems to have a problem running Controlnet.py.  I didn't file this as a bug, because I assume it's some kind of user error (I'm new within the last week, and not a coder).  So far, no one seems to be able to tell me what it is though,

Attached are screen grabs of the error, my initial startup, the web ui, and my settings in the interface.  Just to be sure, I did a new install this morning, and walked though all the installs for both Python, Git, SD (AMD workaround from lshqqytiger), and CN.  If it said to upgrade something, I upgraded that.  So pip is the latest, and I ran the gradio check, but it said it was up to date (I think).

System Specs
OS: Win 10 Home - 10.01.19044
Processor: Intel Core i5-10600
Mother Board: Asus Rog Strix Z490-E
Video Card: AMD Radeon RX 6950 XT
Ram: 16gb

All system components should be running at factory settings.

![WebUI Edit - 2023 03 10](https://user-images.githubusercontent.com/127553283/224503347-5be03ef0-bfa9-4cd0-94c4-8db2e5767807.png)

<img width="958" alt="Initial Startup" src="https://user-images.githubusercontent.com/127553283/224503285-34d66706-8a93-4c1e-9634-b979f1825197.png">

![Txt2Img Settings](https://user-images.githubusercontent.com/127553283/224503295-30068504-fce1-4b62-8e81-c1fad92e0d68.png)

![ControlNet Settings](https://user-images.githubusercontent.com/127553283/224503302-2929e37f-8a62-4e4e-9567-5d921a45f068.png)

<img width="958" alt="Controlnet Error 1a" src="https://user-images.githubusercontent.com/127553283/224503311-ddfd9362-8932-4e19-8d57-2401ae346213.png">

<img width="957" alt="Controlnet Error 1b" src="https://user-images.githubusercontent.com/127553283/224503321-fcfd376e-7e0f-4a63-8528-cefd360514b2.png">

**Comment by Sto3IV** [comment]
same
