### ISSUE TITLE
[Bug]: I can't get API call to load any Controlnet process

### ISSUE THREAD

**Issue by lenkunz** [Mikubill/sd-webui-controlnet#571]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I trying to run this extension via API call using /controlnet/txt2img
The txt2img run fine but the controlnet model doesn't kick in. 
No log in console that the model was loaded. The result image didn't look like it has any controlnet applied.

Using it via UI works fine thou.

This is my POST body. I have stripped out the base64 image, model and the prompts.
```json
{
    "enable_hr": false,
    "hr_scale": 1,
    "hr_upscaler": "Latent (nearest-exact)",
    "hr_second_pass_steps": 20,
    "hr_resize_x": 0,
    "hr_resize_y": 0,
    "denoising_strength": 0.4,
    "firstphase_width": 0,
    "firstphase_height": 0,
    "prompt": "prompt...",
    "styles": [],
    "seed": 1841357043,
    "subseed": -1,
    "subseed_strength": 0.0,
    "seed_resize_from_h": -1,
    "seed_resize_from_w": -1,
    "batch_size": 1,
    "n_iter": 1,
    "steps": 25,
    "cfg_scale": 10,
    "width": 512,
    "height": 512,
    "restore_faces": false,
    "tiling": false,
    "negative_prompt": "negative prompt...",
    "eta": 0,
    "s_churn": 0,
    "s_tmax": 0,
    "s_tmin": 0,
    "s_noise": 1,
    "override_settings": {
        "sd_model_checkpoint": "model...",
        "CLIP_stop_at_last_layers": 2
    },
    "override_settings_restore_afterwards": true,
    "sampler_name": "Euler a",
    "sampler_index": "Euler a",
    "script_name": null,
    "script_args": [],
    "controlnet_units": [
        {
            "input_image": "base64img...",
            "mask": "",
            "module": "none",
            "model": "difference_controlSd15Openpose [1723948e]",
            "weight": 1.0,
            "resize_mode": "Scale to Fit (Inner Fit)",
            "lowvram": false,
            "processor_res": 64,
            "threshold_a": 64,
            "threshold_b": 64,
            "guidance": 1.0,
            "guidance_start": 0.0,
            "guidance_end": 1.0,
            "guessmode": false
        }
    ]
}
```

### Steps to reproduce the problem

1. Call API /controlnet/txt2img with provided JSON body
2. Wait for result.

### What should have happened?

It should have generates image with controlnet applied as works with UI

### Commit where the problem happens

webui: 
AUTOMATIC1111/stable-diffusion-webui@ab0b0e1e767ddc7ceeaced11513c3692538938eb
controlnet: 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--xformers --no-half-vae --listen --api --enable-insecure-extension-access
```

### Console logs

```Shell
Nothing weird
```

**Comment by Mikubill** [comment]
Hmm…Maybe manually tick enable checkbox in ui could help?

**Comment by AbdullahAlfaraj** [comment]
I'm also experiencing the same issue: even when I use my own detectmap and set the preprocessors to "none", the ControlNet API continues to produce results that do not resemble the input image.


I've also noticed that the output images array is always missing the detectmap result, regardless of the preprocessors I select.


I've also tested the ControlNet settings in the webui, but I'm not seeing the expected effect via the api.

![image](https://user-images.githubusercontent.com/7842232/224558431-40920fad-39c4-4c7c-aa0c-2bf236dbea00.png)

**Comment by lenkunz** [comment]
It seems the problems came from Automatic1111 side.
I notice that there's a lot of commits yesterday. I have reverted it about 50 commits and it's now working again.

I don't sure which commit broke it. But it may take time to investigate.

**Comment by Vespinian** [comment]
I think that to work with the new API changes the hijack needs to change. The args past in the hijack get overwritten by the script_args initialization. To make it work again with the changes the code could add the cnet param from the control net request to the new alwayson_scripts dict instead of creating a script_runner.

related #567

**Comment by dotsimulate** [comment]
local docs after the past day of commits lists the deprecated non control_units call. adjusted for that, but still no effect from controlnet. glad its being looked into.

**Comment by Vespinian** [comment]
For now, if you don't want to remove the commit. You should just be able to use the auto1111 routes with the new `alwayson_scripts` api field.

For a txt2img it, would look something like this

```json
{
    "enable_hr": false,
    "hr_scale": 1,
    "hr_upscaler": "Latent (nearest-exact)",
    "hr_second_pass_steps": 20,
    "hr_resize_x": 0,
    "hr_resize_y": 0,
    "denoising_strength": 0.4,
    "firstphase_width": 0,
    "firstphase_height": 0,
    "prompt": "prompt...",
    "styles": [],
    "seed": 1841357043,
    "subseed": -1,
    "subseed_strength": 0.0,
    "seed_resize_from_h": -1,
    "seed_resize_from_w": -1,
    "batch_size": 1,
    "n_iter": 1,
    "steps": 25,
    "cfg_scale": 10,
    "width": 512,
    "height": 512,
    "restore_faces": false,
    "tiling": false,
    "negative_prompt": "negative prompt...",
    "eta": 0,
    "s_churn": 0,
    "s_tmax": 0,
    "s_tmin": 0,
    "s_noise": 1,
    "override_settings": {
        "sd_model_checkpoint": "model...",
        "CLIP_stop_at_last_layers": 2
    },
    "override_settings_restore_afterwards": true,
    "sampler_name": "Euler a",
    "sampler_index": "Euler a",
    "script_name": null,
    "script_args": [],
    "alwayson_scripts": {
      "ControlNet": {
        "args": [false, false,
            true,
            "none",
            "difference_controlSd15Openpose [1723948e]",
            1.0,
            {"image": "base64img..."},
            false,
            "Scale to Fit (Inner Fit)",
             false,
             false,
             64,
             64,
             64,
            0.0,
            1.0,
            false
            ]
        }
    }
}

```

img2img would have the first false in the controlnet args turn true

**Comment by dotsimulate** [comment]
Word, I can confirm that it works currently with the alwayson_scipts method above

**Comment by Vespinian** [comment]
I made a quick and dirty fix that should make the cnet api calls work [here](https://github.com/Vespinian/sd-webui-controlnet/tree/quick-fix-for-old-api-calls) if you want to continue using them for the time being. It just dumps the cnet units into the alwayson_scripts. That being said, I assume a bit of refactoring is going to occur soon with #567

**Comment by rbbrdckybk** [comment]
@Vespinian Thanks, can confirm that the alwayson_scripts method is working for me! 

Is there a reference for what the values in the "args" list map to? The image, module, and model entries are obvious, but the multiple booleans and various duplicate numbers are ambiguous.

**Comment by Vespinian** [comment]
They are listed in #567 

```
[
  false,  # is_img2img
  false,  # is_ui
  true,   # enabled,
  "canny",    # module,
  "control_canny-fp16 [e3fe7712]",    # model,
  1,    # weight,
  {"image":"BASE64_IMAGE_STRING", "mask": "BASE64_IMAGE_STRING"},    # image/mask,
  false,    # scribble_mode,
  "Scale to Fit (Inner Fit)",   # resize_mode,
  false,    # rgbbgr_mode,
  false,    # lowvram,
  512,    # pres,
  100,    # pthr_a,
  200,    # pthr_b,
  0,    # guidance_start,
  1,    # guidance_end,
  false   # guess_mode
]
```
and the last 15 repeat for every module you have

**Comment by rbbrdckybk** [comment]
@Vespinian thanks for the quick response!

**Comment by nguyenvuducthuy** [comment]
Are there anyone have a same problem, I disable Preprocessor and control net not going to work any more, It's working when Preprocessor on only

           "alwayson_scripts":
            {
                "ControlNet":
                {
                    "args":
                    [
                        True,  # is_img2img
                        False,  # is_ui
                        True,   # enabled,
                        "none",    # module,
                        "control_openpose-fp16 [9ca67cc5]",    # model,
                        1,    # weight,
                        {"image":cn_img},    # image/mask,
                        False,    # scribble_mode,
                        "Scale to Fit (Inner Fit)",   # resize_mode,
                        False,    # rgbbgr_mode,
                        False,    # lowvram,
                        512,    # pres,
                        64,    # pthr_a,
                        64,    # pthr_b,
                        0,    # guidance_start,
                        1,    # guidance_end,
                        False   # guess_mode
                    ]
                }
            }

**Comment by ljleb** [comment]
@nguyenvuducthuy This is not how to call the API. Let me edit the wiki to help users migrate routes in advance.
