### ISSUE TITLE
[Bug]: ControlNet models are reloaded each *external code-API* call

### ISSUE THREAD

**Issue by kabachuha** [Mikubill/sd-webui-controlnet#572]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When using the [external code API](https://github.com/Mikubill/sd-webui-controlnet/wiki/API#external-code-api) to launch CN generations from the Deforum extension, the same selected CN model is being reloaded on each call.

It seems like it's very similar to https://github.com/Mikubill/sd-webui-controlnet/issues/429, but it happened for the **web API** then, and not to the code API.

### Steps to reproduce the problem

1. Go to the Deforum extension at this WIP branch https://github.com/deforum-art/deforum-for-automatic1111-webui/pull/454
2. Press ControlNet tab, click 'Enable' and select a model with a preprocessor, upload the input video
3. Click 'Generate'
4. Observe that the model is loaded and unloaded each time which slows down the animation process dramatically.

### What should have happened?

The currently selected model should stay in memory until a new one is selected.

### Commit where the problem happens

webui: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8
controlnet: c9340671d6d59e5a79fc404f78f747f969f87374
Deforum: https://github.com/deforum-art/deforum-for-automatic1111-webui/pull/454

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
--gradio-debug --port 8892 --xformers --xformers-flash-attention --no-half-vae
```

### Console logs

```Shell
https://gist.github.com/kabachuha/380ca49b73dc7ec8ee8911bcf2ccad1a
```

**Comment by hananbeer** [comment]
It says "loading model **from cache**" I just tested it and it does not have any overhead whatsoever.

**Comment by kabachuha** [comment]
Oh, I see

https://github.com/Mikubill/sd-webui-controlnet/blob/4c13542c931f9401a4072b2f7fc9eb704e74a2f8/scripts/controlnet.py#L530-L535

it does load them from a dictionary, just a misleading message
