### ISSUE TITLE
when call the api, I got TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by MrWWY** [Mikubill/sd-webui-controlnet#578]
my Command Line Arguments: 
python webui.py --port 6006 --xformers --no-half-vae --listen --api --enable-insecure-extension-access

<img width="1363" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/31330418/224603124-8657ecf4-adb9-4020-8998-0080c9ab18b0.png">
<img width="1096" alt="A n  lee Die, le-aall" src="https://user-images.githubusercontent.com/31330418/224603138-74c69554-1747-4759-8005-0fca954d435f.png">
<img width="1082" alt="Soleaproeesslmg py  1ine 6e  ln Procees aepe" src="https://user-images.githubusercontent.com/31330418/224603142-a8a311cb-5a2b-46c7-9622-881dd816570c.png">

**Comment by ljleb** [comment]
The webui was updated recently. If you are using the latest version of the webui, the `/controlnet/*2img` will stop working.

**Comment by MrWWY** [comment]
yeah, I noticed the api is deprecated. Now we can use Controlnet and other scripts from the /sdapi/v1/txt2img and sdapi/v1/img2img with parameter  alwayson_scripts ! Cool
Thank you~ 
https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/8187
