### ISSUE TITLE
Segmentation preprocessor is missing prettytable package

### ISSUE THREAD

**Issue by Danamir** [Mikubill/sd-webui-controlnet#58]
When trying the `segmentation` preprocessor, I had a Python error trying to import from the `prettytable` package.

I don't know if this error was specific to my system, but it was easily corrected with :  
```
venv\Script\activate.bat
pip install prettytable
```

To be safe, the package should be added to the requirements for auto-install.

**Comment by butaixianran** [comment]
Document has already told you to install prettytable before you using segmentation, you just do not read it

**Comment by Danamir** [comment]
Oh, the readme was updated. I gave it a full read only the first time. 
Since the package is pretty lightweight, it could still be a good idea to just require it.

**Comment by enternalsaga** [comment]
hey, anyone solve it?   When I tried segment, it says:
File "I:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\uniformer\mmseg\datasets\custom.py", line 9, in <module>
    from prettytable import PrettyTable
ModuleNotFoundError: No module named 'prettytable'

But I already installed it:
I:\stable-diffusion-webui>pip install prettytable
Requirement already satisfied: prettytable in c:\users\nba\appdata\local\programs\python\python310\lib\site-packages (3.6.0)
Requirement already satisfied: wcwidth in c:\users\nba\appdata\local\programs\python\python310\lib\site-packages (from prettytable) (0.2.6)

What's the problem?

**Comment by Danamir** [comment]
> Requirement already satisfied: prettytable in c:\users\nba\appdata\local\programs\python\python310\lib\site-packages (3.6.0)

The package seems to be installed in your system Python. It needs to be installed in the stable-diffusion-webui virtual env.
Try this command before the pip install one : `.\venv\Scripts\activate.bat` .

**Comment by jnpatrick99** [comment]
I have the same problem, I ran `.\venv\Scripts\activate.bat` and then `pip install prettytable` it said everything is installed but then when I run web I get the message `ModuleNotFoundError: No module named 'prettytable'`.

**Comment by ClashSAN** [comment]
@jnpatrick99 you can just add `prettytable` to requirements.txt, run webui once, and remove `prettytable` from requirements.txt to not conflict with git pull updates

**Comment by enternalsaga** [comment]
> > Requirement already satisfied: prettytable in c:\users\nba\appdata\local\programs\python\python310\lib\site-packages (3.6.0)
> 
> The package seems to be installed in your system Python. It needs to be installed in the stable-diffusion-webui virtual env. Try this command before the pip install one : `.\venv\Scripts\activate.bat` .

thank you. I did paste the whole command lines to cmd but it always point to my system. 
![image](https://user-images.githubusercontent.com/31148570/219225368-923a6fdd-444c-4947-9184-5c5706ad03cf.png)

**Comment by ClashSAN** [comment]
@Danamir its now added as a requirement: https://github.com/Mikubill/sd-webui-controlnet/commit/5184a46a1d4af8d74b64f103a213bf789e020aea#diff-a5fa297e66b71ac1a8685caa5c37577774be2c36024ecda7abeb70bb50214d0f

**Comment by Danamir** [comment]
Nice, thanks. Closing the issue.
