### ISSUE TITLE
[BUG?] Opening images doesn't offer PNG files

### ISSUE THREAD

**Issue by Woisek** [Mikubill/sd-webui-controlnet#580]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Since I have and use this extension, it is so, that opening an image does not consider PNG files. Every other image extension is offered, but not the important, the main one.

### Steps to reproduce the problem

1. Click on image upload
2. Can't select PNG files

### What should have happened?

Should be able to select PNG files

### Commit where the problem happens

webui: https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/dfeee786f903e392dbef1519c7c246b9856ebab3
controlnet: f0a82190 

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
n/a
```

**Comment by missionfloyd** [comment]
This is a [gradio bug](https://github.com/gradio-app/gradio/issues/2110). It's since been [fixed](https://github.com/gradio-app/gradio/pull/3002).

You should be able to select "All files" here:
![image](https://user-images.githubusercontent.com/4073789/224847439-590746f7-44d0-4620-ae74-1635875c3a10.png)

**Comment by Woisek** [comment]
> You should be able to select "All files" here:

Well ... that's exactly the problem: I have _always_ to select "All files" to be able to select PNG files instead that the PNG extension is in the list of "all supported types" as it should be. It is annoying always have to make this extra click ... :/

**Comment by Woisek** [comment]
So ... is this going to be fixed or not ... ?

**Comment by missionfloyd** [comment]
As I said, this is a problem with gradio. The way to fix it is to use a newer version, which is being worked on.
https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/8752

**Comment by Woisek** [comment]
> As I said, this is a problem with gradio. The way to fix it is to use a newer version, which is being worked on. [AUTOMATIC1111/stable-diffusion-webui#8752](https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/8752)

OK, and how is Gradio updated? Is it done with Automatic1111 or has it to be done manually somehow? And if so, how should it be performed?

**Comment by missionfloyd** [comment]
If/when that PR is merged, run `git pull` in the `stable-diffusion-webui` folder, and Gradio will be updated the next time you start it.

**Comment by Woisek** [comment]
OK, thanks.
