### ISSUE TITLE
Can't call API from another computer in the same local network

### ISSUE THREAD

**Issue by popkingcorn** [Mikubill/sd-webui-controlnet#581]
I have two computers:

- first wich running webui-controlnet

- second wich trying to call api

The problem is that site can’t be reached. Port 7860 is opened.
Locally on one computer all works great.

P.S. i dont't wan't to use public url

**Comment by ljleb** [comment]
Nothing to do with this extension. add `--listen` to your webui args.

**Comment by popkingcorn** [comment]
Adding --listen to args solved my problem. Thanks a lot =)
