### ISSUE TITLE
the red bounding box on "resize" in img2img stops working when controlnet extension is installed

### ISSUE THREAD

**Issue by genewitch** [Mikubill/sd-webui-controlnet#607]
Not sure how else to describe it. on a base install of auto1111 if you go to the img2img tab and load an image, you can click the resize sliders and see the red box overlay of how big the output image will be relative to the input image - so you can get the aspect ratio correct.

after installing controlnet on two different machines, i've lost the ability to see this red bounding box. 

Is there a way to get it back? Is there already a bug for this?

**Comment by ljleb** [comment]
I did a fresh install of webui but I cannot see which feature the "red bounding box" refers to. I do not see any red rectangle when clicking the pencil icon on a loaded image:

![image](https://user-images.githubusercontent.com/32277961/225824271-efc3e055-aa32-4d1e-83a9-a3f9d5993287.png)

I would appreciate if you could share a screenshot of what you expect to see.

**Comment by LonicaMewinsky** [comment]
@genewitch is this what you're talking about? (This scales with the w/h generation sliders).
![image](https://user-images.githubusercontent.com/93007558/225993529-ce48fd5e-4565-4a84-b327-4564b8e0b504.png)

FWIW, works on my machine with fresh/current clones, but I have seen it randomly stop working (even prior to controlnet extension). Any other extensions at work here?

**Comment by genewitch** [comment]
Lonica:

only image browser extension. If we're sure this is an auto1111 rather than a controlnet extension issue, i can make a bug report over there.

I've never experienced "random" or otherwise non-working bounding box except after installing controlnet.

**Comment by genewitch** [comment]
![image](https://user-images.githubusercontent.com/3182020/226165359-79747fef-d367-44ca-9c97-66e532245cad.png)
This red bounding box stops working after controlnet is installed - sometimes.

**Comment by xiaofei-zhu** [comment]
i met the same issue, any solution for this?

**Comment by genewitch** [comment]
it stopped; it is possible something updated (an extension probably) - maybe just a fluke.
