### ISSUE TITLE
Feature Request: support for new T2i CoAdapter demo models

### ISSUE THREAD

**Issue by AugmentedRealityCat** [Mikubill/sd-webui-controlnet#614]
Tencent has released a [new feature for T2i: Composable Adapters](https://github.com/TencentARC/T2I-Adapter/blob/main/docs/coadapter.md). 
New models based on that feature have been [released on Huggingface.](https://huggingface.co/TencentARC/T2I-Adapter/tree/main/models)
We find the usual suspects over there (depth, canny, etc.) but one of these new 1.5 models has a completely new identity : [coadapter-**fuser**-sd15v1.pth](https://huggingface.co/TencentARC/T2I-Adapter/blob/main/models/coadapter-fuser-sd15v1.pth)
@Dfaker also started a [discussion on the subject](https://github.com/Mikubill/sd-webui-controlnet/discussions/609). 

> We introduce CoAdapter (Composable Adapter) by jointly training T2I-Adapters and an extra fuser. The fuser allows different adapters with various conditions to be aware of each other and synergize to achieve more powerful composability, especially the combination of element-level style and other structural information.
> 
> CoAdapter is inspired by [Composer](https://github.com/damo-vilab/composer). However, instead of training the whole model, it only trains extra light-weight adapters based on T2I-Adapter. But CoAdapter can also show the capability of generating creative images with composibility. Note that the model is still in training and this release is only a preview.

| Sketch                                                                                                                                    | Canny |                                                                   Depth                                                                   | Color (Spatial) | Style                                                                                                                                      | Results |
|:------------------------------------------------------------------------------------------------------------------------------------------|:-----:|:-----------------------------------------------------------------------------------------------------------------------------------------:|:---------------:|--------------------------------------------------------------------------------------------------------------------------------------------|---------|
| <img width="200" alt="image" src="https://user-images.githubusercontent.com/11482921/225659269-2d50e40d-f79b-41bc-9a0e-9dc73663f010.png"> |       |                                                                                                                                           |                 | <img width="100" alt="image" src="https://user-images.githubusercontent.com/11482921/225659792-07f3d5f4-3e26-4c52-988b-c4f228d6e45d.jpeg"> |    <img width="200" alt="image" src="https://user-images.githubusercontent.com/11482921/225660076-665b5889-3825-48cc-b9f9-06903fdd0c4b.jpg">     |
| <img width="200" alt="image" src="https://user-images.githubusercontent.com/11482921/225659269-2d50e40d-f79b-41bc-9a0e-9dc73663f010.png"> |       |                                                                                                                                           |                 | <img width="150" alt="image" src="https://user-images.githubusercontent.com/11482921/225660608-ca526f86-f506-4d0c-bdb8-75b95fbdbce0.png">  |    <img width="200" alt="image" src="https://user-images.githubusercontent.com/11482921/225660901-86bcbfd8-0643-4e17-a6ec-4a2305e5f0a5.png">     |
| <img width="200" alt="image" src="https://user-images.githubusercontent.com/11482921/225661058-656d87d7-3c8d-4216-820e-a02a8a5f5a4a.png"> |       | <img width="200" alt="image" src="https://user-images.githubusercontent.com/11482921/225661380-c9a01791-9b96-4b25-8878-87cdcf01a6f6.png"> |                 | <img width="250" alt="image" src="https://user-images.githubusercontent.com/11482921/225661180-98f338ee-950e-45d0-bd5f-4e8b7e82cecb.png">  |    <img width="200" alt="image" src="https://user-images.githubusercontent.com/11482921/225661273-82867799-b8f8-4fe5-9b12-cc99df85696d.png">     |
| <img width="200" alt="image" src="https://user-images.githubusercontent.com/11482921/225661058-656d87d7-3c8d-4216-820e-a02a8a5f5a4a.png"> |       | <img width="200" alt="image" src="https://user-images.githubusercontent.com/11482921/225661380-c9a01791-9b96-4b25-8878-87cdcf01a6f6.png"> |                 | <img width="250" alt="image" src="https://user-images.githubusercontent.com/11482921/225661755-cfa48f8d-712d-41a0-a1bf-4c1e90ca4d7a.png">  |    <img width="200" alt="image" src="https://user-images.githubusercontent.com/11482921/225661944-0f02ab3c-de8d-4898-a7b0-5ff55fa5f253.png">     |

**Comment by CCpt5** [comment]
Came to see if it was possible to use this new model - Thanks in advance for any work toward implementing it!

**Comment by bropines** [comment]
Looks like the author died a little -_-.

**Comment by setothegreat** [comment]
Any updates on this?

**Comment by AugmentedRealityCat** [comment]
Just to make sure I understand, is this considered implemented because the extension already allows us to mix and match multiple models together (and even mix T2i with ControlNet !) or is that a new feature ? 
And if it's a new feature, do we have to download the models from the link at the top of this thread ? Do we have to use the Fuser T2i model ?

**Comment by setothegreat** [comment]
> Just to make sure I understand, is this considered implemented because the extension already allows us to mix and match multiple models together (and even mix T2i with ControlNet !) or is that a new feature ? And if it's a new feature, do we have to download the models from the link at the top of this thread ? Do we have to use the Fuser T2i model ?

Not really sure. Author marked this as completed yesterday but I don't see any info in the ReadMe regarding it, nor any reference to the fuser model anywhere in the repo. I admittedly might've just missed it, but none of the commits from yesterday seem to add support for it either.

**Comment by ljleb** [comment]
most issues have been closed in bulk yesterday. this probably has been closed by mistake. Please close again if this as not planned if it is not something we intend to implement.

**Comment by FlowDownTheRiver** [comment]
This is something I am also waiting for. I hope it gets implemented.Looking pretty cool from the examles. Please devs,keep us updated about it.

**Comment by amir84ferdos** [comment]
Does anybody know how to use the Coadapter fuser?

**Comment by AugmentedRealityCat** [comment]
As far as I know it is not supported yet by this extension.

**Comment by leo27heady** [comment]
There're any news about this feature request?
