### ISSUE TITLE
[Bug]: Enhancementrequest: provide option in the controlnet interface to paste from clipboard

### ISSUE THREAD

**Issue by ChrisFab16** [Mikubill/sd-webui-controlnet#617]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Currently, if I am in the img2img tab and paste an image from the clipboard, it ends up in the img2img input box. If I need to paste it to the Controlnet input, I need to drag and drop it.

Adding a button in the controlnet section to paste from clipboard would make this much easier

### Steps to reproduce the problem

1. Go to img2img tab
2. Press ctrl-v
3. image ends up in img2img input box but cannot be pasted to controlnet

### What should have happened?

it should be possible to paste to controlnet input

### Commit where the problem happens

webui: 
controlnet: 

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
not applicable
```

**Comment by 2blackbar** [comment]
theres extension for that

**Comment by sbuldan** [comment]
> 

Which extension is that? I was able to paste into control net but I cannot now.
