### ISSUE TITLE
Feature Request: Add option to set controlnet prompt/negative prompt independently of stable diffusion prompt

### ISSUE THREAD

**Issue by 1lint** [Mikubill/sd-webui-controlnet#622]
Hi longtime user and fan of your extension! I wanted to request a feature for setting the controlnet prompt/negative prompt independently of the stable diffusion model. 

I trained a [controlnet](https://github.com/1lint/style_controlnet) for adding anime style, and used danbooru tags for the training prompts. Ideally the user would be able to pass danbooru style prompts to the anime controlnet, and use a separate set of prompts for the (non-anime) stable diffusion checkpoint. I have the weights (compatible with your extension) saved at my HF [repo](https://huggingface.co/lint/anime_controlnet) and a basic gradio UI at https://huggingface.co/spaces/lint/controlstyle_ui that allows setting controlnet prompt separately, but I have hard time navigating the A1111 UI layout to implement the same feature. 

![hint_grid](https://user-images.githubusercontent.com/105617163/225996355-3d15d2ab-5a0c-472b-8b82-149ffde1d962.png)
from left to right: controlnet weight 0.0, controlnet weight 0.5, controlnet weight 1.0, hint | prompt: 1girl, blue eyes, seed 2048

Being able to set the controlnet prompts separately would be really useful for using controlnets to control style, and I think it might also be a useful feature for the original controlnets as well (i.e. controlnet prompt would describe the hint image, while the stable diffusion prompt describes the overall image).

**Comment by mmi366127** [comment]
Hi, I also thought of this function a few days ago, and had modified the code to add separate prompt for each controlnet model. However, I find it difficult to control with only separate text prompt, or maybe I messed up implementing it. [here's my implementation](https://github.com/mmi366127/sd-webui-controlnet/tree/try-to-add-separate-prompt)

**Comment by ljleb** [comment]
This could be an interesting feature, we may want to implement it eventually. I think we should keep this open.

**Comment by ljleb** [comment]
@lllyasviel think this is a bad idea?
