### ISSUE TITLE
Feature Request: Add API Support

### ISSUE THREAD

**Issue by kft334** [Mikubill/sd-webui-controlnet#63]
Many people use the API instead of the webui. ControlNet is a significant development so API support should be considered. Thanks

**Comment by spinagon** [comment]
I agree, API access is necessary for bot development.

**Comment by killfrenzy96** [comment]
I would love this. I want to add ControlNet to my own bot too.

**Comment by Ryu1845** [comment]
Here's how it's done in the dreambooth extension if someone wants inspiration. https://github.com/d8ahazard/sd_dreambooth_extension/blob/main/scripts/api.py

**Comment by Mikubill** [comment]
Looks nice. PR welcome or will implement later if no one does

**Comment by devilismyfriend** [comment]
definitely need API integration soon, this extension is too good.

**Comment by chrisbward** [comment]
Super excited for this!
