### ISSUE TITLE
[Bug]: controlnet some setting only work with slider, not work when you enter numbers

### ISSUE THREAD

**Issue by jimys** [Mikubill/sd-webui-controlnet#632]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

these setting will not change if you enter numbers,
it only change when you use the slide
<img width="569" alt="E6C31B3B-2A07-45D4-AF6E-95FC61DB7273" src="https://user-images.githubusercontent.com/1137380/226152836-ee6cfa73-7ae3-49ae-ad9a-64c786e646d2.png">

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

enter numbers should work

### Commit where the problem happens

webui: 
controlnet: 

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
no
```

**Comment by ljleb** [comment]
I tested this and I can't reproduce the behavior you describe for any of the silders. Are you on the latest version of both the webui and controlnet? (which is dbdd6b1b027b8dd02c1f13310f82cf359c617dc6 at this moment)
