### ISSUE TITLE
Feature request: save/load clip_vision output

### ISSUE THREAD

**Issue by tkalayci71** [Mikubill/sd-webui-controlnet#633]
It would be nice if you could save clip_vision output like other preprocessor outputs, by somehow converting it to an image maybe. Thanks.

**Comment by tkalayci71** [comment]
update: reason for this request was partly because I wanted to be able to share the image embedding without exposing the original image. I'm using clip_vision+adapter_style to generate image variations via txt2img with empty prompt. Then I tried resizing the original image to 32x32 and amazingly it still works. Just from that thumbnail, clip_vision can generate 768x768 images with imagined details, so wanted to share this:

![32](https://user-images.githubusercontent.com/114084637/226896536-5b890df9-dc64-4458-98cf-0b5060cbe565.png)


![768](https://user-images.githubusercontent.com/114084637/226896566-bdc7ca26-e7c9-42da-945f-e2dbec60975e.jpg)


parameters
<lora:epiNoiseoffset_v2:1>
Negative prompt: cartoon
Steps: 8, Sampler: DPM++ SDE Karras, CFG scale: 5, Seed: 144529209, Size: 768x768, Model hash: 20bae33336, Model: realisticVisionV13_v13, ControlNet-0 Enabled: True, ControlNet-0 Module: clip_vision, ControlNet-0 Model: t2iadapter_style-fp16 [0e2e8330], ControlNet-0 Weight: 1, ControlNet-0 Guidance Start: 0, ControlNet-0 Guidance End: 1

**Comment by chrisgoringe** [comment]
Just created a pull request from https://github.com/chrisgoringe/sd-webui-controlnet/tree/req/633 that implements this - returns a completely fake image representing the output from the clip_vision preconditioner.

**Comment by tkalayci71** [comment]
> Just created a pull request from https://github.com/chrisgoringe/sd-webui-controlnet/tree/req/633 that implements this - returns a completely fake image representing the output from the clip_vision preconditioner.

Wow, this totally works, you rock! It's great, thank you so much!!

**Comment by chrisgoringe** [comment]
Good to hear it works for you :). Hopefully this gets merged into the main code.

**Comment by tkalayci71** [comment]
What can I do to support this PR? Should I close this issue or not?

Btw, funny, on a saved fake image, I draw a large black rectangle, destroying most of the data, and it still mostly works, which is crazy

**Comment by tkalayci71** [comment]
Thanks to you, I was able to come up with an extension for batch converting images and optional merging

https://github.com/tkalayci71/convert_clipvision

I hope I have given enough credits, let me know if you need anything changed
:)

**Comment by chrisgoringe** [comment]
Nice!

**Comment by chrisgoringe** [comment]
:)
