### ISSUE TITLE
Support Face Landmark Control

### ISSUE THREAD

**Issue by Ted-developer** [Mikubill/sd-webui-controlnet#636]
It's very useful Generate face with the identical poses and expression with [Face-Landmark-ControlNet](https://github.com/Georgefwt/Face-Landmark-ControlNet)

Is possible to support it ?  Thank you very much

**Comment by OedoSoldier** [comment]
I've made a PR #637

**Comment by lllyasviel** [comment]
Face landmarks will be officially supported by a official model of ControlNet V1.1 openpose-full model, trained with arbitary combinations of face, body, and hand landmarks. The annotator will be a pytorch version of openpose's full 3 models, written by ControlNet team. The community model and anotator might be very constructive but may be replace by official ones that will be released soon.

**Comment by toyxyz** [comment]
> Face landmarks will be officially supported by a official model of ControlNet V1.1 openpose-full model, trained with arbitary combinations of face, body, and hand landmarks. The annotator will be a pytorch version of openpose's full 3 models, written by ControlNet team. The community model and anotator might be very constructive but may be replace by official ones that will be released soon.

Oh that's really great news! I have been able to get nice results using the ControlNet face-landmark model. Looking forward to the new ControlNet V 1.1!
![image](https://user-images.githubusercontent.com/8006000/227256520-72901ed8-f5aa-4b7f-8fb5-3e8eff32a010.png)

**Comment by camenduru** [comment]
another news:
https://github.com/crucible-ai/ControlNet/blob/laion_dataset/README_laion_face.md
https://huggingface.co/CrucibleAI/ControlNetMediaPipeFace
