### ISSUE TITLE
Is it possible to disable the control net in Highres.fix process?

### ISSUE THREAD

**Issue by 105gun** [Mikubill/sd-webui-controlnet#64]
I try to use line art to generate colored anime pics. The low resolution output is pretty good, but also out of the origin lines. While in highres process, I believe the control net is trying to fix the picture with origin lines, which may make awful pattens. 

Here is an example:

Line art
![Line](https://user-images.githubusercontent.com/52597991/218993431-d6799160-0358-43e5-b455-405c90e2b705.jpg)
Low resolution output
![02124-3569111255-1girl,Kuniform,masterpiece,simple background,](https://user-images.githubusercontent.com/52597991/218993141-7e28c91c-b3a2-4a56-9c8c-99c5ce94d445.png)
Highres, just notice these strange red lines in the sky
![02125-3569111255-1girl,Kuniform,masterpiece,simple background,](https://user-images.githubusercontent.com/52597991/218993174-0affef54-1910-49a6-b64f-2472ff605937.png)
![02126-3569111255-1girl,Kuniform,masterpiece,simple background,](https://user-images.githubusercontent.com/52597991/218993207-86b6882c-a11a-4804-afe2-6644d7312aaf.png)

I think a button on the UI disabling control net in highres can help to fix this problem.

**Comment by Mikubill** [comment]
Related: #62

**Comment by 105gun** [comment]
I got a solution. My code is ugly, but I guess it's working.
![02191-3719080654-1girl,Kuniform,masterpiece,simple background,](https://user-images.githubusercontent.com/52597991/219038208-5d2a41c4-20e5-4dc6-ab99-3000e0aa784d.png)
![02190-3719080654-1girl,Kuniform,masterpiece,simple background,](https://user-images.githubusercontent.com/52597991/219038273-0362fe1d-4169-4307-9147-8bac3644b2d8.png)
Add a checkbox
![QQ截图20230215212431](https://user-images.githubusercontent.com/52597991/219039613-f1d34c10-b615-4243-bd92-80aa3bebda08.png)


My method need to modify 2 files, one is **./extensions/sd-webui-controlnet/scripts/controlnet.py**
And another, is **./modules/processing.py**

The first has been uploaded to my repo: [https://github.com/105gun/sd-webui-controlnet/blob/Highres-disable/scripts/controlnet.py](url)

While in processing.py, we just call disable_controlnet() in StableDiffusionProcessingTxt2Img/sample/save_intermediate(). This function will be called before Highres.fix.
`sys.path.append('./extensions/sd-webui-controlnet')`
`from scripts.controlnet import disable_controlnet`
![QQ截图20230215205227](https://user-images.githubusercontent.com/52597991/219041010-69aaf028-9656-483e-9dab-81b88fa33612.png)
` disable_controlnet()`
![QQ截图20230215205255](https://user-images.githubusercontent.com/52597991/219041197-b3b6a0df-db43-47ef-bfe9-64de05262694.png)

I don't know if there is any way to implement similar function without modifying processing.py.

**Comment by Mikubill** [comment]
Added a trick to improve quality when hires enabled. 
https://github.com/Mikubill/sd-webui-controlnet/blob/c2eff2c56fa46f5cbcaf827eeddbe1fd2dc65792/scripts/cldm.py#L73-L80
Image generated using your sketch:
| Completely Disabled | Only Mid-Control | Based |
|:-------------------------:|:-------------------------:|:-------------------------:|
|<img width="256" alt="" src="https://user-images.githubusercontent.com/31246794/219079945-aef9e320-1034-48be-aa2a-5fa0edff4898.png">  |  <img width="256" alt="" src="https://user-images.githubusercontent.com/31246794/219079978-5de37984-6608-48f9-9544-2691552d44fe.png"> | <img width="256" alt="" src="https://user-images.githubusercontent.com/31246794/219079987-5f48c587-b6f5-4807-aeb3-0e34840b66e2.png"> |

**Comment by younyokel** [comment]
When I'm using Hi-res and the Hi-res upscale value is not precisely 1,5, 2.0, I'm getting this: `RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 28 but got size 27 for tensor number 1 in the list.`

**Comment by Starlento** [comment]
> 

Same thing happening.

**Comment by Starlento** [comment]
> When I'm using Hi-res and the Hi-res upscale value is not precisely 1.5, 1.75, 2.0, etc... I'm getting this: `RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 28 but got size 27 for tensor number 1 in the list.`

Same thing happening.

**Comment by entmike** [comment]
I get a tensor size error any time I have ControlNet enabled and High-res fix on, even if it is exactly 1.5 etc.

**Comment by WARRIORPSIX** [comment]
Hi. This trick no longer works. Leads to an error. Is there a new solution?
