### ISSUE TITLE
Stable diffusion webui will be killed when I use controlnet 

### ISSUE THREAD

**Issue by hcv1027** [Mikubill/sd-webui-controlnet#668]
Basic information:
GPU: RTX 2070 8G
Driver: 531.29
OS: Ubuntu 22.04 run on wsl2

Problem description:
As the attached screenshot shows, every time I try to use ControlNet, the web UI is killed after I press the "generate" button. The log only shows the following error message:
```bash
Loading model: control_sd15_openpose [fef5e48e]
Loaded state_dict from [/workspace/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_sd15_openpose.pth]
Killed
```
However, if I drag an image and click on the "Preview annotator result" button, ControlNet successfully detects the human pose. I have tried reinstalling the application multiple times, but it does not work, and I have no idea what the exact issue is. I hope someone can help me fix this problem. Thank you.

![螢幕擷取畫面 (72)](https://user-images.githubusercontent.com/12728923/227964032-d4773267-5ddb-4f45-9b2c-3f246f2aca59.png)

**Comment by ClashSAN** [comment]
```
# Turn swap off
# This moves stuff in swap to the main memory and might take several minutes
sudo swapoff -a

# Create an empty swapfile
# Note that "1G" is basically just the unit and count is an integer.
# Together, they define the size. In this case 8GB.
sudo dd if=/dev/zero of=/swapfile bs=1G count=8

# Set the correct permissions
sudo chmod 0600 /swapfile

sudo mkswap /swapfile  # Set up a Linux swap area
sudo swapon /swapfile  # Turn the swap on
```
