### ISSUE TITLE
API endpoints for modules parameters

### ISSUE THREAD

**Issue by olegchomp** [Mikubill/sd-webui-controlnet#690]
It will be greate to have endpoint for parameter like in gradio.

`label="Annotator Resolution", minimum=64, maximum=2048, value=512, step=1, interactive=True`

**Comment by ljleb** [comment]
To make sure I understand your request, are you referring to creating an endpoint to discover which thresholds (none, a, or a and b) are available for a given annotator?

**Comment by olegchomp** [comment]
> To make sure I understand your request, are you referring to creating an endpoint to discover which thresholds (none, a, or a and b) are available for a given annotator?

Yes! I'm making own UI and it will be very cool to just request parameters with labels and values. Here is example on my side, copied from gradio, but it hard to allways keep up to date and look for git update.
```
update(inpar=r, label="Annotator resolution", value=512, minimum=64, maximum=2048, step=1, interactive=True)
update(inpar=a, label="Canny low threshold", minimum=1, maximum=255, value=100, step=1, interactive=True)
update(inpar=b, label="Canny high threshold", minimum=1, maximum=255, value=200, step=1, interactive=True)
```
