### ISSUE TITLE
ControlNet collapsible settings panel in Deforum doesn't always show setting when "Enable" check box is checked.

### ISSUE THREAD

**Issue by Vendaciousness** [Mikubill/sd-webui-controlnet#692]
Apologies if this should be submitted to Automatic1111 or Deforum devs, since it involves both also, but the error occurs in the ControlNet portion of the UI.

The ControlNet tab inside the Deforum extension in Automatic1111 contains a check box called "Enable" to enable/disable the extension and all of the settings specific to CN are displayed, only when this check box is checked.

However, checking the box sometimes has no effect, like here:
![image](https://user-images.githubusercontent.com/127359965/229271572-bccdc200-38d5-41a7-9912-b1533af1e1bf.png)

Or it only shows a few of the component rows, like here:  
![image](https://user-images.githubusercontent.com/127359965/229271604-7bf28f96-0a6b-4454-be90-44630cc00d77.png)

Other times, it displays all but the bottommost component ("controlnet_input_video_mask_chosen_file").

Other times, unchecking the box does not cause the components to disappear, like here:
![image](https://user-images.githubusercontent.com/127359965/229271713-5bb3d70f-4ea7-4682-93ce-acd97ee4cd3d.png)

The specific component involved is div id="component-8825".

Sometimes, I need to check and un-check the "Enable" box 20-30 times, before I can see all the settings. Other times, it works fine the first time.

I'm running Google Chrome Version 110.0.5481.178 (Official Build) (64-bit)

Sorry if I'm leaving anything important out; this is my first bug report.

**Comment by hithereai** [comment]
I believe this issue can be closed.

**Comment by Vendaciousness** [comment]
Not really. I made this yesterday.
https://youtu.be/dV8oilz7XcU

**Comment by hithereai** [comment]
This is gradio bugs, honestly. You can close your issue in here anyway.

**Comment by Vendaciousness** [comment]
>This is gradio bugs, honestly. You can close your issue in here anyway.
I don't know why you're blaming gradio for a bug on your custom-made ControlNet page, but whatever.

https://youtu.be/LaYiORzFprs
