### ISSUE TITLE
Big anomaly on ControleNet

### ISSUE THREAD

**Issue by XT-404** [Mikubill/sd-webui-controlnet#695]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I install only control via WebUI interface:
webui reboot:
controlenet appears from reboot:
installing a module in controlnet : 
basic configuration of controlenet
verification in setting of the controlnet configuration:
generation launch
knockout generation
this is what happens all the time as soon as I activate controle net
I can uninstall and reinstall it as many times as I want, it stays that way
on the other hand if controle net is not installed or activated 0 problem
![image](https://user-images.githubusercontent.com/128090530/229299697-031d5138-97ab-45ac-aacd-3fada8063d6a.png)
![image](https://user-images.githubusercontent.com/128090530/229299705-296c36dd-6315-43e7-88b9-f1f0b1778e16.png)
![image](https://user-images.githubusercontent.com/128090530/229299709-3b59c045-39d8-4ee3-b7dc-8d2573dfdb97.png)
![image](https://user-images.githubusercontent.com/128090530/229299715-51fa53c2-48d3-43de-90d0-3fbf03d31914.png)
![image](https://user-images.githubusercontent.com/128090530/229299719-b7caa924-5684-4164-9d6b-c09bb33c9de1.png)
the anomaly and presents in all forms of control_SD15/16 or other

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...
4

### What should have happened?

.

### Commit where the problem happens

webui: 
controlnet: 

### What browsers do you use to access the UI ?

Brave

### Command Line Arguments

```Shell
.
```

### Console logs

```Shell
.
```

### Additional information

.

**Comment by ostap667inbox** [comment]
Hmm. Try to use the correct model for the task. In this case, 'openpose' instead of 'normal'.

**Comment by XT-404** [comment]
I will test and I will come back to you to announce the return

**Comment by XT-404** [comment]
![image](https://user-images.githubusercontent.com/128090530/229323463-34539619-a57f-4eb1-b434-ac262a50116c.png)

I have this error that comes out now if I use control net once there is no error if I run it a second time it gives me this error in a loop.

**Comment by ostap667inbox** [comment]
You must specify the correct configuration files for each model you are currently using in the settings. ControlNet models have their own configuration files, and t2i Adapter models have their own configuration files. 
In the current form of the extension there is no way to switch configuration files on the fly, you do it manually.
You can read which file corresponds to which model in the ControlNet manual: https://github.com/Mikubill/sd-webui-controlnet
![cn-settings](https://user-images.githubusercontent.com/123593542/229324205-cc0c47f2-5f1a-44ac-80ab-d1dd493e3a38.png)

**Comment by ostap667inbox** [comment]
Also, the ControlNet models must match the version of the Stable Diffusion model that is currently in use. A version mismatch will also cause an error. There are special models for SD2.1.
