### ISSUE TITLE
[FEATURE REQUEST] - Batch reference inputs for controlnet

### ISSUE THREAD

**Issue by Smackdab69** [Mikubill/sd-webui-controlnet#703]
For the input image for controlnet, is it possible to allow for batches?  For example, if you wish to iterate through multiple source images containing poses, it'd be very helpful.

Right now, I must manually change the input image when I wish to change poses.

**Comment by Ericxgao** [comment]
Seconded.

**Comment by tkalayci71** [comment]
this is already possible, unless I misunderstood

in img2img tab, if you don't provide an input image for ControlNet, it will use the initial image instead. In this case you might also want to check the setting 'Skip img2img processing when using img2img initial image' (or if you don't, black background in openpose images will act as noise offset). This method works in batch mode too and with other scripts.

**Comment by ljleb** [comment]
This works if you have a directlory of images to process, but not if you have a directory of pre-processed openpose images. #683 closes this.

**Comment by ljleb** [comment]
Ah you are right, my bad. I'll wait for OP to let us know if the "multiple source images containing poses" also contain other types of images and controlmaps, otherwise we can close this I think.

**Comment by Smackdab69** [comment]
> 

Ah, I see!  I was focused on using the txt2img tab.  But, it is nice to see a new feature is being released for this in https://github.com/Mikubill/sd-webui-controlnet/pull/683, since it allows us to do hi-res and face restoration in txt2img.
