### ISSUE TITLE
[Bug]: Why using the same configuration, the effect is not as good as the controlnet original repo? and the generated result looks black

### ISSUE THREAD

**Issue by jaycecd** [Mikubill/sd-webui-controlnet#707]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I use the same configuration in webui and original controlnet repo, but the generated result looks worse:
![image](https://user-images.githubusercontent.com/33342388/229484524-a55c859a-adaf-475b-b53e-3be827bb6ebd.png)
original controlnet repo,looks very good
![image](https://user-images.githubusercontent.com/33342388/229485355-00c3e297-e7c5-40dc-a439-8b039423160a.png)
The result is also generated, there is no problem with the structure, but the color is not coordinated, it seems that the black is too heavy, especially the black lines seem to be thickened

So, what happened?

### Steps to reproduce the problem

The following is my operating system information, the prompt used and the corresponding configuration:

1. OS: Windows 10
2. Browsers:Chrome
3. GPU:RTX 4090
4. Prompt: a fantastic living room made of wood,best quality, extremely detailed
5. Negative prompt: longbody, lowres, bad anatomy, bad hands, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, text, legend
6. Steps: 20
7. Sampler: DDIM
8. CFG scale: 9
9. Seed: 54568563
10. Size: 512x512
11. Model hash: cc6cb27103
12. Model: v1-5-pruned-emaonly
13. ENSD: 31337
14. ControlNet-0 Enabled: True
15. ControlNet-0 Module: mlsd
16. ControlNet-0 Model: control_sd15_mlsd [fef5e48e]
17. ControlNet-0 Weight: 1
18. ControlNet-0 Guidance Start: 0
19.  ControlNet-0 Guidance End: 1

Others are the default configuration, then click txt2img

### What should have happened?

The results should be the same or very similar

### Commit where the problem happens

webui: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2
controlnet: 16ea3b5379c1e78a4bc8e3fc9cae8d65c42511b1
sd-webui-controlnet:6e339e9b578019576155e7902c660fb88acdcb36

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
set COMMANDLINE_ARGS=--autolaunch --deepdanbooru --xformers --enable-console-prompts --api --api-log
```

### Console logs

```Shell
{"prompt": "a fantastic living room made of wood,best quality, extremely detailed", "all_prompts": ["a fantastic living room made of wood,best quality, extremely detailed", "a fantastic living room made of wood,best quality, extremely detailed", "a fantastic living room made of wood,best quality, extremely detailed", "a fantastic living room made of wood,best quality, extremely detailed"], "negative_prompt": "longbody, lowres, bad anatomy, bad hands, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, text, legend", "all_negative_prompts": ["longbody, lowres, bad anatomy, bad hands, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, text, legend", "longbody, lowres, bad anatomy, bad hands, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, text, legend", "longbody, lowres, bad anatomy, bad hands, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, text, legend", "longbody, lowres, bad anatomy, bad hands, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, text, legend"], "seed": 54568563, "all_seeds": [54568563, 54568564, 54568565, 54568566], "subseed": 4195957760, "all_subseeds": [4195957760, 4195957761, 4195957762, 4195957763], "subseed_strength": 0, "width": 512, "height": 512, "sampler_name": "DDIM", "cfg_scale": 9, "steps": 20, "batch_size": 2, "restore_faces": false, "face_restoration_model": null, "sd_model_hash": "cc6cb27103", "seed_resize_from_w": 0, "seed_resize_from_h": 0, "denoising_strength": null, "extra_generation_params": {"ControlNet-0 Enabled": true, "ControlNet-0 Module": "mlsd", "ControlNet-0 Model": "control_sd15_mlsd [fef5e48e]", "ControlNet-0 Weight": 1, "ControlNet-0 Guidance Start": 0, "ControlNet-0 Guidance End": 1}, "index_of_first_image": 1, "infotexts": ["a fantastic living room made of wood,best quality, extremely detailed\nNegative prompt: longbody, lowres, bad anatomy, bad hands, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, text, legend\nSteps: 20, Sampler: DDIM, CFG scale: 9, Seed: 54568563, Size: 512x512, Model hash: cc6cb27103, Model: v1-5-pruned-emaonly, ENSD: 31337, ControlNet-0 Enabled: True, ControlNet-0 Module: mlsd, ControlNet-0 Model: control_sd15_mlsd [fef5e48e], ControlNet-0 Weight: 1, ControlNet-0 Guidance Start: 0, ControlNet-0 Guidance End: 1", "a fantastic living room made of wood,best quality, extremely detailed\nNegative prompt: longbody, lowres, bad anatomy, bad hands, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, text, legend\nSteps: 20, Sampler: DDIM, CFG scale: 9, Seed: 54568563, Size: 512x512, Model hash: cc6cb27103, Model: v1-5-pruned-emaonly, ENSD: 31337, ControlNet-0 Enabled: True, ControlNet-0 Module: mlsd, ControlNet-0 Model: control_sd15_mlsd [fef5e48e], ControlNet-0 Weight: 1, ControlNet-0 Guidance Start: 0, ControlNet-0 Guidance End: 1", "a fantastic living room made of wood,best quality, extremely detailed\nNegative prompt: longbody, lowres, bad anatomy, bad hands, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, text, legend\nSteps: 20, Sampler: DDIM, CFG scale: 9, Seed: 54568564, Size: 512x512, Model hash: cc6cb27103, Model: v1-5-pruned-emaonly, ENSD: 31337, ControlNet-0 Enabled: True, ControlNet-0 Module: mlsd, ControlNet-0 Model: control_sd15_mlsd [fef5e48e], ControlNet-0 Weight: 1, ControlNet-0 Guidance Start: 0, ControlNet-0 Guidance End: 1", "a fantastic living room made of wood,best quality, extremely detailed\nNegative prompt: longbody, lowres, bad anatomy, bad hands, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, text, legend\nSteps: 20, Sampler: DDIM, CFG scale: 9, Seed: 54568565, Size: 512x512, Model hash: cc6cb27103, Model: v1-5-pruned-emaonly, ENSD: 31337, ControlNet-0 Enabled: True, ControlNet-0 Module: mlsd, ControlNet-0 Model: control_sd15_mlsd [fef5e48e], ControlNet-0 Weight: 1, ControlNet-0 Guidance Start: 0, ControlNet-0 Guidance End: 1", "a fantastic living room made of wood,best quality, extremely detailed\nNegative prompt: longbody, lowres, bad anatomy, bad hands, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, text, legend\nSteps: 20, Sampler: DDIM, CFG scale: 9, Seed: 54568566, Size: 512x512, Model hash: cc6cb27103, Model: v1-5-pruned-emaonly, ENSD: 31337, ControlNet-0 Enabled: True, ControlNet-0 Module: mlsd, ControlNet-0 Model: control_sd15_mlsd [fef5e48e], ControlNet-0 Weight: 1, ControlNet-0 Guidance Start: 0, ControlNet-0 Guidance End: 1"], "styles": [], "job_timestamp": "20230403185204", "clip_skip": 1, "is_using_inpainting_conditioning": false}
```

**Comment by jaycecd** [comment]
> can you share the input image and your random seed?

Of course, here is my input image as well as the random seed:
![room](https://user-images.githubusercontent.com/33342388/229503630-e8215f64-0385-4b26-82e1-28fbbf8bccf3.png)
seed:54568563

Note: the seed are fixed whether in WebUI or the original controlnet repo

Thanks again for your quick reply!

**Comment by jaycecd** [comment]
Not only this input image, but also other images have a similar situation, it looks like the quality of the image is very poor. I used the same prompts without controlnet in webui and it looked fine:
![image](https://user-images.githubusercontent.com/33342388/229506890-30192bf6-e053-419a-8cd4-037f246a8b67.png)

but when SD1.5 and controlnet worked together, the problem happened.

Disable controlnet and use only sd1.5 to generate images：
![00244-54568564](https://user-images.githubusercontent.com/33342388/229508666-473b55fe-de6f-49b4-9e49-d4f0220ec922.png)

![00245-54568565](https://user-images.githubusercontent.com/33342388/229508692-021d117a-31b1-4f18-bbbb-b295e7e40a1e.png)

controlnet + sd1.5：
![00252-54568564](https://user-images.githubusercontent.com/33342388/229507675-376c6375-dcf5-43ab-b919-0cad9480b841.png)
![00254-54568566](https://user-images.githubusercontent.com/33342388/229507700-26d18b8a-bd57-483a-8a68-d0ae4585b403.png)

The prompt is the same as above：

> Prompt: a fantastic living room made of wood,best quality, extremely detailed
> Negative prompt: longbody, lowres, bad anatomy, bad hands, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, text, legend

**Comment by jaycecd** [comment]
@lllyasviel 
Problem solved! The main reason was that I had "Enable CFG-based guidance" checked in the settings, which caused me to use guess mode by default.

When I unchecked "Enable CFG-based guidance" and then checked "Guess mode", the problem appeared again!

So, the problem is caused by the guess mode, and the above problem occurs whenever at least one of "Enable CFG-based guidance" and "Guess mode" is checked.
So, is this a bug?

**Comment by lllyasviel** [comment]
no. Enable CFG-based guidance is not Guess mode. I do not know much about CFG-based guidance mode. but for Guess mode you need to use cfg scale at about 4

**Comment by jaycecd** [comment]
Okay, thank you for your advice
