### ISSUE TITLE
Output of normal map is RGB, but input is BGR

### ISSUE THREAD

**Issue by toshiaki1729** [Mikubill/sd-webui-controlnet#71]
Thank you so much for this brilliant extension!  

I was using blender to create normal map:
<details><summary>Like this (click to show)</summary>
<img src="https://user-images.githubusercontent.com/116595002/219080102-7f973285-a85a-463c-9689-25d5cd6b5688.png" title="RGB normal map from blender"/>
</details>

When I used this RGB normal map as input of this extension, collapsed image was generated:
<details><summary>Like this (click to show)</summary>
<img src="https://user-images.githubusercontent.com/116595002/219076565-860206a5-b3f8-45fd-80fe-92dc0a2ad293.png" title="image generated with RGB normal map"/>
</details>

Changing the order of channels to BGR solved the problem:
<details><summary>Like this (click to show)</summary>
<img src="https://user-images.githubusercontent.com/116595002/219079996-46d4a0cc-5cb2-4c76-8c6a-a60aa0b8512d.png" title="BGR normal map from blender"/>
<img src="https://user-images.githubusercontent.com/116595002/219079410-05fcc61a-d909-4df7-b8b4-ccf055d1e035.png" title="image generated with BGR normal map"/>
</details>

Since the output of the normal_map preprocessor visible in the gallery is RGB, I think this behavior is a little bit confusing.

**Comment by Mikubill** [comment]
Fixed in https://github.com/Mikubill/sd-webui-controlnet/commit/1d2cb96c3b9a1298cee322b82235d0752a2dba70, should works now.

**Comment by toshiaki1729** [comment]
It seems not working with custom RGB normal map:
![result after](https://user-images.githubusercontent.com/116595002/219092286-86fc10ee-e594-402b-9d54-59d50c7c760d.png)

I think this may difficult problem since swapping operation `detected_map[:, :, ::-1]` is needed when `module == "none"` and user is choosing normal map model (this may not detectable).
Adding checkbox to change order from RGB to BGR may be needed like `Scribble Mode (Reverse color)`, I think.

**Comment by Mikubill** [comment]
Added. How about this commit?

**Comment by toshiaki1729** [comment]
It is working greatly!
Thank you so much for your prompt response.

![great result](https://user-images.githubusercontent.com/116595002/219099352-7f8b72d1-9c51-4016-9c42-2eb18284d52a.png)
