### ISSUE TITLE
[Feature Request]: Add folder input for random selection of pose 

### ISSUE THREAD

**Issue by Jonseed** [Mikubill/sd-webui-controlnet#710]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

It would be great if there was an option to instead of an image from the UI to have it pull a random image from a folder for the image input, and if it pulled a new random image for each generation in a batch. That way you could have it generate a random pose, for instance, for every generation, from a folder filled with pose images.

### Steps to reproduce the problem

1. Add a field for inputting a path to a folder for random selection of image input

### What should have happened?

.

### Commit where the problem happens

.

### Command Line Arguments

```Shell
.
```

### Console logs

```Shell
.
```

**Comment by ik1ng** [comment]
Looking for this as well!
