### ISSUE TITLE
[Bug]: Masking Not Working with API

### ISSUE THREAD

**Issue by brennanerbz** [Mikubill/sd-webui-controlnet#713]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Uploading a mask works with the UI, however it does not work with the API. The last step of painting the mask over the original image fails. It paints the entire generated image into the masked area. The settings for the UI and the API call are the exact same. 

Original Image:
![IMG_2643](https://user-images.githubusercontent.com/9124902/230333199-e06bb4a2-09fd-4c78-a0c3-6eade86277f0.JPG)

1111 UI Image with Mask:
![00030-1109714606](https://user-images.githubusercontent.com/9124902/230333312-625893a2-ad06-4557-b3fc-bd5cb35825b2.png)

API Image with Mask:
![0OqB15WMArg0MwfjzN6A](https://user-images.githubusercontent.com/9124902/230333357-e79ae6c1-9ad0-4ef6-98db-5cac91f09737.png)

The Mask:
![0Oq6h0YN4JwdMSvW3c_p](https://user-images.githubusercontent.com/9124902/230333399-67a9cc47-d4ae-4f4f-baa1-1b497ff8b7cc.png)

### Steps to reproduce the problem

Here is the API call

` width: 776,
  height: 512,
  sampler_index: 'Euler a',
  steps: 80,
  cfg_scale: 6,
  seed: -1,
  batch_size: 1,
  restore_faces: false,
  denoising_strength: 0.8,
  resize_mode: 0,
  inpainting_fill: 0,
  inpaint_full_res: true,
  inpaint_full_res_padding: 32,
  inpainting_mask_invert: 1,
  mask_blur: 20,
  mask_mode: 1,
  controlnet_guidance: 1,
  controlnet_model: 'control_mlsd-fp16 [e3705cfa]',
  controlnet_module: 'mlsd',
  controlnet_weight: 0.7,
  controlnet_processor_res: 512,
  controlnet_threshold_a: 0.1,
  controlnet_threshold_b: 0.1,
  controlnet_resize_mode: 'Just Resize',
  controlnet_lowvram: false,
  controlnet_guessmode: false
`

### What should have happened?

The API and the UI should produce the same results.

### Commit where the problem happens

idk?

### Command Line Arguments

```Shell
--
```

### Console logs

```Shell
--
```

**Comment by brennanerbz** [comment]
@ljleb any ideas on how to fix this?

**Comment by ljleb** [comment]
Which api route are you using? It looks like you are using the deprecated route which I am not sure is still working with the latest version of the webui and controlnet.

**Comment by brennanerbz** [comment]
@ljleb tested both routes with new API config and object like `data.alwayson_scripts = {
                controlnet: {
                  args: [
                    {
                      guidance_start: data.controlnet_guidance,
                      guidance_end: data.controlnet_guidance,
                      model: data.controlnet_model,
                      module: data.controlnet_module,
                      weight: data.controlnet_weight,
                      processor_res: data.controlnet_processor_res,
                      threshold_a: data.controlnet_threshold_a,
                      threshold_b: data.controlnet_threshold_b,
                      resize_mode: data.controlnet_resize_mode,
                      lowvram: data.controlnet_lowvram,
                      guessmode: data.controlnet_guessmode,
                    },
                  ],
                },
              };`

**Comment by brennanerbz** [comment]
@ljleb are you able to upload a mask to the API? If so, can you send your settings config from your API call?

**Comment by brennanerbz** [comment]
@ljleb any update here?

**Comment by ljleb** [comment]
@brennanerbz can you verify that this has been fixed with the new update? It is possible that the type of image you pass as mask matters.
