### ISSUE TITLE
controlnetInst allation failed

### ISSUE THREAD

**Issue by yuren6** [Mikubill/sd-webui-controlnet#725]
Eject during installation GitCommandError: Cmd('git') failed due to: exit code(128) cmdline: git clone -v -- https://github.com/mikubill/sd-webui-controlnet E:\ai绘画\sd绘画\novelai-webui-aki-v3\tmp\sd-webui-controlnet stderr: 'fatal: destination path 'E:\ai绘画\sd绘画\novelai-webui-aki-v3\tmp\sd-webui-controlnet' already exists and is not an empty directory. ' don't quite understand

**Comment by EmperorOzy** [comment]
I'm getting this same error, but my extensions folder has nothing in it but "put extensions here.txt"

The tmp folder has the sd-webui-controlnet folder with nothing but the .git folder inside it.
