### ISSUE TITLE
[Feature Request] Control model offsets and some others

### ISSUE THREAD

**Issue by lllyasviel** [Mikubill/sd-webui-controlnet#73]
Hi great plugin. I played with it a bit and the memory optimization is really good. Some considerations should be put with higher priority:

1. The requirements for some mode like the segmentation is broken.

3. We really need a button to offset the weight inside the controlnet: that will immediately solve the distorted faces in pose mode and distorted edges in canny mode. This can be done by offsetting the weight copy inside the controlnet with user models and sd15. Right now all controls are targeted to SD15. These should be retargeted to user models.

**Comment by lllyasviel** [comment]
or at least we should put some control_any3_X.pth files for anime models. I cannot release these officially because of many considerations. But this can be done by 3rd projects.

**Comment by lllyasviel** [comment]
the formulation is 

    Any3.control_model.weights = SD15.control_model.weights + Any3.model.diffusion_model.weights - SD15.model.diffusion_model.weights

**Comment by lllyasviel** [comment]
or we can directly store 

SD15.control_model.weights - SD15.model.diffusion_model.weights

and any time user load the model, it add the base weight from user model

**Comment by lllyasviel** [comment]
Updated https://github.com/lllyasviel/ControlNet/discussions/12

**Comment by lllyasviel** [comment]
This should be considered early since it seems that this plugin is super popular in both english and asian community. so the early this is fixed, the less things we will need to ask people to try download new files.

**Comment by Mikubill** [comment]
Thanks for pointing out. Will implement some fix immediately

**Comment by Mikubill** [comment]
Fixed in https://github.com/Mikubill/sd-webui-controlnet/commit/b9efb602e5c6851e86d72d302e9592ddc0230d53, should work but still need some tests.

**Comment by lllyasviel** [comment]
seems broken, not working anymore

**Comment by lllyasviel** [comment]
Great. Now working. But how is the current offset computed? I do not even have sd15 in my webui.

**Comment by lllyasviel** [comment]
non-transfer results looks even better? perhaps because any3 is bad at drawing house

**Comment by lllyasviel** [comment]
by the way, what is the best practice to develop webui extension? open private github repo? directly write code in webui folder?

**Comment by Mikubill** [comment]
Hmm, looks like transferring control brings some instability. Temporary disabled and could be re-enable in the settings.

**Comment by brunogcar** [comment]
> by the way, what is the best practice to develop webui extension? open private github repo? directly write code in webui folder?

https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Developing-extensions

https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Extensions

**Comment by lllyasviel** [comment]
I am working on these. But I have also found that in some cases, non-transfered models even have better performance. Very weird. I'm trying to understand. We still know too little about neural networks.

**Comment by Mikubill** [comment]
> I can make a pull request, and I also think you can easily copy the codes from there. Please feel free to modify it.

Feel free to make a PR. Add some extra check I think both methods could work together.

**Comment by Mikubill** [comment]
Merged. This method seems to be more correctly and effective. 
btw, any samples?

**Comment by lllyasviel** [comment]
perhaps those anime models are trained too much in anime domain and forgets many general object context concepts, and controlnet without transferring accidentally brought those general concepts back.

**Comment by ljleb** [comment]
Should the code be tweaked to accept difference models instead of full checkpoints? Would save some disk space for some people, lighter to move around/download etc.

I'm just not sure how to distinguish diff models vs complete checkpoints programatically.

**Comment by Mikubill** [comment]
Difference models should be loaded without any issues. Feel free to open new issue if not works

**Comment by CCRcmcpe** [comment]
IMO, doing a weights merge will not save the bad generation quality, possibly will perform even worse. This is like saying `human + w * (human - ape) = more intelligent human`. Train a proper model based on any3 (etc.) is the way to go.

**Comment by Sansui233** [comment]
Thanks for your great work! 
I tested my sketch on pre-made extracted canny models with Anything-v3-fp16. Weird that the non-diff models always works much better on details and more like "Anything's style". I don't understand much about that, just post the show case for feedback.

Original sketch: 
![IMG_1784](https://user-images.githubusercontent.com/27474981/220116238-f20313f3-cfc5-43eb-9ded-c71f309addb7.PNG)

ControlNet:
![xyz_grid-0000-577891555-masterpiece, best quality, illustration,face, right hand, atomespheric, cold, sunshine, sky,, high detail, flowers and leafs](https://user-images.githubusercontent.com/27474981/220116305-e389d7d0-5d99-486c-8ffb-98a412798d22.png)

**Comment by plcpinho** [comment]
Hello @Mikubill, @lllyasviel or @kohya-ss. Could you pls clarify me one thing? In this project are you replacing ControlNet base model with the user model (e.g. AnythingV3), or are you doing some other operation? I don't understand how Transfer Control happens "on the fly" without the need to generate a new merged model (e.g. `AnythingV3ControlCanny.pth`).

Could you please explain how this works and if it is possible, through the extension, to save the merged model? Thanks!

**Comment by haofanwang** [comment]
@plcpinho Check my reply [here](https://github.com/haofanwang/ControlNet-for-Diffusers/issues/10#issuecomment-1445014696). **on the fly** never means it doesn't merging, it merges in time once the model updated without saving the merged model locally.

**Comment by tavihalperin** [comment]
@haofanwang 
Thanks for the clarifications on this!
So the the A1111 "on the fly" should match the output of the "statically merged" model right?
why do the results look better in this approach?
