### ISSUE TITLE
[Bug]: With API: When you put 2 canny controlnets in alwayson_scripts, it gives an error "ValueError: controlnet is enabled but no input image is given" and none of the controlnets are run. If you put one controlnet, then it works fine.

### ISSUE THREAD

**Issue by vandanchopra** [Mikubill/sd-webui-controlnet#732]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

1 controlnet works, but two don't: When 2 controlnets are run with the API, both don't run.

ERROR below:
Loading preprocessor: canny                                                                           
Loading model from cache: control_sd15_canny [fef5e48e]                                               
Error running process: /home/vandan_pc/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/c
ontrolnet.py                                                                                          
Traceback (most recent call last):                                                                    
  File "/home/vandan_pc/stable-diffusion-webui/modules/scripts.py", line 417, in process              
    script.process(p, *script_args)                                                                   
  File "/home/vandan_pc/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", 
line 706, in process                                                                                  
    raise ValueError('controlnet is enabled but no input image is given')                             
ValueError: controlnet is enabled but no input image is given   

### Steps to reproduce the problem

1. API usage

The args being passed in to: 'http://localhost:7860/sdapi/v1/txt2img'

txt2_img_args = {
    'prompt':'clouds with a blue sky in the background', 
                 'steps': 10,
                "alwayson_scripts": {
    "ControlNet": {
      "args": [{
          "input_image": [product_mask],
            "module": "canny",
          "model": "control_sd15_canny [fef5e48e]",
            "weight": 2,
             "processor_res": 512,
      "threshold_a": 20,
      "threshold_b": 50,
        },
          {"input_image": [product_image],
            "module": "canny",
          "model": "control_sd15_canny [fef5e48e]",
            "weight": 0.5,
             "processor_res": 512,
      "threshold_a": 20,
      "threshold_b": 50,
          }     
          
              ]
    }
    }}

### What should have happened?

Both controlnets should've worked.

### Commit where the problem happens

webui: latest
controlnet: latest

### Command Line Arguments

```Shell
--api
```

### Console logs

```Shell
Loading preprocessor: canny                                                                           
Loading model from cache: control_sd15_canny [fef5e48e]                                               
Error running process: /home/vandan_pc/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/c
ontrolnet.py                                                                                          
Traceback (most recent call last):                                                                    
  File "/home/vandan_pc/stable-diffusion-webui/modules/scripts.py", line 417, in process              
    script.process(p, *script_args)                                                                   
  File "/home/vandan_pc/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", 
line 706, in process                                                                                  
    raise ValueError('controlnet is enabled but no input image is given')                             
ValueError: controlnet is enabled but no input image is given
```

**Comment by vandanchopra** [comment]
PS. I'd love to answer any questions, I'm constantly checking in here for updates.

**Comment by ljleb** [comment]
Could you try removing the brackets around `[product_mask]`? Putting an array has a special meaning, it's the old way of specifying multiple control units.

**Comment by vandanchopra** [comment]
Sorry. Solved the issue at my end. I was passing the controlnet image in a list.
