### ISSUE TITLE
I managed to make it work Locally but not on Collab?

### ISSUE THREAD

**Issue by AxelFar94** [Mikubill/sd-webui-controlnet#75]
On Collab it stuck on 
`Loading preprocessor: scribble, model: control_sd15_scribble [fef5e48e]`
while locally it passes and goes to `Loaded state_dict from [C:\Users\...`
Any ideas on how to fix it?

**Comment by Hetaneko** [comment]
Did you check the RAM usage? I had the same problem and fixed it by using ControlNet extracted model.
Here is the models that I have used

https://huggingface.co/webui/ControlNet-modules-safetensors/tree/main

**Comment by AxelFar94** [comment]
@Hetaneko Using the extracted models from the link worked, must've been a RAM problem as you suggested, thank you very much!
