### ISSUE TITLE
Pasting control image directly from clipboard on img2img tab (is it possible?)

### ISSUE THREAD

**Issue by aleksusklim** [Mikubill/sd-webui-controlnet#76]
I'm not sure is this intended behavior, but it seems that currently it is impossible to paste images with Ctrl+V to arbitrary Gradio image inputs, including yours.

This could be fixed globally with a "paste"-event hook like this one:  
https://github.com/klimaleksus/stable-diffusion-webui-fix-image-paste 

But, WebUI already have a hook for paste, and it is doing some work in [dragdrop.js](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/3715ece0adce7bf7c5e9c5ab3710b2fdc3848f39/javascript/dragdrop.js#L77)

Mine version tries to paste relative to mouse, but requires to press Ctrl+V twice if the pointer is not directly over an image field.  
Should I make a PR to WebUI instead, to fix their handler so it will work correctly with extension like yours?

Posting here because I assume you will have an Issue for this problem sooner or later anyway; so you could point people to my solution for now. (My extension is purely in JS, just installs the handler which passes event to the correct input).

**Comment by ClashSAN** [comment]
I haven't seen this issue on Brave or firefox, from the txt2img tab, ctrl+v from anywhere here, using just this extension.

from the img2img tab, paste won't work.

**Comment by aleksusklim** [comment]
> from the img2img tab, paste won't work.

I believe WebUI is pasting to the first image input available on current tab.

If it can be changed so that it prefers the input under the pointer (reverting to default if none), the problem would be fixed.

My extension doesn't search specifically for Gradio components (my script was rather generic), but checking for exact classes up in DOM tree will solve inability to paste when the cursor is over the title "click here to open image" (or something).

The only my consideration is availability for people without mouse altogether – can they even use WebUI right now? I don't want paste to break completely just because there is no mouse…
Otherwise, the code should be even smarter and look not only to hover, but on selected/keyboard-focus elements too.
