### ISSUE TITLE
When "Only masked" is specified for Inpaint, the image is not drawn correctly

### ISSUE THREAD

**Issue by mutaguchi** [Mikubill/sd-webui-controlnet#78]
When "Only masked" is specified for Inpaint in the img2img tab, ControlNet may not render the image correctly.

When specifying "Only masked", I think it is necessary to crop the input image generated by the preprocessor and apply it within the masked range.

An example is shown below.

This is the original image.
<img width="666" alt="image" src="https://user-images.githubusercontent.com/1762724/219211390-fab4b83e-2b6a-47f6-aea3-2f6b92f64b9d.png">

This is the result of inpainting with "Only masked" and generating and applying a normal map.
<img width="1355" alt="image" src="https://user-images.githubusercontent.com/1762724/219212018-70b16044-6414-417f-84ef-9ce77f3e7221.png">

**Comment by lhucklen** [comment]
are you using an inpainting model? may also try increasing padding pixels

**Comment by Dekker3D** [comment]
Definitely looks like the control image isn't cropped and zoomed in on like the source image is. Adding more padding pixels wouldn't help.

**Comment by demirklvc** [comment]
wait- i thought inpainting isnt yet possible with control net?

**Comment by Dekker3D** [comment]
img2img already works, including masking. Could be that inpainting-specific models don't work yet?

**Comment by mutaguchi** [comment]
I have inpainted an image of a cat using sd-v1-4.ckpt.

Increasing the "Only masked padding, pixels" value does indeed result in correct rendering, but I suspect that this is essentially the same as specifying "Whole picture".

In addition, when inpainting using sd-v1-5-inpainting.ckpt with ControlNet enabled, the following error occurs.

`RuntimeError: Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 9, 64, 96] to have 4 channels, but got 9 channels instead`

This may be another problem.

**Comment by VantomPayne** [comment]
Seconded, hopefully support for inpainting specific models can be implemented, it will greatly enhance the process.

**Comment by 2blackbar** [comment]
This is still not working correctly, its one of the most important features in webui, i think the pipeline order needs to be changed to take into consideration the actual inpainted area only and not the whole image

**Comment by lhucklen** [comment]
Inpainting model support would be killer. Hopefully he implements.

**Comment by loboere** [comment]
same get error RuntimeError: Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 9, 64, 96] to have 4 channels, but got 9 channels instead  , please add support for the sd-v1-5-inpainting model

**Comment by Mikubill** [comment]
fixed in https://github.com/Mikubill/sd-webui-controlnet/commit/da7a3609e1011b7a2a1f020b77cb630743d11b2f

**Comment by donzimmah** [comment]
Still get same `RuntimeError: Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 9, 64, 64] to have 4 channels, but got 9 channels instead` error when trying to use an inpainting model

**Comment by loboere** [comment]
same

**Comment by mutaguchi** [comment]
Both the "Only masked" option and drawing in the inpainting model now work well.
Thank you very much.

**Comment by cheetahchicken** [comment]
I'm still getting this error when trying to use the 1.5 inpaint model:

```
RuntimeError: The size of tensor a (4) must match the size of tensor b (9) at non-singleton dimension 1
```

I'm on the latest ControlNet commit attempting to use the 1.5 inpainting checkpoint.

**Comment by RenderTool** [comment]
![image](https://user-images.githubusercontent.com/31579609/231449607-5950421b-575f-4bf5-bc0f-a728d37ced66.png)
