### ISSUE TITLE
Img2img support?

### ISSUE THREAD

**Issue by Dekker3D** [Mikubill/sd-webui-controlnet#8]
I don't see a ControlNet section on the img2img tab, but as far as I know, it should be something the model could support. I think it would allow some extremely fine control over the output.

**Comment by Gushousekai195** [comment]
Yeah. I figured this would be in the Img2Img tab, not the Text2Img tab!

**Comment by 2blackbar** [comment]
This makes resolutions like 960x960 possible on 1.5 models without any double bodyparts, its pretty amazing !
This is next step and a revolution for SD in my opinion, so great!

**Comment by 2blackbar** [comment]
I would love to use it with inpainting tab, so we can mask the stuff and it would process it, only the masked part of big image would be replaced

**Comment by Mikubill** [comment]
Just unlocked limits on img2img, but not ensure if it works (feedback welcome).

**Comment by AugmentedRealityCat** [comment]
> feedback welcome

I'm going to test that immediately and I'll be back !

**Comment by AugmentedRealityCat** [comment]
I can now confirm it: 
### ControlNet now works in with IMG2IMG !

**Comment by Dekker3D** [comment]
I just tried it too, it's awesome!

**Comment by daogework** [comment]
> I can now confirm it:
> 
> ### ControlNet now works in with IMG2IMG !
> ![Stable Diffusion](https://user-images.githubusercontent.com/114955776/218649742-76d89d67-b098-4fa9-b3a5-bfbb5583f21b.jpg)

So would you share the code?

**Comment by 2blackbar** [comment]
Works great ! The only thing that could be changed is ability to use image from top panel ( no w you have to load same image twice to top img2img and bottom controlnet panels)
Something like a tickbox with "use same image as img2img) would be great and would save time, so you basically only load top image and leave controlnet image empty and it would still work

**Comment by Klace** [comment]
> Works great ! The only thing that could be changed is ability to use image from top panel ( no w you have to load same image twice to top img2img and bottom controlnet panels) Something like a tickbox with "use same image as img2img) would be great and would save time, so you basically only load top image and leave controlnet image empty and it would still work oh people actually want to use 2 different images for both , so id say tickbox would be best

I think https://github.com/Mikubill/sd-webui-controlnet/pull/36 took care of this

**Comment by ClashSAN** [comment]
for more understanding of this workflow:

| img2img input  | controlnet input  | canny extraction  | generated result  |
|---|---|---|---|
| ![00006-1796276134](https://user-images.githubusercontent.com/98228077/218893373-957226ab-71bd-45fe-8d70-acb7f8d4e80a.png) prompt: moon |  ![00007-2792489619](https://user-images.githubusercontent.com/98228077/218893410-05717e1e-cf55-455b-b830-cefa44d79a98.png) | ![00008](https://user-images.githubusercontent.com/98228077/218893447-e782f859-100b-4f63-b2f2-afeb719f6d1d.png)  | ![00009-1638568050](https://user-images.githubusercontent.com/98228077/218893481-406fbebf-62ad-4516-b2a5-91765abf59bc.png)  |

**Comment by Klace** [comment]
Can still use the same picture for both control and initial image if so desired, so it's nice to have the option to only place in the initial image.

**Comment by ClashSAN** [comment]
I wonder if there are positives using the riffusion model, too.

**Comment by Dekker3D** [comment]
I literally tried that this afternoon, but trying to load Riffusion in Auto1111 kept filling up my 16 GB of ram and requiring a hard reset. It's usually used with img2img at average denoising strength, but a ControlNet could allow it to be used with higher strength or even straight txt2img instead.

**Comment by ClashSAN** [comment]
https://huggingface.co/ckpt/riffusion-model-v1/blob/main/riffusion-model-v1-half.ckpt
there's no quality difference using this. By default everybody uses fp16 anyway.

**Comment by Dekker3D** [comment]
I'm pretty sure this can be closed now, as img2img support is implemented.
