### ISSUE TITLE
[Bug]: maybe not a bug,models\\sketch_adapter_v14.yaml is missing,so error occur

### ISSUE THREAD

**Issue by mlwei1** [Mikubill/sd-webui-controlnet#802]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

using adapter models in controlnet ,

### Steps to reproduce the problem

using adapter models in controlnet to create pictures

### What should have happened?

using adapter model to create pictures sucessfully

### Commit where the problem happens

webui: A1111 web ui
controlnet: 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\scx56\\Documents\\A1111_Web_UI_Autoinstaller_2\\stable-diffusion-webui\\extensions\\sd-webui-controlnet\\models\\sketch_adapter_v14.yaml'
```

### Additional information

no

**Comment by ljleb** [comment]
Anyone with the previous sketch adapter config location in the settings will have to manually set it to `t2iadapter_sketch_sd14v1.yaml` now. Might want to consider using the previous config location as an alias for the new location when no config can be found at the old location.

**Comment by mlwei1** [comment]
> Anyone with the previous sketch adapter config location in the settings will have to manually set it to `t2iadapter_sketch_sd14v1.yaml` now. We might want to consider using the previous config location as an alias for the new location when no config can be found at the old location.

thank u for answer,now i had manually set it to t2iadapter_sketch_sd14v1.yaml,and it works finely with t2iadapter_canny_sd15v2,  but error with other adapter models like t2iadapter_depth_sd15v2 and color,
console error:
RuntimeError: Error(s) in loading state_dict for Adapter:
        size mismatch for conv_in.weight: copying a param with shape torch.Size([320, 192, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 64, 3, 3]).

it seems to be t2iadapter_sketch_sd14v1.yaml not fit to other adapter model

**Comment by ljleb** [comment]
There is now one config per model in `/models`. You may need to manually set the adapter config to `t2iadapter_canny_sd15v2.yaml` for now.

**Comment by lllyasviel** [comment]
fixed
