### ISSUE TITLE
'Shuffle or Guess in --lowvram or --medvram needs you to add --always-batch-cond-uncond in your A1111 flags'

### ISSUE THREAD

**Issue by DavidSnow1** [Mikubill/sd-webui-controlnet#805]
Hey. Great update. I initially installed this last night when it was first announced on Reddit. Downloaded all the models, and everything went great. I tested for multiple hours and went to bed. Woke up this morning and updated the extension, now I'm getting this:

> Traceback (most recent call last):
>   File "C:\Users\Snow\stable-diffusion-webui\modules\call_queue.py", line 56, in f
>     res = list(func(*args, **kwargs))
>   File "C:\Users\Snow\stable-diffusion-webui\modules\call_queue.py", line 37, in f
>     res = func(*args, **kwargs)
>   File "C:\Users\Snow\stable-diffusion-webui\modules\img2img.py", line 171, in img2img
>     processed = process_images(p)
>   File "C:\Users\Snow\stable-diffusion-webui\modules\processing.py", line 486, in process_images
>     res = process_images_inner(p)
>   File "C:\Users\Snow\stable-diffusion-webui\modules\processing.py", line 632, in process_images_inner
>     samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
>   File "C:\Users\Snow\stable-diffusion-webui\modules\processing.py", line 1048, in sample
>     samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
>   File "C:\Users\Snow\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 323, in sample_img2img
>     samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
>   File "C:\Users\Snow\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 226, in launch_sampling
>     return func()
>   File "C:\Users\Snow\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 323, in <lambda>
>     samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
>   File "C:\Users\Snow\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
>     return func(*args, **kwargs)
>   File "C:\Users\Snow\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
>     denoised = model(x, sigmas[i] * s_in, **extra_args)
>   File "C:\Users\Snow\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "C:\Users\Snow\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 137, in forward
>     x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond={"c_crossattn": c_crossattn, "c_concat": [image_cond_in[a:b]]})
>   File "C:\Users\Snow\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "C:\Users\Snow\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
>     eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
>   File "C:\Users\Snow\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
>     return self.inner_model.apply_model(*args, **kwargs)
>   File "C:\Users\Snow\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
>     setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
>   File "C:\Users\Snow\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
>     return self.__orig_func(*args, **kwargs)
>   File "C:\Users\Snow\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
>     x_recon = self.model(x_noisy, t, **cond)
>   File "C:\Users\Snow\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1212, in _call_impl
>     result = forward_call(*input, **kwargs)
>   File "C:\Users\Snow\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1329, in forward
>     out = self.diffusion_model(x, t, context=cc)
>   File "C:\Users\Snow\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "C:\Users\Snow\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 255, in forward2
>     return forward(*args, **kwargs)
>   File "C:\Users\Snow\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 199, in forward
>     raise 'Shuffle or Guess in --lowvram or --medvram needs you to add --always-batch-cond-uncond in your A1111 flags'
> TypeError: exceptions must derive from BaseException

I added "--always-batch-cond-uncond" to my args (which I shouldn't need to do) and the problem persists. Rtx 3080, if you are interested. Any thoughts?

**Comment by zark119** [comment]
same problem. I have 3060 12g vcard

**Comment by 54681** [comment]
I also have the same problem, but there is no problem if the +- prompt words are controlled within 75. Followed by shuffle seems to have no effect.
![`U_{0J{CM8JUR%UL`U4TRCE](https://user-images.githubusercontent.com/125456320/232316822-4646b02c-90d5-42ad-9d92-f0bbd949a84f.png)
![BD8O4(KA7H87M3H@L0$SQZ7](https://user-images.githubusercontent.com/125456320/232316837-c4410329-d92a-47fe-a26c-a6a608c058a8.png)
No error was reported in the two operations, only the controlnet option was turned on and off.

**Comment by physis123** [comment]
The issue seems to be when using "Guess Mode" with a prompt larger than 75. 

Shortening the prompt or switching off guess mode fixes it.

**Comment by lllyasviel** [comment]
I have fixed the situation and changed the bahavior back to previous behaviors when the it fail
https://github.com/Mikubill/sd-webui-controlnet/commit/d499bd4080dc87ef00dc5a7bc2024483bc84b51b

Now it will not faile to generate images, but the inner problem is still there.
Note that the previous implementation will not fail but is incorrect. 

But now it should work in most cases

**Comment by lllyasviel** [comment]
I am closing this. let mw know if any problem remains
