### ISSUE TITLE
[Help Needed] Someone to maintain the preprocessor API

### ISSUE THREAD

**Issue by lllyasviel** [Mikubill/sd-webui-controlnet#809]
I am not very familiar with the API part and I am mainly maintaining the correctness of inference.
We need some other contributors to maintain the correctness of APIs for other projects to use.

**Comment by lllyasviel** [comment]
@Mikubill can you take a look at api part?

**Comment by physis123** [comment]
I can't really help I'm afraid but I am hoping the new depth_leres parameters (Remove Near % and Remove Background %) will be added to ControlNetUnitRequest in the API soon.

**Comment by ljleb** [comment]
We should `getattr` on `scripts.processor` and only list exceptional cases with `if elif` cases, otherwise this will be time consuming to maintain.

**Comment by ljleb** [comment]
Should be fixed now.
