### ISSUE TITLE
[Bug]: ControlNet 1.1 - Shuffle + Shuffle Pre-Processor - 1st Generation on same seed is different to all generations after

### ISSUE THREAD

**Issue by Arron17** [Mikubill/sd-webui-controlnet#811]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When producing an image with the shuffle controlnet and the Shuffle Pre-Processor if you lock the seed and generate again with the exact same parameters the image will change completely. Any more generations after, so 3rd, 4th, 5th and so on are the same as the 2nd generation.

This doesn't happen if you use the Shuffle ControlNet without the Pre-Processor

### Steps to reproduce the problem

1. In the ControlNet tab place an image, select preprocessor shuffle and model control_v11e_sd15_shuffle:
![image](https://user-images.githubusercontent.com/87210034/232349632-be2be9b6-f618-4f8a-95d0-192426a2480e.png)
2. Generate an image:
Prompt: solo, Realistic, woman, very long hair, red hair, brown eyes, armor, full helmet
Negative prompt: (Worst quality, bad quality:1.4), patreon username, patreon logo, artist name, signature,
Steps: 35, Sampler: DPM++ 2M Karras, CFG scale: 6, Seed: 636563336, Size: 512x768, Model hash: 61e23e57ea, Model: mixProV4_v4, Clip skip: 2, ControlNet-0 Enabled: True, ControlNet-0 Module: shuffle, ControlNet-0 Model: control_v11e_sd15_shuffle [526bfdae], ControlNet-0 Weight: 0.9, ControlNet-0 Guidance Start: 0, ControlNet-0 Guidance End: 1
![image](https://user-images.githubusercontent.com/87210034/232349659-2d8b76d4-e0f8-40e0-8604-23d89f6767b9.png)
3. Lock or "Recycle" the seed:
![image](https://user-images.githubusercontent.com/87210034/232349686-c0ba5988-837a-4cee-99ae-8d2e371e3f04.png)
4. Click to generate the image again. Change nothing.
Prompt: solo, Realistic, woman, very long hair, red hair, brown eyes, armor, full helmet
Negative prompt: (Worst quality, bad quality:1.4), patreon username, patreon logo, artist name, signature,
Steps: 35, Sampler: DPM++ 2M Karras, CFG scale: 6, Seed: 636563336, Size: 512x768, Model hash: 61e23e57ea, Model: mixProV4_v4, Clip skip: 2, ControlNet-0 Enabled: True, ControlNet-0 Module: shuffle, ControlNet-0 Model: control_v11e_sd15_shuffle [526bfdae], ControlNet-0 Weight: 0.9, ControlNet-0 Guidance Start: 0, ControlNet-0 Guidance End: 1
![image](https://user-images.githubusercontent.com/87210034/232349728-f44bcb85-bd26-4db7-8499-a99ad2cf83bf.png)

Note: clicking generate again for a 3rd time or any more times after, always then produces the exact same image, so it seems to be some change between the initial generation and then the first repeat.

### What should have happened?

The image should not drastically change between the 1st and 2nd generations of the same seed and identical settings.

Especially as it doesn't then change between the 2nd and 3rd and 4th..... images.

### Commit where the problem happens

webui: 22bcc7be428c94e9408f589966c2040187245d81
controlnet: 82c42285b9e28f6ab76aa35e2ed62690639b2b5c

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
--opt-sdp-attention --no-half-vae --opt-channelslast
```

### Console logs

```Shell
Nothing different happens in the console logs between the generations
```

**Comment by Arron17** [comment]
Forgot to include, the shuffle images. These are changing which is causing this issue.

1st Generation:
![image](https://user-images.githubusercontent.com/87210034/232350035-1cb75d30-79d7-42a8-a556-72706f530c43.png)

2nd Generation:
![image](https://user-images.githubusercontent.com/87210034/232350074-dc4841cd-8406-4657-88eb-1b13dabe6186.png)

3rd Generation:
![image](https://user-images.githubusercontent.com/87210034/232350100-365b9def-e0b8-4364-9d58-d2bc0380add9.png)

**Comment by lllyasviel** [comment]
I cannot reproduce. how you fix seed?

**Comment by Arron17** [comment]
> I cannot reproduce. how you fix seed?

After a generation click the recycle button to the right of the seed box in the A1111 WebUI, I've included a screenshot showing the window under step 3.

This Button: 
![image](https://user-images.githubusercontent.com/87210034/232350995-c2da3dc0-bf79-4327-9107-bf5e7725642e.png)

**Comment by lllyasviel** [comment]
I can reproduce it.

But it seems an a1111 problem rather than controlnet problem. Any one have ideas?
