### ISSUE TITLE
[Bug]: Weight, Guidance Start and Guidance End Selected isn't always being correctly used

### ISSUE THREAD

**Issue by Arron17** [Mikubill/sd-webui-controlnet#812]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When generating an image after changing the Weight, Guidance Start and Guidance End, the Weight, Guidance Start and Guidance End valuez shown in the prompt information is incorrect.

For example you can select 1 and generate and the prompt information will show 1, then you change the value to 0.9 and generate, but the prompt information will now show 0.95.

The same bug happens with all 3 value types.

It seems inconsistent however.

### Steps to reproduce the problem

1. Use any ControlNet model to generate an image
![image](https://user-images.githubusercontent.com/87210034/232350661-832371ef-2194-426e-bf2f-41832f4d7c83.png)
` ControlNet-0 Enabled: True, ControlNet-0 Module: none, ControlNet-0 Model: control_v11p_sd15_lineart [43d4be0d], ControlNet-0 Weight: 1, ControlNet-0 Guidance Start: 0, ControlNet-0 Guidance End: 1`
2. Change one of the weight, guidance start or guidance end values.
![image](https://user-images.githubusercontent.com/87210034/232350708-aaaa9bd0-4aa5-45c5-98b4-7042e2e3f4ee.png)
3. Check the prompt information and the value does not match what is selected (It may require a few attempts to get it to do this)
`ControlNet-0 Enabled: True, ControlNet-0 Module: none, ControlNet-0 Model: control_v11p_sd15_lineart [43d4be0d], ControlNet-0 Weight: 0.9, ControlNet-0 Guidance Start: 0, ControlNet-0 Guidance End: 1`

### What should have happened?

The value in the prompt information should reflect the selected value, from testing it also seems that the generation is using the incorrect value and not the one chosen in the ControlNet UI.

### Commit where the problem happens

webui: 22bcc7be428c94e9408f589966c2040187245d81
controlnet: 82c42285b9e28f6ab76aa35e2ed62690639b2b5c

### Command Line Arguments

```Shell
--opt-sdp-attention --no-half-vae --opt-channelslast
```

### Console logs

```Shell
Nothing different happens in the console logs between the generations
```

**Comment by ljleb** [comment]
This is caused by the way we update the control unit objects in the ui code. gradio does not dispatch all events when they happen rapidly.

Updating the controls more slowly should help for now. I'll see what we can do. Maybe we'll go back to flattened options in gradio ui... or maybe we can subscribe to the txt2img and img2img generate buttons to update the objects before generation starts.

**Comment by ljleb** [comment]
I tried subscribing to the img2img and txt2img submit buttons, however there is a race condition when we do this. Sometimes the parameters are updated before being passed to `modules.img2img.img2img` for example, sometimes they are updated after.

I have not yet found another way to fix this, than flatten the options back to how it was before. We could look into using `inspect` to keep the number of arguments passed to `process` up to date with the actual number of arguments in each control unit.

**Comment by ljleb** [comment]
Should be fixed now, let us know if the fix works as intended.
