### ISSUE TITLE
when I use control_v11p_sd15_mlsd.pth, raise a error: model not found: None

### ISSUE THREAD

**Issue by lzghades** [Mikubill/sd-webui-controlnet#829]
I download the model "control_v11p_sd15_mlsd.pth" and put it in the models, but a error raise:

 File "/data/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 517, in build_control_model
    raise RuntimeError(f"model not found: {model}")
RuntimeError: model not found: None

Did I miss any configuration?

**Comment by MarkGree** [comment]
Did you select your model in controlnet?

**Comment by MarkGree** [comment]
Try to copy `control_v11p_sd15_mlsd.yaml` from the `extensions\sd-webui-controlnet\models` folder to `models/ControlNet`

**Comment by lllyasviel** [comment]
fixed
