### ISSUE TITLE
Using canny generated image without preproccesor creates bugged images

### ISSUE THREAD

**Issue by Nazzaroth2** [Mikubill/sd-webui-controlnet#84]
I wanted to try the canny generated image as a mask directly, maybe change it a bit in photoshop. But just using the raw image alone without any preprocessor and the canny model creates this:

![bad](https://user-images.githubusercontent.com/49390075/219284280-55adddb8-89e2-413d-bc9a-cc15339edff5.png)

Mask:
![mask](https://user-images.githubusercontent.com/49390075/219284318-1f916770-2727-468e-a3d5-172167ddb8b3.png)

Original File:
![original](https://user-images.githubusercontent.com/49390075/219284343-1c10d5c2-6f2e-46c9-a211-86a53bfa640a.jpg)

What i get when i let the mask be generated by preproccesor:

![good](https://user-images.githubusercontent.com/49390075/219284630-def509fc-5e26-44c0-8b2e-4316cd65b23a.png)

If i activate the scribble-mode the mask semi-works but of course also inverts the colors, changing the output a bit.
I did not see similar issues with other models like openpose or hed, which is why i expect it is actually a bug. Maybe not reading the mask correctly?

**Comment by Takemorikohoto** [comment]
yep I have the same problem, trying a way to figure what it doesnt work and I have no idea.

**Comment by ClashSAN** [comment]
can confirm, it worked before.

normal maps input was also not working from the start. the rest of them seem to work fine on cuda.

let's see if we can pinpoint the commit

**Comment by Mikubill** [comment]
Normal maps input requires `RGB to BGR` option as stated in #71. And if you want to use something like lineart, `Scribble Mode` is required to produce correct result. We have some plan to add auto inverse (#7) but not impl yet.

**Comment by ClashSAN** [comment]
ah, my bad. I thought it worked before.

**Comment by Takemorikohoto** [comment]
well the problem I'm having is that I use image preprocess by canny and put it into canny again but it doesnt work.

**Comment by Nazzaroth2** [comment]
yeah exactly, it's not selfmade lineart, it is the direct output image from canny-preprocessor. So either the shown mask image when generating images is not the version that get's fed into the canny-model on the normal process, or when we don't use preprocessor the image doesn't get fed into the model correctly.

This process works perfectly fine with hed-model, so i do think it is more a bug than user error.

**Comment by Mikubill** [comment]
Hmm no matter self-made or not, once the background is white you should inverse it since the model input requires. Simple test:

1-pass: using original pic:
![input-3](https://user-images.githubusercontent.com/31246794/219304737-7d209275-6d7b-418b-9eeb-929e106ecb3c.png)

2-pass: using output from canny:
![inpug-4](https://user-images.githubusercontent.com/31246794/219304881-948628a4-73c5-4d74-a06c-9f181012656a.png)

well, at least it looks like the output is almost the same

**Comment by Takemorikohoto** [comment]
yeah that is literally what I'm trying to do but it doesnt work

**Comment by Nazzaroth2** [comment]
ok if that is how it is supposed to be used it's fine, but why is the canny output then shown how it is shown? There HAS to be a difference between the canny image that gets fed from the preprocessor into the ai model and the mask image that is saved into the temp folder, otherwise the canny-model would never work in the first place.
If it can't be done manually fine, but just from a technical standpoint it makes no sense why we should not be able to use the output of the preprocessor directly as the mask image.

**Comment by ClashSAN** [comment]
I feed canny input and am getting light brown scaly images with some form. I think it may be some kind of vae problem but I'll keep testing.

**Comment by Mikubill** [comment]
Show white-background image is for user-friendly. In fact we used same process as original repo:
https://github.com/Mikubill/sd-webui-controlnet/blob/760f9d78244b1a3678c83d6e3311fe5fc34ada32/scripts/controlnet.py#L357-L358


You can find such things on [lllyasviel/ControlNet/gradio_canny2image.py](https://github.com/lllyasviel/ControlNet/blob/5b9908e35c43aa020695a819c6cab1b8ae2f3695/gradio_canny2image.py#L64)


And about threshold and resolution, currently they are hard-encoded in https://github.com/Mikubill/sd-webui-controlnet/blob/760f9d78244b1a3678c83d6e3311fe5fc34ada32/scripts/processor.py#L9-L12

Maybe we should add it to somewhere later.

**Comment by Nazzaroth2** [comment]
alright that clears up my confussion ^^
So basically just use the scribble mode to get the original mask-input.
Maybe add a note about it in the readme so other users don't get confused like me?

**Comment by enn-nafnlaus** [comment]
So people (myself included) stop getting confused by this, it would be best to stop converting it into a white background version that's unusable.  Can't tell you how much time I've wasted trying to get white background canny images to work, only getting those sorts of "cracked paint" images like at the top of this thread!
