### ISSUE TITLE
[Bug]: controlnet cannot be used normally

### ISSUE THREAD

**Issue by awy-ww** [Mikubill/sd-webui-controlnet#852]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When using it after the update, some functions are available, but some functions cannot be used. It is very strange. After reinstalling many times, it is still the same problem
![微信图片_20230418000506](https://user-images.githubusercontent.com/129488620/232544750-2333c9e4-48e4-4f98-894e-77789bffe4f0.png)
![微信图片_20230418000541](https://user-images.githubusercontent.com/129488620/232544773-1f10b341-702c-4421-9c82-73d9a58d789e.jpg)
![微信图片_20230418000621](https://user-images.githubusercontent.com/129488620/232544789-aca68fb0-fcd0-4b69-8b60-2702a60a484b.jpg)

### Steps to reproduce the problem

1. Regenerate after update
2. Some functions cannot be used

### What should have happened?

All functions should work normally

### Commit where the problem happens

webui: 
controlnet:  not working

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
amd graphics card, download and install manually,
```

**Comment by ljleb** [comment]
Have you tried restarting the webui completely? After some testing, it seems that some preprocessors will not be recognized because `scripts.process` is not passed to `importlib.reload`.

If the problem persists, can you specify which function you are referring to? If you are more comfortable speaking in another language than English feel free to do it, I will use google translate or similar services.

**Comment by MarkGree** [comment]
Try to copy all of your `.yaml` files from the `extensions\sd-webui-controlnet\models` folder to `models/ControlNet`
Also your models and .yaml files should have the same name I believe (that worked for me)

If the error still remains, open the console and show us what it says after you have the error.

**Comment by lllyasviel** [comment]
update again and completely restart including terminal

**Comment by awy-ww** [comment]
I'm sorry to trouble you again, now according to your help, the basic functions can be used, but the only posture detection can not be used normally, I have to ask for your help, thank you,By the way, I am using win10 gpu 6600xt graphics card
this is the error code:RuntimeError: Input type (torch.FloatTensor) and weight type (PrivateUse1FloatType) should be the same or input should be a MKLDNN tensor and weight is a dense tensor
![微信图片_20230418144057](https://user-images.githubusercontent.com/129488620/232692849-d1f12d53-72ea-4cdd-88ce-c3ae45193b2f.png)
