### ISSUE TITLE
txt2img's input_image is not used in /sdapi/v1/txt2img (payload included)

### ISSUE THREAD

**Issue by ivanskodje** [Mikubill/sd-webui-controlnet#865]
## The Issue
txt2img does not use `input_image` no matter what I set it to via the /sdapi/v1/txt2img API

## Expected Result
I expect the image I am drawing to alter the way the image is generated, like when done from within Automatic111 which works just fine.

## My setup

According to somevague documentation this is the way I am supposed to set the image:

**URI:** http://localhost:7860/sdapi/v1/txt2img
**Payload:**
```json
{
    "prompt": "A cartoon style scene",
    "negative_prompt": "",
    "seed": 42113322,
    "subseed": -1,
    "subseed_strength": 0,
    "batch_size": 1,
    "steps": 15,
    "cfg_scale": 7,
    "width": 512,
    "height": 512,
    "eta": 0,
    "sampler_index": "Euler a",
    "enable_hr": "false",
    "alwayson_scripts": {
        "controlnet": {
            "args": [
                {
                    "enabled": true,
                    "input_image": "base64 image goes here"
                    "model": "control_normal-fp16 [63f96f7c]",
                    "weight": 1.0,
                    "guidance": 1.0,
                    "guidance_start": 0.0,
                    "guidance_end": 1.0,
                    "guessmode": false
                }
            ]
        }
    }
}
```
I have confirmed it does not use it at all by completely removing the input_image, as well as to print the base64 to verify it is different.

If this is not the correct way to send the base64 image I want it to be based on; what is the correct way?

**Comment by ljleb** [comment]
Yeah I need to update the docs to remove the old routes or swap their place with the current API.

The webui currently does not work well with alwayson scripts that take a variable number of args. Make sure you always put exactly the max amount of controlnet specified in settings.

**Comment by ljleb** [comment]
Can you try removing `"guidance"` from your arguments? It is a deprecated field. Maybe it is related?

**Comment by ivanskodje** [comment]
> Can you try removing `"guidance"` from your arguments? It is a deprecated field. Maybe it is related?

Unfortunately that did not change the end result:

```json
{
    "prompt": "A cartoon style scene",
    "negative_prompt": "",
    "seed": 42113322,
    "subseed": -1,
    "subseed_strength": 0,
    "batch_size": 1,
    "steps": 15,
    "cfg_scale": 7,
    "width": 512,
    "height": 512,
    "eta": 0,
    "sampler_index": "Euler a",
    "enable_hr": "false",
    "alwayson_scripts": {
        "controlnet": {
            "args": [
                {
                    "enabled": true,
                    "model": "control_normal-fp16 [63f96f7c]",
                    "weight": 1.0,
					"guidance_start": 0.0,
					"guidance_end": 1.0,
                    "guessmode": false
                }
            ]
        }
    }
}
```

**Comment by cucued** [comment]
i have same problem,the response info containing ControlNet Enable:True and so on,but the image is not related with the input image.and rs['images'] have only 1 result image .
