### ISSUE TITLE
MacOS?

### ISSUE THREAD

**Issue by koen330** [Mikubill/sd-webui-controlnet#87]
Is ControlNet compatible with MacOS.
I could install it, and see it in the webUI, but when I use it, I get following error:

Loading preprocessor: canny, model: control_sd15_canny [fef5e48e]
Loaded state_dict from [/Users/koen/Documents/SD/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_sd15_canny.pth]
ControlNet model control_sd15_canny [fef5e48e] loaded.
0%| | 0/16 [00:00<?, ?it/s]loc("mps_add"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/a0876c02-1788-11ed-b9c4-96898e02b808/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":219:0)): error: input types 'tensor<2x1280xf32>' and 'tensor<*xf16>' are not broadcast compatible
LLVM ERROR: Failed to infer result type(s).
zsh: abort ./webui.sh
koen@Koens-MacBook-Pro-2 stable-diffusion-webui % /opt/homebrew/Cellar/python@3.10/3.10.10/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
warnings.warn('resource_tracker: There appear to be %d '

Shortly after "Python quit unexpectedly"

Koen

**Comment by Mikubill** [comment]
Related: #68, will fix later

**Comment by brkirch** [comment]
Make sure you start web UI with `--no-half` for now. I do plan to try to get it working without `--no-half` but it may be up to a few days until I have enough time for that.

**Comment by koen330** [comment]
--no-half seems to work.
Thanks!!

**Comment by Mikubill** [comment]
> error: 'mps.matmul' op contracting dimensions differ 1024 & 768

Pretrained controlnet model is for sd1.5/sd1.4, not compatible with sd2/sd2.1/inpainting model.

**Comment by a-starry-night** [comment]
another error seemingly related with macOS or could the execution model be a problem - currently using wd15 should I use default sd?

`
(mpsFileLoc): /AppleInternal/Library/BuildRoots/97f6331a-ba75-11ed-a4bc-863efbbaf80d/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm:39:0: error: 'mps.matmul' op contracting dimensions differ 1024 & 768
(mpsFileLoc): /AppleInternal/Library/BuildRoots/97f6331a-ba75-11ed-a4bc-863efbbaf80d/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm:39:0: note: see current operation: %5 = "mps.matmul"(%arg0, %4) {transpose_lhs = false, transpose_rhs = false} : (tensor<2x77x1024xf32>, tensor<768x320xf32>) -> tensor<2x77x320xf32>
/opt/homebrew/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
zsh: segmentation fault  sh webui.sh
`

**Comment by LightGlobal** [comment]
the same error happy "segmentation fault":

- success commit: 9ea19a74a027a29e0a80c1b9f901331a82d63db3
- error commit: ca03f4e3d8a4839009af083d305aa195be956c01

**Comment by linusqqqq** [comment]
<img width="1440" alt="Bildschirmfoto 2023-07-17 um 19 18 09" src="https://github.com/Mikubill/sd-webui-controlnet/assets/139799711/45039562-f328-481b-bbee-0c8ea22942eb">
Please help. It is still not working for me. M1 Air 8GB
