### ISSUE TITLE
TypeError: PlugableControlModel.__init__() got an unexpected keyword argument 'base_model'

### ISSUE THREAD

**Issue by MarkEmery** [Mikubill/sd-webui-controlnet#88]
Just updated ControlNet via Automatic GUI, it now bombs out when trying to generate an image:

`Loading preprocessor: openpose, model: control_sd15_openpose [fef5e48e]

Error running process: /Users/emerym/Downloads/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py

Traceback (most recent call last):

  File "/Users/emerym/Downloads/stable-diffusion-webui/modules/scripts.py", line 386, in process
    script.process(p, *script_args)

  File "/Users/emerym/Downloads/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 280, in process

    network = PlugableControlModel(

TypeError: PlugableControlModel.__init__() got an unexpected keyword argument 'base_model'`

**Comment by Mikubill** [comment]
Restart webui instead of reload it.

**Comment by MarkEmery** [comment]
I did that. Twice. Now when I click Generate I get this:

ControlNet model control_sd15_openpose [fef5e48e] loaded.
  0%|                                                                                                                      | 0/20 [00:00<?, ?it/s]loc("mps_matmul"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/0aa643d0-625a-11ed-b319-a23c4f261b56/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":39:0)): error: inner dimensions differ 1024 & 768
loc("mps_matmul"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/0aa643d0-625a-11ed-b319-a23c4f261b56/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":39:0)): error: invalid shape
LLVM ERROR: Failed to infer result type(s).

I've noticed on startup I now get this. 90% sure I didn't get it before adding ControlNet

Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
No module 'xformers'. Proceeding without it.
Cannot import xformers
Traceback (most recent call last):
  File "/Users/emerym/Downloads/stable-diffusion-webui/modules/sd_hijack_optimizations.py", line 20, in <module>
    import xformers.ops
ModuleNotFoundError: No module named 'xformers'

**Comment by Mikubill** [comment]
Maybe same issue as #68 and #87. https://github.com/Mikubill/sd-webui-controlnet/issues/68#issuecomment-1431639073 this may help but slow, xformers shouldn't have any impact since mps device not depends on it.

**Comment by WhiteZeroX** [comment]
I was having this too. I updated the extension and fully restarted webui and it's working now.

**Comment by MarkEmery** [comment]
I've done a fresh install, now get:

ControlNet model control_sd15_openpose [fef5e48e] loaded.
  0%|                                                                                                                      | 0/20 [00:00<?, ?it/s]loc("mps_matmul"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/0aa643d0-625a-11ed-b319-a23c4f261b56/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":39:0)): **error: inner dimensions differ 1024 & 768**
loc("mps_matmul"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/0aa643d0-625a-11ed-b319-a23c4f261b56/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":39:0)): error: invalid shape
LLVM ERROR: Failed to infer result type(s).
/opt/homebrew/Cellar/python@3.10/3.10.10/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by Mikubill** [comment]
Use sdv1 model with sdv1//sd15 pretrained controlnet.

**Comment by MarkEmery** [comment]
Doh! Sorry, bit of a SD n00b here. It would help. v1.4 model downloaded, it's all working now. Slow on my 8GB Mini M1, but working. Thanks!
