### ISSUE TITLE
Does ControlNet 1.1 support API yet?

### ISSUE THREAD

**Issue by Haoming02** [Mikubill/sd-webui-controlnet#887]
I have the latest ControlNet 1.1 ([0696c67c](https://github.com/Mikubill/sd-webui-controlnet/commit/0696c67cfef2bb991157470475583c3c7c8b45ae)) installed. And I'm trying to activate it via the API.
I send the following payload to `/sdapi/v1/img2img`:
```json
{
  "init_images": [ "base64 img" ],
  "resize_mode": 1,
  "denoising_strength": 0.69,
  "mask": "base64 img",
  "mask_blur": 32,
  "inpainting_fill": 0,
  "inpaint_full_res": false,
  "inpaint_full_res_padding": 128,
  "inpainting_mask_invert": 0,
  "initial_noise_multiplier": 1,
  "prompt": "...",
  "negative_prompt": "(low quality, worst quality:1.2)",
  "seed": -1,
  "sampler_name": "Euler a",
  "batch_size": 1,
  "steps": 24,
  "cfg_scale": 8.0,
  "width": 512,
  "height": 512,
  "restore_faces": false,
  "tiling": false,
  "alwayson_scripts": {
    "controlnet": {
      "args": [
        {
          "enabled": true,
          "input_image": "base64 img",
          "module": "depth",
          "model": "control_v11f1p_sd15_depth [cfd03158]",
          "weight": 2.0,
          "guidance": 1.0,
          "guidance_start": 0.0,
          "guidance_end": 1.0,
          "guessmode": false
        }
      ]
    }
  }
}
```
The image generated normally. And no error is shown in the CLI.
However, the result image doesn't seem to be influenced by ControlNet.

I have set `Max models amount` and `Model cache size` to 1; unchecked all settings except for `Allow other script to control this extension`.

Also, when using ControlNet on the webui, it would show `Loading model ...` and `Loading preprocessor: ...` in the CLI. 
But they didn't appear when using the API. 

Am I doing something wrong?

**Comment by ljleb** [comment]
Related to #865. No indication of error when using multiple units, but I assume the underlying error is the same.

**Comment by ljleb** [comment]
By the way `"guidance"` is the deprecated name for `"guidance_end"`, you should prefer to use `"guidance_end"` in the api.

**Comment by Haoming02** [comment]
Tried setting `Max models amount` to **2** and restart the webui completely.
Then send the following:
```json
{
  "init_images": [ "..." ],
  "resize_mode": 1,
  "denoising_strength": 0.69,
  "mask": "...",
  "mask_blur": 32,
  "inpainting_fill": 0,
  "inpaint_full_res": false,
  "inpaint_full_res_padding": 128,
  "inpainting_mask_invert": 0,
  "initial_noise_multiplier": 1,
  "prompt": "...",
  "negative_prompt": "(low quality, worst quality:1.2)",
  "seed": -1,
  "sampler_name": "Euler a",
  "batch_size": 1,
  "steps": 24,
  "cfg_scale": 8.0,
  "width": 512,
  "height": 512,
  "restore_faces": false,
  "tiling": false,
  "alwayson_scripts": {
    "controlnet": {
      "args": [
        {
          "enabled": true,
          "input_image": "...",
          "module": "depth",
          "model": "control_v11f1p_sd15_depth [cfd03158]",
          "weight": 2.0,
          "guidance_start": 0.0,
          "guidance_end": 1.0,
          "guessmode": false
        },
        {
          "enabled": false,
          "input_image": "",
          "module": "",
          "model": "",
          "weight": 1.0,
          "guidance_start": 0.0,
          "guidance_end": 1.0,
          "guessmode": false
        }
      ]
    }
  }
}
```

The result is still the same, no influence and no error, unfortunately.

**Comment by thegenerativegeneration** [comment]
> Tried setting `Max models amount` to **2** and restart the webui completely. Then send the following:
> 
> ```json
> {
>   "init_images": [ "..." ],
>   "resize_mode": 1,
>   "denoising_strength": 0.69,
>   "mask": "...",
>   "mask_blur": 32,
>   "inpainting_fill": 0,
>   "inpaint_full_res": false,
>   "inpaint_full_res_padding": 128,
>   "inpainting_mask_invert": 0,
>   "initial_noise_multiplier": 1,
>   "prompt": "...",
>   "negative_prompt": "(low quality, worst quality:1.2)",
>   "seed": -1,
>   "sampler_name": "Euler a",
>   "batch_size": 1,
>   "steps": 24,
>   "cfg_scale": 8.0,
>   "width": 512,
>   "height": 512,
>   "restore_faces": false,
>   "tiling": false,
>   "alwayson_scripts": {
>     "controlnet": {
>       "args": [
>         {
>           "enabled": true,
>           "input_image": "...",
>           "module": "depth",
>           "model": "control_v11f1p_sd15_depth [cfd03158]",
>           "weight": 2.0,
>           "guidance_start": 0.0,
>           "guidance_end": 1.0,
>           "guessmode": false
>         },
>         {
>           "enabled": false,
>           "input_image": "",
>           "module": "",
>           "model": "",
>           "weight": 1.0,
>           "guidance_start": 0.0,
>           "guidance_end": 1.0,
>           "guessmode": false
>         }
>       ]
>     }
>   }
> }
> ```
> 
> The result is still the same, no `loading...` no influence and no error, unfortunately.

Shouldn't "controlnet" be "ControlNet"?

That's the only difference I can make out to my working config.

**Comment by ljleb** [comment]
The webui compares the extension name as `.lower()` so it does not make a difference IIRC. It may be related to an interraction between different extensions, I can't think of anything else. Would appreciate if you could test just with controlnet alone in the active extensions list.

**Comment by physis123** [comment]
For this line in your args:

` "module": "depth",`

I think you now want either:

`  "module": "depth_leres",`
or
 ` "module": "depth_midas",`

**Comment by Haoming02** [comment]
When you run `http://<localhost>/controlnet/module_list`, it does return `"depth"` as one of the option though.
```json
{"module_list":["none","canny","depth","depth_leres","hed","hed_safe","mediapipe_face","mlsd","normal_map","openpose","openpose_hand","openpose_face","openpose_faceonly","openpose_full","clip_vision","color","pidinet","pidinet_safe","pidinet_sketch","pidinet_scribble","scribble_xdog","scribble_hed","segmentation","threshold","depth_zoe","normal_bae","oneformer_coco","oneformer_ade20k","lineart","lineart_coarse","lineart_anime","lineart_standard","shuffle","tile_gaussian","inpaint","invert"]}
```

**Comment by physis123** [comment]
Yes, sorry my mistake, "depth" does work.

**Comment by omair-kg** [comment]
I can't seem to run openpose. Tried openpose_full as well. This is via the api btw, it runs fine from the webui.
Any idea what could be going wrong?

**Comment by ljleb** [comment]
All preprocessor names are listed under global_state.py > cn_preprocessor_modules. The keys are the valid preprocessor names.

**Comment by omair-kg** [comment]
Ok i figured out my problem. For some reason (I think this is coming from the webui interface) the controlnet units has a None unit appended at the end. So it would process both openpose and depth but then when it encountered the None unit it threw an exception of model not being found. For now i added a check that if a unit is none then don't append it to enabled_units and everything is working.

**Comment by Haoming02** [comment]
**Update:** I reinstalled the Automatic1111 Webui and now it works!
I guess my webui was outdated and the API had changed between the versions...
Thanks for all the helps.

**Comment by xxtyy** [comment]
Can I see your full calling code? I get no data back .thanks

**Comment by Haoming02** [comment]
## My Working Configs:
**Automatic1111:** `22bcc7b`
**ControlNet:** `3c3b9d1`
**URL:** `http://<localhost>/sdapi/v1/img2img`
**Multi ControlNet: Max models amount:** `2`
**Model cache size:** `1`
**Allow other script to control this extension:** `true`

**Payload:**
```json
{
  "init_images": [ "..." ],
  "resize_mode": 0,
  "denoising_strength": 0.75,
  "mask": "...",
  "mask_blur": 36,
  "inpainting_fill": 0,
  "inpaint_full_res": true,
  "inpaint_full_res_padding": 72,
  "inpainting_mask_invert": 0,
  "initial_noise_multiplier": 1,
  "prompt": "...",
  "negative_prompt": "...",
  "seed": -1,
  "sampler_name": "Euler a",
  "sampler_index": "Euler a",
  "batch_size": 1,
  "steps": 20,
  "cfg_scale": 8.5,
  "width": 512,
  "height": 512,
  "restore_faces": false,
  "tiling": false,
  "alwayson_scripts": {
    "ControlNet": {
      "args": [
        {
          "enabled": true,
          "input_image": "...",
          "module": "depth",
          "model": "control_v11f1p_sd15_depth [cfd03158]"
        },
        {
          "enabled": false,
          "input_image": "",
          "module": "",
          "model": ""
        }
      ]
    }
  }
}
```

**Comment by xxtyy** [comment]
import requests
import cv2
from base64 import b64encode

def readImage(path):
    img = cv2.imread(path)
    retval, buffer = cv2.imencode('.jpg', img)
    b64img = b64encode(buffer).decode("utf-8")
    return b64img

b64img = readImage("C:\Users\Administrator\Desktop\test\demo.jpg")

class controlnetRequest():
    def __init__(self, prompt):
        self.url = "http://localhost:7860/sdapi/v1/img2img"
        self.body = {
            "init_images": [b64img],
            "prompt": prompt,
            "negative_prompt": "",
            "seed": -1,
            "subseed": -1,
            "subseed_strength": 0,
            "batch_size": 1,
            "n_iter": 1,
            "steps": 20,
            "cfg_scale": 7,
            "width": 512,
            "height": 768,
            "restore_faces": True,
            "eta": 0,
            "sampler_index": "Euler a",
            "controlnet_input_image": [b64img],
            "controlnet_module": 'canny',
            "controlnet_model": 'control_canny-fp16 [e3fe7712]',
            "controlnet_guidance": 1.0,
        }

    def sendRequest(self):
        r = requests.post(self.url, json=self.body)
        return r.json()

js = controlnetRequest("walter white").sendRequest()
I used pycharm to run, followed his modification but did not return data, you this
Automatic1111: 22bcc7b
ControlNet: 3c3b9d1
URL: http://<localhost>/sdapi/v1/img2img
Multi ControlNet: Max models amount: 2
Model cache size: 1
Allow other script to control this extension: true
how to set

**Comment by xxtyy** [comment]
I'm a novice programmer,can you help me.
thank you very much

**Comment by xxtyy** [comment]
I can return the data,{'detail': 'Not Found'}
What I set is http://localhost:7860/sdapi/v1/img2img
why can't i find it

**Comment by zmq175** [comment]
I've met with that issue too, after turning off two-shot and composable-lora, everything works well now

**Comment by zhangyc** [comment]
> 

I didn't find the two-shot and composable-lora you mentioned, can you provide more information?
