### ISSUE TITLE
Feature request: Add checkbox to not show preprocessor output

### ISSUE THREAD

**Issue by DiceOwl** [Mikubill/sd-webui-controlnet#89]
The normal map/scribble/depthmap/etc. in processed.images can break other custom scripts which expected only the usual img2img/txt2img output. A simple checkbox to disable returning the map would fix this problem.

**Comment by Mikubill** [comment]
Already added, see settings panel or https://github.com/Mikubill/sd-webui-controlnet/blob/760f9d78244b1a3678c83d6e3311fe5fc34ada32/scripts/controlnet.py#L388

**Comment by DiceOwl** [comment]
Indeed, thank you.
