### ISSUE TITLE
Make new preprocessor parameters available through API

### ISSUE THREAD

**Issue by physis123** [Mikubill/sd-webui-controlnet#896]
The "depth_leres" preprocessor has a few new parameters:
Preprocessor Resolution
Remove Near %
Remove Background %

Would it be possible to add these to the "ControlNetUnitRequest" model so that we can make use of them through the API? 

Thanks!

**Comment by ljleb** [comment]
The corresponding parameters are threshold a and threshold b listed in the schema, respectively. all annotators use the thresholds in the background.
