### ISSUE TITLE
[Bug]: TypeError: int() argument must be a string, a bytes-like object or a real number, not 'list'

### ISSUE THREAD

**Issue by iljung1106** [Mikubill/sd-webui-controlnet#900]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When I turn on controlnet and generate, controlnet doesn't work and cmd shows error

### Steps to reproduce the problem

1. update webUI
2. install new version of controlnet extention
3. add control_v11p_sd15s2_lineart_anime.pth to controlnet models folder
4. turn the web ui on
5. turn the controlnet on, set image and generate

### What should have happened?

no error

### Commit where the problem happens

python: 3.10.8  •  torch: 1.12.1+cu113  •  xformers: 0.0.14.dev  •  gradio: 3.23.0  •  commit: [22bcc7be]
controlnet: sorry i don't know about it

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
--xformers --deepdanbooru --autolaunch
```

### Console logs

```Shell
Loading model from cache: control_v11p_sd15s2_lineart_anime [3825e83e]
Error running process: C:\AI\WEBUI0.64.4\stable-diffusion-webui\extensions\sd-webui-controlnet-main\scripts\controlnet.py
Traceback (most recent call last):
  File "C:\AI\WEBUI0.64.4\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "C:\AI\WEBUI0.64.4\stable-diffusion-webui\extensions\sd-webui-controlnet-main\scripts\controlnet.py", line 819, in process
    tmp_seed = int(p.all_seeds[0] if p.seed == -1 else max(int(p.seed),0))
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'list'
```

**Comment by lllyasviel** [comment]
@ljleb how to fix this?
