### ISSUE TITLE
Warning: Failed to install mediapipe==0.9.1.0, some preprocessors may not work.

### ISSUE THREAD

**Issue by mrseawood** [Mikubill/sd-webui-controlnet#902]
Warning: Failed to install mediapipe==0.9.1.0, some preprocessors may not work.
Installing sd-webui-controlnet requirement: svglib
Installing sd-webui-controlnet requirement: fvcore
Installing sd-webui-controlnet requirement: opencv-python

Can I ignore the warning or I need to install the mediapie, if I need to install it, may I know how to do it?
I find some install guide from online, but there are very rough, so I do not finish the install.
Thanks

**Comment by lllyasviel** [comment]
yes programmers ignore warning
