### ISSUE TITLE
License

### ISSUE THREAD

**Issue by CCRcmcpe** [Mikubill/sd-webui-controlnet#906]
Background: https://github.com/lllyasviel/ControlNet/issues/262

This extension, which is licensed under MIT License, uses a ControlNet implementation modified from https://github.com/lllyasviel/ControlNet, which is Apache 2.0 licensed.

Some issues of this extension:

* Does not include a copy of Apache 2.0 license, which does not comply 4.a
* Does not state changes in changed files, which does not comply 4.b

Lastly the HED implementation is licensed to https://github.com/lllyasviel/ControlNet by a special agreement, which is not clearly mentioned in this project.

**Comment by lllyasviel** [comment]
fixed https://github.com/Mikubill/sd-webui-controlnet/commit/d020a0a9636199e798cfbec5b87d5929684d86fd
