### ISSUE TITLE
 The pose of my character remains totally static throughout the duration of the video [Bug]:  

### ISSUE THREAD

**Issue by lulorobb** [Mikubill/sd-webui-controlnet#908]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When I give controlnet a video input, the pose of my character remains totally static throughout the duration of the video. I see that in the "detected_maps" folder the skeleton is animated perfectly, but it is not transmitted to the output images, any idea? I think I tried everything.
![Imagen 509](https://user-images.githubusercontent.com/130868837/232984138-bf8f3799-1051-4f4c-bbc0-e420ea955359.png)
![Imagen 510](https://user-images.githubusercontent.com/130868837/232984144-b465860f-bf2c-4512-9253-3095e9f02a8d.png)

### Steps to reproduce the problem

1. Go to deforum
2. promt "robot dancing in the dark in the style of Travis Charest, monochromatic, black & white, high contrast" (with JSON format)
3. init: some init image created in midjourney of a robot dancing (strength 0,5)
4. controlnet. Openpose, input my video of a guy dancing.
5. generate.

### What should have happened?

generate a sequence of images where each one respects the detected map that corresponds to it

### Commit where the problem happens

webui: [22bcc7be]
controlnet: 55a6fcb0

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
@echo off

set PYTHON="C:\Users\Luciano\AppData\Local\Programs\Python\Python38\python.exe"
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS= --xformers
git pull
call webui.bat
```

### Console logs

```Shell
https://pastebin.com/0dtmCyM0
```

### Additional information

I had the same problem with the non deforum version of controlnet and it fixed itself eventually. I think it had something to do with disabling the low ram option, but now even doing that doesn't change anything.

**Comment by lllyasviel** [comment]
anyone has ideas?

**Comment by p0mad** [comment]
@lllyasviel @lulorobb 
is this fixed?
Thanks
Best regards
