### ISSUE TITLE
is it possible to provide and folder and do batch generation with control net

### ISSUE THREAD

**Issue by demirklvc** [Mikubill/sd-webui-controlnet#91]
is it possible to provide and folder and do batch generation with control net? lets say i choose depth model and want to run like 30 images trhough the same settings.

**Comment by FizzleDorf** [comment]
#61 and #74 are already open. #61 has the fix for batch img2img. It also works in gif2gif.

**Comment by demirklvc** [comment]
thanks for pointing this out to me!
