### ISSUE TITLE
Why sometimes I need to click generate two times to change preprocessor

### ISSUE THREAD

**Issue by lllyasviel** [Mikubill/sd-webui-controlnet#937]
sometime I cannot remove the image to disable cnet
sometimes after I change preprocessor, the result does not change. I need to generate two times to see the change
is that again annoying gradio problems or we mess anything up?

**Comment by Mikubill** [comment]
Maybe related: https://github.com/Mikubill/sd-webui-controlnet/pull/841

**Comment by ljleb** [comment]
Actually, one solution could be to use placeholder values from the ui, say `object()` or a new class `UiControlNetPlaceHolder()`, and then replace them with actual units when calling `external_code.get_all_units_from(args)`. We need a way to wait for the gradio update to finish before reading the values from a global list i.e. `global_state.ui_cn_units` and I am not sure whether this is possible.

**Comment by lllyasviel** [comment]
https://github.com/Mikubill/sd-webui-controlnet/pull/942 seems fixed
