### ISSUE TITLE
[Suggestion]: New controlnet model to colorise photos, workflow suggestion to merge with original hires luminance grayscale image

### ISSUE THREAD

**Issue by 2blackbar** [Mikubill/sd-webui-controlnet#946]
This model already works in webui so its more about the workflow with colorising models similar to this one

I think implementation would work better if colorised image would be merged with original grayscale image using  resolution of original grayscale picture and its luminance , of course we first must match histogram low point and high point (works best) this way we get hires output , color doesnt have to be super hires to work fine, high resolution luminance channel can make it look hires.

since image speak louder than words, here is a detail difference between not merging with original image and with merged one , the colorised image with color data  is the same one on first 2 pics ,luminance channel from original graysucale pic is applied later in gimp manually which is tedious with many pics.This suggestion is a remedy for that.

So first image is output from auto11 and res of 768x768, below it is merged with luminance from original, and last one is grayscale original  before colorisation

![image](https://user-images.githubusercontent.com/33694664/233594081-1d1244a4-8929-4758-9bc3-cac9bbc4d718.png)

And by using original grayscale image resolution i dont mean generating colorisation at this resolution, we should be able to generate at lower res still but also would be nice to generate at original image res as well so its not locked to one or the other, sometimes images are too high res to generate colorisation and lower res is enough cause we can merge it with hires luminance from original res.
Do you guys think something like fullscale colorise can be done using this techniqe of merging luminance with coloriused output from colorise models ?
That would save time so we dont have to merge all colorised images with original grayscale hires images on our own.

https://www.reddit.com/r/StableDiffusion/comments/12ttajy/trained_a_new_controlnet_for_coloring_grayscale/

### Steps to reproduce the problem

.

### What should have happened?

.

### Commit where the problem happens

webui: x
controlnet: x

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
.
```

### Console logs

```Shell
.
```

**Comment by lllyasviel** [comment]
a bit concerned with preprocessor name. if the name is gery then it is correct but peoplo do not know it is coloring. if the name is coloring then it is wrong since it make images grey. Also if model names are colorization then preprocessor should be consistent. but the preprocessor does not colorize images. it grey images

**Comment by ljleb** [comment]
Yeah the name should be greyscale. I think it will be hard to enforce in the community, unless we tell model creators how we intend to use the hints from the model name.

The sooner we read from model names to automatically chose a preprocessor, the sooner the community will understand the purpose of the naming convention.

**Comment by lllyasviel** [comment]
I am going to close this and feel free to discuss in https://github.com/Mikubill/sd-webui-controlnet/issues/946
