### ISSUE TITLE
ControlNet masks are always blank and have no effect on the final image

### ISSUE THREAD

**Issue by ezynda3** [Mikubill/sd-webui-controlnet#95]
![image](https://user-images.githubusercontent.com/5308871/219366152-99324221-5473-43d8-a7a7-667931eff8be.png)
![image](https://user-images.githubusercontent.com/5308871/219366229-2d9a1109-b15d-48e4-9c9d-36694b60cdd3.png)
![image](https://user-images.githubusercontent.com/5308871/219366312-8794a54d-44a9-4789-adfc-94bd8fdf25c6.png)

Not sure what the issue is. Using a runpod instance with RTX A5000 29GB ram

**Comment by Mikubill** [comment]
Non-zero canvas + external image will result in the issue. Ensure that the canvas is empty if you want to upload image as input.

**Comment by ezynda3** [comment]
So the canvas is completely empty. I've tried clicking to upload the image as well as copy pasting the image to canvas. Neither actually work...

**Comment by andr8337** [comment]
Having the same issue, using 1.5 SD model with fresh instance of Automatic1111.
![1](https://user-images.githubusercontent.com/57616238/219374679-b9f198dc-c648-47e5-927e-8152829c6caa.png)
![2](https://user-images.githubusercontent.com/57616238/219374685-00cb4648-7917-449f-bf9e-fd79259deaef.png)

**Comment by Mikubill** [comment]
Couldn't reproduce. Maybe something like browser compatibility?

**Comment by ezynda3** [comment]
Ok weird but it seems like it doesn't work in Brave browser but does in Chrome...

**Comment by MegaScience** [comment]
Interesting. Does CanvasBlocker allow whitelisting certain domains so it will not act on them? Depending on the implementation, that might not be enough, but I'm just curious. A quick look around, I'm having trouble figuring out if that's possible.

**Comment by andr8337** [comment]
In my short testing it seems to need total disabling in settings, not just turned off. So a whitelist properly won't be enough.

**Comment by ilahazs** [comment]
Yeah, can't load it while using brave browser

**Comment by sygi** [comment]
Fwiw, for me it doesn't work on Chrome either, but your suggestion that it's due to extensions made me try it in the incognito mode, where it works fine. In my case, the extension that caused it to fail was [Crumbs](https://chrome.google.com/webstore/detail/crumbs-keep-your-data-saf/akommlakkhgbjbidpkkdcgbjgbeemdik).

**Comment by DanielSpacek** [comment]
I am having the same issue, that it generates white empty mask,  but only with MSLD preprocessor, canny and others work as expected. Anyone experiencing same issue?

**Comment by neo-js** [comment]
So, I've been fighting this issue all last week and I've came to the conclusion that it does not work unless accessing from localhost or 127.0.0.1.  Any domain names or even the Gradio proxy url will cause it to fail.  I am using Brave and was able to fix the issue by putting the Shields Down/Trusting my domain url.
