### ISSUE TITLE
[New  Change in UI] Preview size is finally fixed

### ISSUE THREAD

**Issue by lllyasviel** [Mikubill/sd-webui-controlnet#954]
Now the size of preview will not suddenly mess your webui

it looks like this
![image](https://user-images.githubusercontent.com/19834515/233631487-2f261ab0-1926-4de1-8ef2-8d2124a75f24.png)

pretty neat

**Comment by lllyasviel** [comment]
before this update, the preview is always suddenly too big or too small, constantly mess up the webui and users need to scroll up and down

now it is fixed!

thanks gradio's magic numbers

**Comment by iamddtla0620** [comment]
After updating to the latest version, the "explosion button" for the preview image disappeared. How to solve it?
![Uploading 缺乏預覽的爆炸按鈕.png…]()

**Comment by lllyasviel** [comment]
> After updating to the latest version, the "explosion button" for the preview image disappeared. How to solve it?

check allow preview

**Comment by iamddtla0620** [comment]
Thank you, it has been solved!

**Comment by jiadabao666** [comment]
> > 更新到最新版本后，预览图像的“爆炸按钮”消失了。如何解决？
> 
> 选中允许预览

After I updated it, it was still the old version of UI
<img width="706" alt="屏幕截图 2023-04-23 142946" src="https://user-images.githubusercontent.com/130242699/233823699-83545948-4211-4aa2-bb22-8fb82cad56b0.png">
