### ISSUE TITLE
[Feature Request] Add ControlNet variables into XYZ script 

### ISSUE THREAD

**Issue by hassan-sd** [Mikubill/sd-webui-controlnet#96]
**Summary**
When using controlnet, we can adjust multiple parameters so to find the "sweet spot" it can take some tweaking. It's a bit of hassle running a generation each time after you tweak a value.

**Request**
Add support for all controlnet variables into the XYZ plot script:

- Preprocessor/Model
- Weight
- Resize Mode
- etc

**Comment by demirklvc** [comment]
very much needed!

**Comment by Mikubill** [comment]
Finished in https://github.com/Mikubill/sd-webui-controlnet/pull/171

**Comment by shihanqu** [comment]
This issue isn't resolved though. The "[ControlNet] Model" option for X/Y/Z plot isn't useful, because we can't define Model and Preprocessor pairs.
