### ISSUE TITLE
[Bug]: I am using controlnet on colab but none of preprocessor working

### ISSUE THREAD

**Issue by doctord98618** [Mikubill/sd-webui-controlnet#975]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I was using preprocessor in local machine and they all working fine, but when I tried it on google colab machine they all look bad and wrong, canny is all black and open pose is also black
![Capture](https://user-images.githubusercontent.com/43003547/233796956-7bc9ab2c-d2d1-41e9-a83d-9a8b07978c27.PNG)

### Steps to reproduce the problem

1 installed automatic1111 
2 installed controlnet from this git via extension 
3 restart. webui  

### What should have happened?

should have generated this, this is from my local machine
![Capture3](https://user-images.githubusercontent.com/43003547/233797038-c668b4ce-7f64-4f53-885f-4a9020c32dc9.PNG)

### Commit where the problem happens

webui: 22bcc7b
controlnet: 68e4acf7c9ae899fd073df9cc3712cf0b7cb249d

### What browsers do you use to access the UI ?

Brave

### Command Line Arguments

```Shell
!COMMANDLINE_ARGS="--share --disable-safe-unpickle --no-half-vae --xformers --reinstall-xformers --enable-insecure-extension-access" REQS_FILE="requirements.txt" python launch.py
```

### Console logs

```Shell
Python 3.9.16 (main, Dec  7 2022, 01:11:51) 
[GCC 9.4.0]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Installing xformers
Installing requirements for Web UI

Launching Web UI with arguments: --share --disable-safe-unpickle --no-half-vae --xformers --reinstall-xformers --enable-insecure-extension-access
2023-04-22 17:08:34.627772: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-22 17:08:36.617984: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Loading weights [32c4949218] from /content/stable-diffusion-webui/models/Stable-diffusion/V08_V08.safetensors
Creating model from config: /content/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(15): bad-hands-5, bad-artist-anime, ulzzang-6500, badhandv4, bad_prompt, HyperStylizeV6, bad_prompt_version2, ng_deepnegative_v1_75t, bad-artist, pureerosface_v1, easynegative, bad-picture-chill-75v, charturnerv2, ulzzang-6500-v1.1, bad-image-v2-39000
Textual inversion embeddings skipped(4): nartfixer, nfixer, nrealfixer, 21charturnerv2
Model loaded in 23.0s (load weights from disk: 1.2s, create model: 0.9s, apply weights to model: 11.7s, apply half(): 1.4s, load VAE: 7.1s, move model to device: 0.6s).
Running on local URL:  http://127.0.0.1:7860/
Running on public URL: https://d6d36348faf6c898ca.gradio.live/

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
Startup time: 45.3s (import torch: 9.2s, import gradio: 1.7s, import ldm: 2.2s, other imports: 2.0s, setup codeformer: 0.2s, load scripts: 1.0s, load SD checkpoint: 23.1s, create ui: 1.7s, gradio launch: 4.2s).
ControlNet preprocessor location: /content/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
```

**Comment by lllyasviel** [comment]
not sure what happened. but considering google's recent news about banning a1111 in colab, this may be more complicated. but we will take a look

**Comment by doctord98618** [comment]
> not sure what happened. but considering google's recent news about banning a1111 in colab, this may be more complicated. but we will take a look
Yes they banned the word "stable-diffusion-webui", so I cloned the git with different name

**Comment by lllyasviel** [comment]
update and restart completely and see if fixed

**Comment by doctord98618** [comment]
> update and restart completely and see if fixed

still not working

**Comment by doctord98618** [comment]
![image (5)](https://user-images.githubusercontent.com/43003547/233827168-4972fbcc-998a-4b39-8d7d-fe7ce7ab2795.png)

**Comment by NovaGaming1964** [comment]
![image](https://user-images.githubusercontent.com/40416745/233874561-d7208c5b-1d08-4062-ba0f-68639b2b9cf9.png)
 with preprocessor none , the image is full black.
 
 its working fine in my PC , my pc has 3.10.9 Python and colab has 3.9.16 . It it the reason ?

**Comment by NovaGaming1964** [comment]
> ![image](https://user-images.githubusercontent.com/40416745/233874561-d7208c5b-1d08-4062-ba0f-68639b2b9cf9.png) with preprocessor none , the image is full black.
> 
> its working fine in my PC , my pc has 3.10.9 Python and colab has 3.9.16 . It it the reason ?

Found the cause , It was brave browser that was messing with the system and producing black images , i changed the browser to edge and it started working

**Comment by herbzhao** [comment]
> 
This is the same behaviour on my local deployment. good that i found this. Chrome not working, edge yes.
