### ISSUE TITLE
[Bug]: [Controlnet 1.1] The use of normal maps in Inpaint mode is not ideal. 

### ISSUE THREAD

**Issue by woszma** [Mikubill/sd-webui-controlnet#983]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I have encountered a problem where when using a normal map in Inpaint, the mask applied in Inpaint will directly affect the normal map and indirectly change the normals of the original image, which is not desirable. I hope to restore the normal map to its original state.

Here is an example. I used AI to make my cat smile:
<img width="1439" alt="螢幕截圖 2023-04-23 下午5 59 40" src="https://user-images.githubusercontent.com/56037559/233833405-030bab6c-fcd5-4fec-a994-053c1de2097d.png">

Preview normal map from the preprocessor:
![image (12)](https://user-images.githubusercontent.com/56037559/233833431-66bf19cb-9230-4c89-9a89-1f183b8faf77.png)

Output normal map:
![tmpf1_gbdgy](https://user-images.githubusercontent.com/56037559/233833442-d998aa40-a772-4caa-bb02-97962ebedc2a.png)

As you can see, the contour of the nose is very different, and there are also problems with the edge position, which makes it difficult for the edge of the original image and the mask to blend well.

Here are the final output image I made by the old version of ControlNet:
![23](https://user-images.githubusercontent.com/56037559/233833544-804c1618-f31f-4637-881a-4658fd97476f.png)

And the output by new version of ControlNet:
![image](https://user-images.githubusercontent.com/56037559/233833688-6c33e44c-52d3-49a7-9d5f-75a654041cde.png)

PS. other maps like depth map also have same issue. 

### Steps to reproduce the problem

1. go to inpaint upload and mask a area
![sormo_meme12](https://user-images.githubusercontent.com/56037559/233833762-77db5729-cbe0-49b7-87a4-83d2df61a207.png)

2. enable the control net, select normalbae preprocessor& model , add this image and preview
![meme_white](https://user-images.githubusercontent.com/56037559/233833791-fd233f78-b6d9-47fb-805e-7000b4cc2e6c.png)

3. generate and see the result

### What should have happened?

the normal map should be used the full size image as the source image

### Commit where the problem happens

webui: A1111(3/29)
controlnet: https://github.com/Mikubill/sd-webui-controlnet

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
non
```

**Comment by lllyasviel** [comment]
fixed https://github.com/Mikubill/sd-webui-controlnet/commit/5eadd24830d05ae2eaeeb600632964d407d0b730
update and restart completely

**Comment by lllyasviel** [comment]
I am going to close this. let me know if u want to reopen it
