### ISSUE TITLE
[Bug]: Recent changes in inpaint masking degrades quality of inpainting result

### ISSUE THREAD

**Issue by cheetahchicken** [Mikubill/sd-webui-controlnet#985]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Recent changes in inpaint masking degrades quality of inpainting by not including outer pixels when rendering the annotator image.

Here is an example difference of annotator out put for the following image and masked area. I am using a "masked padding" of 128 and the new masking for controlnet annotators seems to be ignoring it:

## Input
|original|mask|
|--|--
|![unmasked](https://user-images.githubusercontent.com/126948902/233835812-957c4049-59a3-406d-8f21-4a4359c2e5a0.PNG)|![masked](https://user-images.githubusercontent.com/126948902/233835825-5bb6cef8-1e85-4838-aa18-905cbfdca42d.PNG)

## Annotator Output
|commit|02e2a6d|main|
|--|--|--|
|openpose|![tmp250f3e6c](https://user-images.githubusercontent.com/126948902/233835337-d1f746e9-4c8e-4dbd-beaf-00da66e91f63.png)|![tmp6mdj4vos](https://user-images.githubusercontent.com/126948902/233835576-4dedff79-0071-4da5-ae27-7722964afb1f.png)
|depth|![tmpj0fc9kqe](https://user-images.githubusercontent.com/126948902/233835340-50e7021a-8a07-4b22-8f41-e9a7af37f873.png)|![tmp4dn5hhfn](https://user-images.githubusercontent.com/126948902/233835580-cb8813a6-d3d8-48f0-87a4-c59d576f0239.png)

This seems to have a negative influence on inpainting masked features such as "Only masked padding pixels" which helps guide the inpaint by allowing pixels outside the mask to influence the render.

### Steps to reproduce the problem

1. go to img2img inpaint
2. pick masked only with a large padding

### What should have happened?

The annotator should included padded pixels in generating the result.

### Commit where the problem happens

webui: latest
controlnet: latest commit after merges of "fix a1111 mask implementation" prs

### Command Line Arguments

```Shell
none
```

### Console logs

```Shell
N/A
```

### Additional information

I'm sure the change is intentional, but I rather liked the old behavior as the inpainting annotators like openpose would generate a proper full pose, but only apply to the masked area. Now openpose fails to generate anything when the masked area is only a part of a body. I get many black/blank annotations when masking individual body parts for inpainting with the new masking behavior, where as before a pose would always be generated, but the result was obviously still cropped.

**Comment by lllyasviel** [comment]
no it is not intentional. i will take a look

**Comment by lllyasviel** [comment]
fixed https://github.com/Mikubill/sd-webui-controlnet/commit/5eadd24830d05ae2eaeeb600632964d407d0b730
update and restart completely

**Comment by lllyasviel** [comment]
I am going to close this. let me know if u want to reopen it
