### ISSUE TITLE
[Bug]: error when inpainting ControlNet v1.1.02

### ISSUE THREAD

**Issue by demirklvc** [Mikubill/sd-webui-controlnet#994]
This happens when i use global harmonius inpaint:

Error running postprocess: C:\Users\RTX01\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.pys]
Traceback (most recent call last):
  File "C:\Users\RTX01\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 3080, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
KeyError: ((1, 1, 3), '<f4')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\RTX01\stable-diffusion-webui\modules\scripts.py", line 365, in postprocess
    script.postprocess(p, processed, *script_args)
  File "C:\Users\RTX01\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1059, in postprocess
    img = Image.fromarray(detect_map)
  File "C:\Users\RTX01\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 3083, in fromarray
    raise TypeError(msg) from e
TypeError: Cannot handle this data type: (1, 1, 3), <f4

### Steps to reproduce the problem

Mask area in img 2 img/inpaint tab, click generate. 

### What should have happened?

no detectmap/input.

### Commit where the problem happens

webui: 
controlnet: 

### Command Line Arguments

```Shell
-
```

### Console logs

```Shell
-
```

**Comment by demirklvc** [comment]
help would be appreciated, would love to use the new inpainting.

**Comment by lllyasviel** [comment]
how you use it? do you have screen shoot

**Comment by demirklvc** [comment]
<img width="1440" alt="Bildschirmfoto 2023-04-24 um 00 16 36" src="https://user-images.githubusercontent.com/78754525/233869061-96cfeda1-54ac-46c7-be52-6a694c5844a9.png">
<img width="1440" alt="Bildschirmfoto 2023-04-24 um 00 16 43" src="https://user-images.githubusercontent.com/78754525/233869067-cf2be1e3-c4fa-4e72-8bad-7620f6a86833.png">
<img width="1440" alt="Bildschirmfoto 2023-04-24 um 00 16 48" src="https://user-images.githubusercontent.com/78754525/233869068-1bc5224c-c193-4c4c-9b1b-ddbacd824bde.png">

**Comment by demirklvc** [comment]
@lllyasviel thanks for trying to help.

**Comment by lllyasviel** [comment]
any error logs?

**Comment by lllyasviel** [comment]
ah i see. will take a look. can use try another image and  see if that is problem with only one image or all images

**Comment by demirklvc** [comment]
> ah i see. will take a look. can use try another image and see if that is problem with only one image or all images

already did. the problem is also with other images.

**Comment by lllyasviel** [comment]
this problem is fixed in 1.1.08

**Comment by demirklvc** [comment]
thanks so much!!
